name: 'Proud Peach'
description: 'A simple medical register online application.'
version: 0.1.0-alpha
link: 'https://github.com/Nereare/proud-peach'
license:
    code: MIT
    name: 'Licensa MIT'
    link: 'https://opensource.org/licenses/MIT'
author:
    name: 'Igor Padoim'
    email: igorpadoim@gmail.com
    link: 'https://nereare.github.io'
