INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('A00', 'Cólera', 'A00 Colera'),
  ('A000', 'Cólera devida a Vibrio cholerae 01, biótipo cholerae', 'A00.0 Colera dev Vibrio cholerae 01 biot cholerae'),
  ('A001', 'Cólera devida a Vibrio cholerae 01, biótipo El Tor', 'A00.1 Colera dev Vibrio cholerae 01 biot El Tor'),
  ('A009', 'Cólera não especificada', 'A00.9 Colera NE'),
  ('A01', 'Febres tifóide e paratifóide', 'A01 Febres tifoide e paratifoide'),
  ('A010', 'Febre tifóide', 'A01.0 Febre tifoide'),
  ('A011', 'Febre paratifóide A', 'A01.1 Febre paratifoide A'),
  ('A012', 'Febre paratifóide B', 'A01.2 Febre paratifoide B'),
  ('A013', 'Febre paratifóide C', 'A01.3 Febre paratifoide C'),
  ('A014', 'Febre paratifóide não especificada', 'A01.4 Febre paratifoide NE'),
  ('A02', 'Outras infecções por Salmonella', 'A02 Outr infecc p/Salmonella'),
  ('A020', 'Enterite por salmonela', 'A02.0 Enterite p/salmonela'),
  ('A021', 'Septicemia por salmonela', 'A02.1 Septicemia p/salmonela'),
  ('A022', 'Infecções localizadas por salmonela', 'A02.2 Infecc localizadas p/salmonela'),
  ('A028', 'Outras infecções especificadas por salmonela', 'A02.8 Outr infecc espec p/salmonela'),
  ('A029', 'Infecção não especificada por salmonela', 'A02.9 Infecc NE p/salmonela'),
  ('A03', 'Shiguelose', 'A03 Shiguelose'),
  ('A030', 'Shiguelose devida a Shigella dysenteriae', 'A03.0 Shiguelose dev Shigella dysenteriae'),
  ('A031', 'Shiguelose devida a Shigella flexneri', 'A03.1 Shiguelose dev Shigella flexneri'),
  ('A032', 'Shiguelose devida a Shigella boydii', 'A03.2 Shiguelose dev Shigella boydii'),
  ('A033', 'Shiguelose devida a Shigella sonnei', 'A03.3 Shiguelose dev Shigella sonnei'),
  ('A038', 'Outras shigueloses', 'A03.8 Outr shigueloses'),
  ('A039', 'Shiguelose não especificada', 'A03.9 Shiguelose NE'),
  ('A04', 'Outras infecções intestinais bacterianas', 'A04 Outr infecc intestinais bacter'),
  ('A040', 'Infecção por Escherichia coli enteropatogênica', 'A04.0 Infecc p/Escherichia coli enteropatogenica'),
  ('A041', 'Infecção por Escherichia coli enterotoxigênica', 'A04.1 Infecc p/Escherichia coli enterotoxigenica'),
  ('A042', 'Infecção por Escherichia coli enteroinvasiva', 'A04.2 Infecc p/Escherichia coli enteroinvasiva'),
  ('A043', 'Infecção por Escherichia coli enterohemorrágica', 'A04.3 Infecc p/Escherichia coli enterohemorragica'),
  ('A044', 'Outras infecções intestinais por Escherichia coli', 'A04.4 Outr infecc intestinais p/Escherichia coli'),
  ('A045', 'Enterite por Campylobacter', 'A04.5 Enterite p/Campylobacter'),
  ('A046', 'Enterite devida a Yersinia enterocolítica', 'A04.6 Enterite dev Yersinia enterocolitica'),
  ('A047', 'Enterocolite devida a Clostridium difficile', 'A04.7 Enterocolite dev Clostridium difficile'),
  ('A048', 'Outras infecções bacterianas intestinais especificadas', 'A04.8 Outr infecc bacter intestinais espec'),
  ('A049', 'Infecção intestinal bacteriana não especificada', 'A04.9 Infecc intestinal bacter NE'),
  ('A05', 'Outras intoxicações alimentares bacterianas, não classificadas em outra parte', 'A05 Outr intox alimentares bacter NCOP'),
  ('A050', 'Intoxicação alimentar estafilocócica', 'A05.0 Intox alimentar estafilococica'),
  ('A051', 'Botulismo', 'A05.1 Botulismo'),
  ('A052', 'Intoxicação alimentar devida a Clostridium perfringens (Clostridium welchii)', 'A05.2 Intox alimentar dev Clostridium perfringens'),
  ('A053', 'Intoxicação alimentar devida a Vibrio parahemolyticus', 'A05.3 Intox alimentar dev Vibrio parahemolyticus'),
  ('A054', 'Intoxicação alimentar devida a Bacillus cereus', 'A05.4 Intox alimentar dev Bacillus cereus'),
  ('A058', 'Outras intoxicações alimentares bacterianas especificadas', 'A05.8 Outr intox alimentares bacter espec'),
  ('A059', 'Intoxicação alimentar bacteriana não especificada', 'A05.9 Intox alimentar bacter NE'),
  ('A06', 'Amebíase', 'A06 Amebiase'),
  ('A060', 'Disenteria amebiana aguda', 'A06.0 Disenteria amebiana aguda'),
  ('A061', 'Amebíase intestinal crônica', 'A06.1 Amebiase intestinal cronica'),
  ('A062', 'Colite amebiana não-disentérica', 'A06.2 Colite amebiana nao-disenterica'),
  ('A063', 'Ameboma intestinal', 'A06.3 Ameboma intestinal'),
  ('A064', 'Abscesso amebiano do fígado', 'A06.4 Abscesso amebiano do figado'),
  ('A065', 'Abscesso amebiano do pulmão', 'A06.5 Abscesso amebiano do pulmao'),
  ('A066', 'Abscesso amebiano do cérebro', 'A06.6 Abscesso amebiano do cerebro'),
  ('A067', 'Amebíase cutânea', 'A06.7 Amebiase cutanea'),
  ('A068', 'Infecção amebiana de outras localizações', 'A06.8 Infecc amebiana de outr localiz'),
  ('A069', 'Amebíase não especificada', 'A06.9 Amebiase NE'),
  ('A07', 'Outras doenças intestinais por protozoários', 'A07 Outr doenc intestinais p/protozoarios'),
  ('A070', 'Balantidíase', 'A07.0 Balantidiase'),
  ('A071', 'Giardíase (lamblíase)', 'A07.1 Giardiase'),
  ('A072', 'Criptosporidiose', 'A07.2 Criptosporidiose'),
  ('A073', 'Isosporíase', 'A07.3 Isosporiase'),
  ('A078', 'Outras doenças intestinais especificadas por protozoários', 'A07.8 Outr doenc intestinais espec p/protozoarios'),
  ('A079', 'Doença intestinal não especificada por protozoários', 'A07.9 Doenc intestinal NE p/protozoarios'),
  ('A08', 'Infecções intestinais virais, outras e as não especificadas', 'A08 Infecc intestinais virais outr e as NE'),
  ('A080', 'Enterite por rotavírus', 'A08.0 Enterite p/rotavirus'),
  ('A081', 'Gastroenteropatia aguda pelo agente de Norwalk', 'A08.1 Gastroenteropatia aguda p/agente de Norwalk'),
  ('A082', 'Enterite por adenovírus', 'A08.2 Enterite p/adenovirus'),
  ('A083', 'Outras enterites virais', 'A08.3 Outr enterites virais'),
  ('A084', 'Infecção intestinal devida a vírus não especificado', 'A08.4 Infecc intestinal dev virus NE'),
  ('A085', 'Outras infecções intestinais especificadas', 'A08.5 Outr infecc intestinais espec'),
  ('A09', 'Diarréia e gastroenterite de origem infecciosa presumível', 'A09 Diarreia e gastroenterite orig infecc presum'),
  ('A09', 'Diarréia e gastroenterite de origem infecciosa presumível', 'A09 Diarreia e gastroenterite orig infecc presum'),
  ('A15', 'Tuberculose respiratória, com confirmação bacteriológica e histológica', 'A15 Tuberc respirat c/conf bacteriol e histolog'),
  ('A150', 'Tuberculose pulmonar, com confirmação por exame microscópico da expectoração, com ou sem cultura', 'A15.0 Tuberc pulm c/conf p/ex micr expec c/s/cult'),
  ('A151', 'Tuberculose pulmonar, com confirmação somente por cultura', 'A15.1 Tuberc pulmonar c/conf somente p/cultura'),
  ('A152', 'Tuberculose pulmonar, com confirmação histológica', 'A15.2 Tuberc pulmonar c/conf histolog'),
  ('A153', 'Tuberculose pulmonar, com confirmação por meio não especificado', 'A15.3 Tuberc pulmonar c/conf p/meio NE'),
  ('A154', 'Tuberculose dos gânglios intratorácicos, com confirmação bacteriológica e histológica', 'A15.4 Tuberc gangl intrator c/conf bacter e histol'),
  ('A155', 'Tuberculose da laringe, da traquéia e dos brônquios, com confirmação bacteriológica e histológica', 'A15.5 Tuberc laring traq bronq c/conf bact e hist'),
  ('A156', 'Pleuris tuberculoso, com confirmação bacteriológica e histológica', 'A15.6 Pleuris tuberc c/conf bacteriol e histolog'),
  ('A157', 'Tuberculose primária das vias respiratórias, com confirmação bacteriológica e histológica', 'A15.7 Tuberc prim vias respir c/conf bact e histol'),
  ('A158', 'Outras formas de tuberculose das vias respiratórias, com confirmação bacteriológica e histológica', 'A15.8 Outr form tuberc via resp c/conf bact hist'),
  ('A159', 'Tuberculose não especificada das vias respiratórias, com confirmação bacteriológica e histológica', 'A15.9 Tuberc NE vias respir c/conf bacter histol'),
  ('A16', 'Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica', 'A16 Tuberc vias respirat s/conf bacter histol'),
  ('A160', 'Tuberculose pulmonar com exames bacteriológico e histológico negativos', 'A16.0 Tuberc pulmonar c/exames bact e hist negat'),
  ('A161', 'Tuberculose pulmonar, sem realização de exame bacteriológico ou histológico', 'A16.1 Tuberc pulmonar s/exame bacter ou histolog'),
  ('A162', 'Tuberculose pulmonar, sem menção de confirmação bacteriológica ou histológica', 'A16.2 Tuberc pulmonar s/menc conf bact ou hist'),
  ('A163', 'Tuberculose dos gânglios intratorácicos, sem menção de confirmação bacteriológica ou histológica', 'A16.3 Tuberc gangl intrat s/menc conf bact hist'),
  ('A164', 'Tuberculose da laringe, da traquéia e dos brônquios, sem menção de confirmação bacteriológica ou histológica', 'A16.4 Tuberc laring traq bronq s/menc bact hist'),
  ('A165', 'Pleurisia tuberculosa, sem menção de confirmação bacteriológica ou histológica', 'A16.5 Pleurisia tuberc s/menc conf bact ou histol'),
  ('A167', 'Tuberculosa respiratória primária sem menção de confirmação bacteriológica ou histológica', 'A16.7 Tuberc respir prim s/menc conf bact ou hist'),
  ('A168', 'Outras formas de tuberculose das vias respiratórias, sem menção de confirmação bacteriológica ou histológica', 'A16.8 Outr tuber via resp s/menc conf bact hist'),
  ('A169', 'Tuberculose respiratória, não especificada, sem menção de confirmação bacteriológica ou histológica', 'A16.9 Tuberc respirat NE s/menc conf bact ou hist'),
  ('A17', 'Tuberculose do sistema nervoso', 'A17 Tuberc do sist nervoso'),
  ('A170', 'Meningite tuberculosa', 'A17.0 Meningite tuberc'),
  ('A171', 'Tuberculoma meníngeo', 'A17.1 Tuberculoma meningeo'),
  ('A178', 'Outras tuberculoses do sistema nervoso', 'A17.8 Outr tuberc do sist nervoso'),
  ('A179', 'Tuberculose não especificada do sistema nervoso', 'A17.9 Tuberc NE do sist nervoso'),
  ('A18', 'Tuberculose de outros órgãos', 'A18 Tuberc de outr orgaos'),
  ('A180', 'Tuberculose óssea e das articulações', 'A18.0 Tuberc ossea e das articulacoes'),
  ('A181', 'Tuberculose do aparelho geniturinário', 'A18.1 Tuberc do aparelho geniturinario'),
  ('A182', 'Linfadenopatia tuberculosa periférica', 'A18.2 Linfadenopatia tuberc periferica'),
  ('A183', 'Tuberculose do intestino, do peritônio e dos gânglios mesentéricos', 'A18.3 Tuberc intestino peritonio gangl mesenter'),
  ('A184', 'Tuberculose de pele e do tecido celular subcutâneo', 'A18.4 Tuberc de pele e tec celular subcutaneo'),
  ('A185', 'Tuberculose do olho', 'A18.5 Tuberc do olho'),
  ('A186', 'Tuberculose do ouvido', 'A18.6 Tuberc do ouvido'),
  ('A187', 'Tuberculose das supra-renais', 'A18.7 Tuberc das supra-renais'),
  ('A188', 'Tuberculose de outros órgãos especificados', 'A18.8 Tuberc de outr orgaos espec'),
  ('A19', 'Tuberculose miliar', 'A19 Tuberc miliar'),
  ('A190', 'Tuberculose miliar aguda de localização única e especificada', 'A19.0 Tuberc miliar aguda de localiz unica espec'),
  ('A191', 'Tuberculose miliar aguda de múltiplas localizações', 'A19.1 Tuberc miliar aguda de mult localiz'),
  ('A192', 'Tuberculose miliar aguda não especificada', 'A19.2 Tuberc miliar aguda NE'),
  ('A198', 'Outras tuberculoses miliares', 'A19.8 Outr tuberc miliares'),
  ('A199', 'Tuberculose miliar não especificada', 'A19.9 Tuberc miliar NE'),
  ('A20', 'Peste', 'A20 Peste'),
  ('A200', 'Peste bubônica', 'A20.0 Peste bubonica'),
  ('A201', 'Peste celulocutânea', 'A20.1 Peste celulocutanea'),
  ('A202', 'Peste pneumônica', 'A20.2 Peste pneumonica'),
  ('A203', 'Peste meníngea', 'A20.3 Peste meningea'),
  ('A207', 'Peste septicêmica', 'A20.7 Peste septicemica'),
  ('A208', 'Outras formas de peste', 'A20.8 Outr form de peste'),
  ('A209', 'Peste, forma não especificada', 'A20.9 Peste form NE'),
  ('A21', 'Tularemia', 'A21 Tularemia'),
  ('A210', 'Tularemia ulceroglandular', 'A21.0 Tularemia ulceroglandular'),
  ('A211', 'Tularemia oculoglandular', 'A21.1 Tularemia oculoglandular'),
  ('A212', 'Tularemia pulmonar', 'A21.2 Tularemia pulmonar'),
  ('A213', 'Tularemia gastrointestinal', 'A21.3 Tularemia gastrointestinal'),
  ('A217', 'Tularemia generalizada', 'A21.7 Tularemia generalizada'),
  ('A218', 'Outras formas de tularemia', 'A21.8 Outr form de tularemia'),
  ('A219', 'Tularemia, forma não especificada', 'A21.9 Tularemia form NE'),
  ('A22', 'Carbúnculo', 'A22 Carbunculo'),
  ('A220', 'Carbúnculo cutâneo', 'A22.0 Carbunculo cutaneo'),
  ('A221', 'Carbúnculo pulmonar', 'A22.1 Carbunculo pulmonar'),
  ('A222', 'Carbúnculo gastrointestinal', 'A22.2 Carbunculo gastrointestinal'),
  ('A227', 'Septicemia carbunculosa', 'A22.7 Septicemia carbunculosa'),
  ('A228', 'Outras formas de carbúnculo', 'A22.8 Outr form de carbunculo'),
  ('A229', 'Carbúnculo, forma não especificada', 'A22.9 Carbunculo form NE'),
  ('A23', 'Brucelose', 'A23 Brucelose'),
  ('A230', 'Brucelose por Brucella melitensis', 'A23.0 Brucelose p/Brucella melitensis'),
  ('A231', 'Brucelose por Brucella abortus', 'A23.1 Brucelose p/Brucella abortus'),
  ('A232', 'Brucelose por Brucella suis', 'A23.2 Brucelose p/Brucella suis'),
  ('A233', 'Brucelose por Brucella canis', 'A23.3 Brucelose p/Brucella canis'),
  ('A238', 'Outras bruceloses', 'A23.8 Outr bruceloses'),
  ('A239', 'Brucelose não especificada', 'A23.9 Brucelose NE'),
  ('A24', 'Mormo e melioidose', 'A24 Mormo e melioidose'),
  ('A240', 'Mormo', 'A24.0 Mormo'),
  ('A241', 'Melioidose aguda e fulminante', 'A24.1 Melioidose aguda e fulminante'),
  ('A242', 'Melioidose subaguda e crônica', 'A24.2 Melioidose subaguda e cronica'),
  ('A243', 'Outras melioidoses', 'A24.3 Outr melioidoses'),
  ('A244', 'Melioidose não especificada', 'A24.4 Melioidose NE'),
  ('A25', 'Febres transmitidas por mordedura de rato', 'A25 Febres transm p/mordedura de rato'),
  ('A250', 'Espirilose', 'A25.0 Espirilose'),
  ('A251', 'Estreptobacilose', 'A25.1 Estreptobacilose'),
  ('A259', 'Febre transmitida por mordedura de rato, tipo não especificado', 'A25.9 Febre transm p/mordedura de rato tipo NE'),
  ('A26', 'Erisipelóide', 'A26 Erisipeloide'),
  ('A260', 'Erisipelóide cutâneo', 'A26.0 Erisipeloide cutaneo'),
  ('A267', 'Septicemia por Erysipelothrix', 'A26.7 Septicemia p/Erysipelothrix'),
  ('A268', 'Outras formas de erisipelóide', 'A26.8 Outr form de erisipeloide'),
  ('A269', 'Erisipelóide não especificado', 'A26.9 Erisipeloide NE'),
  ('A27', 'Leptospirose', 'A27 Leptospirose'),
  ('A270', 'Leptopirose icterohemorrágica', 'A27.0 Leptopirose icterohemorragica'),
  ('A278', 'Outras formas de leptospirose', 'A27.8 Outr form de leptospirose'),
  ('A279', 'Leptospirose não especificada', 'A27.9 Leptospirose NE'),
  ('A28', 'Outras doenças bacterianas zoonóticas não classificadas em outra parte', 'A28 Outr doenc bacter zoonoticas NCOP'),
  ('A280', 'Pasteurelose', 'A28.0 Pasteurelose'),
  ('A281', 'Doença por arranhadura do gato', 'A28.1 Doenc p/arranhadura do gato'),
  ('A282', 'Yersiniose extra-intestinal', 'A28.2 Yersiniose extra-intestinal'),
  ('A288', 'Outras doenças bacterianas zoonóticas especificadas não classificadas em outra parte', 'A28.8 Outr doenc bacter zoonoticas espec NCOP'),
  ('A289', 'Doença bacteriana zoonótica não especificada', 'A28.9 Doenc bacter zoonotica NE'),
  ('A30', 'Hanseníase (doença de Hansen) (lepra)', 'A30 Hanseniase'),
  ('A300', 'Hanseníase (lepra) indeterminada', 'A30.0 Hanseniase indeterminada'),
  ('A301', 'Hanseníase (lepra) tuberculóide', 'A30.1 Hanseniase tuberculoide'),
  ('A302', 'Hanseníase (lepra) tuberculóide borderline', 'A30.2 Hanseniase tuberculoide borderline'),
  ('A303', 'Hanseníase (lepra) dimorfa', 'A30.3 Hanseniase dimorfa'),
  ('A304', 'Hanseníase (lepra) lepromatosa borderline', 'A30.4 Hanseniase lepromatosa borderline'),
  ('A305', 'Hanseníase (lepra) lepromatosa', 'A30.5 Hanseniase lepromatosa'),
  ('A308', 'Outras formas de hanseníase (lepra)', 'A30.8 Outr form de hanseniase'),
  ('A309', 'Hanseníase (lepra) não especificada', 'A30.9 Hanseniase NE'),
  ('A31', 'Infecções devidas a outras micobactérias', 'A31 Infecc dev outr micobacterias'),
  ('A310', 'Infecção pulmonar micobacteriana', 'A31.0 Infecc pulmonar micobacteriana'),
  ('A311', 'Infecção cutânea micobacteriana', 'A31.1 Infecc cutanea micobacteriana'),
  ('A318', 'Outras infecções micobacterianas', 'A31.8 Outr infecc micobacterianas'),
  ('A319', 'Infecção micobacteriana não especificada', 'A31.9 Infecc micobacteriana NE'),
  ('A32', 'Listeriose (listeríase)', 'A32 Listeriose'),
  ('A320', 'Listeriose cutânea', 'A32.0 Listeriose cutanea'),
  ('A321', 'Meningite e meningoencefalite por listéria', 'A32.1 Meningite e meningoencefalite p/listeria'),
  ('A327', 'Septicemia listeriótica', 'A32.7 Septicemia listeriotica'),
  ('A328', 'Outras formas de listeriose', 'A32.8 Outr form de listeriose'),
  ('A329', 'Listeriose não especificada', 'A32.9 Listeriose NE'),
  ('A33', 'Tétano do recém-nascido (neonatal)', 'A33 Tetano do recem-nascido'),
  ('A33', 'Tétano do recém-nascido (neonatal)', 'A33 Tetano do recem-nascido'),
  ('A34', 'Tétano obstétrico', 'A34 Tetano obstetrico'),
  ('A34', 'Tétano obstétrico', 'A34 Tetano obstetrico'),
  ('A35', 'Outros tipos de tétano', 'A35 Outr tipos de tetano'),
  ('A35', 'Outros tipos de tétano', 'A35 Outr tipos de tetano'),
  ('A36', 'Difteria', 'A36 Difteria'),
  ('A360', 'Difteria faríngea', 'A36.0 Difteria faringea'),
  ('A361', 'Difteria nasofaríngea', 'A36.1 Difteria nasofaringea'),
  ('A362', 'Difteria laríngea', 'A36.2 Difteria laringea'),
  ('A363', 'Difteria cutânea', 'A36.3 Difteria cutanea'),
  ('A368', 'Outras formas de difteria', 'A36.8 Outr form de difteria'),
  ('A369', 'Difteria não especificada', 'A36.9 Difteria NE'),
  ('A37', 'Coqueluche', 'A37 Coqueluche'),
  ('A370', 'Coqueluche por Bordetella pertussis', 'A37.0 Coqueluche p/Bordetella pertussis'),
  ('A371', 'Coqueluche por Bordetella parapertussis', 'A37.1 Coqueluche p/Bordetella parapertussis'),
  ('A378', 'Coqueluche por outras espécies da Bordetella', 'A37.8 Coqueluche p/outr especies da Bordetella'),
  ('A379', 'Coqueluche não especificada', 'A37.9 Coqueluche NE'),
  ('A38', 'Escarlatina', 'A38 Escarlatina'),
  ('A38', 'Escarlatina', 'A38 Escarlatina'),
  ('A39', 'Infecção meningogócica', 'A39 Infecc meningogocica'),
  ('A390', 'Meningite meningocócica', 'A39.0 Meningite meningococica'),
  ('A391', 'Síndrome de Waterhouse-Friderichsen', 'A39.1 Sindr de Waterhouse-Friderichsen'),
  ('A392', 'Meningococcemia aguda', 'A39.2 Meningococcemia aguda'),
  ('A393', 'Meningococcemia crônica', 'A39.3 Meningococcemia cronica'),
  ('A394', 'Meningococcemia não especificada', 'A39.4 Meningococcemia NE'),
  ('A395', 'Cardite por meningococos', 'A39.5 Cardite p/meningococos'),
  ('A398', 'Outras infecções por meningococos', 'A39.8 Outr infecc p/meningococos'),
  ('A399', 'Infecção meningocócica não especificada', 'A39.9 Infecc meningococica NE'),
  ('A40', 'Septicemia estreptocócica', 'A40 Septicemia estreptococica'),
  ('A400', 'Septicemia por Streptococcus do grupo A', 'A40.0 Septicemia p/Streptococcus do grupo A'),
  ('A401', 'Septicemia por Streptococcus do grupo B', 'A40.1 Septicemia p/Streptococcus do grupo B'),
  ('A402', 'Septicemia por Streptococcus do grupo D', 'A40.2 Septicemia p/Streptococcus do grupo D'),
  ('A403', 'Septicemia por Streptococcus pneumonia', 'A40.3 Septicemia p/Streptococcus pneumonia'),
  ('A408', 'Outras septicemias estreptocócicas', 'A40.8 Outr septicemias estreptococicas'),
  ('A409', 'Septicemia estreptocócica não especificada', 'A40.9 Septicemia estreptococica NE'),
  ('A41', 'Outras septicemias', 'A41 Outr septicemias'),
  ('A410', 'Septicemia por Staphylococcus aureus', 'A41.0 Septicemia p/Staphylococcus aureus'),
  ('A411', 'Septicemia por outros estafilococos especificados', 'A41.1 Septicemia p/outr estafilococos espec'),
  ('A412', 'Septicemia por estafilococos não especificados', 'A41.2 Septicemia p/estafilococos NE'),
  ('A413', 'Septicemia por Haemophilus influenzae', 'A41.3 Septicemia p/Haemophilus influenzae'),
  ('A414', 'Septicemia por anaeróbios', 'A41.4 Septicemia p/anaerobios'),
  ('A415', 'Septicemia por outros microorganismos gram-negativos', 'A41.5 Septicemia p/outr microorg gram-negativos'),
  ('A418', 'Outras septicemias especificadas', 'A41.8 Outr septicemias espec'),
  ('A419', 'Septicemia não especificada', 'A41.9 Septicemia NE'),
  ('A42', 'Actinomicose', 'A42 Actinomicose'),
  ('A420', 'Actinomicose pulmonar', 'A42.0 Actinomicose pulmonar'),
  ('A421', 'Actinomicose abdominal', 'A42.1 Actinomicose abdominal'),
  ('A422', 'Actinomicose cervicofacial', 'A42.2 Actinomicose cervicofacial'),
  ('A427', 'Septicemia actinomicótica', 'A42.7 Septicemia actinomicotica'),
  ('A428', 'Outras formas de actinomicose', 'A42.8 Outr form de actinomicose'),
  ('A429', 'Actinomicose não especificada', 'A42.9 Actinomicose NE'),
  ('A43', 'Nocardiose', 'A43 Nocardiose'),
  ('A430', 'Nocardiose pulmonar', 'A43.0 Nocardiose pulmonar'),
  ('A431', 'Nocardiose cutânea', 'A43.1 Nocardiose cutanea'),
  ('A438', 'Outras formas de nocardiose', 'A43.8 Outr form de nocardiose'),
  ('A439', 'Nocardiose não especificada', 'A43.9 Nocardiose NE'),
  ('A44', 'Bartonelose', 'A44 Bartonelose'),
  ('A440', 'Bartonelose sistêmica', 'A44.0 Bartonelose sistemica'),
  ('A441', 'Bartonelose cutânea e cutâneo-mucosa', 'A44.1 Bartonelose cutanea e cutaneo-mucosa'),
  ('A448', 'Outras formas de bartonelose', 'A44.8 Outr form de bartonelose'),
  ('A449', 'Bartonelose não especificada', 'A44.9 Bartonelose NE'),
  ('A46', 'Erisipela', 'A46 Erisipela'),
  ('A46', 'Erisipela', 'A46 Erisipela'),
  ('A48', 'Outras doenças bacterianas não classificadas em outra parte', 'A48 Outr doenc bacter NCOP'),
  ('A480', 'Gangrena gasosa', 'A48.0 Gangrena gasosa'),
  ('A481', 'Doença dos legionários', 'A48.1 Doenc dos legionarios'),
  ('A482', 'Doença dos legionários não-pneumônica (febre de Pontiac)', 'A48.2 Doenc dos legionarios nao-pneumonica'),
  ('A483', 'Síndrome do choque tóxico', 'A48.3 Sindr do choque toxico'),
  ('A484', 'Febre purpúrica do Brasil', 'A48.4 Febre purpurica do Brasil'),
  ('A488', 'Outras doenças bacterianas especificadas', 'A48.8 Outr doenc bacter espec'),
  ('A49', 'Infecção bacteriana de localização não especificada', 'A49 Infecc bacter de localiz NE'),
  ('A490', 'Infecção estafilocócica de localização não especificada', 'A49.0 Infecc estafilococica localiz NE'),
  ('A491', 'Infecção estreptocócica de localização não especificada', 'A49.1 Infecc estreptococica localiz NE'),
  ('A492', 'Infecção por Haemophilus influenzae de localização não especificada', 'A49.2 Infecc p/Haemophilus influenzae localiz NE'),
  ('A493', 'Infecção por Mycoplasma de localização não especificada', 'A49.3 Infecc p/Mycoplasma localiz NE'),
  ('A498', 'Outras infecções bacterianas de localização não especificada', 'A49.8 Outr infecc bacterianas localiz NE'),
  ('A499', 'Infecção bacteriana não especificada', 'A49.9 Infecc bacter NE'),
  ('A50', 'Sífilis congênita', 'A50 Sifilis congen'),
  ('A500', 'Sífilis congênita precoce sintomática', 'A50.0 Sifilis congen precoce sintomatica'),
  ('A501', 'Sífilis congênita precoce, forma latente', 'A50.1 Sifilis congen precoce form latente'),
  ('A502', 'Sífilis congênita precoce não especificada', 'A50.2 Sifilis congen precoce NE'),
  ('A503', 'Oculopatia sifilítica congênita tardia', 'A50.3 Oculopatia sifilitica congen tard'),
  ('A504', 'Neurossífilis congênita tardia (neurossífilis juvenil)', 'A50.4 Neurossifilis congen tard'),
  ('A505', 'Outras formas tardias e sintomáticas da sífilis congênita', 'A50.5 Outr form tard e sintomat sifilis congen'),
  ('A506', 'Sífilis congênita tardia latente', 'A50.6 Sifilis congen tard latente'),
  ('A507', 'Sífilis congênita tardia não especificada', 'A50.7 Sifilis congen tard NE'),
  ('A509', 'Sífilis congênita não especificada', 'A50.9 Sifilis congen NE'),
  ('A51', 'Sífilis precoce', 'A51 Sifilis precoce'),
  ('A510', 'Sífilis genital primária', 'A51.0 Sifilis genital prim'),
  ('A511', 'Sífilis anal primária', 'A51.1 Sifilis anal prim'),
  ('A512', 'Sífilis primária de outras localizações', 'A51.2 Sifilis prim de outr localiz'),
  ('A513', 'Sífilis secundária da pele e das mucosas', 'A51.3 Sifilis secund da pele e das mucosas'),
  ('A514', 'Outras formas de sífilis secundária', 'A51.4 Outr form de sifilis secund'),
  ('A515', 'Sífilis precoce latente', 'A51.5 Sifilis precoce latente'),
  ('A519', 'Sífilis precoce não especificada', 'A51.9 Sifilis precoce NE'),
  ('A52', 'Sífilis tardia', 'A52 Sifilis tard'),
  ('A520', 'Sífilis cardiovascular', 'A52.0 Sifilis cardiovascular'),
  ('A521', 'Neurossífilis sintomática', 'A52.1 Neurossifilis sintomatica'),
  ('A522', 'Neurossífilis assintomática', 'A52.2 Neurossifilis assintomatica'),
  ('A523', 'Neurossífilis não especificada', 'A52.3 Neurossifilis NE'),
  ('A527', 'Outras formas de sífilis tardia sintomática', 'A52.7 Outr form de sifilis tard sintomatica'),
  ('A528', 'Sífilis tardia latente', 'A52.8 Sifilis tard latente'),
  ('A529', 'Sífilis tardia não especificada', 'A52.9 Sifilis tard NE'),
  ('A53', 'Outras formas e as não especificadas da sífilis', 'A53 Outr form e as NE da sifilis'),
  ('A530', 'Sífilis latente, não especificada se recente ou tardia', 'A53.0 Sifilis latente NE se recente ou tard'),
  ('A539', 'Sífilis não especificada', 'A53.9 Sifilis NE'),
  ('A54', 'Infecção gonocócica', 'A54 Infecc gonococica'),
  ('A540', 'Infecção gonocócica do trato geniturinário inferior, sem abscesso periuretral ou das glândulas acessórias', 'A54.0 Inf gon tr genit inf s/abs periur/gland aces'),
  ('A541', 'Infecção gonocócica do trato geniturinário inferior, com abscesso periuretral ou das glândulas acessórias', 'A54.1 Inf gon tr genit inf c/abs periur/gland aces'),
  ('A542', 'Pelviperitonite gonocócica e outras infecções geniturinárias gonocócicas', 'A54.2 Pelviperit gonoc e outr infecc genitur gonoc'),
  ('A543', 'Infecção gonocócica do olho', 'A54.3 Infecc gonococica do olho'),
  ('A544', 'Infecção gonocócica do sistema músculo-esquelético', 'A54.4 Infecc gonococica sist musculo-esqueletico'),
  ('A545', 'Faringite gonocócica', 'A54.5 Faringite gonococica'),
  ('A546', 'Infecção gonocócica do ânus ou do reto', 'A54.6 Infecc gonococica do anus ou do reto'),
  ('A548', 'Outras infecções gonocócicas', 'A54.8 Outr infecc gonococicas'),
  ('A549', 'Infecção gonocócica não especificada', 'A54.9 Infecc gonococica NE'),
  ('A55', 'Linfogranuloma (venéreo) por clamídia', 'A55 Linfogranuloma p/clamidia'),
  ('A55', 'Linfogranuloma (venéreo) por clamídia', 'A55 Linfogranuloma p/clamidia'),
  ('A56', 'Outras infecções causadas por clamídias transmitidas por via sexual', 'A56 Outr infecc p/clamidias transm p/via sexual'),
  ('A560', 'Infecções por clamídias do trato geniturinário inferior', 'A56.0 Infecc p/clamidias trato geniturinario infer'),
  ('A561', 'Infecção por clamídias, pelviperitonial e de outros órgãos geniturinários', 'A56.1 Infecc p/clamid pelviper e outr org genitur'),
  ('A562', 'Infecção por clamídias do trato geniturinário, localização não especificada', 'A56.2 Infecc p/clamidias trato genitur localiz NE'),
  ('A563', 'Infecção do ânus e do reto por clamídias', 'A56.3 Infecc do anus e do reto p/clamidias'),
  ('A564', 'Infecção da faringe por clamídias', 'A56.4 Infecc da faringe p/clamidias'),
  ('A568', 'Infecção por clamídias transmitida por via sexual, de outras localizações', 'A56.8 Infecc p/clamid transm p/via sex outr local'),
  ('A57', 'Cancro mole', 'A57 Cancro mole'),
  ('A57', 'Cancro mole', 'A57 Cancro mole'),
  ('A58', 'Granuloma inguinal', 'A58 Granuloma inguinal'),
  ('A58', 'Granuloma inguinal', 'A58 Granuloma inguinal'),
  ('A59', 'Tricomoníase', 'A59 Tricomoniase'),
  ('A590', 'Tricomoníase urogenital', 'A59.0 Tricomoniase urogenital'),
  ('A598', 'Outras localizações de tricomoníase', 'A59.8 Outr localiz de tricomoniase'),
  ('A599', 'Tricomoníase não especificada', 'A59.9 Tricomoniase NE'),
  ('A60', 'Infecções anogenitais pelo vírus do herpes (herpes simples)', 'A60 Infecc anogenitais p/virus do herpes'),
  ('A600', 'Infecção dos órgãos genitais e do trato geniturinário pelo vírus do herpes', 'A60.0 Infecc org genit trat genitur p/virus herpes'),
  ('A601', 'Infecção da margem cutânea do ânus e do reto pelo vírus do herpes', 'A60.1 Infecc margem cutan anus/reto p/virus herpes'),
  ('A609', 'Infecção anogenital não especificada pelo vírus do herpes', 'A60.9 Infecc anogenital NE p/virus do herpes'),
  ('A63', 'Outras doenças de transmissão predominantemente sexual, não classificadas em outra parte', 'A63 Outr doenc de transm predom sexual NCOP'),
  ('A630', 'Verrugas anogenitais (venéreas)', 'A63.0 Verrugas anogenitais'),
  ('A638', 'Outras doenças especificadas de transmissão predominantemente sexual', 'A63.8 Outr doenc espec de transm predom sexual'),
  ('A64', 'Doenças sexualmente transmitidas, não especificadas', 'A64 Doenc sexualmente transm NE'),
  ('A64', 'Doenças sexualmente transmitidas, não especificadas', 'A64 Doenc sexualmente transm NE'),
  ('A65', 'Sífilis não-venérea', 'A65 Sifilis nao-venerea'),
  ('A65', 'Sífilis não-venérea', 'A65 Sifilis nao-venerea'),
  ('A66', 'Bouba', 'A66 Bouba'),
  ('A660', 'Lesões iniciais da bouba', 'A66.0 Lesoes iniciais da bouba'),
  ('A661', 'Papilomas múltiplos e bouba plantar úmida (cravo de bouba)', 'A66.1 Papilomas mult e bouba plantar umida'),
  ('A662', 'Outras lesões cutâneas precoces da bouba', 'A66.2 Outr lesoes cutaneas precoces da bouba'),
  ('A663', 'Hiperceratose devida a bouba', 'A66.3 Hiperceratose dev bouba'),
  ('A664', 'Gomas e úlceras devidas à bouba', 'A66.4 Gomas e ulceras dev bouba'),
  ('A665', 'Gangosa', 'A66.5 Gangosa'),
  ('A666', 'Lesões osteoarticulares devidas à bouba', 'A66.6 Lesoes osteoarticulares dev bouba'),
  ('A667', 'Outras manifestações da bouba', 'A66.7 Outr manifestacoes da bouba'),
  ('A668', 'Bouba latente', 'A66.8 Bouba latente'),
  ('A669', 'Bouba não especificada', 'A66.9 Bouba NE'),
  ('A67', 'Pinta (carate)', 'A67 Pinta'),
  ('A670', 'Lesões primárias da pinta', 'A67.0 Lesoes prim da pinta'),
  ('A671', 'Lesões intermediárias da pinta', 'A67.1 Lesoes intermediarias da pinta'),
  ('A672', 'Lesões tardias da pinta', 'A67.2 Lesoes tard da pinta'),
  ('A673', 'Lesões mistas da pinta', 'A67.3 Lesoes mistas da pinta'),
  ('A679', 'Pinta não especificada', 'A67.9 Pinta NE'),
  ('A68', 'Febres recorrentes (Borrelioses)', 'A68 Febres recorrentes'),
  ('A680', 'Febre recorrente transmitida por piolhos', 'A68.0 Febre recorrente transm p/piolhos'),
  ('A681', 'Febre recorrente transmitida por carrapatos', 'A68.1 Febre recorrente transm p/carrapatos'),
  ('A689', 'Febre recorrente não especificada', 'A68.9 Febre recorrente NE'),
  ('A69', 'Outras infecções por espiroquetas', 'A69 Outr infecc p/espiroquetas'),
  ('A690', 'Estomatite ulcerativa necrotizante', 'A69.0 Estomatite ulcerativa necrotizante'),
  ('A691', 'Outras infecções de Vincent', 'A69.1 Outr infecc de Vincent'),
  ('A692', 'Doença de Lyme', 'A69.2 Doenc de Lyme'),
  ('A698', 'Outras infecções especificadas por espiroquetas', 'A69.8 Outr infecc espec p/espiroquetas'),
  ('A699', 'Infecção por espiroqueta, não especificada', 'A69.9 Infecc p/espiroqueta NE'),
  ('A70', 'Infecções causadas por Clamídia psittaci', 'A70 Infecc causadas p/Clamidia psittaci'),
  ('A70', 'Infecções causadas por Clamídia psittaci', 'A70 Infecc causadas p/Clamidia psittaci'),
  ('A71', 'Tracoma', 'A71 Tracoma'),
  ('A710', 'Fase inicial do tracoma', 'A71.0 Fase inicial do tracoma'),
  ('A711', 'Fase ativa do tracoma', 'A71.1 Fase ativa do tracoma'),
  ('A719', 'Tracoma não especificado', 'A71.9 Tracoma NE'),
  ('A74', 'Outras doenças causadas por Clamídias', 'A74 Outr doenc causadas p/Clamidias'),
  ('A740', 'Conjuntivite causada por clamídias', 'A74.0 Conjuntivite causada p/clamidias'),
  ('A748', 'Outras doenças causadas por clamídias', 'A74.8 Outr doenc causadas p/clamidias'),
  ('A749', 'Infecção causada por clamídias não especificada', 'A74.9 Infecc causada p/clamidias NE'),
  ('A75', 'Tifo exantemático', 'A75 Tifo exantematico'),
  ('A750', 'Tifo epidêmico transmitido por piolhos devido a Rickettsia prowazekii', 'A75.0 Tifo epidem transm p/piolhos R. prowazekii'),
  ('A751', 'Tifo recrudescente (doença de Brill)', 'A75.1 Tifo recrudescente'),
  ('A752', 'Tifo por Rickettsia typhi', 'A75.2 Tifo p/Rickettsia typhi'),
  ('A753', 'Tifo por Rickettsia tsutsugamuchi', 'A75.3 Tifo p/Rickettsia tsutsugamuchi'),
  ('A759', 'Tifo não especificado', 'A75.9 Tifo NE'),
  ('A77', 'Febre maculosa (rickettsioses transmitidas por carrapatos)', 'A77 Febre maculosa'),
  ('A770', 'Febre maculosa por Rickettsia richettsii', 'A77.0 Febre maculosa p/Rickettsia richettsii'),
  ('A771', 'Febre maculosa por Rickettsia conorii', 'A77.1 Febre maculosa p/Rickettsia conorii'),
  ('A772', 'Febre maculosa devida à Rickettsia siberica', 'A77.2 Febre maculosa dev Rickettsia siberica'),
  ('A773', 'Febre maculosa devida à Rickettsia australis', 'A77.3 Febre maculosa dev Rickettsia australis'),
  ('A778', 'Outras febres maculosas', 'A77.8 Outr febres maculosas'),
  ('A779', 'Febre maculosa não especificada', 'A77.9 Febre maculosa NE'),
  ('A78', 'Febre Q', 'A78 Febre Q'),
  ('A78', 'Febre Q', 'A78 Febre Q'),
  ('A79', 'Outras rickettsioses', 'A79 Outr rickettsioses'),
  ('A790', 'Febre das trincheiras', 'A79.0 Febre das trincheiras'),
  ('A791', 'Rickettsiose variceliforme devida à Rickettsia akari', 'A79.1 Rickettsiose variceliforme dev R.akari'),
  ('A798', 'Outros tipos de rickettsioses especificadas', 'A79.8 Outr tipos de rickettsioses espec'),
  ('A799', 'Rickettsiose não especificada', 'A79.9 Rickettsiose NE'),
  ('A80', 'Poliomielite aguda', 'A80 Poliomielite aguda'),
  ('A800', 'Poliomielite paralítica aguda, associada ao vírus vacinal', 'A80.0 Poliomielite paral aguda assoc virus vacinal'),
  ('A801', 'Poliomielite paralítica aguda, vírus selvagem importado', 'A80.1 Poliomiel paral aguda virus selvagem import'),
  ('A802', 'Poliomielite paralítica aguda, vírus selvagem indígena', 'A80.2 Poliomiel paral aguda virus selvagem indig'),
  ('A803', 'Poliomielites paralíticas agudas, outras e não especificadas', 'A80.3 Poliomielites paraliticas agudas outr e NE'),
  ('A804', 'Poliomielite aguda não-paralítica', 'A80.4 Poliomielite aguda nao-paralitica'),
  ('A809', 'Poliomielite aguda não especificada', 'A80.9 Poliomielite aguda NE'),
  ('A81', 'Infecções por vírus atípicos do sistema nervoso central', 'A81 Infecc p/virus atipicos sist nervoso central'),
  ('A810', 'Doença de Creutzfeldt-Jakob', 'A81.0 Doenc de Creutzfeldt-Jakob'),
  ('A811', 'Panencefalite esclerosante subaguda', 'A81.1 Panencefalite esclerosante subaguda'),
  ('A812', 'Leucoencefalopatia multifocal progressiva', 'A81.2 Leucoencefalopatia multifocal progressiva'),
  ('A818', 'Outras infecções por vírus atípicos do sistema nervoso central', 'A81.8 Outr infecc p/virus atipic sist nerv central'),
  ('A819', 'Infecção não especificada do sistema nervosos central por vírus atípicos', 'A81.9 Infecc NE sist nerv central p/virus atipicos'),
  ('A82', 'Raiva', 'A82 Raiva'),
  ('A820', 'Raiva silvestre', 'A82.0 Raiva silvestre'),
  ('A821', 'Raiva urbana', 'A82.1 Raiva urbana'),
  ('A829', 'Raiva não especificada', 'A82.9 Raiva NE'),
  ('A83', 'Encefalite por vírus transmitidos por mosquitos', 'A83 Encefalite p/virus transm p/mosquitos'),
  ('A830', 'Encefalite japonesa', 'A83.0 Encefalite japonesa'),
  ('A831', 'Encefalite eqüina ocidental', 'A83.1 Encefalite equina ocidental'),
  ('A832', 'Encefalite eqüina oriental', 'A83.2 Encefalite equina oriental'),
  ('A833', 'Encefalite de St. Louis', 'A83.3 Encefalite de St. Louis'),
  ('A834', 'Encefalite australiana', 'A83.4 Encefalite australiana'),
  ('A835', 'Encefalite da Califórnia', 'A83.5 Encefalite da California'),
  ('A836', 'Doença pelo vírus de Rocio', 'A83.6 Doenc p/virus de Rocio'),
  ('A838', 'Outras encefalites por vírus transmitidas por mosquitos', 'A83.8 Outr encefalites p/virus transm p/mosquitos'),
  ('A839', 'Encefalite não especificada por vírus transmitida por mosquitos', 'A83.9 Encefalite NE p/virus transm p/mosquitos'),
  ('A84', 'Encefalite por vírus transmitido por carrapatos', 'A84 Encefalite p/virus transm p/carrapatos'),
  ('A840', 'Encefalite da taiga (encefalite vernoestival russa)', 'A84.0 Encefalite da taiga'),
  ('A841', 'Encefalite da Europa Central transmitida por carrapatos', 'A84.1 Encefalite Europa Central transm p/carrapato'),
  ('A848', 'Outras encefalites por vírus transmitidas por carrapatos', 'A84.8 Outr encefalites p/virus transm p/carrapatos'),
  ('A849', 'Encefalite não especificada por vírus transmitida por carrapatos', 'A84.9 Encefalite NE p/virus transm p/carrapatos'),
  ('A85', 'Outras encefalites virais, não classificadas em outra parte', 'A85 Outr encefalites virais NCOP'),
  ('A850', 'Encefalite por enterovírus', 'A85.0 Encefalite p/enterovirus'),
  ('A851', 'Encefalite por adenovírus', 'A85.1 Encefalite p/adenovirus'),
  ('A852', 'Encefalite por vírus transmitido por artrópodes, não especificada', 'A85.2 Encefalite p/virus transm p/artropodes NE'),
  ('A858', 'Outras encefalites virais especificadas', 'A85.8 Outr encefalites virais espec'),
  ('A86', 'Encefalite viral, não especificada', 'A86 Encefalite viral NE'),
  ('A86', 'Encefalite viral, não especificada', 'A86 Encefalite viral NE'),
  ('A87', 'Meningite viral', 'A87 Meningite viral'),
  ('A870', 'Meningite por enterovírus', 'A87.0 Meningite p/enterovirus'),
  ('A871', 'Meningite por adenovírus', 'A87.1 Meningite p/adenovirus'),
  ('A872', 'Coriomeningite linfocitária', 'A87.2 Coriomeningite linfocitaria'),
  ('A878', 'Outras meningites virais', 'A87.8 Outr meningites virais'),
  ('A879', 'Meningite viral não especificada', 'A87.9 Meningite viral NE'),
  ('A88', 'Outras infecções virais do sistema nervoso central não classificadas em outra parte', 'A88 Outr infecc virais sist nervoso central NCOP'),
  ('A880', 'Febre exantemática por enterovírus (exantema de Boston)', 'A88.0 Febre exantematica p/enterovirus'),
  ('A881', 'Vertigem epidêmica', 'A88.1 Vertigem epidemica'),
  ('A888', 'Outras infecções virais especificadas do sistema nervoso central', 'A88.8 Outr infecc virais espec sist nerv central'),
  ('A89', 'Infecções virais não especificadas do sistema nervoso central', 'A89 Infecc virais NE do sist nervoso central'),
  ('A89', 'Infecções virais não especificadas do sistema nervoso central', 'A89 Infecc virais NE do sist nervoso central'),
  ('A90', 'Dengue (dengue clássico)', 'A90 Dengue'),
  ('A90', 'Dengue (dengue clássico)', 'A90 Dengue'),
  ('A91', 'Febre hemorrágica devida ao vírus do dengue', 'A91 Febre hemorragica dev virus do dengue'),
  ('A91', 'Febre hemorrágica devida ao vírus do dengue', 'A91 Febre hemorragica dev virus do dengue'),
  ('A92', 'Outras febres virais transmitidas por mosquitos', 'A92 Outr febres virais transm p/mosquitos'),
  ('A920', 'Febre de Chikungunya', 'A92.0 Febre de Chikungunya'),
  ('A921', 'Febre de O-nyong-nyong', 'A92.1 Febre de Onyong-nyong'),
  ('A922', 'Febre eqüina venezuelana', 'A92.2 Febre equina venezuelana'),
  ('A923', 'Infecção pelo vírus West Nile', 'A92.3 Infecção p/virus West Nile'),
  ('A924', 'Febre do vale do Rift', 'A92.4 Febre do vale do Rift'),
  ('A928', 'Outras febres virais especificadas transmitidas por mosquitos', 'A92.8 Outr febres virais espec transm p/mosquitos'),
  ('A929', 'Febre viral transmitida por mosquitos, não especificada', 'A92.9 Febre viral transm p/mosquitos NE'),
  ('A93', 'Outras febres por vírus transmitidas por artrópodes não classificadas em outra parte', 'A93 Outr febres p/virus transm p/artropodes NCOP'),
  ('A930', 'Febre de Oropouche', 'A93.0 Febre de Oropouche'),
  ('A931', 'Febre por flebótomos', 'A93.1 Febre p/flebotomos'),
  ('A932', 'Febre do Colorado transmitida por carrapatos', 'A93.2 Febre do Colorado transm p/carrapatos'),
  ('A938', 'Outras febres virais especificadas transmitidas por artrópodes', 'A93.8 Outr febres virais espec transm p/artropodes'),
  ('A94', 'Febre viral transmitida por artrópodes, não especificada', 'A94 Febre viral transm p/artropodes NE'),
  ('A94', 'Febre viral transmitida por artrópodes, não especificada', 'A94 Febre viral transm p/artropodes NE'),
  ('A95', 'Febre amarela', 'A95 Febre amarela'),
  ('A950', 'Febre amarela silvestre', 'A95.0 Febre amarela silvestre'),
  ('A951', 'Febre amarela urbana', 'A95.1 Febre amarela urbana'),
  ('A959', 'Febre amarela não especificada', 'A95.9 Febre amarela NE'),
  ('A96', 'Febre hemorrágica por arenavírus', 'A96 Febre hemorragica p/arenavirus'),
  ('A960', 'Febre hemorrágica de Junin', 'A96.0 Febre hemorragica de Junin'),
  ('A961', 'Febre hemorrágica de Machupo', 'A96.1 Febre hemorragica de Machupo'),
  ('A962', 'Febre de Lassa', 'A96.2 Febre de Lassa'),
  ('A968', 'Outras febres hemorrágicas por arenavírus', 'A96.8 Outr febres hemorragicas p/arenavirus'),
  ('A969', 'Febre hemorrágica por arenavírus, não especificada', 'A96.9 Febre hemorragica p/arenavirus NE'),
  ('A98', 'Outras febres hemorrágicas por vírus, não classificadas em outra parte', 'A98 Outr febres hemorragicas p/virus NCOP'),
  ('A980', 'Febre hemorrágica da Criméia (do Congo)', 'A98.0 Febre hemorragica da Crimeia'),
  ('A981', 'Febre hemorrágica de Omsk', 'A98.1 Febre hemorragica de Omsk'),
  ('A982', 'Doença da floresta de Kyasanur', 'A98.2 Doenc da floresta de Kyasanur'),
  ('A983', 'Doença de Marburg', 'A98.3 Doenc de Marburg'),
  ('A984', 'Doença pelo vírus Ebola', 'A98.4 Doenc p/virus Ebola'),
  ('A985', 'Febre hemorrágica com síndrome renal', 'A98.5 Febre hemorragica c/sindr renal'),
  ('A988', 'Outras febres hemorrágicas especificadas por vírus', 'A98.8 Outr febres hemorragicas espec p/virus'),
  ('A99', 'Febres hemorrágicas virais não especificadas', 'A99 Febres hemorragicas virais NE'),
  ('A99', 'Febres hemorrágicas virais não especificadas', 'A99 Febres hemorragicas virais NE');
