INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('E00', 'Síndrome de deficiência congênita de iodo', 'E00 Sindr de defic congen de iodo'),
  ('E000', 'Síndrome da deficiência congênita de iodo do tipo neurológico', 'E00.0 Sindr defic congen iodo tipo neurologico'),
  ('E001', 'Síndrome da deficiência congênita de iodo do tipo mixedematoso', 'E00.1 Sindr defic congen iodo tipo mixedematoso'),
  ('E002', 'Síndrome da deficiência congênita de iodo do tipo misto', 'E00.2 Sindr defic congen iodo tipo misto'),
  ('E009', 'Síndrome da deficiência congênita de iodo, não especificada', 'E00.9 Sindr da defic congen de iodo NE'),
  ('E01', 'Transtornos tireoidianos e afecções associadas, relacionados à deficiência de iodo', 'E01 Transt tireoid e afecc assoc rel defic iodo'),
  ('E010', 'Bócio (endêmico) difuso por deficiência de iodo', 'E01.0 Bocio difuso p/defic de iodo'),
  ('E011', 'Bócio (endêmico) multinodular por deficiência de iodo', 'E01.1 Bocio multinodular p/defic de iodo'),
  ('E012', 'Bócio (endêmico) não especificado, por deficiência de iodo', 'E01.2 Bocio NE p/defic de iodo'),
  ('E018', 'Outros transtornos tireoidianos e afecções associadas, relacionados com a deficiência de iodo', 'E01.8 Outr transt tireoid afecc assoc rel def iodo'),
  ('E02', 'Hipotireoidismo subclínico por deficiência de iodo', 'E02 Hipotireoidismo subclinico p/defic de iodo'),
  ('E02', 'Hipotireoidismo subclínico por deficiência de iodo', 'E02 Hipotireoidismo subclinico p/defic de iodo'),
  ('E03', 'Outros hipotireoidismos', 'E03 Outr hipotireoidismos'),
  ('E030', 'Hipotireoidismo congênito com bócio difuso', 'E03.0 Hipotireoidismo congen c/bocio difuso'),
  ('E031', 'Hipotireoidismo congênito sem bócio', 'E03.1 Hipotireoidismo congen s/bocio'),
  ('E032', 'Hipotireoidismo devido a medicamentos e outras substâncias exógenas', 'E03.2 Hipotireoidismo dev medic outr subst exogen'),
  ('E033', 'Hipotireoidismo pós-infeccioso', 'E03.3 Hipotireoidismo pos-infecc'),
  ('E034', 'Atrofia (adquirida) da tireóide', 'E03.4 Atrofia da tireoide'),
  ('E035', 'Coma mixedematoso', 'E03.5 Coma mixedematoso'),
  ('E038', 'Outros hipotireoidismos especificados', 'E03.8 Outr hipotireoidismos espec'),
  ('E039', 'Hipotireoidismo não especificado', 'E03.9 Hipotireoidismo NE'),
  ('E04', 'Outros bócios não-tóxicos', 'E04 Outr bocios nao-toxicos'),
  ('E040', 'Bócio não-tóxico difuso', 'E04.0 Bocio nao-toxico difuso'),
  ('E041', 'Bócio não-tóxico uninodular', 'E04.1 Bocio nao-toxico uninodular'),
  ('E042', 'Bócio não-tóxico multinodular', 'E04.2 Bocio nao-toxico multinodular'),
  ('E048', 'Outro bócio não-tóxico especificado', 'E04.8 Outr bocio nao-toxico espec'),
  ('E049', 'Bócio não-tóxico, não especificado', 'E04.9 Bocio nao-toxico NE'),
  ('E05', 'Tireotoxicose (hipertireoidismo)', 'E05 Tireotoxicose'),
  ('E050', 'Tireotoxicose com bócio difuso', 'E05.0 Tireotoxicose c/bocio difuso'),
  ('E051', 'Tireotoxicose com bócio tóxico uninodular', 'E05.1 Tireotoxicose c/bocio toxico uninodular'),
  ('E052', 'Tireotoxicose com bócio tóxico multinodular', 'E05.2 Tireotoxicose c/bocio toxico multinodular'),
  ('E053', 'Tireotoxicose causada por tecido tireoidiano ectópico', 'E05.3 Tireotoxicose caus p/tec tireoid ectopico'),
  ('E054', 'Tireotoxicose factícia', 'E05.4 Tireotoxicose facticia'),
  ('E055', 'Crise ou tempestade tireotóxica', 'E05.5 Crise ou tempestade tireotoxica'),
  ('E058', 'Outras tireotoxicoses', 'E05.8 Outr tireotoxicoses'),
  ('E059', 'Tireotoxicose não especificada', 'E05.9 Tireotoxicose NE'),
  ('E06', 'Tireoidite', 'E06 Tireoidite'),
  ('E060', 'Tireoidite aguda', 'E06.0 Tireoidite aguda'),
  ('E061', 'Tireoidite subaguda', 'E06.1 Tireoidite subaguda'),
  ('E062', 'Tireoidite crônica com tireotoxicose transitória', 'E06.2 Tireoidite cronica c/tireotoxicose transit'),
  ('E063', 'Tireoidite auto-imune', 'E06.3 Tireoidite auto-imune'),
  ('E064', 'Tireoidite induzida por droga', 'E06.4 Tireoidite induz p/droga'),
  ('E065', 'Outras tireoidites crônicas', 'E06.5 Outr tireoidites cronicas'),
  ('E069', 'Tireoidite não especificada', 'E06.9 Tireoidite NE'),
  ('E07', 'Outros transtornos da tireóide', 'E07 Outr transt da tireoide'),
  ('E070', 'Hipersecreção de calcitonina', 'E07.0 Hipersecrecao de calcitonina'),
  ('E071', 'Bócio disormonogênico', 'E07.1 Bocio disormonogenico'),
  ('E078', 'Outros transtornos especificados da tireóide', 'E07.8 Outr transt espec da tireoide'),
  ('E079', 'Transtorno não especificado da tireóide', 'E07.9 Transt NE da tireoide'),
  ('E10', 'Diabetes mellitus insulino-dependente', 'E10 Diabetes mellitus insulino-dependente'),
  ('E100', 'Diabetes mellitus insulino-dependente - com coma', 'E10.0 C/coma'),
  ('E101', 'Diabetes mellitus insulino-dependente - com cetoacidose', 'E10.1 C/cetoacidose'),
  ('E102', 'Diabetes mellitus insulino-dependente - com complicações renais', 'E10.2 C/compl renais'),
  ('E103', 'Diabetes mellitus insulino-dependente - com complicações oftálmicas', 'E10.3 C/compl oftalmicas'),
  ('E104', 'Diabetes mellitus insulino-dependente - com complicações neurológicas', 'E10.4 C/compl neurologicas'),
  ('E105', 'Diabetes mellitus insulino-dependente - com complicações circulatórias periféricas', 'E10.5 C/compl circulatorias perifericas'),
  ('E106', 'Diabetes mellitus insulino-dependente - com outras complicações especificadas', 'E10.6 C/outr compl espec'),
  ('E107', 'Diabetes mellitus insulino-dependente - com complicações múltiplas', 'E10.7 C/complic mult'),
  ('E108', 'Diabetes mellitus insulino-dependente - com complicações não especificadas', 'E10.8 C/compl NE'),
  ('E109', 'Diabetes mellitus insulino-dependente - sem complicações', 'E10.9 S/complic'),
  ('E11', 'Diabetes mellitus não-insulino-dependente', 'E11 Diabetes mellitus nao-insulino-dependemte'),
  ('E110', 'Diabetes mellitus não-insulino-dependente - com coma', 'E11.0 C/coma'),
  ('E111', 'Diabetes mellitus não-insulino-dependente - com cetoacidose', 'E11.1 C/cetoacidose'),
  ('E112', 'Diabetes mellitus não-insulino-dependente - com complicações renais', 'E11.2 C/compl renais'),
  ('E113', 'Diabetes mellitus não-insulino-dependente - com complicações oftálmicas', 'E11.3 C/compl oftalmicas'),
  ('E114', 'Diabetes mellitus não-insulino-dependente - com complicações neurológicas', 'E11.4 C/compl neurologicas'),
  ('E115', 'Diabetes mellitus não-insulino-dependente - com complicações circulatórias periféricas', 'E11.5 C/compl circulatorias perifericas'),
  ('E116', 'Diabetes mellitus não-insulino-dependente - com outras complicações especificadas', 'E11.6 C/outr compl espec'),
  ('E117', 'Diabetes mellitus não-insulino-dependente - com complicações múltiplas', 'E11.7 C/complic mult'),
  ('E118', 'Diabetes mellitus não-insulino-dependente - com complicações não especificadas', 'E11.8 C/compl NE'),
  ('E119', 'Diabetes mellitus não-insulino-dependente - sem complicações', 'E11.9 S/complic'),
  ('E12', 'Diabetes mellitus relacionado com a desnutrição', 'E12 Diabetes mellitus relac c/a desnutr'),
  ('E120', 'Diabetes mellitus relacionado com a desnutrição - com coma', 'E12.0 C/coma'),
  ('E121', 'Diabetes mellitus relacionado com a desnutrição - com cetoacidose', 'E12.1 C/cetoacidose'),
  ('E122', 'Diabetes mellitus relacionado com a desnutrição - com complicações renais', 'E12.2 C/compl renais'),
  ('E123', 'Diabetes mellitus relacionado com a desnutrição - com complicações oftálmicas', 'E12.3 C/compl oftalmicas'),
  ('E124', 'Diabetes mellitus relacionado com a desnutrição - com complicações neurológicas', 'E12.4 C/compl neurologicas'),
  ('E125', 'Diabetes mellitus relacionado com a desnutrição - com complicações circulatórias periféricas', 'E12.5 C/compl circulatorias perifericas'),
  ('E126', 'Diabetes mellitus relacionado com a desnutrição - com outras complicações especificadas', 'E12.6 C/outr compl espec'),
  ('E127', 'Diabetes mellitus relacionado com a desnutrição - com complicações múltiplas', 'E12.7 C/complic mult'),
  ('E128', 'Diabetes mellitus relacionado com a desnutrição - com complicações não especificadas', 'E12.8 C/compl NE'),
  ('E129', 'Diabetes mellitus relacionado com a desnutrição - sem complicações', 'E12.9 S/complic'),
  ('E13', 'Outros tipos especificados de diabetes mellitus', 'E13 Outr tipos espec de diabetes mellitus'),
  ('E130', 'Outros tipos especificados de diabetes mellitus - com coma', 'E13.0 C/coma'),
  ('E131', 'Outros tipos especificados de diabetes mellitus - com cetoacidose', 'E13.1 C/cetoacidose'),
  ('E132', 'Outros tipos especificados de diabetes mellitus - com complicações renais', 'E13.2 C/compl renais'),
  ('E133', 'Outros tipos especificados de diabetes mellitus - com complicações oftálmicas', 'E13.3 C/compl oftalmicas'),
  ('E134', 'Outros tipos especificados de diabetes mellitus - com complicações neurológicas', 'E13.4 C/compl neurologicas'),
  ('E135', 'Outros tipos especificados de diabetes mellitus - com complicações circulatórias periféricas', 'E13.5 C/compl circulatorias perifericas'),
  ('E136', 'Outros tipos especificados de diabetes mellitus - com outras complicações especificadas', 'E13.6 C/outr compl espec'),
  ('E137', 'Outros tipos especificados de diabetes mellitus - com complicações múltiplas', 'E13.7 C/complic mult'),
  ('E138', 'Outros tipos especificados de diabetes mellitus - com complicações não especificadas', 'E13.8 C/compl NE'),
  ('E139', 'Outros tipos especificados de diabetes mellitus - sem complicações', 'E13.9 S/complic'),
  ('E14', 'Diabetes mellitus não especificado', 'E14 Diabetes mellitus NE'),
  ('E140', 'Diabetes mellitus não especificado - com coma', 'E14.0 C/coma'),
  ('E141', 'Diabetes mellitus não especificado - com cetoacidose', 'E14.1 C/cetoacidose'),
  ('E142', 'Diabetes mellitus não especificado - com complicações renais', 'E14.2 C/compl renais'),
  ('E143', 'Diabetes mellitus não especificado - com complicações oftálmicas', 'E14.3 C/compl oftalmicas'),
  ('E144', 'Diabetes mellitus não especificado - com complicações neurológicas', 'E14.4 C/compl neurologicas'),
  ('E145', 'Diabetes mellitus não especificado - com complicações circulatórias periféricas', 'E14.5 C/compl circulatorias perifericas'),
  ('E146', 'Diabetes mellitus não especificado - com outras complicações especificadas', 'E14.6 C/outr compl espec'),
  ('E147', 'Diabetes mellitus não especificado - com complicações múltiplas', 'E14.7 C/complic mult'),
  ('E148', 'Diabetes mellitus não especificado - com complicações não especificadas', 'E14.8 C/compl NE'),
  ('E149', 'Diabetes mellitus não especificado - sem complicações', 'E14.9 S/complic'),
  ('E15', 'Coma hipoglicêmico não-diabético', 'E15 Coma hipoglicemico nao-diabetico'),
  ('E15', 'Coma hipoglicêmico não-diabético', 'E15 Coma hipoglicemico nao-diabetico'),
  ('E16', 'Outros transtornos da secreção pancreática interna', 'E16 Outr transt da secrecao pancreatica interna'),
  ('E160', 'Hipoglicemia induzida por droga sem coma', 'E16.0 Hipoglicemia induz p/droga s/coma'),
  ('E161', 'Outra hipoglicemia', 'E16.1 Outr hipoglicemia'),
  ('E162', 'Hipoglicemia não especificada', 'E16.2 Hipoglicemia NE'),
  ('E163', 'Aumento da secreção de glucagon', 'E16.3 Aumento da secrecao de glucagon'),
  ('E164', 'Secreção anormal de gastrina', 'E16.4 Secrecao anormal de gastrina'),
  ('E168', 'Outros transtornos especificados da secreção pancreática interna', 'E16.8 Outr transt espec secrecao pancreatica int'),
  ('E169', 'Transtorno não especificado da secreção pancreática interna', 'E16.9 Transt NE da secrecao pancreatica interna'),
  ('E20', 'Hipoparatireoidismo', 'E20 Hipoparatireoidismo'),
  ('E200', 'Hipoparatireoidismo idiopático', 'E20.0 Hipoparatireoidismo idiopatico'),
  ('E201', 'Pseudohipoparatireoidismo', 'E20.1 Pseudohipoparatireoidismo'),
  ('E208', 'Outro hipoparatireoidismo', 'E20.8 Outr hipoparatireoidismo'),
  ('E209', 'Hipoparatireoidismo não especificado', 'E20.9 Hipoparatireoidismo NE'),
  ('E21', 'Hiperparatireoidismo e outros transtornos da glândula paratireóide', 'E21 Hiperparatireoid e out transt gland paratir'),
  ('E210', 'Hiperparatireoidismo primário', 'E21.0 Hiperparatireoidismo prim'),
  ('E211', 'Hiperparatireoidismo secundário não classificado em outra parte', 'E21.1 Hiperparatireoidismo secund NCOP'),
  ('E212', 'Outro hiperparatireoidismo', 'E21.2 Outr hiperparatireoidismo'),
  ('E213', 'Hiperparatireoidismo não especificado', 'E21.3 Hiperparatireoidismo NE'),
  ('E214', 'Outros transtornos especificados da glândula paratireóide', 'E21.4 Outr transt espec da gland paratireoide'),
  ('E215', 'Transtorno não especificado da glândula paratireóide', 'E21.5 Transt NE da gland paratireoide'),
  ('E22', 'Hiperfunção da hipófise', 'E22 Hiperfuncao da hipofise'),
  ('E220', 'Acromegalia e gigantismo hipofisário', 'E22.0 Acromegalia e gigantismo hipofisario'),
  ('E221', 'Hiperprolactinemia', 'E22.1 Hiperprolactinemia'),
  ('E222', 'Síndrome da secreção inadequada de hormônio antidiurético', 'E22.2 Sindr secrecao inadeq hormonio antidiuretico'),
  ('E228', 'Outras hiperfunções da hipófise', 'E22.8 Outr hiperfuncoes da hipofise'),
  ('E229', 'Hiperfunção não especificada da hipófise', 'E22.9 Hiperfuncao NE da hipofise'),
  ('E23', 'Hipofunção e outros transtornos da hipófise', 'E23 Hipofuncao e outr transt da hipofise'),
  ('E230', 'Hipopituitarismo', 'E23.0 Hipopituitarismo'),
  ('E231', 'Hipopituitarismo induzido por droga', 'E23.1 Hipopituitarismo induz p/droga'),
  ('E232', 'Diabetes insípido', 'E23.2 Diabetes insipido'),
  ('E233', 'Disfunção hipotalâmica não classificada em outra parte', 'E23.3 Disfuncao hipotalamica NCOP'),
  ('E236', 'Outros transtornos da hipófise', 'E23.6 Outr transt da hipofise'),
  ('E237', 'Transtorno não especificado da hipófise', 'E23.7 Transt NE da hipofise'),
  ('E24', 'Síndrome de Cushing', 'E24 Sindr de Cushing'),
  ('E240', 'Síndrome de Cushing dependente da hipófise', 'E24.0 Sindr de Cushing dependente da hipofise'),
  ('E241', 'Síndrome de Nelson', 'E24.1 Sindr de Nelson'),
  ('E242', 'Síndrome de Cushing induzida por droga', 'E24.2 Sindr de Cushing induz p/droga'),
  ('E243', 'Síndrome do ACTH ectópico', 'E24.3 Sindr do ACTH ectopico'),
  ('E244', 'Síndrome de pseudo-Cushing induzida pelo álcool', 'E24.4 Sindr de pseudo-Cushing induz p/alcool'),
  ('E248', 'Outra síndrome de Cushing', 'E24.8 Outr sindr de Cushing'),
  ('E249', 'Síndrome de Cushing não especificada', 'E24.9 Sindr de Cushing NE'),
  ('E25', 'Transtornos adrenogenitais', 'E25 Transt adrenogenitais'),
  ('E250', 'Transtornos adrenogenitais congênitos associados à deficiência enzimática', 'E25.0 Transt adrenogen congen assoc defic enzimat'),
  ('E258', 'Outros transtornos adrenogenitais', 'E25.8 Outr transt adrenogenitais'),
  ('E259', 'Transtorno adrenogenital não especificado', 'E25.9 Transt adrenogenital NE'),
  ('E26', 'Hiperaldosteronismo', 'E26 Hiperaldosteronismo'),
  ('E260', 'Hiperaldosteronismo primário', 'E26.0 Hiperaldosteronismo prim'),
  ('E261', 'Hiperaldosteronismo secundário', 'E26.1 Hiperaldosteronismo secund'),
  ('E268', 'Outro hiperaldosteronismo', 'E26.8 Outr hiperaldosteronismo'),
  ('E269', 'Hiperaldosteronismo não especificado', 'E26.9 Hiperaldosteronismo NE'),
  ('E27', 'Outros transtornos da glândula supra-renal', 'E27 Outr transt da gland supra-renal'),
  ('E270', 'Outros excessos de atividade adrenocortical', 'E27.0 Outr excessos de atividade adrenocortical'),
  ('E271', 'Insuficiência adrenocortical primária', 'E27.1 Insuf adrenocortical prim'),
  ('E272', 'Crise addisoniana', 'E27.2 Crise addisoniana'),
  ('E273', 'Insuficiência adrenocortical induzida por drogas', 'E27.3 Insuf adrenocortical induz p/drogas'),
  ('E274', 'Outras insuficiências adrenocorticais e as não especificadas', 'E27.4 Outr insuf adrenocorticais e as NE'),
  ('E275', 'Hiperfunção adrenomedular', 'E27.5 Hiperfuncao adrenomedular'),
  ('E278', 'Outros transtornos especificados da supra-renal', 'E27.8 Outr transt espec da supra-renal'),
  ('E279', 'Transtorno não especificado da supra-renal', 'E27.9 Transt NE da supra-renal'),
  ('E28', 'Disfunção ovariana', 'E28 Disfuncao ovariana'),
  ('E280', 'Excesso de estrógeno', 'E28.0 Excesso de estrogeno'),
  ('E281', 'Excesso de andrógenos', 'E28.1 Excesso de androgenos'),
  ('E282', 'Síndrome do ovário policístico', 'E28.2 Sindr do ovario policistico'),
  ('E283', 'Insuficiência ovariana primária', 'E28.3 Insuf ovariana prim'),
  ('E288', 'Outra disfunção ovariana', 'E28.8 Outr disfuncao ovariana'),
  ('E289', 'Disfunção ovariana não especificada', 'E28.9 Disfuncao ovariana NE'),
  ('E29', 'Disfunção testicular', 'E29 Disfuncao testicular'),
  ('E290', 'Hiperfunção testicular', 'E29.0 Hiperfuncao testicular'),
  ('E291', 'Hipofunção testicular', 'E29.1 Hipofuncao testicular'),
  ('E298', 'Outra disfunção testicular', 'E29.8 Outr disfuncao testicular'),
  ('E299', 'Disfunção testicular não especificada', 'E29.9 Disfuncao testicular NE'),
  ('E30', 'Transtornos da puberdade não classificados em outra parte', 'E30 Transt da puberdade NCOP'),
  ('E300', 'Puberdade retardada', 'E30.0 Puberdade retardada'),
  ('E301', 'Puberdade precoce', 'E30.1 Puberdade precoce'),
  ('E308', 'Outros transtornos da puberdade', 'E30.8 Outr transt da puberdade'),
  ('E309', 'Transtorno não especificado da puberdade', 'E30.9 Transt NE da puberdade'),
  ('E31', 'Disfunção poliglandular', 'E31 Disfuncao poliglandular'),
  ('E310', 'Insuficiência poliglandular auto-imune', 'E31.0 Insuf poliglandular auto-imune'),
  ('E311', 'Hiperfunção poliglandular', 'E31.1 Hiperfuncao poliglandular'),
  ('E318', 'Outra disfunção poliglandular', 'E31.8 Outr disfuncao poliglandular'),
  ('E319', 'Disfunção poliglandular não especificada', 'E31.9 Disfuncao poliglandular NE'),
  ('E32', 'Doenças do timo', 'E32 Doenc do timo'),
  ('E320', 'Hiperplasia persistente do timo', 'E32.0 Hiperplasia persistente do timo'),
  ('E321', 'Abscesso do timo', 'E32.1 Abscesso do timo'),
  ('E328', 'Outras doenças do timo', 'E32.8 Outr doenc do timo'),
  ('E329', 'Doença do timo não especificada', 'E32.9 Doenc do timo NE'),
  ('E34', 'Outros transtornos endócrinos', 'E34 Outr transt endocrinos'),
  ('E340', 'Síndrome carcinóide', 'E34.0 Sindr carcinoide'),
  ('E341', 'Outra hipersecreção de hormônios intestinais', 'E34.1 Outr hipersecrecao de hormonios intestinais'),
  ('E342', 'Secreção hormonal ectópica, não classificada em outra parte', 'E34.2 Secrecao hormonal ectopica NCOP'),
  ('E343', 'Nanismo, não classificado em outra parte', 'E34.3 Nanismo NCOP'),
  ('E344', 'Alta estatura constitucional', 'E34.4 Alta estatura constitucional'),
  ('E345', 'Síndrome de resistência a andrógenos', 'E34.5 Sindr de resistencia a androgenos'),
  ('E348', 'Outros transtornos endócrinos especificados', 'E34.8 Outr transt endocrinos espec'),
  ('E349', 'Transtorno endócrino não especificado', 'E34.9 Transt endocrino NE'),
  ('E35', 'Transtornos das glândulas endócrinas em doenças classificadas em outra parte', 'E35 Transt das gland endocrinas em doenc COP'),
  ('E350', 'Transtornos da glândula tireóide em doenças classificadas em outra parte', 'E35.0 Transt da gland tireoide em doenc COP'),
  ('E351', 'Transtornos das supra-renais em doenças classificadas em outra parte', 'E35.1 Transt das supra-renais em doenc COP'),
  ('E358', 'Transtornos de outras glândulas endócrinas em doenças classificadas em outra parte', 'E35.8 Transt de outr gland endocrinas em doenc COP'),
  ('E40', 'Kwashiorkor', 'E40 Kwashiorkor'),
  ('E40', 'Kwashiorkor', 'E40 Kwashiorkor'),
  ('E41', 'Marasmo nutricional', 'E41 Marasmo nutricional'),
  ('E41', 'Marasmo nutricional', 'E41 Marasmo nutricional'),
  ('E42', 'Kwashiorkor marasmático', 'E42 Kwashiorkor marasmatico'),
  ('E42', 'Kwashiorkor marasmático', 'E42 Kwashiorkor marasmatico'),
  ('E43', 'Desnutrição protéico-calórica grave não especificada', 'E43 Desnutric proteico-calorica grave NE'),
  ('E43', 'Desnutrição protéico-calórica grave não especificada', 'E43 Desnutric proteico-calorica grave NE'),
  ('E44', 'Desnutrição protéico-calórica de graus moderado e leve', 'E44 Desnutric proteico-calorica grau moder leve'),
  ('E440', 'Desnutrição protéico-calórica moderada', 'E44.0 Desnutric proteico-calorica moderada'),
  ('E441', 'Desnutrição protéico-calórica leve', 'E44.1 Desnutric proteico-calorica leve'),
  ('E45', 'Atraso do desenvolvimento devido à desnutrição protéico-calórica', 'E45 Atraso desenv dev desnutric proteico-caloric'),
  ('E45', 'Atraso do desenvolvimento devido à desnutrição protéico-calórica', 'E45 Atraso desenv dev desnutric proteico-caloric'),
  ('E46', 'Desnutrição protéico-calórica não especificada', 'E46 Desnutric proteico-calorica NE'),
  ('E46', 'Desnutrição protéico-calórica não especificada', 'E46 Desnutric proteico-calorica NE'),
  ('E50', 'Deficiência de vitamina A', 'E50 Defic de vitamina A'),
  ('E500', 'Deficiência de vitamina A com xerose conjuntival', 'E50.0 Defic de vitamina A c/xerose conjuntival'),
  ('E501', 'Deficiência de vitamina A com mancha de Bitot e xerose conjuntival', 'E50.1 Defic vitamina c/mancha de Bitot xerose conj'),
  ('E502', 'Deficiência de vitamina A com xerose da córnea', 'E50.2 Defic de vitamina A c/xerose da cornea'),
  ('E503', 'Deficiência de vitamina A com ulceração e xerose da córnea', 'E50.3 Defic vitamina A c/ulceracao e xerose cornea'),
  ('E504', 'Deficiência de vitamina A com ceratomalácia', 'E50.4 Defic de vitamina A c/ceratomalacia'),
  ('E505', 'Deficiência de vitamina A com cegueira noturna', 'E50.5 Defic de vitamina A c/cegueira noturna'),
  ('E506', 'Deficiência de vitamina A com cicatrizes xeroftálmicas da córnea', 'E50.6 Defic vitamina A cicatrizes xeroft cornea'),
  ('E507', 'Outras manifestações oculares devidas a deficiência de vitamina A', 'E50.7 Outr manif oculares dev defic vitamina A'),
  ('E508', 'Outras manifestações devidas a deficiência de vitamina A', 'E50.8 Outr manifestacoes dev defic de vitamina A'),
  ('E509', 'Deficiência não especificada de vitamina A', 'E50.9 Defic NE de vitamina A'),
  ('E51', 'Deficiência de tiamina', 'E51 Defic de tiamina'),
  ('E511', 'Beribéri', 'E51.1 Beriberi'),
  ('E512', 'Encefalopatia de Wernicke', 'E51.2 Encefalopatia de Wernicke'),
  ('E518', 'Outras manifestações da deficiência de tiamina', 'E51.8 Outr manifestacoes da defic de tiamina'),
  ('E519', 'Deficiência não especificada de tiamina', 'E51.9 Defic NE de tiamina'),
  ('E52', 'Deficiência de niacina (pelagra)', 'E52 Defic de niacina'),
  ('E52', 'Deficiência de niacina (pelagra)', 'E52 Defic de niacina'),
  ('E53', 'Deficiência de outras vitaminas do grupo B', 'E53 Defic de outr vitaminas do grupo B'),
  ('E530', 'Deficiência de riboflavina', 'E53.0 Defic de riboflavina'),
  ('E531', 'Deficiência de piridoxina', 'E53.1 Defic de piridoxina'),
  ('E538', 'Deficiência de outras vitaminas especificadas do grupo B', 'E53.8 Defic de outr vitaminas espec do grupo B'),
  ('E539', 'Deficiência não especificada de vitamina B', 'E53.9 Defic NE de vitamina B'),
  ('E54', 'Deficiência de ácido ascórbico', 'E54 Defic de acido ascorbico'),
  ('E54', 'Deficiência de ácido ascórbico', 'E54 Defic de acido ascorbico'),
  ('E55', 'Deficiência de vitamina D', 'E55 Defic de vitamina D'),
  ('E550', 'Raquitismo ativo', 'E55.0 Raquitismo ativo'),
  ('E559', 'Deficiência não especificada de vitamina D', 'E55.9 Defic NE de vitamina D'),
  ('E56', 'Outras deficiências vitamínicas', 'E56 Outr defic vitaminicas'),
  ('E560', 'Deficiência de vitamina E', 'E56.0 Defic de vitamina E'),
  ('E561', 'Deficiência de vitamina K', 'E56.1 Defic de vitamina K'),
  ('E568', 'Deficiência de outras vitaminas', 'E56.8 Defic de outr vitaminas'),
  ('E569', 'Deficiência vitamínica não especificada', 'E56.9 Defic vitaminica NE'),
  ('E58', 'Deficiência de cálcio da dieta', 'E58 Defic de calcio da dieta'),
  ('E58', 'Deficiência de cálcio da dieta', 'E58 Defic de calcio da dieta'),
  ('E59', 'Deficiência de selênio da dieta', 'E59 Defic de selenio da dieta'),
  ('E59', 'Deficiência de selênio da dieta', 'E59 Defic de selenio da dieta'),
  ('E60', 'Deficiência de zinco da dieta', 'E60 Defic de zinco da dieta'),
  ('E60', 'Deficiência de zinco da dieta', 'E60 Defic de zinco da dieta'),
  ('E61', 'Deficiência de outros elementos nutrientes', 'E61 Defic de outr elementos nutrientes'),
  ('E610', 'Deficiência de cobre', 'E61.0 Defic de cobre'),
  ('E611', 'Deficiência de ferro', 'E61.1 Defic de ferro'),
  ('E612', 'Deficiência de magnésio', 'E61.2 Defic de magnesio'),
  ('E613', 'Deficiência de manganês', 'E61.3 Defic de manganes'),
  ('E614', 'Deficiência de cromo', 'E61.4 Defic de cromo'),
  ('E615', 'Deficiência de molibdênio', 'E61.5 Defic de molibdenio'),
  ('E616', 'Deficiência de vanádio', 'E61.6 Defic de vanadio'),
  ('E617', 'Deficiência de múltiplos elementos nutrientes', 'E61.7 Defic de mult elementos nutrientes'),
  ('E618', 'Deficiência de outros elementos nutrientes especificados', 'E61.8 Defic de outr elementos nutrientes espec'),
  ('E619', 'Deficiência de elementos nutrientes não especificados', 'E61.9 Defic de elementos nutrientes NE'),
  ('E63', 'Outras deficiências nutricionais', 'E63 Outr defic nutricionais'),
  ('E630', 'Deficiência de ácido graxo essencial', 'E63.0 Defic de acido graxo essencial'),
  ('E631', 'Desequilíbrio de constituintes da ingestão de alimentos', 'E63.1 Desequilibrio constituintes ingest alimentos'),
  ('E638', 'Outras deficiências nutricionais especificadas', 'E63.8 Outr defic nutricionais espec'),
  ('E639', 'Deficiência nutricional não especificada', 'E63.9 Defic nutricional NE'),
  ('E64', 'Seqüelas de desnutrição e de outras deficiências nutricionais', 'E64 Sequelas desnutric e outr defic nutricionais'),
  ('E640', 'Seqüelas de desnutrição protéico-calórica', 'E64.0 Sequelas de desnutric proteico-calorica'),
  ('E641', 'Seqüelas da deficiência de vitamina A', 'E64.1 Sequelas da defic de vitamina A'),
  ('E642', 'Seqüelas da deficiência de vitamina C', 'E64.2 Sequelas da defic de vitamina C'),
  ('E643', 'Seqüelas do raquitismo', 'E64.3 Sequelas do raquitismo'),
  ('E648', 'Seqüelas de outras deficiências nutricionais', 'E64.8 Sequelas de outr defic nutricionais'),
  ('E649', 'Seqüelas de deficiência nutricional não especificada', 'E64.9 Sequelas de defic nutricional NE'),
  ('E65', 'Adiposidade localizada', 'E65 Adiposidade localizada'),
  ('E65', 'Adiposidade localizada', 'E65 Adiposidade localizada'),
  ('E66', 'Obesidade', 'E66 Obesidade'),
  ('E660', 'Obesidade devida a excesso de calorias', 'E66.0 Obesidade dev excesso de calorias'),
  ('E661', 'Obesidade induzida por drogas', 'E66.1 Obesidade induz p/drogas'),
  ('E662', 'Obesidade extrema com hipoventilação alveolar', 'E66.2 Obesidade extrema c/hipoventilacao alveolar'),
  ('E668', 'Outra obesidade', 'E66.8 Outr obesidade'),
  ('E669', 'Obesidade não especificada', 'E66.9 Obesidade NE'),
  ('E67', 'Outras formas de hiperalimentação', 'E67 Outr form de hiperalimentacao'),
  ('E670', 'Hipervitaminose A', 'E67.0 Hipervitaminose A'),
  ('E671', 'Hipercarotenemia', 'E67.1 Hipercarotenemia'),
  ('E672', 'Síndrome de megavitamina B6', 'E67.2 Sindr de megavitamina B6'),
  ('E673', 'Hipervitaminose D', 'E67.3 Hipervitaminose D'),
  ('E678', 'Outras formas especificadas de hiperalimentação', 'E67.8 Outr form espec de hiperalimentacao'),
  ('E68', 'Seqüelas de hiperalimentação', 'E68 Sequelas de hiperalimentacao'),
  ('E68', 'Seqüelas de hiperalimentação', 'E68 Sequelas de hiperalimentacao'),
  ('E70', 'Distúrbios do metabolismo de aminoácidos aromáticos', 'E70 Disturbios metabolism aminoacidos aromaticos'),
  ('E700', 'Fenilcetonúria clássica', 'E70.0 Fenilcetonuria classica'),
  ('E701', 'Outras hiperfenilalaninemias', 'E70.1 Outr hiperfenilalaninemias'),
  ('E702', 'Distúrbios do metabolismo da tirosina', 'E70.2 Disturbios do metabolismo da tirosina'),
  ('E703', 'Albinismo', 'E70.3 Albinismo'),
  ('E708', 'Outros distúrbios do metabolismo de aminoácidos aromáticos', 'E70.8 Outr disturbios metab aminoacidos aromaticos'),
  ('E709', 'Distúrbio não especificado do metabolismo de aminoácidos aromáticos', 'E70.9 Disturbio NE metab aminoacidos aromaticos'),
  ('E71', 'Distúrbios do metabolismo de aminoácidos de cadeia ramificada e do metabolismo dos ácidos graxos', 'E71 Dist metab aminoacidos cad ramif e acid grax'),
  ('E710', 'Doença da urina em xarope de ácer (ou bordo) (Maple-syrup urine disease)', 'E71.0 Doenc da urina em xarope de acer'),
  ('E711', 'Outros distúrbios do metabolismo de aminoácidos de cadeia ramificada', 'E71.1 Outr disturb metab aminoacidos cadeia ramif'),
  ('E712', 'Distúrbio não especificado do metabolismo de aminoácidos de cadeia ramificada', 'E71.2 Disturbio NE metab aminoacidos cadeia ramif'),
  ('E713', 'Distúrbios do metabolismo de ácidos graxos', 'E71.3 Disturbios do metabolismo de acidos graxos'),
  ('E72', 'Outros distúrbios do metabolismo de aminoácidos', 'E72 Outr disturbios metabolismo de aminoacidos'),
  ('E720', 'Distúrbios do transporte de aminoácidos', 'E72.0 Disturbios do transporte de aminoacidos'),
  ('E721', 'Distúrbios do metabolismo dos aminoácidos que contêm enxofre', 'E72.1 Disturb metab aminoacidos que contem enxofre'),
  ('E722', 'Distúrbios do metabolismo do ciclo da uréia', 'E72.2 Disturbios do metabolismo do ciclo da ureia'),
  ('E723', 'Distúrbios do metabolismo da lisina e da hidroxilisina', 'E72.3 Disturbios metabolismo lisina hidroxilisina'),
  ('E724', 'Distúrbios do metabolismo da ornitina', 'E72.4 Disturbios do metabolismo da ornitina'),
  ('E725', 'Distúrbios do metabolismo da glicina', 'E72.5 Disturbios do metabolismo da glicina'),
  ('E728', 'Outros distúrbios especificados do metabolismo dos aminoácidos', 'E72.8 Outr disturbios espec metab aminoacidos'),
  ('E729', 'Distúrbio não especificado do metabolismo dos aminoácidos', 'E72.9 Disturbio NE do metabolismo dos aminoacidos'),
  ('E73', 'Intolerância à lactose', 'E73 Intolerancia a lactose'),
  ('E730', 'Deficiência congênita de lactase', 'E73.0 Defic congen de lactase'),
  ('E731', 'Deficiência secundária de lactase', 'E73.1 Defic secund de lactase'),
  ('E738', 'Outras intolerâncias à lactose', 'E73.8 Outr intolerancias a lactose'),
  ('E739', 'Intolerância à lactose, não especificada', 'E73.9 Intolerancia a lactose NE'),
  ('E74', 'Outros distúrbios do metabolismo de carboidratos', 'E74 Outr disturbios do metabolismo carboidratos'),
  ('E740', 'Doença de depósito de glicogênio', 'E74.0 Doenc de deposito de glicogenio'),
  ('E741', 'Distúrbios do metabolismo da frutose', 'E74.1 Disturbios do metabolismo da frutose'),
  ('E742', 'Distúrbios do metabolismo da galactose', 'E74.2 Disturbios do metabolismo da galactose'),
  ('E743', 'Outros distúrbios da absorção intestinal de carboidratos', 'E74.3 Outr disturbios absorcao intest carboidratos'),
  ('E744', 'Distúrbios do metabolismo do piruvato e da gliconeogênese', 'E74.4 Disturbios metab piruvato gliconeogenese'),
  ('E748', 'Outros distúrbios especificados do metabolismo de carboidratos', 'E74.8 Outr disturbios espec metab carboidratos'),
  ('E749', 'Distúrbio não especificado do metabolismo de carboidratos', 'E74.9 Disturbio NE do metabolismo de carboidratos'),
  ('E75', 'Distúrbios do metabolismo de esfingolípides e outros distúrbios de depósito de lípides', 'E75 Disturb metab esfingolip e outr depos lipid'),
  ('E750', 'Gangliosidose GM2', 'E75.0 Gangliosidose GM2'),
  ('E751', 'Outras gangliosidoses', 'E75.1 Outr gangliosidoses'),
  ('E752', 'Outras esfingolipidoses', 'E75.2 Outr esfingolipidoses'),
  ('E753', 'Esfingolipidose não especificada', 'E75.3 Esfingolipidose NE'),
  ('E754', 'Lipofuscinose neuronal ceróide', 'E75.4 Lipofuscinose neuronal ceroide'),
  ('E755', 'Outros distúrbios do depósito de lípides', 'E75.5 Outr disturbios do deposito de lipides'),
  ('E756', 'Distúrbio não especificado do depósito de lípides', 'E75.6 Disturbio NE do deposito de lipides'),
  ('E76', 'Distúrbios do metabolismo do glicosaminoglicano', 'E76 Disturbios metabolismo do glicosaminoglicano'),
  ('E760', 'Mucopolissacaridose do tipo I', 'E76.0 Mucopolissacaridose do tipo I'),
  ('E761', 'Mucopolissacaridose do tipo II', 'E76.1 Mucopolissacaridose do tipo II'),
  ('E762', 'Outras mucopolissacaridoses', 'E76.2 Outr mucopolissacaridoses'),
  ('E763', 'Mucopolissacaridose não especificada', 'E76.3 Mucopolissacaridose NE'),
  ('E768', 'Outros distúrbios do metabolismo do glicosaminoglicano', 'E76.8 Outr disturbios metab glicosaminoglicano'),
  ('E769', 'Distúrbio não especificado do metabolismo do glicosaminoglicano', 'E76.9 Disturbio NE metabolismo glicosaminoglicano'),
  ('E77', 'Distúrbios do metabolismo de glicoproteínas', 'E77 Disturbios do metabolismo de glicoproteinas'),
  ('E770', 'Defeitos na modificação pós-translacional de enzimas lisossômicas', 'E77.0 Defeitos modif pos-translac enzimas lisossom'),
  ('E771', 'Defeitos na degradação das glicoproteínas', 'E77.1 Defeitos na degradacao das glicoproteinas'),
  ('E778', 'Outros distúrbios do metabolismo de glicoproteínas', 'E77.8 Outr disturbios metabolismo glicoproteinas'),
  ('E779', 'Distúrbio não especificado do metabolismo de glicoproteínas', 'E77.9 Disturbio NE do metabolismo glicoproteinas'),
  ('E78', 'Distúrbios do metabolismo de lipoproteínas e outras lipidemias', 'E78 Disturbios metab lipoproteinas e out lipidem'),
  ('E780', 'Hipercolesterolemia pura', 'E78.0 Hipercolesterolemia pura'),
  ('E781', 'Hipergliceridemia pura', 'E78.1 Hipergliceridemia pura'),
  ('E782', 'Hiperlipidemia mista', 'E78.2 Hiperlipidemia mista'),
  ('E783', 'Hiperquilomicronemia', 'E78.3 Hiperquilomicronemia'),
  ('E784', 'Outras hiperlipidemias', 'E78.4 Outr hiperlipidemias'),
  ('E785', 'Hiperlipidemia não especificada', 'E78.5 Hiperlipidemia NE'),
  ('E786', 'Deficiências de lipoproteínas', 'E78.6 Defic de lipoproteinas'),
  ('E788', 'Outros distúrbios do metabolismo de lipoproteínas', 'E78.8 Outr disturbios metabolismo de lipoproteinas'),
  ('E789', 'Distúrbio não especificado do metabolismo de lipoproteínas', 'E78.9 Disturbio NE do metabolismo de lipoproteinas'),
  ('E79', 'Distúrbios do metabolismo de purina e pirimidina', 'E79 Disturbios metabolismo purina e pirimidina'),
  ('E790', 'Hiperuricemia sem sinais de artrite inflamatória e de doença com tofos', 'E79.0 Hiperuric s/sinais artrite infl doenc tofos'),
  ('E791', 'Síndrome de Lesch-Nyhan', 'E79.1 Sindr de Lesch-Nyhan'),
  ('E798', 'Outros distúrbios do metabolismo da purina e pirimidina', 'E79.8 Outr disturbios metab purina e pirimidina'),
  ('E799', 'Distúrbio não especificado do metabolismo da purina e pirimidina', 'E79.9 Disturbio NE metabolismo purina e pirimidina'),
  ('E80', 'Distúrbios do metabolismo da porfirina e da bilirrubina', 'E80 Disturbios metab porfirina e bilirrubina'),
  ('E800', 'Porfiria hereditária eritropoética', 'E80.0 Porfiria hereditaria eritropoetica'),
  ('E801', 'Porfiria cutânea tardia', 'E80.1 Porfiria cutanea tard'),
  ('E802', 'Outras porfirias', 'E80.2 Outr porfirias'),
  ('E803', 'Defeitos da catalase e da peroxidase', 'E80.3 Defeitos da catalase e da peroxidase'),
  ('E804', 'Síndrome de Gilbert', 'E80.4 Sindr de Gilbert'),
  ('E805', 'Síndrome da Crigler-Najjar', 'E80.5 Sindr da Crigler-Najjar'),
  ('E806', 'Outros distúrbios do metabolismo da bilirrubina', 'E80.6 Outr disturbios metabolismo da bilirrubina'),
  ('E807', 'Distúrbio não especificado do metabolismo da bilirrubina', 'E80.7 Disturbio NE do metabolismo da bilirrubina'),
  ('E83', 'Distúrbios do metabolismo de minerais', 'E83 Disturbios do metabolismo de minerais'),
  ('E830', 'Distúrbios do metabolismo do cobre', 'E83.0 Disturbios do metabolismo do cobre'),
  ('E831', 'Doença do metabolismo do ferro', 'E83.1 Doenc do metabolismo do ferro'),
  ('E832', 'Distúrbios do metabolismo do zinco', 'E83.2 Disturbios do metabolismo do zinco'),
  ('E833', 'Distúrbios do metabolismo do fósforo', 'E83.3 Disturbios do metabolismo do fosforo'),
  ('E834', 'Distúrbios do metabolismo do magnésio', 'E83.4 Disturbios do metabolismo do magnesio'),
  ('E835', 'Distúrbios do metabolismo do cálcio', 'E83.5 Disturbios do metabolismo do calcio'),
  ('E838', 'Outros distúrbios do metabolismo mineral', 'E83.8 Outr disturbios do metabolismo mineral'),
  ('E839', 'Distúrbio não especificado do metabolismo mineral', 'E83.9 Disturbio NE do metabolismo mineral'),
  ('E84', 'Fibrose cística', 'E84 Fibrose cistica'),
  ('E840', 'Fibrose cística com manifestações pulmonares', 'E84.0 Fibrose cistica c/manifestacoes pulmonares'),
  ('E841', 'Fibrose cística com manifestações intestinais', 'E84.1 Fibrose cistica c/manifestacoes intestinais'),
  ('E848', 'Fibrose cística com outras manifestações', 'E84.8 Fibrose cistica c/outr manifestacoes'),
  ('E849', 'Fibrose cística não especificada', 'E84.9 Fibrose cistica NE'),
  ('E85', 'Amiloidose', 'E85 Amiloidose'),
  ('E850', 'Amiloidose heredofamiliar não-neuropática', 'E85.0 Amiloidose heredofamiliar nao-neuropatica'),
  ('E851', 'Amiloidose heredofamiliar neuropática', 'E85.1 Amiloidose heredofamiliar neuropatica'),
  ('E852', 'Amiloidose heredofamiliar não especificada', 'E85.2 Amiloidose heredofamiliar NE'),
  ('E853', 'Amiloidose sistêmica secundária', 'E85.3 Amiloidose sistemica secund'),
  ('E854', 'Amiloidose limitada a órgãos', 'E85.4 Amiloidose limitada a orgaos'),
  ('E858', 'Outras amiloidoses', 'E85.8 Outr amiloidoses'),
  ('E859', 'Amiloidose não especificada', 'E85.9 Amiloidose NE'),
  ('E86', 'Depleção de volume', 'E86 Deplecao de volume'),
  ('E86', 'Depleção de volume', 'E86 Deplecao de volume'),
  ('E87', 'Outros transtornos do equilíbrio hidroeletrolítico e ácido-básico', 'E87 Outr transt equil hidroeletr e acido-basic'),
  ('E870', 'Hiperosmolaridade e hipernatremia', 'E87.0 Hiperosmolaridade e hipernatremia'),
  ('E871', 'Hiposmolaridade e hiponatremia', 'E87.1 Hiposmolaridade e hiponatremia'),
  ('E872', 'Acidose', 'E87.2 Acidose'),
  ('E873', 'Alcalose', 'E87.3 Alcalose'),
  ('E874', 'Distúrbio misto do equilíbrio ácido-básico', 'E87.4 Disturbio misto do equilibrio acido-basico'),
  ('E875', 'Hiperpotassemia', 'E87.5 Hiperpotassemia'),
  ('E876', 'Hipopotassemia', 'E87.6 Hipopotassemia'),
  ('E877', 'Sobrecarga de líquidos', 'E87.7 Sobrecarga de liquidos'),
  ('E878', 'Outros transtornos do equilíbrio hidroeletrolítico não classificados em outra parte', 'E87.8 Outr transt equilibrio hidroeletrolit NCOP'),
  ('E88', 'Outros distúrbios metabólicos', 'E88 Outr disturbios metabolicos'),
  ('E880', 'Distúrbios do metabolismo das proteínas plasmáticas não classificados em outra parte', 'E88.0 Disturbios metab proteinas plasmaticas NCOP'),
  ('E881', 'Lipodistrofia não classificada em outra parte', 'E88.1 Lipodistrofia NCOP'),
  ('E882', 'Lipomatose não classificada em outra parte', 'E88.2 Lipomatose NCOP'),
  ('E888', 'Outros distúrbios especificados do metabolismo', 'E88.8 Outr disturbios espec do metabolismo'),
  ('E889', 'Distúrbio metabólico não especificado', 'E88.9 Disturbio metabolico NE'),
  ('E89', 'Transtornos endócrinos e metabólicos pós-procedimentos, não classificados em outra parte', 'E89 Transt endocrinos e metab pos-proced NCOP'),
  ('E890', 'Hipotireoidismo pós-procedimento', 'E89.0 Hipotireoidismo pos-proced'),
  ('E891', 'Hipoinsulinemia pós-procedimento', 'E89.1 Hipoinsulinemia pos-proced'),
  ('E892', 'Hipoparatireoidismo pós-procedimento', 'E89.2 Hipoparatireoidismo pos-proced'),
  ('E893', 'Hipopituitarismo pós-procedimento', 'E89.3 Hipopituitarismo pos-proced'),
  ('E894', 'Insuficiência ovariana pós-procedimento', 'E89.4 Insuf ovariana pos-proced'),
  ('E895', 'Hipofunção testicular pós-procedimento', 'E89.5 Hipofuncao testicular pos-proced'),
  ('E896', 'Hipofunção adrenocortical(-medular) pós-procedimento', 'E89.6 Hipofuncao adrenocortical pos-proced'),
  ('E898', 'Outros transtornos endócrinos e metabólicos pós-procedimento', 'E89.8 Outr transt endocr e metab pos-proced'),
  ('E899', 'Transtornos endócrinos e metabólicos não especificados pós-procedimento', 'E89.9 Transt endocrinos e metab NE pos-proced'),
  ('E90', 'Transtornos nutricionais e metabólicos em doenças classificadas em outra parte', 'E90 Transt nutricionais e metab em doenc COP'),
  ('E90', 'Transtornos nutricionais e metabólicos em doenças classificadas em outra parte', 'E90 Transt nutricionais e metab em doenc COP');
