INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('R00', 'Anormalidades do batimento cardíaco', 'R00 Anormalidades do batimento cardiaco'),
  ('R000', 'Taquicardia não especificada', 'R00.0 Taquicardia NE'),
  ('R001', 'Bradicardia não especificada', 'R00.1 Bradicardia NE'),
  ('R002', 'Palpitações', 'R00.2 Palpitacoes'),
  ('R008', 'Outras anormalidades e as não especificadas do batimento cardíaco', 'R00.8 Outr anormalidades e NE batimento cardiaco'),
  ('R01', 'Sopros e outros ruídos cardíacos', 'R01 Sopros e outr ruidos cardiacos'),
  ('R010', 'Sopros cardíacos benignos ou inocentes', 'R01.0 Sopros cardiacos benignos ou inocentes'),
  ('R011', 'Sopro cardíaco, não especificado', 'R01.1 Sopro cardiaco NE'),
  ('R012', 'Outros ruídos cardíacos', 'R01.2 Outr ruidos cardiacos'),
  ('R02', 'Gangrena não classificada em outra parte', 'R02 Gangrena NCOP'),
  ('R02', 'Gangrena não classificada em outra parte', 'R02 Gangrena NCOP'),
  ('R03', 'Valor anormal da pressão arterial sem diagnóstico', 'R03 Valor anormal pressao arterial s/diagn'),
  ('R030', 'Valor elevado da pressão arterial sem o diagnóstico de hipertensão', 'R03.0 Valor elevado press arter s/diagn hipertens'),
  ('R031', 'Valor baixo da pressão arterial não específico', 'R03.1 Valor baixo pressao arterial nao especifico'),
  ('R04', 'Hemorragia das vias respiratórias', 'R04 Hemorragia das vias respirat'),
  ('R040', 'Epistaxis', 'R04.0 Epistaxis'),
  ('R041', 'Hemorragia da garganta', 'R04.1 Hemorragia da garganta'),
  ('R042', 'Hemoptise', 'R04.2 Hemoptise'),
  ('R048', 'Hemorragia de outras localizações das vias respiratórias', 'R04.8 Hemorragia de outr localiz das vias respirat'),
  ('R049', 'Hemorragia não especificada das vias respiratórias', 'R04.9 Hemorragia NE das vias respirat'),
  ('R05', 'Tosse', 'R05 Tosse'),
  ('R05', 'Tosse', 'R05 Tosse'),
  ('R06', 'Anormalidades da respiração', 'R06 Anormalidades da respiracao'),
  ('R060', 'Dispnéia', 'R06.0 Dispneia'),
  ('R061', 'Estridor', 'R06.1 Estridor'),
  ('R062', 'Respiração ofegante', 'R06.2 Respiracao ofegante'),
  ('R063', 'Respiração periódica', 'R06.3 Respiracao periodica'),
  ('R064', 'Hiperventilação', 'R06.4 Hiperventilacao'),
  ('R065', 'Respiração pela boca', 'R06.5 Respiracao p/boca'),
  ('R066', 'Soluço', 'R06.6 Soluco'),
  ('R067', 'Espirro', 'R06.7 Espirro'),
  ('R068', 'Outras anormalidades e as não especificadas da respiração', 'R06.8 Outr anormalidades e as NE da respiracao'),
  ('R07', 'Dor de garganta e no peito', 'R07 Dor de garganta e no peito'),
  ('R070', 'Dor de garganta', 'R07.0 Dor de garganta'),
  ('R071', 'Dor torácica ao respirar', 'R07.1 Dor toracica ao respirar'),
  ('R072', 'Dor precordial', 'R07.2 Dor precordial'),
  ('R073', 'Outra dor torácica', 'R07.3 Outr dor toracica'),
  ('R074', 'Dor torácica, não especificada', 'R07.4 Dor toracica NE'),
  ('R09', 'Outros sintomas e sinais relativos aos aparelhos circulatório e respiratório', 'R09 Outr sint sinais relat ap circulat respirat'),
  ('R090', 'Asfixia', 'R09.0 Asfixia'),
  ('R091', 'Pleurisia', 'R09.1 Pleurisia'),
  ('R092', 'Parada respiratória', 'R09.2 Parada respirat'),
  ('R093', 'Escarro anormal', 'R09.3 Escarro anormal'),
  ('R098', 'Outros sintomas e sinais especificados relativos aos aparelhos circulatório e respiratório', 'R09.8 Outr sint sinais espec rel ap circul respir'),
  ('R10', 'Dor abdominal e pélvica', 'R10 Dor abdominal e pelvica'),
  ('R100', 'Abdome agudo', 'R10.0 Abdome agudo'),
  ('R101', 'Dor localizada no abdome superior', 'R10.1 Dor localizada no abdome super'),
  ('R102', 'Dor pélvica e perineal', 'R10.2 Dor pelvica e perineal'),
  ('R103', 'Dor localizada em outras partes do abdome inferior', 'R10.3 Dor localizada em outr partes abdome infer'),
  ('R104', 'Outras dores abdominais e as não especificadas', 'R10.4 Outr dores abdominais e as NE'),
  ('R11', 'Náusea e vômitos', 'R11 Nausea e vomitos'),
  ('R11', 'Náusea e vômitos', 'R11 Nausea e vomitos'),
  ('R12', 'Pirose', 'R12 Pirose'),
  ('R12', 'Pirose', 'R12 Pirose'),
  ('R13', 'Disfagia', 'R13 Disfagia'),
  ('R13', 'Disfagia', 'R13 Disfagia'),
  ('R14', 'Flatulência e afecções correlatas', 'R14 Flatulencia e afeccoes correlatas'),
  ('R14', 'Flatulência e afecções correlatas', 'R14 Flatulencia e afeccoes correlatas'),
  ('R15', 'Incontinência fecal', 'R15 Incontinencia fecal'),
  ('R15', 'Incontinência fecal', 'R15 Incontinencia fecal'),
  ('R16', 'Hepatomegalia e esplenomegalia não classificadas em outra parte', 'R16 Hepatomegalia e esplenomegalia NCOP'),
  ('R160', 'Hepatomegalia não classificada em outra parte', 'R16.0 Hepatomegalia NCOP'),
  ('R161', 'Esplenomegalia não classificada em outra parte', 'R16.1 Esplenomegalia NCOP'),
  ('R162', 'Hepatomegalia com esplenomegalia não classificada em outra parte', 'R16.2 Hepatomegalia c/esplenomegalia NCOP'),
  ('R17', 'Icterícia não especificada', 'R17 Ictericia NE'),
  ('R17', 'Icterícia não especificada', 'R17 Ictericia NE'),
  ('R18', 'Ascite', 'R18 Ascite'),
  ('R18', 'Ascite', 'R18 Ascite'),
  ('R19', 'Outros sintomas e sinais relativos ao aparelho digestivo e ao abdome', 'R19 Outr sint e sinais relat ap digest abdome'),
  ('R190', 'Massa, tumoração ou tumefação intra-abdominal e pélvica', 'R19.0 Massa tumoracao tumefacao intra-abdom pelv'),
  ('R191', 'Ruídos hidroaéreos anormais', 'R19.1 Ruidos hidroaereos anormais'),
  ('R192', 'Peristaltismo visível', 'R19.2 Peristaltismo visivel'),
  ('R193', 'Rigidez abdominal', 'R19.3 Rigidez abdominal'),
  ('R194', 'Alteração do hábito intestinal', 'R19.4 Alteracao do habito intestinal'),
  ('R195', 'Outras anormalidades fecais', 'R19.5 Outr anormalidades fecais'),
  ('R196', 'Halitose', 'R19.6 Halitose'),
  ('R198', 'Outros sintomas e sinais especificados relativos ao aparelho digestivo e ao abdome', 'R19.8 Outr sint sinais esp relat ap digest abdome'),
  ('R20', 'Distúrbios da sensibilidade cutânea', 'R20 Disturbios da sensibilidade cutanea'),
  ('R200', 'Anestesia cutânea', 'R20.0 Anestesia cutanea'),
  ('R201', 'Hipoestesia cutânea', 'R20.1 Hipoestesia cutanea'),
  ('R202', 'Parestesias cutâneas', 'R20.2 Parestesias cutaneas'),
  ('R203', 'Hiperestesia', 'R20.3 Hiperestesia'),
  ('R208', 'Outros distúrbios e os não especificadas da sensibilidade cutânea', 'R20.8 Outr disturbios e NE sensibilidade cutanea'),
  ('R21', 'Eritema e outras erupções cutâneas não especificadas', 'R21 Eritema e outr erupcoes cutaneas NE'),
  ('R21', 'Eritema e outras erupções cutâneas não especificadas', 'R21 Eritema e outr erupcoes cutaneas NE'),
  ('R22', 'Tumefação, massa ou tumoração localizadas da pele e do tecido subcutâneo', 'R22 Tumefac massa tumoracao loc pele tec subcut'),
  ('R220', 'Tumefação, massa ou tumoração localizadas da cabeça', 'R22.0 Tumefacao massa tumoracao localizadas cabeca'),
  ('R221', 'Tumefação, massa ou tumoração localizadas do pescoço', 'R22.1 Tumefacao massa tumoracao localiz pescoco'),
  ('R222', 'Tumefação, massa ou tumoração localizadas do tronco', 'R22.2 Tumefacao massa tumoracao localizadas tronco'),
  ('R223', 'Tumefação, massa ou tumoração localizadas de membro superior', 'R22.3 Tumefacao massa tumoracao localiz membro sup'),
  ('R224', 'Tumefação, massa ou tumoração localizadas no membro inferior', 'R22.4 Tumefacao massa tumoracao localiz membro inf'),
  ('R227', 'Tumefação, massa ou tumoração localizadas de múltiplas localizações', 'R22.7 Tumefacao massa tumoracao localiz mult local'),
  ('R229', 'Tumefação, massa ou tumoração não especificadas, localizadas', 'R22.9 Tumefacao massa ou tumoracao NE localizadas'),
  ('R23', 'Outras alterações cutâneas', 'R23 Outr alteracoes cutaneas'),
  ('R230', 'Cianose', 'R23.0 Cianose'),
  ('R231', 'Palidez', 'R23.1 Palidez'),
  ('R232', 'Rubor', 'R23.2 Rubor'),
  ('R233', 'Equimoses espontâneas', 'R23.3 Equimoses espontaneas'),
  ('R234', 'Alterações na textura da pele', 'R23.4 Alteracoes na textura da pele'),
  ('R238', 'Outras alterações da pele e as não especificadas', 'R23.8 Outr alteracoes da pele e as NE'),
  ('R25', 'Movimentos involuntários anormais', 'R25 Movimentos involuntarios anormais'),
  ('R250', 'Movimentos anormais da cabeça', 'R25.0 Movimentos anormais da cabeca'),
  ('R251', 'Tremor não especificado', 'R25.1 Tremor NE'),
  ('R252', 'Cãibras e espasmos', 'R25.2 Caibras e espasmos'),
  ('R253', 'Fasciculação', 'R25.3 Fasciculacao'),
  ('R258', 'Outros movimentos involuntários anormais e os não especificados', 'R25.8 Outr movimentos involuntarios anormais e NE'),
  ('R26', 'Anormalidades da marcha e da mobilidade', 'R26 Anormalidades da marcha e da mobilidade'),
  ('R260', 'Marcha atáxica', 'R26.0 Marcha ataxica'),
  ('R261', 'Marcha paralítica', 'R26.1 Marcha paralitica'),
  ('R262', 'Dificuldade para andar não classificada em outra parte', 'R26.2 Dificuldade p/andar NCOP'),
  ('R268', 'Outras anormalidades da marcha e da mobilidade e as não especificadas', 'R26.8 Outr anormalidades marcha e mobilidade e NE'),
  ('R27', 'Outros distúrbios da coordenação', 'R27 Outr disturbios da coordenacao'),
  ('R270', 'Ataxia não especificada', 'R27.0 Ataxia NE'),
  ('R278', 'Outros distúrbios da coordenação e os não especificados', 'R27.8 Outr disturbios da coordenacao e os NE'),
  ('R29', 'Outros sintomas e sinais relativos aos sistemas nervoso e osteomuscular', 'R29 Outr sint sinais relat sist nerv osteomusc'),
  ('R290', 'Tetania', 'R29.0 Tetania'),
  ('R291', 'Meningismo', 'R29.1 Meningismo'),
  ('R292', 'Reflexos anormais', 'R29.2 Reflexos anormais'),
  ('R293', 'Postura anormal', 'R29.3 Postura anormal'),
  ('R294', 'Quadril estalante', 'R29.4 Quadril estalante'),
  ('R296', 'Tendência a queda, não classificada em outra parte', 'R29.6 Tendência a queda NCOP'),
  ('R298', 'Outros sintomas e sinais relativos aos sistemas nervoso e osteomuscular e os não especificados', 'R29.8 Out sint sinais rel sist nerv osteomusc e NE'),
  ('R30', 'Dor associada à micção', 'R30 Dor assoc a miccao'),
  ('R300', 'Disúria', 'R30.0 Disuria'),
  ('R301', 'Tenesmo vesical', 'R30.1 Tenesmo vesical'),
  ('R309', 'Micção dolorosa, não especificada', 'R30.9 Miccao dolorosa NE'),
  ('R31', 'Hematúria não especificada', 'R31 Hematuria NE'),
  ('R31', 'Hematúria não especificada', 'R31 Hematuria NE'),
  ('R32', 'Incontinência urinária não especificada', 'R32 Incontinencia urinaria NE'),
  ('R32', 'Incontinência urinária não especificada', 'R32 Incontinencia urinaria NE'),
  ('R33', 'Retenção urinária', 'R33 Retencao urinaria'),
  ('R33', 'Retenção urinária', 'R33 Retencao urinaria'),
  ('R34', 'Anúria e oligúria', 'R34 Anuria e oliguria'),
  ('R34', 'Anúria e oligúria', 'R34 Anuria e oliguria'),
  ('R35', 'Poliúria', 'R35 Poliuria'),
  ('R35', 'Poliúria', 'R35 Poliuria'),
  ('R36', 'Secreção uretral', 'R36 Secrecao uretral'),
  ('R36', 'Secreção uretral', 'R36 Secrecao uretral'),
  ('R39', 'Outros sintomas e sinais relativos ao aparelho urinário', 'R39 Outr sint e sinais relativos ap urinario'),
  ('R390', 'Extravasamento de urina', 'R39.0 Extravasamento de urina'),
  ('R391', 'Outras dificuldades à micção', 'R39.1 Outr dificuldades a miccao'),
  ('R392', 'Uremia extra-renal', 'R39.2 Uremia extra-renal'),
  ('R398', 'Outros sintomas e sinais relativos ao aparelho urinário e os não especificados', 'R39.8 Outr sint sinais relativos ap urinario e NE'),
  ('R40', 'Sonolência, estupor e coma', 'R40 Sonolencia estupor e coma'),
  ('R400', 'Sonolência', 'R40.0 Sonolencia'),
  ('R401', 'Estupor', 'R40.1 Estupor'),
  ('R402', 'Coma não especificado', 'R40.2 Coma NE'),
  ('R41', 'Outros sintomas e sinais relativos à função cognitiva e à consciência', 'R41 Outr sint sinais relat func cognit e consc'),
  ('R410', 'Desorientação não especificada', 'R41.0 Desorientacao NE'),
  ('R411', 'Amnésia anterógrada', 'R41.1 Amnesia anterograda'),
  ('R412', 'Amnésia retrógrada', 'R41.2 Amnesia retrograda'),
  ('R413', 'Outra amnésia', 'R41.3 Outr amnesia'),
  ('R418', 'Outros sintomas e sinais especificados relativos às funções cognitivas e à consciência', 'R41.8 Outr sint sinais esp rel func cognit e consc'),
  ('R42', 'Tontura e instabilidade', 'R42 Tontura e instabilidade'),
  ('R42', 'Tontura e instabilidade', 'R42 Tontura e instabilidade'),
  ('R43', 'Distúrbios do olfato e do paladar', 'R43 Disturbios do olfato e do paladar'),
  ('R430', 'Anosmia', 'R43.0 Anosmia'),
  ('R431', 'Parosmia', 'R43.1 Parosmia'),
  ('R432', 'Parageusia', 'R43.2 Parageusia'),
  ('R438', 'Outros distúrbios do olfato e do paladar e os não especificados', 'R43.8 Outr disturbios do olfato e do paladar e NE'),
  ('R44', 'Outros sintomas e sinais relativos às sensações e às percepções gerais', 'R44 Outr sint sinais relat sensac percep gerais'),
  ('R440', 'Alucinações auditivas', 'R44.0 Alucinacoes auditivas'),
  ('R441', 'Alucinações visuais', 'R44.1 Alucinacoes visuais'),
  ('R442', 'Outras alucinações', 'R44.2 Outr alucinacoes'),
  ('R443', 'Alucinações não especificadas', 'R44.3 Alucinacoes NE'),
  ('R448', 'Outros sintomas e sinais especificados relativos às sensações e percepções gerais', 'R44.8 Outr sint sinais espec rel sensac percep ger'),
  ('R45', 'Sintomas e sinais relativos ao estado emocional', 'R45 Sint e sinais relativos ao estado emocional'),
  ('R450', 'Nervosismo', 'R45.0 Nervosismo'),
  ('R451', 'Agitação e inquietação', 'R45.1 Agitacao e inquietacao'),
  ('R452', 'Tristeza', 'R45.2 Tristeza'),
  ('R453', 'Apatia e desinteresse', 'R45.3 Apatia e desinteresse'),
  ('R454', 'Irritabilidade e mau humor', 'R45.4 Irritabilidade e mau humor'),
  ('R455', 'Hostilidade', 'R45.5 Hostilidade'),
  ('R456', 'Violência física', 'R45.6 Violencia fisica'),
  ('R457', 'Estado de choque emocional e tensão, não especificado', 'R45.7 Estado de choque emocional e tensao NE'),
  ('R458', 'Outros sintomas e sinais relativos ao estado emocional', 'R45.8 Outr sint sinais relativos estado emocional'),
  ('R46', 'Sintomas e sinais relativos à aparência e ao comportamento', 'R46 Sint e sinais relativos aparencia e comport'),
  ('R460', 'Baixo nível de higiene pessoal', 'R46.0 Baixo nivel de higiene pessoal'),
  ('R461', 'Aparência pessoal bizarra', 'R46.1 Aparencia pessoal bizarra'),
  ('R462', 'Comportamento estranho e inexplicável', 'R46.2 Comport estranho e inexplicavel'),
  ('R463', 'Hiperatividade', 'R46.3 Hiperatividade'),
  ('R464', 'Lentidão e baixa reatividade', 'R46.4 Lentidao e baixa reatividade'),
  ('R465', 'Personalidade suspeita e evasiva', 'R46.5 Personalidade suspeita e evasiva'),
  ('R466', 'Inquietação e preocupação exageradas com acontecimentos estressantes', 'R46.6 Inquiet e preocup exageradas c/acont estress'),
  ('R467', 'Verborragia e pormenores circunstanciais mascarando o motivo da consulta', 'R46.7 Verborr pormenores circunst masc mot consult'),
  ('R468', 'Outros sintomas e sinais relativos à aparência e ao comportamento', 'R46.8 Outr sint sinais relativos aparencia comport'),
  ('R47', 'Distúrbios da fala não classificados em outra parte', 'R47 Disturbios da fala NCOP'),
  ('R470', 'Disfasia e afasia', 'R47.0 Disfasia e afasia'),
  ('R471', 'Disartria e anartria', 'R47.1 Disartria e anartria'),
  ('R478', 'Outros distúrbios da fala e os não especificados', 'R47.8 Outr disturbios da fala e os NE'),
  ('R48', 'Dislexia e outras disfunções simbólicas, não classificadas em outra parte', 'R48 Dislexia e outr disfuncoes simbolicas NCOP'),
  ('R480', 'Dislexia e alexia', 'R48.0 Dislexia e alexia'),
  ('R481', 'Agnosia', 'R48.1 Agnosia'),
  ('R482', 'Apraxia', 'R48.2 Apraxia'),
  ('R488', 'Outras disfunções simbólicas e as não especificadas', 'R48.8 Outr disfuncoes simbolicas e as NE'),
  ('R49', 'Distúrbios da voz', 'R49 Disturbios da voz'),
  ('R490', 'Disfonia', 'R49.0 Disfonia'),
  ('R491', 'Afonia', 'R49.1 Afonia'),
  ('R492', 'Hipernasalidade e hiponasalidade', 'R49.2 Hipernasalidade e hiponasalidade'),
  ('R498', 'Outros distúrbios da voz e os não especificados', 'R49.8 Outr disturbios da voz e os NE'),
  ('R50', 'Febre de origem desconhecida e de outras origens', 'R50 Febre origem desconhecida e outras origens'),
  ('R502', 'Febre induzida por drogas', 'R50.2 Febre induzida por drogas'),
  ('R508', 'Outra febre especificada', 'R50.8 Outra febre especificada'),
  ('R509', 'Febre não especificada', 'R50.9 Febre NE'),
  ('R51', 'Cefaléia', 'R51 Cefaleia'),
  ('R51', 'Cefaléia', 'R51 Cefaleia'),
  ('R52', 'Dor não classificada em outra parte', 'R52 Dor NCOP'),
  ('R520', 'Dor aguda', 'R52.0 Dor aguda'),
  ('R521', 'Dor crônica intratável', 'R52.1 Dor cronica intratavel'),
  ('R522', 'Outra dor crônica', 'R52.2 Outr dor cronica'),
  ('R529', 'Dor não especificada', 'R52.9 Dor NE'),
  ('R53', 'Mal estar, fadiga', 'R53 Mal estar fadiga'),
  ('R53', 'Mal estar, fadiga', 'R53 Mal estar fadiga'),
  ('R54', 'Senilidade', 'R54 Senilidade'),
  ('R54', 'Senilidade', 'R54 Senilidade'),
  ('R55', 'Síncope e colapso', 'R55 Sincope e colapso'),
  ('R55', 'Síncope e colapso', 'R55 Sincope e colapso'),
  ('R56', 'Convulsões, não classificadas em outra parte', 'R56 Convulsoes NCOP'),
  ('R560', 'Convulsões febris', 'R56.0 Convulsoes febris'),
  ('R568', 'Outras convulsões e as não especificadas', 'R56.8 Outr convulsoes e as NE'),
  ('R57', 'Choque não classificado em outra parte', 'R57 Choque NCOP'),
  ('R570', 'Choque cardiogênico', 'R57.0 Choque cardiogenico'),
  ('R571', 'Choque hipovolêmico', 'R57.1 Choque hipovolemico'),
  ('R578', 'Outras formas de choque', 'R57.8 Outr form de choque'),
  ('R579', 'Choque não especificado', 'R57.9 Choque NE'),
  ('R58', 'Hemorragia não classificada em outra parte', 'R58 Hemorragia NCOP'),
  ('R58', 'Hemorragia não classificada em outra parte', 'R58 Hemorragia NCOP'),
  ('R59', 'Aumento de volume dos gânglios linfáticos', 'R59 Aumento de volume dos ganglios linfaticos'),
  ('R590', 'Aumento de volume localizado de gânglios linfáticos', 'R59.0 Aumento volume localiz ganglios linfaticos'),
  ('R591', 'Aumento de volume generalizado de gânglios linfáticos', 'R59.1 Aumento volume generaliz ganglios linfaticos'),
  ('R599', 'Adenomegalia ou aumento de volume dos gânglios linfáticos, não especificado', 'R59.9 Adenomegalia aumento vol gangl linfaticos NE'),
  ('R60', 'Edema não classificado em outra parte', 'R60 Edema NCOP'),
  ('R600', 'Edema localizado', 'R60.0 Edema localizado'),
  ('R601', 'Edema generalizado', 'R60.1 Edema generalizado'),
  ('R609', 'Edema não especificado', 'R60.9 Edema NE'),
  ('R61', 'Hiperidrose', 'R61 Hiperidrose'),
  ('R610', 'Hiperidrose localizada', 'R61.0 Hiperidrose localizada'),
  ('R611', 'Hiperidrose generalizada', 'R61.1 Hiperidrose generalizada'),
  ('R619', 'Hiperidrose não especificada', 'R61.9 Hiperidrose NE'),
  ('R62', 'Retardo do desenvolvimento fisiológico normal', 'R62 Retardo do desenvolv fisiologico normal'),
  ('R620', 'Retardo de maturação', 'R62.0 Retardo de maturacao'),
  ('R628', 'Outras formas de retardo do desenvolvimento fisiológico normal', 'R62.8 Outr form retardo desenvolv fisiologico norm'),
  ('R629', 'Retardo do desenvolvimento fisiológico normal, não especificado', 'R62.9 Retardo do desenvolv fisiologico normal NE'),
  ('R63', 'Sintomas e sinais relativos à ingestão de alimentos e líquidos', 'R63 Sint sinais relat ingestao alimentos liquid'),
  ('R630', 'Anorexia', 'R63.0 Anorexia'),
  ('R631', 'Polidipsia', 'R63.1 Polidipsia'),
  ('R632', 'Polifagia', 'R63.2 Polifagia'),
  ('R633', 'Dificuldades de alimentação e erros na administração de alimentos', 'R63.3 Dificuld alimentacao erros admin alimentos'),
  ('R634', 'Perda de peso anormal', 'R63.4 Perda de peso anormal'),
  ('R635', 'Ganho de peso anormal', 'R63.5 Ganho de peso anormal'),
  ('R638', 'Outros sintomas e sinais relativos a ingestão de alimentos e de líquidos', 'R63.8 Outr sint sinais rel ingestao alimentos liq'),
  ('R64', 'Caquexia', 'R64 Caquexia'),
  ('R64', 'Caquexia', 'R64 Caquexia'),
  ('R68', 'Outros sintomas e sinais gerais', 'R68 Outr sint e sinais gerais'),
  ('R680', 'Hipotermia não associada à baixa temperatura ambiental', 'R68.0 Hipotermia nao assoc baixa temperat ambient'),
  ('R681', 'Sintomas não específicos peculiares à infância', 'R68.1 Sint nao especificos peculiares a infancia'),
  ('R682', 'Boca seca, não especificada', 'R68.2 Boca seca NE'),
  ('R683', 'Baqueteamento dos dedos', 'R68.3 Baqueteamento dos dedos'),
  ('R688', 'Outros sintomas e sinais gerais especificados', 'R68.8 Outr sint e sinais gerais espec'),
  ('R69', 'Causas desconhecidas e não especificadas de morbidade', 'R69 Causas desconhecidas e NE de morbidade'),
  ('R69', 'Causas desconhecidas e não especificadas de morbidade', 'R69 Causas desconhecidas e NE de morbidade'),
  ('R70', 'Velocidade de hemossedimentação elevada e outras anormalidades da viscosidade plasmática', 'R70 Veloc hemossedim elev outr anorm visc plasm'),
  ('R700', 'Velocidade de hemossedimentação elevada', 'R70.0 Velocidade de hemossedimentacao elevada'),
  ('R701', 'Viscosidade plasmática anormal', 'R70.1 Viscosidade plasmatica anormal'),
  ('R71', 'Anormalidade das hemácias', 'R71 Anormalidade das hemacias'),
  ('R71', 'Anormalidade das hemácias', 'R71 Anormalidade das hemacias'),
  ('R72', 'Anormalidade dos leucócitos não classificada em outra parte', 'R72 Anormalidade dos leucocitos NCOP'),
  ('R72', 'Anormalidade dos leucócitos não classificada em outra parte', 'R72 Anormalidade dos leucocitos NCOP'),
  ('R73', 'Aumento da glicemia', 'R73 Aumento da glicemia'),
  ('R730', 'Teste de tolerância a glicose anormal', 'R73.0 Teste de tolerancia a glicose anormal'),
  ('R739', 'Hiperglicemia não especificada', 'R73.9 Hiperglicemia NE'),
  ('R74', 'Anormalidades dos níveis de enzimas séricas', 'R74 Anormalidades dos niveis de enzimas sericas'),
  ('R740', 'Aumento dos níveis de transaminases e da desidrogenase lática (DHL)', 'R74.0 Aumento niv transaminases desidrogen latica'),
  ('R748', 'Níveis anormais de outras enzimas séricas', 'R74.8 Niveis anormais de outr enzimas sericas'),
  ('R749', 'Anormalidade dos níveis de enzimas séricas, não especificada', 'R74.9 Anormalidade dos niveis enzimas sericas NE'),
  ('R75', 'Evidência laboratorial do vírus da imunodeficiência humana (HIV)', 'R75 Evidencia laboratorial do HIV'),
  ('R75', 'Evidência laboratorial do vírus da imunodeficiência humana (HIV)', 'R75 Evidencia laboratorial do HIV'),
  ('R76', 'Outros achados imunológicos anormais no soro', 'R76 Outr achados imunologicos anormais no soro'),
  ('R760', 'Título aumentado de anticorpos', 'R76.0 Titulo aumentado de anticorpos'),
  ('R761', 'Reação anormal ao teste da tuberculina', 'R76.1 Reacao anormal ao teste da tuberculina'),
  ('R762', 'Exame sorológico falso positivo para sífilis', 'R76.2 Exame sorologico falso positivo p/sifilis'),
  ('R768', 'Outros achados imunológicos especificados anormais no soro', 'R76.8 Outr achados imunologicos espec anorm soro'),
  ('R769', 'Achado anormal de exame imunológico sérico, não especificado', 'R76.9 Achado anormal exame imunologico serico NE'),
  ('R77', 'Outras anormalidades das proteínas plasmáticas', 'R77 Outr anormalidades das proteinas plasmaticas'),
  ('R770', 'Anormalidade da albumina', 'R77.0 Anormalidade da albumina'),
  ('R771', 'Anormalidade das globulinas', 'R77.1 Anormalidade das globulinas'),
  ('R772', 'Anormalidade da alfafetoproteína', 'R77.2 Anormalidade da alfafetoproteina'),
  ('R778', 'Outras anormalidades especificadas das proteínas plasmáticas', 'R77.8 Outr anormalidades espec proteinas plasmatic'),
  ('R779', 'Anormalidades de proteína plasmática, não especificadas', 'R77.9 Anormalidades de proteina plasmatica NE'),
  ('R78', 'Presença de drogas e de outras substâncias normalmente não encontradas no sangue', 'R78 Presenca drog outr subst norm n encontr sang'),
  ('R780', 'Presença de álcool no sangue', 'R78.0 Presenca de alcool no sangue'),
  ('R781', 'Presença de opiáceos no sangue', 'R78.1 Presenca de opiaceos no sangue'),
  ('R782', 'Presença de cocaína no sangue', 'R78.2 Presenca de cocaina no sangue'),
  ('R783', 'Presença de alucinógeno no sangue', 'R78.3 Presenca de alucinogeno no sangue'),
  ('R784', 'Presença de outras drogas com potencial de causar dependência, no sangue', 'R78.4 Presenca outr drog potenc caus depend sangue'),
  ('R785', 'Presença de droga psicotrópica no sangue', 'R78.5 Presenca de droga psicotropica no sangue'),
  ('R786', 'Presença de agente esteróide no sangue', 'R78.6 Presenca de agente esteroide no sangue'),
  ('R787', 'Presença de nível anormal de metais pesados no sangue', 'R78.7 Presenca nivel anormal metais pesados sangue'),
  ('R788', 'Presença de outras substâncias especificadas não normalmente encontradas no sangue', 'R78.8 Presenc outr subst espec n norm encontr sang'),
  ('R789', 'Presença de substância não especificada normalmente não encontrada no sangue', 'R78.9 Presenca subst NE norm nao encontrada sangue'),
  ('R79', 'Outros achados anormais de exames químicos do sangue', 'R79 Outr achados anormais exames quimicos sangue'),
  ('R790', 'Anormalidade do nível de elementos minerais no sangue', 'R79.0 Anormalidade nivel elementos minerais sangue'),
  ('R798', 'Outros achados anormais especificados de exames químicos do sangue', 'R79.8 Outr achados anormais espec exames quim sang'),
  ('R799', 'Achado anormal de exame químico do sangue, não especificado', 'R79.9 Achado anormal de exame quimico do sangue NE'),
  ('R80', 'Proteinúria isolada', 'R80 Proteinuria isolada'),
  ('R80', 'Proteinúria isolada', 'R80 Proteinuria isolada'),
  ('R81', 'Glicosúria', 'R81 Glicosuria'),
  ('R81', 'Glicosúria', 'R81 Glicosuria'),
  ('R82', 'Outros achados anormais na urina', 'R82 Outr achados anormais na urina'),
  ('R820', 'Quilúria', 'R82.0 Quiluria'),
  ('R821', 'Mioglobinúria', 'R82.1 Mioglobinuria'),
  ('R822', 'Biliúria', 'R82.2 Biliuria'),
  ('R823', 'Hemoglobinúria', 'R82.3 Hemoglobinuria'),
  ('R824', 'Acetonúria', 'R82.4 Acetonuria'),
  ('R825', 'Níveis urinários elevados de drogas, medicamentos e substâncias biológicas', 'R82.5 Niveis urinar elev drogas medic subst biolog'),
  ('R826', 'Níveis urinários anormais de substâncias cuja origem é essencialmente não-medicinal', 'R82.6 Niveis urinar anorm subst orig essen n-medic'),
  ('R827', 'Achados anormais ao exame microbiológico da urina', 'R82.7 Achados anormais exame microbiologico urina'),
  ('R828', 'Achados anormais ao exame citológico e histológico da urina', 'R82.8 Achados anorm exame citolog histolog urina'),
  ('R829', 'Outros achados anormais na urina e os não especificados', 'R82.9 Outr achados anormais na urina e os NE'),
  ('R83', 'Achados anormais no líquido cefalorraquidiano', 'R83 Achados anormais liquido cefalorraquidiano'),
  ('R830', 'Achados anormais no líquido cefalorraquidiano - nível enzimático anormal', 'R83.0 Nivel enzimatico anormal'),
  ('R831', 'Achados anormais no líquido cefalorraquidiano - nível hormonal anormal', 'R83.1 Nivel hormonal anormal'),
  ('R832', 'Achados anormais no líquido cefalorraquidiano - nível anormal de outras drogas, medicamentos e substâncias biológicas', 'R83.2 Nivel anormal outr drog medic subst biologic'),
  ('R833', 'Achados anormais no líquido cefalorraquidiano - nível anormal de substâncias cuja origem é essencialmente não medicinal', 'R83.3 Nivel anormal subst origem essenc nao medic'),
  ('R834', 'Achados anormais no líquido cefalorraquidiano - achados imunológicos anormais', 'R83.4 Achados imunologicos anormais'),
  ('R835', 'Achados anormais no líquido cefalorraquidiano - achados microbiológicos anormais', 'R83.5 Achados microbiologicos anormais'),
  ('R836', 'Achados anormais no líquido cefalorraquidiano - achados citológicos anormais', 'R83.6 Achados citologicos anormais'),
  ('R837', 'Achados anormais no líquido cefalorraquidiano - achados histológicos anormais', 'R83.7 Achados histolog anormais'),
  ('R838', 'Achados anormais no líquido cefalorraquidiano - outros achados anormais', 'R83.8 Outr achados anormais'),
  ('R839', 'Achados anormais no líquido cefalorraquidiano - achado anormal não especificado', 'R83.9 Achado anormal NE'),
  ('R84', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax', 'R84 Achados anormais mat prov org respirat torax'),
  ('R840', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - nível enzimático anormal', 'R84.0 Nivel enzimatico anormal'),
  ('R841', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - nível hormonal anormal', 'R84.1 Nivel hormonal anormal'),
  ('R842', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - nível anormal de outras drogas, medicamentos e substâncias biológicas', 'R84.2 Nivel anormal outr drog medic subst biolog'),
  ('R843', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - nível anormal de substâncias cuja origem é essencialmente não medicinal', 'R84.3 Nivel anormal subst orig essenc nao medic'),
  ('R844', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - achados imunológicos anormais', 'R84.4 Achados imunologicos anormais'),
  ('R845', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - achados microbiológicos anormais', 'R84.5 Achados microbiologicos anormais'),
  ('R846', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - achados citológicos anormais', 'R84.6 Achados citologicos anormais'),
  ('R847', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - achados histológicos anormais', 'R84.7 Achados histolog anormais'),
  ('R848', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - outros achados anormais', 'R84.8 Outr achados anormais'),
  ('R849', 'Achados anormais de material proveniente dos órgãos respiratórios e do tórax - achado anormal não especificado', 'R84.9 Achado anormal NE'),
  ('R85', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal', 'R85 Achados anorm mat prov org digest cav abdom'),
  ('R850', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - nível enzimático anormal', 'R85.0 Nivel enzimatico anormal'),
  ('R851', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - nível hormonal anormal', 'R85.1 Nivel hormonal anormal'),
  ('R852', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - nível anormal de outras drogas, medicamentos e substâncias biológicas', 'R85.2 Nivel anormal outr drog medic subst biolog'),
  ('R853', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - nível anormal de substâncias cuja origem é essencialmente não medicinal', 'R85.3 Nivel anormal subst origem essenc nao medic'),
  ('R854', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - achados imunológicos anormais', 'R85.4 Achados imunologicos anormais'),
  ('R855', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - achados microbiológicos anormais', 'R85.5 Achados microbiologicos anormais'),
  ('R856', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - achados citológicos anormais', 'R85.6 Achados citologicos anormais'),
  ('R857', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - achados histológicos anormais', 'R85.7 Achados histolog anormais'),
  ('R858', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - outros achados anormais', 'R85.8 Outr achados anormais'),
  ('R859', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal - achado anormal não especificado', 'R85.9 Achado anormal NE'),
  ('R86', 'Achados anormais de material proveniente dos órgãos genitais masculinos', 'R86 Achados anormais mat prov org genitais masc'),
  ('R860', 'Achados anormais de material proveniente dos órgãos genitais masculinos - nível enzimático anormal', 'R86.0 Nivel enzimatico anormal'),
  ('R861', 'Achados anormais de material proveniente dos órgãos genitais masculinos - nível hormonal anormal', 'R86.1 Nivel hormonal anormal'),
  ('R862', 'Achados anormais de material proveniente dos órgãos genitais masculinos - nível anormal de outras drogas, medicamentos e substâncias biológicas', 'R86.2 Nivel anormal outr drog medic subst biolog'),
  ('R863', 'Achados anormais de material proveniente dos órgãos genitais masculinos - nível anormal de substâncias cuja origem é essencialmente não medicinal', 'R86.3 Nivel anormal subst origem essenc nao medic'),
  ('R864', 'Achados anormais de material proveniente dos órgãos genitais masculinos - achados imunológicos anormais', 'R86.4 Achados imunologicos anormais'),
  ('R865', 'Achados anormais de material proveniente dos órgãos genitais masculinos - achados microbiológicos anormais', 'R86.5 Achados microbiologicos anormais'),
  ('R866', 'Achados anormais de material proveniente dos órgãos genitais masculinos - achados citológicos anormais', 'R86.6 Achados citologicos anormais'),
  ('R867', 'Achados anormais de material proveniente dos órgãos genitais masculinos - achados histológicos anormais', 'R86.7 Achados histolog anormais'),
  ('R868', 'Achados anormais de material proveniente dos órgãos genitais masculinos - outros achados anormais', 'R86.8 Outr achados anormais'),
  ('R869', 'Achados anormais de material proveniente dos órgãos genitais masculinos - achado anormal não especificado', 'R86.9 Achado anormal NE'),
  ('R87', 'Achados anormais de material proveniente dos órgãos genitais femininos', 'R87 Achados anormais mat prov org genitais femin'),
  ('R870', 'Achados anormais de material proveniente dos órgãos genitais femininos - nível enzimático anormal', 'R87.0 Nivel enzimatico anormal'),
  ('R871', 'Achados anormais de material proveniente dos órgãos genitais femininos - nível hormonal anormal', 'R87.1 Nivel hormonal anormal'),
  ('R872', 'Achados anormais de material proveniente dos órgãos genitais femininos - nível anormal de outras drogas, medicamentos e substâncias biológicas', 'R87.2 Nivel anormal outr drog medic subst biolog'),
  ('R873', 'Achados anormais de material proveniente dos órgãos genitais femininos - nível anormal de substâncias cuja origem é essencialmente não medicinal', 'R87.3 Nivel anormal subst origem essenc nao medic'),
  ('R874', 'Achados anormais de material proveniente dos órgãos genitais femininos - achados imunológicos anormais', 'R87.4 Achados imunologicos anormais'),
  ('R875', 'Achados anormais de material proveniente dos órgãos genitais femininos - achados microbiológicos anormais', 'R87.5 Achados microbiologicos anormais'),
  ('R876', 'Achados anormais de material proveniente dos órgãos genitais femininos - achados citológicos anormais', 'R87.6 Achados citologicos anormais'),
  ('R877', 'Achados anormais de material proveniente dos órgãos genitais femininos - achados histológicos anormais', 'R87.7 Achados histolog anormais'),
  ('R878', 'Achados anormais de material proveniente dos órgãos genitais femininos - outros achados anormais', 'R87.8 Outr achados anormais'),
  ('R879', 'Achados anormais de material proveniente dos órgãos genitais femininos - achado anormal não especificado', 'R87.9 Achado anormal NE'),
  ('R89', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos', 'R89 Achados anorms mat prov outr org ap sist tec'),
  ('R890', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - nível enzimático anormal', 'R89.0 Nivel enzimatico anormal'),
  ('R891', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - nível hormonal anormal', 'R89.1 Nivel hormonal anormal'),
  ('R892', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - nível anormal de outras drogas, medicamentos e substâncias biológicas', 'R89.2 Nivel anormal outr drog medic subst biolog'),
  ('R893', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - nível anormal de substâncias cuja origem é essencialmente não medicinal', 'R89.3 Nivel anormal subst origem essenc nao medic'),
  ('R894', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - achados imunológicos anormais', 'R89.4 Achados imunologicos anormais'),
  ('R895', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - achados microbiológicos anormais', 'R89.5 Achados microbiologicos anormais'),
  ('R896', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - achados citológicos anormais', 'R89.6 Achados citologicos anormais'),
  ('R897', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - achados histológicos anormais', 'R89.7 Achados histolog anormais'),
  ('R898', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - outros achados anormais', 'R89.8 Outr achados anormais'),
  ('R899', 'Achados anormais de material proveniente de outros órgãos, aparelhos, sistemas e tecidos - achado anormal não especificado', 'R89.9 Achado anormal NE'),
  ('R90', 'Resultados anormais de exames para diagnóstico por imagem do sistema nervoso central', 'R90 Result anorm exam diagn imag sist nerv centr'),
  ('R900', 'Lesão intracraniana ocupando espaço', 'R90.0 Lesao intracraniana ocupando espaco'),
  ('R908', 'Outros resultados anormais de exames para diagnóstico por imagem do sistema nervoso central', 'R90.8 Out resul anorm exam diag imag sis nerv cent'),
  ('R91', 'Achados anormais, de exames para diagnóstico por imagem, do pulmão', 'R91 Achados anorm exames diagn imagem do pulmao'),
  ('R91', 'Achados anormais, de exames para diagnóstico por imagem, do pulmão', 'R91 Achados anorm exames diagn imagem do pulmao'),
  ('R92', 'Achados anormais, de exames para diagnóstico por imagem, da mama', 'R92 Achados anorm exames diagn imagem da mama'),
  ('R92', 'Achados anormais, de exames para diagnóstico por imagem, da mama', 'R92 Achados anorm exames diagn imagem da mama'),
  ('R93', 'Achados anormais de exames para diagnóstico por imagem de outras estruturas do corpo', 'R93 Achados anorm exam diagn imag out estr corp'),
  ('R930', 'Achados anormais de exames para diagnóstico por imagem do crânio e da cabeça não classificados em outra parte', 'R93.0 Achados anorm ex diag imag cran cabeca NCOP'),
  ('R931', 'Achados anormais de exames para diagnóstico por imagem do coração e da circulação coronariana', 'R93.1 Achados anorm ex diag imag corac circ coron'),
  ('R932', 'Achados anormais de exames para diagnóstico por imagem do fígado e das vias biliares', 'R93.2 Achados anorm ex diag imag figado via biliar'),
  ('R933', 'Achados anormais de exames para diagnóstico por imagem de outras partes do tubo digestivo', 'R93.3 Achados anorm ex diag imag outr part tub dig'),
  ('R934', 'Achados anormais de exames para diagnóstico por imagem dos órgãos urinários', 'R93.4 Achados anorm exam diagn imagem org urinar'),
  ('R935', 'Achados anormais de exames para diagnóstico por imagem de outras regiões do abdome, incluindo o retroperitônio', 'R93.5 Achados anorm ex diag imag out reg abd retr'),
  ('R936', 'Achados anormais de exames para diagnóstico por imagem dos membros', 'R93.6 Achados anorm exam diagn imagem dos membros'),
  ('R937', 'Achados anormais de exames para diagnóstico por imagem de outras partes do sistema osteomuscular', 'R93.7 Achados anorm ex diag imag outr sist osteom'),
  ('R938', 'Achados anormais de exames diagnósticos por imagem de outras estruturas somáticas especificadas', 'R93.8 Achados anorm ex diag imag out estr soma esp'),
  ('R94', 'Resultados anormais de estudos de função', 'R94 Resultados anormais de estudos de funcao'),
  ('R940', 'Resultados anormais de estudos de função do sistema nervoso central', 'R94.0 Result anorm estudos funcao sist nerv centr'),
  ('R941', 'Resultados anormais de estudos de função do sistema nervoso periférico e dos órgãos dos sentidos', 'R94.1 Result anorm est func sis nerv peri org sent'),
  ('R942', 'Resultados anormais de estudos da função pulmonar', 'R94.2 Result anorm de estudos da funcao pulmonar'),
  ('R943', 'Resultados anormais de estudos da função cardiovascular', 'R94.3 Result anorm estudos funcao cardiovascular'),
  ('R944', 'Resultados anormais de estudos de função renal', 'R94.4 Resultados anormais de estudos funcao renal'),
  ('R945', 'Resultados anormais de estudos de função hepática', 'R94.5 Resultados anormais estudos funcao hepatica'),
  ('R946', 'Resultados anormais de estudos de função tireoidiana', 'R94.6 Resultados anorm estudos funcao tireoidiana'),
  ('R947', 'Resultados anormais de estudos de função de outras glândulas endócrinas', 'R94.7 Result anorm estudos funcao out gland endocr'),
  ('R948', 'Resultados anormais de estudos de função de outros órgãos, aparelhos e sistemas', 'R94.8 Result anorm estudos funcao outr org ap sist'),
  ('R95', 'Síndrome da morte súbita na infância', 'R95 Sindr da morte subita na infancia'),
  ('R95', 'Síndrome da morte súbita na infância', 'R95 Sindr da morte subita na infancia'),
  ('R96', 'Outras mortes súbitas de causa desconhecida', 'R96 Outr mortes subitas de causa desconhecida'),
  ('R960', 'Morte instantânea', 'R96.0 Morte instantanea'),
  ('R961', 'Morte que ocorre em menos de 24 horas após o início dos sintomas, que não pode ser explicada', 'R96.1 Morte ocorr menos 24h apos inic sint n expl'),
  ('R98', 'Morte sem assistência', 'R98 Morte s/assist'),
  ('R98', 'Morte sem assistência', 'R98 Morte s/assist'),
  ('R99', 'Outras causas mal definidas e as não especificadas de mortalidade', 'R99 Outr causas mal definidas e NE mortalidade'),
  ('R99', 'Outras causas mal definidas e as não especificadas de mortalidade', 'R99 Outr causas mal definidas e NE mortalidade');
