INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('I00', 'Febre reumática sem menção de comprometimento do coração', 'I00 Febre reumatica s/mencao de compr do coracao'),
  ('I00', 'Febre reumática sem menção de comprometimento do coração', 'I00 Febre reumatica s/mencao de compr do coracao'),
  ('I01', 'Febre reumática com comprometimento do coração', 'I01 Febre reumatica c/compr do coracao'),
  ('I010', 'Pericardite reumática aguda', 'I01.0 Pericardite reumatica aguda'),
  ('I011', 'Endocardite reumática aguda', 'I01.1 Endocardite reumatica aguda'),
  ('I012', 'Miocardite reumática aguda', 'I01.2 Miocardite reumatica aguda'),
  ('I018', 'Outras formas de doença cardíaca reumática aguda', 'I01.8 Outr form de doenc cardiaca reumatica aguda'),
  ('I019', 'Doença cardíaca reumática aguda não especificada', 'I01.9 Doenc cardiaca reumatica aguda NE'),
  ('I02', 'Coréia reumática', 'I02 Coreia reumatica'),
  ('I020', 'Coréia reumática com comprometimento cardíaco', 'I02.0 Coreia reumatica c/compr cardiaco'),
  ('I029', 'Coréia reumática sem comprometimento cardíaco', 'I02.9 Coreia reumatica s/compr cardiaco'),
  ('I05', 'Doenças reumáticas da valva mitral', 'I05 Doenc reumaticas da valva mitral'),
  ('I050', 'Estenose mitral', 'I05.0 Estenose mitral'),
  ('I051', 'Insuficiência mitral reumática', 'I05.1 Insuf mitral reumatica'),
  ('I052', 'Estenose mitral com insuficiência', 'I05.2 Estenose mitral c/insuf'),
  ('I058', 'Outras doenças da valva mitral', 'I05.8 Outr doenc da valva mitral'),
  ('I059', 'Doença não especificada da valva mitral', 'I05.9 Doenc NE da valva mitral'),
  ('I06', 'Doenças reumáticas da valva aórtica', 'I06 Doenc reumaticas da valva aortica'),
  ('I060', 'Estenose aórtica reumática', 'I06.0 Estenose aortica reumatica'),
  ('I061', 'Insuficiência aórtica reumática', 'I06.1 Insuf aortica reumatica'),
  ('I062', 'Estenose aórtica reumática com insuficiência', 'I06.2 Estenose aortica reumatica c/insuf'),
  ('I068', 'Outras doenças reumáticas da valva aórtica', 'I06.8 Outr doenc reumaticas da valva aortica'),
  ('I069', 'Doença reumática da valva aórtica, não especificada', 'I06.9 Doenc reumatica da valva aortica NE'),
  ('I07', 'Doenças reumáticas da valva tricúspide', 'I07 Doenc reumaticas da valva tricuspide'),
  ('I070', 'Estenose tricúspide', 'I07.0 Estenose tricuspide'),
  ('I071', 'Insuficiência tricúspide', 'I07.1 Insuf tricuspide'),
  ('I072', 'Estenose tricúspide com insuficiência', 'I07.2 Estenose tricuspide c/insuf'),
  ('I078', 'Outras doenças da valva tricúspide', 'I07.8 Outr doenc da valva tricuspide'),
  ('I079', 'Doença não especificada da valva tricúspide', 'I07.9 Doenc NE da valva tricuspide'),
  ('I08', 'Doenças de múltiplas valvas', 'I08 Doenc de mult valvas'),
  ('I080', 'Transtornos de valvas mitral e aórtica', 'I08.0 Transt de valvas mitral e aortica'),
  ('I081', 'Transtornos de ambas as valvas mitral e tricúspide', 'I08.1 Transt de ambas as valvas mitral tricuspide'),
  ('I082', 'Transtornos de ambas as valvas aórtica e tricúspide', 'I08.2 Transt de ambas as valvas aortica tricuspide'),
  ('I083', 'Transtornos das valvas mitral, aórtica e tricúspide', 'I08.3 Transt das valvas mitral aortica tricuspide'),
  ('I088', 'Outras doenças de múltiplas valvas', 'I08.8 Outr doenc de mult valvas'),
  ('I089', 'Doença não especificada de múltiplas valvas', 'I08.9 Doenc NE de mult valvas'),
  ('I09', 'Outras doenças reumáticas do coração', 'I09 Outr doenc reumaticas do coracao'),
  ('I090', 'Miocardite reumática', 'I09.0 Miocardite reumatica'),
  ('I091', 'Doenças reumáticas do endocárdio, valva não especificada', 'I09.1 Doenc reumaticas do endocardio valva NE'),
  ('I092', 'Pericardite reumática crônica', 'I09.2 Pericardite reumatica cronica'),
  ('I098', 'Outras doenças reumáticas especificadas do coração', 'I09.8 Outr doenc reumaticas espec do coracao'),
  ('I099', 'Doença cardíaca reumática não especificada', 'I09.9 Doenc cardiaca reumatica NE'),
  ('I10', 'Hipertensão essencial (primária)', 'I10 Hipertensao essencial'),
  ('I10', 'Hipertensão essencial (primária)', 'I10 Hipertensao essencial'),
  ('I11', 'Doença cardíaca hipertensiva', 'I11 Doenc cardiaca hipertensiva'),
  ('I110', 'Doença cardíaca hipertensiva com insuficiência cardíaca (congestiva)', 'I11.0 Doenc cardiaca hipertensiva c/insuf cardiaca'),
  ('I119', 'Doença cardíaca hipertensiva sem insuficiência cardíaca (congestiva)', 'I11.9 Doenc cardiaca hipertensiva s/insuf cardiaca'),
  ('I12', 'Doença renal hipertensiva', 'I12 Doenc renal hipertensiva'),
  ('I120', 'Doença renal hipertensiva com insuficiência renal', 'I12.0 Doenc renal hipertensiva c/insuf renal'),
  ('I129', 'Doença renal hipertensiva sem insuficiência renal', 'I12.9 Doenc renal hipertensiva s/insuf renal'),
  ('I13', 'Doença cardíaca e renal hipertensiva', 'I13 Doenc cardiaca e renal hipertensiva'),
  ('I130', 'Doença cardíaca e renal hipertensiva com insuficiência cardíaca (congestiva)', 'I13.0 Doenc cardiaca e renal hipert c/insufic card'),
  ('I131', 'Doença cardíaca e renal hipertensiva com insuficiência renal', 'I13.1 Doenc cardiaca e renal hipert c/insuf renal'),
  ('I132', 'Doença cardíaca e renal hipertensiva com insuficiência cardíaca (congestiva) e insuficiência renal', 'I13.2 Doenc card renal hipert c/insuf card e renal'),
  ('I139', 'Doença cardíaca e renal hipertensiva, não especificada', 'I13.9 Doenc cardiaca e renal hipertensiva NE'),
  ('I15', 'Hipertensão secundária', 'I15 Hipertensao secund'),
  ('I150', 'Hipertensão renovascular', 'I15.0 Hipertensao renovascular'),
  ('I151', 'Hipertensão secundária a outras afecções renais', 'I15.1 Hipertensao secund a outr afeccoes renais'),
  ('I152', 'Hipertensão secundária a afecções endócrinas', 'I15.2 Hipertensao secund a afeccoes endocrinas'),
  ('I158', 'Outras formas de hipertensão secundária', 'I15.8 Outr form de hipertensao secund'),
  ('I159', 'Hipertensão secundária, não especificada', 'I15.9 Hipertensao secund NE'),
  ('I20', 'Angina pectoris', 'I20 Angina pectoris'),
  ('I200', 'Angina instável', 'I20.0 Angina instavel'),
  ('I201', 'Angina pectoris com espasmo documentado', 'I20.1 Angina pectoris c/espasmo documentado'),
  ('I208', 'Outras formas de angina pectoris', 'I20.8 Outr form de angina pectoris'),
  ('I209', 'Angina pectoris, não especificada', 'I20.9 Angina pectoris NE'),
  ('I21', 'Infarto agudo do miocárdio', 'I21 Infarto agudo do miocardio'),
  ('I210', 'Infarto agudo transmural da parede anterior do miocárdio', 'I21.0 Infarto agudo transmural parede ant miocard'),
  ('I211', 'Infarto agudo transmural da parede inferior do miocárdio', 'I21.1 Infarto agudo transmural parede inf miocard'),
  ('I212', 'Infarto agudo transmural do miocárdio de outras localizações', 'I21.2 Infarto agudo transmural miocardio outr loc'),
  ('I213', 'Infarto agudo transmural do miocárdio, de localização não especificada', 'I21.3 Infarto agudo transmural miocardio loc NE'),
  ('I214', 'Infarto agudo subendocárdico do miocárdio', 'I21.4 Infarto agudo subendocardico do miocardio'),
  ('I219', 'Infarto agudo do miocárdio não especificado', 'I21.9 Infarto agudo do miocardio NE'),
  ('I22', 'Infarto do miocárdio recorrente', 'I22 Infarto do miocardio recorrente'),
  ('I220', 'Infarto do miocárdio recorrente da parede anterior', 'I22.0 Infarto do miocardio recorrente parede ant'),
  ('I221', 'Infarto do miocárdio recorrente da parede inferior', 'I22.1 Infarto do miocardio recorrente parede infer'),
  ('I228', 'Infarto do miocárdio recorrente de outras localizações', 'I22.8 Infarto do miocardio recorrente outr localiz'),
  ('I229', 'Infarto do miocárdio recorrente de localização não especificada', 'I22.9 Infarto do miocardio recorrente localiz NE'),
  ('I23', 'Algumas complicações atuais subseqüentes ao infarto agudo do miocárdio', 'I23 Alg complic atuais subs infarto agud miocard'),
  ('I230', 'Hemopericárdio como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.0 Hemoperic c/compl subs infart agud miocard'),
  ('I231', 'Comunicação interatrial como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.1 Com interatr c/comp atual subs inf agud mioc'),
  ('I232', 'Comunicação interventricular como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.2 Com interven c/comp atual subs inf agud mioc'),
  ('I233', 'Ruptura da parede do coração sem ocorrência de hemopericárdio como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.3 Rupt par cor s/hemop c/comp subs inf ag mioc'),
  ('I234', 'Ruptura de cordoalhas tendíneas como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.4 Rupt cord tend c/comp atual subs inf ag mioc'),
  ('I235', 'Ruptura de músculos papilares como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.5 Rupt musc pap c/comp atual subs inf ag mioc'),
  ('I236', 'Trombose de átrio, aurícula e ventrículo como complicação atual subseqüente ao infarto agudo do miocárdio', 'I23.6 Tromb atr aur/vent c/comp at sub inf ag mioc'),
  ('I238', 'Outras complicações atuais subseqüentes ao infarto agudo do miocárdio', 'I23.8 Outr complic atuais subs infart agud miocard'),
  ('I24', 'Outras doenças isquêmicas agudas do coração', 'I24 Outr doenc isquemicas agudas do coracao'),
  ('I240', 'Trombose coronária que não resulta em infarto do miocárdio', 'I24.0 Tromb coronaria q n result infarto miocardio'),
  ('I241', 'Síndrome de Dressler', 'I24.1 Sindr de Dressler'),
  ('I248', 'Outras formas de doença isquêmica aguda do coração', 'I24.8 Outr form doenc isquemica aguda do coracao'),
  ('I249', 'Doença isquêmica aguda do coração não especificada', 'I24.9 Doenc isquemica aguda do coracao NE'),
  ('I25', 'Doença isquêmica crônica do coração', 'I25 Doenc isquemica cronica do coracao'),
  ('I250', 'Doença cardiovascular aterosclerótica, descrita desta maneira', 'I25.0 Doenc cardiovasc ateroscler descr deste modo'),
  ('I251', 'Doença aterosclerótica do coração', 'I25.1 Doenc aterosclerotica do coracao'),
  ('I252', 'Infarto antigo do miocárdio', 'I25.2 Infarto antigo do miocardio'),
  ('I253', 'Aneurisma cardíaco', 'I25.3 Aneurisma cardiaco'),
  ('I254', 'Aneurisma de artéria coronária', 'I25.4 Aneurisma de arteria coronaria'),
  ('I255', 'Miocardiopatia isquêmica', 'I25.5 Miocardiopatia isquemica'),
  ('I256', 'Isquemia miocárdica silenciosa', 'I25.6 Isquemia miocardica silenciosa'),
  ('I258', 'Outras formas de doença isquêmica crônica do coração', 'I25.8 Outr form de doenc isquemica cronica coracao'),
  ('I259', 'Doença isquêmica crônica do coração não especificada', 'I25.9 Doenc isquemica cronica do coracao NE'),
  ('I26', 'Embolia pulmonar', 'I26 Embolia pulmonar'),
  ('I260', 'Embolia pulmonar com menção de cor pulmonale agudo', 'I26.0 Embolia pulmonar c/menc cor pulmonale agudo'),
  ('I269', 'Embolia pulmonar sem menção de cor pulmonale agudo', 'I26.9 Embolia pulmonar s/menc cor pulmonale agudo'),
  ('I27', 'Outras formas de doença cardíaca pulmonar', 'I27 Outr form de doenc cardiaca pulmonar'),
  ('I270', 'Hipertensão pulmonar primária', 'I27.0 Hipertensao pulmonar prim'),
  ('I271', 'Cardiopatia cifoescoliótica', 'I27.1 Cardiopatia cifoescoliotica'),
  ('I272', 'Outra hipertensão pulmonar secundária', 'I27.2 Outra hipertensao pulmonar secundaria'),
  ('I278', 'Outras doenças pulmonares do coração especificadas', 'I27.8 Outr doenc pulmonares do coracao espec'),
  ('I279', 'Cardiopatia pulmonar não especificada', 'I27.9 Cardiopatia pulmonar NE'),
  ('I28', 'Outras doenças dos vasos pulmonares', 'I28 Outr doenc dos vasos pulmonares'),
  ('I280', 'Fístula arteriovenosa de vasos pulmonares', 'I28.0 Fistula arteriovenosa de vasos pulmonares'),
  ('I281', 'Aneurisma da artéria pulmonar', 'I28.1 Aneurisma da arteria pulmonar'),
  ('I288', 'Outras doenças especificadas dos vasos pulmonares', 'I28.8 Outr doenc espec dos vasos pulmonares'),
  ('I289', 'Doença não especificada dos vasos pulmonares', 'I28.9 Doenc NE dos vasos pulmonares'),
  ('I30', 'Pericardite aguda', 'I30 Pericardite aguda'),
  ('I300', 'Pericardite aguda idiopática não específica', 'I30.0 Pericardite aguda idiopatica nao especifica'),
  ('I301', 'Pericardite infecciosa', 'I30.1 Pericardite infecc'),
  ('I308', 'Outras formas de pericardite aguda', 'I30.8 Outr form de pericardite aguda'),
  ('I309', 'Pericardite aguda não especificada', 'I30.9 Pericardite aguda NE'),
  ('I31', 'Outras doenças do pericárdio', 'I31 Outr doenc do pericardio'),
  ('I310', 'Pericardite adesiva crônica', 'I31.0 Pericardite adesiva cronica'),
  ('I311', 'Pericardite constritiva crônica', 'I31.1 Pericardite constritiva cronica'),
  ('I312', 'Hemopericárdio não classificado em outra parte', 'I31.2 Hemopericardio NCOP'),
  ('I313', 'Derrame pericárdico (não-inflamatório)', 'I31.3 Derrame pericardico'),
  ('I318', 'Outras doenças especificadas do pericárdio', 'I31.8 Outr doenc espec do pericardio'),
  ('I319', 'Doença não especificada do pericárdio', 'I31.9 Doenc NE do pericardio'),
  ('I32', 'Pericardite em doenças classificadas em outra parte', 'I32 Pericardite em doenc COP'),
  ('I320', 'Pericardite em doenças bacterianas classificadas em outra parte', 'I32.0 Pericardite em doenc bacter COP'),
  ('I321', 'Pericardite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'I32.1 Pericardite outr doenc infecc e parasit COP'),
  ('I328', 'Pericardite em outras doenças classificadas em outra parte', 'I32.8 Pericardite em outr doenc COP'),
  ('I33', 'Endocardite aguda e subaguda', 'I33 Endocardite aguda e subaguda'),
  ('I330', 'Endocardite infecciosa aguda e subaguda', 'I33.0 Endocardite infecc aguda e subaguda'),
  ('I339', 'Endocardite aguda não especificada', 'I33.9 Endocardite aguda NE'),
  ('I34', 'Transtornos não-reumáticos da valva mitral', 'I34 Transt nao-reumaticos da valva mitral'),
  ('I340', 'Insuficiência (da valva) mitral', 'I34.0 Insuf mitral'),
  ('I341', 'Prolapso (da valva) mitral', 'I34.1 Prolapso mitral'),
  ('I342', 'Estenose (da valva) mitral, não-reumática', 'I34.2 Estenose mitral nao-reumatica'),
  ('I348', 'Outros transtornos não-reumáticos da valva mitral', 'I34.8 Outr transt nao-reumaticos da valva mitral'),
  ('I349', 'Transtornos não-reumáticos da valva mitral, não especificados', 'I34.9 Transt nao-reumaticos da valva mitral NE'),
  ('I35', 'Transtornos não-reumáticos da valva aórtica', 'I35 Transt nao-reumaticos da valva aortica'),
  ('I350', 'Estenose (da valva) aórtica', 'I35.0 Estenose aortica'),
  ('I351', 'Insuficiência (da valva) aórtica', 'I35.1 Insuf aortica'),
  ('I352', 'Estenose (da valva) aórtica com insuficiência', 'I35.2 Estenose aortica c/insuf'),
  ('I358', 'Outros transtornos da valva aórtica', 'I35.8 Outr transt da valva aortica'),
  ('I359', 'Transtornos não especificados da valva aórtica', 'I35.9 Transt NE da valva aortica'),
  ('I36', 'Transtornos não-reumáticos da valva tricúspide', 'I36 Transt nao-reumaticos da valva tricuspide'),
  ('I360', 'Estenose (da valva) tricúspide não-reumática', 'I36.0 Estenose tricuspide nao-reumatica'),
  ('I361', 'Insuficiência (da valva) tricúspide não-reumática', 'I36.1 Insuf tricuspide nao-reumatica'),
  ('I362', 'Estenose (da valva) tricúspide com insuficiência, não-reumática', 'I36.2 Estenose tricuspide c/insuf nao-reumatica'),
  ('I368', 'Outros transtornos não-reumáticos da valva tricúspide', 'I36.8 Outr transt nao-reumaticos valva tricuspide'),
  ('I369', 'Transtornos não-reumáticos da valva tricúspide, não especificados', 'I36.9 Transt nao-reumaticos da valva tricuspide NE'),
  ('I37', 'Transtornos da valva pulmonar', 'I37 Transt da valva pulmonar'),
  ('I370', 'Estenose da valva pulmonar', 'I37.0 Estenose da valva pulmonar'),
  ('I371', 'Insuficiência da valva pulmonar', 'I37.1 Insuf da valva pulmonar'),
  ('I372', 'Estenose da valva pulmonar com insuficiência', 'I37.2 Estenose da valva pulmonar c/insuf'),
  ('I378', 'Outros transtornos da valva pulmonar', 'I37.8 Outr transt da valva pulmonar'),
  ('I379', 'Transtornos não especificados da valva pulmonar', 'I37.9 Transt NE da valva pulmonar'),
  ('I38', 'Endocardite de valva não especificada', 'I38 Endocardite de valva NE'),
  ('I38', 'Endocardite de valva não especificada', 'I38 Endocardite de valva NE'),
  ('I39', 'Endocardite e transtornos valvulares cardíacos em doenças classificadas em outra parte', 'I39 Endocardite transt valvulares card doenc COP'),
  ('I390', 'Transtornos da valva mitral em doenças classificadas em outra parte', 'I39.0 Transt da valva mitral em doenc COP'),
  ('I391', 'Transtornos da valva aórtica em doenças classificadas em outra parte', 'I39.1 Transt da valva aortica em doenc COP'),
  ('I392', 'Transtornos da valva tricúspide em doenças classificadas em outra parte', 'I39.2 Transt da valva tricuspide em doenc COP'),
  ('I393', 'Transtornos da valva pulmonar em doenças classificadas em outra parte', 'I39.3 Transt da valva pulmonar em doenc COP'),
  ('I394', 'Transtornos de múltiplas valvas em doenças classificadas em outra parte', 'I39.4 Transt de mult valvas em doenc COP'),
  ('I398', 'Endocardite, de valva não especificada, em doenças classificadas em outra parte', 'I39.8 Endocardite de valva NE em doenc COP'),
  ('I40', 'Miocardite aguda', 'I40 Miocardite aguda'),
  ('I400', 'Miocardite infecciosa', 'I40.0 Miocardite infecc'),
  ('I401', 'Miocardite isolada', 'I40.1 Miocardite isolada'),
  ('I408', 'Outras miocardites agudas', 'I40.8 Outr miocardites agudas'),
  ('I409', 'Miocardite aguda não especificada', 'I40.9 Miocardite aguda NE'),
  ('I41', 'Miocardite em doenças classificadas em outra parte', 'I41 Miocardite em doenc COP'),
  ('I410', 'Miocardite em doenças bacterianas classificadas em outra parte', 'I41.0 Miocardite em doenc bacter COP'),
  ('I411', 'Miocardite em doenças virais classificadas em outra parte', 'I41.1 Miocardite em doenc virais COP'),
  ('I412', 'Miocardite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'I41.2 Miocardite outr doenc infecc e parasit COP'),
  ('I418', 'Miocardite em outras doenças classificadas em outra parte', 'I41.8 Miocardite em outr doenc COP'),
  ('I42', 'Cardiomiopatias', 'I42 Cardiomiopatias'),
  ('I420', 'Cardiomiopatia dilatada', 'I42.0 Cardiomiopatia dilatada'),
  ('I421', 'Cardiomiopatia obstrutiva hipertrófica', 'I42.1 Cardiomiopatia obstrutiva hipertrofica'),
  ('I422', 'Outras cardiomiopatias hipertróficas', 'I42.2 Outr cardiomiopatias hipertroficas'),
  ('I423', 'Doença endomiocárdica (eosinofílica)', 'I42.3 Doenc endomiocardica'),
  ('I424', 'Fibroelastose endocárdica', 'I42.4 Fibroelastose endocardica'),
  ('I425', 'Outras cardiomiopatias restritivas', 'I42.5 Outr cardiomiopatias restritivas'),
  ('I426', 'Cardiomiopatia alcoólica', 'I42.6 Cardiomiopatia alcoolica'),
  ('I427', 'Cardiomiopatia devida a drogas e outros agentes externos', 'I42.7 Cardiomiopatia dev drogas e outr agentes ext'),
  ('I428', 'Outras cardiomiopatias', 'I42.8 Outr cardiomiopatias'),
  ('I429', 'Cardiomiopatia não especificada', 'I42.9 Cardiomiopatia NE'),
  ('I43', 'Cardiomiopatia em doenças classificadas em outra parte', 'I43 Cardiomiopatia em doenc COP'),
  ('I430', 'Cardiomiopatia em doenças infecciosas e parasitárias classificadas em outra parte', 'I43.0 Cardiomiopatia em doenc infecc e parasit COP'),
  ('I431', 'Cardiomiopatia em doenças metabólicas', 'I43.1 Cardiomiopatia em doenc metabolicas'),
  ('I432', 'Cardiomiopatia em doenças nutricionais', 'I43.2 Cardiomiopatia em doenc nutricionais'),
  ('I438', 'Cardiomiopatia em outras doenças classificadas em outra parte', 'I43.8 Cardiomiopatia em outr doenc COP'),
  ('I44', 'Bloqueio atrioventricular e do ramo esquerdo', 'I44 Bloqueio atrioventricular e do ramo esquerdo'),
  ('I440', 'Bloqueio atrioventricular de primeiro grau', 'I44.0 Bloqueio atrioventricular de 1.grau'),
  ('I441', 'Bloqueio atrioventricular de segundo grau', 'I44.1 Bloqueio atrioventricular de 2.grau'),
  ('I442', 'Bloqueio atrioventricular total', 'I44.2 Bloqueio atrioventricular total'),
  ('I443', 'Outras formas de bloqueio atrioventricular e as não especificadas', 'I44.3 Outr form de bloqueio atrioventricular e NE'),
  ('I444', 'Bloqueio do fascículo anterior esquerdo', 'I44.4 Bloqueio do fasciculo anterior esquerdo'),
  ('I445', 'Bloqueio do fascículo posterior esquerdo', 'I44.5 Bloqueio do fasciculo posterior esquerdo'),
  ('I446', 'Outras formas de bloqueio fascicular e as não especificadas', 'I44.6 Outr form de bloqueio fascicular e as NE'),
  ('I447', 'Bloqueio de ramo esquerdo não especificado', 'I44.7 Bloqueio de ramo esquerdo NE'),
  ('I45', 'Outros transtornos de condução', 'I45 Outr transt de conducao'),
  ('I450', 'Bloqueio fascicular direito', 'I45.0 Bloqueio fascicular direito'),
  ('I451', 'Outras formas de bloqueio de ramo direito e as não especificadas', 'I45.1 Outr form de bloqueio de ramo direito e NE'),
  ('I452', 'Bloqueio bifascicular', 'I45.2 Bloqueio bifascicular'),
  ('I453', 'Bloqueio trifascicular', 'I45.3 Bloqueio trifascicular'),
  ('I454', 'Bloqueio intraventricular não específico', 'I45.4 Bloqueio intraventricular nao especifico'),
  ('I455', 'Outras formas especificadas de bloqueio cardíaco', 'I45.5 Outr form espec de bloqueio cardiaco'),
  ('I456', 'Síndrome de pré-excitação', 'I45.6 Sindr de pre-excitacao'),
  ('I458', 'Outros transtornos especificados da condução', 'I45.8 Outr transt espec da conducao'),
  ('I459', 'Transtorno de condução não especificado', 'I45.9 Transt de conducao NE'),
  ('I46', 'Parada cardíaca', 'I46 Parada cardiaca'),
  ('I460', 'Parada cardíaca com ressuscitação bem sucedida', 'I46.0 Parada cardiaca c/ressuscitacao bem sucedida'),
  ('I461', 'Morte súbita (de origem) cardíaca, descrita desta forma', 'I46.1 Morte subita cardiaca descrita desta form'),
  ('I469', 'Parada cardíaca não especificada', 'I46.9 Parada cardiaca NE'),
  ('I47', 'Taquicardia paroxística', 'I47 Taquicardia paroxistica'),
  ('I470', 'Arritmia ventricular por reentrada', 'I47.0 Arritmia ventricular p/reentrada'),
  ('I471', 'Taquicardia supraventricular', 'I47.1 Taquicardia supraventricular'),
  ('I472', 'Taquicardia ventricular', 'I47.2 Taquicardia ventricular'),
  ('I479', 'Taquicardia paroxística não especificada', 'I47.9 Taquicardia paroxistica NE'),
  ('I48', 'Flutter e fibrilação atrial', 'I48 Flutter e fibrilacao atrial'),
  ('I48', 'Flutter e fibrilação atrial', 'I48 Flutter e fibrilacao atrial'),
  ('I49', 'Outras arritmias cardíacas', 'I49 Outr arritmias cardiacas'),
  ('I490', 'Flutter e fibrilação ventricular', 'I49.0 Flutter e fibrilacao ventricular'),
  ('I491', 'Despolarização atrial prematura', 'I49.1 Despolarizacao atrial prematura'),
  ('I492', 'Despolarização juncional prematura', 'I49.2 Despolarizacao juncional prematura'),
  ('I493', 'Despolarização ventricular prematura', 'I49.3 Despolarizacao ventricular prematura'),
  ('I494', 'Outras formas de despolarização prematura e as não especificadas', 'I49.4 Outr form de despolarizacao prematura e NE'),
  ('I495', 'Síndrome do nó sinusal', 'I49.5 Sindr do no sinusal'),
  ('I498', 'Outras arritmias cardíacas especificadas', 'I49.8 Outr arritmias cardiacas espec'),
  ('I499', 'Arritmia cardíaca não especificada', 'I49.9 Arritmia cardiaca NE'),
  ('I50', 'Insuficiência cardíaca', 'I50 Insuf cardiaca'),
  ('I500', 'Insuficiência cardíaca congestiva', 'I50.0 Insuf cardiaca congestiva'),
  ('I501', 'Insuficiência ventricular esquerda', 'I50.1 Insuf ventricular esquerda'),
  ('I509', 'Insuficiência cardíaca não especificada', 'I50.9 Insuf cardiaca NE'),
  ('I51', 'Complicações de cardiopatias e doenças cardíacas mal definidas', 'I51 Complic cardiopatias doenc cardiacas mal def'),
  ('I510', 'Defeito adquirido de septo cardíaco', 'I51.0 Defeito adquir de septo cardiaco'),
  ('I511', 'Ruptura de cordoalha tendínea, não classificada em outra parte', 'I51.1 Ruptura de cordoalha tendinea NCOP'),
  ('I512', 'Ruptura de músculo papilar, não classificada em outra parte', 'I51.2 Ruptura de musculo papilar NCOP'),
  ('I513', 'Trombose intracardíaca, não classificada em outra parte', 'I51.3 Trombose intracardiaca NCOP'),
  ('I514', 'Miocardite não especificada', 'I51.4 Miocardite NE'),
  ('I515', 'Degeneração miocárdica', 'I51.5 Degeneracao miocardica'),
  ('I516', 'Doença cardiovascular não especificada', 'I51.6 Doenc cardiovascular NE'),
  ('I517', 'Cardiomegalia', 'I51.7 Cardiomegalia'),
  ('I518', 'Outras doenças mal definidas do coração', 'I51.8 Outr doenc mal definidas do coracao'),
  ('I519', 'Doença não especificada do coração', 'I51.9 Doenc NE do coracao'),
  ('I52', 'Outras afecções cardíacas em doenças classificadas em outra parte', 'I52 Outr afeccoes cardiacas em doenc COP'),
  ('I520', 'Outras afecções cardíacas em doenças bacterianas classificadas em outra parte', 'I52.0 Outr afeccoes cardiacas em doenc bacter COP'),
  ('I521', 'Outras afecções cardíacas em outras doenças infecciosas e parasitárias classificadas em outra parte', 'I52.1 Outr afecc card outr doenc infec parasit COP'),
  ('I528', 'Outras afecções cardíacas em outras doenças classificadas em outra parte', 'I52.8 Outr afeccoes cardiacas em outr doenc COP'),
  ('I60', 'Hemorragia subaracnóide', 'I60 Hemorragia subaracnoide'),
  ('I600', 'Hemorragia subaracnóide proveniente do sifão e da bifurcação da carótida', 'I60.0 Hemorragia subarac prov sifao bifurc carotid'),
  ('I601', 'Hemorragia subaracnóide proveniente da artéria cerebral média', 'I60.1 Hemorragia subarac prov arteria cerebr media'),
  ('I602', 'Hemorragia subaracnóide proveniente da artéria comunicante anterior', 'I60.2 Hemorragia subarac prov arteria comunic ant'),
  ('I603', 'Hemorragia subaracnóide proveniente da artéria comunicante posterior', 'I60.3 Hemorragia subarac prov arteria comunic post'),
  ('I604', 'Hemorragia subaracnóide proveniente da artéria basilar', 'I60.4 Hemorragia subarac prov arteria basilar'),
  ('I605', 'Hemorragia subaracnóide proveniente da artéria vertebral', 'I60.5 Hemorragia subarac prov arteria vertebral'),
  ('I606', 'Hemorragia subaracnóide proveniente de outras artérias intracranianas', 'I60.6 Hemorragia subarac prov outr arter intracran'),
  ('I607', 'Hemorragia subaracnóide proveniente de artéria intracraniana não especificada', 'I60.7 Hemorragia subarac prov arteria intracran NE'),
  ('I608', 'Outras hemorragias subaracnóides', 'I60.8 Outr hemorragias subaracnoides'),
  ('I609', 'Hemorragia subaracnóide não especificada', 'I60.9 Hemorragia subaracnoide NE'),
  ('I61', 'Hemorragia intracerebral', 'I61 Hemorragia intracerebral'),
  ('I610', 'Hemorragia intracerebral hemisférica subcortical', 'I61.0 Hemorragia intracerebr hemisf subcortical'),
  ('I611', 'Hemorragia intracerebral hemisférica cortical', 'I61.1 Hemorragia intracerebr hemisferica cortical'),
  ('I612', 'Hemorragia intracerebral hemisférica não especificada', 'I61.2 Hemorragia intracerebral hemisferica NE'),
  ('I613', 'Hemorragia intracerebral do tronco cerebral', 'I61.3 Hemorragia intracerebral do tronco cerebral'),
  ('I614', 'Hemorragia intracerebral cerebelar', 'I61.4 Hemorragia intracerebral cerebelar'),
  ('I615', 'Hemorragia intracerebral intraventricular', 'I61.5 Hemorragia intracerebral intraventricular'),
  ('I616', 'Hemorragia intracerebral de múltiplas localizações', 'I61.6 Hemorragia intracerebral de mult localiz'),
  ('I618', 'Outras hemorragias intracerebrais', 'I61.8 Outr hemorragias intracerebrais'),
  ('I619', 'Hemorragia intracerebral não especificada', 'I61.9 Hemorragia intracerebral NE'),
  ('I62', 'Outras hemorragias intracranianas não-traumáticas', 'I62 Outr hemorragias intracranianas nao-traum'),
  ('I620', 'Hemorragia subdural (aguda) (não-traumática)', 'I62.0 Hemorragia subdural'),
  ('I621', 'Hemorragia extradural não-traumática', 'I62.1 Hemorragia extradural nao-traum'),
  ('I629', 'Hemorragia intracraniana (não-traumática) não especificada', 'I62.9 Hemorragia intracraniana NE'),
  ('I63', 'Infarto cerebral', 'I63 Infarto cerebral'),
  ('I630', 'Infarto cerebral devido a trombose de artérias pré-cerebrais', 'I63.0 Infarto cerebr dev tromb arterias pre-cerebr'),
  ('I631', 'Infarto cerebral devido a embolia de artérias pré-cerebrais', 'I63.1 Infarto cerebr dev embol arterias pre-cerebr'),
  ('I632', 'Infarto cerebral devido a oclusão ou estenose não especificadas de artérias pré-cerebrais', 'I63.2 Inf cer dev oclusao esten NE art pre-cerebr'),
  ('I633', 'Infarto cerebral devido a trombose de artérias cerebrais', 'I63.3 Infarto cerebr dev trombose arterias cerebr'),
  ('I634', 'Infarto cerebral devido a embolia de artérias cerebrais', 'I63.4 Infarto cerebral dev embolia arterias cerebr'),
  ('I635', 'Infarto cerebral devido a oclusão ou estenose não especificadas de artérias cerebrais', 'I63.5 Inf cer dev oclusao estenose NE art cerebr'),
  ('I636', 'Infarto cerebral devido a trombose venosa cerebral não-piogênica', 'I63.6 Inf cerebr dev tromb ven cerebr nao-piogenic'),
  ('I638', 'Outros infartos cerebrais', 'I63.8 Outr infartos cerebrais'),
  ('I639', 'Infarto cerebral não especificado', 'I63.9 Infarto cerebral NE'),
  ('I64', 'Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico', 'I64 Acid vasc cerebr NE como hemorrag isquemico'),
  ('I64', 'Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico', 'I64 Acid vasc cerebr NE como hemorrag isquemico'),
  ('I65', 'Oclusão e estenose de artérias pré-cerebrais que não resultam em infarto cerebral', 'I65 Oclus/esten art pre-cereb q n res inf cereb'),
  ('I650', 'Oclusão e estenose da artéria vertebral', 'I65.0 Oclusao e estenose da arteria vertebral'),
  ('I651', 'Oclusão e estenose da artéria basilar', 'I65.1 Oclusao e estenose da arteria basilar'),
  ('I652', 'Oclusão e estenose da artéria carótida', 'I65.2 Oclusao e estenose da arteria carotida'),
  ('I653', 'Oclusão e estenose de artérias pré-cerebrais múltiplas e bilaterais', 'I65.3 Oclusao/estenose art pre-cerebr mult bilat'),
  ('I658', 'Oclusão e estenose de outra artéria pré-cerebral', 'I65.8 Oclusao e estenose outr arteria pre-cerebral'),
  ('I659', 'Oclusão e estenose de artérias pré-cerebrais não especificadas', 'I65.9 Oclusao e estenose arterias pre-cerebrais NE'),
  ('I66', 'Oclusão e estenose de artérias cerebrais que não resultam em infarto cerebral', 'I66 Oclusao/estenose art cereb q n res inf cereb'),
  ('I660', 'Oclusão e estenose da artéria cerebral média', 'I66.0 Oclusao e estenose da arteria cerebral media'),
  ('I661', 'Oclusão e estenose da artéria cerebral anterior', 'I66.1 Oclusao e estenose arteria cerebral anterior'),
  ('I662', 'Oclusão e estenose da artéria cerebral posterior', 'I66.2 Oclusao e estenose arteria cerebral post'),
  ('I663', 'Oclusão e estenose de artérias cerebelares', 'I66.3 Oclusao e estenose de arterias cerebelares'),
  ('I664', 'Oclusão e estenose de artérias cerebrais, múltiplas e bilaterais', 'I66.4 Oclusao/estenose arterias cerebr mult bilat'),
  ('I668', 'Oclusão e estenose de outra artéria cerebral', 'I66.8 Oclusao e estenose de outr arteria cerebral'),
  ('I669', 'Oclusão e estenose de artéria cerebral não especificada', 'I66.9 Oclusao e estenose de arteria cerebral NE'),
  ('I67', 'Outras doenças cerebrovasculares', 'I67 Outr doenc cerebrovasculares'),
  ('I670', 'Dissecção de artérias cerebrais, sem ruptura', 'I67.0 Disseccao de arterias cerebrais s/ruptura'),
  ('I671', 'Aneurisma cerebral não-roto', 'I67.1 Aneurisma cerebral nao-roto'),
  ('I672', 'Aterosclerose cerebral', 'I67.2 Aterosclerose cerebral'),
  ('I673', 'Leucoencefalopatia vascular progressiva', 'I67.3 Leucoencefalopatia vascular progressiva'),
  ('I674', 'Encefalopatia hipertensiva', 'I67.4 Encefalopatia hipertensiva'),
  ('I675', 'Doença de Moyamoya', 'I67.5 Doenc de Moyamoya'),
  ('I676', 'Trombose não-piogênica do sistema venoso intracraniano', 'I67.6 Trombose nao-piogenica sist venoso intracran'),
  ('I677', 'Arterite cerebral não classificada em outra parte', 'I67.7 Arterite cerebral NCOP'),
  ('I678', 'Outras doenças cerebrovasculares especificadas', 'I67.8 Outr doenc cerebrovasculares espec'),
  ('I679', 'Doença cerebrovascular não especificada', 'I67.9 Doenc cerebrovascular NE'),
  ('I68', 'Transtornos cerebrovasculares em doenças classificadas em outra parte', 'I68 Transt cerebrovasculares em doenc COP'),
  ('I680', 'Angiopatia cerebral amiloidótica', 'I68.0 Angiopatia cerebral amiloidotica'),
  ('I681', 'Arterite cerebral em doenças infecciosas e parasitárias', 'I68.1 Arterite cerebral em doenc infecc e parasit'),
  ('I682', 'Arterite cerebral em outras doenças classificadas em outra parte', 'I68.2 Arterite cerebral em outr doenc COP'),
  ('I688', 'Outros transtornos cerebrovasculares em doenças classificadas em outra parte', 'I68.8 Outr transt cerebrovasculares em doenc COP'),
  ('I69', 'Seqüelas de doenças cerebrovasculares', 'I69 Sequelas de doenc cerebrovasculares'),
  ('I690', 'Seqüelas de hemorragia subaracnoídea', 'I69.0 Sequelas de hemorragia subaranoidea'),
  ('I691', 'Seqüelas de hemorragia intracerebral', 'I69.1 Sequelas de hemorragia intracerebral'),
  ('I692', 'Seqüelas de outras hemorragias intracranianas não traumáticas', 'I69.2 Sequelas outr hemorrag intracran nao traum'),
  ('I693', 'Seqüelas de infarto cerebral', 'I69.3 Sequelas de infarto cerebral'),
  ('I694', 'Seqüelas de acidente vascular cerebral não especificado como hemorrágico ou isquêmico', 'I69.4 Sequelas acid vasc cerebr NE c/hemorr isquem'),
  ('I698', 'Seqüelas de outras doenças cerebrovasculares e das não especificadas', 'I69.8 Sequelas outr doenc cerebrovasculares e NE'),
  ('I70', 'Aterosclerose', 'I70 Aterosclerose'),
  ('I700', 'Aterosclerose da aorta', 'I70.0 Aterosclerose da aorta'),
  ('I701', 'Aterosclerose da artéria renal', 'I70.1 Aterosclerose da arteria renal'),
  ('I702', 'Aterosclerose das artérias das extremidades', 'I70.2 Aterosclerose das arterias das extremidades'),
  ('I708', 'Aterosclerose de outras artérias', 'I70.8 Aterosclerose de outr arterias'),
  ('I709', 'Aterosclerose generalizada e a não especificada', 'I70.9 Aterosclerose generalizada e a NE'),
  ('I71', 'Aneurisma e dissecção da aorta', 'I71 Aneurisma e disseccao da aorta'),
  ('I710', 'Aneurisma dissecante da aorta (qualquer porção)', 'I71.0 Aneurisma dissecante da aorta'),
  ('I711', 'Aneurisma da aorta torácica, roto', 'I71.1 Aneurisma da aorta toracica roto'),
  ('I712', 'Aneurisma da aorta torácica, sem menção de ruptura', 'I71.2 Aneurisma da aorta toracica s/mencao ruptura'),
  ('I713', 'Aneurisma da aorta abdominal, roto', 'I71.3 Aneurisma da aorta abdominal roto'),
  ('I714', 'Aneurisma da aorta abdominal, sem menção de ruptura', 'I71.4 Aneurisma aorta abdominal s/mencao ruptura'),
  ('I715', 'Aneurisma da aorta tóraco-abdominal, roto', 'I71.5 Aneurisma da aorta toraco-abdominal roto'),
  ('I716', 'Aneurisma da aorta toráco-abdominal, sem menção de ruptura', 'I71.6 Aneurisma aorta toraco-abdom s/menc ruptura'),
  ('I718', 'Aneurisma da aorta de localização não especificada, roto', 'I71.8 Aneurisma da aorta de localiz NE roto'),
  ('I719', 'Aneurisma aórtico de localização não especificada, sem menção de ruptura', 'I71.9 Aneurisma aortico local NE s/mencao ruptura'),
  ('I72', 'Outros aneurismas', 'I72 Outr aneurismas'),
  ('I720', 'Aneurisma da artéria carótida', 'I72.0 Aneurisma da arteria carotida'),
  ('I721', 'Aneurisma de artéria dos membros superiores', 'I72.1 Aneurisma de arteria dos membros super'),
  ('I722', 'Aneurisma da artéria renal', 'I72.2 Aneurisma da arteria renal'),
  ('I723', 'Aneurisma de artéria ilíaca', 'I72.3 Aneurisma de arteria iliaca'),
  ('I724', 'Aneurisma de artéria dos membros inferiores', 'I72.4 Aneurisma de arteria dos membros infer'),
  ('I728', 'Aneurisma de outras artérias especificadas', 'I72.8 Aneurisma de outr arterias espec'),
  ('I729', 'Aneurisma de localização não especificada', 'I72.9 Aneurisma de localiz NE'),
  ('I73', 'Outras doenças vasculares periféricas', 'I73 Outr doenc vasculares perifericas'),
  ('I730', 'Síndrome de Raynaud', 'I73.0 Sindr de Raynaud'),
  ('I731', 'Tromboangeíte obliterante (doença de Buerger)', 'I73.1 Tromboangeite obliterante'),
  ('I738', 'Outras doenças vasculares periféricas especificadas', 'I73.8 Outr doenc vasculares perifericas espec'),
  ('I739', 'Doenças vasculares periféricas não especificada', 'I73.9 Doenc vasculares perifericas NE'),
  ('I74', 'Embolia e trombose arteriais', 'I74 Embolia e trombose arteriais'),
  ('I740', 'Embolia e trombose da aorta abdominal', 'I74.0 Embolia e trombose da aorta abdominal'),
  ('I741', 'Embolia e trombose de outras porções da aorta e das não especificadas', 'I74.1 Embolia trombose outr porcoes da aorta e NE'),
  ('I742', 'Embolia e trombose de artérias dos membros superiores', 'I74.2 Embolia e trombose de arterias membros super'),
  ('I743', 'Embolia e trombose de artérias dos membros inferiores', 'I74.3 Embolia e trombose de arterias membros infer'),
  ('I744', 'Embolia e trombose de artérias dos membros não especificadas', 'I74.4 Embolia e trombose de arterias membros NE'),
  ('I745', 'Embolia e trombose da artéria ilíaca', 'I74.5 Embolia e trombose da arteria iliaca'),
  ('I748', 'Embolia e trombose de outras artérias', 'I74.8 Embolia e trombose de outr arterias'),
  ('I749', 'Embolia e trombose de artéria não especificada', 'I74.9 Embolia e trombose de arteria NE'),
  ('I77', 'Outras afecções das artérias e arteríolas', 'I77 Outr afeccoes das arterias e arteriolas'),
  ('I770', 'Fístula arteriovenosa adquirida', 'I77.0 Fistula arteriovenosa adquir'),
  ('I771', 'Estenose de artéria', 'I77.1 Estenose de arteria'),
  ('I772', 'Ruptura de artéria', 'I77.2 Ruptura de arteria'),
  ('I773', 'Displasia fibromuscular arterial', 'I77.3 Displasia fibromuscular arterial'),
  ('I774', 'Síndrome de compressão da artéria celíaca', 'I77.4 Sindr de compressao da arteria celiaca'),
  ('I775', 'Necrose de artéria', 'I77.5 Necrose de arteria'),
  ('I776', 'Arterite não especificada', 'I77.6 Arterite NE'),
  ('I778', 'Outras afecções especificadas das artérias e das arteríolas', 'I77.8 Outr afeccoes espec arterias e arteriolas'),
  ('I779', 'Afecções de artérias e arteríolas, não especificadas', 'I77.9 Afeccoes de arterias e arteriolas NE'),
  ('I78', 'Doenças dos capilares', 'I78 Doenc dos capilares'),
  ('I780', 'Telangiectasia hemorrágica hereditária', 'I78.0 Telangiectasia hemorragica hereditaria'),
  ('I781', 'Nevo não-neoplásico', 'I78.1 Nevo nao-neoplasico'),
  ('I788', 'Outras doenças dos capilares', 'I78.8 Outr doenc dos capilares'),
  ('I789', 'Doenças não especificadas dos capilares', 'I78.9 Doenc NE dos capilares'),
  ('I79', 'Transtornos das artérias, das arteríolas e dos capilares em doenças classificadas em outra parte', 'I79 Transt arter arteriolas capilares doenc COP'),
  ('I790', 'Aneurisma da aorta em doenças classificadas em outra parte', 'I79.0 Aneurisma da aorta em doenc COP'),
  ('I791', 'Aortite em doenças classificadas em outra parte', 'I79.1 Aortite em doenc COP'),
  ('I792', 'Angiopatia periférica em doenças classificadas em outra parte', 'I79.2 Angiopatia periferica em doenc COP'),
  ('I798', 'Outros transtornos das artérias, das arteríolas e dos capilares em doenças classificadas em outra parte', 'I79.8 Outr transt arter arteriolas capil doenc COP'),
  ('I80', 'Flebite e tromboflebite', 'I80 Flebite e tromboflebite'),
  ('I800', 'Flebite e tromboflebite dos vasos superficiais dos membros inferiores', 'I80.0 Flebite tromboflebite vasos superf membr inf'),
  ('I801', 'Flebite e tromboflebite da veia femural', 'I80.1 Flebite e tromboflebite da veia femural'),
  ('I802', 'Flebite e tromboflebite de outros vasos profundos dos membros inferiores', 'I80.2 Flebite trombofleb outr vasos prof membr inf'),
  ('I803', 'Flebite e tromboflebite dos membros inferiores, não especificada', 'I80.3 Flebite e tromboflebite dos membros infer NE'),
  ('I808', 'Flebite e tromboflebite de outras localizações', 'I80.8 Flebite e tromboflebite de outr localiz'),
  ('I809', 'Flebite e tromboflebite de localização não especificada', 'I80.9 Flebite e tromboflebite de localiz NE'),
  ('I81', 'Trombose da veia porta', 'I81 Trombose da veia porta'),
  ('I81', 'Trombose da veia porta', 'I81 Trombose da veia porta'),
  ('I82', 'Outra embolia e trombose venosas', 'I82 Outr embolia e trombose venosas'),
  ('I820', 'Síndrome de Budd-Chiari', 'I82.0 Sindr de Budd-Chiari'),
  ('I821', 'Tromboflebite migratória', 'I82.1 Tromboflebite migratoria'),
  ('I822', 'Embolia e trombose de veia cava', 'I82.2 Embolia e trombose de veia cava'),
  ('I823', 'Embolia e trombose de veia renal', 'I82.3 Embolia e trombose de veia renal'),
  ('I828', 'Embolia e trombose de outras veias especificadas', 'I82.8 Embolia e trombose de outr veias espec'),
  ('I829', 'Embolia e trombose venosas de veia não especificada', 'I82.9 Embolia e trombose venosas de veia NE'),
  ('I83', 'Varizes dos membros inferiores', 'I83 Varizes dos membros infer'),
  ('I830', 'Varizes dos membros inferiores com úlcera', 'I83.0 Varizes dos membros infer c/ulcera'),
  ('I831', 'Varizes dos membros inferiores com inflamação', 'I83.1 Varizes dos membros infer c/inflam'),
  ('I832', 'Varizes dos membros inferiores com úlcera e inflamação', 'I83.2 Varizes membros infer c/ulcera e inflam'),
  ('I839', 'Varizes dos membros inferiores sem úlcera ou inflamação', 'I83.9 Varizes membros infer s/ulcera ou inflam'),
  ('I84', 'Hemorróidas', 'I84 Hemorroidas'),
  ('I840', 'Hemorróidas internas trombosadas', 'I84.0 Hemorroidas internas trombosadas'),
  ('I841', 'Hemorróidas internas com outras complicações', 'I84.1 Hemorroidas internas c/outr complic'),
  ('I842', 'Hemorróidas internas sem complicações', 'I84.2 Hemorroidas internas s/complic'),
  ('I843', 'Hemorróidas externas trombosadas', 'I84.3 Hemorroidas externas trombosadas'),
  ('I844', 'Hemorróidas externas com outras complicações', 'I84.4 Hemorroidas externas c/outr complic'),
  ('I845', 'Hemorróidas externas sem complicação', 'I84.5 Hemorroidas externas s/complic'),
  ('I846', 'Plicomas hemorroidários residuais', 'I84.6 Plicomas hemorroidarios residuais'),
  ('I847', 'Hemorróidas trombosadas, não especificadas', 'I84.7 Hemorroidas trombosadas NE'),
  ('I848', 'Hemorróidas não especificadas com outras complicações', 'I84.8 Hemorroidas NE c/outr complic'),
  ('I849', 'Hemorróidas sem complicações, não especificadas', 'I84.9 Hemorroidas s/complic NE'),
  ('I85', 'Varizes esofagianas', 'I85 Varizes esofagianas'),
  ('I850', 'Varizes esofagianas sangrantes', 'I85.0 Varizes esofagianas sangrantes'),
  ('I859', 'Varizes esofagianas sem sangramento', 'I85.9 Varizes esofagianas s/sangramento'),
  ('I86', 'Varizes de outras localizações', 'I86 Varizes de outr localiz'),
  ('I860', 'Varizes sublinguais', 'I86.0 Varizes sublinguais'),
  ('I861', 'Varizes escrotais', 'I86.1 Varizes escrotais'),
  ('I862', 'Varizes pélvicas', 'I86.2 Varizes pelvicas'),
  ('I863', 'Varizes da vulva', 'I86.3 Varizes da vulva'),
  ('I864', 'Varizes gástricas', 'I86.4 Varizes gastricas'),
  ('I868', 'Varizes de outras localizações especificadas', 'I86.8 Varizes de outr localiz espec'),
  ('I87', 'Outros transtornos das veias', 'I87 Outr transt das veias'),
  ('I870', 'Síndrome pós-flebite', 'I87.0 Sindr pos-flebite'),
  ('I871', 'Compressão venosa', 'I87.1 Compressao venosa'),
  ('I872', 'Insuficiência venosa (crônica) (periférica)', 'I87.2 Insuf venosa'),
  ('I878', 'Outros transtornos venosos especificados', 'I87.8 Outr transt venosos espec'),
  ('I879', 'Transtorno venoso não especificado', 'I87.9 Transt venoso NE'),
  ('I88', 'Linfadenite inespecífica', 'I88 Linfadenite inespecifica'),
  ('I880', 'Linfadenite mesentérica não específica', 'I88.0 Linfadenite mesenterica nao especifica'),
  ('I881', 'Linfadenite crônica, exceto a mesentérica', 'I88.1 Linfadenite cronica exceto a mesenterica'),
  ('I888', 'Outras linfadenites inespecíficas', 'I88.8 Outr linfadenites inespecificas'),
  ('I889', 'Linfadenite não especificada', 'I88.9 Linfadenite NE'),
  ('I89', 'Outros transtornos não-infecciosos dos vasos linfáticos e dos gânglios linfáticos', 'I89 Outr transt nao-infecc vasos linf gangl linf'),
  ('I890', 'Linfedema não classificado em outra parte', 'I89.0 Linfedema NCOP'),
  ('I891', 'Linfangite', 'I89.1 Linfangite'),
  ('I898', 'Outros transtornos não-infecciosos, especificados, dos vasos linfáticos e dos gânglios linfáticos', 'I89.8 Out transt n-inf espec vasos linf gangl linf'),
  ('I899', 'Transtornos não-infecciosos dos vasos linfáticos e dos gânglios linfáticos, não especificados', 'I89.9 Transt nao-infecc vasos linf gangl linf NE'),
  ('I95', 'Hipotensão', 'I95 Hipotensao'),
  ('I950', 'Hipotensão idiopática', 'I95.0 Hipotensao idiopatica'),
  ('I951', 'Hipotensão ortostática', 'I95.1 Hipotensao ortostatica'),
  ('I952', 'Hipotensão devida a drogas', 'I95.2 Hipotensao dev drogas'),
  ('I958', 'Outros tipos de hipotensão', 'I95.8 Outr tipos de hipotensao'),
  ('I959', 'Hipotensão não especificada', 'I95.9 Hipotensao NE'),
  ('I97', 'Transtornos do aparelho circulatório, subseqüentes a procedimentos não classificados em outra parte', 'I97 Transt aparelho circulat subseq proced NCOP'),
  ('I970', 'Síndrome pós-cardiotomia', 'I97.0 Sindr pos-cardiotomia'),
  ('I971', 'Outros distúrbios funcionais subseqüentes à cirurgia cardíaca', 'I97.1 Outr disturb func subseq cirurgia cardiaca'),
  ('I972', 'Síndrome do linfedema pós-mastectomia', 'I97.2 Sindr do linfedema pos-mastectomia'),
  ('I978', 'Outros transtornos do aparelho circulatório subseqüentes a procedimentos não classificados em outra parte', 'I97.8 Outr transt ap circulat subseq proced NCOP'),
  ('I979', 'Transtornos do aparelho circulatório, subseqüentes a procedimento não especificado', 'I97.9 Transt aparelho circulat subseq proced NE'),
  ('I98', 'Outros transtornos do aparelho circulatório em doenças classificadas em outra parte', 'I98 Outr transt aparelho circulatorio doenc COP'),
  ('I980', 'Sífilis cardiovascular', 'I98.0 Sifilis cardiovascular'),
  ('I981', 'Transtornos cardiovasculares em outras doenças infecciosas e parasitárias classificadas em outra parte', 'I98.1 Transt cardiovasc outr doenc inf parasit COP'),
  ('I982', 'Varizes esofagianas em doenças classificadas em outra parte', 'I98.2 Varizes esofagianas em doenc COP'),
  ('I988', 'Outros transtornos especificados do aparelho circulatório em doenças classificadas em outra parte', 'I98.8 Outr transt espec ap circulat doenc COP'),
  ('I99', 'Outros transtornos do aparelho circulatório e os não especificados', 'I99 Outr transt do aparelho circulatorio e os NE');
