INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('J00', 'Nasofaringite aguda (resfriado comum)', 'J00 Nasofaringite aguda'),
  ('J00', 'Nasofaringite aguda (resfriado comum)', 'J00 Nasofaringite aguda'),
  ('J01', 'Sinusite aguda', 'J01 Sinusite aguda'),
  ('J010', 'Sinusite maxilar aguda', 'J01.0 Sinusite maxilar aguda'),
  ('J011', 'Sinusite frontal aguda', 'J01.1 Sinusite frontal aguda'),
  ('J012', 'Sinusite etmoidal aguda', 'J01.2 Sinusite etmoidal aguda'),
  ('J013', 'Sinusite esfenoidal aguda', 'J01.3 Sinusite esfenoidal aguda'),
  ('J014', 'Pansinusite aguda', 'J01.4 Pansinusite aguda'),
  ('J018', 'Outras sinusites agudas', 'J01.8 Outr sinusites agudas'),
  ('J019', 'Sinusite aguda não especificada', 'J01.9 Sinusite aguda NE'),
  ('J02', 'Faringite aguda', 'J02 Faringite aguda'),
  ('J020', 'Faringite estreptocócica', 'J02.0 Faringite estreptococica'),
  ('J028', 'Faringite aguda devida a outros microorganismos especificados', 'J02.8 Faringite aguda dev outr microorg espec'),
  ('J029', 'Faringite aguda não especificada', 'J02.9 Faringite aguda NE'),
  ('J03', 'Amigdalite aguda', 'J03 Amigdalite aguda'),
  ('J030', 'Amigdalite estreptocócica', 'J03.0 Amigdalite estreptococica'),
  ('J038', 'Amigdalite aguda devida a outros microorganismos especificados', 'J03.8 Amigdalite aguda dev outr microorg espec'),
  ('J039', 'Amigdalite aguda não especificada', 'J03.9 Amigdalite aguda NE'),
  ('J04', 'Laringite e traqueíte agudas', 'J04 Laringite e traqueite agudas'),
  ('J040', 'Laringite aguda', 'J04.0 Laringite aguda'),
  ('J041', 'Traqueíte aguda', 'J04.1 Traqueite aguda'),
  ('J042', 'Laringotraqueíte aguda', 'J04.2 Laringotraqueite aguda'),
  ('J05', 'Laringite obstrutiva aguda (crupe) e epiglotite', 'J05 Laringite obstrutiva aguda e epiglotite'),
  ('J050', 'Laringite obstrutiva aguda (crupe)', 'J05.0 Laringite obstrutiva aguda'),
  ('J051', 'Epiglotite aguda', 'J05.1 Epiglotite aguda'),
  ('J06', 'Infecções agudas das vias aéreas superiores de localizações múltiplas e não especificadas', 'J06 Infecc agudas vias aereas super loc mult NE'),
  ('J060', 'Laringofaringite aguda', 'J06.0 Laringofaringite aguda'),
  ('J068', 'Outras infecções agudas das vias aéreas superiores de localizações múltiplas', 'J06.8 Outr infecc agudas vias aereas sup loc mult'),
  ('J069', 'Infecção aguda das vias aéreas superiores não especificada', 'J06.9 Infecc aguda das vias aereas super NE'),
  ('J09', 'Influenza (gripe) devida a vírus identificado da gripe aviária', 'J09 Influenza dev virus gripe aviária'),
  ('J09', 'Influenza (gripe) devida a vírus identificado da gripe aviária', 'J09 Influenza dev virus gripe aviária'),
  ('J10', 'Influenza devida a outro vírus da influenza (gripe) identificado', 'J10 Influenza dev outro virus influenza ident'),
  ('J100', 'Influenza com pneumonia devida a outro vírus da influenza (gripe) identificado', 'J10.0 Influenza c/pneum dev outr virus influ ident'),
  ('J101', 'Influenza com outras manifestações respiratórias, devida a outro vírus da influenza (gripe) identificado', 'J10.1 Influenz c/out manif resp out vir infl ident'),
  ('J108', 'Influenza com outras manifestações, devida a outro vírus da influenza (gripe) identificado', 'J10.8 Influenza c/out manif dev out vir infl ident'),
  ('J11', 'Influenza (gripe) devida a vírus não identificado', 'J11 Influenza dev virus nao identificado'),
  ('J110', 'Influenza (gripe) com pneumonia, devida a vírus não identificado', 'J11.0 Influenza c/pneumonia dev virus nao ident'),
  ('J111', 'Influenza (gripe) com outras manifestações respiratórias, devida a vírus não identificado', 'J11.1 Influenza c/out manif resp dev virus n ident'),
  ('J118', 'Influenza (gripe) com outras manifestações, devida a vírus não identificado', 'J11.8 Influenza c/outr manif dev virus nao ident'),
  ('J12', 'Pneumonia viral não classificada em outra parte', 'J12 Pneumonia viral NCOP'),
  ('J120', 'Pneumonia devida a adenovírus', 'J12.0 Pneumonia dev adenovirus'),
  ('J121', 'Pneumonia devida a vírus respiratório sincicial', 'J12.1 Pneumonia dev virus respirat sincicial'),
  ('J122', 'Pneumonia devida à parainfluenza', 'J12.2 Pneumonia dev parainfluenza'),
  ('J128', 'Outras pneumonias virais', 'J12.8 Outr pneumonias virais'),
  ('J129', 'Pneumonia viral não especificada', 'J12.9 Pneumonia viral NE'),
  ('J13', 'Pneumonia devida a Streptococcus pneumoniae', 'J13 Pneumonia dev Streptococcus pneumoniae'),
  ('J13', 'Pneumonia devida a Streptococcus pneumoniae', 'J13 Pneumonia dev Streptococcus pneumoniae'),
  ('J14', 'Pneumonia devida a Haemophilus infuenzae', 'J14 Pneumonia dev Haemophilus infuenzae'),
  ('J14', 'Pneumonia devida a Haemophilus infuenzae', 'J14 Pneumonia dev Haemophilus infuenzae'),
  ('J15', 'Pneumonia bacteriana não classificada em outra parte', 'J15 Pneumonia bacter NCOP'),
  ('J150', 'Pneumonia devida à Klebsiella pneumoniae', 'J15.0 Pneumonia dev Klebsiella pneumoniae'),
  ('J151', 'Pneumonia devida a Pseudomonas', 'J15.1 Pneumonia dev Pseudomonas'),
  ('J152', 'Pneumonia devida a Staphylococcus', 'J15.2 Pneumonia dev Staphylococcus'),
  ('J153', 'Pneumonia devida a Streptococcus do grupo B', 'J15.3 Pneumonia dev Streptococcus do grupo B'),
  ('J154', 'Pneumonia devida a outros estreptococos', 'J15.4 Pneumonia dev outr estreptococos'),
  ('J155', 'Pneumonia devida a Escherichia coli', 'J15.5 Pneumonia dev Escherichia coli'),
  ('J156', 'Pneumonia devida a outras bactérias aeróbicas gram-negativas', 'J15.6 Pneumonia dev outr bact aerobicas gram-neg'),
  ('J157', 'Pneumonia devida a Mycoplasma pneumoniae', 'J15.7 Pneumonia dev Mycoplasma pneumoniae'),
  ('J158', 'Outras pneumonias bacterianas', 'J15.8 Outr pneumonias bacter'),
  ('J159', 'Pneumonia bacteriana não especificada', 'J15.9 Pneumonia bacter NE'),
  ('J16', 'Pneumonia devida a outros microorganismos infecciosos especificados não classificados em outra parte', 'J16 Pneumonia dev out microorg infecc espec NCOP'),
  ('J160', 'Pneumonia devida a clamídias', 'J16.0 Pneumonia dev clamidias'),
  ('J168', 'Pneumonia devida a outros microorganismos infecciosos especificados', 'J16.8 Pneumonia dev outr microorg infecc espec'),
  ('J17', 'Pneumonia em doenças classificadas em outra parte', 'J17 Pneumonia em doenc COP'),
  ('J170', 'Pneumonia em doenças bacterianas classificadas em outra parte', 'J17.0 Pneumonia em doenc bacter COP'),
  ('J171', 'Pneumonia em doenças virais classificadas em outra parte', 'J17.1 Pneumonia em doenc virais COP'),
  ('J172', 'Pneumonia em micoses classificadas em outra parte', 'J17.2 Pneumonia em micoses COP'),
  ('J173', 'Pneumonia em doenças parasitárias classificadas em outra parte', 'J17.3 Pneumonia em doenc parasit COP'),
  ('J178', 'Pneumonia em outras doenças classificadas em outra parte', 'J17.8 Pneumonia em outr doenc COP'),
  ('J18', 'Pneumonia por microorganismo não especificada', 'J18 Pneumonia p/microorg NE'),
  ('J180', 'Broncopneumonia não especificada', 'J18.0 Broncopneumonia NE'),
  ('J181', 'Pneumonia lobar não especificada', 'J18.1 Pneumonia lobar NE'),
  ('J182', 'Pneumonia hipostática não especificada', 'J18.2 Pneumonia hipostatica NE'),
  ('J188', 'Outras pneumonias devidas a microorganismos não especificados', 'J18.8 Outr pneumonias dev microorg NE'),
  ('J189', 'Pneumonia não especificada', 'J18.9 Pneumonia NE'),
  ('J20', 'Bronquite aguda', 'J20 Bronquite aguda'),
  ('J200', 'Bronquite aguda devida a Mycoplasma pneumoniae', 'J20.0 Bronquite aguda dev Mycoplasma pneumoniae'),
  ('J201', 'Bronquite aguda devida a Haemophilus influenzae', 'J20.1 Bronquite aguda dev Haemophilus influenzae'),
  ('J202', 'Bronquite aguda devida a estreptococos', 'J20.2 Bronquite aguda dev estreptococos'),
  ('J203', 'Bronquite aguda devida a vírus Coxsackie', 'J20.3 Bronquite aguda dev virus Coxsackie'),
  ('J204', 'Bronquite aguda devida a vírus parainfluenza', 'J20.4 Bronquite aguda dev virus parainfluenza'),
  ('J205', 'Bronquite aguda devida a vírus sincicial respiratório', 'J20.5 Bronquite aguda dev virus sincicial respirat'),
  ('J206', 'Bronquite aguda devida a rinovírus', 'J20.6 Bronquite aguda dev rinovirus'),
  ('J207', 'Bronquite aguda devida a echovírus', 'J20.7 Bronquite aguda dev echovirus'),
  ('J208', 'Bronquite aguda devida a outros microorganismos especificados', 'J20.8 Bronquite aguda dev outr microorg espec'),
  ('J209', 'Bronquite aguda não especificada', 'J20.9 Bronquite aguda NE'),
  ('J21', 'Bronquiolite aguda', 'J21 Bronquiolite aguda'),
  ('J210', 'Bronquiolite aguda devida a vírus sincicial respiratório', 'J21.0 Bronquiolite aguda dev virus sincicial resp'),
  ('J218', 'Bronquiolite aguda devida a outros microorganismos especificados', 'J21.8 Bronquiolite aguda dev outr microorg espec'),
  ('J219', 'Bronquite aguda não especificada', 'J21.9 Bronquite aguda NE'),
  ('J22', 'Infecções agudas não especificada das vias aéreas inferiores', 'J22 Infecc agudas NE das vias aereas infer'),
  ('J22', 'Infecções agudas não especificada das vias aéreas inferiores', 'J22 Infecc agudas NE das vias aereas infer'),
  ('J30', 'Rinite alérgica e vasomotora', 'J30 Rinite alergica e vasomotora'),
  ('J300', 'Rinite vasomotora', 'J30.0 Rinite vasomotora'),
  ('J301', 'Rinite alérgica devida a pólen', 'J30.1 Rinite alergica dev polen'),
  ('J302', 'Outras rinites alérgicas sazonais', 'J30.2 Outr rinites alergicas sazonais'),
  ('J303', 'Outras rinites alérgicas', 'J30.3 Outr rinites alergicas'),
  ('J304', 'Rinite alérgica não especificada', 'J30.4 Rinite alergica NE'),
  ('J31', 'Rinite, nasofaringite e faringite crônicas', 'J31 Rinite nasofaringite e faringite cronicas'),
  ('J310', 'Rinite crônica', 'J31.0 Rinite cronica'),
  ('J311', 'Nasofaringite crônica', 'J31.1 Nasofaringite cronica'),
  ('J312', 'Faringite crônica', 'J31.2 Faringite cronica'),
  ('J32', 'Sinusite crônica', 'J32 Sinusite cronica'),
  ('J320', 'Sinusite maxilar crônica', 'J32.0 Sinusite maxilar cronica'),
  ('J321', 'Sinusite frontal crônica', 'J32.1 Sinusite frontal cronica'),
  ('J322', 'Sinusite etmoidal crônica', 'J32.2 Sinusite etmoidal cronica'),
  ('J323', 'Sinusite esfenoidal crônica', 'J32.3 Sinusite esfenoidal cronica'),
  ('J324', 'Pansinusite crônica', 'J32.4 Pansinusite cronica'),
  ('J328', 'Outras sinusites crônicas', 'J32.8 Outr sinusites cronicas'),
  ('J329', 'Sinusite crônica não especificada', 'J32.9 Sinusite cronica NE'),
  ('J33', 'Pólipo nasal', 'J33 Polipo nasal'),
  ('J330', 'Pólipo da cavidade nasal', 'J33.0 Polipo da cavidade nasal'),
  ('J331', 'Degeneração polipóide do seio paranasal', 'J33.1 Degeneracao polipoide do seio paranasal'),
  ('J338', 'Outros pólipos do seio paranasal', 'J33.8 Outr polipos do seio paranasal'),
  ('J339', 'Pólipo nasal não especificado', 'J33.9 Polipo nasal NE'),
  ('J34', 'Outros transtornos do nariz e dos seios paranasais', 'J34 Outr transt do nariz e dos seios paranasais'),
  ('J340', 'Abscesso, furúnculo e antraz do nariz', 'J34.0 Abscesso furunculo e antraz do nariz'),
  ('J341', 'Cisto e mucocele do nariz e do seio paranasal', 'J34.1 Cisto e mucocele do nariz e seio paranasal'),
  ('J342', 'Desvio do septo nasal', 'J34.2 Desvio do septo nasal'),
  ('J343', 'Hipertrofia dos cornetos nasais', 'J34.3 Hipertrofia dos cornetos nasais'),
  ('J348', 'Outros transtornos especificados do nariz e dos seios paranasais', 'J34.8 Outr transt espec nariz e seios paranasais'),
  ('J35', 'Doenças crônicas das amígdalas e das adenóides', 'J35 Doenc cronicas das amigdalas e das adenoides'),
  ('J350', 'Amigdalite crônica', 'J35.0 Amigdalite cronica'),
  ('J351', 'Hipertrofia das amígdalas', 'J35.1 Hipertrofia das amigdalas'),
  ('J352', 'Hipertrofia das adenóides', 'J35.2 Hipertrofia das adenoides'),
  ('J353', 'Hipertrofia das amígdalas com hipertrofia das adenóides', 'J35.3 Hipertrofia amigdalas c/hipertrof adenoides'),
  ('J358', 'Outras doenças crônicas das amígdalas e das adenóides', 'J35.8 Outr doenc cronicas amigdalas e adenoides'),
  ('J359', 'Doenças das amígdalas e das adenóides não especificadas', 'J35.9 Doenc das amigdalas e das adenoides NE'),
  ('J36', 'Abscesso periamigdaliano', 'J36 Abscesso periamigdaliano'),
  ('J36', 'Abscesso periamigdaliano', 'J36 Abscesso periamigdaliano'),
  ('J37', 'Laringite e laringotraqueíte crônicas', 'J37 Laringite e laringotraqueite cronicas'),
  ('J370', 'Laringite crônica', 'J37.0 Laringite cronica'),
  ('J371', 'Laringotraqueíte crônica', 'J37.1 Laringotraqueite cronica'),
  ('J38', 'Doenças das cordas vocais e da laringe não classificadas em outra parte', 'J38 Doenc das cordas vocais e da laringe NCOP'),
  ('J380', 'Paralisia das cordas vocais e da laringe', 'J38.0 Paralisia das cordas vocais e da laringe'),
  ('J381', 'Pólipo das cordas vocais e da laringe', 'J38.1 Polipo das cordas vocais e da laringe'),
  ('J382', 'Nódulos das cordas vocais', 'J38.2 Nodulos das cordas vocais'),
  ('J383', 'Outras doenças das cordas vocais', 'J38.3 Outr doenc das cordas vocais'),
  ('J384', 'Edema da laringe', 'J38.4 Edema da laringe'),
  ('J385', 'Espasmo da laringe', 'J38.5 Espasmo da laringe'),
  ('J386', 'Estenose da laringe', 'J38.6 Estenose da laringe'),
  ('J387', 'Outras doenças da laringe', 'J38.7 Outr doenc da laringe'),
  ('J39', 'Outras doenças das vias aéreas superiores', 'J39 Outr doenc das vias aereas super'),
  ('J390', 'Abscesso retrofaríngeo e parafaríngeo', 'J39.0 Abscesso retrofaringeo e parafaringeo'),
  ('J391', 'Outros abscessos da faringe', 'J39.1 Outr abscessos da faringe'),
  ('J392', 'Outras doenças da faringe', 'J39.2 Outr doenc da faringe'),
  ('J393', 'Reação de hipersensibilidade das vias aéreas superiores de localização não especificada', 'J39.3 Reacao hipersensib vias aereas super loc NE'),
  ('J398', 'Outras doenças especificadas das vias aéreas superiores', 'J39.8 Outr doenc espec das vias aereas super'),
  ('J399', 'Doença não especificada das vias aéreas superiores', 'J39.9 Doenc NE das vias aereas super'),
  ('J40', 'Bronquite não especificada como aguda ou crônica', 'J40 Bronquite NE como aguda ou cronica'),
  ('J40', 'Bronquite não especificada como aguda ou crônica', 'J40 Bronquite NE como aguda ou cronica'),
  ('J41', 'Bronquite crônica simples e a mucopurulenta', 'J41 Bronquite cronica simples e a mucopurulenta'),
  ('J410', 'Bronquite crônica simples', 'J41.0 Bronquite cronica simples'),
  ('J411', 'Bronquite crônica mucopurulenta', 'J41.1 Bronquite cronica mucopurulenta'),
  ('J418', 'Bronquite crônica mista, simples e mucopurulenta', 'J41.8 Bronquite cron mista simples e mucopurulenta'),
  ('J42', 'Bronquite crônica não especificada', 'J42 Bronquite cronica NE'),
  ('J42', 'Bronquite crônica não especificada', 'J42 Bronquite cronica NE'),
  ('J43', 'Enfisema', 'J43 Enfisema'),
  ('J430', 'Síndrome de MacLeod', 'J43.0 Sindr de MacLeod'),
  ('J431', 'Enfisema panlobular', 'J43.1 Enfisema panlobular'),
  ('J432', 'Enfisema centrolobular', 'J43.2 Enfisema centrolobular'),
  ('J438', 'Outras formas de enfisema', 'J43.8 Outr form de enfisema'),
  ('J439', 'Enfisema não especificado', 'J43.9 Enfisema NE'),
  ('J44', 'Outras doenças pulmonares obstrutivas crônicas', 'J44 Outr doenc pulmonares obstrutivas cronicas'),
  ('J440', 'Doença pulmonar obstrutiva crônica com infecção respiratória aguda do trato respiratório inferior', 'J44.0 Doen pulm obs cron c/inf resp ag tr resp inf'),
  ('J441', 'Doença pulmonar obstrutiva crônica com exacerbação aguda não especificada', 'J44.1 Doenc pulmonar obstr cron c/exacerb aguda NE'),
  ('J448', 'Outras formas especificadas de doença pulmonar obstrutiva crônica', 'J44.8 Outr form espec doenc pulmonar obstrut cron'),
  ('J449', 'Doença pulmonar obstrutiva crônica não especificada', 'J44.9 Doenc pulmonar obstrutiva cronica NE'),
  ('J45', 'Asma', 'J45 Asma'),
  ('J450', 'Asma predominantemente alérgica', 'J45.0 Asma predom alergica'),
  ('J451', 'Asma não-alérgica', 'J45.1 Asma nao-alergica'),
  ('J458', 'Asma mista', 'J45.8 Asma mista'),
  ('J459', 'Asma não especificada', 'J45.9 Asma NE'),
  ('J46', 'Estado de mal asmático', 'J46 Estado de mal asmatico'),
  ('J46', 'Estado de mal asmático', 'J46 Estado de mal asmatico'),
  ('J47', 'Bronquectasia', 'J47 Bronquectasia'),
  ('J47', 'Bronquectasia', 'J47 Bronquectasia'),
  ('J60', 'Pneumoconiose dos mineiros de carvão', 'J60 Pneumoconiose dos mineiros de carvao'),
  ('J60', 'Pneumoconiose dos mineiros de carvão', 'J60 Pneumoconiose dos mineiros de carvao'),
  ('J61', 'Pneumoconiose devida a amianto (asbesto) e outras fibras minerais', 'J61 Pneumoconiose dev amianto outr fibr minerais'),
  ('J61', 'Pneumoconiose devida a amianto (asbesto) e outras fibras minerais', 'J61 Pneumoconiose dev amianto outr fibr minerais'),
  ('J62', 'Pneumoconiose devida a poeira que contenham sílica', 'J62 Pneumoconiose dev poeira que cont silica'),
  ('J620', 'Pneumoconiose devida a pó de talco', 'J62.0 Pneumoconiose dev po de talco'),
  ('J628', 'Pneumoconiose devida a outras poeiras que contenham sílica', 'J62.8 Pneumoconiose dev outr poeiras q cont silica'),
  ('J63', 'Pneumoconiose devida a outras poeiras inorgânicas', 'J63 Pneumoconiose dev outr poeiras inorganicas'),
  ('J630', 'Aluminose (do pulmão)', 'J63.0 Aluminose'),
  ('J631', 'Fibrose (do pulmão) causada por bauxita', 'J63.1 Fibrose causada p/bauxita'),
  ('J632', 'Beriliose', 'J63.2 Beriliose'),
  ('J633', 'Fibrose (do pulmão) causada por grafite', 'J63.3 Fibrose causada p/grafite'),
  ('J634', 'Siderose', 'J63.4 Siderose'),
  ('J635', 'Estanose', 'J63.5 Estanose'),
  ('J638', 'Pneumoconiose devida a outras poeira inorgânicas especificados', 'J63.8 Pneumoconiose dev outr poeira inorg espec'),
  ('J64', 'Pneumoconiose não especificada', 'J64 Pneumoconiose NE'),
  ('J64', 'Pneumoconiose não especificada', 'J64 Pneumoconiose NE'),
  ('J65', 'Pneumoconiose associada com tuberculose', 'J65 Pneumoconiose assoc c/tuberc'),
  ('J65', 'Pneumoconiose associada com tuberculose', 'J65 Pneumoconiose assoc c/tuberc'),
  ('J66', 'Doenças das vias aéreas devida a poeiras orgânicas específicas', 'J66 Doenc das vias aereas dev poeiras org espec'),
  ('J660', 'Bissinose', 'J66.0 Bissinose'),
  ('J661', 'Doença dos cardadores de linho', 'J66.1 Doenc dos cardadores de linho'),
  ('J662', 'Canabinose', 'J66.2 Canabinose'),
  ('J668', 'Doenças das vias aéreas devida a outras poeiras orgânicas específicas', 'J66.8 Doenc vias aereas dev outr poeiras org espec'),
  ('J67', 'Pneumonite de hipersensibilidade devida a poeiras orgânicas', 'J67 Pneumonite hipersensibilid dev poeiras org'),
  ('J670', 'Pulmão de fazendeiro', 'J67.0 Pulmao de fazendeiro'),
  ('J671', 'Bagaçose', 'J67.1 Bagacose'),
  ('J672', 'Pulmão dos criadores de pássaros', 'J67.2 Pulmao dos criadores de passaros'),
  ('J673', 'Suberose', 'J67.3 Suberose'),
  ('J674', 'Pulmão dos trabalhadores do malte', 'J67.4 Pulmao dos trabalhadores do malte'),
  ('J675', 'Pulmão dos que trabalham com cogumelos', 'J67.5 Pulmao dos que trabalham c/cogumelos'),
  ('J676', 'Pulmão dos cortadores de casca do bordo', 'J67.6 Pulmao dos cortadores de casca do bordo'),
  ('J677', 'Doença pulmonar devida aos sistemas de ar condicionado e de umidificação do ar', 'J67.7 Doenc pulmonar dev sist ar cond umidif ar'),
  ('J678', 'Pneumonites de hipersensibilidade, devidas a outras poeiras orgânicas', 'J67.8 Pneumonites hipersens dev outr poeiras org'),
  ('J679', 'Pneumonite de hipersensibilidade devida a poeira orgânica não especificada', 'J67.9 Pneumonite hipersensibilid dev poeira org NE'),
  ('J68', 'Afecções respiratórias devidas a inalação de produtos químicos, gases, fumaças e vapores', 'J68 Afecc resp dev inal prod quim gas fumac vap'),
  ('J680', 'Bronquite e pneumonite devida a produtos químicos, gases, fumaças e vapores', 'J68.0 Bronquit pneumon dev prod quim gas fumac vap'),
  ('J681', 'Edema pulmonar devido a produtos químicos, gases, fumaças e vapores', 'J68.1 Edema pulm dev prod quim gas fumac vap'),
  ('J682', 'Inflamação das vias aéreas superiores devida a produtos químicos, gases, fumaças e vapores, não classificada em outra parte', 'J68.2 Infl via aer sup dev pr qui gas fum vap NCOP'),
  ('J683', 'Outras afecções respiratórias agudas e subagudas devidas a produtos químicos, gases, fumaças e vapores', 'J68.3 Out af resp ag subag dev pro qui gas fum vap'),
  ('J684', 'Afecções respiratórias crônicas devidas a produtos químicos, gases, fumaças e vapores', 'J68.4 Afecc resp cron dev prod quim gas fum vap'),
  ('J688', 'Outras afecções respiratórias devida a produtos químicos, gases, fumaças e vapores', 'J68.8 Outr afecc resp dev prod quim gas fum vap'),
  ('J689', 'Afecção respiratória não especificada devida a produtos químicos, gases, fumaça e vapores', 'J68.9 Afecc resp NE dev prod quim gases fumac vap'),
  ('J69', 'Pneumonite devida a sólidos e líquidos', 'J69 Pneumonite dev solidos e liquidos'),
  ('J690', 'Pneumonite devida a alimento ou vômito', 'J69.0 Pneumonite dev alimento ou vomito'),
  ('J691', 'Pneumonite devida a óleos e essências', 'J69.1 Pneumonite dev oleos e essencias'),
  ('J698', 'Pneumonite devida a outros sólidos e líquidos', 'J69.8 Pneumonite dev outr solidos e liquidos'),
  ('J70', 'Afecções respiratórias devida a outros agentes externos', 'J70 Afeccoes respirat dev outr agentes externos'),
  ('J700', 'Manifestações pulmonares agudas devidas à radiação', 'J70.0 Manifestacoes pulmonares agudas dev radiacao'),
  ('J701', 'Manifestações pulmonares crônicas e outras, devidas a radiação', 'J70.1 Manif pulmonares cron e outr dev radiacao'),
  ('J702', 'Transtornos pulmonares intersticiais agudos, induzidos por droga', 'J70.2 Transt pulm interstic agudos induz p/droga'),
  ('J703', 'Transtornos pulmonares intersticiais crônicos induzidos por droga', 'J70.3 Transt pulm interstic cronicos induz p/droga'),
  ('J704', 'Transtornos pulmonar intersticial não especificado induzido por droga', 'J70.4 Transt pulm intersticial NE induz p/droga'),
  ('J708', 'Afecções respiratórias devidas a outros agentes externos especificados', 'J70.8 Afecc respirat dev outr agent externos espec'),
  ('J709', 'Afecções respiratórias devidas a agentes externos não especificados', 'J70.9 Afeccoes respirat dev agentes externos NE'),
  ('J80', 'Síndrome do desconforto respiratório do adulto', 'J80 Sindr do desconforto respirat do adulto'),
  ('J80', 'Síndrome do desconforto respiratório do adulto', 'J80 Sindr do desconforto respirat do adulto'),
  ('J81', 'Edema pulmonar, não especificado de outra forma', 'J81 Edema pulmonar NE de outr form'),
  ('J81', 'Edema pulmonar, não especificado de outra forma', 'J81 Edema pulmonar NE de outr form'),
  ('J82', 'Eosinofilia pulmonar, não classificada em outra parte', 'J82 Eosinofilia pulmonar NCOP'),
  ('J82', 'Eosinofilia pulmonar, não classificada em outra parte', 'J82 Eosinofilia pulmonar NCOP'),
  ('J84', 'Outras doenças pulmonares intersticiais', 'J84 Outr doenc pulmonares intersticiais'),
  ('J840', 'Afecções alveolares e parieto-alveolares', 'J84.0 Afeccoes alveolares e parieto-alveolares'),
  ('J841', 'Outras doenças pulmonares intersticiais com fibrose', 'J84.1 Outr doenc pulm intersticiais c/fibrose'),
  ('J848', 'Outras doenças pulmonares intersticiais especificadas', 'J84.8 Outr doenc pulmonares intersticiais espec'),
  ('J849', 'Doença pulmonar intersticial não especificadas', 'J84.9 Doenc pulmonar intersticial NE'),
  ('J85', 'Abscesso do pulmão e do mediastino', 'J85 Abscesso do pulmao e do mediastino'),
  ('J850', 'Gangrena e necrose do pulmão', 'J85.0 Gangrena e necrose do pulmao'),
  ('J851', 'Abscesso do pulmão com pneumonia', 'J85.1 Abscesso do pulmao c/pneumonia'),
  ('J852', 'Abscesso do pulmão sem pneumonia', 'J85.2 Abscesso do pulmao s/pneumonia'),
  ('J853', 'Abscesso do mediastino', 'J85.3 Abscesso do mediastino'),
  ('J86', 'Piotórax', 'J86 Piotorax'),
  ('J860', 'Piotórax com fístula', 'J86.0 Piotorax c/fistula'),
  ('J869', 'Piotórax sem fístula', 'J86.9 Piotorax s/fistula'),
  ('J90', 'Derrame pleural não classificado em outra parte', 'J90 Derrame pleural NCOP'),
  ('J90', 'Derrame pleural não classificado em outra parte', 'J90 Derrame pleural NCOP'),
  ('J91', 'Derrame pleural em afecções classificadas em outra parte', 'J91 Derrame pleural em afeccoes COP'),
  ('J91', 'Derrame pleural em afecções classificadas em outra parte', 'J91 Derrame pleural em afeccoes COP'),
  ('J92', 'Placas pleurais', 'J92 Placas pleurais'),
  ('J920', 'Placas pleurais com presença de amianto (asbesto)', 'J92.0 Placas pleurais c/presenca de amianto'),
  ('J929', 'Placas pleurais sem presença de amianto (asbesto)', 'J92.9 Placas pleurais cem presenca de amianto'),
  ('J93', 'Pneumotórax', 'J93 Pneumotorax'),
  ('J930', 'Pneumotórax de tensão, espontâneo', 'J93.0 Pneumotorax de tensao espontaneo'),
  ('J931', 'Outras formas de pneumotórax espontâneo', 'J93.1 Outr form de pneumotorax espontaneo'),
  ('J938', 'Outros tipos de pneumotórax, especificados', 'J93.8 Outr tipos de pneumotorax espec'),
  ('J939', 'Pneumotórax não especificado', 'J93.9 Pneumotorax NE'),
  ('J94', 'Outras afecções pleurais', 'J94 Outr afeccoes pleurais'),
  ('J940', 'Derrame quiloso ou quiliforme', 'J94.0 Derrame quiloso ou quiliforme'),
  ('J941', 'Fibrotórax', 'J94.1 Fibrotorax'),
  ('J942', 'Hemotórax', 'J94.2 Hemotorax'),
  ('J948', 'Outras afecções pleurais especificadas', 'J94.8 Outr afeccoes pleurais espec'),
  ('J949', 'Afecção pleural não especificada', 'J94.9 Afeccao pleural NE'),
  ('J95', 'Afecções respiratórias pós-procedimentos não classificadas em outra parte', 'J95 Afeccoes respirat pos-proced NCOP'),
  ('J950', 'Mau funcionamento de traqueostomia', 'J95.0 Mau funcionamento de traqueostomia'),
  ('J951', 'Insuficiência pulmonar aguda subsequente a cirurgia torácica', 'J95.1 Insuf pulmonar aguda subseq cirurg toracica'),
  ('J952', 'Insuficiência pulmonar aguda subsequente a cirurgia não torácica', 'J95.2 Insuf pulm aguda subseq cirurg nao toracica'),
  ('J953', 'Insuficiência pulmonar crônica pós-cirúrgica', 'J95.3 Insuf pulmonar cronica pos-cirurgica'),
  ('J954', 'Síndrome de Mendelson', 'J95.4 Sindr de Mendelson'),
  ('J955', 'Estenose subglótica pós-procedimento', 'J95.5 Estenose subglotica pos-proced'),
  ('J958', 'Outros transtornos respiratórios pós-procedimentos', 'J95.8 Outr transt respirat pos-proced'),
  ('J959', 'Transtornos respiratórios pós-procedimentos não especificados', 'J95.9 Transt respirat pos-proced NE'),
  ('J96', 'Insuficiência respiratória não classificada de outra parte', 'J96 Insuf respirat NCOP'),
  ('J960', 'Insuficiência respiratória aguda', 'J96.0 Insuf respirat aguda'),
  ('J961', 'Insuficiência respiratória crônica', 'J96.1 Insuf respirat cronica'),
  ('J969', 'Insuficiência respiratória não especificada', 'J96.9 Insuf respirat NE'),
  ('J98', 'Outros transtornos respiratórios', 'J98 Outr transt respirat'),
  ('J980', 'Outras doenças dos brônquios não classificadas em outra parte', 'J98.0 Outr doenc dos bronquios NCOP'),
  ('J981', 'Colapso pulmonar', 'J98.1 Colapso pulmonar'),
  ('J982', 'Enfisema intersticial', 'J98.2 Enfisema intersticial'),
  ('J983', 'Enfisema compensatório', 'J98.3 Enfisema compensatorio'),
  ('J984', 'Outros transtornos pulmonares', 'J98.4 Outr transt pulmonares'),
  ('J985', 'Doenças do mediastino não classificadas em outra parte', 'J98.5 Doenc do mediastino NCOP'),
  ('J986', 'Transtornos do diafragma', 'J98.6 Transt do diafragma'),
  ('J988', 'Outros transtornos respiratórios especificados', 'J98.8 Outr transt respirat espec'),
  ('J989', 'Transtorno respiratório não especificados', 'J98.9 Transt respirat NE'),
  ('J99', 'Transtornos respiratórios em doenças classificadas em outra parte', 'J99 Transt respirat em doenc COP'),
  ('J990', 'Doença pulmonar reumatóide', 'J99.0 Doenc pulmonar reumatoide'),
  ('J991', 'Transtornos respiratórios em outras doenças sistêmicas do tecido conjuntivo classificadas em outra parte', 'J99.1 Transt respirat outr doenc sist tec conj COP'),
  ('J998', 'Transtornos respiratórios em outras doenças classificadas em outra parte', 'J99.8 Transt respirat em outr doenc COP');
