INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('C00', 'Neoplasia maligna do lábio', 'C00 Neopl malig do labio'),
  ('C000', 'Neoplasia maligna do lábio superior externo', 'C00.0 Labio super externo'),
  ('C001', 'Neoplasia maligna do lábio inferior externo', 'C00.1 Labio infer externo'),
  ('C002', 'Neoplasia maligna do lábio externo, não especificado', 'C00.2 Labio externo NE'),
  ('C003', 'Neoplasia maligna do lábio superior, face interna', 'C00.3 Labio super face interna'),
  ('C004', 'Neoplasia maligna do lábio inferior, face interna', 'C00.4 Labio infer face interna'),
  ('C005', 'Neoplasia maligna do lábio, sem especificação, face interna', 'C00.5 Labio s/especificacao face interna'),
  ('C006', 'Neoplasia maligna da comissura labial', 'C00.6 Comissura labial'),
  ('C008', 'Neoplasia maligna do lábio com lesão invasiva', 'C00.8 Lesao invasiva do labio'),
  ('C009', 'Neoplasia maligna do lábio, não especificado', 'C00.9 Labio NE'),
  ('C01', 'Neoplasia maligna da base da língua', 'C01 Neopl malig da base da lingua'),
  ('C01', 'Neoplasia maligna da base da língua', 'C01 Neopl malig da base da lingua'),
  ('C02', 'Neoplasia maligna de outras partes e de partes não especificadas da língua', 'C02 Neopl malig outr partes e NE da lingua'),
  ('C020', 'Neoplasia maligna da face dorsal da língua', 'C02.0 Face dorsal da lingua'),
  ('C021', 'Neoplasia maligna da borda da língua', 'C02.1 Borda da lingua'),
  ('C022', 'Neoplasia maligna da face ventral da língua', 'C02.2 Face ventral da lingua'),
  ('C023', 'Neoplasia maligna de dois terços anteriores da língua, parte não especificada', 'C02.3 Dois tercos anteriores da lingua parte NE'),
  ('C024', 'Neoplasia maligna da amígdala lingual', 'C02.4 Amigdala lingual'),
  ('C028', 'Neoplasia maligna da língua com lesão invasiva', 'C02.8 Lesao invasiva da lingua'),
  ('C029', 'Neoplasia maligna da língua, não especificada', 'C02.9 Lingua NE'),
  ('C03', 'Neoplasia maligna da gengiva', 'C03 Neopl malig da gengiva'),
  ('C030', 'Neoplasia maligna da gengiva superior', 'C03.0 Gengiva super'),
  ('C031', 'Neoplasia maligna da gengiva inferior', 'C03.1 Gengiva infer'),
  ('C039', 'Neoplasia maligna da gengiva, não especificada', 'C03.9 Gengiva NE'),
  ('C04', 'Neoplasia maligna do assoalho da boca', 'C04 Neopl malig do assoalho da boca'),
  ('C040', 'Neoplasia maligna do assoalho anterior da boca', 'C04.0 Assoalho anterior da boca'),
  ('C041', 'Neoplasia maligna do assoalho lateral da boca', 'C04.1 Assoalho lateral da boca'),
  ('C048', 'Neoplasia maligna do assoalho da boca com lesão invasiva', 'C04.8 Lesao invasiva do assoalho da boca'),
  ('C049', 'Neoplasia maligna do assoalho da boca, não especificado', 'C04.9 Assoalho da boca NE'),
  ('C05', 'Neoplasia maligna do palato', 'C05 Neopl malig do palato'),
  ('C050', 'Neoplasia maligna do palato duro', 'C05.0 Palato duro'),
  ('C051', 'Neoplasia maligna do palato mole', 'C05.1 Palato mole'),
  ('C052', 'Neoplasia maligna da úvula', 'C05.2 Uvula'),
  ('C058', 'Neoplasia maligna do palato com lesão invasiva', 'C05.8 Lesao invasiva do palato'),
  ('C059', 'Neoplasia maligna do palato, não especificado', 'C05.9 Palato NE'),
  ('C06', 'Neoplasia maligna de outras partes e de partes não especificadas da boca', 'C06 Neopl malig outr partes e partes NE da boca'),
  ('C060', 'Neoplasia maligna da mucosa oral', 'C06.0 Mucosa oral'),
  ('C061', 'Neoplasia maligna do vestíbulo da boca', 'C06.1 Vestibulo da boca'),
  ('C062', 'Neoplasia maligna da área retromolar', 'C06.2 Area retromolar'),
  ('C068', 'Neoplasia maligna de outras partes e de partes não especificadas da boca com lesão invasiva', 'C06.8 Lesao invasiva outr partes e partes NE boca'),
  ('C069', 'Neoplasia maligna da boca, não especificada', 'C06.9 Boca NE'),
  ('C07', 'Neoplasia maligna da glândula parótida', 'C07 Neopl malig da gland parotida'),
  ('C07', 'Neoplasia maligna da glândula parótida', 'C07 Neopl malig da gland parotida'),
  ('C08', 'Neoplasia maligna de outras glândulas salivares maiores e as não especificadas', 'C08 Neopl malig outr gland saliv maiores e NE'),
  ('C080', 'Neoplasia maligna da glândula submandibular', 'C08.0 Gland submandibular'),
  ('C081', 'Neoplasia maligna da glândula sublingual', 'C08.1 Gland sublingual'),
  ('C088', 'Neoplasia maligna das glândulas salivares maiores com lesão invasiva', 'C08.8 Lesao invasiva de gland salivares maiores'),
  ('C089', 'Neoplasia maligna da glândula salivar maior, não especificada', 'C08.9 Gland salivar maior NE'),
  ('C09', 'Neoplasia maligna da amígdala', 'C09 Neopl malig da amigdala'),
  ('C090', 'Neoplasia maligna da fossa amigdaliana', 'C09.0 Fossa amigdaliana'),
  ('C091', 'Neoplasia maligna do pilar amigdaliano (anterior) (posterior)', 'C09.1 Pilar amigdaliano'),
  ('C098', 'Neoplasia maligna da amígdala com lesão invasiva', 'C09.8 Lesao invasiva da amigdala'),
  ('C099', 'Neoplasia maligna da amígdala, não especificada', 'C09.9 Amigdala NE'),
  ('C10', 'Neoplasia maligna da orofaringe', 'C10 Neopl malig da orofaringe'),
  ('C100', 'Neoplasia maligna da valécula', 'C10.0 Valecula'),
  ('C101', 'Neoplasia maligna da face anterior da epiglote', 'C10.1 Face anterior da epiglote'),
  ('C102', 'Neoplasia maligna da parede lateral da orofaringe', 'C10.2 Parede lateral da orofaringe'),
  ('C103', 'Neoplasia maligna da parede posterior da orofaringe', 'C10.3 Parede posterior da orofaringe'),
  ('C104', 'Neoplasia maligna da fenda branquial', 'C10.4 Fenda branquial'),
  ('C108', 'Neoplasia maligna da orofaringe com lesão invasiva', 'C10.8 Lesao invasiva da orofaringe'),
  ('C109', 'Neoplasia maligna da orofaringe, não especificada', 'C10.9 Orofaringe NE'),
  ('C11', 'Neoplasia maligna da nasofaringe', 'C11 Neopl malig da nasofaringe'),
  ('C110', 'Neoplasia maligna da parede superior da nasofaringe', 'C11.0 Parede super da nasofaringe'),
  ('C111', 'Neoplasia maligna da parede posterior da nasofaringe', 'C11.1 Parede posterior da nasofaringe'),
  ('C112', 'Neoplasia maligna da parede lateral da nasofaringe', 'C11.2 Parede lateral da nasofaringe'),
  ('C113', 'Neoplasia maligna da parede anterior da nasofaringe', 'C11.3 Parede anterior da nasofaringe'),
  ('C118', 'Neoplasia maligna da nasofaringe com lesão invasiva', 'C11.8 Lesao invasiva da nasofaringe'),
  ('C119', 'Neoplasia maligna da nasofaringe, não especificada', 'C11.9 Nasofaringe NE'),
  ('C12', 'Neoplasia maligna do seio piriforme', 'C12 Neopl malig do seio piriforme'),
  ('C12', 'Neoplasia maligna do seio piriforme', 'C12 Neopl malig do seio piriforme'),
  ('C13', 'Neoplasia maligna da hipofaringe', 'C13 Neopl malig da hipofaringe'),
  ('C130', 'Neoplasia maligna da região pós-cricóidea', 'C13.0 Regiao pos-cricoidea'),
  ('C131', 'Neoplasia maligna da prega ariepiglótica, face hipofaríngea', 'C13.1 Prega ariepiglotica face hipofaringea'),
  ('C132', 'Neoplasia maligna da parede posterior da hipofaringe', 'C13.2 Parede posterior da hipofaringe'),
  ('C138', 'Neoplasia maligna da hipofaringe com lesão invasiva', 'C13.8 Lesao invasiva da hipofaringe'),
  ('C139', 'Neoplasia maligna da hipofaringe, não especificada', 'C13.9 Hipofaringe NE'),
  ('C14', 'Neoplasia maligna de outras localizações e de localizações mal definida, do lábio, cavidade oral e faringe', 'C14 Neop mal out loc mal def labio cav oral far'),
  ('C140', 'Neoplasia maligna da faringe, não especificada', 'C14.0 Faringe NE'),
  ('C142', 'Neoplasia maligna do anel de Waldeyer', 'C14.2 Anel de Waldeyer'),
  ('C148', 'Neoplasia maligna do lábio, cavidade oral e faringe com lesão invasiva', 'C14.8 Lesao invasiva labio cavidade oral e faringe'),
  ('C15', 'Neoplasia maligna do esôfago', 'C15 Neopl malig do esofago'),
  ('C150', 'Neoplasia maligna da porção cervical do esôfago (esôfago cervical)', 'C15.0 Porcao cervical do esofago'),
  ('C151', 'Neoplasia maligna da porção torácica do esôfago (esôfago torácico)', 'C15.1 Porcao toracica do esofago'),
  ('C152', 'Neoplasia maligna da porção abdominal do esôfago (esôfago abdominal)', 'C15.2 Porcao abdominal do esofago'),
  ('C153', 'Neoplasia maligna do terço superior do esôfago', 'C15.3 Terco super do esofago'),
  ('C154', 'Neoplasia maligna do terço médio do esôfago', 'C15.4 Terco medio do esofago'),
  ('C155', 'Neoplasia maligna do terço inferior do esôfago', 'C15.5 Terco infer do esofago'),
  ('C158', 'Neoplasia maligna do esôfago com lesão invasiva', 'C15.8 Lesao invasiva do esofago'),
  ('C159', 'Neoplasia maligna do esôfago, não especificado', 'C15.9 Esofago NE'),
  ('C16', 'Neoplasia maligna do estômago', 'C16 Neopl malig do estomago'),
  ('C160', 'Neoplasia maligna da cárdia', 'C16.0 Cardia'),
  ('C161', 'Neoplasia maligna do fundo do estômago', 'C16.1 Fundo do estomago'),
  ('C162', 'Neoplasia maligna do corpo do estômago', 'C16.2 Corpo do estomago'),
  ('C163', 'Neoplasia maligna do antro pilórico', 'C16.3 Antro pilorico'),
  ('C164', 'Neoplasia maligna do piloro', 'C16.4 Piloro'),
  ('C165', 'Neoplasia maligna da pequena curvatura do estômago, não especificada', 'C16.5 Pequena curvatura do estomago NE'),
  ('C166', 'Neoplasia maligna da grande curvatura do estômago, não especificada', 'C16.6 Grande curvatura do estomago NE'),
  ('C168', 'Neoplasia maligna do estômago com lesão invasiva', 'C16.8 Lesao invasiva do estomago'),
  ('C169', 'Neoplasia maligna do estômago, não especificado', 'C16.9 Estomago NE'),
  ('C17', 'Neoplasia maligna do intestino delgado', 'C17 Neopl malig do intestino delgado'),
  ('C170', 'Neoplasia maligna do duodeno', 'C17.0 Duodeno'),
  ('C171', 'Neoplasia maligna do jejuno', 'C17.1 Jejuno'),
  ('C172', 'Neoplasia maligna do íleo', 'C17.2 Ileo'),
  ('C173', 'Neoplasia maligna do divertículo de Meckel', 'C17.3 Diverticulo de Meckel'),
  ('C178', 'Neoplasia maligna do intestino delgado com lesão invasiva', 'C17.8 Lesao invasiva do intestino delgado'),
  ('C179', 'Neoplasia maligna do intestino delgado, não especificado', 'C17.9 Intestino delgado NE'),
  ('C18', 'Neoplasia maligna do cólon', 'C18 Neopl malig do colon'),
  ('C180', 'Neoplasia maligna do ceco', 'C18.0 Ceco'),
  ('C181', 'Neoplasia maligna do apêndice (vermiforme)', 'C18.1 Apendice'),
  ('C182', 'Neoplasia maligna do cólon ascendente', 'C18.2 Colon ascendente'),
  ('C183', 'Neoplasia maligna da flexura (ângulo) hepática(o)', 'C18.3 Flexura hepatica'),
  ('C184', 'Neoplasia maligna do cólon transverso', 'C18.4 Colon transverso'),
  ('C185', 'Neoplasia maligna da flexura (ângulo) esplênica(o)', 'C18.5 Flexura esplenica'),
  ('C186', 'Neoplasia maligna do cólon descendente', 'C18.6 Colon descendente'),
  ('C187', 'Neoplasia maligna do cólon sigmóide', 'C18.7 Colon sigmoide'),
  ('C188', 'Neoplasia maligna do cólon com lesão invasiva', 'C18.8 Lesao invasiva do colon'),
  ('C189', 'Neoplasia maligna do cólon, não especificado', 'C18.9 Colon NE'),
  ('C19', 'Neoplasia maligna da junção retossigmóide', 'C19 Neopl malig da juncao retossigmoide'),
  ('C19', 'Neoplasia maligna da junção retossigmóide', 'C19 Neopl malig da juncao retossigmoide'),
  ('C20', 'Neoplasia maligna do reto', 'C20 Neopl malig do reto'),
  ('C20', 'Neoplasia maligna do reto', 'C20 Neopl malig do reto'),
  ('C21', 'Neoplasia maligna do ânus e do canal anal', 'C21 Neopl malig do anus e do canal anal'),
  ('C210', 'Neoplasia maligna do ânus, não especificado', 'C21.0 Anus NE'),
  ('C211', 'Neoplasia maligna do canal anal', 'C21.1 Canal anal'),
  ('C212', 'Neoplasia maligna da zona cloacogênica', 'C21.2 Zona cloacogenica'),
  ('C218', 'Neoplasia maligna do reto, ânus e do canal anal com lesão invasiva', 'C21.8 Lesao invasiva do reto anus e do canal anal'),
  ('C22', 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas', 'C22 Neopl malig figado vias biliares intra-hepat'),
  ('C220', 'Carcinoma de células hepáticas', 'C22.0 Carcinoma de celulas hepaticas'),
  ('C221', 'Carcinoma de vias biliares intra-hepáticas', 'C22.1 Carcinoma de vias biliares intra-hepaticas'),
  ('C222', 'Hepatoblastoma', 'C22.2 Hepatoblastoma'),
  ('C223', 'Angiossarcoma do fígado', 'C22.3 Angiossarcoma do figado'),
  ('C224', 'Outros sarcomas do fígado', 'C22.4 Outr sarcomas do figado'),
  ('C227', 'Outros carcinomas especificados do fígado', 'C22.7 Outr carcinomas espec do figado'),
  ('C229', 'Neoplasia maligna do fígado, não especificada', 'C22.9 Neopl malig do figado NE'),
  ('C23', 'Neoplasia maligna da vesícula biliar', 'C23 Neopl malig da vesicula biliar'),
  ('C23', 'Neoplasia maligna da vesícula biliar', 'C23 Neopl malig da vesicula biliar'),
  ('C24', 'Neoplasia maligna de outras partes, e de partes não especificadas das vias biliares', 'C24 Neopl malig outr partes e NE vias biliares'),
  ('C240', 'Neoplasia maligna das vias biliares extra-hepáticas', 'C24.0 Vias biliares extra-hepaticas'),
  ('C241', 'Neoplasia maligna da ampola de Vater', 'C24.1 Ampola de Vater'),
  ('C248', 'Neoplasia maligna das vias biliares com lesão invasiva', 'C24.8 Lesao invasiva das vias biliares'),
  ('C249', 'Neoplasia maligna da via biliar, não especificada', 'C24.9 Via biliar NE'),
  ('C25', 'Neoplasia maligna do pâncreas', 'C25 Neopl malig do pancreas'),
  ('C250', 'Neoplasia maligna da cabeça do pâncreas', 'C25.0 Cabeca do pancreas'),
  ('C251', 'Neoplasia maligna do corpo do pâncreas', 'C25.1 Corpo do pancreas'),
  ('C252', 'Neoplasia maligna da cauda do pâncreas', 'C25.2 Cauda do pancreas'),
  ('C253', 'Neoplasia maligna do canal pancreático', 'C25.3 Canal pancreatico'),
  ('C254', 'Neoplasia maligna do pâncreas endócrino', 'C25.4 Pancreas endocrino'),
  ('C257', 'Neoplasia maligna de outras partes do pâncreas', 'C25.7 Neopl malig de outr partes do pancreas'),
  ('C258', 'Neoplasia maligna do pâncreas com lesão invasiva', 'C25.8 Lesao invasiva do pancreas'),
  ('C259', 'Neoplasia maligna do pâncreas, não especificado', 'C25.9 Pancreas NE'),
  ('C26', 'Neoplasia maligna de outros órgãos digestivos e de localizações mal definidas no aparelho digestivo', 'C26 Neopl malig outr mal def aparelho digestivo'),
  ('C260', 'Neoplasia maligna do trato intestinal, parte não especificada', 'C26.0 Trato intestinal parte NE'),
  ('C261', 'Neoplasia maligna do baço', 'C26.1 Baco'),
  ('C268', 'Neoplasia maligna do aparelho digestivo com lesão invasiva', 'C26.8 Lesao invasiva do aparelho digestivo'),
  ('C269', 'Neoplasia maligna de localizações mal definidas dentro do aparelho digestivo', 'C26.9 Localiz mal def dentro aparelho digestivo'),
  ('C30', 'Neoplasia maligna da cavidade nasal e do ouvido médio', 'C30 Neopl malig cavidade nasal e do ouvido medio'),
  ('C300', 'Neoplasia maligna da cavidade nasal', 'C30.0 Cavidade nasal'),
  ('C301', 'Neoplasia maligna do ouvido médio', 'C30.1 Ouvido medio'),
  ('C31', 'Neoplasia maligna dos seios da face', 'C31 Neopl malig dos seios da face'),
  ('C310', 'Neoplasia maligna do seio maxilar', 'C31.0 Seio maxilar'),
  ('C311', 'Neoplasia maligna do seio etmoidal', 'C31.1 Seio etmoidal'),
  ('C312', 'Neoplasia maligna do seio frontal', 'C31.2 Seio frontal'),
  ('C313', 'Neoplasia maligna do seio esfenoidal', 'C31.3 Seio esfenoidal'),
  ('C318', 'Neoplasia maligna dos seios da face com lesão invasiva', 'C31.8 Lesao invasiva dos seios da face'),
  ('C319', 'Neoplasia maligna do seio da face, não especificado', 'C31.9 Seio da face NE'),
  ('C32', 'Neoplasia maligna da laringe', 'C32 Neopl malig da laringe'),
  ('C320', 'Neoplasia maligna da glote', 'C32.0 Glote'),
  ('C321', 'Neoplasia maligna da região supraglótica', 'C32.1 Regiao supraglotica'),
  ('C322', 'Neoplasia maligna da região subglótica', 'C32.2 Regiao subglotica'),
  ('C323', 'Neoplasia maligna das cartilagens da laringe', 'C32.3 Cartilagens da laringe'),
  ('C328', 'Neoplasia maligna da laringe com lesão invasiva', 'C32.8 Lesao invasiva da laringe'),
  ('C329', 'Neoplasia maligna da laringe, não especificada', 'C32.9 Laringe NE'),
  ('C33', 'Neoplasia maligna da traquéia', 'C33 Neopl malig da traqueia'),
  ('C33', 'Neoplasia maligna da traquéia', 'C33 Neopl malig da traqueia'),
  ('C34', 'Neoplasia maligna dos brônquios e dos pulmões', 'C34 Neopl malig dos bronquios e dos pulmoes'),
  ('C340', 'Neoplasia maligna do brônquio principal', 'C34.0 Bronquio principal'),
  ('C341', 'Neoplasia maligna do lobo superior, brônquio ou pulmão', 'C34.1 Lobo super bronquio ou pulmao'),
  ('C342', 'Neoplasia maligna do lobo médio, brônquio ou pulmão', 'C34.2 Lobo medio bronquio ou pulmao'),
  ('C343', 'Neoplasia maligna do lobo inferior, brônquio ou pulmão', 'C34.3 Lobo infer bronquio ou pulmao'),
  ('C348', 'Neoplasia maligna dos brônquios e dos pulmões com lesão invasiva', 'C34.8 Lesao invasiva dos bronquios e dos pulmoes'),
  ('C349', 'Neoplasia maligna dos brônquios ou pulmões, não especificado', 'C34.9 Bronquios ou pulmoes NE'),
  ('C37', 'Neoplasia maligna do timo', 'C37 Neopl malig do timo'),
  ('C37', 'Neoplasia maligna do timo', 'C37 Neopl malig do timo'),
  ('C38', 'Neoplasia maligna do coração, mediastino e pleura', 'C38 Neopl malig do coracao mediastino e pleura'),
  ('C380', 'Neoplasia maligna do coração', 'C38.0 Coracao'),
  ('C381', 'Neoplasia maligna do mediastino anterior', 'C38.1 Mediastino anterior'),
  ('C382', 'Neoplasia maligna do mediastino posterior', 'C38.2 Mediastino posterior'),
  ('C383', 'Neoplasia maligna do mediastino, porção não especificada', 'C38.3 Mediastino porcao NE'),
  ('C384', 'Neoplasia maligna da pleura', 'C38.4 Pleura'),
  ('C388', 'Neoplasia maligna do coração, mediastino e pleura com lesão invasiva', 'C38.8 Lesao invasiva coracao mediastino e pleura'),
  ('C39', 'Neoplasia maligna de outras localizações e de localizações mal definidas do aparelho respiratório e dos órgãos intratorácicos', 'C39 Neop mal out loc mal def ap resp org intrat'),
  ('C390', 'Neoplasia maligna do trato respiratório superior, porção não especificada', 'C39.0 Trato respirat super porcao NE'),
  ('C398', 'Neoplasia maligna do aparelho respiratório e dos órgãos intratorácicos com lesão invasiva', 'C39.8 Lesao invasiva ap respirat org intratoracic'),
  ('C399', 'Neoplasia maligna de localizações mal definidas do aparelho respiratório', 'C39.9 Localiz mal definidas do aparelho respirat'),
  ('C40', 'Neoplasia maligna dos ossos e cartilagens articulares dos membros', 'C40 Neopl malig ossos/cartilag artic membros'),
  ('C400', 'Neoplasia maligna da omoplata (escápula) e ossos longos dos membros superiores', 'C40.0 Omoplata e ossos longos dos membros super'),
  ('C401', 'Neoplasia maligna dos ossos curtos dos membros superiores', 'C40.1 Ossos curtos dos membros super'),
  ('C402', 'Neoplasia maligna dos ossos longos dos membros inferiores', 'C40.2 Ossos longos dos membros infer'),
  ('C403', 'Neoplasia maligna dos ossos curtos dos membros inferiores', 'C40.3 Ossos curtos dos membros infer'),
  ('C408', 'Neoplasia maligna dos ossos e cartilagens articulares dos membros com lesão invasiva', 'C40.8 Lesao invasiva ossos/cartilag artic membros'),
  ('C409', 'Neoplasia maligna dos ossos e cartilagens articulares de membro não especificado', 'C40.9 Ossos e cartilagens articulares de membro NE'),
  ('C41', 'Neoplasia maligna dos ossos e das cartilagens articulares de outras localizações e de localizações não especificadas', 'C41 Neopl malig ossos/cartil artic outr loc e NE'),
  ('C410', 'Neoplasia maligna dos ossos do crânio e da face', 'C41.0 Ossos do cranio e da face'),
  ('C411', 'Neoplasia maligna da mandíbula', 'C41.1 Mandibula'),
  ('C412', 'Neoplasia maligna da coluna vertebral', 'C41.2 Coluna vertebral'),
  ('C413', 'Neoplasia maligna das costelas, esterno e clavícula', 'C41.3 Costelas esterno e clavicula'),
  ('C414', 'Neoplasia maligna dos ossos da pelve, sacro e cóccix', 'C41.4 Ossos da pelve sacro e coccix'),
  ('C418', 'Neoplasia maligna dos ossos e das cartilagens articulares com lesão invasiva', 'C41.8 Lesao invasiva ossos e cartilag articulares'),
  ('C419', 'Neoplasia maligna dos ossos e cartilagens articulares, não especificados', 'C41.9 Ossos e cartilagens articulares NE'),
  ('C43', 'Melanoma maligno da pele', 'C43 Melanoma malig da pele'),
  ('C430', 'Melanoma maligno do lábio', 'C43.0 Melanoma malig do labio'),
  ('C431', 'Melanoma maligno da pálpebra, incluindo as comissuras palpebrais', 'C43.1 Melanoma malig palpebra incl comiss palpebr'),
  ('C432', 'Melanoma maligno da orelha e do conduto auditivo externo', 'C43.2 Melanoma malig orelha conduto auditiv extern'),
  ('C433', 'Melanoma maligno de outras partes e partes não especificadas da face', 'C43.3 Melanoma malig outr partes e NE da face'),
  ('C434', 'Melanoma maligno do couro cabeludo e do pescoço', 'C43.4 Melanoma malig couro cabeludo e do pescoco'),
  ('C435', 'Melanoma maligno do tronco', 'C43.5 Melanoma maligno do tronco'),
  ('C436', 'Melanoma maligno do membro superior, incluindo ombro', 'C43.6 Melanoma maligno do membro super incl ombro'),
  ('C437', 'Melanoma maligno do membro inferior, incluindo quadril', 'C43.7 Melanoma maligno membro infer incl quadril'),
  ('C438', 'Melanoma maligno invasivo da pele', 'C43.8 Melanoma maligno invasivo da pele'),
  ('C439', 'Melanoma maligno de pele, não especificado', 'C43.9 Melanoma maligno de pele NE'),
  ('C44', 'Outras neoplasias malignas da pele', 'C44 Outr neopl malig da pele'),
  ('C440', 'Neoplasia maligna da pele do lábio', 'C44.0 Pele do labio'),
  ('C441', 'Neoplasia maligna da pele da pálpebra, incluindo o canto', 'C44.1 Pele da palpebra incl o canto'),
  ('C442', 'Neoplasia maligna da pele da orelha e do conduto auditivo externo', 'C44.2 Pele da orelha e do conduto auditivo externo'),
  ('C443', 'Neoplasia maligna da pele de outras partes e de partes não especificadas da face', 'C44.3 Pele de outr partes e de partes NE da face'),
  ('C444', 'Neoplasia maligna da pele do couro cabeludo e do pescoço', 'C44.4 Pele do couro cabeludo e do pescoco'),
  ('C445', 'Neoplasia maligna da pele do tronco', 'C44.5 Pele do tronco'),
  ('C446', 'Neoplasia maligna da pele do membro superior, incluindo ombro', 'C44.6 Pele do membro super incl ombro'),
  ('C447', 'Neoplasia maligna da pele do membro inferior, incluindo quadril', 'C44.7 Pele do membro infer incl quadril'),
  ('C448', 'Neoplasia maligna da pele com lesão invasiva', 'C44.8 Lesao invasiva da pele'),
  ('C449', 'Neoplasia maligna da pele, não especificada', 'C44.9 Neopl malig da pele NE'),
  ('C45', 'Mesotelioma', 'C45 Mesotelioma'),
  ('C450', 'Mesotelioma da pleura', 'C45.0 Mesotelioma da pleura'),
  ('C451', 'Mesotelioma do peritônio', 'C45.1 Mesotelioma do peritonio'),
  ('C452', 'Mesotelioma do pericárdio', 'C45.2 Mesotelioma do pericardio'),
  ('C457', 'Mesotelioma de outras localizações', 'C45.7 Mesotelioma de outr localiz'),
  ('C459', 'Mesotelioma, não especificado', 'C45.9 Mesotelioma NE'),
  ('C46', 'Sarcoma de Kaposi', 'C46 Sarcoma de Kaposi'),
  ('C460', 'Sarcoma de Kaposi da pele', 'C46.0 Sarcoma de Kaposi da pele'),
  ('C461', 'Sarcoma de Kaposi de tecidos moles', 'C46.1 Sarcoma de Kaposi de tec moles'),
  ('C462', 'Sarcoma de Kaposi do palato', 'C46.2 Sarcoma de Kaposi do palato'),
  ('C463', 'Sarcoma de Kaposi dos gânglios linfáticos', 'C46.3 Sarcoma de Kaposi dos ganglios linfaticos'),
  ('C467', 'Sarcoma de Kaposi de outras localizações', 'C46.7 Sarcoma de Kaposi de outr localiz'),
  ('C468', 'Sarcoma de Kaposi de múltiplos órgãos', 'C46.8 Sarcoma de Kaposi de mult orgaos'),
  ('C469', 'Sarcoma de Kaposi, não especificado', 'C46.9 Sarcoma de Kaposi NE'),
  ('C47', 'Neoplasia maligna dos nervos periféricos e do sistema nervoso autônomo', 'C47 Neopl malig nervos perif e sist nerv autonom'),
  ('C470', 'Neoplasia maligna dos nervos periféricos da cabeça, face e pescoço', 'C47.0 Nervos perifericos da cabeca face e pescoco'),
  ('C471', 'Neoplasia maligna dos nervos periféricos dos membros superiores, incluindo ombro', 'C47.1 Nervos perifericos membros super incl ombro'),
  ('C472', 'Neoplasia maligna dos nervos periféricos dos membros inferiores, incluindo quadril', 'C47.2 Nervos periferic membros infer incl quadril'),
  ('C473', 'Neoplasia maligna dos nervos periféricos do tórax', 'C47.3 Nervos perifericos do torax'),
  ('C474', 'Neoplasia maligna dos nervos periféricos do abdome', 'C47.4 Nervos perifericos do abdome'),
  ('C475', 'Neoplasia maligna dos nervos periféricos da pelve', 'C47.5 Nervos perifericos da pelve'),
  ('C476', 'Neoplasia maligna dos nervos periféricos do tronco', 'C47.6 Nervos perifericos do tronco'),
  ('C478', 'Neoplasia maligna dos nervos periféricos e do sistema nervoso autônomo com lesão invasiva', 'C47.8 Lesao invasiva nervos perif e sist nerv auto'),
  ('C479', 'Neoplasia maligna dos nervos periféricos e sistema nervoso autônomo, não especificados', 'C47.9 Nervos perifericos e sist nerv autonomo NE'),
  ('C48', 'Neoplasia maligna dos tecidos moles do retroperitônio e do peritônio', 'C48 Neopl malig tec moles retro- e peritonio'),
  ('C480', 'Neoplasia maligna do retroperitônio', 'C48.0 Retroperitonio'),
  ('C481', 'Neoplasia maligna de partes especificadas do peritônio', 'C48.1 Partes espec do peritonio'),
  ('C482', 'Neoplasia maligna do peritônio', 'C48.2 Peritonio'),
  ('C488', 'Neoplasia maligna dos tecidos moles do retroperitônio e do peritônio com lesão invasiva', 'C48.8 Lesao invasiva tec moles retro- e peritonio'),
  ('C49', 'Neoplasia maligna do tecido conjuntivo e de outros tecidos moles', 'C49 Neopl malig tec conjuntivo e outr tec moles'),
  ('C490', 'Neoplasia maligna do tecido conjuntivo e tecidos moles da cabeça, face e pescoço', 'C49.0 Tec conjuntivo e moles cabeca face e pescoco'),
  ('C491', 'Neoplasia maligna do tecido conjuntivo e tecidos moles dos membros superiores, incluindo ombro', 'C49.1 Tec conjuntivo e moles membr sup incl ombro'),
  ('C492', 'Neoplasia maligna do tecido conjuntivo e tecidos moles dos membros inferiores, incluindo quadril', 'C49.2 Tec conjuntivo e moles membr inf incl quadr'),
  ('C493', 'Neoplasia maligna do tecido conjuntivo e tecidos moles do tórax', 'C49.3 Tec conjuntivo e tec moles do torax'),
  ('C494', 'Neoplasia maligna do tecido conjuntivo e tecidos moles do abdome', 'C49.4 Tec conjuntivo e tec moles do abdome'),
  ('C495', 'Neoplasia maligna do tecido conjuntivo e tecidos moles da pelve', 'C49.5 Tec conjuntivo e tec moles da pelve'),
  ('C496', 'Neoplasia maligna do tecido conjuntivo e tecidos moles do tronco', 'C49.6 Tec conjuntivo e tec moles do tronco'),
  ('C498', 'Neoplasia maligna do tecido conjuntivo e dos tecidos moles com lesão invasiva', 'C49.8 Lesao invasiva tec conjuntivo e tec moles'),
  ('C499', 'Neoplasia maligna do tecido conjuntivo e tecidos moles, não especificados', 'C49.9 Neopl malig tec conjuntivo e tec moles NE'),
  ('C50', 'Neoplasia maligna da mama', 'C50 Neopl malig da mama'),
  ('C500', 'Neoplasia maligna do mamilo e aréola', 'C50.0 Mamilo e areola'),
  ('C501', 'Neoplasia maligna da porção central da mama', 'C50.1 Porcao central da mama'),
  ('C502', 'Neoplasia maligna do quadrante superior interno da mama', 'C50.2 Quadrante super interno da mama'),
  ('C503', 'Neoplasia maligna do quadrante inferior interno da mama', 'C50.3 Quadrante infer interno da mama'),
  ('C504', 'Neoplasia maligna do quadrante superior externo da mama', 'C50.4 Quadrante super externo da mama'),
  ('C505', 'Neoplasia maligna do quadrante inferior externo da mama', 'C50.5 Quadrante infer externo da mama'),
  ('C506', 'Neoplasia maligna da porção axilar da mama', 'C50.6 Porcao axilar da mama'),
  ('C508', 'Neoplasia maligna da mama com lesão invasiva', 'C50.8 Lesao invasiva da mama'),
  ('C509', 'Neoplasia maligna da mama, não especificada', 'C50.9 Mama NE'),
  ('C51', 'Neoplasia maligna da vulva', 'C51 Neopl malig da vulva'),
  ('C510', 'Neoplasia maligna dos grandes lábios', 'C51.0 Grandes labios'),
  ('C511', 'Neoplasia maligna dos pequenos lábios', 'C51.1 Pequenos labios'),
  ('C512', 'Neoplasia maligna do clitóris', 'C51.2 Clitoris'),
  ('C518', 'Neoplasia maligna da vulva com lesão invasiva', 'C51.8 Lesao invasiva da vulva'),
  ('C519', 'Neoplasia maligna da vulva, não especificada', 'C51.9 Vulva NE'),
  ('C52', 'Neoplasia maligna da vagina', 'C52 Neopl malig da vagina'),
  ('C52', 'Neoplasia maligna da vagina', 'C52 Neopl malig da vagina'),
  ('C53', 'Neoplasia maligna do colo do útero', 'C53 Neopl malig do colo do utero'),
  ('C530', 'Neoplasia maligna do endocérvix', 'C53.0 Endocervix'),
  ('C531', 'Neoplasia maligna do exocérvix', 'C53.1 Exocervix'),
  ('C538', 'Neoplasia maligna do colo do útero com lesão invasiva', 'C53.8 Lesao invasiva do colo do utero'),
  ('C539', 'Neoplasia maligna do colo do útero, não especificado', 'C53.9 Colo do utero NE'),
  ('C54', 'Neoplasia maligna do corpo do útero', 'C54 Neopl malig do corpo do utero'),
  ('C540', 'Neoplasia maligna do istmo do útero', 'C54.0 Istmo do utero'),
  ('C541', 'Neoplasia maligna do endométrio', 'C54.1 Endometrio'),
  ('C542', 'Neoplasia maligna do miométrio', 'C54.2 Miometrio'),
  ('C543', 'Neoplasia maligna do fundo do útero', 'C54.3 Fundo do utero'),
  ('C548', 'Neoplasia maligna do corpo do útero com lesão invasiva', 'C54.8 Lesao invasiva do corpo do utero'),
  ('C549', 'Neoplasia maligna do corpo do útero, não especificado', 'C54.9 Corpo do utero NE'),
  ('C55', 'Neoplasia maligna do útero, porção não especificada', 'C55 Neopl malig do utero porcao NE'),
  ('C55', 'Neoplasia maligna do útero, porção não especificada', 'C55 Neopl malig do utero porcao NE'),
  ('C56', 'Neoplasia maligna do ovário', 'C56 Neopl malig do ovario'),
  ('C56', 'Neoplasia maligna do ovário', 'C56 Neopl malig do ovario'),
  ('C57', 'Neoplasia maligna de outros órgãos genitais femininos e dos não especificados', 'C57 Neopl malig outr org genitais femin e NE'),
  ('C570', 'Neoplasia maligna da trompa de Falópio', 'C57.0 Trompa de Falopio'),
  ('C571', 'Neoplasia maligna do ligamento largo', 'C57.1 Ligamento largo'),
  ('C572', 'Neoplasia maligna do ligamento redondo', 'C57.2 Ligamento redondo'),
  ('C573', 'Neoplasia maligna do paramétrio', 'C57.3 Parametrio'),
  ('C574', 'Neoplasia maligna dos anexos uterinos', 'C57.4 Anexos uterinos'),
  ('C577', 'Neoplasia maligna de outras partes especificadas dos órgãos genitais femininos', 'C57.7 Outr partes espec orgaos genitais femin'),
  ('C578', 'Neoplasia maligna dos órgãos genitais femininos com lesão invasiva', 'C57.8 Lesao invasiva dos orgaos genitais femin'),
  ('C579', 'Neoplasia maligna de órgão genital feminino, não especificado', 'C57.9 Orgao genital femin NE'),
  ('C58', 'Neoplasia maligna da placenta', 'C58 Neopl malig da placenta'),
  ('C58', 'Neoplasia maligna da placenta', 'C58 Neopl malig da placenta'),
  ('C60', 'Neoplasia maligna do pênis', 'C60 Neopl malig do penis'),
  ('C600', 'Neoplasia maligna do prepúcio', 'C60.0 Prepucio'),
  ('C601', 'Neoplasia maligna da glande', 'C60.1 Glande'),
  ('C602', 'Neoplasia maligna do corpo do pênis', 'C60.2 Corpo do penis'),
  ('C608', 'Neoplasia maligna do pênis com lesão invasiva', 'C60.8 Lesao invasiva do penis'),
  ('C609', 'Neoplasia maligna do pênis, não especificado', 'C60.9 Penis NE'),
  ('C61', 'Neoplasia maligna da próstata', 'C61 Neopl malig da prostata'),
  ('C61', 'Neoplasia maligna da próstata', 'C61 Neopl malig da prostata'),
  ('C62', 'Neoplasia maligna dos testículos', 'C62 Neopl malig dos testiculos'),
  ('C620', 'Neoplasia maligna do testículo criptorquídico', 'C62.0 Testiculo criptorquidico'),
  ('C621', 'Neoplasia maligna do testículo tópico', 'C62.1 Testiculo topico'),
  ('C629', 'Neoplasia maligna do testículo, sem outras especificações', 'C62.9 Testiculo SOE'),
  ('C63', 'Neoplasia maligna de outros órgãos genitais masculinos e dos não especificados', 'C63 Neopl malig outr org genit masc e NE'),
  ('C630', 'Neoplasia maligna do epidídimo', 'C63.0 Epididimo'),
  ('C631', 'Neoplasia maligna do cordão espermático', 'C63.1 Cordao espermatico'),
  ('C632', 'Neoplasia maligna do escroto', 'C63.2 Escroto'),
  ('C637', 'Neoplasia maligna de outros órgãos genitais masculinos especificados', 'C63.7 Outr orgaos genitais masc espec'),
  ('C638', 'Neoplasia maligna dos órgãos genitais masculinos com lesão invasiva', 'C63.8 Lesao invasiva orgaos genitais masc'),
  ('C639', 'Neoplasia maligna de órgão genital masculino, não especificado', 'C63.9 Orgao genital masc NE'),
  ('C64', 'Neoplasia maligna do rim, exceto pelve renal', 'C64 Neopl malig do rim exceto pelve renal'),
  ('C64', 'Neoplasia maligna do rim, exceto pelve renal', 'C64 Neopl malig do rim exceto pelve renal'),
  ('C65', 'Neoplasia maligna da pelve renal', 'C65 Neopl malig da pelve renal'),
  ('C65', 'Neoplasia maligna da pelve renal', 'C65 Neopl malig da pelve renal'),
  ('C66', 'Neoplasia maligna dos ureteres', 'C66 Neopl malig dos ureteres'),
  ('C66', 'Neoplasia maligna dos ureteres', 'C66 Neopl malig dos ureteres'),
  ('C67', 'Neoplasia maligna da bexiga', 'C67 Neopl malig da bexiga'),
  ('C670', 'Neoplasia maligna do trígono da bexiga', 'C67.0 Trigono da bexiga'),
  ('C671', 'Neoplasia maligna da cúpula da bexiga', 'C67.1 Cupula da bexiga'),
  ('C672', 'Neoplasia maligna da parede lateral da bexiga', 'C67.2 Parede lateral da bexiga'),
  ('C673', 'Neoplasia maligna da parede anterior da bexiga', 'C67.3 Parede anterior da bexiga'),
  ('C674', 'Neoplasia maligna da parede posterior da bexiga', 'C67.4 Parede posterior da bexiga'),
  ('C675', 'Neoplasia maligna do colo da bexiga', 'C67.5 Colo da bexiga'),
  ('C676', 'Neoplasia maligna do orifício uretérico', 'C67.6 Orificio ureterico'),
  ('C677', 'Neoplasia maligna do úraco', 'C67.7 Uraco'),
  ('C678', 'Neoplasia maligna da bexiga com lesão invasiva', 'C67.8 Lesao invasiva da bexiga'),
  ('C679', 'Neoplasia maligna da bexiga, sem outra especificações', 'C67.9 Bexiga SOE'),
  ('C68', 'Neoplasia maligna de outros órgãos urinários e dos não especificados', 'C68 Neopl malig de outr orgaos urinarios e NE'),
  ('C680', 'Neoplasia maligna da uretra', 'C68.0 Uretra'),
  ('C681', 'Neoplasia maligna da glândula parauretral', 'C68.1 Gland parauretral'),
  ('C688', 'Neoplasia maligna dos órgãos urinários com lesão invasiva', 'C68.8 Lesao invasiva dos orgaos urinarios'),
  ('C689', 'Neoplasia maligna de órgão urinário, não especificado', 'C68.9 Orgao urinario NE'),
  ('C69', 'Neoplasia maligna do olho e anexos', 'C69 Neopl malig do olho e anexos'),
  ('C690', 'Neoplasia maligna da conjuntiva', 'C69.0 Conjuntiva'),
  ('C691', 'Neoplasia maligna da córnea', 'C69.1 Cornea'),
  ('C692', 'Neoplasia maligna da retina', 'C69.2 Retina'),
  ('C693', 'Neoplasia maligna da coróide', 'C69.3 Coroide'),
  ('C694', 'Neoplasia maligna do corpo ciliar', 'C69.4 Corpo ciliar'),
  ('C695', 'Neoplasia maligna da glândula e canal lacrimal', 'C69.5 Gland e canal lacrimal'),
  ('C696', 'Neoplasia maligna da órbita', 'C69.6 Orbita'),
  ('C698', 'Neoplasia maligna do olho e anexos com lesão invasiva', 'C69.8 Lesao invasiva do olho e anexos'),
  ('C699', 'Neoplasia maligna do olho, não especificado', 'C69.9 Olho NE'),
  ('C70', 'Neoplasia maligna das meninges', 'C70 Neopl malig das meninges'),
  ('C700', 'Neoplasia maligna das meninges cerebrais', 'C70.0 Meninges cerebrais'),
  ('C701', 'Neoplasia maligna das meninges espinhais', 'C70.1 Meninges espinhais'),
  ('C709', 'Neoplasia maligna da meninge, não especificada', 'C70.9 Meninge NE'),
  ('C71', 'Neoplasia maligna do encéfalo', 'C71 Neopl malig do encefalo'),
  ('C710', 'Neoplasia maligna do cérebro, exceto lobos e ventrículos', 'C71.0 Cerebro exceto lobos e ventriculos'),
  ('C711', 'Neoplasia maligna do lobo frontal', 'C71.1 Lobo frontal'),
  ('C712', 'Neoplasia maligna do lobo temporal', 'C71.2 Lobo temporal'),
  ('C713', 'Neoplasia maligna do lobo parietal', 'C71.3 Lobo parietal'),
  ('C714', 'Neoplasia maligna do lobo occipital', 'C71.4 Lobo occipital'),
  ('C715', 'Neoplasia maligna do ventrículo cerebral', 'C71.5 Ventriculo cerebral'),
  ('C716', 'Neoplasia maligna do cerebelo', 'C71.6 Cerebelo'),
  ('C717', 'Neoplasia maligna do tronco cerebral', 'C71.7 Tronco cerebral'),
  ('C718', 'Neoplasia maligna do encéfalo com lesão invasiva', 'C71.8 Lesao invasiva do encefalo'),
  ('C719', 'Neoplasia maligna do encéfalo, não especificado', 'C71.9 Encefalo NE'),
  ('C72', 'Neoplasia maligna da medula espinhal, dos nervos cranianos e de outras partes do sistema nervoso central', 'C72 Neop mal med esp nerv cran out sist nerv cen'),
  ('C720', 'Neoplasia maligna da medula espinhal', 'C72.0 Medula espinhal'),
  ('C721', 'Neoplasia maligna da cauda eqüina', 'C72.1 Cauda equina'),
  ('C722', 'Neoplasia maligna do nervo olfativo', 'C72.2 Nervo olfativo'),
  ('C723', 'Neoplasia maligna do nervo óptico', 'C72.3 Nervo optico'),
  ('C724', 'Neoplasia maligna do nervo acústico', 'C72.4 Nervo acustico'),
  ('C725', 'Neoplasia maligna de outros nervos cranianos e os não especificados', 'C72.5 Outr nervos cranianos e os NE'),
  ('C728', 'Neoplasia maligna do encéfalo e de outras partes do sistema nervoso central com lesão invasiva', 'C72.8 Lesao invasiva encef out part sist nerv cent'),
  ('C729', 'Neoplasia maligna do sistema nervoso central, não especificado', 'C72.9 Sist nervoso central NE'),
  ('C73', 'Neoplasia maligna da glândula tireóide', 'C73 Neopl malig da gland tireoide'),
  ('C73', 'Neoplasia maligna da glândula tireóide', 'C73 Neopl malig da gland tireoide'),
  ('C74', 'Neoplasia maligna da glândula supra-renal (Glândula adrenal)', 'C74 Neopl malig da gland supra-renal'),
  ('C740', 'Neoplasia maligna do córtex da supra-renal', 'C74.0 Cortex da supra-renal'),
  ('C741', 'Neoplasia maligna da medula da supra-renal', 'C74.1 Medula da supra-renal'),
  ('C749', 'Neoplasia maligna da glândula supra-renal, não especificada', 'C74.9 Gland supra-renal NE'),
  ('C75', 'Neoplasia maligna de outras glândulas endócrinas e de estruturas relacionadas', 'C75 Neopl malig outr gland endocrinas estr relac'),
  ('C750', 'Neoplasia maligna da glândula paratireóide', 'C75.0 Gland paratireoide'),
  ('C751', 'Neoplasia maligna da glândula hipófise (pituitária)', 'C75.1 Gland hipofise'),
  ('C752', 'Neoplasia maligna do conduto craniofaríngeo', 'C75.2 Conduto craniofaringeo'),
  ('C753', 'Neoplasia maligna da glândula pineal', 'C75.3 Gland pineal'),
  ('C754', 'Neoplasia maligna do corpo carotídeo', 'C75.4 Corpo carotideo'),
  ('C755', 'Neoplasia maligna do corpo aórtico e outros paragânglios', 'C75.5 Corpo aortico e outr paraganglios'),
  ('C758', 'Neoplasia maligna com comprometimento pluriglandular, sem outra especificação', 'C75.8 Compr pluriglandular SOE'),
  ('C759', 'Neoplasia maligna de glândula endócrina, não especificada', 'C75.9 Gland endocrina NE'),
  ('C76', 'Neoplasia maligna de outras localizações e de localizações mal definidas', 'C76 Neopl malig outr localiz e mal definidas'),
  ('C760', 'Neoplasia maligna da cabeça, face e pescoço', 'C76.0 Cabeca face e pescoco'),
  ('C761', 'Neoplasia maligna do tórax', 'C76.1 Torax'),
  ('C762', 'Neoplasia maligna do abdome', 'C76.2 Abdome'),
  ('C763', 'Neoplasia maligna da pelve', 'C76.3 Pelve'),
  ('C764', 'Neoplasia maligna do membro superior', 'C76.4 Membro super'),
  ('C765', 'Neoplasia maligna do membro inferior', 'C76.5 Membro infer'),
  ('C767', 'Neoplasia maligna de outras localizações mal definidas', 'C76.7 Outr localiz mal definidas'),
  ('C768', 'Neoplasia maligna de outras localizações e das mal definidas com lesão invasiva', 'C76.8 Lesao invasiva outr localiz e mal definidas'),
  ('C77', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos', 'C77 Neopl malig secund e NE gangl linfaticos'),
  ('C770', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos da cabeça, face e pescoço', 'C77.0 Ganglios linfaticos da cabeca face e pescoco'),
  ('C771', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos intratorácicos', 'C77.1 Ganglios linfaticos intratoracicos'),
  ('C772', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos intra-abdominais', 'C77.2 Ganglios linfaticos intra-abdominais'),
  ('C773', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos axilares e dos membros superiores', 'C77.3 Ganglios linfaticos axilares e membros super'),
  ('C774', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos inguinais e dos membros inferiores', 'C77.4 Ganglios linfaticos inguinais e membr infer'),
  ('C775', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos intrapélvicos', 'C77.5 Ganglios linfaticos intrapelvicos'),
  ('C778', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos de múltiplas regiões', 'C77.8 Ganglios linfaticos de mult regioes'),
  ('C779', 'Neoplasia maligna secundária e não especificada de gânglio linfático, não especificado', 'C77.9 Ganglio linfatico NE'),
  ('C78', 'Neoplasia maligna secundária dos órgãos respiratórios e digestivos', 'C78 Neopl malig secund org respirat e digestivos'),
  ('C780', 'Neoplasia maligna secundária dos pulmões', 'C78.0 Neopl malig secund dos pulmoes'),
  ('C781', 'Neoplasia maligna secundária do mediastino', 'C78.1 Neopl malig secund do mediastino'),
  ('C782', 'Neoplasia maligna secundária da pleura', 'C78.2 Neopl malig secund da pleura'),
  ('C783', 'Neoplasia maligna secundária de outros órgãos respiratórios e não especificados', 'C78.3 Neopl malig secund outr orgaos respirat e NE'),
  ('C784', 'Neoplasia maligna secundária do intestino delgado', 'C78.4 Neopl malig secund do intestino delgado'),
  ('C785', 'Neoplasia maligna secundária do intestino grosso e do reto', 'C78.5 Neopl malig secund intestino grosso e reto'),
  ('C786', 'Neoplasia maligna secundária do retroperitônio e do peritônio', 'C78.6 Neopl malig secund retro- e peritonio'),
  ('C787', 'Neoplasia maligna secundária do fígado', 'C78.7 Neopl malig secund do figado'),
  ('C788', 'Neoplasia maligna secundária de outros órgãos digestivos e não especificados', 'C78.8 Neopl malig secund outr org digestivos e NE'),
  ('C79', 'Neoplasia maligna secundária de outras localizações', 'C79 Neopl malig secund de outr localiz'),
  ('C790', 'Neoplasia maligna secundária do rim e da pelve renal', 'C79.0 Neopl malig secund do rim e da pelve renal'),
  ('C791', 'Neoplasia maligna secundária da bexiga, de outro órgão urinário e não especificado', 'C79.1 Neopl malig secund bexiga outr org urin e NE'),
  ('C792', 'Neoplasia maligna secundária da pele', 'C79.2 Neopl malig secund da pele'),
  ('C793', 'Neoplasia maligna secundária do encéfalo e das meninges cerebrais', 'C79.3 Neopl malig secund encefalo e mening cerebr'),
  ('C794', 'Neoplasia maligna secundária de outras partes do sistema nervoso e não especificadas', 'C79.4 Neopl malig secund outr part sist nerv e NE'),
  ('C795', 'Neoplasia maligna secundária dos ossos e da medula óssea', 'C79.5 Neopl malig secund ossos e medula ossea'),
  ('C796', 'Neoplasia maligna secundária do ovário', 'C79.6 Neopl malig secund do ovario'),
  ('C797', 'Neoplasia maligna secundária das glândulas supra-renais (adrenais)', 'C79.7 Neopl malig secund das gland supra-renais'),
  ('C798', 'Neoplasia maligna secundária de outra localização especificada', 'C79.8 Neopl malig secund de outr localiz espec'),
  ('C80', 'Neoplasia maligna, sem especificação de localização', 'C80 Neopl malig s/especificacao de localiz'),
  ('C80', 'Neoplasia maligna, sem especificação de localização', 'C80 Neopl malig s/especificacao de localiz'),
  ('C81', 'Doença de Hodgkin', 'C81 Doenc de Hodgkin'),
  ('C810', 'Doença de Hodgkin, predominância linfocítica', 'C81.0 Predom linfocitica'),
  ('C811', 'Doença de Hodgkin, esclerose nodular', 'C81.1 Esclerose nodular'),
  ('C812', 'Doença de Hodgkin, celularidade mista', 'C81.2 Celularidade mista'),
  ('C813', 'Doença de Hodgkin, depleção linfocítica', 'C81.3 Deplecao linfocitica'),
  ('C817', 'Outra forma da doença de Hodgkin', 'C81.7 Outr form da doenc de Hodgkin'),
  ('C819', 'Doença de Hodgkin, não especificada', 'C81.9 Doenc de Hodgkin NE'),
  ('C82', 'Linfoma não-Hodgkin, folicular (nodular)', 'C82 Linfoma nao-Hodgkin folicular'),
  ('C820', 'Linfoma não-Hodgkin, pequenas células clivadas, folicular', 'C82.0 Pequenas celulas clivadas folicular'),
  ('C821', 'Linfoma não-Hodgkin, misto, de pequenas e grandes células clivadas, folicular', 'C82.1 Misto peq/grandes celulas clivadas folicular'),
  ('C822', 'Linfoma não-Hodgkin, grandes células, folicular', 'C82.2 Grandes celulas folicular'),
  ('C827', 'Outros tipos de linfoma não-Hodgkin, folicular', 'C82.7 Outr tipos de linfoma nao-Hodgkin folicular'),
  ('C829', 'Linfoma não-Hodgkin, folicular, não especificado', 'C82.9 Linfoma nao-Hodgkin folicular NE'),
  ('C83', 'Linfoma não-Hodgkin difuso', 'C83 Linfoma nao-Hodgkin difuso'),
  ('C830', 'Linfoma não-Hodgkin difuso, pequenas células (difuso)', 'C83.0 Pequenas celulas'),
  ('C831', 'Linfoma não-Hodgkin difuso, pequenas células clivadas (difuso)', 'C83.1 Pequenas celulas clivadas'),
  ('C832', 'Linfoma não-Hodgkin difuso, misto, de pequenas e grandes células (difuso)', 'C83.2 Misto de pequenas e grandes celulas'),
  ('C833', 'Linfoma não-Hodgkin difuso, grandes células (difuso)', 'C83.3 Grandes celulas'),
  ('C834', 'Linfoma não-Hodgkin difuso, imunoblástico (difuso)', 'C83.4 Imunoblastico'),
  ('C835', 'Linfoma não-Hodgkin difuso, linfoblástico (difuso)', 'C83.5 Linfoblastico'),
  ('C836', 'Linfoma não-Hodgkin difuso, indiferenciado (difuso)', 'C83.6 Indiferenciado'),
  ('C837', 'Tumor de Burkitt', 'C83.7 Tumor de Burkitt'),
  ('C838', 'Outros tipos de linfoma não-Hodgkin difuso', 'C83.8 Outr tipos de linfoma nao-Hodgkin difuso'),
  ('C839', 'Linfoma não-Hodgkin difuso, não especificado', 'C83.9 Linfoma nao-Hodgkin difuso NE'),
  ('C84', 'Linfomas de células T cutâneas e periféricas', 'C84 Linfomas de celulas T cutaneas e perifericas'),
  ('C840', 'Micose fungóide', 'C84.0 Micose fungoide'),
  ('C841', 'Doença de Sézary', 'C84.1 Doenc de Sezary'),
  ('C842', 'Linfoma da zona T', 'C84.2 Linfoma da zona T'),
  ('C843', 'Linfoma linfoepitelióide', 'C84.3 Linfoma linfoepitelioide'),
  ('C844', 'Linfoma de células T, periférico', 'C84.4 Linfoma de celulas T periferico'),
  ('C845', 'Outros linfomas de células T e os não especificados', 'C84.5 Outr linfomas de celulas T e os NE'),
  ('C85', 'Linfoma não-Hodgkin de outros tipos e de tipo não especificado', 'C85 Linfoma nao-Hodgkin de outr tipos e tipo NE'),
  ('C850', 'Linfossarcoma', 'C85.0 Linfossarcoma'),
  ('C851', 'Linfoma de células B, não especificado', 'C85.1 Linfoma de celulas B NE'),
  ('C857', 'Outros tipos especificados de linfoma não-Hodgkin', 'C85.7 Outr tipos espec de linfoma nao-Hodgkin'),
  ('C859', 'Linfoma não-Hodgkin de tipo não especificado', 'C85.9 Linfoma nao-Hodgkin de tipo NE'),
  ('C88', 'Doenças imunoproliferativas malignas', 'C88 Doenc imunoproliferativas malignas'),
  ('C880', 'Macroglobulinemia de Waldenström', 'C88.0 Macroglobulinemia de Waldenstrom'),
  ('C881', 'Doença de cadeia pesada alfa', 'C88.1 Doenc de cadeia pesada alfa'),
  ('C882', 'Doença de cadeia pesada gama', 'C88.2 Doenc de cadeia pesada gama'),
  ('C883', 'Doença imunoproliferativa do intestino delgado', 'C88.3 Doenc imunoproliferativa intestino delgado'),
  ('C887', 'Outras doenças imunoproliferativas malignas', 'C88.7 Outr doenc imunoproliferativas malignas'),
  ('C889', 'Doença imunoproliferativa maligna, não especificada', 'C88.9 Doenc imunoproliferativa maligna NE'),
  ('C90', 'Mieloma múltiplo e neoplasias malignas de plasmócitos', 'C90 Mieloma mult e neopl malig de plasmocitos'),
  ('C900', 'Mieloma múltiplo', 'C90.0 Mieloma mult'),
  ('C901', 'Leucemia plasmocitária', 'C90.1 Leucemia plasmocitaria'),
  ('C902', 'Plasmocitoma extramedular', 'C90.2 Plasmocitoma extramedular'),
  ('C91', 'Leucemia linfóide', 'C91 Leucemia linfoide'),
  ('C910', 'Leucemia linfoblástica aguda', 'C91.0 Leucemia linfoblastica aguda'),
  ('C911', 'Leucemia linfocítica crônica', 'C91.1 Leucemia linfocitica cronica'),
  ('C912', 'Leucemia linfocítica subaguda', 'C91.2 Leucemia linfocitica subaguda'),
  ('C913', 'Leucemia pró-linfocítica', 'C91.3 Leucemia pro-linfocitica'),
  ('C914', 'Leucemia de células pilosas', 'C91.4 Leucemia de celulas pilosas'),
  ('C915', 'Leucemia de células T do adulto', 'C91.5 Leucemia de celulas T do adulto'),
  ('C917', 'Outras leucemias linfóides', 'C91.7 Outr leucemias linfoides'),
  ('C919', 'Leucemia linfóide, não especificada', 'C91.9 Leucemia linfoide NE'),
  ('C92', 'Leucemia mielóide', 'C92 Leucemia mieloide'),
  ('C920', 'Leucemia mielóide aguda', 'C92.0 Leucemia mieloide aguda'),
  ('C921', 'Leucemia mielóide crônica', 'C92.1 Leucemia mieloide cronica'),
  ('C922', 'Leucemia mielóide subaguda', 'C92.2 Leucemia mieloide subaguda'),
  ('C923', 'Sarcoma mielóide', 'C92.3 Sarcoma mieloide'),
  ('C924', 'Leucemia pró-mielocítica aguda', 'C92.4 Leucemia pro-mielocitica aguda'),
  ('C925', 'Leucemia mielomonocítica aguda', 'C92.5 Leucemia mielomonocitica aguda'),
  ('C927', 'Outras leucemias mielóides', 'C92.7 Outr leucemias mieloides'),
  ('C929', 'Leucemia mielóide, não especificada', 'C92.9 Leucemia mieloide NE'),
  ('C93', 'Leucemia monocítica', 'C93 Leucemia monocitica'),
  ('C930', 'Leucemia monocítica aguda', 'C93.0 Leucemia monocitica aguda'),
  ('C931', 'Leucemia monocítica crônica', 'C93.1 Leucemia monocitica cronica'),
  ('C932', 'Leucemia monocítica subaguda', 'C93.2 Leucemia monocitica subaguda'),
  ('C937', 'Outras leucemias monocíticas', 'C93.7 Outr leucemias monociticas'),
  ('C939', 'Leucemia monocítica, não especificada', 'C93.9 Leucemia monocitica NE'),
  ('C94', 'Outras leucemias de células de tipo especificado', 'C94 Outr leucemias de celulas de tipo espec'),
  ('C940', 'Eritremia e eritroleucemia agudas', 'C94.0 Eritremia e eritroleucemia agudas'),
  ('C941', 'Eritremia crônica', 'C94.1 Eritremia cronica'),
  ('C942', 'Leucemia megacarioblástica aguda', 'C94.2 Leucemia megacarioblastica aguda'),
  ('C943', 'Leucemia de mastócitos', 'C94.3 Leucemia de mastocitos'),
  ('C944', 'Panmielose aguda', 'C94.4 Panmielose aguda'),
  ('C945', 'Mielofibrose aguda', 'C94.5 Mielofibrose aguda'),
  ('C947', 'Outras leucemias especificadas', 'C94.7 Outr leucemias espec'),
  ('C95', 'Leucemia de tipo celular não especificado', 'C95 Leucemia de tipo celular NE'),
  ('C950', 'Leucemia aguda de tipo celular não especificado', 'C95.0 Leucemia aguda de tipo celular NE'),
  ('C951', 'Leucemia crônica de tipo celular não especificado', 'C95.1 Leucemia cronica de tipo celular NE'),
  ('C952', 'Leucemia subaguda de tipo celular não especificado', 'C95.2 Leucemia subaguda de tipo celular NE'),
  ('C957', 'Outras leucemias de tipo celular não especificado', 'C95.7 Outr leucemias de tipo celular NE'),
  ('C959', 'Leucemia não especificada', 'C95.9 Leucemia NE'),
  ('C96', 'Outras neoplasias malignas e as não especificadas dos tecidos linfático, hematopoético e tecidos correlatos', 'C96 Outr neopl mal e NE tec linf hematop e corr'),
  ('C960', 'Doença de Letterer-Siwe', 'C96.0 Doenc de Letterer-Siwe'),
  ('C961', 'Histiocitose maligna', 'C96.1 Histiocitose maligna'),
  ('C962', 'Tumor maligno de mastócitos', 'C96.2 Tumor maligno de mastocitos'),
  ('C963', 'Linfoma histiocítico verdadeiro', 'C96.3 Linfoma histiocitico verdadeiro'),
  ('C967', 'Outras neoplasias malignas especificadas dos tecidos linfático, hematopoético e tecidos correlatos', 'C96.7 Outr neop mal espec tec linf hematop e corr'),
  ('C969', 'Neoplasia maligna dos tecidos linfático, hematopoético e tecidos correlatos, não especificada', 'C96.9 Neop mal tec linf hematop e corr NE'),
  ('C97', 'Neoplasias malignas de localizações múltiplas independentes (primárias)', 'C97 Neopl malig de localiz mult independentes'),
  ('C97', 'Neoplasias malignas de localizações múltiplas independentes (primárias)', 'C97 Neopl malig de localiz mult independentes');
