INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('N00', 'Síndrome nefrítica aguda', 'N00 Sindr nefritica aguda'),
  ('N000', 'Síndrome nefrítica aguda - anormalidade glomerular minor', 'N00.0 Anormalidade glomerular minor'),
  ('N001', 'Síndrome nefrítica aguda - lesões glomerulares focais e segmentares', 'N00.1 Lesoes glomerulares focais e segmentares'),
  ('N002', 'Síndrome nefrítica aguda - glomerulonefrite membranosa difusa', 'N00.2 Glomerulonefrite membranosa difusa'),
  ('N003', 'Síndrome nefrítica aguda - glomerulonefrite proliferativa mesangial difusa', 'N00.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N004', 'Síndrome nefrítica aguda - glomerulonefrite proliferativa endocapilar difusa', 'N00.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N005', 'Síndrome nefrítica aguda - glomerulonefrite mesangiocapilar difusa', 'N00.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N006', 'Síndrome nefrítica aguda - doença de depósito denso', 'N00.6 Doenc de deposito denso'),
  ('N007', 'Síndrome nefrítica aguda - glomerulonefrite difusa em crescente', 'N00.7 Glomerulonefrite difusa em crescente'),
  ('N008', 'Síndrome nefrítica aguda - outras', 'N00.8 Outr'),
  ('N009', 'Síndrome nefrítica aguda - não especificada', 'N00.9 NE'),
  ('N01', 'Síndrome nefrítica rapidamente progressiva', 'N01 Sindr nefritica rapidamente progressiva'),
  ('N010', 'Síndrome nefrítica rapidamente progressiva - anormalidade glomerular minor', 'N01.0 Anormalidade glomerular minor'),
  ('N011', 'Síndrome nefrítica rapidamente progressiva - lesões glomerulares focais e segmentares', 'N01.1 Lesoes glomerulares focais e segmentares'),
  ('N012', 'Síndrome nefrítica rapidamente progressiva - glomerulonefrite membranosa difusa', 'N01.2 Glomerulonefrite membranosa difusa'),
  ('N013', 'Síndrome nefrítica rapidamente progressiva - glomerulonefrite proliferativa mesangial difusa', 'N01.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N014', 'Síndrome nefrítica rapidamente progressiva - glomerulonefrite proliferativa endocapilar difusa', 'N01.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N015', 'Síndrome nefrítica rapidamente progressiva - glomerulonefrite mesangiocapilar difusa', 'N01.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N016', 'Síndrome nefrítica rapidamente progressiva - doença de depósito denso', 'N01.6 Doenc de deposito denso'),
  ('N017', 'Síndrome nefrítica rapidamente progressiva - glomerulonefrite difusa em crescente', 'N01.7 Glomerulonefrite difusa em crescente'),
  ('N018', 'Síndrome nefrítica rapidamente progressiva - outras', 'N01.8 Outr'),
  ('N019', 'Síndrome nefrítica rapidamente progressiva - não especificada', 'N01.9 NE'),
  ('N02', 'Hematúria recidivante e persistente', 'N02 Hematuria recidivante e persistente'),
  ('N020', 'Hematúria recidivante e persistente - anormalidade glomerular minor', 'N02.0 Anormalidade glomerular minor'),
  ('N021', 'Hematúria recidivante e persistente - lesões glomerulares focais e segmentares', 'N02.1 Lesoes glomerulares focais e segmentares'),
  ('N022', 'Hematúria recidivante e persistente - glomerulonefrite membranosa difusa', 'N02.2 Glomerulonefrite membranosa difusa'),
  ('N023', 'Hematúria recidivante e persistente - glomerulonefrite proliferativa mesangial difusa', 'N02.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N024', 'Hematúria recidivante e persistente - glomerulonefrite proliferativa endocapilar difusa', 'N02.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N025', 'Hematúria recidivante e persistente - glomerulonefrite mesangiocapilar difusa', 'N02.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N026', 'Hematúria recidivante e persistente - doença de depósito denso', 'N02.6 Doenc de deposito denso'),
  ('N027', 'Hematúria recidivante e persistente - glomerulonefrite difusa em crescente', 'N02.7 Glomerulonefrite difusa em crescente'),
  ('N028', 'Hematúria recidivante e persistente - outras', 'N02.8 Outr'),
  ('N029', 'Hematúria recidivante e persistente - não especificada', 'N02.9 NE'),
  ('N03', 'Síndrome nefrítica crônica', 'N03 Sindr nefritica cronica'),
  ('N030', 'Síndrome nefrítica crônica - anormalidade glomerular minor', 'N03.0 Anormalidade glomerular minor'),
  ('N031', 'Síndrome nefrítica crônica - lesões glomerulares focais e segmentares', 'N03.1 Lesoes glomerulares focais e segmentares'),
  ('N032', 'Síndrome nefrítica crônica - glomerulonefrite membranosa difusa', 'N03.2 Glomerulonefrite membranosa difusa'),
  ('N033', 'Síndrome nefrítica crônica - glomerulonefrite proliferativa mesangial difusa', 'N03.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N034', 'Síndrome nefrítica crônica - glomerulonefrite proliferativa endocapilar difusa', 'N03.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N035', 'Síndrome nefrítica crônica - glomerulonefrite mesangiocapilar difusa', 'N03.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N036', 'Síndrome nefrítica crônica - doença de depósito denso', 'N03.6 Doenc de deposito denso'),
  ('N037', 'Síndrome nefrítica crônica - glomerulonefrite difusa em crescente', 'N03.7 Glomerulonefrite difusa em crescente'),
  ('N038', 'Síndrome nefrítica crônica - outras', 'N03.8 Outr'),
  ('N039', 'Síndrome nefrítica crônica - não especificada', 'N03.9 NE'),
  ('N04', 'Síndrome nefrótica', 'N04 Sindr nefrotica'),
  ('N040', 'Síndrome nefrótica - anormalidade glomerular minor', 'N04.0 Anormalidade glomerular minor'),
  ('N041', 'Síndrome nefrótica - lesões glomerulares focais e segmentares', 'N04.1 Lesoes glomerulares focais e segmentares'),
  ('N042', 'Síndrome nefrótica - glomerulonefrite membranosa difusa', 'N04.2 Glomerulonefrite membranosa difusa'),
  ('N043', 'Síndrome nefrótica - glomerulonefrite proliferativa mesangial difusa', 'N04.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N044', 'Síndrome nefrótica - glomerulonefrite proliferativa endocapilar difusa', 'N04.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N045', 'Síndrome nefrótica - glomerulonefrite mesangiocapilar difusa', 'N04.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N046', 'Síndrome nefrótica - doença de depósito denso', 'N04.6 Doenc de deposito denso'),
  ('N047', 'Síndrome nefrótica - glomerulonefrite difusa em crescente', 'N04.7 Glomerulonefrite difusa em crescente'),
  ('N048', 'Síndrome nefrótica - outras', 'N04.8 Outr'),
  ('N049', 'Síndrome nefrótica - não especificada', 'N04.9 NE'),
  ('N05', 'Síndrome nefrítica não especificada', 'N05 Sindr nefritica NE'),
  ('N050', 'Síndrome nefrítica não especificada - anormalidade glomerular minor', 'N05.0 Anormalidade glomerular minor'),
  ('N051', 'Síndrome nefrítica não especificada - lesões glomerulares focais e segmentares', 'N05.1 Lesoes glomerulares focais e segmentares'),
  ('N052', 'Síndrome nefrítica não especificada - glomerulonefrite membranosa difusa', 'N05.2 Glomerulonefrite membranosa difusa'),
  ('N053', 'Síndrome nefrítica não especificada - glomerulonefrite proliferativa mesangial difusa', 'N05.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N054', 'Síndrome nefrítica não especificada - glomerulonefrite proliferativa endocapilar difusa', 'N05.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N055', 'Síndrome nefrítica não especificada - glomerulonefrite mesangiocapilar difusa', 'N05.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N056', 'Síndrome nefrítica não especificada - doença de depósito denso', 'N05.6 Doenc de deposito denso'),
  ('N057', 'Síndrome nefrítica não especificada - glomerulonefrite difusa em crescente', 'N05.7 Glomerulonefrite difusa em crescente'),
  ('N058', 'Síndrome nefrítica não especificada - outras', 'N05.8 Outr'),
  ('N059', 'Síndrome nefrítica não especificada - não especificada', 'N05.9 NE'),
  ('N06', 'Proteinúria isolada com lesão morfológica especificada', 'N06 Proteinuria isolada c/lesao morfolog espec'),
  ('N060', 'Proteinúria isolada com lesão morfológica especificada - anormalidade glomerular minor', 'N06.0 Anormalidade glomerular minor'),
  ('N061', 'Proteinúria isolada com lesão morfológica especificada - lesões glomerulares focais e segmentares', 'N06.1 Lesoes glomerulares focais e segmentares'),
  ('N062', 'Proteinúria isolada com lesão morfológica especificada - glomerulonefrite membranosa difusa', 'N06.2 Glomerulonefrite membranosa difusa'),
  ('N063', 'Proteinúria isolada com lesão morfológica especificada - glomerulonefrite proliferativa mesangial difusa', 'N06.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N064', 'Proteinúria isolada com lesão morfológica especificada - glomerulonefrite proliferativa endocapilar difusa', 'N06.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N065', 'Proteinúria isolada com lesão morfológica especificada - glomerulonefrite mesangiocapilar difusa', 'N06.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N066', 'Proteinúria isolada com lesão morfológica especificada - doença de depósito denso', 'N06.6 Doenc de deposito denso'),
  ('N067', 'Proteinúria isolada com lesão morfológica especificada - glomerulonefrite difusa em crescente', 'N06.7 Glomerulonefrite difusa em crescente'),
  ('N068', 'Proteinúria isolada com lesão morfológica especificada - outras', 'N06.8 Outr'),
  ('N069', 'Proteinúria isolada com lesão morfológica especificada - não especificada', 'N06.9 NE'),
  ('N07', 'Nefropatia hereditária não classificada em outra parte', 'N07 Nefropatia hereditaria NCOP'),
  ('N070', 'Nefropatia hereditária não classificada em outra parte - anormalidade glomerular minor', 'N07.0 Anormalidade glomerular minor'),
  ('N071', 'Nefropatia hereditária não classificada em outra parte - lesões glomerulares focais e segmentares', 'N07.1 Lesoes glomerulares focais e segmentares'),
  ('N072', 'Nefropatia hereditária não classificada em outra parte - glomerulonefrite membranosa difusa', 'N07.2 Glomerulonefrite membranosa difusa'),
  ('N073', 'Nefropatia hereditária não classificada em outra parte - glomerulonefrite proliferativa mesangial difusa', 'N07.3 Glomerulonefrite prolifer mesangial difusa'),
  ('N074', 'Nefropatia hereditária não classificada em outra parte - glomerulonefrite proliferativa endocapilar difusa', 'N07.4 Glomerulonefrite prolifer endocapilar difusa'),
  ('N075', 'Nefropatia hereditária não classificada em outra parte - glomerulonefrite mesangiocapilar difusa', 'N07.5 Glomerulonefrite mesangiocapilar difusa'),
  ('N076', 'Nefropatia hereditária não classificada em outra parte - doença de depósito denso', 'N07.6 Doenc de deposito denso'),
  ('N077', 'Nefropatia hereditária não classificada em outra parte - glomerulonefrite difusa em crescente', 'N07.7 Glomerulonefrite difusa em crescente'),
  ('N078', 'Nefropatia hereditária não classificada em outra parte - outras', 'N07.8 Outr'),
  ('N079', 'Nefropatia hereditária não classificada em outra parte - não especificada', 'N07.9 NE'),
  ('N08', 'Transtornos glomerulares em doenças classificadas em outra parte', 'N08 Transt glomerulares em doenc COP'),
  ('N080', 'Transtornos glomerulares em doenças infecciosas e parasitárias classificadas em outra parte', 'N08.0 Transt glomerulares doenc infecc parasit COP'),
  ('N081', 'Transtornos glomerulares em doenças neoplásicas', 'N08.1 Transt glomerulares em doenc neoplasicas'),
  ('N082', 'Transtornos glomerulares em doenças do sangue e transtornos imunitários', 'N08.2 Transt glomerulares doenc sangue transt imun'),
  ('N083', 'Transtornos glomerulares no diabetes mellitus', 'N08.3 Transt glomerulares no diabetes mellitus'),
  ('N084', 'Transtornos glomerulares em doenças endócrinas, nutricionais e metabólicas', 'N08.4 Transt glomerulares doenc endocr nutr metab'),
  ('N085', 'Transtornos glomerulares em doenças sistêmicas do tecido conjuntivo', 'N08.5 Transt glomerulares doenc sist tec conjunt'),
  ('N088', 'Transtornos glomerulares em outras doenças classificadas em outra parte', 'N08.8 Transt glomerulares em outr doenc COP'),
  ('N10', 'Nefrite túbulo-intersticial aguda', 'N10 Nefrite tubulo-intersticial aguda'),
  ('N10', 'Nefrite túbulo-intersticial aguda', 'N10 Nefrite tubulo-intersticial aguda'),
  ('N11', 'Nefrite túbulo-intersticial crônica', 'N11 Nefrite tubulo-intersticial cronica'),
  ('N110', 'Pielonefrite não-obstrutiva crônica associada a refluxo', 'N11.0 Pielonefrite nao-obstrut cron assoc refluxo'),
  ('N111', 'Pielonefrite obstrutiva crônica', 'N11.1 Pielonefrite obstrutiva cronica'),
  ('N118', 'Outras nefrites túbulo-intersticiais crônicas', 'N11.8 Outr nefrites tubulo-intersticiais cronicas'),
  ('N119', 'Nefrite túbulo-intersticial crônica não especificada', 'N11.9 Nefrite tubulo-intersticial cronica NE'),
  ('N12', 'Nefrite túbulo-intersticial não especificada se aguda ou crônica', 'N12 Nefrite tubulo-intersticial NE aguda cronica'),
  ('N12', 'Nefrite túbulo-intersticial não especificada se aguda ou crônica', 'N12 Nefrite tubulo-intersticial NE aguda cronica'),
  ('N13', 'Uropatia obstrutiva e por refluxo', 'N13 Uropatia obstrutiva e p/refluxo'),
  ('N130', 'Hidronefrose com obstrução da junção uretero-pélvica', 'N13.0 Hidronefrose c/obstr juncao uretero-pelvica'),
  ('N131', 'Hidronefrose com estreitamento de ureter não classificada em outra parte', 'N13.1 Hidronefrose c/estreitamento de ureter NCOP'),
  ('N132', 'Hidronefrose com obstrução por calculose renal e ureteral', 'N13.2 Hidronefr c/obstr p/calculose renal ureteral'),
  ('N133', 'Outras hidronefroses e as não especificadas', 'N13.3 Outr hidronefroses e as NE'),
  ('N134', 'Hidroureter', 'N13.4 Hidroureter'),
  ('N135', 'Torção e estreitamento do ureter sem hidronefrose', 'N13.5 Torcao e estreitamento ureter s/hidronefrose'),
  ('N136', 'Pionefrose', 'N13.6 Pionefrose'),
  ('N137', 'Uropatia associada a refluxo vésico-ureteral', 'N13.7 Uropatia assoc a refluxo vesico-ureteral'),
  ('N138', 'Outras uropatias obstrutivas e por refluxo', 'N13.8 Outr uropatias obstrutivas e p/refluxo'),
  ('N139', 'Uropatia obstrutiva e por refluxo não especificada', 'N13.9 Uropatia obstrutiva e p/refluxo NE'),
  ('N14', 'Afecções tubulares e túbulo-intersticiais induzidas por drogas ou metais pesados', 'N14 Afec tubul tubulo-interst ind drog met pesad'),
  ('N140', 'Nefropatia induzida por analgésico', 'N14.0 Nefropatia induz p/analgesico'),
  ('N141', 'Nefropatia induzida por outras drogas, medicamentos e substâncias biológicas', 'N14.1 Nefropatia induz out drog medic subst biolog'),
  ('N142', 'Nefropatia induzida por drogas, medicamentos e substâncias biológicas não especificadas', 'N14.2 Nefropatia induz drog medic subst biolog NE'),
  ('N143', 'Nefropatia induzida por metais pesados', 'N14.3 Nefropatia induz p/metais pesados'),
  ('N144', 'Nefropatia tóxica não classificada em outra parte', 'N14.4 Nefropatia toxica NCOP'),
  ('N15', 'Outras doenças renais túbulo-intersticiais', 'N15 Outr doenc renais tubulo-intersticiais'),
  ('N150', 'Nefropatia dos Bálcãs', 'N15.0 Nefropatia dos Balcas'),
  ('N151', 'Abscesso renal e perinefrético', 'N15.1 Abscesso renal e perinefretico'),
  ('N158', 'Outras doenças renais túbulo-intersticiais especificadas', 'N15.8 Outr doenc renais tubulo-intersticiais espec'),
  ('N159', 'Doença renal túbulo-intersticial não especificada', 'N15.9 Doenc renal tubulo-intersticial NE'),
  ('N16', 'Transtornos renais túbulo-intersticiais em doenças classificadas em outra parte', 'N16 Transt renais tubulo-intersticiais doenc COP'),
  ('N160', 'Transtornos renais túbulo-intersticiais em doenças infecciosas e parasitárias classificadas em outra parte', 'N16.0 Transt renais tub-interst doen inf paras COP'),
  ('N161', 'Transtornos renais túbulo-intersticiais em doenças neoplásicas', 'N16.1 Transt renais tubulo-interst doenc neoplas'),
  ('N162', 'Transtornos renais túbulo-intersticiais em doenças do sangue e transtornos imunitários', 'N16.2 Transt renais tub-inter doen sang trans imun'),
  ('N163', 'Transtornos renais túbulo-intersticiais em doenças metabólicas', 'N16.3 Transt renais tubulo-interst doenc metab'),
  ('N164', 'Transtornos renais túbulo-intersticiais em doenças do tecido conjuntivo', 'N16.4 Transt renais tubulo-interst doenc tec conj'),
  ('N165', 'Transtornos renais túbulo-intersticiais em rejeição a transplantes', 'N16.5 Transt renais tubulo-interst rej transpl'),
  ('N168', 'Transtornos renais túbulo-intersticiais em outras doenças classificadas em outra parte', 'N16.8 Transt renais tubulo-interst outr doenc COP'),
  ('N17', 'Insuficiência renal aguda', 'N17 Insuf renal aguda'),
  ('N170', 'Insuficiência renal aguda com necrose tubular', 'N17.0 Insuf renal aguda c/necrose tubular'),
  ('N171', 'Insuficiência renal aguda com necrose cortical aguda', 'N17.1 Insuf renal aguda c/necrose cortical aguda'),
  ('N172', 'Insuficiência renal aguda com necrose medular', 'N17.2 Insuf renal aguda c/necrose medular'),
  ('N178', 'Outro tipo de insuficiência renal aguda', 'N17.8 Outr tipo de insuf renal aguda'),
  ('N179', 'Insuficiência renal aguda não especificada', 'N17.9 Insuf renal aguda NE'),
  ('N18', 'Insuficiência renal crônica', 'N18 Insuf renal cronica'),
  ('N180', 'Doença renal em estádio final', 'N18.0 Doenc renal em estadio final'),
  ('N188', 'Outra insuficiência renal crônica', 'N18.8 Outr insuf renal cronica'),
  ('N189', 'Insuficiência renal crônica não especificada', 'N18.9 Insuf renal cronica NE'),
  ('N19', 'Insuficiência renal não especificada', 'N19 Insuf renal NE'),
  ('N19', 'Insuficiência renal não especificada', 'N19 Insuf renal NE'),
  ('N20', 'Calculose do rim e do ureter', 'N20 Calculose do rim e do ureter'),
  ('N200', 'Calculose do rim', 'N20.0 Calculose do rim'),
  ('N201', 'Calculose do ureter', 'N20.1 Calculose do ureter'),
  ('N202', 'Calculose do rim com cálculo do ureter', 'N20.2 Calculose do rim c/calculo do ureter'),
  ('N209', 'Calculose urinária, não especificada', 'N20.9 Calculose urinaria NE'),
  ('N21', 'Calculose do trato urinário inferior', 'N21 Calculose do trato urinario infer'),
  ('N210', 'Calculose na bexiga', 'N21.0 Calculose na bexiga'),
  ('N211', 'Cálculo uretral', 'N21.1 Calculo uretral'),
  ('N218', 'Outros cálculos do trato urinário inferior', 'N21.8 Outr calculos do trato urinario infer'),
  ('N219', 'Cálculo do trato urinário inferior, porção não especificada', 'N21.9 Calculo do trato urinario infer porcao NE'),
  ('N22', 'Calculose do trato urinário inferior em doenças classificadas em outra parte', 'N22 Calculose do trato urinario infer doenc COP'),
  ('N220', 'Cálculo urinário na esquistossomose (bilharziose) (schistosomíase)', 'N22.0 Calculo urinario na esquistossomose'),
  ('N228', 'Calculose do trato urinário em outras doenças classificadas em outra parte', 'N22.8 Calculose do trato urinario outr doenc COP'),
  ('N23', 'Cólica nefrética não especificada', 'N23 Colica nefretica NE'),
  ('N23', 'Cólica nefrética não especificada', 'N23 Colica nefretica NE'),
  ('N25', 'Transtornos resultantes de função renal tubular alterada', 'N25 Transt result funcao renal tubular alterada'),
  ('N250', 'Osteodistrofia renal', 'N25.0 Osteodistrofia renal'),
  ('N251', 'Diabetes insípido nefrogênico', 'N25.1 Diabetes insipido nefrogenico'),
  ('N258', 'Outros transtornos resultantes de função renal tubular alterada', 'N25.8 Outr transt result func renal tubular alter'),
  ('N259', 'Transtornos resultante de função tubular alterada', 'N25.9 Transt resultante de funcao tubular alterada'),
  ('N26', 'Rim contraído, não especificado', 'N26 Rim contraido NE'),
  ('N26', 'Rim contraído, não especificado', 'N26 Rim contraido NE'),
  ('N27', 'Hipoplasia renal de causa desconhecida', 'N27 Hipoplasia renal de causa desconhecida'),
  ('N270', 'Hipoplasia renal unilateral', 'N27.0 Hipoplasia renal unilateral'),
  ('N271', 'Hipoplasia renal bilateral', 'N27.1 Hipoplasia renal bilateral'),
  ('N279', 'Hipoplasia renal não especificada', 'N27.9 Hipoplasia renal NE'),
  ('N28', 'Outros transtornos do rim e do ureter não classificado em outra parte', 'N28 Outr transt do rim e do ureter NCOP'),
  ('N280', 'Isquemia e infarto renal', 'N28.0 Isquemia e infarto renal'),
  ('N281', 'Cisto do rim, adquirido', 'N28.1 Cisto do rim adquir'),
  ('N288', 'Outros transtornos especificados do rim e do ureter', 'N28.8 Outr transt espec do rim e do ureter'),
  ('N289', 'Transtorno não especificado do rim e do ureter', 'N28.9 Transt NE do rim e do ureter'),
  ('N29', 'Outros transtornos do rim e do ureter em doenças classificadas em outra parte', 'N29 Outr transt do rim e do ureter em doenc COP'),
  ('N290', 'Sífilis tardia renal', 'N29.0 Sifilis tard renal'),
  ('N291', 'Outros transtornos do rim e do ureter em doenças infecciosas e parasitárias classificadas em outra parte', 'N29.1 Outr transt rim ureter doenc infec paras COP'),
  ('N298', 'Outros transtornos do rim e do ureter em outras doenças classificadas em outra parte', 'N29.8 Outr transt rim e ureter em outr doenc COP'),
  ('N30', 'Cistite', 'N30 Cistite'),
  ('N300', 'Cistite aguda', 'N30.0 Cistite aguda'),
  ('N301', 'Cistite intersticial (crônica)', 'N30.1 Cistite intersticial'),
  ('N302', 'Outras cistites crônicas', 'N30.2 Outr cistites cronicas'),
  ('N303', 'Trigonite', 'N30.3 Trigonite'),
  ('N304', 'Cistite por radiação', 'N30.4 Cistite p/radiacao'),
  ('N308', 'Outras cistites', 'N30.8 Outr cistites'),
  ('N309', 'Cistite, não especificada', 'N30.9 Cistite NE'),
  ('N31', 'Disfunções neuromusculares da bexiga não classificados em outra parte', 'N31 Disfuncoes neuromusculares da bexiga NCOP'),
  ('N310', 'Bexiga neuropática não-inibida não classificada em outra parte', 'N31.0 Bexiga neuropatica nao-inibida NCOP'),
  ('N311', 'Bexiga neuropática reflexa não classificada em outra parte', 'N31.1 Bexiga neuropatica reflexa NCOP'),
  ('N312', 'Bexiga neuropática flácida não classificada em outra parte', 'N31.2 Bexiga neuropatica flacida NCOP'),
  ('N318', 'Outra disfunção neuromuscular da bexiga', 'N31.8 Outr disfuncao neuromuscular da bexiga'),
  ('N319', 'Disfunção neuromuscular não especificada da bexiga', 'N31.9 Disfuncao neuromuscular NE da bexiga'),
  ('N32', 'Outros transtornos da bexiga', 'N32 Outr transt da bexiga'),
  ('N320', 'Obstrução do colo da bexiga', 'N32.0 Obstrucao do colo da bexiga'),
  ('N321', 'Fístula êntero-vesical', 'N32.1 Fistula entero-vesical'),
  ('N322', 'Fístula vesical não classificada em outra parte', 'N32.2 Fistula vesical NCOP'),
  ('N323', 'Divertículo da bexiga', 'N32.3 Diverticulo da bexiga'),
  ('N324', 'Ruptura da bexiga, não-traumática', 'N32.4 Ruptura da bexiga nao-traum'),
  ('N328', 'Outros transtornos especificados da bexiga', 'N32.8 Outr transt espec da bexiga'),
  ('N329', 'Transtorno não especificado da bexiga', 'N32.9 Transt NE da bexiga'),
  ('N33', 'Transtornos da bexiga em doenças classificadas em outra parte', 'N33 Transt da bexiga em doenc COP'),
  ('N330', 'Cistite tuberculosa', 'N33.0 Cistite tuberc'),
  ('N338', 'Transtornos da bexiga em outras doenças classificadas em outra parte', 'N33.8 Transt da bexiga em outr doenc COP'),
  ('N34', 'Uretrite e síndrome uretral', 'N34 Uretrite e sindr uretral'),
  ('N340', 'Abscesso uretral', 'N34.0 Abscesso uretral'),
  ('N341', 'Uretrites não específicas', 'N34.1 Uretrites nao especificas'),
  ('N342', 'Outras uretrites', 'N34.2 Outr uretrites'),
  ('N343', 'Síndrome uretral, não especificada', 'N34.3 Sindr uretral NE'),
  ('N35', 'Estenose da uretra', 'N35 Estenose da uretra'),
  ('N350', 'Estenose uretral pós-traumática', 'N35.0 Estenose uretral pos-traum'),
  ('N351', 'Estenose uretral pós-infecciosa não classificada em outra parte', 'N35.1 Estenose uretral pos-infecc NCOP'),
  ('N358', 'Outra estenose (estreitamento) uretral', 'N35.8 Outr estenose uretral'),
  ('N359', 'Estenose (estreitamento) uretral não especificada(o)', 'N35.9 Estenose uretral NE'),
  ('N36', 'Outros transtornos da uretra', 'N36 Outr transt da uretra'),
  ('N360', 'Fístula uretral', 'N36.0 Fistula uretral'),
  ('N361', 'Divertículo uretral', 'N36.1 Diverticulo uretral'),
  ('N362', 'Carúncula uretral', 'N36.2 Caruncula uretral'),
  ('N363', 'Prolapso da mucosa uretral', 'N36.3 Prolapso da mucosa uretral'),
  ('N368', 'Outros transtornos especificados da uretra', 'N36.8 Outr transt espec da uretra'),
  ('N369', 'Transtorno não especificado da uretra', 'N36.9 Transt NE da uretra'),
  ('N37', 'Transtornos da uretra em doenças classificadas em outra parte', 'N37 Transt da uretra em doenc COP'),
  ('N370', 'Uretrite em doenças classificadas em outra parte', 'N37.0 Uretrite em doenc COP'),
  ('N378', 'Outros transtornos da uretra em doenças classificadas em outra parte', 'N37.8 Outr transt da uretra em doenc COP'),
  ('N39', 'Outros transtornos do trato urinário', 'N39 Outr transt do trato urinario'),
  ('N390', 'Infecção do trato urinário de localização não especificada', 'N39.0 Infecc do trato urinario de localiz NE'),
  ('N391', 'Proteinúria persistente não especificada', 'N39.1 Proteinuria persistente NE'),
  ('N392', 'Proteinúria ortostática não especificada', 'N39.2 Proteinuria ortostatica NE'),
  ('N393', 'Incontinência de tensão (stress)', 'N39.3 Incontinencia de tensao'),
  ('N394', 'Outras incontinências urinárias especificadas', 'N39.4 Outr incontinencias urinarias espec'),
  ('N398', 'Outros transtornos especificados do aparelho urinário', 'N39.8 Outr transt espec do aparelho urinario'),
  ('N399', 'Transtornos não especificados do aparelho urinário', 'N39.9 Transt NE do aparelho urinario'),
  ('N40', 'Hiperplasia da próstata', 'N40 Hiperplasia da prostata'),
  ('N40', 'Hiperplasia da próstata', 'N40 Hiperplasia da prostata'),
  ('N41', 'Doenças inflamatórias da próstata', 'N41 Doenc inflam da prostata'),
  ('N410', 'Prostatite aguda', 'N41.0 Prostatite aguda'),
  ('N411', 'Prostatite crônica', 'N41.1 Prostatite cronica'),
  ('N412', 'Abscesso da próstata', 'N41.2 Abscesso da prostata'),
  ('N413', 'Prostatocistite', 'N41.3 Prostatocistite'),
  ('N418', 'Outras doenças inflamatórias da próstata', 'N41.8 Outr doenc inflam da prostata'),
  ('N419', 'Doença inflamatória não especificada da próstata', 'N41.9 Doenc inflam NE da prostata'),
  ('N42', 'Outras afecções da próstata', 'N42 Outr afeccoes da prostata'),
  ('N420', 'Cálculo da próstata', 'N42.0 Calculo da prostata'),
  ('N421', 'Congestão e hemorragia da próstata', 'N42.1 Congestao e hemorragia da prostata'),
  ('N422', 'Atrofia da próstata', 'N42.2 Atrofia da prostata'),
  ('N428', 'Outras afecções especificadas da próstata', 'N42.8 Outr afeccoes espec da prostata'),
  ('N429', 'Afecção não especificada da próstata', 'N42.9 Afeccao NE da prostata'),
  ('N43', 'Hidrocele e espermatocele', 'N43 Hidrocele e espermatocele'),
  ('N430', 'Hidrocele encistada', 'N43.0 Hidrocele encistada'),
  ('N431', 'Hidrocele infectada', 'N43.1 Hidrocele infectada'),
  ('N432', 'Outra hidrocele', 'N43.2 Outr hidrocele'),
  ('N433', 'Hidrocele não especificada', 'N43.3 Hidrocele NE'),
  ('N434', 'Espermatocele', 'N43.4 Espermatocele'),
  ('N44', 'Torção do testículo', 'N44 Torcao do testiculo'),
  ('N44', 'Torção do testículo', 'N44 Torcao do testiculo'),
  ('N45', 'Orquite e epididimite', 'N45 Orquite e epididimite'),
  ('N450', 'Orquite, epididimite e epidídimo-orquite, com menção de abscesso', 'N45.0 Orquite epidid epididimo-orquite c/menc absc'),
  ('N459', 'Orquite, epididimite e epidídimo-orquite, sem menção de abscesso', 'N45.9 Orquite epidid epididimo-orquite s/menc absc'),
  ('N46', 'Infertilidade masculina', 'N46 Infertilidade masc'),
  ('N46', 'Infertilidade masculina', 'N46 Infertilidade masc'),
  ('N47', 'Hipertrofia do prepúcio, fimose e parafimose', 'N47 Hipertrofia do prepucio fimose e parafimose'),
  ('N47', 'Hipertrofia do prepúcio, fimose e parafimose', 'N47 Hipertrofia do prepucio fimose e parafimose'),
  ('N48', 'Outros transtornos do pênis', 'N48 Outr transt do penis'),
  ('N480', 'Leucoplasia do pênis', 'N48.0 Leucoplasia do penis'),
  ('N481', 'Balanopostite', 'N48.1 Balanopostite'),
  ('N482', 'Outros transtornos inflamatórios do pênis', 'N48.2 Outr transt inflam do penis'),
  ('N483', 'Priapismo', 'N48.3 Priapismo'),
  ('N484', 'Impotência de origem orgânica', 'N48.4 Impotencia orig organica'),
  ('N485', 'Úlcera do pênis', 'N48.5 Ulcera do penis'),
  ('N486', 'Induratio penis plastica', 'N48.6 Induratio penis plastica'),
  ('N488', 'Outros transtornos especificados do pênis', 'N48.8 Outr transt espec do penis'),
  ('N489', 'Transtorno não especificado do pênis', 'N48.9 Transt NE do penis'),
  ('N49', 'Transtornos inflamatórios de órgãos genitais masculinos, não classificados em outra parte', 'N49 Transt inflam orgaos genitais masc NCOP'),
  ('N490', 'Transtornos inflamatórios da vesícula seminal', 'N49.0 Transt inflam da vesicula seminal'),
  ('N491', 'Transtornos inflamatórios do cordão espermático, túnica vaginal e vasos deferentes', 'N49.1 Transt infl cord esperm tunic vagin vas def'),
  ('N492', 'Transtorno inflamatório do escroto', 'N49.2 Transt inflam do escroto'),
  ('N498', 'Transtornos inflamatórios de outros órgãos genitais masculinos especificados', 'N49.8 Transt inflam outr org genitais masc espec'),
  ('N499', 'Transtorno inflamatório de órgão genital masculino, não especificado', 'N49.9 Transt inflam de orgao genital masc NE'),
  ('N50', 'Outros transtornos dos órgãos genitais masculinos', 'N50 Outr transt dos orgaos genitais masc'),
  ('N500', 'Atrofia do testículo', 'N50.0 Atrofia do testiculo'),
  ('N501', 'Transtornos vasculares dos órgãos genitais masculinos', 'N50.1 Transt vasculares orgaos genitais masc'),
  ('N508', 'Outros transtornos especificados dos órgãos genitais masculinos', 'N50.8 Outr transt espec orgaos genitais masc'),
  ('N509', 'Transtorno não especificado dos órgãos genitais masculinos', 'N50.9 Transt NE dos orgaos genitais masc'),
  ('N51', 'Transtornos dos órgãos genitais masculinos em doenças classificadas em outra parte', 'N51 Transt orgaos genitais masc doenc COP'),
  ('N510', 'Transtornos da próstata em doenças classificadas em outra parte', 'N51.0 Transt da prostata em doenc COP'),
  ('N511', 'Transtornos do testículo e do epidídimo em doenças classificadas em outra parte', 'N51.1 Transt do testiculo e epididimo em doenc COP'),
  ('N512', 'Balanite em doenças classificadas em outra parte', 'N51.2 Balanite em doenc COP'),
  ('N518', 'Outros transtornos dos órgãos genitais masculinos em doenças classificadas em outra parte', 'N51.8 Outr transt orgaos genitais masc doenc COP'),
  ('N60', 'Displasias mamárias benignas', 'N60 Displasias mamarias benignas'),
  ('N600', 'Cisto solitário da mama', 'N60.0 Cisto solitario da mama'),
  ('N601', 'Mastopatia cística difusa', 'N60.1 Mastopatia cistica difusa'),
  ('N602', 'Fibroadenose da mama', 'N60.2 Fibroadenose da mama'),
  ('N603', 'Fibrosclerose da mama', 'N60.3 Fibrosclerose da mama'),
  ('N604', 'Ectasia de dutos mamários', 'N60.4 Ectasia de dutos mamarios'),
  ('N608', 'Outras displasias mamárias benignas', 'N60.8 Outr displasias mamarias benignas'),
  ('N609', 'Displasia mamária benigna não especificada', 'N60.9 Displasia mamaria benigna NE'),
  ('N61', 'Transtornos inflamatórios da mama', 'N61 Transt inflam da mama'),
  ('N61', 'Transtornos inflamatórios da mama', 'N61 Transt inflam da mama'),
  ('N62', 'Hipertrofia da mama', 'N62 Hipertrofia da mama'),
  ('N62', 'Hipertrofia da mama', 'N62 Hipertrofia da mama'),
  ('N63', 'Nódulo mamário não especificado', 'N63 Nodulo mamario NE'),
  ('N63', 'Nódulo mamário não especificado', 'N63 Nodulo mamario NE'),
  ('N64', 'Outras doenças da mama', 'N64 Outr doenc da mama'),
  ('N640', 'Fissura e fístula do mamilo', 'N64.0 Fissura e fistula do mamilo'),
  ('N641', 'Necrose gordurosa da mama', 'N64.1 Necrose gordurosa da mama'),
  ('N642', 'Atrofia da mama', 'N64.2 Atrofia da mama'),
  ('N643', 'Galactorréia não-associada ao parto', 'N64.3 Galactorreia nao-assoc ao parto'),
  ('N644', 'Mastodinia', 'N64.4 Mastodinia'),
  ('N645', 'Outros sintomas e sinais da mama', 'N64.5 Outr sint e sinais da mama'),
  ('N648', 'Outros transtornos especificados da mama', 'N64.8 Outr transt espec da mama'),
  ('N649', 'Transtorno da mama não especificado', 'N64.9 Transt da mama NE'),
  ('N70', 'Salpingite e ooforite', 'N70 Salpingite e ooforite'),
  ('N700', 'Salpingite e ooforite agudas', 'N70.0 Salpingite e ooforite agudas'),
  ('N701', 'Salpingite e ooforite crônicas', 'N70.1 Salpingite e ooforite cronicas'),
  ('N709', 'Salpingite e ooforite não especificadas', 'N70.9 Salpingite e ooforite NE'),
  ('N71', 'Doença inflamatória do útero, exceto o colo', 'N71 Doenc inflam do utero exceto o colo'),
  ('N710', 'Doença inflamatória aguda do útero', 'N71.0 Doenc inflam aguda do utero'),
  ('N711', 'Doença inflamatória crônica do útero', 'N71.1 Doenc inflam cronica do utero'),
  ('N719', 'Doença inflamatória não especificada do útero', 'N71.9 Doenc inflam NE do utero'),
  ('N72', 'Doença inflamatória do colo do útero', 'N72 Doenc inflam do colo do utero'),
  ('N72', 'Doença inflamatória do colo do útero', 'N72 Doenc inflam do colo do utero'),
  ('N73', 'Outras doenças inflamatórias pélvicas femininas', 'N73 Outr doenc inflam pelvicas femin'),
  ('N730', 'Parametrite e celulite pélvicas agudas', 'N73.0 Parametrite e celulite pelvicas agudas'),
  ('N731', 'Parametrite e celulite pélvicas crônicas', 'N73.1 Parametrite e celulite pelvicas cronicas'),
  ('N732', 'Parametrite e celulite pélvicas não especificadas', 'N73.2 Parametrite e celulite pelvicas NE'),
  ('N733', 'Pelviperitonite aguda feminina', 'N73.3 Pelviperitonite aguda femin'),
  ('N734', 'Pelviperitonite crônica feminina', 'N73.4 Pelviperitonite cronica femin'),
  ('N735', 'Pelviperitonite não especificada feminina', 'N73.5 Pelviperitonite NE femin'),
  ('N736', 'Aderências pelviperitonais femininas', 'N73.6 Aderencias pelviperitonais femin'),
  ('N738', 'Outras doenças inflamatórias especificadas da pelve feminina', 'N73.8 Outr doenc inflam espec pelve fem'),
  ('N739', 'Doença inflamatória não especificada da pelve feminina', 'N73.9 Doenc inflam NE da pelve femin'),
  ('N74', 'Transtornos inflamatórios da pelve feminina em doenças classificadas em outra parte', 'N74 Transt inflam da pelve femin em doenc COP'),
  ('N740', 'Tuberculose do colo do útero', 'N74.0 Tuberc do colo do utero'),
  ('N741', 'Tuberculose da pelve feminina', 'N74.1 Tuberc da pelve femin'),
  ('N742', 'Sífilis pélvica feminina', 'N74.2 Sifilis pelvica femin'),
  ('N743', 'Infecção gonocócica pélvica feminina', 'N74.3 Infecc gonococica pelvica femin'),
  ('N744', 'Infecção pélvica feminina por clamídia', 'N74.4 Infecc pelvica femin p/clamidia'),
  ('N748', 'Inflamação pélvica feminina em outras doenças classificadas em outra parte', 'N74.8 Inflam pelvica femin em outr doenc COP'),
  ('N75', 'Doenças da glândula de Bartholin', 'N75 Doenc da gland de Bartholin'),
  ('N750', 'Cisto da glândula de Bartholin', 'N75.0 Cisto da gland de Bartholin'),
  ('N751', 'Abscesso da glândula de Bartholin', 'N75.1 Abscesso da gland de Bartholin'),
  ('N758', 'Outras doenças da glândula de Bartholin', 'N75.8 Outr doenc da gland de Bartholin'),
  ('N759', 'Doença não especificada da glândula de Bartholin', 'N75.9 Doenc NE da gland de Bartholin'),
  ('N76', 'Outras afecções inflamatórias da vagina e da vulva', 'N76 Outr afeccoes inflam da vagina e da vulva'),
  ('N760', 'Vaginite aguda', 'N76.0 Vaginite aguda'),
  ('N761', 'Vaginite subaguda e crônica', 'N76.1 Vaginite subaguda e cronica'),
  ('N762', 'Vulvite aguda', 'N76.2 Vulvite aguda'),
  ('N763', 'Vulvite subaguda e crônica', 'N76.3 Vulvite subaguda e cronica'),
  ('N764', 'Abscesso vulvar', 'N76.4 Abscesso vulvar'),
  ('N765', 'Ulceração vaginal', 'N76.5 Ulceracao vaginal'),
  ('N766', 'Ulceração vulvar', 'N76.6 Ulceracao vulvar'),
  ('N768', 'Outras inflamações especificadas da vagina e da vulva', 'N76.8 Outr inflam espec da vagina e da vulva'),
  ('N77', 'Ulceração e inflamação vulvovaginais em doenças classificadas em outra parte', 'N77 Ulceracao e inflam vulvovaginais doenc COP'),
  ('N770', 'Ulceração da vulva em doenças infecciosas e parasitárias classificadas em outra parte', 'N77.0 Ulceracao da vulva doenc infecc parasit COP'),
  ('N771', 'Vaginite, vulvite e vulvovaginite em doenças infecciosas e parasitárias classificadas em outra parte', 'N77.1 Vagin vulv vulvovaginite doenc inf paras COP'),
  ('N778', 'Ulceração e inflamação vulvovaginais em outras doenças classificadas em outra parte', 'N77.8 Ulceracao inflam vulvovag outr doenc COP'),
  ('N80', 'Endometriose', 'N80 Endometriose'),
  ('N800', 'Endometriose do útero', 'N80.0 Endometriose do utero'),
  ('N801', 'Endometriose do ovário', 'N80.1 Endometriose do ovario'),
  ('N802', 'Endometriose da trompa de Falópio', 'N80.2 Endometriose da trompa de Falopio'),
  ('N803', 'Endometriose do peritônio pélvico', 'N80.3 Endometriose do peritonio pelvico'),
  ('N804', 'Endometriose do septo retovaginal e da vagina', 'N80.4 Endometriose do septo retovaginal e vagina'),
  ('N805', 'Endometriose do intestino', 'N80.5 Endometriose do intestino'),
  ('N806', 'Endometriose em cicatriz cutânea', 'N80.6 Endometriose em cicatriz cutanea'),
  ('N808', 'Outra endometriose', 'N80.8 Outr endometriose'),
  ('N809', 'Endometriose não especificada', 'N80.9 Endometriose NE'),
  ('N81', 'Prolapso genital feminino', 'N81 Prolapso genital femin'),
  ('N810', 'Uretrocele feminina', 'N81.0 Uretrocele femin'),
  ('N811', 'Cistocele', 'N81.1 Cistocele'),
  ('N812', 'Prolapso uterovaginal incompleto', 'N81.2 Prolapso uterovaginal incompleto'),
  ('N813', 'Prolapso uterovaginal completo', 'N81.3 Prolapso uterovaginal completo'),
  ('N814', 'Prolapso uterovaginal não especificado', 'N81.4 Prolapso uterovaginal NE'),
  ('N815', 'Enterocele vaginal', 'N81.5 Enterocele vaginal'),
  ('N816', 'Retocele', 'N81.6 Retocele'),
  ('N818', 'Outro prolapso genital feminino', 'N81.8 Outr prolapso genital femin'),
  ('N819', 'Prolapso genital feminino não especificado', 'N81.9 Prolapso genital femin NE'),
  ('N82', 'Fístulas do trato genital feminino', 'N82 Fistulas do trato genital femin'),
  ('N820', 'Fístula vesicovaginal', 'N82.0 Fistula vesicovaginal'),
  ('N821', 'Outras fístulas do trato geniturinário feminino', 'N82.1 Outr fistulas do trato geniturinario femin'),
  ('N822', 'Fístula vagina-intestino delgado', 'N82.2 Fistula vagina-intestino delgado'),
  ('N823', 'Fístula vagina-cólon', 'N82.3 Fistula vagina-colon'),
  ('N824', 'Outras fístulas genito-intestinais femininas', 'N82.4 Outr fistulas genito-intestinais femin'),
  ('N825', 'Fístula genitocutânea feminina', 'N82.5 Fistula genitocutanea femin'),
  ('N828', 'Outras fístulas do trato genital feminino', 'N82.8 Outr fistulas do trato genital femin'),
  ('N829', 'Fístulas não especificadas do trato genital feminino', 'N82.9 Fistulas NE do trato genital femin'),
  ('N83', 'Transtornos não-inflamatórios do ovário, da trompa de Falópio e do ligamento largo', 'N83 Transt nao-infl ovario tromp Falop lig largo'),
  ('N830', 'Cisto folicular do ovário', 'N83.0 Cisto folicular do ovario'),
  ('N831', 'Cisto do corpo lúteo', 'N83.1 Cisto do corpo luteo'),
  ('N832', 'Outros cistos ovarianos e os não especificados', 'N83.2 Outr cistos ovarianos e os NE'),
  ('N833', 'Atrofia adquirida do ovário e da trompa de Falópio', 'N83.3 Atrofia adquir do ovario e trompa de Falopio'),
  ('N834', 'Prolapso e hérnia do ovário e da trompa de Falópio', 'N83.4 Prolapso e hernia ovario e trompa de Falopio'),
  ('N835', 'Torção do ovário, do pedículo ovariano e da trompa de Falópio', 'N83.5 Torcao ovario pediculo ovarian tromp Falopio'),
  ('N836', 'Hematossalpinge', 'N83.6 Hematossalpinge'),
  ('N837', 'Hematoma do ligamento largo', 'N83.7 Hematoma do ligamento largo'),
  ('N838', 'Outros transtornos não-inflamatórios do ovário, da trompa de Falópio e do ligamento largo', 'N83.8 Outr transt n infl ovar tromp Falop lig larg'),
  ('N839', 'Transtornos não-inflamatórios do ovário, da trompa de Falópio e do ligamento largo, não especificados', 'N83.9 Transt n infl ovar trompa Falop lig largo NE'),
  ('N84', 'Pólipo do trato genital feminino', 'N84 Polipo do trato genital femin'),
  ('N840', 'Pólipo do corpo do útero', 'N84.0 Polipo do corpo do utero'),
  ('N841', 'Pólipo do colo do útero', 'N84.1 Polipo do colo do utero'),
  ('N842', 'Pólipo da vagina', 'N84.2 Polipo da vagina'),
  ('N843', 'Pólipo da vulva', 'N84.3 Polipo da vulva'),
  ('N848', 'Pólipo de outras partes do trato genital feminino', 'N84.8 Polipo de outr partes do trato genital femin'),
  ('N849', 'Pólipo do trato genital feminino não especificado', 'N84.9 Polipo do trato genital femin NE'),
  ('N85', 'Outros transtornos não-inflamatórios do útero, exceto do colo do útero', 'N85 Outr transt nao-inflam utero exc colo utero'),
  ('N850', 'Hiperplasia glandular endometrial', 'N85.0 Hiperplasia glandular endometrial'),
  ('N851', 'Hiperplasia adenomatosa endometrial', 'N85.1 Hiperplasia adenomatosa endometrial'),
  ('N852', 'Hipertrofia do útero', 'N85.2 Hipertrofia do utero'),
  ('N853', 'Subinvolução do útero', 'N85.3 Subinvolucao do utero'),
  ('N854', 'Posição anormal do útero', 'N85.4 Posicao anormal do utero'),
  ('N855', 'Inversão do útero', 'N85.5 Inversao do utero'),
  ('N856', 'Sinéquias intra-uterinas', 'N85.6 Sinequias intra-uterinas'),
  ('N857', 'Hematometra', 'N85.7 Hematometra'),
  ('N858', 'Outros transtornos não-inflamatórios especificados do útero', 'N85.8 Outr transt nao-inflam espec do utero'),
  ('N859', 'Transtornos não-inflamatórios do útero, não especificados', 'N85.9 Transt nao-inflam do utero NE'),
  ('N86', 'Erosão e ectrópio do colo do útero', 'N86 Erosao e ectropio do colo do utero'),
  ('N86', 'Erosão e ectrópio do colo do útero', 'N86 Erosao e ectropio do colo do utero'),
  ('N87', 'Displasia do colo do útero', 'N87 Displasia do colo do utero'),
  ('N870', 'Displasia cervical leve', 'N87.0 Displasia cervical leve'),
  ('N871', 'Displasia cervical moderada', 'N87.1 Displasia cervical moderada'),
  ('N872', 'Displasia cervical grave, não classificada em outra parte', 'N87.2 Displasia cervical grave NCOP'),
  ('N879', 'Displasia do colo do útero, não especificada', 'N87.9 Displasia do colo do utero NE'),
  ('N88', 'Outros transtornos não-inflamatórios do colo do útero', 'N88 Outr transt nao-inflam do colo do utero'),
  ('N880', 'Leucoplasia do colo do útero', 'N88.0 Leucoplasia do colo do utero'),
  ('N881', 'Laceração antiga do colo do útero', 'N88.1 Laceracao antiga do colo do utero'),
  ('N882', 'Estreitamento e estenose do colo do útero', 'N88.2 Estreitamento e estenose do colo do utero'),
  ('N883', 'Incompetência do colo do útero', 'N88.3 Incompetencia do colo do utero'),
  ('N884', 'Alongamento hipertrófico do colo do útero', 'N88.4 Alongamento hipertrofico do colo do utero'),
  ('N888', 'Outros transtornos não-inflamatórios especificados do colo do útero', 'N88.8 Outr transt nao-inflam espec colo do utero'),
  ('N889', 'Transtorno não-inflamatório e não especificado do colo do útero', 'N88.9 Transt nao-inflam e NE do colo do utero'),
  ('N89', 'Outros transtornos não-inflamatórios da vagina', 'N89 Outr transt nao-inflam da vagina'),
  ('N890', 'Displasia vaginal leve', 'N89.0 Displasia vaginal leve'),
  ('N891', 'Displasia vaginal moderada', 'N89.1 Displasia vaginal moderada'),
  ('N892', 'Displasia vaginal grave, não classificada em outra parte', 'N89.2 Displasia vaginal grave NCOP'),
  ('N893', 'Displasia da vagina, não especificada', 'N89.3 Displasia da vagina NE'),
  ('N894', 'Leucoplasia da vagina', 'N89.4 Leucoplasia da vagina'),
  ('N895', 'Estreitamento e atresia da vagina', 'N89.5 Estreitamento e atresia da vagina'),
  ('N896', 'Anel himenal apertado', 'N89.6 Anel himenal apertado'),
  ('N897', 'Hematocolpos', 'N89.7 Hematocolpos'),
  ('N898', 'Outros transtornos não-inflamatórios especificados da vagina', 'N89.8 Outr transt nao-inflam espec da vagina'),
  ('N899', 'Transtorno não-inflamatório da vagina, não especificado', 'N89.9 Transt nao-inflam da vagina NE'),
  ('N90', 'Outros transtornos não-inflamatórios da vulva e do períneo', 'N90 Outr transt nao-inflam da vulva e do perineo'),
  ('N900', 'Displasia vulvar leve', 'N90.0 Displasia vulvar leve'),
  ('N901', 'Displasia vulvar moderada', 'N90.1 Displasia vulvar moderada'),
  ('N902', 'Displasia vulvar grave, não classificada em outra parte', 'N90.2 Displasia vulvar grave NCOP'),
  ('N903', 'Displasia de vulva, não especificada', 'N90.3 Displasia de vulva NE'),
  ('N904', 'Leucoplasia de vulva', 'N90.4 Leucoplasia de vulva'),
  ('N905', 'Atrofia da vulva', 'N90.5 Atrofia da vulva'),
  ('N906', 'Hipertrofia da vulva', 'N90.6 Hipertrofia da vulva'),
  ('N907', 'Cisto vulvar', 'N90.7 Cisto vulvar'),
  ('N908', 'Outros transtornos não-inflamatórios especificados da vulva e do períneo', 'N90.8 Outr transt nao-inflam espec vulva e perineo'),
  ('N909', 'Transtorno não-inflamatório e não especificado da vulva e do períneo', 'N90.9 Transt nao-inflam e NE da vulva e do perineo'),
  ('N91', 'Menstruação ausente, escassa e pouco freqüente', 'N91 Menstruacao ausente escassa e pouco freq'),
  ('N910', 'Amenorréia primária', 'N91.0 Amenorreia prim'),
  ('N911', 'Amenorréia secundária', 'N91.1 Amenorreia secund'),
  ('N912', 'Amenorréia, não especificada', 'N91.2 Amenorreia NE'),
  ('N913', 'Oligomenorréia primária', 'N91.3 Oligomenorreia prim'),
  ('N914', 'Oligomenorréia secundária', 'N91.4 Oligomenorreia secund'),
  ('N915', 'Oligomenorréia, não especificada', 'N91.5 Oligomenorreia NE'),
  ('N92', 'Menstruação excessiva, freqüente e irregular', 'N92 Menstruacao excessiva frequente e irregular'),
  ('N920', 'Menstruação excessiva e freqüente com ciclo regular', 'N92.0 Menstruacao excessiva freq c/ciclo regular'),
  ('N921', 'Menstruação excessiva e freqüente com ciclo irregular', 'N92.1 Menstruacao excessiva freq c/ciclo irregular'),
  ('N922', 'Menstruação excessiva na puberdade', 'N92.2 Menstruacao excessiva na puberdade'),
  ('N923', 'Sangramento da ovulação', 'N92.3 Sangramento da ovulacao'),
  ('N924', 'Sangramento abundante na pré-menopausa', 'N92.4 Sangramento abundante na pre-menopausa'),
  ('N925', 'Outros tipos especificados de irregularidade da menstruação', 'N92.5 Outr tipos espec irregularidade menstruacao'),
  ('N926', 'Menstruação irregular, não especificada', 'N92.6 Menstruacao irregular NE'),
  ('N93', 'Outros sangramentos anormais do útero e da vagina', 'N93 Outr sangramentos anormais utero e vagina'),
  ('N930', 'Sangramentos pós-coito ou de contato', 'N93.0 Sangramentos pos-coito ou de contato'),
  ('N938', 'Outros sangramentos anormais especificados do útero e da vagina', 'N93.8 Outr sangramentos anorm espec utero vagina'),
  ('N939', 'Sangramento anormal do útero ou da vagina, não especificado', 'N93.9 Sangramento anormal do utero ou da vagina NE'),
  ('N94', 'Dor e outras afecções associadas com os órgãos genitais femininos e com o ciclo menstrual', 'N94 Dor outr afecc ass org genit fem cicl menstr'),
  ('N940', 'Ovulação dolorosa (Mittelschmerz)', 'N94.0 Ovulacao dolorosa'),
  ('N941', 'Dispareunia', 'N94.1 Dispareunia'),
  ('N942', 'Vaginismo', 'N94.2 Vaginismo'),
  ('N943', 'Síndrome de tensão pré-menstrual', 'N94.3 Sindr de tensao pre-menstrual'),
  ('N944', 'Dismenorréia primária', 'N94.4 Dismenorreia prim'),
  ('N945', 'Dismenorréia secundária', 'N94.5 Dismenorreia secund'),
  ('N946', 'Dismenorréia não especificada', 'N94.6 Dismenorreia NE'),
  ('N948', 'Outras afecções especificadas associadas com os órgãos genitais femininos e com o ciclo menstrual', 'N94.8 Outr afec esp ass org genit fem ciclo menstr'),
  ('N949', 'Afecções não especificadas associadas com os órgãos genitais femininos e com o ciclo menstrual', 'N94.9 Afecc NE assoc org genit femin ciclo menstr'),
  ('N95', 'Transtornos da menopausa e da perimenopausa', 'N95 Transt da menopausa e da perimenopausa'),
  ('N950', 'Sangramento pós-menopausa', 'N95.0 Sangramento pos-menopausa'),
  ('N951', 'Estado da menopausa e do climatério feminino', 'N95.1 Estado da menopausa e do climaterio femin'),
  ('N952', 'Vaginite atrófica pós-menopausa', 'N95.2 Vaginite atrofica pos-menopausa'),
  ('N953', 'Condições associadas com a menopausa artificial', 'N95.3 Condicoes assoc c/a menopausa artificial'),
  ('N958', 'Outros transtornos especificados da menopausa e da perimenopausa', 'N95.8 Outr transt espec menopausa e perimenopausa'),
  ('N959', 'Transtorno não especificado da menopausa e da perimenopausa', 'N95.9 Transt NE da menopausa e da perimenopausa'),
  ('N96', 'Abortamento habitual', 'N96 Abortamento habitual'),
  ('N96', 'Abortamento habitual', 'N96 Abortamento habitual'),
  ('N97', 'Infertilidade feminina', 'N97 Infertilidade femin'),
  ('N970', 'Infertilidade feminina associada à anovulação', 'N97.0 Infertilidade femin assoc a anovulacao'),
  ('N971', 'Infertilidade feminina de origem tubária', 'N97.1 Infertilidade femin orig tubaria'),
  ('N972', 'Infertilidade feminina de origem uterina', 'N97.2 Infertilidade femin orig uterina'),
  ('N973', 'Infertilidade feminina de origem cervical', 'N97.3 Infertilidade femin orig cervical'),
  ('N974', 'Infertilidade feminina associada à fatores do parceiro', 'N97.4 Infertilidade femin assoc fatores parceiro'),
  ('N978', 'Infertilidade feminina de outra origem', 'N97.8 Infertilidade femin de outr origem'),
  ('N979', 'Infertilidade feminina não especificada', 'N97.9 Infertilidade femin NE'),
  ('N98', 'Complicações associadas à fecundação artificial', 'N98 Complic assoc a fecundacao artificial'),
  ('N980', 'Infecção associada à inseminação artificial', 'N98.0 Infecc assoc a inseminacao artificial'),
  ('N981', 'Hiperestimulação dos ovários', 'N98.1 Hiperestimulacao dos ovarios'),
  ('N982', 'Complicações relacionadas com a tentativa de introdução do óvulo fecundado artificialmente (in vitro)', 'N98.2 Complic relac tent introd ovulo fecund artif'),
  ('N983', 'Complicações relacionadas com a tentativa de transferência do embrião', 'N98.3 Complic relac tent transferencia do embriao'),
  ('N988', 'Outras complicações associadas à fecundação artificial', 'N98.8 Outr complic assoc a fecundacao artificial'),
  ('N989', 'Complicações não especificadas associadas à fecundação artificial', 'N98.9 Complic NE assoc a fecundacao artificial'),
  ('N99', 'Transtornos do trato geniturinário pós-procedimentos não classificados em outra parte', 'N99 Transt trato geniturinario pos-proced NCOP'),
  ('N990', 'Insuficiência renal pós-procedimentos', 'N99.0 Insuf renal pos-proced'),
  ('N991', 'Estreitamento de uretra pós-procedimentos', 'N99.1 Estreitamento de uretra pos-proced'),
  ('N992', 'Aderências pós-operatórias da vagina', 'N99.2 Aderencias pos-operatorias da vagina'),
  ('N993', 'Prolapso de cúpula de vagina pós-histerectomia', 'N99.3 Prolapso cupula de vagina pos-histerectomia'),
  ('N994', 'Aderências do peritônio pélvico pós-procedimentos', 'N99.4 Aderencias do peritonio pelvico pos-proced'),
  ('N995', 'Mau funcionamento de abertura externa (estoma) do trato urinário', 'N99.5 Mau funcionamento abertura ext trato urin'),
  ('N998', 'Outros transtornos pós-procedimentos do aparelho geniturinário', 'N99.8 Outr transt pos-proced ap geniturinario'),
  ('N999', 'Transtorno pós-procedimento não especificado do aparelho geniturinário', 'N99.9 Transt pos-proced NE aparelho geniturinario');
