INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('H00', 'Hordéolo e calázio', 'H00 Hordeolo e calazio'),
  ('H000', 'Hordéolo e outras inflamações profundas das pálpebras', 'H00.0 Hordeolo e outr inflam profundas palpebras'),
  ('H001', 'Calázio', 'H00.1 Calazio'),
  ('H01', 'Outras inflamações da pálpebra', 'H01 Outr inflam da palpebra'),
  ('H010', 'Blefarite', 'H01.0 Blefarite'),
  ('H011', 'Dermatoses não infecciosas da pálpebra', 'H01.1 Dermatoses nao infecc da palpebra'),
  ('H018', 'Outras inflamações especificadas da pálpebra', 'H01.8 Outr inflam espec da palpebra'),
  ('H019', 'Inflamação não especificada da pálpebra', 'H01.9 Inflam NE da palpebra'),
  ('H02', 'Outros transtornos da pálpebra', 'H02 Outr transt da palpebra'),
  ('H020', 'Entrópio e triquíase da pálpebra', 'H02.0 Entropio e triquiase da palpebra'),
  ('H021', 'Ectrópio da pálpebra', 'H02.1 Ectropio da palpebra'),
  ('H022', 'Lagoftalmo', 'H02.2 Lagoftalmo'),
  ('H023', 'Blefarocalásia', 'H02.3 Blefarocalasia'),
  ('H024', 'Ptose da pálpebra', 'H02.4 Ptose da palpebra'),
  ('H025', 'Outros transtornos que afetam a função da pálpebra', 'H02.5 Outr transt que afetam a funcao da palpebra'),
  ('H026', 'Xantelasma da pálpebra', 'H02.6 Xantelasma da palpebra'),
  ('H027', 'Outros transtornos degenerativos da pálpebra e da área periocular', 'H02.7 Outr transt degener palpebra area periocular'),
  ('H028', 'Outros transtornos especificados das pálpebras', 'H02.8 Outr transt espec das palpebras'),
  ('H029', 'Transtorno não especificado da pálpebra', 'H02.9 Transt NE da palpebra'),
  ('H03', 'Transtornos da pálpebra em doenças classificadas em outras partes', 'H03 Transt da palpebra em doenc COP'),
  ('H030', 'Infestação parasitária da pálpebra em doenças classificadas em outra parte', 'H03.0 Infestacao parasit da palpebra doenc COP'),
  ('H031', 'Comprometimento da pálpebra em outras doenças infecciosas classificadas em outra parte', 'H03.1 Compr da palpebra em outr doenc infecc COP'),
  ('H038', 'Comprometimento da pálpebra em outras doenças classificadas em outras partes', 'H03.8 Compr da palpebra em outr doenc COP'),
  ('H04', 'Transtornos do aparelho lacrimal', 'H04 Transt do aparelho lacrimal'),
  ('H040', 'Dacrioadenite', 'H04.0 Dacrioadenite'),
  ('H041', 'Outros transtornos da glândula lacrimal', 'H04.1 Outr transt da gland lacrimal'),
  ('H042', 'Epífora', 'H04.2 Epifora'),
  ('H043', 'Inflamação aguda e não especificada dos canais lacrimais', 'H04.3 Inflam aguda e NE dos canais lacrimais'),
  ('H044', 'Inflamação crônica dos canais lacrimais', 'H04.4 Inflam cronica dos canais lacrimais'),
  ('H045', 'Estenose e insuficiência dos canais lacrimais', 'H04.5 Estenose e insuf dos canais lacrimais'),
  ('H046', 'Outras alterações nos canais lacrimais', 'H04.6 Outr alteracoes nos canais lacrimais'),
  ('H048', 'Outros transtornos do aparelho lacrimal', 'H04.8 Outr transt do aparelho lacrimal'),
  ('H049', 'Transtorno não especificado do aparelho lacrimal', 'H04.9 Transt NE do aparelho lacrimal'),
  ('H05', 'Transtornos da órbita', 'H05 Transt da orbita'),
  ('H050', 'Inflamação aguda da órbita', 'H05.0 Inflam aguda da orbita'),
  ('H051', 'Transtornos inflamatórios crônicos da órbita', 'H05.1 Transt inflam cronicos da orbita'),
  ('H052', 'Afecções exoftálmicas', 'H05.2 Afeccoes exoftalmicas'),
  ('H053', 'Deformidade da órbita', 'H05.3 Deform da orbita'),
  ('H054', 'Enoftalmia', 'H05.4 Enoftalmia'),
  ('H055', 'Corpo estranho (antigo) retido conseqüente a ferimento perfurante da órbita', 'H05.5 Corpo estranho ret cons ferim perfur orbita'),
  ('H058', 'Outros transtornos da órbita', 'H05.8 Outr transt da orbita'),
  ('H059', 'Transtorno não especificado da órbita', 'H05.9 Transt NE da orbita'),
  ('H06', 'Transtornos do aparelho lacrimal e da órbita em doenças classificadas em outra parte', 'H06 Transt aparelho lacrimal orbita em doenc COP'),
  ('H060', 'Transtornos do aparelho lacrimal em doenças classificadas em outra parte', 'H06.0 Transt do aparelho lacrimal em doenc COP'),
  ('H061', 'Infestação parasitária da órbita em doenças classificadas em outra parte', 'H06.1 Infestacao parasit da orbita doenc COP'),
  ('H062', 'Exoftalmo distireoídeo', 'H06.2 Exoftalmo distireoideo'),
  ('H063', 'Outros transtornos da órbita em doenças classificadas em outra parte', 'H06.3 Outr transt da orbita em doenc COP'),
  ('H10', 'Conjuntivite', 'H10 Conjuntivite'),
  ('H100', 'Conjuntivite mucopurulenta', 'H10.0 Conjuntivite mucopurulenta'),
  ('H101', 'Conjuntivite aguda atópica', 'H10.1 Conjuntivite aguda atopica'),
  ('H102', 'Outras conjuntivites agudas', 'H10.2 Outr conjuntivites agudas'),
  ('H103', 'Conjuntivite aguda não especificada', 'H10.3 Conjuntivite aguda NE'),
  ('H104', 'Conjuntivite crônica', 'H10.4 Conjuntivite cronica'),
  ('H105', 'Blefaroconjuntivite', 'H10.5 Blefaroconjuntivite'),
  ('H108', 'Outras conjuntivites', 'H10.8 Outr conjuntivites'),
  ('H109', 'Conjuntivite não especificada', 'H10.9 Conjuntivite NE'),
  ('H11', 'Outros transtornos da conjuntiva', 'H11 Outr transt da conjuntiva'),
  ('H110', 'Pterígio', 'H11.0 Pterigio'),
  ('H111', 'Degenerações e depósitos da conjuntiva', 'H11.1 Degeneracoes e depositos da conjuntiva'),
  ('H112', 'Cicatrizes da conjuntiva', 'H11.2 Cicatrizes da conjuntiva'),
  ('H113', 'Hemorragia conjuntival', 'H11.3 Hemorragia conjuntival'),
  ('H114', 'Outros transtornos vasculares e cistos conjuntivais', 'H11.4 Outr transt vasculares e cistos conjuntivais'),
  ('H118', 'Outros transtornos especificados da conjuntiva', 'H11.8 Outr transt espec da conjuntiva'),
  ('H119', 'Transtorno não especificado da conjuntiva', 'H11.9 Transt NE da conjuntiva'),
  ('H13', 'Transtornos da conjuntiva em doenças classificadas em outra parte', 'H13 Transt da conjuntiva em doenc COP'),
  ('H130', 'Infestação por filárias na conjuntiva', 'H13.0 Infestacao p/filarias na conjuntiva'),
  ('H131', 'Conjuntivite em doenças infecciosas e parasitárias classificadas em outra parte', 'H13.1 Conjuntivite em doenc infecc e parasit COP'),
  ('H132', 'Conjuntivite em outras doenças classificadas em outra parte', 'H13.2 Conjuntivite em outr doenc COP'),
  ('H133', 'Penfigóide ocular', 'H13.3 Penfigoide ocular'),
  ('H138', 'Outros transtornos da conjuntiva em doença classificadas em outra parte', 'H13.8 Outr transt da conjuntiva em doenc COP'),
  ('H15', 'Transtornos da esclerótica', 'H15 Transt da esclerotica'),
  ('H150', 'Esclerite', 'H15.0 Esclerite'),
  ('H151', 'Episclerite', 'H15.1 Episclerite'),
  ('H158', 'Outros transtornos da esclerótica', 'H15.8 Outr transt da esclerotica'),
  ('H159', 'Transtorno não especificado da esclerótica', 'H15.9 Transt NE da esclerotica'),
  ('H16', 'Ceratite', 'H16 Ceratite'),
  ('H160', 'Úlcera de córnea', 'H16.0 Ulcera de cornea'),
  ('H161', 'Outras ceratites superficiais sem conjuntivite', 'H16.1 Outr ceratites superf s/conjuntivite'),
  ('H162', 'Ceratoconjuntivite', 'H16.2 Ceratoconjuntivite'),
  ('H163', 'Ceratites intersticial e profunda', 'H16.3 Ceratites intersticial e profunda'),
  ('H164', 'Neovascularização da córnea', 'H16.4 Neovascularizacao da cornea'),
  ('H168', 'Outras ceratites', 'H16.8 Outr ceratites'),
  ('H169', 'Ceratite não especificada', 'H16.9 Ceratite NE'),
  ('H17', 'Cicatrizes e opacidades da córnea', 'H17 Cicatrizes e opacidades da cornea'),
  ('H170', 'Leucoma aderente', 'H17.0 Leucoma aderente'),
  ('H171', 'Outra opacidade central da córnea', 'H17.1 Outr opacidade central da cornea'),
  ('H178', 'Outras cicatrizes e opacidades da córnea', 'H17.8 Outr cicatrizes e opacidades da cornea'),
  ('H179', 'Cicatriz e opacidade não especificadas da córnea', 'H17.9 Cicatriz e opacidade NE da cornea'),
  ('H18', 'Outros transtornos da córnea', 'H18 Outr transt da cornea'),
  ('H180', 'Pigmentações e depósitos da córnea', 'H18.0 Pigmentacoes e depositos da cornea'),
  ('H181', 'Ceratopatia bolhosa', 'H18.1 Ceratopatia bolhosa'),
  ('H182', 'Outros edemas da córnea', 'H18.2 Outr edemas da cornea'),
  ('H183', 'Alterações nas membranas da córnea', 'H18.3 Alteracoes nas membranas da cornea'),
  ('H184', 'Degenerações da córnea', 'H18.4 Degeneracoes da cornea'),
  ('H185', 'Distrofias hereditárias da córnea', 'H18.5 Distrofias hereditarias da cornea'),
  ('H186', 'Ceratocone', 'H18.6 Ceratocone'),
  ('H187', 'Outras deformidades da córnea', 'H18.7 Outr deform da cornea'),
  ('H188', 'Outros transtornos especificados da córnea', 'H18.8 Outr transt espec da cornea'),
  ('H189', 'Transtorno não especificado da córnea', 'H18.9 Transt NE da cornea'),
  ('H19', 'Transtorno da esclerótica e da córnea em doenças classificadas em outra parte', 'H19 Transt da esclerotica e da cornea doenc COP'),
  ('H190', 'Esclerite e episclerite em doenças classificadas em outra parte', 'H19.0 Esclerite e episclerite em doenc COP'),
  ('H191', 'Ceratite e ceratoconjuntivite pelo vírus do herpes simples', 'H19.1 Ceratite ceratoconjunt virus herpes simples'),
  ('H192', 'Ceratite e ceratoconjuntivite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'H19.2 Cerat ceratoconj outr doenc infec paras COP'),
  ('H193', 'Ceratite e ceratoconjuntivite em outras doenças classificadas em outra parte', 'H19.3 Ceratite ceratoconjuntivite outr doenc COP'),
  ('H198', 'Outros transtornos de esclerótica e da córnea em doenças classificadas em outra parte', 'H19.8 Outr transt de esclerotica cornea doenc COP'),
  ('H20', 'Iridociclite', 'H20 Iridociclite'),
  ('H200', 'Iridociclite aguda e subaguda', 'H20.0 Iridociclite aguda e subaguda'),
  ('H201', 'Iridociclite crônica', 'H20.1 Iridociclite cronica'),
  ('H202', 'Iridociclite induzida pelo cristalino', 'H20.2 Iridociclite induz p/cristalino'),
  ('H208', 'Outras iridociclites', 'H20.8 Outr iridociclites'),
  ('H209', 'Iridociclite não especificada', 'H20.9 Iridociclite NE'),
  ('H21', 'Outros transtornos da íris e do corpo ciliar', 'H21 Outr transt da iris e do corpo ciliar'),
  ('H210', 'Hifema', 'H21.0 Hifema'),
  ('H211', 'Outros transtornos vasculares da íris e do corpo ciliar', 'H21.1 Outr transt vasculares iris e corpo ciliar'),
  ('H212', 'Degenerações da íris e do corpo ciliar', 'H21.2 Degeneracoes da iris e do corpo ciliar'),
  ('H213', 'Cistos da íris, do corpo ciliar e da câmara anterior', 'H21.3 Cistos iris corpo ciliar e camara anterior'),
  ('H214', 'Membranas pupilares', 'H21.4 Membranas pupilares'),
  ('H215', 'Outras aderências e roturas da íris e do corpo ciliar', 'H21.5 Outr aderencias e roturas iris corpo ciliar'),
  ('H218', 'Outros transtornos especificados da íris e do corpo ciliar', 'H21.8 Outr transt espec da iris e do corpo ciliar'),
  ('H219', 'Transtorno não especificado da íris e do corpo ciliar', 'H21.9 Transt NE da iris e do corpo ciliar'),
  ('H22', 'Transtornos da íris e do corpo ciliar em doenças classificadas em outra parte', 'H22 Transt da iris e do corpo ciliar doenc COP'),
  ('H220', 'Iridociclite em doenças infecciosas e parasitárias classificadas em outra parte', 'H22.0 Iridociclite em doenc infecc e parasit COP'),
  ('H221', 'Iridociclite em outras doenças classificadas em outra parte', 'H22.1 Iridociclite em outr doenc COP'),
  ('H228', 'Outros transtornos da íris e do corpo ciliar em doenças classificadas em outra parte', 'H22.8 Outr transt da iris e corpo ciliar doenc COP'),
  ('H25', 'Catarata senil', 'H25 Catarata senil'),
  ('H250', 'Catarata senil incipiente', 'H25.0 Catarata senil incipiente'),
  ('H251', 'Catarata senil nuclear', 'H25.1 Catarata senil nuclear'),
  ('H252', 'Catarata senil tipo Morgagni', 'H25.2 Catarata senil tipo Morgagni'),
  ('H258', 'Outras cataratas senis', 'H25.8 Outr cataratas senis'),
  ('H259', 'Catarata senil não especificada', 'H25.9 Catarata senil NE'),
  ('H26', 'Outras cataratas', 'H26 Outr cataratas'),
  ('H260', 'Catarata infantil, juvenil e pré-senil', 'H26.0 Catarata infantil juvenil e pre-senil'),
  ('H261', 'Catarata traumática', 'H26.1 Catarata traum'),
  ('H262', 'Catarata complicada', 'H26.2 Catarata complicada'),
  ('H263', 'Catarata induzida por drogas', 'H26.3 Catarata induz p/drogas'),
  ('H264', 'Pós-catarata', 'H26.4 Pos-catarata'),
  ('H268', 'Outras cataratas especificadas', 'H26.8 Outr cataratas espec'),
  ('H269', 'Catarata não especificada', 'H26.9 Catarata NE'),
  ('H27', 'Outros transtornos do cristalino', 'H27 Outr transt do cristalino'),
  ('H270', 'Afacia', 'H27.0 Afacia'),
  ('H271', 'Deslocamento do cristalino', 'H27.1 Deslocamento do cristalino'),
  ('H278', 'Outros transtornos especificados do cristalino', 'H27.8 Outr transt espec do cristalino'),
  ('H279', 'Transtorno não especificado do cristalino', 'H27.9 Transt NE do cristalino'),
  ('H28', 'Catarata e outros transtornos do cristalino em doenças classificadas em outra parte', 'H28 Catarata e outr transt cristalino doenc COP'),
  ('H280', 'Catarata diabética', 'H28.0 Catarata diabetica'),
  ('H281', 'Catarata em outras doenças endócrinas, nutricionais e metabólicas', 'H28.1 Catarata outr doenc endocr nutric e metabol'),
  ('H282', 'Catarata em outras doenças classificadas em outra parte', 'H28.2 Catarata em outr doenc COP'),
  ('H288', 'Outros transtorno do cristalino em doenças classificadas em outra parte', 'H28.8 Outr transt do cristalino em doenc COP'),
  ('H30', 'Inflamação coriorretiniana', 'H30 Inflam coriorretiniana'),
  ('H300', 'Inflamação coriorretiniana focal', 'H30.0 Inflam coriorretiniana focal'),
  ('H301', 'Inflamação corrorretiniana disseminada', 'H30.1 Inflam corrorretiniana disseminada'),
  ('H302', 'Ciclite posterior', 'H30.2 Ciclite posterior'),
  ('H308', 'Outras inflamações coriorretinianas', 'H30.8 Outr inflam coriorretinianas'),
  ('H309', 'Inflamação não especificada da coróide e da retina', 'H30.9 Inflam NE da coroide e da retina'),
  ('H31', 'Outros transtornos da coróide', 'H31 Outr transt da coroide'),
  ('H310', 'Cicatrizes coriorretinianas', 'H31.0 Cicatrizes coriorretinianas'),
  ('H311', 'Degeneração da coróide', 'H31.1 Degeneracao da coroide'),
  ('H312', 'Distrofia hereditária da coróide', 'H31.2 Distrofia hereditaria da coroide'),
  ('H313', 'Hemorragia e rotura da coróide', 'H31.3 Hemorragia e rotura da coroide'),
  ('H314', 'Descolamento da coróide', 'H31.4 Descolamento da coroide'),
  ('H318', 'Outros transtornos especificados da coróide', 'H31.8 Outr transt espec da coroide'),
  ('H319', 'Transtorno não especificado da coróide', 'H31.9 Transt NE da coroide'),
  ('H32', 'Transtornos coriorretinianos em doenças classificadas em outra parte', 'H32 Transt coriorretinianos em doenc COP'),
  ('H320', 'Inflamação coriorretiniana em doenças infecciosas e parasitárias classificadas em outra parte', 'H32.0 Inflam coriorretin doenc infecc parasit COP'),
  ('H328', 'Outros transtornos coriorretinianos em doenças classificadas em outra parte', 'H32.8 Outr transt coriorretinianos em doenc COP'),
  ('H33', 'Descolamentos e defeitos da retina', 'H33 Descolamentos e defeitos da retina'),
  ('H330', 'Descolamento da retina com defeito retiniano', 'H33.0 Descolamento da retina c/defeito retiniano'),
  ('H331', 'Retinosquise e cistos da retina', 'H33.1 Retinosquise e cistos da retina'),
  ('H332', 'Descolamento seroso da retina', 'H33.2 Descolamento seroso da retina'),
  ('H333', 'Defeitos da retina sem descolamento', 'H33.3 Defeitos da retina s/descolamento'),
  ('H334', 'Descolamento da retina por tração', 'H33.4 Descolamento da retina p/tracao'),
  ('H335', 'Outros descolamentos da retina', 'H33.5 Outr descolamentos da retina'),
  ('H34', 'Oclusões vasculares da retina', 'H34 Oclusoes vasculares da retina'),
  ('H340', 'Oclusão arterial retiniana transitória', 'H34.0 Oclusao arterial retiniana transitoria'),
  ('H341', 'Oclusão da artéria retiniana central', 'H34.1 Oclusao da arteria retiniana central'),
  ('H342', 'Outras oclusões da artéria retiniana', 'H34.2 Outr oclusoes da arteria retiniana'),
  ('H348', 'Outras oclusões vasculares retinianas', 'H34.8 Outr oclusoes vasculares retinianas'),
  ('H349', 'Oclusão vascular retiniana não especificada', 'H34.9 Oclusao vascular retiniana NE'),
  ('H35', 'Outros transtornos da retina', 'H35 Outr transt da retina'),
  ('H350', 'Retinopatias de fundo e alterações vasculares da retina', 'H35.0 Retinopatias de fundo alteracoes vasc retina'),
  ('H351', 'Retinopatia da prematuridade', 'H35.1 Retinopatia da prematuridade'),
  ('H352', 'Outras retinopatias proliferativas', 'H35.2 Outr retinopatias proliferativas'),
  ('H353', 'Degeneração da mácula e do pólo posterior', 'H35.3 Degeneracao da macula e do polo posterior'),
  ('H354', 'Degenerações periféricas da retina', 'H35.4 Degeneracoes perifericas da retina'),
  ('H355', 'Distrofias hereditárias da retina', 'H35.5 Distrofias hereditarias da retina'),
  ('H356', 'Hemorragia retiniana', 'H35.6 Hemorragia retiniana'),
  ('H357', 'Separação das camadas da retina', 'H35.7 Separacao das camadas da retina'),
  ('H358', 'Outros transtornos especificados da retina', 'H35.8 Outr transt espec da retina'),
  ('H359', 'Transtorno da retina não especificado', 'H35.9 Transt da retina NE'),
  ('H36', 'Transtornos da retina em doenças classificadas em outra parte', 'H36 Transt da retina em doenc COP'),
  ('H360', 'Retinopatia diabética', 'H36.0 Retinopatia diabetica'),
  ('H368', 'Outros transtornos retinianos em doenças classificadas em outra parte', 'H36.8 Outr transt retinianos em doenc COP'),
  ('H40', 'Glaucoma', 'H40 Glaucoma'),
  ('H400', 'Suspeita de glaucoma', 'H40.0 Suspeita de glaucoma'),
  ('H401', 'Glaucoma primário de ângulo aberto', 'H40.1 Glaucoma prim de angulo aberto'),
  ('H402', 'Glaucoma primário de ângulo fechado', 'H40.2 Glaucoma prim de angulo fechado'),
  ('H403', 'Glaucoma secundário a traumatismo ocular', 'H40.3 Glaucoma secund a traum ocular'),
  ('H404', 'Glaucoma secundário a inflamação ocular', 'H40.4 Glaucoma secund a inflam ocular'),
  ('H405', 'Glaucoma secundário a outros transtornos do olho', 'H40.5 Glaucoma secund a outr transt do olho'),
  ('H406', 'Glaucoma secundário a drogas', 'H40.6 Glaucoma secund a drogas'),
  ('H408', 'Outro glaucoma', 'H40.8 Outr glaucoma'),
  ('H409', 'Glaucoma não especificado', 'H40.9 Glaucoma NE'),
  ('H42', 'Glaucoma em doenças classificadas em outra parte', 'H42 Glaucoma em doenc COP'),
  ('H420', 'Glaucoma em doenças endócrinas, nutricionais e metabólicas classificadas em outra parte', 'H42.0 Glaucoma em doenc endocr nutric e metab COP'),
  ('H428', 'Glaucoma em outras doenças classificadas em outra parte', 'H42.8 Glaucoma em outr doenc COP'),
  ('H43', 'Transtornos do humor vítreo', 'H43 Transt do humor vitreo'),
  ('H430', 'Prolapso do humor vítreo', 'H43.0 Prolapso do humor vitreo'),
  ('H431', 'Hemorragia do humor vítreo', 'H43.1 Hemorragia do humor vitreo'),
  ('H432', 'Depósitos cristalinos no humor vítreo', 'H43.2 Depositos cristalinos no humor vitreo'),
  ('H433', 'Outras opacidades do vítreo', 'H43.3 Outr opacidades do vitreo'),
  ('H438', 'Outros transtornos do humor vítreo', 'H43.8 Outr transt do humor vitreo'),
  ('H439', 'Transtorno não especificado do humor vítreo', 'H43.9 Transt NE do humor vitreo'),
  ('H44', 'Transtornos do globo ocular', 'H44 Transt do globo ocular'),
  ('H440', 'Endoftalmite purulenta', 'H44.0 Endoftalmite purulenta'),
  ('H441', 'Outras endoftalmites', 'H44.1 Outr endoftalmites'),
  ('H442', 'Miopia degenerativa', 'H44.2 Miopia degenerativa'),
  ('H443', 'Outros transtornos degenerativos do globo ocular', 'H44.3 Outr transt degenerativos do globo ocular'),
  ('H444', 'Hipotonia do olho', 'H44.4 Hipotonia do olho'),
  ('H445', 'Afecções degenerativas do globo ocular', 'H44.5 Afeccoes degenerativas do globo ocular'),
  ('H446', 'Corpo estranho retido (antigo) intra-ocular de natureza magnética', 'H44.6 Corpo estranho retido intra-ocular nat magn'),
  ('H447', 'Corpo estranho retido (antigo) intra-ocular de natureza não-magnética', 'H44.7 Corpo estranho ret intra-ocular nat nao-magn'),
  ('H448', 'Outros transtornos do globo ocular', 'H44.8 Outr transt do globo ocular'),
  ('H449', 'Transtorno não especificado do globo ocular', 'H44.9 Transt NE do globo ocular'),
  ('H45', 'Transtornos do humor vítreo e do globo ocular em doenças classificadas em outra parte', 'H45 Transt humor vitreo e globo ocular doenc COP'),
  ('H450', 'Hemorragia vítrea em doenças classificadas em outra parte', 'H45.0 Hemorragia vitrea em doenc COP'),
  ('H451', 'Endoftalmite em doenças classificadas em outra parte', 'H45.1 Endoftalmite em doenc COP'),
  ('H458', 'Outros transtornos do humor vítreo e do globo ocular em doenças classificadas em outra parte', 'H45.8 Outr transt humor vitr glob ocular doenc COP'),
  ('H46', 'Neurite óptica', 'H46 Neurite optica'),
  ('H46', 'Neurite óptica', 'H46 Neurite optica'),
  ('H47', 'Outros transtornos do nervo óptico e das vias ópticas', 'H47 Outr transt do nervo optico e vias opticas'),
  ('H470', 'Transtornos do nervo óptico não classificados em outra parte', 'H47.0 Transt do nervo optico NCOP'),
  ('H471', 'Papiledema não especificado', 'H47.1 Papiledema NE'),
  ('H472', 'Atrofia óptica', 'H47.2 Atrofia optica'),
  ('H473', 'Outros transtornos do disco óptico', 'H47.3 Outr transt do disco optico'),
  ('H474', 'Transtornos do quiasma óptico', 'H47.4 Transt do quiasma optico'),
  ('H475', 'Transtornos de outras vias ópticas', 'H47.5 Transt de outr vias opticas'),
  ('H476', 'Transtornos do córtex visual', 'H47.6 Transt do cortex visual'),
  ('H477', 'Transtornos não especificados das vias ópticas', 'H47.7 Transt NE das vias opticas'),
  ('H48', 'Transtornos do nervo óptico (segundo par) e das vias ópticas em doenças classificadas em outra parte', 'H48 Transt nervo optico e vias opticas doenc COP'),
  ('H480', 'Atrofia óptica em doenças classificadas em outra parte', 'H48.0 Atrofia optica em doenc COP'),
  ('H481', 'Neurite retrobulbar em doenças classificadas em outra parte', 'H48.1 Neurite retrobulbar em doenc COP'),
  ('H488', 'Outros transtornos do nervo óptico e das vias ópticas em doenças classificadas em outra parte', 'H48.8 Outr transt nervo optic vias optic doenc COP'),
  ('H49', 'Estrabismo paralítico', 'H49 Estrabismo paralitico'),
  ('H490', 'Paralisia do terceiro par (oculomotor)', 'H49.0 Paralisia do terceiro par'),
  ('H491', 'Paralisia do quarto par (troclear)', 'H49.1 Paralisia do quarto par'),
  ('H492', 'Paralisia do sexto par (abducente)', 'H49.2 Paralisia do sexto par'),
  ('H493', 'Oftalmoplegia total (externa)', 'H49.3 Oftalmoplegia total'),
  ('H494', 'Oftalmoplegia externa progressiva', 'H49.4 Oftalmoplegia externa progressiva'),
  ('H498', 'Outros estrabismos paralíticos', 'H49.8 Outr estrabismos paraliticos'),
  ('H499', 'Estrabismo paralítico não especificado', 'H49.9 Estrabismo paralitico NE'),
  ('H50', 'Outros estrabismos', 'H50 Outr estrabismos'),
  ('H500', 'Estrabismo convergente concomitante', 'H50.0 Estrabismo convergente concomitante'),
  ('H501', 'Estrabismo divergente concomitante', 'H50.1 Estrabismo divergente concomitante'),
  ('H502', 'Estrabismo vertical', 'H50.2 Estrabismo vertical'),
  ('H503', 'Heterotropia intermitente', 'H50.3 Heterotropia intermitente'),
  ('H504', 'Outras heterotropias e as não especificadas', 'H50.4 Outr heterotropias e as NE'),
  ('H505', 'Heteroforia', 'H50.5 Heteroforia'),
  ('H506', 'Estrabismo mecânico', 'H50.6 Estrabismo mecanico'),
  ('H508', 'Outros estrabismos especificados', 'H50.8 Outr estrabismos espec'),
  ('H509', 'Estrabismo não especificado', 'H50.9 Estrabismo NE'),
  ('H51', 'Outros transtornos do movimento binocular', 'H51 Outr transt do movimento binocular'),
  ('H510', 'Paralisia do olhar conjugado', 'H51.0 Paralisia do olhar conjugado'),
  ('H511', 'Insuficiência ou excesso de convergência', 'H51.1 Insuf ou excesso de convergencia'),
  ('H512', 'Oftalmoplegia internuclear', 'H51.2 Oftalmoplegia internuclear'),
  ('H518', 'Outros transtornos especificados do movimento binocular', 'H51.8 Outr transt espec do movimento binocular'),
  ('H519', 'Transtorno não especificado do movimento binocular', 'H51.9 Transt NE do movimento binocular'),
  ('H52', 'Transtornos da refração e da acomodação', 'H52 Transt da refracao e da acomodacao'),
  ('H520', 'Hipermetropia', 'H52.0 Hipermetropia'),
  ('H521', 'Miopia', 'H52.1 Miopia'),
  ('H522', 'Astigmatismo', 'H52.2 Astigmatismo'),
  ('H523', 'Anisometropia e aniseiconia', 'H52.3 Anisometropia e aniseiconia'),
  ('H524', 'Presbiopia', 'H52.4 Presbiopia'),
  ('H525', 'Transtornos da acomodação', 'H52.5 Transt da acomodacao'),
  ('H526', 'Outros transtornos da refração', 'H52.6 Outr transt da refracao'),
  ('H527', 'Transtorno não especificado da refração', 'H52.7 Transt NE da refracao'),
  ('H53', 'Distúrbios visuais', 'H53 Disturbios visuais'),
  ('H530', 'Ambliopia por anopsia', 'H53.0 Ambliopia p/anopsia'),
  ('H531', 'Distúrbios visuais subjetivos', 'H53.1 Disturbios visuais subjetivos'),
  ('H532', 'Diplopia', 'H53.2 Diplopia'),
  ('H533', 'Outros transtornos da visão binocular', 'H53.3 Outr transt da visao binocular'),
  ('H534', 'Defeitos do campo visual', 'H53.4 Defeitos do campo visual'),
  ('H535', 'Deficiências da visão cromática', 'H53.5 Defic da visao cromatica'),
  ('H536', 'Cegueira noturna', 'H53.6 Cegueira noturna'),
  ('H538', 'Outros distúrbios visuais', 'H53.8 Outr disturbios visuais'),
  ('H539', 'Distúrbio visual não especificado', 'H53.9 Disturbio visual NE'),
  ('H54', 'Cegueira e visão subnormal', 'H54 Cegueira e visao subnormal'),
  ('H540', 'Cegueira, ambos os olhos', 'H54.0 Cegueira ambos os olhos'),
  ('H541', 'Cegueira em um olho e visão subnormal em outro', 'H54.1 Cegueira um olho e visao subnormal em outr'),
  ('H542', 'Visão subnormal de ambos os olhos', 'H54.2 Visao subnormal de ambos os olhos'),
  ('H543', 'Perda não qualificada da visão em ambos os olhos', 'H54.3 Perda nao qualificada da visao ambos olhos'),
  ('H544', 'Cegueira em um olho', 'H54.4 Cegueira em um olho'),
  ('H545', 'Visão subnormal em um olho', 'H54.5 Visao subnormal em um olho'),
  ('H546', 'Perda não qualificada da visão em um olho', 'H54.6 Perda nao qualificada da visao em um olho'),
  ('H547', 'Perda não especificada da visão', 'H54.7 Perda NE da visao'),
  ('H55', 'Nistagmo e outros movimentos irregulares do olho', 'H55 Nistagmo e outr movimentos irregulares olho'),
  ('H55', 'Nistagmo e outros movimentos irregulares do olho', 'H55 Nistagmo e outr movimentos irregulares olho'),
  ('H57', 'Outros transtornos do olho e anexos', 'H57 Outr transt do olho e anexos'),
  ('H570', 'Anomalias da função pupilar', 'H57.0 Anomalias da funcao pupilar'),
  ('H571', 'Dor ocular', 'H57.1 Dor ocular'),
  ('H578', 'Outros transtornos especificados do olho e anexos', 'H57.8 Outr transt espec do olho e anexos'),
  ('H579', 'Transtorno não especificado do olho e anexos', 'H57.9 Transt NE do olho e anexos'),
  ('H58', 'Outros transtornos do olho e anexos em doenças classificadas em outra parte', 'H58 Outr transt do olho e anexos em doenc COP'),
  ('H580', 'Anomalias da função pupilar em doenças classificadas em outra parte', 'H58.0 Anomalias da funcao pupilar em doenc COP'),
  ('H581', 'Distúrbios visuais em doenças classificadas em outra parte', 'H58.1 Disturbios visuais em doenc COP'),
  ('H588', 'Outros transtornos especificados do olho e anexos em doenças classificadas em outra parte', 'H58.8 Outr transt espec do olho e anexos doenc COP'),
  ('H59', 'Transtornos do olho e anexos pós-procedimento não classificados em outra parte', 'H59 Transt do olho e anexos pos-proced NCOP'),
  ('H590', 'Ceropatia (bolhosa afácica) subseqüente a cirurgia de catarata', 'H59.0 Ceropatia subseq a cirurgia de catarata'),
  ('H598', 'Outros transtornos do olho e anexos pós-procedimentos', 'H59.8 Outr transt do olho e anexos pos-proced'),
  ('H599', 'Transtorno não especificado do olho e anexos pós-procedimento', 'H59.9 Transt NE do olho e anexos pos-proced'),
  ('H60', 'Otite externa', 'H60 Otite externa'),
  ('H600', 'Abscesso do ouvido externo', 'H60.0 Abscesso do ouvido externo'),
  ('H601', 'Celulite do ouvido externo', 'H60.1 Celulite do ouvido externo'),
  ('H602', 'Otite externa maligna', 'H60.2 Otite externa maligna'),
  ('H603', 'Outras otites externas infecciosas', 'H60.3 Outr otites externas infecc'),
  ('H604', 'Colesteatoma do ouvido externo', 'H60.4 Colesteatoma do ouvido externo'),
  ('H605', 'Otite externa aguda não-infecciosa', 'H60.5 Otite externa aguda nao-infecc'),
  ('H608', 'Outras otites externas', 'H60.8 Outr otites externas'),
  ('H609', 'Otite externa não especificada', 'H60.9 Otite externa NE'),
  ('H61', 'Outros transtornos do ouvido externo', 'H61 Outr transt do ouvido externo'),
  ('H610', 'Pericondrite do pavilhão da orelha', 'H61.0 Pericondrite do pavilhao da orelha'),
  ('H611', 'Transtornos não-infecciosos do pavilhão da orelha', 'H61.1 Transt nao-infecc do pavilhao da orelha'),
  ('H612', 'Cerume impactado', 'H61.2 Cerume impactado'),
  ('H613', 'Estenose adquirida do conduto auditivo externo', 'H61.3 Estenose adquir do conduto auditivo ext'),
  ('H618', 'Outros transtornos especificados do ouvido externo', 'H61.8 Outr transt espec do ouvido externo'),
  ('H619', 'Transtorno não especificado do ouvido externo', 'H61.9 Transt NE do ouvido externo'),
  ('H62', 'Transtornos do ouvido externo em doenças classificadas em outra parte', 'H62 Transt do ouvido externo em doenc COP'),
  ('H620', 'Otite externa em doenças bacterianas classificadas em outra parte', 'H62.0 Otite externa em doenc bacter COP'),
  ('H621', 'Otite externa em doenças virais classificadas em outra parte', 'H62.1 Otite externa em doenc virais COP'),
  ('H622', 'Otite externa em micoses', 'H62.2 Otite externa em micoses'),
  ('H623', 'Otite externa em outras doenças infecciosas e parasitárias classificadas em outra parte', 'H62.3 Otite externa outr doenc infecc parasit COP'),
  ('H624', 'Otite externa em outras doenças classificadas em outra parte', 'H62.4 Otite externa em outr doenc COP'),
  ('H628', 'Outros transtornos do ouvido externo em doenças classificadas em outra parte', 'H62.8 Outr transt do ouvido externo em doenc COP'),
  ('H65', 'Otite média não-supurativa', 'H65 Otite media nao-supurativa'),
  ('H650', 'Otite média aguda serosa', 'H65.0 Otite media aguda serosa'),
  ('H651', 'Outras otites médias agudas não-supurativas', 'H65.1 Outr otites medias agudas nao-supurativas'),
  ('H652', 'Otite média serosa crônica', 'H65.2 Otite media serosa cronica'),
  ('H653', 'Otite média mucóide crônica', 'H65.3 Otite media mucoide cronica'),
  ('H654', 'Outras otites médias crônicas não-supurativas', 'H65.4 Outr otites medias cronicas nao-supurativas'),
  ('H659', 'Otite média não-supurativa, não especificada', 'H65.9 Otite media nao-supurativa NE'),
  ('H66', 'Otite média supurativa e as não especificadas', 'H66 Otite media supurativa e as NE'),
  ('H660', 'Otite média aguda supurativa', 'H66.0 Otite media aguda supurativa'),
  ('H661', 'Otite média tubotimpânica supurativa crônica', 'H66.1 Otite media tubotimpanica supurativa cronica'),
  ('H662', 'Otite média ático-antral supurativa crônica', 'H66.2 Otite media atico-antral supurativa cronica'),
  ('H663', 'Outras otites médias supurativas crônicas', 'H66.3 Outr otites medias supurativas cronicas'),
  ('H664', 'Otite média supurativa não especificada', 'H66.4 Otite media supurativa NE'),
  ('H669', 'Otite média não especificada', 'H66.9 Otite media NE'),
  ('H67', 'Otite média em doenças classificadas em outra parte', 'H67 Otite media em doenc COP'),
  ('H670', 'Otite média em doenças bacterianas classificadas em outra parte', 'H67.0 Otite media em doenc bacter COP'),
  ('H671', 'Otite média em doenças virais classificadas em outra parte', 'H67.1 Otite media em doenc virais COP'),
  ('H678', 'Otite média em outras doenças classificadas em outra parte', 'H67.8 Otite media em outr doenc COP'),
  ('H68', 'Salpingite e obstrução da trompa de Eustáquio', 'H68 Salpingite e obstrucao trompa de Eustaquio'),
  ('H680', 'Salpingite da trompa de Eustáquio', 'H68.0 Salpingite da trompa de Eustaquio'),
  ('H681', 'Obstrução da trompa de Eustáquio', 'H68.1 Obstrucao da trompa de Eustaquio'),
  ('H69', 'Outros transtornos da trompa de Eustáquio', 'H69 Outr transt da trompa de Eustaquio'),
  ('H690', 'Trompa de Eustáquio aberta (patente) (patulosa)', 'H69.0 Trompa de Eustaquio aberta'),
  ('H698', 'Outros transtornos especificados da trompa de Eustáquio', 'H69.8 Outr transt espec da trompa de Eustaquio'),
  ('H699', 'Transtorno não especificado da trompa de Eustáquio', 'H69.9 Transt NE da trompa de Eustaquio'),
  ('H70', 'Mastoidite e afecções correlatas', 'H70 Mastoidite e afeccoes correlatas'),
  ('H700', 'Mastoidite aguda', 'H70.0 Mastoidite aguda'),
  ('H701', 'Mastoidite crônica', 'H70.1 Mastoidite cronica'),
  ('H702', 'Petrosite', 'H70.2 Petrosite'),
  ('H708', 'Outras mastoidites e afecções relacionadas com a mastoidite', 'H70.8 Outr mastoidites e afeccoes relac mastoidite'),
  ('H709', 'Mastoidite não especificada', 'H70.9 Mastoidite NE'),
  ('H71', 'Colesteatoma do ouvido médio', 'H71 Colesteatoma do ouvido medio'),
  ('H71', 'Colesteatoma do ouvido médio', 'H71 Colesteatoma do ouvido medio'),
  ('H72', 'Perfuração da membrana do tímpano', 'H72 Perfuracao da membrana do timpano'),
  ('H720', 'Perfuração central da membrana do tímpano', 'H72.0 Perfuracao central da membrana do timpano'),
  ('H721', 'Perfuração ática da membrana do tímpano', 'H72.1 Perfuracao atica da membrana do timpano'),
  ('H722', 'Outras perfurações marginais da membrana do tímpano', 'H72.2 Outr perfuracoes marginais membrana timpano'),
  ('H728', 'Outras perfurações da membrana do tímpano', 'H72.8 Outr perfuracoes da membrana do timpano'),
  ('H729', 'Perfuração não especificada da membrana do tímpano', 'H72.9 Perfuracao NE da membrana do timpano'),
  ('H73', 'Outros transtornos da membrana do tímpano', 'H73 Outr transt da membrana do timpano'),
  ('H730', 'Miringite aguda', 'H73.0 Miringite aguda'),
  ('H731', 'Miringite crônica', 'H73.1 Miringite cronica'),
  ('H738', 'Outros transtornos especificados da membrana do tímpano', 'H73.8 Outr transt espec da membrana do timpano'),
  ('H739', 'Transtorno não especificado da membrana do tímpano', 'H73.9 Transt NE da membrana do timpano'),
  ('H74', 'Outros transtornos do ouvido médio e da mastóide', 'H74 Outr transt do ouvido medio e da mastoide'),
  ('H740', 'Timpanosclerose', 'H74.0 Timpanosclerose'),
  ('H741', 'Doença adesiva do ouvido médio', 'H74.1 Doenc adesiva do ouvido medio'),
  ('H742', 'Descontinuidade e deslocamento dos ossículos do ouvido', 'H74.2 Descontinuidade e desloc ossiculos ouvido'),
  ('H743', 'Outras anormalidades adquiridas dos ossículos do ouvido', 'H74.3 Outr anorm adquir ossiculos ouvido'),
  ('H744', 'Pólipo do ouvido médio', 'H74.4 Polipo do ouvido medio'),
  ('H748', 'Outros transtornos especificados do ouvido médio e da mastóide', 'H74.8 Outr transt espec do ouvido medio e mastoide'),
  ('H749', 'Transtorno não especificado do ouvido médio e da mastóide', 'H74.9 Transt NE do ouvido medio e da mastoide'),
  ('H75', 'Outros transtornos do ouvido médio e da mastóide em doenças classificadas em outra parte', 'H75 Outr transt ouvido medio mastoide doenc COP'),
  ('H750', 'Mastoidite em doenças infecciosas e parasitárias classificadas em outra parte', 'H75.0 Mastoidite em doenc infecc e parasit COP'),
  ('H758', 'Outros transtornos especificados do ouvido médio e da mastóide em doenças classificadas em outra parte', 'H75.8 Outr transt espec ouv med mastoide doenc COP'),
  ('H80', 'Otosclerose', 'H80 Otosclerose'),
  ('H800', 'Otosclerose que compromete a janela oval, não-obliterante', 'H80.0 Otosclerose q comprom janela oval nao-oblit'),
  ('H801', 'Otosclerose que compromete a janela oval, obliterante', 'H80.1 Otosclerose q comprom janela oval oblit'),
  ('H802', 'Otosclerose da cóclea', 'H80.2 Otosclerose da coclea'),
  ('H808', 'Outras otoscleroses', 'H80.8 Outr otoscleroses'),
  ('H809', 'Otosclerose não especificada', 'H80.9 Otosclerose NE'),
  ('H81', 'Transtornos da função vestibular', 'H81 Transt da funcao vestibular'),
  ('H810', 'Doença de Ménière', 'H81.0 Doenc de Meniere'),
  ('H811', 'Vertigem paroxística benigna', 'H81.1 Vertigem paroxistica benigna'),
  ('H812', 'Neuronite vestibular', 'H81.2 Neuronite vestibular'),
  ('H813', 'Outras vertigens periféricas', 'H81.3 Outr vertigens perifericas'),
  ('H814', 'Vertigem de origem central', 'H81.4 Vertigem orig central'),
  ('H818', 'Outros transtornos da função vestibular', 'H81.8 Outr transt da funcao vestibular'),
  ('H819', 'Transtornos não especificados da função vestibular', 'H81.9 Transt NE da funcao vestibular'),
  ('H82', 'Síndromes vertiginosas em doenças classificadas em outra parte', 'H82 Sindr vertiginosas em doenc COP'),
  ('H82', 'Síndromes vertiginosas em doenças classificadas em outra parte', 'H82 Sindr vertiginosas em doenc COP'),
  ('H83', 'Outros transtornos do ouvido interno', 'H83 Outr transt do ouvido interno'),
  ('H830', 'Labirintite', 'H83.0 Labirintite'),
  ('H831', 'Fístula do labirinto', 'H83.1 Fistula do labirinto'),
  ('H832', 'Disfunção do labirinto', 'H83.2 Disfuncao do labirinto'),
  ('H833', 'Efeitos do ruído sobre o ouvido interno', 'H83.3 Efeitos do ruido sobre o ouvido interno'),
  ('H838', 'Outros transtornos especificados do ouvido interno', 'H83.8 Outr transt espec do ouvido interno'),
  ('H839', 'Transtorno não especificado do ouvido interno', 'H83.9 Transt NE do ouvido interno'),
  ('H90', 'Perda de audição por transtorno de condução e/ou neuro-sensorial', 'H90 Perda audicao transt conducao neuro-sens'),
  ('H900', 'Perda de audição bilateral devida a transtorno de condução', 'H90.0 Perda audicao bilateral dev transt conducao'),
  ('H901', 'Perda de audição unilateral por transtorno de condução, sem restrição de audição contralateral', 'H90.1 Perda aud unilat trans cond s/rest aud contr'),
  ('H902', 'Perda não especificada de audição devida a transtorno de condução', 'H90.2 Perda NE de audicao dev transt de conducao'),
  ('H903', 'Perda de audição bilateral neuro-sensorial', 'H90.3 Perda de audicao bilateral neuro-sensorial'),
  ('H904', 'Perda de audição unilateral neuro-sensorial, sem restrição de audição contralateral', 'H90.4 Perda aud unilat neuro-sens s/rest aud contr'),
  ('H905', 'Perda de audição neuro-sensorial não especificada', 'H90.5 Perda de audicao neuro-sensorial NE'),
  ('H906', 'Perda de audição bilateral mista, de condução e neuro-sensorial', 'H90.6 Perda audic bilat mista conducao neuro-sens'),
  ('H907', 'Perda de audição unilateral mista, de condução e neuro-sensorial, sem restrição de audição contralateral', 'H90.7 Perd aud uni mist cond neur s/rest aud contr'),
  ('H908', 'Perda de audição mista, de condução e neuro-sensorial, não especificada', 'H90.8 Perda audicao mista conducao e neuro-sens NE'),
  ('H91', 'Outras perdas de audição', 'H91 Outr perdas de audicao'),
  ('H910', 'Perda de audição ototóxica', 'H91.0 Perda de audicao ototoxica'),
  ('H911', 'Presbiacusia', 'H91.1 Presbiacusia'),
  ('H912', 'Perda de audição súbita idiopática', 'H91.2 Perda de audicao subita idiopatica'),
  ('H913', 'Surdo-mudez não classificada em outra parte', 'H91.3 Surdo-mudez NCOP'),
  ('H918', 'Outras perdas de audição especificadas', 'H91.8 Outr perdas de audicao espec'),
  ('H919', 'Perda não especificada de audição', 'H91.9 Perda NE de audicao'),
  ('H92', 'Otalgia e secreção auditiva', 'H92 Otalgia e secrecao auditiva'),
  ('H920', 'Otalgia', 'H92.0 Otalgia'),
  ('H921', 'Otorréia', 'H92.1 Otorreia'),
  ('H922', 'Otorragia', 'H92.2 Otorragia'),
  ('H93', 'Outros transtornos do ouvido não classificados em outra parte', 'H93 Outr transt do ouvido NCOP'),
  ('H930', 'Transtornos degenerativos e vasculares do ouvido', 'H93.0 Transt degenerativos e vasculares do ouvido'),
  ('H931', 'Tinnitus', 'H93.1 Tinnitus'),
  ('H932', 'Outras percepções auditivas anormais', 'H93.2 Outr percepcoes auditivas anormais'),
  ('H933', 'Transtornos do nervo acústico', 'H93.3 Transt do nervo acustico'),
  ('H938', 'Outros transtornos especificados do ouvido', 'H93.8 Outr transt espec do ouvido'),
  ('H939', 'Transtorno não especificado do ouvido', 'H93.9 Transt NE do ouvido'),
  ('H94', 'Outros transtornos do ouvido em doenças classificadas em outra parte', 'H94 Outr transt do ouvido em doenc COP'),
  ('H940', 'Neurite acústica em doenças infecciosas e parasitárias classificadas em outra parte', 'H94.0 Neurite acustica em doenc infecc parasit COP'),
  ('H948', 'Outros transtornos especificados do ouvido em doenças classificadas em outra parte', 'H94.8 Outr transt espec do ouvido em doenc COP'),
  ('H95', 'Transtornos do ouvido e da apófise mastóide pós-procedimentos, não classificados em outra parte', 'H95 Transt ouvido apof mastoide pos-proced NCOP'),
  ('H950', 'Colesteatoma recorrente da cavidade pós-mastoidectomia', 'H95.0 Colesteatoma recorr cavidade pos-mastoidect'),
  ('H951', 'Outros transtornos conseqüentes à mastoidectomia', 'H95.1 Outr transt consequentes a mastoidectomia'),
  ('H958', 'Outros transtornos do ouvido e da apófise mastóide pós-procedimento', 'H95.8 Outr transt ouvido apof mastoide pos-proced'),
  ('H959', 'Transtorno não especificado do ouvido e da apófise mastóide pós-procedimento', 'H95.9 Transt NE ouvido apofise mastoide pos-proced');
