INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('G00', 'Meningite bacteriana não classificada em outra parte', 'G00 Meningite bacter NCOP'),
  ('G000', 'Meningite por Haemophilus', 'G00.0 Meningite p/Haemophilus'),
  ('G001', 'Meningite pneumocócica', 'G00.1 Meningite pneumococica'),
  ('G002', 'Meningite estreptocócica', 'G00.2 Meningite estreptococica'),
  ('G003', 'Meningite estafilocócica', 'G00.3 Meningite estafilococica'),
  ('G008', 'Outras meningites bacterianas', 'G00.8 Outr meningites bacter'),
  ('G009', 'Meningite bacteriana não especificada', 'G00.9 Meningite bacter NE'),
  ('G01', 'Meningite em doenças bacterianas classificadas em outra parte', 'G01 Meningite em doenc bacter COP'),
  ('G01', 'Meningite em doenças bacterianas classificadas em outra parte', 'G01 Meningite em doenc bacter COP'),
  ('G02', 'Meningite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'G02 Meningite em outr doenc infecc e parasit COP'),
  ('G020', 'Meningite em doenças virais classificadas em outra parte', 'G02.0 Meningite em doenc virais COP'),
  ('G021', 'Meningite em micoses', 'G02.1 Meningite em micoses'),
  ('G028', 'Meningite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'G02.8 Meningite em outr doenc infecc e parasit COP'),
  ('G03', 'Meningite devida a outras causas e a causas não especificadas', 'G03 Meningite dev outr causas e a causas NE'),
  ('G030', 'Meningite não-piogênica', 'G03.0 Meningite nao-piogenica'),
  ('G031', 'Meningite crônica', 'G03.1 Meningite cronica'),
  ('G032', 'Meningite recorrente benigna (Mollaret)', 'G03.2 Meningite recorrente benigna'),
  ('G038', 'Meningite devida a outras causas especificadas', 'G03.8 Meningite dev outr causas espec'),
  ('G039', 'Meningite não especificada', 'G03.9 Meningite NE'),
  ('G04', 'Encefalite, mielite e encefalomielite', 'G04 Encefalite mielite e encefalomielite'),
  ('G040', 'Encefalite aguda disseminada', 'G04.0 Encefalite aguda disseminada'),
  ('G041', 'Paraplegia espástica tropical', 'G04.1 Paraplegia espastica tropical'),
  ('G042', 'Meningoencefalite e meningomielite bacterianas não classificadas em outra parte', 'G04.2 Meningoencefalite meningomielite bacter NCOP'),
  ('G048', 'Outras encefalites, mielites e encefalomielites', 'G04.8 Outr encefalites mielites e encefalomielites'),
  ('G049', 'Encefalite, mielite e encefalomielite não especificada', 'G04.9 Encefalite mielite e encefalomielite NE'),
  ('G05', 'Encefalite, mielite e encefalomielite em doenças classificadas em outra parte', 'G05 Encefalite mielite encefalomielite doenc COP'),
  ('G050', 'Encefalite, mielite e encefalomielite em doenças bacterianas classificadas em outra parte', 'G05.0 Encefal mielit encefalomiel doenc bacter COP'),
  ('G051', 'Encefalite, mielite e encefalomielite em doenças virais classificadas em outra parte', 'G05.1 Encefal mielit encefalomiel doenc virais COP'),
  ('G052', 'Encefalite, mielite e encefalomielite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'G05.2 Encef miel encefal out doenc infec paras COP'),
  ('G058', 'Encefalite, mielite e encefalomielite em outras doenças classificadas em outra parte', 'G05.8 Encefal mielit encefalomiel outr doenc COP'),
  ('G06', 'Abscesso e granuloma intracranianos e intra-raquidianos', 'G06 Abscesso granuloma intracran intra-raquid'),
  ('G060', 'Abscesso e granuloma intracranianos', 'G06.0 Abscesso e granuloma intracranianos'),
  ('G061', 'Abscesso e granuloma intra-raquidianos', 'G06.1 Abscesso e granuloma intra-raquidianos'),
  ('G062', 'Abscesso extradural e subdural não especificados', 'G06.2 Abscesso extradural e subdural NE'),
  ('G07', 'Abscesso e granuloma intracranianos e intraspinais em doenças classificadas em outra parte', 'G07 Abscess granul intracran intraspin doenc COP'),
  ('G07', 'Abscesso e granuloma intracranianos e intraspinais em doenças classificadas em outra parte', 'G07 Abscess granul intracran intraspin doenc COP'),
  ('G08', 'Flebite e tromboflebite intracranianas e intra-raquidianas', 'G08 Flebite tromboflebite intracran intra-raquid'),
  ('G08', 'Flebite e tromboflebite intracranianas e intra-raquidianas', 'G08 Flebite tromboflebite intracran intra-raquid'),
  ('G09', 'Seqüelas de doenças inflamatórias do sistema nervoso central', 'G09 Sequelas doenc inflam sist nerv centr'),
  ('G09', 'Seqüelas de doenças inflamatórias do sistema nervoso central', 'G09 Sequelas doenc inflam sist nerv centr'),
  ('G10', 'Doença de Huntington', 'G10 Doenc de Huntington'),
  ('G10', 'Doença de Huntington', 'G10 Doenc de Huntington'),
  ('G11', 'Ataxia hereditária', 'G11 Ataxia hereditaria'),
  ('G110', 'Ataxia congênita não-progressiva', 'G11.0 Ataxia congen nao-progressiva'),
  ('G111', 'Ataxia cerebelar de início precoce', 'G11.1 Ataxia cerebelar de inicio precoce'),
  ('G112', 'Ataxia cerebelar de início tardio', 'G11.2 Ataxia cerebelar de inicio tard'),
  ('G113', 'Ataxia cerebelar com déficit na reparação do DNA', 'G11.3 Ataxia cerebelar c/deficit na reparacao DNA'),
  ('G114', 'Paraplegia espástica hereditária', 'G11.4 Paraplegia espastica hereditaria'),
  ('G118', 'Outras ataxias hereditárias', 'G11.8 Outr ataxias hereditarias'),
  ('G119', 'Ataxia hereditária não especificada', 'G11.9 Ataxia hereditaria NE'),
  ('G12', 'Atrofia muscular espinal e síndromes correlatas', 'G12 Atrofia muscular espinal e sindr correlatas'),
  ('G120', 'Atrofia muscular espinal infantil tipo I (Werdnig-Hoffman)', 'G12.0 Atrofia muscular espinal infantil tipo I'),
  ('G121', 'Outras atrofias musculares espinais hereditárias', 'G12.1 Outr atrofias musculares espinais hereditar'),
  ('G122', 'Doença do neurônio motor', 'G12.2 Doenc do neuronio motor'),
  ('G128', 'Outras atrofias musculares espinais e síndromes musculares correlatas', 'G12.8 Outr atrof muscul espinais sindr muscul corr'),
  ('G129', 'Atrofia muscular espinal não especificada', 'G12.9 Atrofia muscular espinal NE'),
  ('G13', 'Atrofias sistêmicas que afetam principalmente o sistema nervoso central em doenças classificadas em outra parte', 'G13 Atrof sist q afet sist nerv centr doen COP'),
  ('G130', 'Neuromiopatia e neuropatia paraneoplásicas', 'G13.0 Neuromiopatia e neuropatia paraneoplasicas'),
  ('G131', 'Outra atrofia sistêmica que afeta primariamente o sistema nervoso central em doenças neoplásicas', 'G13.1 Out atrof sist afet sist nerv cent doen neop'),
  ('G132', 'Atrofia sistêmica que afeta primariamente o sistema nervoso central no mixedema', 'G13.2 Atrof sist q afet prim sist nerv centr mixed'),
  ('G138', 'Atrofia sistêmica que afeta primariamente o sistema nervoso central em outras doenças classificadas em outra parte', 'G13.8 Atr sist q afet sist nerv centr out doen COP'),
  ('G20', 'Doença de Parkinson', 'G20 Doenc de Parkinson'),
  ('G20', 'Doença de Parkinson', 'G20 Doenc de Parkinson'),
  ('G21', 'Parkinsonismo secundário', 'G21 Parkinsonismo secund'),
  ('G210', 'Síndrome maligna dos neurolépticos', 'G21.0 Sindr maligna dos neurolepticos'),
  ('G211', 'Outras formas de parkinsonismo secundário induzido por drogas', 'G21.1 Outr form parkinsonismo secund induz drogas'),
  ('G212', 'Parkinsonismo secundário devido a outros agentes externos', 'G21.2 Parkinsonismo secund dev outr agentes extern'),
  ('G213', 'Parkinsonismo pós-encefalítico', 'G21.3 Parkinsonismo pos-encefalitico'),
  ('G218', 'Outras formas de parkinsonismo secundário', 'G21.8 Outr form de parkinsonismo secund'),
  ('G219', 'Parkinsonismo secundário não especificado', 'G21.9 Parkinsonismo secund NE'),
  ('G22', 'Parkinsonismo em doenças classificadas em outra parte', 'G22 Parkinsonismo em doenc COP'),
  ('G22', 'Parkinsonismo em doenças classificadas em outra parte', 'G22 Parkinsonismo em doenc COP'),
  ('G23', 'Outras doenças degenerativas dos gânglios da base', 'G23 Outr doenc degenerativas dos ganglios base'),
  ('G230', 'Doença de Hallervorden-Spatz', 'G23.0 Doenc de Hallervorden-Spatz'),
  ('G231', 'Oftalmoplegia supranuclear progressiva (Steele-Richardson-Olszewski)', 'G23.1 Oftalmoplegia supranuclear progressiva'),
  ('G232', 'Degeneração estrionígrica', 'G23.2 Degeneracao estrionigrica'),
  ('G238', 'Outras doenças degenerativas especificadas dos gânglios da base', 'G23.8 Outr doenc degenerativas espec ganglios base'),
  ('G239', 'Doença degenerativa dos gânglios da base, não especificada', 'G23.9 Doenc degenerativa dos ganglios da base NE'),
  ('G24', 'Distonia', 'G24 Distonia'),
  ('G240', 'Distonia induzida por drogas', 'G24.0 Distonia induz p/drogas'),
  ('G241', 'Distonia familiar idiopática', 'G24.1 Distonia familiar idiopatica'),
  ('G242', 'Distonia não-familiar idiopática', 'G24.2 Distonia nao-familiar idiopatica'),
  ('G243', 'Torcicolo espasmódico', 'G24.3 Torcicolo espasmodico'),
  ('G244', 'Distonia orofacial idiopática', 'G24.4 Distonia orofacial idiopatica'),
  ('G245', 'Blefaroespasmo', 'G24.5 Blefaroespasmo'),
  ('G248', 'Outras distonias', 'G24.8 Outr distonias'),
  ('G249', 'Distonia não especificada', 'G24.9 Distonia NE'),
  ('G25', 'Outras doenças extrapiramidais e transtornos dos movimentos', 'G25 Outr doenc extrapiramidais transt movimentos'),
  ('G250', 'Tremor essencial', 'G25.0 Tremor essencial'),
  ('G251', 'Tremor induzido por drogas', 'G25.1 Tremor induz p/drogas'),
  ('G252', 'Outras formas especificadas de tremor', 'G25.2 Outr form espec de tremor'),
  ('G253', 'Mioclonia', 'G25.3 Mioclonia'),
  ('G254', 'Coréia induzida por droga', 'G25.4 Coreia induz p/droga'),
  ('G255', 'Outras formas de coréia', 'G25.5 Outr form de coreia'),
  ('G256', 'Tiques induzidos por droga e outros tipos de origem orgânica', 'G25.6 Tiques induz p/droga e outr tipos orig organ'),
  ('G258', 'Outras doenças extrapiramidais e transtornos dos movimentos, especificados', 'G25.8 Outr doenc extrapiramid transt movim espec'),
  ('G259', 'Doenças extrapiramidais e transtornos dos movimentos, não especificados', 'G25.9 Doenc extrapiramidais transt movimentos NE'),
  ('G26', 'Doenças extrapiramidais e transtornos dos movimentos em doenças classificadas em outra parte', 'G26 Doenc extrapiramidais transt movim doenc COP'),
  ('G26', 'Doenças extrapiramidais e transtornos dos movimentos em doenças classificadas em outra parte', 'G26 Doenc extrapiramidais transt movim doenc COP'),
  ('G30', 'Doença de Alzheimer', 'G30 Doenc de Alzheimer'),
  ('G300', 'Doença de Alzheimer de início precoce', 'G30.0 Doenc de Alzheimer de inicio precoce'),
  ('G301', 'Doença de Alzheimer de início tardio', 'G30.1 Doenc de Alzheimer de inicio tard'),
  ('G308', 'Outras formas de doença de Alzheimer', 'G30.8 Outr form de doenc de Alzheimer'),
  ('G309', 'Doença de Alzheimer não especificada', 'G30.9 Doenc de Alzheimer NE'),
  ('G31', 'Outras doenças degenerativas do sistema nervoso não classificadas em outra parte', 'G31 Outr doenc degenerativas sist nervoso NCOP'),
  ('G310', 'Atrofia cerebral circunscrita', 'G31.0 Atrofia cerebral circunscrita'),
  ('G311', 'Degeneração cerebral senil, não classificadas em outra parte', 'G31.1 Degeneracao cerebral senil NCOP'),
  ('G312', 'Degeneração do sistema nervoso devida ao álcool', 'G31.2 Degeneracao do sist nervoso dev alcool'),
  ('G318', 'Outras doenças degenerativas especificadas do sistema nervoso', 'G31.8 Outr doenc degenerativas espec sist nervoso'),
  ('G319', 'Doença degenerativa do sistema nervoso, não especificada', 'G31.9 Doenc degenerativa do sist nervoso NE'),
  ('G32', 'Outros transtornos degenerativos do sistema nervoso em doenças classificadas em outra parte', 'G32 Outr transt degenerativ sist nerv doenc COP'),
  ('G320', 'Degeneração combinada subaguda da medula espinal em doenças classificadas em outra parte', 'G32.0 Degener comb subagud medul espinal doenc COP'),
  ('G328', 'Outros transtornos degenerativos especificados do sistema nervoso em doenças classificadas em outra parte', 'G32.8 Outr transt degener espec sist nerv doen COP'),
  ('G35', 'Esclerose múltipla', 'G35 Esclerose mult'),
  ('G35', 'Esclerose múltipla', 'G35 Esclerose mult'),
  ('G36', 'Outras desmielinizações disseminadas agudas', 'G36 Outr desmielinizacoes disseminadas agudas'),
  ('G360', 'Neuromielite óptica (doença de Devic)', 'G36.0 Neuromielite optica'),
  ('G361', 'Leucoencefalite hemorrágica aguda e subaguda (Hurst)', 'G36.1 Leucoencefalite hemorragica aguda e subaguda'),
  ('G368', 'Outras desmielinizações disseminadas agudas especificadas', 'G36.8 Outr desmielinizacoes dissem agudas espec'),
  ('G369', 'Desmielinização disseminada aguda não especificada', 'G36.9 Desmielinizacao disseminada aguda NE'),
  ('G37', 'Outras doenças desmielinizantes do sistema nervoso central', 'G37 Outr doenc desmielinizantes sist nerv centr'),
  ('G370', 'Esclerose difusa', 'G37.0 Esclerose difusa'),
  ('G371', 'Desmielinização central do corpo caloso', 'G37.1 Desmielinizacao central do corpo caloso'),
  ('G372', 'Mielinólise central da ponte', 'G37.2 Mielinolise central da ponte'),
  ('G373', 'Mielite transversa aguda em doenças desmielinizantes do sistema nervoso central', 'G37.3 Mielit trans agud doen desmiel sis nerv cent'),
  ('G374', 'Mielite subaguda necrótica', 'G37.4 Mielite subaguda necrotica'),
  ('G375', 'Esclerose concêntrica (Baló)', 'G37.5 Esclerose concentrica'),
  ('G378', 'Outras doenças desmielinizantes especificadas do sistema nervoso central', 'G37.8 Outr doenc desmiel espec sist nerv centr'),
  ('G379', 'Doença desmielinizante do sistema nervoso central, não especificada', 'G37.9 Doenc desmielinizante sist nerv central NE'),
  ('G40', 'Epilepsia', 'G40 Epilepsia'),
  ('G400', 'Epilepsia e síndromes epilépticas idiopáticas definidas por sua localização (focal) (parcial) com crises de início focal', 'G40.0 Epilep sind epil idiop def loc cris inic foc'),
  ('G401', 'Epilepsia e síndromes epilépticas sintomáticas definidas por sua localização (focal) (parcial) com crises parciais simples', 'G40.1 Epilep sind epil sint def loc cris parc simp'),
  ('G402', 'Epilepsia e síndromes epilépticas sintomáticas definidas por sua localização (focal) (parcial) com crises parciais complexas', 'G40.2 Epilep sind epil sint def loc cris parc comp'),
  ('G403', 'Epilepsia e síndromes epilépticas generalizadas idiopáticas', 'G40.3 Epilepsia e sindr epilepticas gener idiopat'),
  ('G404', 'Outras epilepsias e síndromes epilépticas generalizadas', 'G40.4 Outr epilepsias e sindr epilepticas gener'),
  ('G405', 'Síndromes epilépticas especiais', 'G40.5 Sindr epilepticas especiais'),
  ('G406', 'Crise de grande mal, não especificada (com ou sem pequeno mal)', 'G40.6 Crise de grande mal NE'),
  ('G407', 'Pequeno mal não especificado, sem crises de grande mal', 'G40.7 Pequeno mal NE s/crises de grande mal'),
  ('G408', 'Outras epilepsias', 'G40.8 Outr epilepsias'),
  ('G409', 'Epilepsia, não especificada', 'G40.9 Epilepsia NE'),
  ('G41', 'Estado de mal epiléptico', 'G41 Estado de mal epileptico'),
  ('G410', 'Estado de grande mal epiléptico', 'G41.0 Estado de grande mal epileptico'),
  ('G411', 'Estado de pequeno mal epiléptico', 'G41.1 Estado de pequeno mal epileptico'),
  ('G412', 'Estado de mal epiléptico parcial complexo', 'G41.2 Estado de mal epileptico parcial complexo'),
  ('G418', 'Outros estados de mal epiléptico', 'G41.8 Outr estados de mal epileptico'),
  ('G419', 'Estado de mal epiléptico, não especificado', 'G41.9 Estado de mal epileptico NE'),
  ('G43', 'Enxaqueca', 'G43 Enxaqueca'),
  ('G430', 'Enxaqueca sem aura (enxaqueca comum)', 'G43.0 Enxaqueca s/aura'),
  ('G431', 'Enxaqueca com aura (enxaqueca clássica)', 'G43.1 Enxaqueca c/aura'),
  ('G432', 'Estado de mal enxaquecoso', 'G43.2 Estado de mal enxaquecoso'),
  ('G433', 'Enxaqueca complicada', 'G43.3 Enxaqueca complicada'),
  ('G438', 'Outras formas de enxaqueca', 'G43.8 Outr form de enxaqueca'),
  ('G439', 'Enxaqueca, sem especificação', 'G43.9 Enxaqueca s/especificacao'),
  ('G44', 'Outras síndromes de algias cefálicas', 'G44 Outr sindr de algias cefalicas'),
  ('G440', 'Síndrome de cluster-headache', 'G44.0 Sindr de cluster-headache'),
  ('G441', 'Cefaléia vascular, não classificada em outra parte', 'G44.1 Cefaleia vascular NCOP'),
  ('G442', 'Cefaléia tensional', 'G44.2 Cefaleia tensional'),
  ('G443', 'Cefaléia crônica pós-traumática', 'G44.3 Cefaleia cronica pos-traum'),
  ('G444', 'Cefaléia induzida por drogas, não classificada em outra parte', 'G44.4 Cefaleia induz p/drogas NCOP'),
  ('G448', 'Outras síndromes de cefaléia especificadas', 'G44.8 Outr sindr de cefaleia espec'),
  ('G45', 'Acidentes vasculares cerebrais isquêmicos transitórios e síndromes correlatas', 'G45 Acid vasc cerebr isquemicos trans sindr corr'),
  ('G450', 'Síndrome da artéria vértebro-basilar', 'G45.0 Sindr da arteria vertebro-basilar'),
  ('G451', 'Síndrome da artéria carotídea (hemisférica)', 'G45.1 Sindr da arteria carotidea'),
  ('G452', 'Síndrome das artérias pré-cerebrais, múltiplas e bilaterais', 'G45.2 Sindr arterias pre-cerebrais mult bilaterais'),
  ('G453', 'Amaurose fugaz', 'G45.3 Amaurose fugaz'),
  ('G454', 'Amnésia global transitória', 'G45.4 Amnesia global transitoria'),
  ('G458', 'Outros acidentes isquêmicos cerebrais transitórios e síndromes correlatas', 'G45.8 Outr acid isquemicos cerebr trans sindr corr'),
  ('G459', 'Isquemia cerebral transitória não especificada', 'G45.9 Isquemia cerebral transitoria NE'),
  ('G46', 'Síndromes vasculares cerebrais que ocorrem em doenças cerebrovasculares', 'G46 Sindr vasc cerebr q ocorr doenc cerebrovasc'),
  ('G460', 'Síndrome da artéria cerebral média', 'G46.0 Sindr da arteria cerebral media'),
  ('G461', 'Síndrome da artéria cerebral anterior', 'G46.1 Sindr da arteria cerebral anterior'),
  ('G462', 'Síndrome da artéria cerebral posterior', 'G46.2 Sindr da arteria cerebral posterior'),
  ('G463', 'Síndromes vasculares do tronco cerebral', 'G46.3 Sindr vasculares do tronco cerebral'),
  ('G464', 'Síndrome vascular cerebelar', 'G46.4 Sindr vascular cerebelar'),
  ('G465', 'Síndrome lacunar motora pura', 'G46.5 Sindr lacunar motora pura'),
  ('G466', 'Síndrome lacunar sensorial pura', 'G46.6 Sindr lacunar sensorial pura'),
  ('G467', 'Outras síndromes lacunares', 'G46.7 Outr sindr lacunares'),
  ('G468', 'Outras síndromes vasculares cerebrais em doenças cerebrovasculares', 'G46.8 Outr sindr vasc cerebr doenc cerebrovascular'),
  ('G47', 'Distúrbios do sono', 'G47 Disturbios do sono'),
  ('G470', 'Distúrbios do início e da manutenção do sono (insônias)', 'G47.0 Disturbios do inicio e da manutencao do sono'),
  ('G471', 'Distúrbios do sono por sonolência excessiva (hipersonia)', 'G47.1 Disturbios do sono p/sonolencia excessiva'),
  ('G472', 'Distúrbios do ciclo vigília-sono', 'G47.2 Disturbios do ciclo vigilia-sono'),
  ('G473', 'Apnéia de sono', 'G47.3 Apneia de sono'),
  ('G474', 'Narcolepsia e cataplexia', 'G47.4 Narcolepsia e cataplexia'),
  ('G478', 'Outros distúrbios do sono', 'G47.8 Outr disturbios do sono'),
  ('G479', 'Distúrbio do sono, não especificado', 'G47.9 Disturbio do sono NE'),
  ('G50', 'Transtornos do nervo trigêmeo', 'G50 Transt do nervo trigemeo'),
  ('G500', 'Nevralgia do trigêmeo', 'G50.0 Nevralgia do trigemeo'),
  ('G501', 'Dor facial atípica', 'G50.1 Dor facial atipica'),
  ('G508', 'Outros transtornos do nervo trigêmeo', 'G50.8 Outr transt do nervo trigemeo'),
  ('G509', 'Transtorno não especificado do nervo trigêmeo', 'G50.9 Transt NE do nervo trigemeo'),
  ('G51', 'Transtornos do nervo facial', 'G51 Transt do nervo facial'),
  ('G510', 'Paralisia de Bell', 'G51.0 Paralisia de Bell'),
  ('G511', 'Ganglionite geniculada', 'G51.1 Ganglionite geniculada'),
  ('G512', 'Síndrome de Melkersson', 'G51.2 Sindr de Melkersson'),
  ('G513', 'Espasmo hemifacial clônico', 'G51.3 Espasmo hemifacial clonico'),
  ('G514', 'Mioquimia facial', 'G51.4 Mioquimia facial'),
  ('G518', 'Outros transtornos do nervo facial', 'G51.8 Outr transt do nervo facial'),
  ('G519', 'Transtorno não especificado do nervo facial', 'G51.9 Transt NE do nervo facial'),
  ('G52', 'Transtornos de outros nervos cranianos', 'G52 Transt de outr nervos cranianos'),
  ('G520', 'Transtornos do nervo olfatório', 'G52.0 Transt do nervo olfatorio'),
  ('G521', 'Transtornos do nervo glossofaríngeo', 'G52.1 Transt do nervo glossofaringeo'),
  ('G522', 'Transtornos do nervo vago', 'G52.2 Transt do nervo vago'),
  ('G523', 'Transtornos do nervo hipoglosso', 'G52.3 Transt do nervo hipoglosso'),
  ('G527', 'Transtornos de múltiplos nervos cranianos', 'G52.7 Transt de mult nervos cranianos'),
  ('G528', 'Transtornos de outros nervos cranianos especificados', 'G52.8 Transt de outr nervos cranianos espec'),
  ('G529', 'Transtorno de nervo craniano não especificado', 'G52.9 Transt de nervo craniano NE'),
  ('G53', 'Transtornos dos nervos cranianos em doenças classificadas em outra parte', 'G53 Transt dos nervos cranianos em doenc COP'),
  ('G530', 'Nevralgia pós-zoster', 'G53.0 Nevralgia pos-zoster'),
  ('G531', 'Paralisias de múltiplos nervos cranianos em doenças infecciosas e parasitárias classificadas em outra parte', 'G53.1 Paral mult nerv cran doen infecc parasit COP'),
  ('G532', 'Paralisias de múltiplos nervos cranianos na sarcoidose', 'G53.2 Paralisias mult nervos cranianos sarcoidose'),
  ('G533', 'Paralisias de múltiplos nervos cranianos em doenças neoplásicas', 'G53.3 Paralisias mult nerv cran doenc neoplasicas'),
  ('G538', 'Outros transtornos de nervos cranianos em outras doenças classificadas em outra parte', 'G53.8 Outr transt nervos cranianos outr doenc COP'),
  ('G54', 'Transtornos das raízes e dos plexos nervosos', 'G54 Transt das raizes e dos plexos nervosos'),
  ('G540', 'Transtornos do plexo braquial', 'G54.0 Transt do plexo braquial'),
  ('G541', 'Transtornos do plexo lombossacral', 'G54.1 Transt do plexo lombossacral'),
  ('G542', 'Transtornos das raízes cervicais não classificadas em outra parte', 'G54.2 Transt das raizes cervicais NCOP'),
  ('G543', 'Transtornos das raízes torácicas não classificadas em outra parte', 'G54.3 Transt das raizes toracicas NCOP'),
  ('G544', 'Transtornos das raízes lombossacras não classificadas em outra parte', 'G54.4 Transt das raizes lombossacras NCOP'),
  ('G545', 'Amiotrofia nevrálgica', 'G54.5 Amiotrofia nevralgica'),
  ('G546', 'Síndrome dolorosa do membro fantasma', 'G54.6 Sindr dolorosa do membro fantasma'),
  ('G547', 'Síndrome do membro fantasma sem manifestação dolorosa', 'G54.7 Sindr membro fantasma s/manifest dolorosa'),
  ('G548', 'Outros transtornos das raízes e dos plexos nervosos', 'G54.8 Outr transt das raizes e dos plexos nervosos'),
  ('G549', 'Transtorno não especificado das raízes e dos plexos nervosos', 'G54.9 Transt NE das raizes e dos plexos nervosos'),
  ('G55', 'Compressões das raízes e dos plexos nervosos em doenças classificadas em outra parte', 'G55 Compressoes raizes plexos nervosos doenc COP'),
  ('G550', 'Compressões das raízes e dos plexos nervosos em doenças neoplásicas', 'G55.0 Compressoes raizes plexos nerv doenc neoplas'),
  ('G551', 'Compressões das raízes e dos plexos nervosos em transtornos dos discos intervertebrais', 'G55.1 Compr raiz plexo nerv transt disco intervert'),
  ('G552', 'Compressões das raízes e dos plexos nervosos na espondilose', 'G55.2 Compressoes raizes plexos nerv espondilose'),
  ('G553', 'Compressões das raízes e dos plexos nervosos em outras dorsopatias', 'G55.3 Compressoes raizes plexos nerv outr dorsopat'),
  ('G558', 'Compressões das raízes e dos plexos nervosos em outras doenças classificadas em outra parte', 'G55.8 Compress raizes plexos nerv outr doenc COP'),
  ('G56', 'Mononeuropatias dos membros superiores', 'G56 Mononeuropatias dos membros super'),
  ('G560', 'Síndrome do túnel do carpo', 'G56.0 Sindr do tunel do carpo'),
  ('G561', 'Outras lesões do nervo mediano', 'G56.1 Outr lesoes do nervo mediano'),
  ('G562', 'Lesões do nervo cubital (ulnar)', 'G56.2 Lesoes do nervo cubital'),
  ('G563', 'Lesão do nervo radial', 'G56.3 Lesao do nervo radial'),
  ('G564', 'Causalgia', 'G56.4 Causalgia'),
  ('G568', 'Outras mononeuropatias dos membros superiores', 'G56.8 Outr mononeuropatias dos membros super'),
  ('G569', 'Mononeuropatia dos membros superiores, não especificada', 'G56.9 Mononeuropatia dos membros super NE'),
  ('G57', 'Mononeuropatias dos membros inferiores', 'G57 Mononeuropatias dos membros infer'),
  ('G570', 'Lesão do nervo ciático', 'G57.0 Lesao do nervo ciatico'),
  ('G571', 'Meralgia parestésica', 'G57.1 Meralgia parestesica'),
  ('G572', 'Lesão do nervo femoral', 'G57.2 Lesao do nervo femoral'),
  ('G573', 'Lesão do nervo poplíteo lateral', 'G57.3 Lesao do nervo popliteo lateral'),
  ('G574', 'Lesão do nervo poplíteo medial', 'G57.4 Lesao do nervo popliteo medial'),
  ('G575', 'Síndrome do túnel do tarso', 'G57.5 Sindr do tunel do tarso'),
  ('G576', 'Lesão do nervo plantar', 'G57.6 Lesao do nervo plantar'),
  ('G578', 'Outras mononeuropatias dos membros inferiores', 'G57.8 Outr mononeuropatias dos membros infer'),
  ('G579', 'Mononeuropatia dos membros inferiores, não especificada', 'G57.9 Mononeuropatia dos membros infer NE'),
  ('G58', 'Outras mononeuropatias', 'G58 Outr mononeuropatias'),
  ('G580', 'Neuropatia intercostal', 'G58.0 Neuropatia intercostal'),
  ('G587', 'Mononeurite múltipla', 'G58.7 Mononeurite mult'),
  ('G588', 'Outras mononeuropatias especificadas', 'G58.8 Outr mononeuropatias espec'),
  ('G589', 'Mononeuropatia não especificada', 'G58.9 Mononeuropatia NE'),
  ('G59', 'Mononeuropatias em doenças classificadas em outra parte', 'G59 Mononeuropatias em doenc COP'),
  ('G590', 'Mononeuropatia diabética', 'G59.0 Mononeuropatia diabetica'),
  ('G598', 'Outras mononeuropatias em doenças classificadas em outra parte', 'G59.8 Outr mononeuropatias em doenc COP'),
  ('G60', 'Neuropatia hereditária e idiopática', 'G60 Neuropatia hereditaria e idiopatica'),
  ('G600', 'Neuropatia hereditária motora e sensorial', 'G60.0 Neuropatia hereditaria motora e sensorial'),
  ('G601', 'Doença de Refsum', 'G60.1 Doenc de Refsum'),
  ('G602', 'Neuropatia associada a ataxia hereditária', 'G60.2 Neuropatia assoc a ataxia hereditaria'),
  ('G603', 'Neuropatia progressiva idiopática', 'G60.3 Neuropatia progressiva idiopatica'),
  ('G608', 'Outras neuropatias hereditárias e idiopáticas', 'G60.8 Outr neuropatias hereditarias e idiopaticas'),
  ('G609', 'Neuropatia hereditária e idiopática não especificada', 'G60.9 Neuropatia hereditaria e idiopatica NE'),
  ('G61', 'Polineuropatia inflamatória', 'G61 Polineuropatia inflam'),
  ('G610', 'Síndrome de Guillain-Barré', 'G61.0 Sindr de Guillain-Barre'),
  ('G611', 'Neuropatia sérica', 'G61.1 Neuropatia serica'),
  ('G618', 'Outras polineuropatias inflamatórias', 'G61.8 Outr polineuropatias inflam'),
  ('G619', 'Polineuropatia inflamatória não especificada', 'G61.9 Polineuropatia inflam NE'),
  ('G62', 'Outras polineuropatias', 'G62 Outr polineuropatias'),
  ('G620', 'Polineuropatia induzida por drogas', 'G62.0 Polineuropatia induz p/drogas'),
  ('G621', 'Polineuropatia alcoólica', 'G62.1 Polineuropatia alcoolica'),
  ('G622', 'Polineuropatia devida a outros agentes tóxicos', 'G62.2 Polineuropatia dev outr agentes toxicos'),
  ('G628', 'Outras polineuropatias especificadas', 'G62.8 Outr polineuropatias espec'),
  ('G629', 'Polineuropatia não especificada', 'G62.9 Polineuropatia NE'),
  ('G63', 'Polineuropatia em doenças classificadas em outra parte', 'G63 Polineuropatia em doenc COP'),
  ('G630', 'Polineuropatia em doenças infecciosas e parasitárias classificadas em outra parte', 'G63.0 Polineuropatia em doenc infecc e parasit COP'),
  ('G631', 'Polineuropatia em doenças neoplásicas', 'G63.1 Polineuropatia em doenc neoplasicas'),
  ('G632', 'Polineuropatia diabética', 'G63.2 Polineuropatia diabetica'),
  ('G633', 'Polineuropatia em outras doenças endócrinas e metabólicas', 'G63.3 Polineuropatia outr doenc endocr metabolicas'),
  ('G634', 'Polineuropatia em deficiências nutricionais', 'G63.4 Polineuropatia em defic nutricionais'),
  ('G635', 'Polineuropatia em doenças sistêmicas do tecido conjuntivo', 'G63.5 Polineuropatia doenc sistemicas tec conjunt'),
  ('G636', 'Polineuropatia em outros transtornos osteomusculares', 'G63.6 Polineuropatia outr transt osteomusculares'),
  ('G638', 'Polineuropatia em outras doenças classificadas em outra parte', 'G63.8 Polineuropatia em outr doenc COP'),
  ('G64', 'Outros transtornos do sistema nervoso periférico', 'G64 Outr transt do sist nervoso periferico'),
  ('G64', 'Outros transtornos do sistema nervoso periférico', 'G64 Outr transt do sist nervoso periferico'),
  ('G70', 'Miastenia gravis e outros transtornos neuromusculares', 'G70 Miastenia gravis outr transt neuromusculares'),
  ('G700', 'Miastenia gravis', 'G70.0 Miastenia gravis'),
  ('G701', 'Transtornos mioneurais tóxicos', 'G70.1 Transt mioneurais toxicos'),
  ('G702', 'Miastenia congênita e do desenvolvimento', 'G70.2 Miastenia congen e do desenvolv'),
  ('G708', 'Outros transtornos mioneurais especificados', 'G70.8 Outr transt mioneurais espec'),
  ('G709', 'Transtorno mioneural não especificado', 'G70.9 Transt mioneural NE'),
  ('G71', 'Transtornos primários dos músculos', 'G71 Transt prim dos musculos'),
  ('G710', 'Distrofia muscular', 'G71.0 Distrofia muscular'),
  ('G711', 'Transtornos miotônicos', 'G71.1 Transt miotonicos'),
  ('G712', 'Miopatias congênitas', 'G71.2 Miopatias congen'),
  ('G713', 'Miopatia mitocondrial não classificada em outra parte', 'G71.3 Miopatia mitocondrial NCOP'),
  ('G718', 'Outros transtornos primários dos músculos', 'G71.8 Outr transt prim dos musculos'),
  ('G719', 'Transtorno muscular primário não especificado', 'G71.9 Transt muscular prim NE'),
  ('G72', 'Outras miopatias', 'G72 Outr miopatias'),
  ('G720', 'Miopatia induzida por drogas', 'G72.0 Miopatia induz p/drogas'),
  ('G721', 'Miopatia alcoólica', 'G72.1 Miopatia alcoolica'),
  ('G722', 'Miopatia devida a outros agentes tóxicos', 'G72.2 Miopatia dev outr agentes toxicos'),
  ('G723', 'Paralisia periódica', 'G72.3 Paralisia periodica'),
  ('G724', 'Miopatia inflamatória não classificada em outra parte', 'G72.4 Miopatia inflam NCOP'),
  ('G728', 'Outras miopatias especificadas', 'G72.8 Outr miopatias espec'),
  ('G729', 'Miopatia não especificada', 'G72.9 Miopatia NE'),
  ('G73', 'Transtornos da junção mioneural e dos músculos em doenças classificadas em outra parte', 'G73 Transt juncao mioneural musculos doenc COP'),
  ('G730', 'Síndromes miastênicas em doenças endócrinas', 'G73.0 Sindr miastenicas em doenc endocrinas'),
  ('G731', 'Síndrome de Eaton-Lambert', 'G73.1 Sindr de Eaton-Lambert'),
  ('G732', 'Outras síndromes miastênicas em doenças neoplásicas', 'G73.2 Outr sindr miastenicas em doenc neoplasicas'),
  ('G733', 'Síndromes miastênicas em outras doenças classificadas em outra parte', 'G73.3 Sindr miastenicas em outr doenc COP'),
  ('G734', 'Miopatia em doenças infecciosas e parasitárias classificadas em outra parte', 'G73.4 Miopatia em doenc infecc e parasit COP'),
  ('G735', 'Miopatia em doenças endócrinas', 'G73.5 Miopatia em doenc endocrinas'),
  ('G736', 'Miopatia em doenças metabólicas', 'G73.6 Miopatia em doenc metabolicas'),
  ('G737', 'Miopatia em outras doenças classificadas em outra parte', 'G73.7 Miopatia em outr doenc COP'),
  ('G80', 'Paralisia cerebral', 'G80 Paralisia cerebral'),
  ('G800', 'Paralisia cerebral quadriplágica espástica', 'G80.0 Paralisia cerebral quadriplágica espástica'),
  ('G801', 'Paralisia cerebral diplégica espástica', 'G80.1 Paralisia cerebral diplégica espástica'),
  ('G802', 'Paralisia cerebral hemiplégica espástica', 'G80.2 Paralisia cerebral hemiplégica espástica'),
  ('G803', 'Paralisia cerebral discinética', 'G80.3 Paralisia cerebral discinetica'),
  ('G804', 'Paralisia cerebral atáxica', 'G80.4 Paralisia cerebral ataxica'),
  ('G808', 'Outras formas de paralisia cerebral', 'G80.8 Outr form de paralisia cerebral'),
  ('G809', 'Paralisia cerebral não especificada', 'G80.9 Paralisia cerebral NE'),
  ('G81', 'Hemiplegia', 'G81 Hemiplegia'),
  ('G810', 'Hemiplegia flácida', 'G81.0 Hemiplegia flacida'),
  ('G811', 'Hemiplegia espástica', 'G81.1 Hemiplegia espastica'),
  ('G819', 'Hemiplegia não especificada', 'G81.9 Hemiplegia NE'),
  ('G82', 'Paraplegia e tetraplegia', 'G82 Paraplegia e tetraplegia'),
  ('G820', 'Paraplegia flácida', 'G82.0 Paraplegia flacida'),
  ('G821', 'Paraplegia espástica', 'G82.1 Paraplegia espastica'),
  ('G822', 'Paraplegia não especificada', 'G82.2 Paraplegia NE'),
  ('G823', 'Tetraplegia flácida', 'G82.3 Tetraplegia flacida'),
  ('G824', 'Tetraplegia espástica', 'G82.4 Tetraplegia espastica'),
  ('G825', 'Tetraplegia não especificada', 'G82.5 Tetraplegia NE'),
  ('G83', 'Outras síndromes paralíticas', 'G83 Outr sindr paraliticas'),
  ('G830', 'Diplegia dos membros superiores', 'G83.0 Diplegia dos membros super'),
  ('G831', 'Monoplegia do membro inferior', 'G83.1 Monoplegia do membro infer'),
  ('G832', 'Monoplegia do membro superior', 'G83.2 Monoplegia do membro super'),
  ('G833', 'Monoplegia não especificada', 'G83.3 Monoplegia NE'),
  ('G834', 'Síndrome da cauda eqüina', 'G83.4 Sindr da cauda equina'),
  ('G838', 'Outras síndromes paralíticas especificadas', 'G83.8 Outr sindr paraliticas espec'),
  ('G839', 'Síndrome paralítica não especificada', 'G83.9 Sindr paralitica NE'),
  ('G90', 'Transtornos do sistema nervoso autônomo', 'G90 Transt do sist nervoso autonomo'),
  ('G900', 'Neuropatia autonômica periférica idiopática', 'G90.0 Neuropatia autonomica periferica idiopatica'),
  ('G901', 'Disautonomia familiar (Síndrome de Riley-Day)', 'G90.1 Disautonomia familiar'),
  ('G902', 'Síndrome de Horner', 'G90.2 Sindr de Horner'),
  ('G903', 'Degeneração multissistêmica', 'G90.3 Degeneracao multissistemica'),
  ('G904', 'Disreflexia autonômica', 'G90.4 Disreflexia autonômica'),
  ('G908', 'Outros transtornos do sistema nervoso autônomo', 'G90.8 Outr transt do sist nervoso autonomo'),
  ('G909', 'Transtorno não especificado do sistema nervoso autônomo', 'G90.9 Transt NE do sist nervoso autonomo'),
  ('G91', 'Hidrocefalia', 'G91 Hidrocefalia'),
  ('G910', 'Hidrocefalia comunicante', 'G91.0 Hidrocefalia comunicante'),
  ('G911', 'Hidrocefalia obstrutiva', 'G91.1 Hidrocefalia obstrutiva'),
  ('G912', 'Hidrocefalia de pressão normal', 'G91.2 Hidrocefalia de pressao normal'),
  ('G913', 'Hidrocefalia pós-traumática não especificada', 'G91.3 Hidrocefalia pos-traum NE'),
  ('G918', 'Outras formas de hidrocefalia', 'G91.8 Outr form de hidrocefalia'),
  ('G919', 'Hidrocefalia não especificada', 'G91.9 Hidrocefalia NE'),
  ('G92', 'Encefalopatia tóxica', 'G92 Encefalopatia toxica'),
  ('G92', 'Encefalopatia tóxica', 'G92 Encefalopatia toxica'),
  ('G93', 'Outros transtornos do encéfalo', 'G93 Outr transt do encefalo'),
  ('G930', 'Cistos cerebrais', 'G93.0 Cistos cerebrais'),
  ('G931', 'Lesão encefálica anóxica, não classificada em outra parte', 'G93.1 Lesao encefalica anoxica NCOP'),
  ('G932', 'Hipertensão intracraniana benigna', 'G93.2 Hipertensao intracraniana benigna'),
  ('G933', 'Síndrome da fadiga pós-viral', 'G93.3 Sindr da fadiga pos-viral'),
  ('G934', 'Encefalopatia não especificada', 'G93.4 Encefalopatia NE'),
  ('G935', 'Compressão do encéfalo', 'G93.5 Compressao do encefalo'),
  ('G936', 'Edema cerebral', 'G93.6 Edema cerebral'),
  ('G937', 'Síndrome de Reye', 'G93.7 Sindr de Reye'),
  ('G938', 'Outros transtornos especificados do encéfalo', 'G93.8 Outr transt espec do encefalo'),
  ('G939', 'Transtorno não especificado do encéfalo', 'G93.9 Transt NE do encefalo'),
  ('G94', 'Outros transtornos do encéfalo em doenças classificadas em outra parte', 'G94 Outr transt do encefalo em doenc COP'),
  ('G940', 'Hidrocefalia em doenças infecciosas e parasitárias classificadas em outra parte', 'G94.0 Hidrocefalia em doenc infecc e parasit COP'),
  ('G941', 'Hidrocefalia em doenças neoplásicas', 'G94.1 Hidrocefalia em doenc neoplasicas'),
  ('G942', 'Hidrocefalia em outras doenças classificadas em outra parte', 'G94.2 Hidrocefalia em outr doenc COP'),
  ('G948', 'Outros transtornos encefálicos especificados em doenças classificadas em outra parte', 'G94.8 Outr transt encefalicos espec em doenc COP'),
  ('G95', 'Outras doenças da medula espinal', 'G95 Outr doenc da medula espinal'),
  ('G950', 'Siringomielia e siringobulbia', 'G95.0 Siringomielia e siringobulbia'),
  ('G951', 'Mielopatias vasculares', 'G95.1 Mielopatias vasculares'),
  ('G952', 'Compressão não especificada de medula espinal', 'G95.2 Compressao NE de medula espinal'),
  ('G958', 'Outras doenças especificadas da medula espinal', 'G95.8 Outr doenc espec da medula espinal'),
  ('G959', 'Doença não especificada da medula espinal', 'G95.9 Doenc NE da medula espinal'),
  ('G96', 'Outros transtornos do sistema nervoso central', 'G96 Outr transt do sist nervoso central'),
  ('G960', 'Fístula liquórica', 'G96.0 Fistula liquorica'),
  ('G961', 'Transtornos das meninges não classificados em outra parte', 'G96.1 Transt das meninges NCOP'),
  ('G968', 'Outros transtornos especificados do sistema nervoso central', 'G96.8 Outr transt espec do sist nervoso central'),
  ('G969', 'Transtorno não especificado do sistema nervoso central', 'G96.9 Transt NE do sist nervoso central'),
  ('G97', 'Transtornos pós-procedimento do sistema nervoso não classificados em outra parte', 'G97 Transt pos-proced do sist nervoso NCOP'),
  ('G970', 'Perda de líquor resultante de punção espinal', 'G97.0 Perda de liquor resultante de puncao espinal'),
  ('G971', 'Outra reação à punção espinal e lombar', 'G97.1 Outr reacao a puncao espinal e lombar'),
  ('G972', 'Hipotensão intracraniana conseqüente à derivação ventricular', 'G97.2 Hipotensao intracran conseq deriv ventric'),
  ('G978', 'Outros transtornos pós-procedimento do sistema nervoso', 'G97.8 Outr transt pos-proced do sist nervoso'),
  ('G979', 'Transtorno pós-procedimento do sistema nervoso, não especificado', 'G97.9 Transt pos-proced do sist nervoso NE'),
  ('G98', 'Outros transtornos do sistema nervoso não classificados em outra parte', 'G98 Outr transt do sist nervoso NCOP'),
  ('G98', 'Outros transtornos do sistema nervoso não classificados em outra parte', 'G98 Outr transt do sist nervoso NCOP'),
  ('G99', 'Outros transtornos do sistema nervoso em doenças classificadas em outra parte', 'G99 Outr transt do sist nervoso em doenc COP'),
  ('G990', 'Neuropatia autonômica em doenças endócrinas e metabólicas', 'G99.0 Neuropatia autonomica doenc endocr metabol'),
  ('G991', 'Outros transtornos do sistema nervoso autônomo em doenças classificadas em outra parte', 'G99.1 Outr transt sist nervoso autonomo doenc COP'),
  ('G992', 'Mielopatia em doenças classificadas em outra parte', 'G99.2 Mielopatia em doenc COP'),
  ('G998', 'Outros transtornos especificados do sistema nervoso em doenças classificadas em outra parte', 'G99.8 Outr transt espec do sist nervoso doenc COP');
