INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('M00', 'Artrite piogênica', 'M00 Artrite piogenica'),
  ('M000', 'Artrite e pioliartrite estafilocócicas', 'M00.0 Artrite e pioliartrite estafilococicas'),
  ('M001', 'Artrite e poliartrite pneumocócicas', 'M00.1 Artrite e poliartrite pneumococicas'),
  ('M002', 'Outras artrites e poliartrites estreptocócicas', 'M00.2 Outr artrites e poliartrites estreptococicas'),
  ('M008', 'Artrite e poliartrite devidas a outro agente bacteriano especificado', 'M00.8 Artrite poliartr dev outr agent bacter espec'),
  ('M009', 'Artrite piogênica, não especificada', 'M00.9 Artrite piogenica NE'),
  ('M01', 'Infecções diretas da articulação em doenças infecciosas e parasitárias classificadas em outra parte', 'M01 Infecc diretas artic doenc infec parasit COP'),
  ('M010', 'Artrite meningocócica', 'M01.0 Artrite meningococica'),
  ('M011', 'Artrite tuberculosa', 'M01.1 Artrite tuberc'),
  ('M012', 'Artrite na doença de Lyme', 'M01.2 Artrite na doenc de Lyme'),
  ('M013', 'Artrite em outras doenças bacterianas classificadas em outra parte', 'M01.3 Artrite em outr doenc bacter COP'),
  ('M014', 'Artrite na rubéola', 'M01.4 Artrite na rubeola'),
  ('M015', 'Artrite em outras doenças virais classificadas em outra parte', 'M01.5 Artrite em outr doenc virais COP'),
  ('M016', 'Artrite em micoses', 'M01.6 Artrite em micoses'),
  ('M018', 'Artrite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'M01.8 Artrite em outr doenc infecc e parasit COP'),
  ('M02', 'Artropatias reacionais', 'M02 Artropatias reacionais'),
  ('M020', 'Artropatia pós-derivação intestinal', 'M02.0 Artropatia pos-derivacao intestinal'),
  ('M021', 'Artropatia pós-desintérica', 'M02.1 Artropatia pos-desinterica'),
  ('M022', 'Artropatia pós-imunização', 'M02.2 Artropatia pos-imunizacao'),
  ('M023', 'Doença de Reiter', 'M02.3 Doenc de Reiter'),
  ('M028', 'Outras artropatias reacionais', 'M02.8 Outr artropatias reacionais'),
  ('M029', 'Artropatia reacional não especificada', 'M02.9 Artropatia reacional NE'),
  ('M03', 'Artropatias pós-infecciosas e reacionais em doenças infecciosas classificadas em outra parte', 'M03 Artropatias pos-infecc reac doenc infecc COP'),
  ('M030', 'Artrite pós-meningocócica', 'M03.0 Artrite pos-meningococica'),
  ('M031', 'Artropatia pós-infecciosa na sífilis', 'M03.1 Artropatia pos-infecc na sifilis'),
  ('M032', 'Outras artropatias pós-infecciosas em doenças classificadas em outra parte', 'M03.2 Outr artropatias pos-infecc em doenc COP'),
  ('M036', 'Artropatia reacional em outras doenças classificadas em outra parte', 'M03.6 Artropatia reacional em outr doenc COP'),
  ('M05', 'Artrite reumatóide soro-positiva', 'M05 Artrite reumatoide soro-positiva'),
  ('M050', 'Síndrome de Felty', 'M05.0 Sindr de Felty'),
  ('M051', 'Doença reumatóide do pulmão', 'M05.1 Doenc reumatoide do pulmao'),
  ('M052', 'Vasculite reumatóide', 'M05.2 Vasculite reumatoide'),
  ('M053', 'Artrite reumatóide com comprometimento de outros órgãos e sistemas', 'M05.3 Artrite reumatoide c/compr outr org e sist'),
  ('M058', 'Outras artrites reumatóides soro-positivas', 'M05.8 Outr artrites reumatoides soro-positivas'),
  ('M059', 'Artrite reumatóide soro-positiva não especificada', 'M05.9 Artrite reumatoide soro-positiva NE'),
  ('M06', 'Outras artrites reumatóides', 'M06 Outr artrites reumatoides'),
  ('M060', 'Artrite reumatóide soro-negativa', 'M06.0 Artrite reumatoide soro-negativa'),
  ('M061', 'Doença de Still do adulto', 'M06.1 Doenc de Still do adulto'),
  ('M062', 'Bursite reumatóide', 'M06.2 Bursite reumatoide'),
  ('M063', 'Nódulo reumatóide', 'M06.3 Nodulo reumatoide'),
  ('M064', 'Poliartropatia inflamatória', 'M06.4 Poliartropatia inflam'),
  ('M068', 'Outras artrites reumatóides especificadas', 'M06.8 Outr artrites reumatoides espec'),
  ('M069', 'Artrite reumatóide não especificada', 'M06.9 Artrite reumatoide NE'),
  ('M07', 'Artropatias psoriásicas e enteropáticas', 'M07 Artropatias psoriasicas e enteropaticas'),
  ('M070', 'Artropatia psoriásica interfalangiana distal', 'M07.0 Artropatia psoriasica interfalangiana distal'),
  ('M071', 'Artrite mutilante', 'M07.1 Artrite mutilante'),
  ('M072', 'Espondilite psoriásica', 'M07.2 Espondilite psoriasica'),
  ('M073', 'Outras artropatias psoriásicas', 'M07.3 Outr artropatias psoriasicas'),
  ('M074', 'Artropatia na doença de Crohn (enterite regional)', 'M07.4 Artropatia na doenc de Crohn'),
  ('M075', 'Artropatia na colite ulcerativa', 'M07.5 Artropatia na colite ulcerativa'),
  ('M076', 'Outras artropatias enteropáticas', 'M07.6 Outr artropatias enteropaticas'),
  ('M08', 'Artrite juvenil', 'M08 Artrite juvenil'),
  ('M080', 'Artrite reumatóide juvenil', 'M08.0 Artrite reumatoide juvenil'),
  ('M081', 'Espondilite ancilosante juvenil', 'M08.1 Espondilite ancilosante juvenil'),
  ('M082', 'Artrite juvenil com início sistêmico', 'M08.2 Artrite juvenil c/inicio sistemico'),
  ('M083', 'Poliartrite juvenil (soro-negativa)', 'M08.3 Poliartrite juvenil'),
  ('M084', 'Artrite juvenil pauciarticular', 'M08.4 Artrite juvenil pauciarticular'),
  ('M088', 'Outras artrites juvenis', 'M08.8 Outr artrites juvenis'),
  ('M089', 'Artrite juvenil não especificada', 'M08.9 Artrite juvenil NE'),
  ('M09', 'Artrite juvenil em doenças classificadas em outra parte', 'M09 Artrite juvenil em doenc COP'),
  ('M090', 'Artrite juvenil na psoríase', 'M09.0 Artrite juvenil na psoriase'),
  ('M091', 'Artrite juvenil na doença de Chron (enterite regional)', 'M09.1 Artrite juvenil na doenc de Chron'),
  ('M092', 'Artrite juvenil na colite ulcerativa', 'M09.2 Artrite juvenil na colite ulcerativa'),
  ('M098', 'Artrite juvenil em outras doenças classificadas em outra parte', 'M09.8 Artrite juvenil em outr doenc COP'),
  ('M10', 'Gota', 'M10 Gota'),
  ('M100', 'Gota idiopática', 'M10.0 Gota idiopatica'),
  ('M101', 'Gota induzida por chumbo', 'M10.1 Gota induz p/chumbo'),
  ('M102', 'Gota induzida por drogas', 'M10.2 Gota induz p/drogas'),
  ('M103', 'Gota devida à disfunção renal', 'M10.3 Gota dev disfuncao renal'),
  ('M104', 'Outra gota secundária', 'M10.4 Outr gota secund'),
  ('M109', 'Gota, não especificada', 'M10.9 Gota NE'),
  ('M11', 'Outras artropatias por deposição de cristais', 'M11 Outr artropatias p/deposicao de cristais'),
  ('M110', 'Doença por deposição de hidroxiapatita', 'M11.0 Doenc p/deposicao de hidroxiapatita'),
  ('M111', 'Condrocalcinose familiar', 'M11.1 Condrocalcinose familiar'),
  ('M112', 'Outras condrocalcinoses', 'M11.2 Outr condrocalcinoses'),
  ('M118', 'Outras artropatias especificadas por deposição de cristais', 'M11.8 Outr artropatias espec p/deposicao cristais'),
  ('M119', 'Artropatia por deposição de cristais, não especificada', 'M11.9 Artropatia p/deposicao de cristais NE'),
  ('M12', 'Outras artropatias especificadas', 'M12 Outr artropatias espec'),
  ('M120', 'Artropatia pós-reumática crônica (Jaccoud)', 'M12.0 Artropatia pos-reumatica cronica'),
  ('M121', 'Doença de Kashin-Beck', 'M12.1 Doenc de Kashin-Beck'),
  ('M122', 'Sinovite vilonodular (pigmentada)', 'M12.2 Sinovite vilonodular'),
  ('M123', 'Reumatismo palindrômico', 'M12.3 Reumatismo palindromico'),
  ('M124', 'Hidrartrose intermitente', 'M12.4 Hidrartrose intermitente'),
  ('M125', 'Artropatia traumática', 'M12.5 Artropatia traum'),
  ('M128', 'Outras artropatias específicas não classificadas em outra parte', 'M12.8 Outr artropatias especificas NCOP'),
  ('M13', 'Outras artrites', 'M13 Outr artrites'),
  ('M130', 'Poliartrite não especificada', 'M13.0 Poliartrite NE'),
  ('M131', 'Monoartrites não classificadas em outra parte', 'M13.1 Monoartrites NCOP'),
  ('M138', 'Outras artrites especificadas', 'M13.8 Outr artrites espec'),
  ('M139', 'Artrite não especificada', 'M13.9 Artrite NE'),
  ('M14', 'Artropatias em outras doenças classificadas em outra parte', 'M14 Artropatias em outr doenc COP'),
  ('M140', 'Artropatia gotosa devida a defeitos enzimáticos e a outras doenças hereditárias', 'M14.0 Artropat gotosa dev def enzim out doen hered'),
  ('M141', 'Artropatia por depósito de cristais em outras doenças metabólicas classificadas em outra parte', 'M14.1 Artropatia dep cristais outr doenc metab COP'),
  ('M142', 'Artropatia diabética', 'M14.2 Artropatia diabetica'),
  ('M143', 'Dermatoartrite lipóide', 'M14.3 Dermatoartrite lipoide'),
  ('M144', 'Artropatia na amiloidose', 'M14.4 Artropatia na amiloidose'),
  ('M145', 'Artropatias em outras doenças endócrinas, nutricionais e metabólicas', 'M14.5 Artropatias outr doenc endocr nutric metab'),
  ('M146', 'Artropatia neuropática', 'M14.6 Artropatia neuropatica'),
  ('M148', 'Artropatias em outras doenças especificadas classificadas em outra parte', 'M14.8 Artropatias em outr doenc espec COP'),
  ('M15', 'Poliartrose', 'M15 Poliartrose'),
  ('M150', '(Osteo)artrose primária generalizada', 'M15.0 Artrose prim generalizada'),
  ('M151', 'Nódulos de Heberden (com artropatia)', 'M15.1 Nodulos de Heberden'),
  ('M152', 'Nódulos de Bouchard (com artropatia)', 'M15.2 Nodulos de Bouchard'),
  ('M153', 'Artrose múltipla secundária', 'M15.3 Artrose mult secund'),
  ('M154', '(Osteo)artrose erosiva', 'M15.4 Artrose erosiva'),
  ('M158', 'Outras poliartroses', 'M15.8 Outr poliartroses'),
  ('M159', 'Poliartrose não especificada', 'M15.9 Poliartrose NE'),
  ('M16', 'Coxartrose (artrose do quadril)', 'M16 Coxartrose'),
  ('M160', 'Coxartrose primária bilateral', 'M16.0 Coxartrose prim bilateral'),
  ('M161', 'Outras coxartroses primárias', 'M16.1 Outr coxartroses prim'),
  ('M162', 'Coxartrose bilateral resultante de displasia', 'M16.2 Coxartrose bilateral resultante de displasia'),
  ('M163', 'Outras coxartroses displásicas', 'M16.3 Outr coxartroses displasicas'),
  ('M164', 'Coxartrose bilateral pós-traumática', 'M16.4 Coxartrose bilateral pos-traum'),
  ('M165', 'Outras coxartroses pós-traumáticas', 'M16.5 Outr coxartroses pos-traum'),
  ('M166', 'Outras coxartroses secundárias bilaterais', 'M16.6 Outr coxartroses secund bilaterais'),
  ('M167', 'Outras coxartroses secundárias', 'M16.7 Outr coxartroses secund'),
  ('M169', 'Coxartrose não especificada', 'M16.9 Coxartrose NE'),
  ('M17', 'Gonartrose (artrose do joelho)', 'M17 Gonartrose'),
  ('M170', 'Gonartrose primária bilateral', 'M17.0 Gonartrose prim bilateral'),
  ('M171', 'Outras gonartroses primárias', 'M17.1 Outr gonartroses prim'),
  ('M172', 'Gonartrose pós-traumática bilateral', 'M17.2 Gonartrose pos-traum bilateral'),
  ('M173', 'Outras gonartroses pós-traumática', 'M17.3 Outr gonartroses pos-traum'),
  ('M174', 'Outras gonartroses secundárias bilaterais', 'M17.4 Outr gonartroses secund bilaterais'),
  ('M175', 'Outras gonartroses secundárias', 'M17.5 Outr gonartroses secund'),
  ('M179', 'Gonartrose não especificada', 'M17.9 Gonartrose NE'),
  ('M18', 'Artrose da primeira articulação carpometacarpiana', 'M18 Artrose prim articulacao carpometacarpiana'),
  ('M180', 'Artrose primária bilateral das primeiras articulações carpometacarpianas', 'M18.0 Artrose prim bilat prim artic carpometacarp'),
  ('M181', 'Outras artroses primárias da primeira articulação carpometacarpiana', 'M18.1 Outr artroses prim prim artic carpometacarp'),
  ('M182', 'Artrose pós-traumática bilateral da primeira articulação carpometacarpiana', 'M18.2 Artrose pos-traum bilat prim art carpometac'),
  ('M183', 'Outras artroses pós-traumáticas da primeira articulação carpometacarpiana', 'M18.3 Outr artroses pos-traum prim art carpometac'),
  ('M184', 'Outras cartroses secundárias bilaterais das primeiras articulações carpometacarpianas', 'M18.4 Outr cartroses sec bilat prim art carpometac'),
  ('M185', 'Outras artroses secundárias da primeira articulação carpometacarpiana', 'M18.5 Outr artroses sec prim artic carpometacarp'),
  ('M189', 'Artrose não especificada da primeira articulação carpometacarpiana', 'M18.9 Artrose NE prim artic carpometacarpiana'),
  ('M19', 'Outras artroses', 'M19 Outr artroses'),
  ('M190', 'Artrose primária de outras articulações', 'M19.0 Artrose prim de outr articulacoes'),
  ('M191', 'Artrose pós-traumática de outras articulações', 'M19.1 Artrose pos-traum de outr articulacoes'),
  ('M192', 'Outras artroses secundárias', 'M19.2 Outr artroses secund'),
  ('M198', 'Outras artroses especificadas', 'M19.8 Outr artroses espec'),
  ('M199', 'Artrose não especificada', 'M19.9 Artrose NE'),
  ('M20', 'Deformidades adquiridas dos dedos das mãos e dos pés', 'M20 Deform adquir dedos maos e pes'),
  ('M200', 'Deformidade(s) do(s) dedo(s) das mãos', 'M20.0 Deform de dedos das maos'),
  ('M201', 'Hallux valgo (adquirido)', 'M20.1 Hallux valgo'),
  ('M202', 'Hallux rigidus', 'M20.2 Hallux rigidus'),
  ('M203', 'Outra deformidade do hallux (adquirida)', 'M20.3 Outr deform do hallux'),
  ('M204', 'Dedo(s) do pé em malho (adquirido)', 'M20.4 Dedos do pe em malho'),
  ('M205', 'Outras deformidades (adquiridas) do(s) dedo(s) dos pés', 'M20.5 Outr deform de dedos dos pes'),
  ('M206', 'Deformidade adquirida não especificada de dedo(s) do pé', 'M20.6 Deform adquir NE de dedos do pe'),
  ('M21', 'Outras deformidades adquiridas dos membros', 'M21 Outr deform adquir dos membros'),
  ('M210', 'Deformidade em valgo não classificada em outra parte', 'M21.0 Deform em valgo NCOP'),
  ('M211', 'Deformidade em varo não classificada em outra parte', 'M21.1 Deform em varo NCOP'),
  ('M212', 'Deformidade em flexão', 'M21.2 Deform em flexao'),
  ('M213', 'Mão (pulso) ou pé pendente (adquirido)', 'M21.3 Mao ou pe pendente'),
  ('M214', 'Pé chato (pé plano) (adquirido)', 'M21.4 Pe chato'),
  ('M215', 'Mão e pé em garra e mão e pé tortos adquiridos', 'M21.5 Mao e pe em garra e mao e pe tortos adquir'),
  ('M216', 'Outras deformidades adquiridas do tornozelo e do pé', 'M21.6 Outr deform adquir do tornozelo e do pe'),
  ('M217', 'Desigualdade (adquirida) do comprimento dos membros', 'M21.7 Desigualdade do comprimento dos membros'),
  ('M218', 'Outras deformidades adquiridas especificadas dos membros', 'M21.8 Outr deform adquir espec dos membros'),
  ('M219', 'Deformidade adquirida não especificada de membro', 'M21.9 Deform adquir NE de membro'),
  ('M22', 'Transtornos da rótula (patela)', 'M22 Transt da rotula'),
  ('M220', 'Deslocamento recidivante da rótula', 'M22.0 Deslocamento recidivante da rotula'),
  ('M221', 'Subluxação recidivante da rótula', 'M22.1 Subluxacao recidivante da rotula'),
  ('M222', 'Transtornos femuropatelares', 'M22.2 Transt femuropatelares'),
  ('M223', 'Outros desarranjos da rótula', 'M22.3 Outr desarranjos da rotula'),
  ('M224', 'Condromalácia da rótula', 'M22.4 Condromalacia da rotula'),
  ('M228', 'Outros transtornos da rótula', 'M22.8 Outr transt da rotula'),
  ('M229', 'Transtorno da rótula, não especificado', 'M22.9 Transt da rotula NE'),
  ('M23', 'Transtornos internos dos joelhos', 'M23 Transt internos dos joelhos'),
  ('M230', 'Menisco cístico', 'M23.0 Menisco cistico'),
  ('M231', 'Menisco discóide (congênito)', 'M23.1 Menisco discoide'),
  ('M232', 'Transtorno do menisco devido à ruptura ou lesão antiga', 'M23.2 Transt menisco dev ruptura ou lesao antiga'),
  ('M233', 'Outros transtornos do menisco', 'M23.3 Outr transt do menisco'),
  ('M234', 'Corpo flutuante no joelho', 'M23.4 Corpo flutuante no joelho'),
  ('M235', 'Instabilidade crônica do joelho', 'M23.5 Instabilidade cronica do joelho'),
  ('M236', 'Outras rupturas espontâneas de ligamento(s) do joelho', 'M23.6 Outr rupturas espontaneas ligamentos joelho'),
  ('M238', 'Outros transtornos internos do joelho', 'M23.8 Outr transt internos do joelho'),
  ('M239', 'Transtorno interno não especificado do joelho', 'M23.9 Transt interno NE do joelho'),
  ('M24', 'Outros transtornos articulares específicos', 'M24 Outr transt articulares especificos'),
  ('M240', 'Corpo flutuante em articulação', 'M24.0 Corpo flutuante em articulacao'),
  ('M241', 'Outros transtornos das cartilagens articulares', 'M24.1 Outr transt das cartilagens articulares'),
  ('M242', 'Transtornos de ligamentos', 'M24.2 Transt de ligamentos'),
  ('M243', 'Deslocamento e subluxação patológicas de articulação, não classificada em outra parte', 'M24.3 Deslocamento e subluxacao patolog artic NCOP'),
  ('M244', 'Deslocamento e subluxação de articulação recidivantes', 'M24.4 Deslocamento e subluxacao artic recidivantes'),
  ('M245', 'Contratura articular', 'M24.5 Contratura articular'),
  ('M246', 'Ancilose articular', 'M24.6 Ancilose articular'),
  ('M247', 'Protusão do acetábulo', 'M24.7 Protusao do acetabulo'),
  ('M248', 'Outros transtornos articulares específicos, não classificados em outra parte', 'M24.8 Outr transt articulares especificos NCOP'),
  ('M249', 'Desarranjo articular não especificado', 'M24.9 Desarranjo articular NE'),
  ('M25', 'Outros transtornos articulares não classificados em outra parte', 'M25 Outr transt articulares NCOP'),
  ('M250', 'Hemartrose', 'M25.0 Hemartrose'),
  ('M251', 'Fístula articular', 'M25.1 Fistula articular'),
  ('M252', 'Flail joint', 'M25.2 Flail joint'),
  ('M253', 'Outras instabilidades articulares', 'M25.3 Outr instabilidades articulares'),
  ('M254', 'Derrame articular', 'M25.4 Derrame articular'),
  ('M255', 'Dor articular', 'M25.5 Dor articular'),
  ('M256', 'Rigidez articular não classificada em outra parte', 'M25.6 Rigidez articular NCOP'),
  ('M257', 'Osteofito', 'M25.7 Osteofito'),
  ('M258', 'Outros transtornos articulares especificados', 'M25.8 Outr transt articulares espec'),
  ('M259', 'Transtorno articular não especificado', 'M25.9 Transt articular NE'),
  ('M30', 'Poliarterite nodosa e afecções correlatas', 'M30 Poliarterite nodosa e afeccoes correlatas'),
  ('M300', 'Poliarterite nodosa', 'M30.0 Poliarterite nodosa'),
  ('M301', 'Poliarterite com comprometimento pulmonar (Churg-Strauss)', 'M30.1 Poliarterite c/compr pulmonar'),
  ('M302', 'Poliarterite juvenil', 'M30.2 Poliarterite juvenil'),
  ('M303', 'Síndrome de linfonodos mucocutâneos (Kawasaki)', 'M30.3 Sindr de linfonodos mucocutaneos'),
  ('M308', 'Outras afecções comuns na poliarterite nodosa', 'M30.8 Outr afeccoes comuns na poliarterite nodosa'),
  ('M31', 'Outras vasculopatias necrotizantes', 'M31 Outr vasculopatias necrotizantes'),
  ('M310', 'Angeíte de hipersensibilidade', 'M31.0 Angeite de hipersensibilidade'),
  ('M311', 'Microangiopatia trombótica', 'M31.1 Microangiopatia trombotica'),
  ('M312', 'Granuloma da linha média letal', 'M31.2 Granuloma da linha media letal'),
  ('M313', 'Granulomatose de Wegener', 'M31.3 Granulomatose de Wegener'),
  ('M314', 'Síndrome do arco aórtico (Takayasu)', 'M31.4 Sindr do arco aortico'),
  ('M315', 'Arterite de células gigantes com polimialgia reumática', 'M31.5 Arterite celulas gigantes polimialgia reumat'),
  ('M316', 'Outras arterites de células gigantes', 'M31.6 Outr arterites de celulas gigantes'),
  ('M317', 'Poliangeíte microscópica', 'M31.7 Poliangeíte microscópica'),
  ('M318', 'Outras vasculopatias necrotizantes especificadas', 'M31.8 Outr vasculopatias necrotizantes espec'),
  ('M319', 'Vasculopatia necrotizante não especificada', 'M31.9 Vasculopatia necrotizante NE'),
  ('M32', 'Lúpus eritematoso disseminado (sistêmico)', 'M32 Lupus eritematoso disseminado'),
  ('M320', 'Lúpus eritematoso disseminado (sistêmico) induzido por drogas', 'M32.0 Lupus eritematoso disseminado induz p/drogas'),
  ('M321', 'Lúpus eritematoso disseminado (sistêmico) com comprometimento de outros órgãos e sistemas', 'M32.1 Lupus eritematoso dissem compr outr org/sist'),
  ('M328', 'Outras formas de lúpus eritematoso disseminado (sistêmico)', 'M32.8 Outr form de lupus eritematoso disseminado'),
  ('M329', 'Lúpus eritematoso disseminado (sistêmico) não especificado', 'M32.9 Lupus eritematoso disseminado NE'),
  ('M33', 'Dermatopoliomiosite', 'M33 Dermatopoliomiosite'),
  ('M330', 'Dermatomiosite juvenil', 'M33.0 Dermatomiosite juvenil'),
  ('M331', 'Outras dermatomiosites', 'M33.1 Outr dermatomiosites'),
  ('M332', 'Polimiosite', 'M33.2 Polimiosite'),
  ('M339', 'Dermatopolimiosite não especificada', 'M33.9 Dermatopolimiosite NE'),
  ('M34', 'Esclerose sistêmica', 'M34 Esclerose sistemica'),
  ('M340', 'Esclerose sistêmica progressiva', 'M34.0 Esclerose sistemica progressiva'),
  ('M341', 'Síndrome CR(E)ST', 'M34.1 Sindr CREST'),
  ('M342', 'Esclerose sistêmica induzida por droga e substâncias químicas', 'M34.2 Esclerose sistemica induz p/droga subst quim'),
  ('M348', 'Outras formas de esclerose sistêmica', 'M34.8 Outr form de esclerose sistemica'),
  ('M349', 'Esclerose sistêmica não especificada', 'M34.9 Esclerose sistemica NE'),
  ('M35', 'Outras afecções sistêmicas do tecido conjuntivo', 'M35 Outr afeccoes sistemicas do tec conjuntivo'),
  ('M350', 'Síndrome seca (Sjögren)', 'M35.0 Sindr seca'),
  ('M351', 'Outras síndromes superpostas', 'M35.1 Outr sindr superpostas'),
  ('M352', 'Doença de Behçet', 'M35.2 Doenc de Behcet'),
  ('M353', 'Polimialgia reumática', 'M35.3 Polimialgia reumatica'),
  ('M354', 'Fasciíte (eosinofílica) difusa', 'M35.4 Fasciite difusa'),
  ('M355', 'Fibroesclerose multifocal', 'M35.5 Fibroesclerose multifocal'),
  ('M356', 'Paniculite recidivante (Weber-Christian)', 'M35.6 Paniculite recidivante'),
  ('M357', 'Síndrome de hipermobilidade', 'M35.7 Sindr de hipermobilidade'),
  ('M358', 'Outro comprometimento sistêmico especificado do tecido conjuntivo', 'M35.8 Outr compr sistemico espec do tec conjuntivo'),
  ('M359', 'Comprometimento sistêmico não especificado do tecido conjuntivo', 'M35.9 Compr sistemico NE do tec conjuntivo'),
  ('M36', 'Doenças sistêmicas do tecido conjuntivo em doenças classificadas em outra parte', 'M36 Doenc sistemicas do tec conjuntivo doenc COP'),
  ('M360', 'Dermato(poli)miosite em doenças neoplásicas', 'M36.0 Dermatomiosite em doenc neoplasicas'),
  ('M361', 'Artropatia em doenças neoplásicas classificadas', 'M36.1 Artropatia em doenc neoplasicas classif'),
  ('M362', 'Artropatia hemofílica', 'M36.2 Artropatia hemofilica'),
  ('M363', 'Artropatias em outras doenças hematológicas', 'M36.3 Artropatias em outr doenc hematologicas'),
  ('M364', 'Artropatia associada a reações de hipersensibilidade classificadas em outra parte', 'M36.4 Artropatia assoc reacoes hipersensib COP'),
  ('M368', 'Doenças sistêmicas do tecido conjuntivo em outras doenças classificadas em outra parte', 'M36.8 Doenc sistemicas tec conjunt outr doenc COP'),
  ('M40', 'Cifose e lordose', 'M40 Cifose e lordose'),
  ('M400', 'Cifose postural', 'M40.0 Cifose postural'),
  ('M401', 'Outras cifoses secundárias', 'M40.1 Outr cifoses secund'),
  ('M402', 'Outras cifoses e as não especificadas', 'M40.2 Outr cifoses e as NE'),
  ('M403', 'Síndrome da retificação da coluna vertebral', 'M40.3 Sindr da retificacao da coluna vertebral'),
  ('M404', 'Outras lordoses', 'M40.4 Outr lordoses'),
  ('M405', 'Lordose não especificada', 'M40.5 Lordose NE'),
  ('M41', 'Escoliose', 'M41 Escoliose'),
  ('M410', 'Escoliose idiopática infantil', 'M41.0 Escoliose idiopatica infantil'),
  ('M411', 'Escoliose idiopática juvenil', 'M41.1 Escoliose idiopatica juvenil'),
  ('M412', 'Outras escolioses idiopáticas', 'M41.2 Outr escolioses idiopaticas'),
  ('M413', 'Escoliose toracogênica', 'M41.3 Escoliose toracogenica'),
  ('M414', 'Escoliose neuromuscular', 'M41.4 Escoliose neuromuscular'),
  ('M415', 'Outras escolioses secundárias', 'M41.5 Outr escolioses secund'),
  ('M418', 'Outras formas de escoliose', 'M41.8 Outr form de escoliose'),
  ('M419', 'Escoliose não especificada', 'M41.9 Escoliose NE'),
  ('M42', 'Osteocondrose da coluna vertebral', 'M42 Osteocondrose da coluna vertebral'),
  ('M420', 'Osteocondrose vertebral juvenil', 'M42.0 Osteocondrose vertebral juvenil'),
  ('M421', 'Osteocondrose vertebral do adulto', 'M42.1 Osteocondrose vertebral do adulto'),
  ('M429', 'Osteocondrose vertebral, não especificada', 'M42.9 Osteocondrose vertebral NE'),
  ('M43', 'Outras dorsopatias deformantes', 'M43 Outr dorsopatias deformantes'),
  ('M430', 'Espondilólise', 'M43.0 Espondilolise'),
  ('M431', 'Espondilolistese', 'M43.1 Espondilolistese'),
  ('M432', 'Outras fusões da coluna vertebral', 'M43.2 Outr fusoes da coluna vertebral'),
  ('M433', 'Subluxação atlanto-axial recidivante com mielopatia', 'M43.3 Subluxacao atlanto-axial recidiv mielopatia'),
  ('M434', 'Outras subluxações atlanto-axiais recidivantes', 'M43.4 Outr subluxacoes atlanto-axiais recidivantes'),
  ('M435', 'Outras subluxações vertebrais recidivantes', 'M43.5 Outr subluxacoes vertebrais recidivantes'),
  ('M436', 'Torcicolo', 'M43.6 Torcicolo'),
  ('M438', 'Outras dorsopatias deformantes especificadas', 'M43.8 Outr dorsopatias deformantes espec'),
  ('M439', 'Dorsopatia deformante, não especificada', 'M43.9 Dorsopatia deformante NE'),
  ('M45', 'Espondilite ancilosante', 'M45 Espondilite ancilosante'),
  ('M45', 'Espondilite ancilosante', 'M45 Espondilite ancilosante'),
  ('M46', 'Outras espondilopatias inflamatórias', 'M46 Outr espondilopatias inflam'),
  ('M460', 'Entesopatia vertebral', 'M46.0 Entesopatia vertebral'),
  ('M461', 'Sacroileíte não classificada em outra parte', 'M46.1 Sacroileite NCOP'),
  ('M462', 'Osteomielite das vértebras', 'M46.2 Osteomielite das vertebras'),
  ('M463', 'Infecção (piogênica) do disco intervertebral', 'M46.3 Infecc do disco intervertebral'),
  ('M464', 'Discite não especificada', 'M46.4 Discite NE'),
  ('M465', 'Outras espondilopatias infecciosas', 'M46.5 Outr espondilopatias infecc'),
  ('M468', 'Outras espondilopatias inflamatórias especificadas', 'M46.8 Outr espondilopatias inflam espec'),
  ('M469', 'Espondilopatia inflamatória não especificada', 'M46.9 Espondilopatia inflam NE'),
  ('M47', 'Espondilose', 'M47 Espondilose'),
  ('M470', 'Síndromes de compressão da artéria espinhal anterior ou vertebral anterior', 'M47.0 Sindr compress art espinhal ant ou vert ant'),
  ('M471', 'Outras espondiloses com mielopatia', 'M47.1 Outr espondiloses c/mielopatia'),
  ('M472', 'Outras espondiloses com radiculopatias', 'M47.2 Outr espondiloses c/radiculopatias'),
  ('M478', 'Outras espondiloses', 'M47.8 Outr espondiloses'),
  ('M479', 'Espondilose não especificada', 'M47.9 Espondilose NE'),
  ('M48', 'Outras espondilopatias', 'M48 Outr espondilopatias'),
  ('M480', 'Estenose da coluna vertebral', 'M48.0 Estenose da coluna vertebral'),
  ('M481', 'Hiperostose ancilosante (Forestier)', 'M48.1 Hiperostose ancilosante'),
  ('M482', 'Kissing spine', 'M48.2 Kissing spine'),
  ('M483', 'Espondilopatia traumática', 'M48.3 Espondilopatia traum'),
  ('M484', 'Fratura de fadiga de vértebra', 'M48.4 Frat de fadiga de vertebra'),
  ('M485', 'Vértebra colapsada não classificada em outra parte', 'M48.5 Vertebra colapsada NCOP'),
  ('M488', 'Outras espondilopatias especificadas', 'M48.8 Outr espondilopatias espec'),
  ('M489', 'Espondilopatia não especificada', 'M48.9 Espondilopatia NE'),
  ('M49', 'Espondilopatias em doenças classificadas em outra parte', 'M49 Espondilopatias em doenc COP'),
  ('M490', 'Tuberculose da coluna vertebral', 'M49.0 Tuberc da coluna vertebral'),
  ('M491', 'Espondilite por Brucella', 'M49.1 Espondilite p/Brucella'),
  ('M492', 'Espondilite por enterobactérias', 'M49.2 Espondilite p/enterobacterias'),
  ('M493', 'Espondilopatia em outras doenças infeciosas e parasitárias classificadas em outra parte', 'M49.3 Espondilopatia outr doenc infecc parasit COP'),
  ('M494', 'Espondilopatia neuropática', 'M49.4 Espondilopatia neuropatica'),
  ('M495', 'Vértebra colapsada em doenças classificadas em outra parte', 'M49.5 Vertebra colapsada em doenc COP'),
  ('M498', 'Espondilopatia em outras doenças classificadas em outra parte', 'M49.8 Espondilopatia outr doenc COP'),
  ('M50', 'Transtornos dos discos cervicais', 'M50 Transt dos discos cervicais'),
  ('M500', 'Transtorno do disco cervical com mielopatia', 'M50.0 Transt do disco cervical c/mielopatia'),
  ('M501', 'Transtorno do disco cervical com radiculopatia', 'M50.1 Transt do disco cervical c/radiculopatia'),
  ('M502', 'Outro deslocamento de disco cervical', 'M50.2 Outr deslocamento de disco cervical'),
  ('M503', 'Outra degeneração de disco cervical', 'M50.3 Outr degeneracao de disco cervical'),
  ('M508', 'Outros transtornos de discos cervicais', 'M50.8 Outr transt de discos cervicais'),
  ('M509', 'Transtorno não especificado de disco cervical', 'M50.9 Transt NE de disco cervical'),
  ('M51', 'Outros transtornos de discos intervertebrais', 'M51 Outr transt de discos intervertebrais'),
  ('M510', 'Transtornos de discos lombares e de outros discos intervertebrais com mielopatia', 'M51.0 Transt disco lombar outr intervert mielopat'),
  ('M511', 'Transtornos de discos lombares e de outros discos intervertebrais com radiculopatia', 'M51.1 Transt disco lombar outr intervert radiculop'),
  ('M512', 'Outros deslocamentos discais intervertebrais especificados', 'M51.2 Outr desloc discais intervertebrais espec'),
  ('M513', 'Outra degeneração especificada de disco intervertebral', 'M51.3 Outr degeneracao espec disco intervertebral'),
  ('M514', 'Nódulos de Schmorl', 'M51.4 Nodulos de Schmorl'),
  ('M518', 'Outros transtornos especificados de discos intervertebrais', 'M51.8 Outr transt espec de discos intervertebrais'),
  ('M519', 'Transtorno não especificado de disco intervertebral', 'M51.9 Transt NE de disco intervertebral'),
  ('M53', 'Outras dorsopatias não classificadas em outra parte', 'M53 Outr dorsopatias NCOP'),
  ('M530', 'Síndrome cervicocraniana', 'M53.0 Sindr cervicocraniana'),
  ('M531', 'Síndrome cervicobraquial', 'M53.1 Sindr cervicobraquial'),
  ('M532', 'Instabilidades da coluna vertebral', 'M53.2 Instabilidades da coluna vertebral'),
  ('M533', 'Transtornos sacroccígeos não classificados em outra parte', 'M53.3 Transt sacroccigeos NCOP'),
  ('M538', 'Outras dorsopatias especificadas', 'M53.8 Outr dorsopatias espec'),
  ('M539', 'Dorsopatia não especificada', 'M53.9 Dorsopatia NE'),
  ('M54', 'Dorsalgia', 'M54 Dorsalgia'),
  ('M540', 'Paniculite atingindo regiões do pescoço e do dorso', 'M54.0 Paniculite atingindo regioes pescoco e dorso'),
  ('M541', 'Radiculopatia', 'M54.1 Radiculopatia'),
  ('M542', 'Cervicalgia', 'M54.2 Cervicalgia'),
  ('M543', 'Ciática', 'M54.3 Ciatica'),
  ('M544', 'Lumbago com ciática', 'M54.4 Lumbago c/ciatica'),
  ('M545', 'Dor lombar baixa', 'M54.5 Dor lombar baixa'),
  ('M546', 'Dor na coluna torácica', 'M54.6 Dor na coluna toracica'),
  ('M548', 'Outra dorsalgia', 'M54.8 Outr dorsalgia'),
  ('M549', 'Dorsalgia não especificada', 'M54.9 Dorsalgia NE'),
  ('M60', 'Miosite', 'M60 Miosite'),
  ('M600', 'Miosite infecciosa', 'M60.0 Miosite infecc'),
  ('M601', 'Miosite intersticial', 'M60.1 Miosite intersticial'),
  ('M602', 'Granuloma de corpo estranho no tecido mole não classificado em outra parte', 'M60.2 Granuloma de corpo estranho no tec mole NCOP'),
  ('M608', 'Outras miosites', 'M60.8 Outr miosites'),
  ('M609', 'Miosite não especificada', 'M60.9 Miosite NE'),
  ('M61', 'Calcificação e ossificação do músculo', 'M61 Calcificacao e ossificacao do musculo'),
  ('M610', 'Miosite ossificante traumática', 'M61.0 Miosite ossificante traum'),
  ('M611', 'Miosite ossificante progressiva', 'M61.1 Miosite ossificante progressiva'),
  ('M612', 'Calcificação e ossificação paralítica de músculo', 'M61.2 Calcificacao e ossificacao paralit musculo'),
  ('M613', 'Calcificação e ossificação de músculo associadas com queimaduras', 'M61.3 Calcificacao e ossificacao musc assoc queim'),
  ('M614', 'Outra calcificação de músculo', 'M61.4 Outr calcificacao de musculo'),
  ('M615', 'Outra ossificação de músculo', 'M61.5 Outr ossificacao de musculo'),
  ('M619', 'Calcificação e ossificação de músculo não especificada', 'M61.9 Calcificacao e ossificacao de musculo NE'),
  ('M62', 'Outros transtornos musculares', 'M62 Outr transt musculares'),
  ('M620', 'Diástase de músculo', 'M62.0 Diastase de musculo'),
  ('M621', 'Outras rupturas musculares (não-traumáticas)', 'M62.1 Outr rupturas musculares'),
  ('M622', 'Infarto isquêmico do músculo', 'M62.2 Infarto isquemico do musculo'),
  ('M623', 'Síndrome de imobilidade (paraplégica)', 'M62.3 Sindr de imobilidade'),
  ('M624', 'Contratura de músculo', 'M62.4 Contratura de musculo'),
  ('M625', 'Perda e atrofia muscular não classificadas em outra parte', 'M62.5 Perda e atrofia muscular NCOP'),
  ('M626', 'Distensão muscular', 'M62.6 Distensao muscular'),
  ('M628', 'Outros transtornos musculares especificados', 'M62.8 Outr transt musculares espec'),
  ('M629', 'Transtorno muscular não especificado', 'M62.9 Transt muscular NE'),
  ('M63', 'Transtornos de músculo em doenças classificadas em outra parte', 'M63 Transt de musculo em doenc COP'),
  ('M630', 'Miosite em doenças bacterianas classificadas em outra parte', 'M63.0 Miosite em doenc bacter COP'),
  ('M631', 'Miosite em doenças infecciosas causadas por protozoários e parasitas classificadas em outra parte', 'M63.1 Miosite doenc infecc caus protoz parasit COP'),
  ('M632', 'Miosite em outras doenças infecciosas classificadas em outra parte', 'M63.2 Miosite em outr doenc infecc COP'),
  ('M633', 'Miosite na sarcoidose', 'M63.3 Miosite na sarcoidose'),
  ('M638', 'Outros transtornos musculares em doenças classificadas em outra parte', 'M63.8 Outr transt musculares em doenc COP'),
  ('M65', 'Sinovite e tenossinovite', 'M65 Sinovite e tenossinovite'),
  ('M650', 'Abscesso da bainha tendínea', 'M65.0 Abscesso da bainha tendinea'),
  ('M651', 'Outras (teno)sinovites infecciosas', 'M65.1 Outr sinovites infecc'),
  ('M652', 'Tendinite calcificada', 'M65.2 Tendinite calcificada'),
  ('M653', 'Dedo em gatilho', 'M65.3 Dedo em gatilho'),
  ('M654', 'Tenossinovite estilóide radial (de Quervain)', 'M65.4 Tenossinovite estiloide radial'),
  ('M658', 'Outras sinovites e tenossinovites', 'M65.8 Outr sinovites e tenossinovites'),
  ('M659', 'Sinovite e tenossinovite não especificadas', 'M65.9 Sinovite e tenossinovite NE'),
  ('M66', 'Ruptura espontânea de sinóvia e de tendão', 'M66 Ruptura espontanea de sinovia e de tendao'),
  ('M660', 'Ruptura de cisto poplíteo', 'M66.0 Ruptura de cisto popliteo'),
  ('M661', 'Ruptura de sinóvia', 'M66.1 Ruptura de sinovia'),
  ('M662', 'Ruptura espontânea de tendões extensores', 'M66.2 Ruptura espontanea de tendoes extensores'),
  ('M663', 'Ruptura espontânea de tendões flexores', 'M66.3 Ruptura espontanea de tendoes flexores'),
  ('M664', 'Ruptura espontânea de outros tendões', 'M66.4 Ruptura espontanea de outr tendoes'),
  ('M665', 'Ruptura espontânea de tendões não especificados', 'M66.5 Ruptura espontanea de tendoes NE'),
  ('M67', 'Outros transtornos das sinóvias e dos tendões', 'M67 Outr transt das sinovias e dos tendoes'),
  ('M670', 'Tendão de Aquiles curto (adquirido)', 'M67.0 Tendao de Aquiles curto'),
  ('M671', 'Outra contratura de tendão (bainha)', 'M67.1 Outr contratura de tendao'),
  ('M672', 'Hipertrofia sinovial não classificada em outra parte', 'M67.2 Hipertrofia sinovial NCOP'),
  ('M673', 'Sinovite transitória', 'M67.3 Sinovite transitoria'),
  ('M674', 'Gânglios', 'M67.4 Ganglios'),
  ('M678', 'Outros transtornos especificados da sinóvia e do tendão', 'M67.8 Outr transt espec da sinovia e do tendao'),
  ('M679', 'Transtorno não especificado da sinóvia e do tendão', 'M67.9 Transt NE da sinovia e do tendao'),
  ('M68', 'Transtorno de sinóvias e de tendões em doenças classificadas em outra parte', 'M68 Transt de sinovias e de tendoes em doenc COP'),
  ('M680', 'Sinovite e tenossinovite em doenças bacterianas classificadas em outra parte', 'M68.0 Sinovite e tenossinovite doenc bacter COP'),
  ('M688', 'Outros transtornos de sinóvias e de tendões em doenças classificadas em outra parte', 'M68.8 Outr transt sinovias e tendoes em doenc COP'),
  ('M70', 'Transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão', 'M70 Transt tec moles relac uso excess e pressao'),
  ('M700', 'Sinovite crepitante crônica da mão e do punho', 'M70.0 Sinovite crepitante cronica da mao e punho'),
  ('M701', 'Bursite da mão', 'M70.1 Bursite da mao'),
  ('M702', 'Bursite do olécrano', 'M70.2 Bursite do olecrano'),
  ('M703', 'Outras bursites do cotovelo', 'M70.3 Outr bursites do cotovelo'),
  ('M704', 'Bursite pré-patelar', 'M70.4 Bursite pre-patelar'),
  ('M705', 'Outras bursites do joelho', 'M70.5 Outr bursites do joelho'),
  ('M706', 'Bursite trocantérica', 'M70.6 Bursite trocanterica'),
  ('M707', 'Outras bursites do quadril', 'M70.7 Outr bursites do quadril'),
  ('M708', 'Outros transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão', 'M70.8 Outr transt tec moles relac uso excess press'),
  ('M709', 'Transtorno não especificado dos tecidos moles relacionados com o uso, uso excessivo e pressão', 'M70.9 Transt NE tec moles relac uso excess pressao'),
  ('M71', 'Outras bursopatias', 'M71 Outr bursopatias'),
  ('M710', 'Abscesso de bolsa sinovial', 'M71.0 Abscesso de bolsa sinovial'),
  ('M711', 'Outras bursites infecciosas', 'M71.1 Outr bursites infecc'),
  ('M712', 'Cisto sinovial do espaço poplíteo (Baker)', 'M71.2 Cisto sinovial do espaco popliteo'),
  ('M713', 'Outros cistos de bolsa sinovial', 'M71.3 Outr cistos de bolsa sinovial'),
  ('M714', 'Depósito de cálcio em bolsa sinovial', 'M71.4 Deposito de calcio em bolsa sinovial'),
  ('M715', 'Outras bursites não classificadas em outra parte', 'M71.5 Outr bursites NCOP'),
  ('M718', 'Outras bursopatias especificadas', 'M71.8 Outr bursopatias espec'),
  ('M719', 'Bursopatia não especificada', 'M71.9 Bursopatia NE'),
  ('M72', 'Transtornos fibroblásticos', 'M72 Transt fibroblasticos'),
  ('M720', 'Fibromatose de fáscia palmar (Dupuytren)', 'M72.0 Fibromatose de fascia palmar'),
  ('M721', 'Coxins interfalângicos (nó dos dedos)', 'M72.1 Coxins interfalangicos'),
  ('M722', 'Fibromatose da fáscia plantar', 'M72.2 Fibromatose da fascia plantar'),
  ('M724', 'Fibromatose pseudossarcomatosa', 'M72.4 Fibromatose pseudossarcomatosa'),
  ('M726', 'Fasciíte necrosante', 'M72.6 Fasciite necrosante'),
  ('M728', 'Outros transtornos fibroblásticos', 'M72.8 Outr transt fibroblasticos'),
  ('M729', 'Transtorno fibroblástico não especificado', 'M72.9 Transt fibroblastico NE'),
  ('M73', 'Transtornos dos tecidos moles em doenças classificadas em outra parte', 'M73 Transt dos tec moles em doenc COP'),
  ('M730', 'Bursite gonocócica', 'M73.0 Bursite gonococica'),
  ('M731', 'Bursite sifilítica', 'M73.1 Bursite sifilitica'),
  ('M738', 'Outros transtornos dos tecidos moles em outras doenças classificadas em outra parte', 'M73.8 Outr transt dos tec moles em outr doenc COP'),
  ('M75', 'Lesões do ombro', 'M75 Lesoes do ombro'),
  ('M750', 'Capsulite adesiva do ombro', 'M75.0 Capsulite adesiva do ombro'),
  ('M751', 'Síndrome do manguito rotador', 'M75.1 Sindr do manguito rotador'),
  ('M752', 'Tendinite bicepital', 'M75.2 Tendinite bicepital'),
  ('M753', 'Tendinite calcificante do ombro', 'M75.3 Tendinite calcificante do ombro'),
  ('M754', 'Síndrome de colisão do ombro', 'M75.4 Sindr de colis do ombro'),
  ('M755', 'Bursite do ombro', 'M75.5 Bursite do ombro'),
  ('M758', 'Outras lesões do ombro', 'M75.8 Outr lesoes do ombro'),
  ('M759', 'Lesão não especificada do ombro', 'M75.9 Lesao NE do ombro'),
  ('M76', 'Entesopatias dos membros inferiores, excluindo pé', 'M76 Entesopatias dos membros infer excl pe'),
  ('M760', 'Tendinite glútea', 'M76.0 Tendinite glutea'),
  ('M761', 'Tendinite do psoas', 'M76.1 Tendinite do psoas'),
  ('M762', 'Esporão da crista ilíaca', 'M76.2 Esporao da crista iliaca'),
  ('M763', 'Síndrome da faixa iliotibial', 'M76.3 Sindr da faixa iliotibial'),
  ('M764', 'Bursite tibial colateral (Pellegrini-Stieda)', 'M76.4 Bursite tibial colateral'),
  ('M765', 'Tendinite patelar', 'M76.5 Tendinite patelar'),
  ('M766', 'Tendinite aquileana', 'M76.6 Tendinite aquileana'),
  ('M767', 'Tendinite do perôneo', 'M76.7 Tendinite do peroneo'),
  ('M768', 'Outras entesopatias do membro inferior, excluindo o pé', 'M76.8 Outr entesopatias do membro infer excl o pe'),
  ('M769', 'Entesopatia do membro inferior não especificada', 'M76.9 Entesopatia do membro infer NE'),
  ('M77', 'Outras entesopatias', 'M77 Outr entesopatias'),
  ('M770', 'Epicondilite medial', 'M77.0 Epicondilite medial'),
  ('M771', 'Epicondilite lateral', 'M77.1 Epicondilite lateral'),
  ('M772', 'Periartrite do punho', 'M77.2 Periartrite do punho'),
  ('M773', 'Esporão do calcâneo', 'M77.3 Esporao do calcaneo'),
  ('M774', 'Metatarsalgia', 'M77.4 Metatarsalgia'),
  ('M775', 'Outra entesopatia do pé', 'M77.5 Outr entesopatia do pe'),
  ('M778', 'Outras entesopatias não classificadas em outra parte', 'M77.8 Outr entesopatias NCOP'),
  ('M779', 'Entesopatia não especificada', 'M77.9 Entesopatia NE'),
  ('M79', 'Outros transtornos dos tecidos moles, não classificados em outra parte', 'M79 Outr transt dos tec moles NCOP'),
  ('M790', 'Reumatismo não especificado', 'M79.0 Reumatismo NE'),
  ('M791', 'Mialgia', 'M79.1 Mialgia'),
  ('M792', 'Nevralgia e neurite não especificadas', 'M79.2 Nevralgia e neurite NE'),
  ('M793', 'Paniculite não especificada', 'M79.3 Paniculite NE'),
  ('M794', 'Hipertrofia do coxim gorduroso (infrapatelar)', 'M79.4 Hipertrofia do coxim gorduroso'),
  ('M795', 'Corpo estranho residual no tecido mole', 'M79.5 Corpo estranho residual no tec mole'),
  ('M796', 'Dor em membro', 'M79.6 Dor em membro'),
  ('M797', 'Fibromialgia', 'M79.7 Fibromialgia'),
  ('M798', 'Outros transtornos especificados dos tecidos moles', 'M79.8 Outr transt espec dos tec moles'),
  ('M799', 'Transtorno dos tecidos moles não especificado', 'M79.9 Transt dos tec moles NE'),
  ('M80', 'Osteoporose com fratura patológica', 'M80 Osteoporose c/frat patologica'),
  ('M800', 'Osteoporose pós-menopáusica com fratura patológica', 'M80.0 Osteoporose pos-menopausica c/frat patolog'),
  ('M801', 'Osteoporose pós-ooforectomia com fratura patológica', 'M80.1 Osteoporose pos-ooforectomia c/frat patolog'),
  ('M802', 'Osteoporose de desuso com fratura patológica', 'M80.2 Osteoporose de desuso c/frat patologica'),
  ('M803', 'Osteoporose por má-absorção pós-cirúrgica com fratura patológica', 'M80.3 Osteoporose ma-absorc pos-cirurg frat patol'),
  ('M804', 'Osteoporose induzida por drogas com fratura patológica', 'M80.4 Osteoporose induz p/drogas c/frat patologica'),
  ('M805', 'Osteoporose idiopática com fratura patológica', 'M80.5 Osteoporose idiopatica c/frat patologica'),
  ('M808', 'Outras osteoporoses com fratura patológica', 'M80.8 Outr osteoporoses c/frat patologica'),
  ('M809', 'Osteoporose não especificada com fratura patológica', 'M80.9 Osteoporose NE c/frat patologica'),
  ('M81', 'Osteoporose sem fratura patológica', 'M81 Osteoporose s/frat patologica'),
  ('M810', 'Osteoporose pós-menopáusica', 'M81.0 Osteoporose pos-menopausica'),
  ('M811', 'Osteoporose pós-ooforectomia', 'M81.1 Osteoporose pos-ooforectomia'),
  ('M812', 'Osteoporose de desuso', 'M81.2 Osteoporose de desuso'),
  ('M813', 'Osteoporose devida à má-absorção pós-cirúrgica', 'M81.3 Osteoporose dev ma-absorcao pos-cirurgica'),
  ('M814', 'Osteoporose induzida por drogas', 'M81.4 Osteoporose induz p/drogas'),
  ('M815', 'Osteoporose idiopática', 'M81.5 Osteoporose idiopatica'),
  ('M816', 'Osteoporose localizada (Lequesne)', 'M81.6 Osteoporose localizada'),
  ('M818', 'Outras osteoporoses', 'M81.8 Outr osteoporoses'),
  ('M819', 'Osteoporose não especificada', 'M81.9 Osteoporose NE'),
  ('M82', 'Osteoporose em doenças classificadas em outra parte', 'M82 Osteoporose em doenc COP'),
  ('M820', 'Osteoporose na mielomatose múltipla', 'M82.0 Osteoporose na mielomatose mult'),
  ('M821', 'Osteoporose em distúrbios endócrinos', 'M82.1 Osteoporose em disturbios endocrinos'),
  ('M828', 'Osteoporose em outras doenças classificadas em outra parte', 'M82.8 Osteoporose em outr doenc COP'),
  ('M83', 'Osteomalácia do adulto', 'M83 Osteomalacia do adulto'),
  ('M830', 'Osteomalácia puerperal', 'M83.0 Osteomalacia puerperal'),
  ('M831', 'Osteomalácia senil', 'M83.1 Osteomalacia senil'),
  ('M832', 'Osteomalácia do adulto devida a má-absorção', 'M83.2 Osteomalacia do adulto dev ma-absorcao'),
  ('M833', 'Osteomalácia do adulto devido à desnutrição', 'M83.3 Osteomalacia do adulto dev desnutric'),
  ('M834', 'Doença óssea pelo alumínio', 'M83.4 Doenc ossea p/aluminio'),
  ('M835', 'Outras osteomalácias do adulto induzidas por drogas', 'M83.5 Outr osteomalacias do adulto induz p/drogas'),
  ('M838', 'Outra osteomalácia do adulto', 'M83.8 Outr osteomalacia do adulto'),
  ('M839', 'Osteomalácia não especificada do adulto', 'M83.9 Osteomalacia NE do adulto'),
  ('M84', 'Transtornos da continuidade do osso', 'M84 Transt da continuidade do osso'),
  ('M840', 'Defeito de consolidação da fratura', 'M84.0 Defeito de consolidacao da frat'),
  ('M841', 'Ausência de consolidação da fratura (pseudo-artrose)', 'M84.1 Ausencia de consolidacao da frat'),
  ('M842', 'Atraso de consolidação de fratura', 'M84.2 Atraso de consolidacao de frat'),
  ('M843', 'Fratura de fadiga (stress) não classificada em outra parte', 'M84.3 Frat de fadiga NCOP'),
  ('M844', 'Fratura patológica não classificada em outra parte', 'M84.4 Frat patologica NCOP'),
  ('M848', 'Outros transtornos da continuidade do osso', 'M84.8 Outr transt da continuidade do osso'),
  ('M849', 'Transtorno não especificado da continuidade do osso', 'M84.9 Transt NE da continuidade do osso'),
  ('M85', 'Outros transtornos da densidade e da estrutura ósseas', 'M85 Outr transt da densidade e estrutura osseas'),
  ('M850', 'Displasia fibrosa (monostótica)', 'M85.0 Displasia fibrosa'),
  ('M851', 'Fluorose esquelética', 'M85.1 Fluorose esqueletica'),
  ('M852', 'Hiperostose do crânio', 'M85.2 Hiperostose do cranio'),
  ('M853', 'Osteíte condensante', 'M85.3 Osteite condensante'),
  ('M854', 'Cisto ósseo solitário', 'M85.4 Cisto osseo solitario'),
  ('M855', 'Cisto ósseo aneurismático', 'M85.5 Cisto osseo aneurismatico'),
  ('M856', 'Outro cisto ósseo', 'M85.6 Outr cisto osseo'),
  ('M858', 'Outros transtornos especificados da densidade e da estrutura ósseas', 'M85.8 Outr transt espec densidade estrutura osseas'),
  ('M859', 'Transtorno não especificado da densidade e da estrutura ósseas', 'M85.9 Transt NE densidade estrutura osseas'),
  ('M86', 'Osteomielite', 'M86 Osteomielite'),
  ('M860', 'Osteomielite aguda hematogênica', 'M86.0 Osteomielite aguda hematogenica'),
  ('M861', 'Outra osteomielite aguda', 'M86.1 Outr osteomielite aguda'),
  ('M862', 'Osteomielite subaguda', 'M86.2 Osteomielite subaguda'),
  ('M863', 'Osteomielite crônica multifocal', 'M86.3 Osteomielite cronica multifocal'),
  ('M864', 'Osteomielite crônica com seio drenante', 'M86.4 Osteomielite cronica c/seio drenante'),
  ('M865', 'Outra osteomielite crônica hematogênica', 'M86.5 Outr osteomielite cronica hematogenica'),
  ('M866', 'Outra osteomielite crônica', 'M86.6 Outr osteomielite cronica'),
  ('M868', 'Outra osteomielite', 'M86.8 Outr osteomielite'),
  ('M869', 'Osteomielite não especificada', 'M86.9 Osteomielite NE'),
  ('M87', 'Osteonecrose', 'M87 Osteonecrose'),
  ('M870', 'Necrose asséptica idiopática do osso', 'M87.0 Necrose asseptica idiopatica do osso'),
  ('M871', 'Osteonecrose devida a drogas', 'M87.1 Osteonecrose dev drogas'),
  ('M872', 'Osteonecrose devida a traumatismo anterior', 'M87.2 Osteonecrose dev traum anterior'),
  ('M873', 'Outras osteonecroses secundárias', 'M87.3 Outr osteonecroses secund'),
  ('M878', 'Outras osteonecroses', 'M87.8 Outr osteonecroses'),
  ('M879', 'Osteonecrose não especificada', 'M87.9 Osteonecrose NE'),
  ('M88', 'Doença de Paget do osso (osteíte deformante)', 'M88 Doenc de Paget do osso'),
  ('M880', 'Doença de Paget do crânio', 'M88.0 Doenc de Paget do cranio'),
  ('M888', 'Doença de Paget de outros ossos', 'M88.8 Doenc de Paget de outr ossos'),
  ('M889', 'Doença de Paget de osso não especificado', 'M88.9 Doenc de Paget de osso NE'),
  ('M89', 'Outros transtornos ósseos', 'M89 Outr transt osseos'),
  ('M890', 'Algoneurodistrofia', 'M89.0 Algoneurodistrofia'),
  ('M891', 'Parada de crescimento epifisário', 'M89.1 Parada de crescimento epifisario'),
  ('M892', 'Outros transtornos do desenvolvimento e do crescimento ósseo', 'M89.2 Outr transt desenvolv e crescimento osseo'),
  ('M893', 'Hipertrofia óssea', 'M89.3 Hipertrofia ossea'),
  ('M894', 'Outras osteoartropatias hipertróficas', 'M89.4 Outr osteoartropatias hipertroficas'),
  ('M895', 'Osteolise', 'M89.5 Osteolise'),
  ('M896', 'Osteopatia pós-poliomielite', 'M89.6 Osteopatia pos-poliomielite'),
  ('M898', 'Outros transtornos especificados do osso', 'M89.8 Outr transt espec do osso'),
  ('M899', 'Transtorno não especificado do osso', 'M89.9 Transt NE do osso'),
  ('M90', 'Osteopatias em doenças classificadas em outra parte', 'M90 Osteopatias em doenc COP'),
  ('M900', 'Tuberculose óssea', 'M90.0 Tuberc ossea'),
  ('M901', 'Periostite em outras doenças infecciosas classificadas em outra parte', 'M90.1 Periostite em outr doenc infecc COP'),
  ('M902', 'Osteopatia em outras doenças infecciosas classificadas em outra parte', 'M90.2 Osteopatia em outr doenc infecc COP'),
  ('M903', 'Osteonecrose em mal dos caixões', 'M90.3 Osteonecrose em mal dos caixoes'),
  ('M904', 'Osteonecrose devida à hemoglobinopatia', 'M90.4 Osteonecrose dev hemoglobinopatia'),
  ('M905', 'Osteonecrose em outras doenças classificadas em outra parte', 'M90.5 Osteonecrose em outr doenc COP'),
  ('M906', 'Osteíte deformante em doenças neoplásicas', 'M90.6 Osteite deformante em doenc neoplasicas'),
  ('M907', 'Fratura óssea em doenças neoplásicas', 'M90.7 Frat ossea em doenc neoplasicas'),
  ('M908', 'Osteopatia em outras doenças classificadas em outra parte', 'M90.8 Osteopatia em outr doenc COP'),
  ('M91', 'Osteocondrose juvenil do quadril e da pelve', 'M91 Osteocondrose juvenil do quadril e da pelve'),
  ('M910', 'Osteocondrose juvenil da pelve', 'M91.0 Osteocondrose juvenil da pelve'),
  ('M911', 'Osteocondrose juvenil da cabeça do fêmur (Legg-Calvé-Perthes)', 'M91.1 Osteocondrose juvenil da cabeca do femur'),
  ('M912', 'Coxa plana', 'M91.2 Coxa plana'),
  ('M913', 'Pseudocoxalgia', 'M91.3 Pseudocoxalgia'),
  ('M918', 'Outras osteocondroses juvenis do quadril e da pelve', 'M91.8 Outr osteocondroses juvenis quadril e pelve'),
  ('M919', 'Osteocondrose juvenil não especificada do quadril e da pelve', 'M91.9 Osteocondrose juvenil NE quadril e pelve'),
  ('M92', 'Outras osteocondroses juvenis', 'M92 Outr osteocondroses juvenis'),
  ('M920', 'Osteocondrose juvenil do úmero', 'M92.0 Osteocondrose juvenil do umero'),
  ('M921', 'Osteocondrose juvenil do rádio e do cúbito (ulna)', 'M92.1 Osteocondrose juvenil do radio e do cubito'),
  ('M922', 'Osteocondrose juvenil da mão', 'M92.2 Osteocondrose juvenil da mao'),
  ('M923', 'Outras osteocondroses juvenis do membro superior', 'M92.3 Outr osteocondroses juvenis do membro super'),
  ('M924', 'Osteocondrose juvenil da rótula (patela)', 'M92.4 Osteocondrose juvenil da rotula'),
  ('M925', 'Osteocondrose juvenil da tíbia e perônio (fíbula)', 'M92.5 Osteocondrose juvenil da tibia e peronio'),
  ('M926', 'Osteocondrose juvenil do tarso', 'M92.6 Osteocondrose juvenil do tarso'),
  ('M927', 'Osteocondrose juvenil do metatarso', 'M92.7 Osteocondrose juvenil do metatarso'),
  ('M928', 'Outras osteocondroses juvenis especificadas', 'M92.8 Outr osteocondroses juvenis espec'),
  ('M929', 'Osteocondrose juvenil, não especificada', 'M92.9 Osteocondrose juvenil NE'),
  ('M93', 'Outras osteocondropatias', 'M93 Outr osteocondropatias'),
  ('M930', 'Luxação (não-traumática) da epífise superior do fêmur', 'M93.0 Luxacao da epifise super do femur'),
  ('M931', 'Doença de Kienböck do adulto', 'M93.1 Doenc de Kienbock do adulto'),
  ('M932', 'Osteocondrite dissecante', 'M93.2 Osteocondrite dissecante'),
  ('M938', 'Outras osteocondropatias, especificadas', 'M93.8 Outr osteocondropatias espec'),
  ('M939', 'Osteocondropatias, não especificada', 'M93.9 Osteocondropatias NE'),
  ('M94', 'Outros transtornos das cartilagens', 'M94 Outr transt das cartilagens'),
  ('M940', 'Síndrome da junção condrocostal (Tietze)', 'M94.0 Sindr da juncao condrocostal'),
  ('M941', 'Policondrite recidivante', 'M94.1 Policondrite recidivante'),
  ('M942', 'Condromalácia', 'M94.2 Condromalacia'),
  ('M943', 'Condrolise', 'M94.3 Condrolise'),
  ('M948', 'Outros transtornos especificados da cartilagem', 'M94.8 Outr transt espec da cartilagem'),
  ('M949', 'Transtornos não especificados da cartilagem', 'M94.9 Transt NE da cartilagem'),
  ('M95', 'Outras deformidades adquiridas do sistema osteomuscular e do tecido conjuntivo', 'M95 Outr deform adquir sist osteomusc tec conj'),
  ('M950', 'Deformidade adquirida do nariz', 'M95.0 Deform adquir do nariz'),
  ('M951', 'Orelha em couve-flor', 'M95.1 Orelha em couve-flor'),
  ('M952', 'Outras deformidades adquiridas da cabeça', 'M95.2 Outr deform adquir da cabeca'),
  ('M953', 'Deformidade adquirida do pescoço', 'M95.3 Deform adquir do pescoco'),
  ('M954', 'Deformidade adquirida do tórax e das costelas', 'M95.4 Deform adquir do torax e das costelas'),
  ('M955', 'Deformidade adquirida da pelve', 'M95.5 Deform adquir da pelve'),
  ('M958', 'Outras deformidades adquiridas especificadas do sistema osteomuscular', 'M95.8 Outr deform adquir espec sist osteomuscular'),
  ('M959', 'Deformidade adquirida do sistema osteomuscular não especificada', 'M95.9 Deform adquir do sist osteomuscular NE'),
  ('M96', 'Transtornos osteomusculares pós-procedimentos não classificados em outra parte', 'M96 Transt osteomusculares pos-proced NCOP'),
  ('M960', 'Pseudo-artrose após fusão ou artrodese', 'M96.0 Pseudo-artrose apos fusao ou artrodese'),
  ('M961', 'Síndrome pós-laminectomia não classificada em outra parte', 'M96.1 Sindr pos-laminectomia NCOP'),
  ('M962', 'Cifose pós-radiação', 'M96.2 Cifose pos-radiacao'),
  ('M963', 'Cifose pós-laminectomia', 'M96.3 Cifose pos-laminectomia'),
  ('M964', 'Lordose pós-cirúrgica', 'M96.4 Lordose pos-cirurgica'),
  ('M965', 'Escoliose pós-radiação', 'M96.5 Escoliose pos-radiacao'),
  ('M966', 'Fratura de osso subsequente a implante ortopédico, prótese articular ou placa óssea', 'M96.6 Frat osso subs impl ortop prot art placa oss'),
  ('M968', 'Outros transtornos osteomusculares pós-procedimentos', 'M96.8 Outr transt osteomusculares pos-proced'),
  ('M969', 'Transtorno osteomuscular não especificado pós-procedimento', 'M96.9 Transt osteomuscular NE pos-proced'),
  ('M99', 'Lesões biomecânicas não classificadas em outra parte', 'M99 Lesoes biomecanicas NCOP'),
  ('M990', 'Disfunção segmentar e somática', 'M99.0 Disfuncao segmentar e somatica'),
  ('M991', 'Complexo de subluxação (vertebral)', 'M99.1 Complexo de subluxacao'),
  ('M992', 'Estenose de subluxação do canal medular', 'M99.2 Estenose de subluxacao do canal medular'),
  ('M993', 'Estenose óssea do canal medular', 'M99.3 Estenose ossea do canal medular'),
  ('M994', 'Estenose de tecido conjuntivo do canal medular', 'M99.4 Estenose de tec conjuntivo do canal medular'),
  ('M995', 'Estenose de disco intervertebral do canal medular', 'M99.5 Estenose disco intervertebral canal medular'),
  ('M996', 'Estenose óssea e subluxação dos forames intervertebrais', 'M99.6 Estenose ossea subluxacao forames intervert'),
  ('M997', 'Estenose de tecido conjuntivo e do disco dos forames intervertebrais', 'M99.7 Estenose tec conj e disco forames intervert'),
  ('M998', 'Outras lesões biomecânicas', 'M99.8 Outr lesoes biomecanicas'),
  ('M999', 'Lesão biomecânica não especificada', 'M99.9 Lesao biomecanica NE');
