INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('F00', 'Demência na doença de Alzheimer', 'F00 Demencia na doenc de Alzheimer'),
  ('F000', 'Demência na doença de Alzheimer de início precoce', 'F00.0 Demencia doenc Alzheimer inicio precoce'),
  ('F001', 'Demência na doença de Alzheimer de início tardio', 'F00.1 Demencia doenc Alzheimer inicio tard'),
  ('F002', 'Demência na doença de Alzheimer, forma atípica ou mista', 'F00.2 Demencia doenc Alzheimer form atipica mista'),
  ('F009', 'Demência não especificada na doença de Alzheimer', 'F00.9 Demencia NE na doenc de Alzheimer'),
  ('F01', 'Demência vascular', 'F01 Demencia vascular'),
  ('F010', 'Demência vascular de início agudo', 'F01.0 Demencia vascular de inicio agudo'),
  ('F011', 'Demência por infartos múltiplos', 'F01.1 Demencia p/infartos mult'),
  ('F012', 'Demência vascular subcortical', 'F01.2 Demencia vascular subcortical'),
  ('F013', 'Demência vascular mista, cortical e subcortical', 'F01.3 Demencia vascular mista cortical subcortical'),
  ('F018', 'Outra demência vascular', 'F01.8 Outr demencia vascular'),
  ('F019', 'Demência vascular não especificada', 'F01.9 Demencia vascular NE'),
  ('F02', 'Demência em outras doenças classificadas em outra parte', 'F02 Demencia em outr doenc COP'),
  ('F020', 'Demência da doença de Pick', 'F02.0 Demencia da doenc de Pick'),
  ('F021', 'Demência na doença de Creutzfeldt-Jakob', 'F02.1 Demencia na doenc de Creutzfeldt-Jakob'),
  ('F022', 'Demência na doença de Huntington', 'F02.2 Demencia na doenc de Huntington'),
  ('F023', 'Demência na doença de Parkinson', 'F02.3 Demencia na doenc de Parkinson'),
  ('F024', 'Demência na doença pelo vírus da imunodeficiência humana (HIV)', 'F02.4 Demencia na doenc pelo HIV'),
  ('F028', 'Demência em outras doenças especificadas classificadas em outra parte', 'F02.8 Demencia em outr doenc espec COP'),
  ('F03', 'Demência não especificada', 'F03 Demencia NE'),
  ('F03', 'Demência não especificada', 'F03 Demencia NE'),
  ('F04', 'Síndrome amnésica orgânica não induzida pelo álcool ou por outras substâncias psicoativas', 'F04 Sindr amnes org n ind alcool out subst psic'),
  ('F04', 'Síndrome amnésica orgânica não induzida pelo álcool ou por outras substâncias psicoativas', 'F04 Sindr amnes org n ind alcool out subst psic'),
  ('F05', 'Delirium não induzido pelo álcool ou por outras substâncias psicoativas', 'F05 Delirium nao induz alcool outr subst psicoat'),
  ('F050', 'Delirium não superposto a uma demência, assim descrito', 'F05.0 Delirium nao superposto demencia assim descr'),
  ('F051', 'Delirium superposto a uma demência', 'F05.1 Delirium superposto demencia'),
  ('F058', 'Outro delirium', 'F05.8 Outr delirium'),
  ('F059', 'Delirium não especificado', 'F05.9 Delirium NE'),
  ('F06', 'Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física', 'F06 Outr transt ment lesao disf cereb doenc fis'),
  ('F060', 'Alucinose orgânica', 'F06.0 Alucinose organica'),
  ('F061', 'Estado catatônico orgânico', 'F06.1 Estado catatonico organico'),
  ('F062', 'Transtorno delirante orgânico (tipo esquizofrênico)', 'F06.2 Transt delirante organico'),
  ('F063', 'Transtornos do humor (afetivos) orgânicos', 'F06.3 Transt do humor organicos'),
  ('F064', 'Transtornos da ansiedade orgânicos', 'F06.4 Transt da ansiedade organicos'),
  ('F065', 'Transtorno dissociativo orgânico', 'F06.5 Transt dissociativo organico'),
  ('F066', 'Transtorno de labilidade emocional (astênico) orgânico', 'F06.6 Transt de labilidade emocional organico'),
  ('F067', 'Transtorno cognitivo leve', 'F06.7 Transt cognitivo leve'),
  ('F068', 'Outros transtornos mentais especificados devidos a uma lesão e disfunção cerebral e a uma doença física', 'F06.8 Out trans ment esp dev les disf cer doen fis'),
  ('F069', 'Transtorno mental não especificado devido a uma lesão e disfunção cerebral e a uma doença física', 'F06.9 Transt ment NE dev lesao disf cereb doen fis'),
  ('F07', 'Transtornos de personalidade e do comportamento devidos a doença, a lesão e a disfunção cerebral', 'F07 Transt pers comport dev doen lesao disf cer'),
  ('F070', 'Transtorno orgânico da personalidade', 'F07.0 Transt organico da personalidade'),
  ('F071', 'Síndrome pós-encefalítica', 'F07.1 Sindr pos-encefalitica'),
  ('F072', 'Síndrome pós-traumática', 'F07.2 Sindr pos-traum'),
  ('F078', 'Outros transtornos orgânicos da personalidade e do comportamento devidos a doença cerebral, lesão e disfunção', 'F07.8 Out trans org pers comp doen cer lesao disf'),
  ('F079', 'Transtorno orgânico não especificado da personalidade e do comportamento devido a doença cerebral, lesão e disfunção', 'F07.9 Transt org NE pers comp doen cer lesao disf'),
  ('F09', 'Transtorno mental orgânico ou sintomático não especificado', 'F09 Transt mental organico ou sintomatico NE'),
  ('F09', 'Transtorno mental orgânico ou sintomático não especificado', 'F09 Transt mental organico ou sintomatico NE'),
  ('F10', 'Transtornos mentais e comportamentais devidos ao uso de álcool', 'F10 Transt mentais comport dev uso alcool'),
  ('F100', 'Transtornos mentais e comportamentais devidos ao uso de álcool - intoxicação aguda', 'F10.0 Intox aguda'),
  ('F101', 'Transtornos mentais e comportamentais devidos ao uso de álcool - uso nocivo para a saúde', 'F10.1 Uso nocivo p/a saude'),
  ('F102', 'Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome de dependência', 'F10.2 Sindr de dependencia'),
  ('F103', 'Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome (estado) de abstinência', 'F10.3 Sindr de abstinencia'),
  ('F104', 'Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome de abstinência com delirium', 'F10.4 Sindr de abstinencia c/delirium'),
  ('F105', 'Transtornos mentais e comportamentais devidos ao uso de álcool - transtorno psicótico', 'F10.5 Transt psicotico'),
  ('F106', 'Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome amnésica', 'F10.6 Sindr amnesica'),
  ('F107', 'Transtornos mentais e comportamentais devidos ao uso de álcool - transtorno psicótico residual ou de instalação tardia', 'F10.7 Trans psicotico residual instalacao tard'),
  ('F108', 'Transtornos mentais e comportamentais devidos ao uso de álcool - outros transtornos mentais ou comportamentais', 'F10.8 Outr transt mentais ou comport'),
  ('F109', 'Transtornos mentais e comportamentais devidos ao uso de álcool - transtorno mental ou comportamental não especificado', 'F10.9 Transt mental ou comport NE'),
  ('F11', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos', 'F11 Transt mentais e comport dev uso de opiaceos'),
  ('F110', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - intoxicação aguda', 'F11.0 Intox aguda'),
  ('F111', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - uso nocivo para a saúde', 'F11.1 Uso nocivo p/a saude'),
  ('F112', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome de dependência', 'F11.2 Sindr de dependencia'),
  ('F113', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome (estado) de abstinência', 'F11.3 Sindr de abstinencia'),
  ('F114', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome de abstinência com delirium', 'F11.4 Sindr de abstinencia c/delirium'),
  ('F115', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - transtorno psicótico', 'F11.5 Transt psicotico'),
  ('F116', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome amnésica', 'F11.6 Sindr amnesica'),
  ('F117', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - transtorno psicótico residual ou de instalação tardia', 'F11.7 Trans psicotico residual instalacao tard'),
  ('F118', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - outros transtornos mentais ou comportamentais', 'F11.8 Outr transt mentais ou comport'),
  ('F119', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos - transtorno mental ou comportamental não especificado', 'F11.9 Transt mental ou comport NE'),
  ('F12', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides', 'F12 Transt mentais comport dev uso canabinoides'),
  ('F120', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - intoxicação aguda', 'F12.0 Intox aguda'),
  ('F121', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - uso nocivo para a saúde', 'F12.1 Uso nocivo p/a saude'),
  ('F122', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome de dependência', 'F12.2 Sindr de dependencia'),
  ('F123', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome (estado) de abstinência', 'F12.3 Sindr de abstinencia'),
  ('F124', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome de abstinência com delirium', 'F12.4 Sindr de abstinencia c/delirium'),
  ('F125', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - transtorno psicótico', 'F12.5 Transt psicotico'),
  ('F126', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome amnésica', 'F12.6 Sindr amnesica'),
  ('F127', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - transtorno psicótico residual ou de instalação tardia', 'F12.7 Trans psicotico residual instalacao tard'),
  ('F128', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - outros transtornos mentais ou comportamentais', 'F12.8 Outr transt mentais ou comport'),
  ('F129', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides - transtorno mental ou comportamental não especificado', 'F12.9 Transt mental ou comport NE'),
  ('F13', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos', 'F13 Transt mentais comport dev uso sedat hipnot'),
  ('F130', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - intoxicação aguda', 'F13.0 Intox aguda'),
  ('F131', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - uso nocivo para a saúde', 'F13.1 Uso nocivo p/a saude'),
  ('F132', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome de dependência', 'F13.2 Sindr de dependencia'),
  ('F133', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome (estado) de abstinência', 'F13.3 Sindr de abstinencia'),
  ('F134', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome de abstinência com delirium', 'F13.4 Sindr de abstinencia c/delirium'),
  ('F135', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - transtorno psicótico', 'F13.5 Transt psicotico'),
  ('F136', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome amnésica', 'F13.6 Sindr amnesica'),
  ('F137', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - transtorno psicótico residual ou de instalação tardia', 'F13.7 Trans psicotico residual instalacao tard'),
  ('F138', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - outros transtornos mentais ou comportamentais', 'F13.8 Outr transt mentais ou comport'),
  ('F139', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - transtorno mental ou comportamental não especificado', 'F13.9 Transt mental ou comport NE'),
  ('F14', 'Transtornos mentais e comportamentais devidos ao uso da cocaína', 'F14 Transt mentais e comport dev uso da cocaina'),
  ('F140', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - intoxicação aguda', 'F14.0 Intox aguda'),
  ('F141', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - uso nocivo para a saúde', 'F14.1 Uso nocivo p/a saude'),
  ('F142', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome de dependência', 'F14.2 Sindr de dependencia'),
  ('F143', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome (estado) de abstinência', 'F14.3 Sindr de abstinencia'),
  ('F144', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome de abstinência com delirium', 'F14.4 Sindr de abstinencia c/delirium'),
  ('F145', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - transtorno psicótico', 'F14.5 Transt psicotico'),
  ('F146', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome amnésica', 'F14.6 Sindr amnesica'),
  ('F147', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - transtorno psicótico residual ou de instalação tardia', 'F14.7 Trans psicotico residual instalacao tard'),
  ('F148', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - outros transtornos mentais ou comportamentais', 'F14.8 Outr transt mentais ou comport'),
  ('F149', 'Transtornos mentais e comportamentais devidos ao uso da cocaína - transtorno mental ou comportamental não especificado', 'F14.9 Transt mental ou comport NE'),
  ('F15', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína', 'F15 Transt ment comp uso outr estim incl cafeina'),
  ('F150', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - intoxicação aguda', 'F15.0 Intox aguda'),
  ('F151', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - uso nocivo para a saúde', 'F15.1 Uso nocivo p/a saude'),
  ('F152', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome de dependência', 'F15.2 Sindr de dependencia'),
  ('F153', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome (estado) de abstinência', 'F15.3 Sindr de abstinencia'),
  ('F154', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome de abstinência com delirium', 'F15.4 Sindr de abstinencia c/delirium'),
  ('F155', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - transtorno psicótico', 'F15.5 Transt psicotico'),
  ('F156', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome amnésica', 'F15.6 Sindr amnesica'),
  ('F157', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - transtorno psicótico residual ou de instalação tardia', 'F15.7 Trans psicotico residual instalacao tard'),
  ('F158', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - outros transtornos mentais ou comportamentais', 'F15.8 Outr transt mentais ou comport'),
  ('F159', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - transtorno mental ou comportamental não especificado', 'F15.9 Transt mental ou comport NE'),
  ('F16', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos', 'F16 Transt mentais comport dev uso alucinogenos'),
  ('F160', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - intoxicação aguda', 'F16.0 Intox aguda'),
  ('F161', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - uso nocivo para a saúde', 'F16.1 Uso nocivo p/a saude'),
  ('F162', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome de dependência', 'F16.2 Sindr de dependencia'),
  ('F163', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome (estado) de abstinência', 'F16.3 Sindr de abstinencia'),
  ('F164', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome de abstinência com delirium', 'F16.4 Sindr de abstinencia c/delirium'),
  ('F165', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - transtorno psicótico', 'F16.5 Transt psicotico'),
  ('F166', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome amnésica', 'F16.6 Sindr amnesica'),
  ('F167', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - transtorno psicótico residual ou de instalação tardia', 'F16.7 Trans psicotico residual instalacao tard'),
  ('F168', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - outros transtornos mentais ou comportamentais', 'F16.8 Outr transt mentais ou comport'),
  ('F169', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos - transtorno mental ou comportamental não especificado', 'F16.9 Transt mental ou comport NE'),
  ('F17', 'Transtornos mentais e comportamentais devidos ao uso de fumo', 'F17 Transt mentais e comport dev uso de fumo'),
  ('F170', 'Transtornos mentais e comportamentais devidos ao uso de fumo - intoxicação aguda', 'F17.0 Intox aguda'),
  ('F171', 'Transtornos mentais e comportamentais devidos ao uso de fumo - uso nocivo para a saúde', 'F17.1 Uso nocivo p/a saude'),
  ('F172', 'Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome de dependência', 'F17.2 Sindr de dependencia'),
  ('F173', 'Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome (estado) de abstinência', 'F17.3 Sindr de abstinencia'),
  ('F174', 'Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome de abstinência com delirium', 'F17.4 Sindr de abstinencia c/delirium'),
  ('F175', 'Transtornos mentais e comportamentais devidos ao uso de fumo - transtorno psicótico', 'F17.5 Transt psicotico'),
  ('F176', 'Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome amnésica', 'F17.6 Sindr amnesica'),
  ('F177', 'Transtornos mentais e comportamentais devidos ao uso de fumo - transtorno psicótico residual ou de instalação tardia', 'F17.7 Trans psicotico residual instalacao tard'),
  ('F178', 'Transtornos mentais e comportamentais devidos ao uso de fumo - outros transtornos mentais ou comportamentais', 'F17.8 Outr transt mentais ou comport'),
  ('F179', 'Transtornos mentais e comportamentais devidos ao uso de fumo - transtorno mental ou comportamental não especificado', 'F17.9 Transt mental ou comport NE'),
  ('F18', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis', 'F18 Transt mentais comport dev uso solv volateis'),
  ('F180', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - intoxicação aguda', 'F18.0 Intox aguda'),
  ('F181', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - uso nocivo para a saúde', 'F18.1 Uso nocivo p/a saude'),
  ('F182', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome de dependência', 'F18.2 Sindr de dependencia'),
  ('F183', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome (estado) de abstinência', 'F18.3 Sindr de abstinencia'),
  ('F184', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome de abstinência com delirium', 'F18.4 Sindr de abstinencia c/delirium'),
  ('F185', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - transtorno psicótico', 'F18.5 Transt psicotico'),
  ('F186', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome amnésica', 'F18.6 Sindr amnesica'),
  ('F187', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - transtorno psicótico residual ou de instalação tardia', 'F18.7 Trans psicotico residual instalacao tard'),
  ('F188', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - outros transtornos mentais ou comportamentais', 'F18.8 Outr transt mentais ou comport'),
  ('F189', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - transtorno mental ou comportamental não especificado', 'F18.9 Transt mental ou comport NE'),
  ('F19', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas', 'F19 Transt ment comp mult drog out subst psicoat'),
  ('F190', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - intoxicação aguda', 'F19.0 Intox aguda'),
  ('F191', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - uso nocivo para a saúde', 'F19.1 Uso nocivo p/a saude'),
  ('F192', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome de dependência', 'F19.2 Sindr de dependencia'),
  ('F193', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome (estado) de abstinência', 'F19.3 Sindr de abstinencia'),
  ('F194', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome de abstinência com delirium', 'F19.4 Sindr de abstinencia c/delirium'),
  ('F195', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - transtorno psicótico', 'F19.5 Transt psicotico'),
  ('F196', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome amnésica', 'F19.6 Sindr amnesica'),
  ('F197', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - transtorno psicótico residual ou de instalação tardia', 'F19.7 Trans psicotico residual instalacao tard'),
  ('F198', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - outros transtornos mentais ou comportamentais', 'F19.8 Outr transt mentais ou comport'),
  ('F199', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - transtorno mental ou comportamental não especificado', 'F19.9 Transt mental ou comport NE'),
  ('F20', 'Esquizofrenia', 'F20 Esquizofrenia'),
  ('F200', 'Esquizofrenia paranóide', 'F20.0 Esquizofrenia paranoide'),
  ('F201', 'Esquizofrenia hebefrênica', 'F20.1 Esquizofrenia hebefrenica'),
  ('F202', 'Esquizofrenia catatônica', 'F20.2 Esquizofrenia catatonica'),
  ('F203', 'Esquizofrenia indiferenciada', 'F20.3 Esquizofrenia indiferenciada'),
  ('F204', 'Depressão pós-esquizofrênica', 'F20.4 Depressao pos-esquizofrenica'),
  ('F205', 'Esquizofrenia residual', 'F20.5 Esquizofrenia residual'),
  ('F206', 'Esquizofrenia simples', 'F20.6 Esquizofrenia simples'),
  ('F208', 'Outras esquizofrenias', 'F20.8 Outr esquizofrenias'),
  ('F209', 'Esquizofrenia não especificada', 'F20.9 Esquizofrenia NE'),
  ('F21', 'Transtorno esquizotípico', 'F21 Transt esquizotipico'),
  ('F21', 'Transtorno esquizotípico', 'F21 Transt esquizotipico'),
  ('F22', 'Transtornos delirantes persistentes', 'F22 Transt delirantes persistentes'),
  ('F220', 'Transtorno delirante', 'F22.0 Transt delirante'),
  ('F228', 'Outros transtornos delirantes persistentes', 'F22.8 Outr transt delirantes persistentes'),
  ('F229', 'Transtorno delirante persistente não especificado', 'F22.9 Transt delirante persistente NE'),
  ('F23', 'Transtornos psicóticos agudos e transitórios', 'F23 Transt psicoticos agudos e transitorios'),
  ('F230', 'Transtorno psicótico agudo polimorfo, sem sintomas esquizofrênicos', 'F23.0 Transt psicot agudo polimorf s/sint esquizof'),
  ('F231', 'Transtorno psicótico agudo polimorfo, com sintomas esquizofrênicos', 'F23.1 Transt psicot agudo polimorf c/sint esquizof'),
  ('F232', 'Transtorno psicótico agudo de tipo esquizofrênico (schizophrenia-like)', 'F23.2 Transt psicotico agudo tipo esquizofrenico'),
  ('F233', 'Outros transtornos psicóticos agudos, essencialmente delirantes', 'F23.3 Outr transt psicot agudos essenc delirantes'),
  ('F238', 'Outros transtornos psicóticos agudos e transitórios', 'F23.8 Outr transt psicoticos agudos e transitorios'),
  ('F239', 'Transtorno psicótico agudo e transitório não especificado', 'F23.9 Transt psicotico agudo e transitorio NE'),
  ('F24', 'Transtorno delirante induzido', 'F24 Transt delirante induz'),
  ('F24', 'Transtorno delirante induzido', 'F24 Transt delirante induz'),
  ('F25', 'Transtornos esquizoafetivos', 'F25 Transt esquizoafetivos'),
  ('F250', 'Transtorno esquizoafetivo do tipo maníaco', 'F25.0 Transt esquizoafetivo do tipo maniaco'),
  ('F251', 'Transtorno esquizoafetivo do tipo depressivo', 'F25.1 Transt esquizoafetivo do tipo depressivo'),
  ('F252', 'Transtorno esquizoafetivo do tipo misto', 'F25.2 Transt esquizoafetivo do tipo misto'),
  ('F258', 'Outros transtornos esquizoafetivos', 'F25.8 Outr transt esquizoafetivos'),
  ('F259', 'Transtorno esquizoafetivo não especificado', 'F25.9 Transt esquizoafetivo NE'),
  ('F28', 'Outros transtornos psicóticos não-orgânicos', 'F28 Outr transt psicoticos nao-organicos'),
  ('F28', 'Outros transtornos psicóticos não-orgânicos', 'F28 Outr transt psicoticos nao-organicos'),
  ('F29', 'Psicose não-orgânica não especificada', 'F29 Psicose nao-organica NE'),
  ('F29', 'Psicose não-orgânica não especificada', 'F29 Psicose nao-organica NE'),
  ('F30', 'Episódio maníaco', 'F30 Episodio maniaco'),
  ('F300', 'Hipomania', 'F30.0 Hipomania'),
  ('F301', 'Mania sem sintomas psicóticos', 'F30.1 Mania s/sint psicoticos'),
  ('F302', 'Mania com sintomas psicóticos', 'F30.2 Mania c/sint psicoticos'),
  ('F308', 'Outros episódios maníacos', 'F30.8 Outr episodios maniacos'),
  ('F309', 'Episódio maníaco não especificado', 'F30.9 Episodio maniaco NE'),
  ('F31', 'Transtorno afetivo bipolar', 'F31 Transt afetivo bipolar'),
  ('F310', 'Transtorno afetivo bipolar, episódio atual hipomaníaco', 'F31.0 Transt afet bipolar episodio atual hipoman'),
  ('F311', 'Transtorno afetivo bipolar, episódio atual maníaco sem sintomas psicóticos', 'F31.1 Trans afet bip epis atual man s/sint psicot'),
  ('F312', 'Transtorno afetivo bipolar, episódio atual maníaco com sintomas psicóticos', 'F31.2 Trans afet bip epis atual man c/sint psicot'),
  ('F313', 'Transtorno afetivo bipolar, episódio atual depressivo leve ou moderado', 'F31.3 Trans afet bip epis atual depr leve/ moderad'),
  ('F314', 'Transtorno afetivo bipolar, episódio atual depressivo grave sem sintomas psicóticos', 'F31.4 Trans afet bip atual depr grav s/sint psicot'),
  ('F315', 'Transtorno afetivo bipolar, episódio atual depressivo grave com sintomas psicóticos', 'F31.5 Trans afet bip atual depr grav c/sint psicot'),
  ('F316', 'Transtorno afetivo bipolar, episódio atual misto', 'F31.6 Transt afetivo bipolar episodio atual misto'),
  ('F317', 'Transtorno afetivo bipolar, atualmente em remissão', 'F31.7 Transt afet bipolar atualmente em remissao'),
  ('F318', 'Outros transtornos afetivos bipolares', 'F31.8 Outr transt afetivos bipolares'),
  ('F319', 'Transtorno afetivo bipolar não especificado', 'F31.9 Transt afetivo bipolar NE'),
  ('F32', 'Episódios depressivos', 'F32 Episodios depressivos'),
  ('F320', 'Episódio depressivo leve', 'F32.0 Episodio depressivo leve'),
  ('F321', 'Episódio depressivo moderado', 'F32.1 Episodio depressivo moderado'),
  ('F322', 'Episódio depressivo grave sem sintomas psicóticos', 'F32.2 Episodio depressivo grave s/sint psicoticos'),
  ('F323', 'Episódio depressivo grave com sintomas psicóticos', 'F32.3 Episodio depressivo grave c/sint psicoticos'),
  ('F328', 'Outros episódios depressivos', 'F32.8 Outr episodios depressivos'),
  ('F329', 'Episódio depressivo não especificado', 'F32.9 Episodio depressivo NE'),
  ('F33', 'Transtorno depressivo recorrente', 'F33 Transt depressivo recorrente'),
  ('F330', 'Transtorno depressivo recorrente, episódio atual leve', 'F33.0 Transt depressivo recorr episodio atual leve'),
  ('F331', 'Transtorno depressivo recorrente, episódio atual moderado', 'F33.1 Transt depress recorr episodio atual moderad'),
  ('F332', 'Transtorno depressivo recorrente, episódio atual grave sem sintomas psicóticos', 'F33.2 Trans depr recor epis atual grav s/sint psic'),
  ('F333', 'Transtorno depressivo recorrente, episódio atual grave com sintomas psicóticos', 'F33.3 Trans depr recor epis atual grav c/sint psic'),
  ('F334', 'Transtorno depressivo recorrente, atualmente em remissão', 'F33.4 Transt depress recorr atualmente em remissao'),
  ('F338', 'Outros transtornos depressivos recorrentes', 'F33.8 Outr transt depressivos recorrentes'),
  ('F339', 'Transtorno depressivo recorrente sem especificação', 'F33.9 Transt depressivo recorrente s/especificacao'),
  ('F34', 'Transtornos de humor (afetivos) persistentes', 'F34 Transt de humor persistentes'),
  ('F340', 'Ciclotimia', 'F34.0 Ciclotimia'),
  ('F341', 'Distimia', 'F34.1 Distimia'),
  ('F348', 'Outros transtornos do humor (afetivos) persistentes', 'F34.8 Outr transt do humor persistentes'),
  ('F349', 'Transtorno do humor (afetivo) persistente não especificado', 'F34.9 Transt do humor persistente NE'),
  ('F38', 'Outros transtornos do humor (afetivos)', 'F38 Outr transt do humor'),
  ('F380', 'Outros transtornos do humor (afetivos) isolados', 'F38.0 Outr transt do humor isolados'),
  ('F381', 'Outros transtornos do humor (afetivos) recorrentes', 'F38.1 Outr transt do humor recorrentes'),
  ('F388', 'Outros transtornos especificados do humor (afetivos)', 'F38.8 Outr transt espec do humor'),
  ('F39', 'Transtorno do humor (afetivo) não especificado', 'F39 Transt do humor NE'),
  ('F39', 'Transtorno do humor (afetivo) não especificado', 'F39 Transt do humor NE'),
  ('F40', 'Transtornos fóbico-ansiosos', 'F40 Transt fobico-ansiosos'),
  ('F400', 'Agorafobia', 'F40.0 Agorafobia'),
  ('F401', 'Fobias sociais', 'F40.1 Fobias sociais'),
  ('F402', 'Fobias específicas (isoladas)', 'F40.2 Fobias especificas'),
  ('F408', 'Outros transtornos fóbico-ansiosos', 'F40.8 Outr transt fobico-ansiosos'),
  ('F409', 'Transtorno fóbico-ansioso não especificado', 'F40.9 Transt fobico-ansioso NE'),
  ('F41', 'Outros transtornos ansiosos', 'F41 Outr transt ansiosos'),
  ('F410', 'Transtorno de pânico (ansiedade paroxística episódica)', 'F41.0 Transt de panico'),
  ('F411', 'Ansiedade generalizada', 'F41.1 Ansiedade generalizada'),
  ('F412', 'Transtorno misto ansioso e depressivo', 'F41.2 Transt misto ansioso e depressivo'),
  ('F413', 'Outros transtornos ansiosos mistos', 'F41.3 Outr transt ansiosos mistos'),
  ('F418', 'Outros transtornos ansiosos especificados', 'F41.8 Outr transt ansiosos espec'),
  ('F419', 'Transtorno ansioso não especificado', 'F41.9 Transt ansioso NE'),
  ('F42', 'Transtorno obsessivo-compulsivo', 'F42 Transt obsessivo-compulsivo'),
  ('F420', 'Transtorno obsessivo-compulsivo com predominância de idéias ou de ruminações obsessivas', 'F42.0 Com predom ideias ou ruminacoes obsessivas'),
  ('F421', 'Transtorno obsessivo-compulsivo com predominância de comportamentos compulsivos (rituais obsessivos)', 'F42.1 Com predom de comport compulsivos'),
  ('F422', 'Transtorno obsessivo-compulsivo, forma mista, com idéias obsessivas e comportamentos compulsivos', 'F42.2 Form mista c/ideias obsess e comport compuls'),
  ('F428', 'Outros transtornos obsessivo-compulsivos', 'F42.8 Outr transt obsessivo-compulsivos'),
  ('F429', 'Transtorno obsessivo-compulsivo não especificado', 'F42.9 Transt obsessivo-compulsivo NE'),
  ('F43', 'Reações ao stress grave e transtornos de adaptação', 'F43 Reacoes ao stress grave e transt adaptacao'),
  ('F430', 'Reação aguda ao stress', 'F43.0 Reacao aguda ao stress'),
  ('F431', 'Estado de stress pós-traumático', 'F43.1 Estado de stress pos-traum'),
  ('F432', 'Transtornos de adaptação', 'F43.2 Transt de adaptacao'),
  ('F438', 'Outras reações ao stress grave', 'F43.8 Outr reacoes ao stress grave'),
  ('F439', 'Reação não especificada a um stress grave', 'F43.9 Reacao NE a um stress grave'),
  ('F44', 'Transtornos dissociativos (de conversão)', 'F44 Transt dissociativos'),
  ('F440', 'Amnésia dissociativa', 'F44.0 Amnesia dissociativa'),
  ('F441', 'Fuga dissociativa', 'F44.1 Fuga dissociativa'),
  ('F442', 'Estupor dissociativo', 'F44.2 Estupor dissociativo'),
  ('F443', 'Estados de transe e de possessão', 'F44.3 Estados de transe e de possessao'),
  ('F444', 'Transtornos dissociativos do movimento', 'F44.4 Transt dissociativos do movimento'),
  ('F445', 'Convulsões dissociativas', 'F44.5 Convulsoes dissociativas'),
  ('F446', 'Anestesia e perda sensorial dissociativas', 'F44.6 Anestesia e perda sensorial dissociativas'),
  ('F447', 'Transtorno dissociativo misto (de conversão)', 'F44.7 Transt dissociativo misto'),
  ('F448', 'Outros transtornos dissociativos (de conversão)', 'F44.8 Outr transt dissociativos'),
  ('F449', 'Transtorno dissociativo (de conversão) não especificado', 'F44.9 Transt dissociativo NE'),
  ('F45', 'Transtornos somatoformes', 'F45 Transt somatoformes'),
  ('F450', 'Transtorno de somatização', 'F45.0 Transt de somatizacao'),
  ('F451', 'Transtorno somatoforme indiferenciado', 'F45.1 Transt somatoforme indiferenciado'),
  ('F452', 'Transtorno hipocondríaco', 'F45.2 Transt hipocondriaco'),
  ('F453', 'Transtorno neurovegetativo somatoforme', 'F45.3 Transt neurovegetativo somatoforme'),
  ('F454', 'Transtorno doloroso somatoforme persistente', 'F45.4 Transt doloroso somatoforme persistente'),
  ('F458', 'Outros transtornos somatoformes', 'F45.8 Outr transt somatoformes'),
  ('F459', 'Transtorno somatoforme não especificado', 'F45.9 Transt somatoforme NE'),
  ('F48', 'Outros transtornos neuróticos', 'F48 Outr transt neuroticos'),
  ('F480', 'Neurastenia', 'F48.0 Neurastenia'),
  ('F481', 'Síndrome de despersonalização-desrealização', 'F48.1 Sindr de despersonalizacao-desrealizacao'),
  ('F488', 'Outros transtornos neuróticos especificados', 'F48.8 Outr transt neuroticos espec'),
  ('F489', 'Transtorno neurótico não especificado', 'F48.9 Transt neurotico NE'),
  ('F50', 'Transtornos da alimentação', 'F50 Transt da alimentacao'),
  ('F500', 'Anorexia nervosa', 'F50.0 Anorexia nervosa'),
  ('F501', 'Anorexia nervosa atípica', 'F50.1 Anorexia nervosa atipica'),
  ('F502', 'Bulimia nervosa', 'F50.2 Bulimia nervosa'),
  ('F503', 'Bulimia nervosa atípica', 'F50.3 Bulimia nervosa atipica'),
  ('F504', 'Hiperfagia associada a outros distúrbios psicológicos', 'F50.4 Hiperfagia assoc outr disturb psicologicos'),
  ('F505', 'Vômitos associados a outros distúrbios psicológicos', 'F50.5 Vomitos assoc a outr disturbios psicologicos'),
  ('F508', 'Outros transtornos da alimentação', 'F50.8 Outr transt da alimentacao'),
  ('F509', 'Transtorno de alimentação não especificado', 'F50.9 Transt de alimentacao NE'),
  ('F51', 'Transtornos não-orgânicos do sono devidos a fatores emocionais', 'F51 Transt nao-organicos sono dev fat emocionais'),
  ('F510', 'Insônia não-orgânica', 'F51.0 Insonia nao-organica'),
  ('F511', 'Hipersonia não-orgânica', 'F51.1 Hipersonia nao-organica'),
  ('F512', 'Transtorno do ciclo vigília-sono devido a fatores não-orgânicos', 'F51.2 Transt ciclo vigilia-sono dev fat nao-organ'),
  ('F513', 'Sonambulismo', 'F51.3 Sonambulismo'),
  ('F514', 'Terrores noturnos', 'F51.4 Terrores noturnos'),
  ('F515', 'Pesadelos', 'F51.5 Pesadelos'),
  ('F518', 'Outros transtornos do sono devidos a fatores não-orgânicos', 'F51.8 Outr transt do sono dev fat nao-organicos'),
  ('F519', 'Transtorno do sono devido a fatores não-orgânicos não especificados', 'F51.9 Transt do sono dev fatores nao-organicos NE'),
  ('F52', 'Disfunção sexual, não causada por transtorno ou doença orgânica', 'F52 Disfuncao sexual n caus p/transt doenc organ'),
  ('F520', 'Ausência ou perda do desejo sexual', 'F52.0 Ausencia ou perda do desejo sexual'),
  ('F521', 'Aversão sexual e ausência de prazer sexual', 'F52.1 Aversao sexual e ausencia de prazer sexual'),
  ('F522', 'Falha de resposta genital', 'F52.2 Falha de resposta genital'),
  ('F523', 'Disfunção orgásmica', 'F52.3 Disfuncao orgasmica'),
  ('F524', 'Ejaculação precoce', 'F52.4 Ejaculacao precoce'),
  ('F525', 'Vaginismo não-orgânico', 'F52.5 Vaginismo nao-organico'),
  ('F526', 'Dispareunia não-orgânica', 'F52.6 Dispareunia nao-organica'),
  ('F527', 'Apetite sexual excessivo', 'F52.7 Apetite sexual excessivo'),
  ('F528', 'Outras disfunções sexuais não devidas a transtorno ou à doença orgânica', 'F52.8 Outr disfunc sex n dev transt doenc organ'),
  ('F529', 'Disfunção sexual não devida a transtorno ou à doença orgânica, não especificada', 'F52.9 Disfuncao sexual n dev transt doenc organ NE'),
  ('F53', 'Transtornos mentais e comportamentais associados ao puerpério, não classificados em outra parte', 'F53 Transt mentais comport assoc puerperio NCOP'),
  ('F530', 'Transtornos mentais e comportamentais leves associados ao puerpério não classificados em outra parte', 'F53.0 Transt ment comport leves assoc puerp NCOP'),
  ('F531', 'Transtornos mentais e comportamentais graves associados ao puerpério não classificados em outra parte', 'F53.1 Transt ment comport graves assoc puerp NCOP'),
  ('F538', 'Outros transtornos mentais e comportamentais associados ao puerpério não classificados em outra parte', 'F53.8 Outr transt mentais comport assoc puerp NCOP'),
  ('F539', 'Transtorno mental e comportamental associado ao puerpério, não especificado', 'F53.9 Transt mental e comport assoc puerperio NE'),
  ('F54', 'Fatores psicológicos ou comportamentais associados a doença ou a transtornos classificados em outra parte', 'F54 Fat psicolog comport assoc doenc transt COP'),
  ('F54', 'Fatores psicológicos ou comportamentais associados a doença ou a transtornos classificados em outra parte', 'F54 Fat psicolog comport assoc doenc transt COP'),
  ('F55', 'Abuso de substâncias que não produzem dependência', 'F55 Abuso de subst que nao produzem dependencia'),
  ('F55', 'Abuso de substâncias que não produzem dependência', 'F55 Abuso de subst que nao produzem dependencia'),
  ('F59', 'Síndromes comportamentais associados a transtornos das funções fisiológicas e a fatores físicos, não especificadas', 'F59 Sindr comp ass trans func fisio fat fisic NE'),
  ('F59', 'Síndromes comportamentais associados a transtornos das funções fisiológicas e a fatores físicos, não especificadas', 'F59 Sindr comp ass trans func fisio fat fisic NE'),
  ('F60', 'Transtornos específicos da personalidade', 'F60 Transt especificos da personalidade'),
  ('F600', 'Personalidade paranóica', 'F60.0 Personalidade paranoica'),
  ('F601', 'Personalidade esquizóide', 'F60.1 Personalidade esquizoide'),
  ('F602', 'Personalidade dissocial', 'F60.2 Personalidade dissocial'),
  ('F603', 'Transtorno de personalidade com instabilidade emocional', 'F60.3 Transt de personalidade c/instab emocional'),
  ('F604', 'Personalidade histriônica', 'F60.4 Personalidade histrionica'),
  ('F605', 'Personalidade anancástica', 'F60.5 Personalidade anancastica'),
  ('F606', 'Personalidade ansiosa (esquiva)', 'F60.6 Personalidade ansiosa'),
  ('F607', 'Personalidade dependente', 'F60.7 Personalidade dependente'),
  ('F608', 'Outros transtornos específicos da personalidade', 'F60.8 Outr transt especificos da personalidade'),
  ('F609', 'Transtorno não especificado da personalidade', 'F60.9 Transt NE da personalidade'),
  ('F61', 'Transtornos mistos da personalidade e outros transtornos da personalidade', 'F61 Transt mistos personal outr transt personal'),
  ('F61', 'Transtornos mistos da personalidade e outros transtornos da personalidade', 'F61 Transt mistos personal outr transt personal'),
  ('F62', 'Modificações duradouras da personalidade não atribuíveis a lesão ou doença cerebral', 'F62 Modif durad pers n atrib lesao doenc cerebr'),
  ('F620', 'Modificação duradoura da personalidade após uma experiência catastrófica', 'F62.0 Modif durad personalid apos exper catastr'),
  ('F621', 'Modificação duradoura da personalidade após doença psiquiátrica', 'F62.1 Modif durad personalid apos doenc psiquiatr'),
  ('F628', 'Outras modificações duradouras da personalidade', 'F62.8 Outr modificacoes duradouras personalidade'),
  ('F629', 'Modificação duradoura da personalidade, não especificada', 'F62.9 Modificacao duradoura da personalidade NE'),
  ('F63', 'Transtornos dos hábitos e dos impulsos', 'F63 Transt dos habitos e dos impulsos'),
  ('F630', 'Jogo patológico', 'F63.0 Jogo patologico'),
  ('F631', 'Piromania', 'F63.1 Piromania'),
  ('F632', 'Roubo patológico (cleptomania)', 'F63.2 Roubo patologico'),
  ('F633', 'Tricotilomania', 'F63.3 Tricotilomania'),
  ('F638', 'Outros transtornos dos hábitos e dos impulsos', 'F63.8 Outr transt dos habitos e dos impulsos'),
  ('F639', 'Transtorno dos hábitos e impulsos, não especificado', 'F63.9 Transt dos habitos e impulsos NE'),
  ('F64', 'Transtornos da identidade sexual', 'F64 Transt da identidade sexual'),
  ('F640', 'Transexualismo', 'F64.0 Transexualismo'),
  ('F641', 'Travestismo bivalente', 'F64.1 Travestismo bivalente'),
  ('F642', 'Transtorno de identidade sexual na infância', 'F64.2 Transt de identidade sexual na infancia'),
  ('F648', 'Outros transtornos da identidade sexual', 'F64.8 Outr transt da identidade sexual'),
  ('F649', 'Transtorno não especificado da identidade sexual', 'F64.9 Transt NE da identidade sexual'),
  ('F65', 'Transtornos da preferência sexual', 'F65 Transt da preferencia sexual'),
  ('F650', 'Fetichismo', 'F65.0 Fetichismo'),
  ('F651', 'Travestismo fetichista', 'F65.1 Travestismo fetichista'),
  ('F652', 'Exibicionismo', 'F65.2 Exibicionismo'),
  ('F653', 'Voyeurismo', 'F65.3 Voyeurismo'),
  ('F654', 'Pedofilia', 'F65.4 Pedofilia'),
  ('F655', 'Sadomasoquismo', 'F65.5 Sadomasoquismo'),
  ('F656', 'Transtornos múltiplos da preferência sexual', 'F65.6 Transt mult da preferencia sexual'),
  ('F658', 'Outros transtornos da preferência sexual', 'F65.8 Outr transt da preferencia sexual'),
  ('F659', 'Transtorno da preferência sexual, não especificado', 'F65.9 Transt da preferencia sexual NE'),
  ('F66', 'Transtornos psicológicos e comportamentais associados ao desenvolvimento sexual e à sua orientação', 'F66 Transt psic comp assoc desenv sex e orient'),
  ('F660', 'Transtorno da maturação sexual', 'F66.0 Transt da maturacao sexual'),
  ('F661', 'Orientação sexual egodistônica', 'F66.1 Orientacao sexual egodistonica'),
  ('F662', 'Transtorno do relacionamento sexual', 'F66.2 Transt do relacionamento sexual'),
  ('F668', 'Outros transtornos do desenvolvimento psicossexual', 'F66.8 Outr transt do desenvolv psicossexual'),
  ('F669', 'Transtorno do desenvolvimento sexual, não especificado', 'F66.9 Transt do desenvolv sexual NE'),
  ('F68', 'Outros transtornos da personalidade e do comportamento do adulto', 'F68 Outr transt personalidade e comport adulto'),
  ('F680', 'Sintomas físicos aumentados por fatores psicológicos', 'F68.0 Sint fisicos aument p/fatores psicologicos'),
  ('F681', 'Produção deliberada ou simulação de sintomas ou de incapacidades, físicas ou psicológicas (transtorno fictício)', 'F68.1 Prod delib ou simul sint incapac fisic psic'),
  ('F688', 'Outros transtornos especificados da personalidade e do comportamento do adulto', 'F68.8 Outr transt espec personal e comport adulto'),
  ('F69', 'Transtorno da personalidade e do comportamento do adulto, não especificado', 'F69 Transt personalidade e comport adulto NE'),
  ('F69', 'Transtorno da personalidade e do comportamento do adulto, não especificado', 'F69 Transt personalidade e comport adulto NE'),
  ('F70', 'Retardo mental leve', 'F70 Retardo mental leve'),
  ('F700', 'Retardo mental leve - menção de ausência de ou de comprometimento mínimo do comportamento', 'F70.0 Mencao ausencia de ou compr minimo comport'),
  ('F701', 'Retardo mental leve - comprometimento significativo do comportamento, requerendo vigilância ou tratamento', 'F70.1 Compr signif comport req vigilancia ou trat'),
  ('F708', 'Retardo mental leve - outros comprometimentos do comportamento', 'F70.8 Outr comprometimentos do comport'),
  ('F709', 'Retardo mental leve - sem menção de comprometimento do comportamento', 'F70.9 S/mencao de compr do comport'),
  ('F71', 'Retardo mental moderado', 'F71 Retardo mental moderado'),
  ('F710', 'Retardo mental moderado - menção de ausência de ou de comprometimento mínimo do comportamento', 'F71.0 Mencao ausencia de ou compr minimo comport'),
  ('F711', 'Retardo mental moderado - comprometimento significativo do comportamento, requerendo vigilância ou tratamento', 'F71.1 Compr signif comport req vigilancia ou trat'),
  ('F718', 'Retardo mental moderado - outros comprometimentos do comportamento', 'F71.8 Outr comprometimentos do comport'),
  ('F719', 'Retardo mental moderado - sem menção de comprometimento do comportamento', 'F71.9 S/mencao de compr do comport'),
  ('F72', 'Retardo mental grave', 'F72 Retardo mental grave'),
  ('F720', 'Retardo mental grave - menção de ausência de ou de comprometimento mínimo do comportamento', 'F72.0 Mencao ausencia de ou compr minimo comport'),
  ('F721', 'Retardo mental grave - comprometimento significativo do comportamento, requerendo vigilância ou tratamento', 'F72.1 Compr signif comport req vigilancia ou trat'),
  ('F728', 'Retardo mental grave - outros comprometimentos do comportamento', 'F72.8 Outr comprometimentos do comport'),
  ('F729', 'Retardo mental grave - sem menção de comprometimento do comportamento', 'F72.9 S/mencao de compr do comport'),
  ('F73', 'Retardo mental profundo', 'F73 Retardo mental profundo'),
  ('F730', 'Retardo mental profundo - menção de ausência de ou de comprometimento mínimo do comportamento', 'F73.0 Mencao ausencia de ou compr minimo comport'),
  ('F731', 'Retardo mental profundo - comprometimento significativo do comportamento, requerendo vigilância ou tratamento', 'F73.1 Compr signif comport req vigilancia ou trat'),
  ('F738', 'Retardo mental profundo - outros comprometimentos do comportamento', 'F73.8 Outr comprometimentos do comport'),
  ('F739', 'Retardo mental profundo - sem menção de comprometimento do comportamento', 'F73.9 S/mencao de compr do comport'),
  ('F78', 'Outro retardo mental', 'F78 Outr retardo mental'),
  ('F780', 'Outro retardo mental - menção de ausência de ou de comprometimento mínimo do comportamento', 'F78.0 Mencao ausencia de ou compr minimo comport'),
  ('F781', 'Outro retardo mental - comprometimento significativo do comportamento, requerendo vigilância ou tratamento', 'F78.1 Compr signif comport req vigilancia ou trat'),
  ('F788', 'Outro retardo mental - outros comprometimentos do comportamento', 'F78.8 Outr comprometimentos do comport'),
  ('F789', 'Outro retardo mental - sem menção de comprometimento do comportamento', 'F78.9 S/mencao de compr do comport'),
  ('F79', 'Retardo mental não especificado', 'F79 Retardo mental NE'),
  ('F790', 'Retardo mental não especificado - menção de ausência de ou de comprometimento mínimo do comportamento', 'F79.0 Mencao ausencia de ou compr minimo comport'),
  ('F791', 'Retardo mental não especificado - comprometimento significativo do comportamento, requerendo vigilância ou tratamento', 'F79.1 Compr signif comport req vigilancia ou trat'),
  ('F798', 'Retardo mental não especificado - outros comprometimentos do comportamento', 'F79.8 Outr comprometimentos do comport'),
  ('F799', 'Retardo mental não especificado - sem menção de comprometimento do comportamento', 'F79.9 S/mencao de compr do comport'),
  ('F80', 'Transtornos específicos do desenvolvimento da fala e da linguagem', 'F80 Transt especificos desenvolv fala linguagem'),
  ('F800', 'Transtorno específico da articulação da fala', 'F80.0 Transt especifico da articulacao da fala'),
  ('F801', 'Transtorno expressivo de linguagem', 'F80.1 Transt expressivo de linguagem'),
  ('F802', 'Transtorno receptivo da linguagem', 'F80.2 Transt receptivo da linguagem'),
  ('F803', 'Afasia adquirida com epilepsia (síndrome de Landau-Kleffner)', 'F80.3 Afasia adquir c/epilepsia'),
  ('F808', 'Outros transtornos de desenvolvimento da fala ou da linguagem', 'F80.8 Outr transt desenvolv fala ou linguagem'),
  ('F809', 'Transtorno não especificado do desenvolvimento da fala ou da linguagem', 'F80.9 Transt NE do desenvolv da fala ou linguagem'),
  ('F81', 'Transtornos específicos do desenvolvimento das habilidades escolares', 'F81 Transt especif desenvolv habilidade escolar'),
  ('F810', 'Transtorno específico de leitura', 'F81.0 Transt especifico de leitura'),
  ('F811', 'Transtorno específico da soletração', 'F81.1 Transt especifico da soletracao'),
  ('F812', 'Transtorno específico da habilidade em aritmética', 'F81.2 Transt especifico habilidade em aritmetica'),
  ('F813', 'Transtorno misto de habilidades escolares', 'F81.3 Transt misto de habilidades escolares'),
  ('F818', 'Outros transtornos do desenvolvimento das habilidades escolares', 'F81.8 Outr transt do desenvolv habilidade escolar'),
  ('F819', 'Transtorno não especificado do desenvolvimento das habilidades escolares', 'F81.9 Transt NE do desenvolv habilidades escolares'),
  ('F82', 'Transtorno específico do desenvolvimento motor', 'F82 Transt especifico do desenvolv motor'),
  ('F82', 'Transtorno específico do desenvolvimento motor', 'F82 Transt especifico do desenvolv motor'),
  ('F83', 'Transtornos específicos misto do desenvolvimento', 'F83 Transt especificos misto do desenvolv'),
  ('F83', 'Transtornos específicos misto do desenvolvimento', 'F83 Transt especificos misto do desenvolv'),
  ('F84', 'Transtornos globais do desenvolvimento', 'F84 Transt globais do desenvolv'),
  ('F840', 'Autismo infantil', 'F84.0 Autismo infantil'),
  ('F841', 'Autismo atípico', 'F84.1 Autismo atipico'),
  ('F842', 'Síndrome de Rett', 'F84.2 Sindr de Rett'),
  ('F843', 'Outro transtorno desintegrativo da infância', 'F84.3 Outr transt desintegrativo da infancia'),
  ('F844', 'Transtorno com hipercinesia associada a retardo mental e a movimentos estereotipados', 'F84.4 Transt c/hipercin ass ret ment mov estereot'),
  ('F845', 'Síndrome de Asperger', 'F84.5 Sindr de Asperger'),
  ('F848', 'Outros transtornos globais do desenvolvimento', 'F84.8 Outr transt globais do desenvolv'),
  ('F849', 'Transtornos globais não especificados do desenvolvimento', 'F84.9 Transt globais NE do desenvolv'),
  ('F88', 'Outros transtornos do desenvolvimento psicológico', 'F88 Outr transt do desenvolv psicologico'),
  ('F88', 'Outros transtornos do desenvolvimento psicológico', 'F88 Outr transt do desenvolv psicologico'),
  ('F89', 'Transtorno do desenvolvimento psicológico não especificado', 'F89 Transt do desenvolv psicologico NE'),
  ('F89', 'Transtorno do desenvolvimento psicológico não especificado', 'F89 Transt do desenvolv psicologico NE'),
  ('F90', 'Transtornos hipercinéticos', 'F90 Transt hipercineticos'),
  ('F900', 'Distúrbios da atividade e da atenção', 'F90.0 Disturbios da atividade e da atencao'),
  ('F901', 'Transtorno hipercinético de conduta', 'F90.1 Transt hipercinetico de conduta'),
  ('F908', 'Outros transtornos hipercinéticos', 'F90.8 Outr transt hipercineticos'),
  ('F909', 'Transtorno hipercinético não especificado', 'F90.9 Transt hipercinetico NE'),
  ('F91', 'Distúrbios de conduta', 'F91 Disturbios de conduta'),
  ('F910', 'Distúrbio de conduta restrito ao contexto familiar', 'F91.0 Disturbio conduta restrito contexto familiar'),
  ('F911', 'Distúrbio de conduta não-socializado', 'F91.1 Disturbio de conduta nao-socializado'),
  ('F912', 'Distúrbio de conduta do tipo socializado', 'F91.2 Disturbio de conduta do tipo socializado'),
  ('F913', 'Distúrbio desafiador e de oposição', 'F91.3 Disturbio desafiador e de oposicao'),
  ('F918', 'Outros transtornos de conduta', 'F91.8 Outr transt de conduta'),
  ('F919', 'Transtorno de conduta não especificado', 'F91.9 Transt de conduta NE'),
  ('F92', 'Transtornos mistos de conduta e das emoções', 'F92 Transt mistos de conduta e das emocoes'),
  ('F920', 'Distúrbio depressivo de conduta', 'F92.0 Disturbio depressivo de conduta'),
  ('F928', 'Outros transtornos mistos da conduta e das emoções', 'F92.8 Outr transt mistos da conduta e das emocoes'),
  ('F929', 'Transtorno misto da conduta e das emoções não especificado', 'F92.9 Transt misto da conduta e das emocoes NE'),
  ('F93', 'Transtornos emocionais com início especificamente na infância', 'F93 Transt emocionais c/inicio especif infancia'),
  ('F930', 'Transtorno ligado à angústia de separação', 'F93.0 Transt ligado a angustia de separacao'),
  ('F931', 'Transtorno fóbico ansioso da infância', 'F93.1 Transt fobico ansioso da infancia'),
  ('F932', 'Distúrbio de ansiedade social da infância', 'F93.2 Disturbio de ansiedade social da infancia'),
  ('F933', 'Transtorno de rivalidade entre irmãos', 'F93.3 Transt de rivalidade entre irmaos'),
  ('F938', 'Outros transtornos emocionais da infância', 'F93.8 Outr transt emocionais da infancia'),
  ('F939', 'Transtorno emocional da infância não especificado', 'F93.9 Transt emocional da infancia NE'),
  ('F94', 'Transtornos do funcionamento social com início especificamente durante a infância ou a adolescência', 'F94 Transt func soc c/inicio infancia adolesc'),
  ('F940', 'Mutismo eletivo', 'F94.0 Mutismo eletivo'),
  ('F941', 'Distúrbio reativo de vinculação da infância', 'F94.1 Disturbio reativo de vinculacao da infancia'),
  ('F942', 'Transtorno de fixação da infância, com desinibição', 'F94.2 Transt de fixacao da infancia c/desinibicao'),
  ('F948', 'Outros transtornos do funcionamento social na infância', 'F94.8 Outr transt do funcionamento social infancia'),
  ('F949', 'Transtorno do funcionamento social da infância não especificado', 'F94.9 Transt do funcionamento social infancia NE'),
  ('F95', 'Tiques', 'F95 Tiques'),
  ('F950', 'Tique transitório', 'F95.0 Tique transitorio'),
  ('F951', 'Tique motor ou vocal crônico', 'F95.1 Tique motor ou vocal cronico'),
  ('F952', 'Tiques vocais e motores múltiplos combinados (doença de Gilles de la Tourette)', 'F95.2 Tiques vocais e motores mult combinados'),
  ('F958', 'Outros tiques', 'F95.8 Outr tiques'),
  ('F959', 'Tique não especificado', 'F95.9 Tique NE'),
  ('F98', 'Outros transtornos comportamentais e emocionais com início habitualmente durante a infância ou a adolescência', 'F98 Outr transt comp emoc c/inicio inf adolesc'),
  ('F980', 'Enurese de origem não-orgânica', 'F98.0 Enurese orig nao-organica'),
  ('F981', 'Encoprese de origem não-orgânica', 'F98.1 Encoprese orig nao-organica'),
  ('F982', 'Transtorno de alimentação na infância', 'F98.2 Transt de alimentacao na infancia'),
  ('F983', 'Pica do lactente ou da criança', 'F98.3 Pica do lactente ou da crianca'),
  ('F984', 'Estereotipias motoras', 'F98.4 Estereotipias motoras'),
  ('F985', 'Gagueira (tartamudez)', 'F98.5 Gagueira'),
  ('F986', 'Linguagem precipitada', 'F98.6 Linguagem precipitada'),
  ('F988', 'Outros transtornos comportamentais e emocionais especificados com início habitualmente na infância ou adolescência', 'F98.8 Outr trans comp emoc espec c/inic inf adoles'),
  ('F989', 'Transtornos comportamentais e emocionais não especificados com início habitualmente na infância ou adolescência', 'F98.9 Transt comp emoc NE c/inicio infanc adolesc'),
  ('F99', 'Transtorno mental não especificado em outra parte', 'F99 Transt mental NE em outr parte');
