INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('Q00', 'Anencefalia e malformações similares', 'Q00 Anencefalia e malformacoes similares'),
  ('Q000', 'Anencefalia', 'Q00.0 Anencefalia'),
  ('Q001', 'Craniorraquisquise', 'Q00.1 Craniorraquisquise'),
  ('Q002', 'Iniencefalia', 'Q00.2 Iniencefalia'),
  ('Q01', 'Encefalocele', 'Q01 Encefalocele'),
  ('Q010', 'Encefalocele frontal', 'Q01.0 Encefalocele frontal'),
  ('Q011', 'Encefalocele nasofrontal', 'Q01.1 Encefalocele nasofrontal'),
  ('Q012', 'Encefalocele occipital', 'Q01.2 Encefalocele occipital'),
  ('Q018', 'Encefalocele de outras localizações', 'Q01.8 Encefalocele de outr localiz'),
  ('Q019', 'Encefalocele não especificada', 'Q01.9 Encefalocele NE'),
  ('Q02', 'Microcefalia', 'Q02 Microcefalia'),
  ('Q02', 'Microcefalia', 'Q02 Microcefalia'),
  ('Q03', 'Hidrocefalia congênita', 'Q03 Hidrocefalia congen'),
  ('Q030', 'Malformações do aqueduto de Sylvius', 'Q03.0 Malformacoes do aqueduto de Sylvius'),
  ('Q031', 'Atresia das fendas de Luschka e do forâmen de Magendie', 'Q03.1 Atresia fendas Luschka e foramen Magendie'),
  ('Q038', 'Outra hidrocefalia congênita', 'Q03.8 Outr hidrocefalia congen'),
  ('Q039', 'Hidrocefalia congênita não especificada', 'Q03.9 Hidrocefalia congen NE'),
  ('Q04', 'Outras malformações congênitas do cérebro', 'Q04 Outr malformacoes congen do cerebro'),
  ('Q040', 'Malformações congênitas do corpo caloso', 'Q04.0 Malformacoes congen do corpo caloso'),
  ('Q041', 'Arrinencefalia', 'Q04.1 Arrinencefalia'),
  ('Q042', 'Holoprosencefalia', 'Q04.2 Holoprosencefalia'),
  ('Q043', 'Outras deformidades por redução do encéfalo', 'Q04.3 Outr deform p/reducao do encefalo'),
  ('Q044', 'Displasia do septo e das vias ópticas', 'Q04.4 Displasia do septo e das vias opticas'),
  ('Q045', 'Megalencefalia', 'Q04.5 Megalencefalia'),
  ('Q046', 'Cistos cerebrais congênitos', 'Q04.6 Cistos cerebrais congen'),
  ('Q048', 'Outras malformações congênitas especificadas do encéfalo', 'Q04.8 Outr malformacoes congen espec do encefalo'),
  ('Q049', 'Malformação congênita não especificada do encéfalo', 'Q04.9 Malformacao congen NE do encefalo'),
  ('Q05', 'Espinha bífida', 'Q05 Espinha bifida'),
  ('Q050', 'Espinha bífida cervical com hidrocefalia', 'Q05.0 Espinha bifida cervical c/hidrocefalia'),
  ('Q051', 'Espinha bífida torácica com hidrocefalia', 'Q05.1 Espinha bifida toracica c/hidrocefalia'),
  ('Q052', 'Espinha bífida lombar com hidrocefalia', 'Q05.2 Espinha bifida lombar c/hidrocefalia'),
  ('Q053', 'Espinha bífida sacra com hidrocefalia', 'Q05.3 Espinha bifida sacra c/hidrocefalia'),
  ('Q054', 'Espinha bífida não especificada, com hidrocefalia', 'Q05.4 Espinha bifida NE c/hidrocefalia'),
  ('Q055', 'Espinha bífida cervical, sem hidrocefalia', 'Q05.5 Espinha bifida cervical s/hidrocefalia'),
  ('Q056', 'Espinha bífida torácica, sem hidrocefalia', 'Q05.6 Espinha bifida toracica s/hidrocefalia'),
  ('Q057', 'Espinha bífida lombar, sem hidrocefalia', 'Q05.7 Espinha bifida lombar s/hidrocefalia'),
  ('Q058', 'Espinha bífida sacra, sem hidrocefalia', 'Q05.8 Espinha bifida sacra s/hidrocefalia'),
  ('Q059', 'Espinha bífida não especificada', 'Q05.9 Espinha bifida NE'),
  ('Q06', 'Outras malformações congênitas da medula espinhal', 'Q06 Outr malformacoes congen da medula espinhal'),
  ('Q060', 'Amielia', 'Q06.0 Amielia'),
  ('Q061', 'Hipoplasia e displasia da medula espinal', 'Q06.1 Hipoplasia e displasia da medula espinal'),
  ('Q062', 'Diastematomielia', 'Q06.2 Diastematomielia'),
  ('Q063', 'Outras malformações congênitas da cauda eqüina', 'Q06.3 Outr malformacoes congen da cauda equina'),
  ('Q064', 'Hidromielia', 'Q06.4 Hidromielia'),
  ('Q068', 'Outras malformações congênitas especificadas da medula espinal', 'Q06.8 Outr malform congen espec medula espinal'),
  ('Q069', 'Malformação congênita não especificada da medula espinal', 'Q06.9 Malformacao congen NE da medula espinal'),
  ('Q07', 'Outras malformações congênitas do sistema nervoso', 'Q07 Outr malformacoes congen do sist nervoso'),
  ('Q070', 'Síndrome de Arnold-Chiari', 'Q07.0 Sindr de Arnold-Chiari'),
  ('Q078', 'Outras malformações congênitas especificadas do sistema nervoso', 'Q07.8 Outr malformacoes congen espec sist nervoso'),
  ('Q079', 'Malformação congênita não especificada do sistema nervoso', 'Q07.9 Malformacao congen NE do sist nervoso'),
  ('Q10', 'Malformações congênitas das pálpebras, do aparelho lacrimal e da órbita', 'Q10 Malform congen palpebras ap lacrimal orbita'),
  ('Q100', 'Ptose congênita', 'Q10.0 Ptose congen'),
  ('Q101', 'Ectrópio congênito', 'Q10.1 Ectropio congen'),
  ('Q102', 'Entrópio congênito', 'Q10.2 Entropio congen'),
  ('Q103', 'Outras malformações congênitas das pálpebras', 'Q10.3 Outr malformacoes congen das palpebras'),
  ('Q104', 'Ausência ou agenesia do aparelho lacrimal', 'Q10.4 Ausencia ou agenesia do aparelho lacrimal'),
  ('Q105', 'Estenose ou estreitamento congênito do canal lacrimal', 'Q10.5 Estenose ou estreit congen canal lacrimal'),
  ('Q106', 'Outras malformações congênitas do aparelho lacrimal', 'Q10.6 Outr malformacoes congen aparelho lacrimal'),
  ('Q107', 'Malformação congênita da órbita', 'Q10.7 Malformacao congen da orbita'),
  ('Q11', 'Anoftalmia, microftalmia e macroftalmia', 'Q11 Anoftalmia microftalmia e macroftalmia'),
  ('Q110', 'Olho cístico', 'Q11.0 Olho cistico'),
  ('Q111', 'Outras formas de anoftalmia', 'Q11.1 Outr form de anoftalmia'),
  ('Q112', 'Microftalmia', 'Q11.2 Microftalmia'),
  ('Q113', 'Macroftalmia', 'Q11.3 Macroftalmia'),
  ('Q12', 'Malformações congênitas do cristalino', 'Q12 Malformacoes congen do cristalino'),
  ('Q120', 'Catarata congênita', 'Q12.0 Catarata congen'),
  ('Q121', 'Luxação congênita do cristalino', 'Q12.1 Luxacao congen do cristalino'),
  ('Q122', 'Coloboma do cristalino', 'Q12.2 Coloboma do cristalino'),
  ('Q123', 'Afaquia congênita', 'Q12.3 Afaquia congen'),
  ('Q124', 'Esferofaquia', 'Q12.4 Esferofaquia'),
  ('Q128', 'Outras malformações congênitas do cristalino', 'Q12.8 Outr malformacoes congen do cristalino'),
  ('Q129', 'Malformação congênita não especificada do cristalino', 'Q12.9 Malformacao congen NE do cristalino'),
  ('Q13', 'Malformações congênitas da câmara anterior do olho', 'Q13 Malformacoes congen camara anterior do olho'),
  ('Q130', 'Coloboma da íris', 'Q13.0 Coloboma da iris'),
  ('Q131', 'Ausência de íris', 'Q13.1 Ausencia de iris'),
  ('Q132', 'Outras malformações congênitas da íris', 'Q13.2 Outr malformacoes congen da iris'),
  ('Q133', 'Opacidade congênita da córnea', 'Q13.3 Opacidade congen da cornea'),
  ('Q134', 'Outras malformações congênitas da córnea', 'Q13.4 Outr malformacoes congen da cornea'),
  ('Q135', 'Esclerótica azul', 'Q13.5 Esclerotica azul'),
  ('Q138', 'Outras malformações congênitas da câmara anterior do olho', 'Q13.8 Outr malform congen camara anterior olho'),
  ('Q139', 'Malformação congênita não especificada da câmara anterior do olho', 'Q13.9 Malformacao congen NE camara anterior olho'),
  ('Q14', 'Malformações congênitas da câmara posterior do olho', 'Q14 Malformacoes congen camara posterior do olho'),
  ('Q140', 'Malformação congênita do humor vítreo', 'Q14.0 Malformacao congen do humor vitreo'),
  ('Q141', 'Malformação congênita da retina', 'Q14.1 Malformacao congen da retina'),
  ('Q142', 'Malformação congênita do disco óptico', 'Q14.2 Malformacao congen do disco optico'),
  ('Q143', 'Malformação congênita da coróide', 'Q14.3 Malformacao congen da coroide'),
  ('Q148', 'Outras malformações congênitas da câmara posterior do olho', 'Q14.8 Outr malform congen camara posterior olho'),
  ('Q149', 'Malformação congênita não especificada da câmara posterior do olho', 'Q14.9 Malformacao congen NE camara posterior olho'),
  ('Q15', 'Outras malformações congênitas do olho', 'Q15 Outr malformacoes congen do olho'),
  ('Q150', 'Glaucoma congênito', 'Q15.0 Glaucoma congen'),
  ('Q158', 'Outras malformações congênitas especificadas do olho', 'Q15.8 Outr malformacoes congen espec do olho'),
  ('Q159', 'Malformação congênita não especificada do olho', 'Q15.9 Malformacao congen NE do olho'),
  ('Q16', 'Malformações congênitas do ouvido causando comprometimento da audição', 'Q16 Malform congen ouvido caus compr audicao'),
  ('Q160', 'Ausência congênita do pavilhão auricular (orelha)', 'Q16.0 Ausencia congen do pavilhao auricular'),
  ('Q161', 'Ausência, atresia e estreitamento congênitos do conduto auditivo (externo)', 'Q16.1 Ausencia atresia estreit congen cond audit'),
  ('Q162', 'Ausência da trompa de Eustáquio', 'Q16.2 Ausencia da trompa de Eustaquio'),
  ('Q163', 'Malformação congênita dos ossículos do ouvido', 'Q16.3 Malformacao congen dos ossiculos do ouvido'),
  ('Q164', 'Outras malformações congênitas do ouvido médio', 'Q16.4 Outr malformacoes congen do ouvido medio'),
  ('Q165', 'Malformação congênita do ouvido interno', 'Q16.5 Malformacao congen do ouvido interno'),
  ('Q169', 'Malformação congênita do ouvido não especificada causando comprometimento da audição', 'Q16.9 Malform congen ouvido NE caus compr audicao'),
  ('Q17', 'Outras malformações congênitas da orelha', 'Q17 Outr malformacoes congen da orelha'),
  ('Q170', 'Pavilhão supranumerário', 'Q17.0 Pavilhao supranumerario'),
  ('Q171', 'Macrotia', 'Q17.1 Macrotia'),
  ('Q172', 'Microtia', 'Q17.2 Microtia'),
  ('Q173', 'Outras deformidades da orelha', 'Q17.3 Outr deform da orelha'),
  ('Q174', 'Anomalia de posição da orelha', 'Q17.4 Anomalia de posicao da orelha'),
  ('Q175', 'Orelhas proeminentes', 'Q17.5 Orelhas proeminentes'),
  ('Q178', 'Outras malformações congênitas especificadas da orelha', 'Q17.8 Outr malformacoes congen espec da orelha'),
  ('Q179', 'Malformação congênita não especificada da orelha', 'Q17.9 Malformacao congen NE da orelha'),
  ('Q18', 'Outras malformações congênitas da face e do pescoço', 'Q18 Outr malformacoes congen da face e pescoco'),
  ('Q180', 'Seio, fístula e cisto de origem branquial', 'Q18.0 Seio fistula e cisto orig branquial'),
  ('Q181', 'Seio, fístula e cisto pré-auricular', 'Q18.1 Seio fistula e cisto pre-auricular'),
  ('Q182', 'Outras malformações da fenda branquial', 'Q18.2 Outr malformacoes da fenda branquial'),
  ('Q183', 'Pescoço alado', 'Q18.3 Pescoco alado'),
  ('Q184', 'Macrostomia', 'Q18.4 Macrostomia'),
  ('Q185', 'Microstomia', 'Q18.5 Microstomia'),
  ('Q186', 'Macroqueilia', 'Q18.6 Macroqueilia'),
  ('Q187', 'Microqueilia', 'Q18.7 Microqueilia'),
  ('Q188', 'Outras malformações congênitas especificadas da face e do pescoço', 'Q18.8 Outr malformacoes congen espec face pescoco'),
  ('Q189', 'Malformação congênita não especificada da face e do pescoço', 'Q18.9 Malformacao congen NE da face e do pescoco'),
  ('Q20', 'Malformações congênitas das câmaras e das comunicações cardíacas', 'Q20 Malform congen camaras e comunicacoes card'),
  ('Q200', 'Tronco arterial comum', 'Q20.0 Tronco arterial comum'),
  ('Q201', 'Ventrículo direito com dupla via de saída', 'Q20.1 Ventriculo direito c/dupla via de saida'),
  ('Q202', 'Ventrículo esquerdo com dupla via de saída', 'Q20.2 Ventriculo esquerdo c/dupla via de saida'),
  ('Q203', 'Comunicação ventrículo-atrial discordante', 'Q20.3 Comunicacao ventriculo-atrial discordante'),
  ('Q204', 'Ventrículo com dupla via de entrada', 'Q20.4 Ventriculo c/dupla via de entrada'),
  ('Q205', 'Comunicação átrio-ventricular discordante', 'Q20.5 Comunicacao atrio-ventricular discordante'),
  ('Q206', 'Isomerismo dos apêndices atriais', 'Q20.6 Isomerismo dos apendices atriais'),
  ('Q208', 'Outras malformações congênitas das câmaras e das comunicações cardíacas', 'Q20.8 Outr malform congen camaras e comunic card'),
  ('Q209', 'Malformação congênita não especificada das câmaras e das comunicações cardíacas', 'Q20.9 Malformacao congen NE camaras e comumic card'),
  ('Q21', 'Malformações congênitas dos septos cardíacos', 'Q21 Malformacoes congen dos septos cardiacos'),
  ('Q210', 'Comunicação interventricular', 'Q21.0 Comunicacao interventricular'),
  ('Q211', 'Comunicação interatrial', 'Q21.1 Comunicacao interatrial'),
  ('Q212', 'Comunicação atrioventricular', 'Q21.2 Comunicacao atrioventricular'),
  ('Q213', 'Tetralogia de Fallot', 'Q21.3 Tetralogia de Fallot'),
  ('Q214', 'Comunicação aortopulmonar', 'Q21.4 Comunicacao aortopulmonar'),
  ('Q218', 'Outras malformações congênitas dos septos cardíacos', 'Q21.8 Outr malformacoes congen septos cardiacos'),
  ('Q219', 'Malformação congênita não especificada de septo cardíaco', 'Q21.9 Malformacao congen NE de septo cardiaco'),
  ('Q22', 'Malformações congênitas das valvas pulmonar e tricúspide', 'Q22 Malform congen valvas pulmonar tricuspide'),
  ('Q220', 'Atresia da valva pulmonar', 'Q22.0 Atresia da valva pulmonar'),
  ('Q221', 'Estenose congênita da valva pulmonar', 'Q22.1 Estenose congen da valva pulmonar'),
  ('Q222', 'Insuficiência congênita da valva pulmonar', 'Q22.2 Insuf congen da valva pulmonar'),
  ('Q223', 'Outras malformações congênitas da valva pulmonar', 'Q22.3 Outr malformacoes congen da valva pulmonar'),
  ('Q224', 'Estenose congênita da valva tricúspide', 'Q22.4 Estenose congen da valva tricuspide'),
  ('Q225', 'Anomalia de Ebstein', 'Q22.5 Anomalia de Ebstein'),
  ('Q226', 'Síndrome do coração direito hipoplásico', 'Q22.6 Sindr do coracao direito hipoplasico'),
  ('Q228', 'Outras malformações congênitas da valva tricúspide', 'Q22.8 Outr malformacoes congen da valva tricuspide'),
  ('Q229', 'Malformação congênita não especificada da valva tricúspide', 'Q22.9 Malformacao congen NE da valva tricuspide'),
  ('Q23', 'Malformações congênitas das valvas aórtica e mitral', 'Q23 Malformacoes congen valvas aortica e mitral'),
  ('Q230', 'Estenose congênita da valva aórtica', 'Q23.0 Estenose congen da valva aortica'),
  ('Q231', 'Insuficiência congênita da valva aórtica', 'Q23.1 Insuf congen da valva aortica'),
  ('Q232', 'Estenose mitral congênita', 'Q23.2 Estenose mitral congen'),
  ('Q233', 'Insuficiência mitral congênita', 'Q23.3 Insuf mitral congen'),
  ('Q234', 'Síndrome do coração esquerdo hipoplásico', 'Q23.4 Sindr do coracao esquerdo hipoplasico'),
  ('Q238', 'Outras malformações congênitas das valvas aórtica e mitral', 'Q23.8 Outr malform congen valvas aortica mitral'),
  ('Q239', 'Malformação congênita não especificada das valvas aórtica e mitral', 'Q23.9 Malformacao congen NE valvas aortica mitral'),
  ('Q24', 'Outras malformações congênitas do coração', 'Q24 Outr malformacoes congen do coracao'),
  ('Q240', 'Dextrocardia', 'Q24.0 Dextrocardia'),
  ('Q241', 'Levocardia', 'Q24.1 Levocardia'),
  ('Q242', 'Cor triatriatum', 'Q24.2 Cor triatriatum'),
  ('Q243', 'Estenose do infundíbulo pulmonar', 'Q24.3 Estenose do infundibulo pulmonar'),
  ('Q244', 'Estenose subaórtica congênita', 'Q24.4 Estenose subaortica congen'),
  ('Q245', 'Malformações dos vasos coronários', 'Q24.5 Malformacoes dos vasos coronarios'),
  ('Q246', 'Bloqueio congênito do coração', 'Q24.6 Bloqueio congen do coracao'),
  ('Q248', 'Outras malformações congênitas especificadas do coração', 'Q24.8 Outr malformacoes congen espec do coracao'),
  ('Q249', 'Malformação não especificada do coração', 'Q24.9 Malformacao NE do coracao'),
  ('Q25', 'Malformações congênitas das grandes artérias', 'Q25 Malformacoes congen das grandes arterias'),
  ('Q250', 'Permeabilidade do canal arterial', 'Q25.0 Permeabilidade do canal arterial'),
  ('Q251', 'Coartação da aorta', 'Q25.1 Coartacao da aorta'),
  ('Q252', 'Atresia da aorta', 'Q25.2 Atresia da aorta'),
  ('Q253', 'Estenose da aorta', 'Q25.3 Estenose da aorta'),
  ('Q254', 'Outras malformações congênitas da aorta', 'Q25.4 Outr malformacoes congen da aorta'),
  ('Q255', 'Atresia da artéria pulmonar', 'Q25.5 Atresia da arteria pulmonar'),
  ('Q256', 'Estenose da artéria pulmonar', 'Q25.6 Estenose da arteria pulmonar'),
  ('Q257', 'Outras malformações congênitas da artéria pulmonar', 'Q25.7 Outr malformacoes congen da arteria pulmonar'),
  ('Q258', 'Outras malformações congênitas das grandes artérias', 'Q25.8 Outr malformacoes congen grandes arterias'),
  ('Q259', 'Malformação congênita não especificada das grandes artérias', 'Q25.9 Malformacao congen NE das grandes arterias'),
  ('Q26', 'Malformações congênitas das grandes veias', 'Q26 Malformacoes congen das grandes veias'),
  ('Q260', 'Estenose congênita da veia cava', 'Q26.0 Estenose congen da veia cava'),
  ('Q261', 'Persistência da veia cava superior esquerda', 'Q26.1 Persistencia da veia cava super esquerda'),
  ('Q262', 'Comunicação venosa pulmonar anormal total', 'Q26.2 Comunicacao venosa pulmonar anormal total'),
  ('Q263', 'Comunicação venosa pulmonar anormal parcial', 'Q26.3 Comunicacao venosa pulmonar anormal parcial'),
  ('Q264', 'Comunicação venosa pulmonar anormal não especificado', 'Q26.4 Comunicacao venosa pulmonar anormal NE'),
  ('Q265', 'Comunicação venosa portal anormal', 'Q26.5 Comunicacao venosa portal anormal'),
  ('Q266', 'Fístula entre a veia porta e a artéria hepática', 'Q26.6 Fistula entre veia porta e arteria hepatica'),
  ('Q268', 'Outras malformações congênitas das grandes veias', 'Q26.8 Outr malformacoes congen das grandes veias'),
  ('Q269', 'Malformação congênita não especificada de grande veia', 'Q26.9 Malformacao congen NE de grande veia'),
  ('Q27', 'Outras malformações congênitas do sistema vascular periférico', 'Q27 Outr malformacoes congen sist vasc perif'),
  ('Q270', 'Ausência congênita e hipoplasia da artéria umbilical', 'Q27.0 Ausencia congen e hipoplasia arteria umbilic'),
  ('Q271', 'Estenose congênita da artéria renal', 'Q27.1 Estenose congen da arteria renal'),
  ('Q272', 'Outras malformações congênitas da artéria renal', 'Q27.2 Outr malformacoes congen da arteria renal'),
  ('Q273', 'Malformação artério-venosa periférica', 'Q27.3 Malformacao arterio-venosa periferica'),
  ('Q274', 'Ectasia venosa (flebectasia) congênita', 'Q27.4 Ectasia venosa congen'),
  ('Q278', 'Outras malformações congênitas especificadas do sistema vascular periférico', 'Q27.8 Outr malform congen espec sist vasc perif'),
  ('Q279', 'Malformação congênita não especificada do sistema vascular periférico', 'Q27.9 Malformacao congen NE do sist vasc perif'),
  ('Q28', 'Outras malformações congênitas do aparelho circulatório', 'Q28 Outr malform congen aparelho circulatorio'),
  ('Q280', 'Malformação arteriovenosa de vasos pré-cerebrais', 'Q28.0 Malform arteriovenosa de vasos pre-cerebrais'),
  ('Q281', 'Outras malformações dos vasos pré-cerebrais', 'Q28.1 Outr malformacoes dos vasos pre-cerebrais'),
  ('Q282', 'Malformação arteriovenosa dos vasos cerebrais', 'Q28.2 Malform arteriovenosa dos vasos cerebrais'),
  ('Q283', 'Outras malformações dos vasos cerebrais', 'Q28.3 Outr malformacoes dos vasos cerebrais'),
  ('Q288', 'Outras malformações congênitas especificadas do aparelho circulatório', 'Q28.8 Outr malform congen espec aparelho circulat'),
  ('Q289', 'Malformação congênita não especificada do aparelho circulatório', 'Q28.9 Malform congen NE do aparelho circulatorio'),
  ('Q30', 'Malformação congênita do nariz', 'Q30 Malformacao congen do nariz'),
  ('Q300', 'Atresia das coanas', 'Q30.0 Atresia das coanas'),
  ('Q301', 'Agenesia ou hipoplasia do nariz', 'Q30.1 Agenesia ou hipoplasia do nariz'),
  ('Q302', 'Fissura, entalhe ou fenda nasal', 'Q30.2 Fissura entalhe ou fenda nasal'),
  ('Q303', 'Perfuração congênita do septo nasal', 'Q30.3 Perfuracao congen do septo nasal'),
  ('Q308', 'Outras malformações congênitas do nariz', 'Q30.8 Outr malformacoes congen do nariz'),
  ('Q309', 'Malformação congênita não especificada do nariz', 'Q30.9 Malformacao congen NE do nariz'),
  ('Q31', 'Malformações congênitas da laringe', 'Q31 Malformacoes congen da laringe'),
  ('Q310', 'Pterígio da laringe', 'Q31.0 Pterigio da laringe'),
  ('Q311', 'Estenose subglótica congênita', 'Q31.1 Estenose subglotica congen'),
  ('Q312', 'Hipoplasia da laringe', 'Q31.2 Hipoplasia da laringe'),
  ('Q313', 'Laringocele', 'Q31.3 Laringocele'),
  ('Q315', 'Laringomalácia congênita', 'Q31.5 Laringomalacia congenita'),
  ('Q318', 'Outras malformações congênitas da laringe', 'Q31.8 Outr malformacoes congen da laringe'),
  ('Q319', 'Malformação congênita não especificada da laringe', 'Q31.9 Malformacao congen NE da laringe'),
  ('Q32', 'Malformações congênitas da traquéia e dos brônquios', 'Q32 Malformacoes congen traqueia e bronquios'),
  ('Q320', 'Traqueomalácia congênita', 'Q32.0 Traqueomalacia congen'),
  ('Q321', 'Outras malformações congênitas da traquéia', 'Q32.1 Outr malformacoes congen da traqueia'),
  ('Q322', 'Broncomalácia congênita', 'Q32.2 Broncomalacia congen'),
  ('Q323', 'Estenose congênita dos brônquios', 'Q32.3 Estenose congen dos bronquios'),
  ('Q324', 'Outras malformações congênitas dos brônquios', 'Q32.4 Outr malformacoes congen dos bronquios'),
  ('Q33', 'Malformações congênitas do pulmão', 'Q33 Malformacoes congen do pulmao'),
  ('Q330', 'Pulmão cístico congênito', 'Q33.0 Pulmao cistico congen'),
  ('Q331', 'Lobo pulmonar supranumerário', 'Q33.1 Lobo pulmonar supranumerario'),
  ('Q332', 'Seqüestro pulmonar', 'Q33.2 Sequestro pulmonar'),
  ('Q333', 'Agenesia do pulmão', 'Q33.3 Agenesia do pulmao'),
  ('Q334', 'Bronquectasia congênita', 'Q33.4 Bronquectasia congen'),
  ('Q335', 'Tecido ectópico intrapulmonar', 'Q33.5 Tec ectopico intrapulmonar'),
  ('Q336', 'Hipoplasia e displasia do pulmão', 'Q33.6 Hipoplasia e displasia do pulmao'),
  ('Q338', 'Outras malformações congênitas do pulmão', 'Q33.8 Outr malformacoes congen do pulmao'),
  ('Q339', 'Malformação congênita não especificada do pulmão', 'Q33.9 Malformacao congen NE do pulmao'),
  ('Q34', 'Outras malformações congênitas do aparelho respiratório', 'Q34 Outr malformacoes congen aparelho respirat'),
  ('Q340', 'Anomalia da pleura', 'Q34.0 Anomalia da pleura'),
  ('Q341', 'Cisto congênito do mediastino', 'Q34.1 Cisto congen do mediastino'),
  ('Q348', 'Outras malformações congênitas especificadas do aparelho respiratório', 'Q34.8 Outr malform congen espec aparelho respirat'),
  ('Q349', 'Malformação congênita não especificada do aparelho respiratório', 'Q34.9 Malformacao congen NE do aparelho respirat'),
  ('Q35', 'Fenda palatina', 'Q35 Fenda palatina'),
  ('Q351', 'Fenda do palato duro', 'Q35.1 Fenda do palato duro'),
  ('Q353', 'Fenda do palato mole', 'Q35.3 Fenda do palato mole'),
  ('Q355', 'Fenda do palato duro com fenda do palato mole', 'Q35.5 Fenda do palato duro c/fenda do palato mole'),
  ('Q357', 'Fenda da úvula', 'Q35.7 Fenda da uvula'),
  ('Q359', 'Fenda palatina não especificada', 'Q35.9 Fenda palatina NE'),
  ('Q36', 'Fenda labial', 'Q36 Fenda labial'),
  ('Q360', 'Fenda labial bilateral', 'Q36.0 Fenda labial bilateral'),
  ('Q361', 'Fenda labial mediana', 'Q36.1 Fenda labial mediana'),
  ('Q369', 'Fenda labial unilateral', 'Q36.9 Fenda labial unilateral'),
  ('Q37', 'Fenda labial com fenda palatina', 'Q37 Fenda labial c/fenda palatina'),
  ('Q370', 'Fenda do palato duro com fenda labial bilateral', 'Q37.0 Fenda palato duro c/fenda labial bilateral'),
  ('Q371', 'Fenda do palato duro com fenda labial unilateral', 'Q37.1 Fenda palato duro c/fenda labial unilateral'),
  ('Q372', 'Fenda do palato mole com fenda labial bilateral', 'Q37.2 Fenda palato mole c/fenda labial bilateral'),
  ('Q373', 'Fenda do palato mole com fenda labial unilateral', 'Q37.3 Fenda palato mole c/fenda labial unilateral'),
  ('Q374', 'Fenda dos palatos duro e mole com fenda labial bilateral', 'Q37.4 Fenda palatos duro mole c/fenda labial bilat'),
  ('Q375', 'Fenda dos palatos duro e mole com fenda labial unilateral', 'Q37.5 Fenda palatos duro mole c/fend labial unilat'),
  ('Q378', 'Fenda do palato com fenda labial bilateral, não especificada', 'Q37.8 Fenda do palato c/fenda labial bilateral NE'),
  ('Q379', 'Fenda do palato com fenda labial unilateral, não especificada', 'Q37.9 Fenda do palato c/fenda labial unilateral NE'),
  ('Q38', 'Outras malformações congênitas da língua, da boca e da faringe', 'Q38 Outr malform congen lingua boca e faringe'),
  ('Q380', 'Malformações congênitas dos lábios, não classificadas em outra parte', 'Q38.0 Malformacoes congen dos labios NCOP'),
  ('Q381', 'Anquiloglossia', 'Q38.1 Anquiloglossia'),
  ('Q382', 'Macroglossia', 'Q38.2 Macroglossia'),
  ('Q383', 'Outras malformações congênitas da língua', 'Q38.3 Outr malformacoes congen da lingua'),
  ('Q384', 'Malformações congênitas das glândulas e dutos salivares', 'Q38.4 Malformacoes congen gland e dutos salivares'),
  ('Q385', 'Malformações congênitas do palato não classificadas em outra parte', 'Q38.5 Malformacoes congen do palato NCOP'),
  ('Q386', 'Outras malformações congênitas da boca', 'Q38.6 Outr malformacoes congen da boca'),
  ('Q387', 'Bolsa faríngea', 'Q38.7 Bolsa faringea'),
  ('Q388', 'Outras malformações congênitas da faringe', 'Q38.8 Outr malformacoes congen da faringe'),
  ('Q39', 'Malformações congênitas do esôfago', 'Q39 Malformacoes congen do esofago'),
  ('Q390', 'Atresia de esôfago, sem fístula', 'Q39.0 Atresia de esofago s/fistula'),
  ('Q391', 'Atresia de esôfago, com fístula traqueoesofágica', 'Q39.1 Atresia esofago c/fistula traqueoesofagica'),
  ('Q392', 'Fístula traqueoesofágica congênita, sem atresia', 'Q39.2 Fistula traqueoesofagica congen s/atresia'),
  ('Q393', 'Estenose congênita e estreitamento congênito do esôfago', 'Q39.3 Estenose congen e estreit congen esofago'),
  ('Q394', 'Pterígio do esôfago', 'Q39.4 Pterigio do esofago'),
  ('Q395', 'Dilatação congênita do esôfago', 'Q39.5 Dilatacao congen do esofago'),
  ('Q396', 'Divertículo do esôfago', 'Q39.6 Diverticulo do esofago'),
  ('Q398', 'Outras malformações congênitas do esôfago', 'Q39.8 Outr malformacoes congen do esofago'),
  ('Q399', 'Malformação congênita não especificada do esôfago', 'Q39.9 Malformacao congen NE do esofago'),
  ('Q40', 'Outras malformações congênitas do trato digestivo superior', 'Q40 Outr malform congen trato digestivo super'),
  ('Q400', 'Estenose hipertrófica congênita do piloro', 'Q40.0 Estenose hipertrofica congen do piloro'),
  ('Q401', 'Hérnia congênita de hiato', 'Q40.1 Hernia congen de hiato'),
  ('Q402', 'Outras malformações congênitas especificadas do estômago', 'Q40.2 Outr malformacoes congen espec do estomago'),
  ('Q403', 'Malformação congênita não especificada do estômago', 'Q40.3 Malformacao congen NE do estomago'),
  ('Q408', 'Outras malformações congênitas especificadas do trato digestivo superior', 'Q40.8 Outr malform congen espec trato digest super'),
  ('Q409', 'Malformação congênita não especificada do trato digestivo superior', 'Q40.9 Malformacao congen NE trato digestivo super'),
  ('Q41', 'Ausência, atresia e estenose congênita do intestino delgado', 'Q41 Ausencia atresia estenose congen intest delg'),
  ('Q410', 'Ausência, atresia e estenose congênita do duodeno', 'Q41.0 Ausencia atresia e estenose congen duodeno'),
  ('Q411', 'Ausência, atresia e estenose congênita do jejuno', 'Q41.1 Ausencia atresia e estenose congen do jejuno'),
  ('Q412', 'Ausência, atresia e estenose congênita do íleo', 'Q41.2 Ausencia atresia e estenose congen do ileo'),
  ('Q418', 'Ausência, atresia e estenose congênita de outras partes especificadas do intestino delgado', 'Q41.8 Ausen atres esten cong out part esp int delg'),
  ('Q419', 'Ausência, atresia e estenose congênita do intestino delgado, sem especificação de localização', 'Q41.9 Ausen atres esten cong int delg s/espec loc'),
  ('Q42', 'Ausência, atresia e estenose congênita do cólon', 'Q42 Ausencia atresia e estenose congen do colon'),
  ('Q420', 'Ausência, atresia e estenose congênita do reto, com fístula', 'Q42.0 Ausencia atresia estenose congen reto c/fist'),
  ('Q421', 'Ausência, atresia e estenose congênita do reto, sem fístula', 'Q42.1 Ausencia atresia estenose congen reto s/fist'),
  ('Q422', 'Ausência, atresia e estenose congênita do ânus, com fístula', 'Q42.2 Ausencia atresia estenose congen anus c/fist'),
  ('Q423', 'Ausência, atresia e estenose congênita do ânus, sem fístula', 'Q42.3 Ausencia atresia estenose congen anus s/fist'),
  ('Q428', 'Ausência, atresia e estenose congênita de outras partes do cólon (intestino grosso)', 'Q42.8 Ausenc atres estenose congen outr part colon'),
  ('Q429', 'Ausência, atresia e estenose congênita de partes não especificadas do cólon (intestino grosso)', 'Q42.9 Ausenc atresia estenose congen part NE colon'),
  ('Q43', 'Outras malformações congênitas do intestino', 'Q43 Outr malformacoes congen do intestino'),
  ('Q430', 'Divertículo de Meckel', 'Q43.0 Diverticulo de Meckel'),
  ('Q431', 'Doença de Hirschsprung', 'Q43.1 Doenc de Hirschsprung'),
  ('Q432', 'Outros transtornos funcionais congênitos do cólon', 'Q43.2 Outr transt funcionais congen do colon'),
  ('Q433', 'Malformações congênitas da fixação do intestino', 'Q43.3 Malformacoes congen da fixacao do intestino'),
  ('Q434', 'Duplicação do intestino', 'Q43.4 Duplicacao do intestino'),
  ('Q435', 'Ânus ectópico', 'Q43.5 Anus ectopico'),
  ('Q436', 'Fístula congênita do reto e do ânus', 'Q43.6 Fistula congen do reto e do anus'),
  ('Q437', 'Persistência de cloaca', 'Q43.7 Persistencia de cloaca'),
  ('Q438', 'Outras malformações congênitas especificadas do intestino', 'Q43.8 Outr malformacoes congen espec do intestino'),
  ('Q439', 'Malformação congênita não especificada do intestino', 'Q43.9 Malformacao congen NE do intestino'),
  ('Q44', 'Malformações congênitas da vesícula biliar, das vias biliares e do fígado', 'Q44 Malform congen vesic biliar via biliar figad'),
  ('Q440', 'Agenesia, aplasia e hipoplasia da vesícula biliar', 'Q44.0 Agenesia aplasia hipoplasia vesicula biliar'),
  ('Q441', 'Outras malformações congênitas da vesícula biliar', 'Q44.1 Outr malformacoes congen da vesicula biliar'),
  ('Q442', 'Atresia das vias biliares', 'Q44.2 Atresia das vias biliares'),
  ('Q443', 'Estenose e estreitamento congênitos das vias biliares', 'Q44.3 Estenose estreitamento congen vias biliares'),
  ('Q444', 'Cisto do colédoco', 'Q44.4 Cisto do coledoco'),
  ('Q445', 'Outras malformações congênitas das vias biliares', 'Q44.5 Outr malformacoes congen das vias biliares'),
  ('Q446', 'Doença cística do fígado', 'Q44.6 Doenc cistica do figado'),
  ('Q447', 'Outras malformações congênitas do fígado', 'Q44.7 Outr malformacoes congen do figado'),
  ('Q45', 'Outras malformações congênitas do aparelho digestivo', 'Q45 Outr malformacoes congen aparelho digestivo'),
  ('Q450', 'Agenesia, aplasia e hipoplasia do pâncreas', 'Q45.0 Agenesia aplasia e hipoplasia do pancreas'),
  ('Q451', 'Pâncreas anular', 'Q45.1 Pancreas anular'),
  ('Q452', 'Cisto pancreático congênito', 'Q45.2 Cisto pancreatico congen'),
  ('Q453', 'Outras malformações congênitas do pâncreas e do duto pancreático', 'Q45.3 Outr malform congen pancreas duto pancreatic'),
  ('Q458', 'Outras malformações congênitas especificadas do aparelho digestivo', 'Q45.8 Outr malform congen espec aparelho digestivo'),
  ('Q459', 'Malformação congênita não especificada do aparelho digestivo', 'Q45.9 Malformacao congen NE do aparelho digestivo'),
  ('Q50', 'Malformações congênitas dos ovários, das trompas de Falópio e dos ligamentos largos', 'Q50 Malform cong ovario tromp Falopio lig largos'),
  ('Q500', 'Ausência congênita dos ovários', 'Q50.0 Ausencia congen dos ovarios'),
  ('Q501', 'Cisto ovariano de desenvolvimento', 'Q50.1 Cisto ovariano de desenvolv'),
  ('Q502', 'Torsão congênita do ovário', 'Q50.2 Torsao congen do ovario'),
  ('Q503', 'Outras malformações congênitas do ovário', 'Q50.3 Outr malformacoes congen do ovario'),
  ('Q504', 'Cisto embrionário da trompa de Falópio', 'Q50.4 Cisto embrionario da trompa de Falopio'),
  ('Q505', 'Cisto embrionário do ligamento largo', 'Q50.5 Cisto embrionario do ligamento largo'),
  ('Q506', 'Outras malformações congênitas das trompas de Falópio e dos ligamentos largos', 'Q50.6 Outr malform congen tromp Falopio lig largos'),
  ('Q51', 'Malformações congênitas do útero e do colo do útero', 'Q51 Malformacoes congen utero e do colo do utero'),
  ('Q510', 'Agenesia e aplasia do útero', 'Q51.0 Agenesia e aplasia do utero'),
  ('Q511', 'Útero duplo com duplicação do colo uterino e da vagina', 'Q51.1 Utero duplo c/duplicacao colo uterino vagina'),
  ('Q512', 'Outra duplicação do útero', 'Q51.2 Outr duplicacao do utero'),
  ('Q513', 'Útero bicórneo', 'Q51.3 Utero bicorneo'),
  ('Q514', 'Útero unicórneo', 'Q51.4 Utero unicorneo'),
  ('Q515', 'Agenesia e aplasia do colo do útero', 'Q51.5 Agenesia e aplasia do colo do utero'),
  ('Q516', 'Cisto embrionário do colo do útero', 'Q51.6 Cisto embrionario do colo do utero'),
  ('Q517', 'Fístula congênita útero-digestiva ou útero-urinária', 'Q51.7 Fistula congen utero-digest ou utero-urinar'),
  ('Q518', 'Outras malformações congênitas do útero e do colo do útero', 'Q51.8 Outr malformacoes congen utero colo do utero'),
  ('Q519', 'Malformação congênita não especificada do útero e do colo do útero SOE', 'Q51.9 Malformacao congen NE utero colo utero SOE'),
  ('Q52', 'Outras malformações congênitas dos órgãos genitais femininos', 'Q52 Outr malformacoes congen org genitais femin'),
  ('Q520', 'Ausência congênita da vagina', 'Q52.0 Ausencia congen da vagina'),
  ('Q521', 'Duplicação da vagina', 'Q52.1 Duplicacao da vagina'),
  ('Q522', 'Fístula reto-vaginal congênita', 'Q52.2 Fistula reto-vaginal congen'),
  ('Q523', 'Imperfuração do hímen', 'Q52.3 Imperfuracao do himen'),
  ('Q524', 'Outras malformações congênitas da vagina', 'Q52.4 Outr malformacoes congen da vagina'),
  ('Q525', 'Fusão dos lábios vulvares', 'Q52.5 Fusao dos labios vulvares'),
  ('Q526', 'Malformação congênita do clitóris', 'Q52.6 Malformacao congen do clitoris'),
  ('Q527', 'Outras malformações congênitas da vulva', 'Q52.7 Outr malformacoes congen da vulva'),
  ('Q528', 'Outras malformações congênitas especificadas dos órgãos genitais femininos', 'Q52.8 Outr malform congen espec org genitais femin'),
  ('Q529', 'Malformação congênita não especificada dos órgãos genitais femininos', 'Q52.9 Malform congen NE dos orgaos genitais femin'),
  ('Q53', 'Testículo não-descido', 'Q53 Testiculo nao-descido'),
  ('Q530', 'Testículo ectópico', 'Q53.0 Testiculo ectopico'),
  ('Q531', 'Testículo não-descido, unilateral', 'Q53.1 Testiculo nao-descido unilateral'),
  ('Q532', 'Testículo não-descido, bilateral', 'Q53.2 Testiculo nao-descido bilateral'),
  ('Q539', 'Testículo não-descido, não especificado', 'Q53.9 Testiculo nao-descido NE'),
  ('Q54', 'Hipospádias', 'Q54 Hipospadias'),
  ('Q540', 'Hipospádia balânica', 'Q54.0 Hipospadia balanica'),
  ('Q541', 'Hipospádia peniana', 'Q54.1 Hipospadia peniana'),
  ('Q542', 'Hipospádia penoscrotal', 'Q54.2 Hipospadia penoscrotal'),
  ('Q543', 'Hipospádia perineal', 'Q54.3 Hipospadia perineal'),
  ('Q544', 'Corda venérea congênita', 'Q54.4 Corda venerea congen'),
  ('Q548', 'Outras hipospádias', 'Q54.8 Outr hipospadias'),
  ('Q549', 'Hipospádia não especificada', 'Q54.9 Hipospadia NE'),
  ('Q55', 'Outras malformações congênitas dos órgãos genitais masculinos', 'Q55 Outr malformacoes congen org genitais masc'),
  ('Q550', 'Ausência e aplasia do testículo', 'Q55.0 Ausencia e aplasia do testiculo'),
  ('Q551', 'Hipoplasia do(s) testículo(s) e do escroto', 'Q55.1 Hipoplasia do testiculo e do escroto'),
  ('Q552', 'Outras malformações congênitas do(s) testículo(s) e do escroto', 'Q55.2 Outr malformacoes congen testiculo e escroto'),
  ('Q553', 'Atresia do canal deferente', 'Q55.3 Atresia do canal deferente'),
  ('Q554', 'Outras malformações congênitas do canal deferente, do epidídimo, das vesículas seminais e da próstata', 'Q55.4 Out malf cong can defer epid ves sem prostat'),
  ('Q555', 'Ausência e aplasia congênitas do pênis', 'Q55.5 Ausencia e aplasia congen do penis'),
  ('Q556', 'Outras malformações congênitas do pênis', 'Q55.6 Outr malformacoes congen do penis'),
  ('Q558', 'Outras malformações congênitas especificadas dos órgãos genitais masculinos', 'Q55.8 Outr malform congen espec org genitais masc'),
  ('Q559', 'Malformação congênita não especificada dos órgãos genitais masculinos', 'Q55.9 Malform congen NE dos orgaos genitais masc'),
  ('Q56', 'Sexo indeterminado e pseudo-hermafroditismo', 'Q56 Sexo indeterminado e pseudo-hermafroditismo'),
  ('Q560', 'Hermafroditismo não classificado em outra parte', 'Q56.0 Hermafroditismo NCOP'),
  ('Q561', 'Pseudo-hermafroditismo masculino, não classificado em outra parte', 'Q56.1 Pseudo-hermafroditismo masc NCOP'),
  ('Q562', 'Pseudo-hermafroditismo feminino, não classificado em outra parte', 'Q56.2 Pseudo-hermafroditismo femin NCOP'),
  ('Q563', 'Pseudo-hermafroditismo não especificado', 'Q56.3 Pseudo-hermafroditismo NE'),
  ('Q564', 'Sexo indeterminado, não especificado', 'Q56.4 Sexo indeterminado NE'),
  ('Q60', 'Agenesia renal e outros defeitos de redução do rim', 'Q60 Agenesia renal e outr defeitos reducao rim'),
  ('Q600', 'Agenesia unilateral do rim', 'Q60.0 Agenesia unilateral do rim'),
  ('Q601', 'Agenesia bilateral do rim', 'Q60.1 Agenesia bilateral do rim'),
  ('Q602', 'Agenesia renal não especificada', 'Q60.2 Agenesia renal NE'),
  ('Q603', 'Hipoplasia renal unilateral', 'Q60.3 Hipoplasia renal unilateral'),
  ('Q604', 'Hipoplasia renal bilateral', 'Q60.4 Hipoplasia renal bilateral'),
  ('Q605', 'Hipoplasia renal não especificada', 'Q60.5 Hipoplasia renal NE'),
  ('Q606', 'Síndrome de Potter', 'Q60.6 Sindr de Potter'),
  ('Q61', 'Doenças císticas do rim', 'Q61 Doenc cisticas do rim'),
  ('Q610', 'Cisto congênito único do rim', 'Q61.0 Cisto congen unico do rim'),
  ('Q611', 'Rim policístico, autossômico recessivo', 'Q61.1 Rim policistico autossomico recessivo'),
  ('Q612', 'Rim policístico, autossômico dominante', 'Q61.2 Rim policistico autossomico dominante'),
  ('Q613', 'Rim policístico não especificado', 'Q61.3 Rim policistico NE'),
  ('Q614', 'Displasia renal', 'Q61.4 Displasia renal'),
  ('Q615', 'Cisto medular do rim', 'Q61.5 Cisto medular do rim'),
  ('Q618', 'Outras doenças císticas do rim', 'Q61.8 Outr doenc cisticas do rim'),
  ('Q619', 'Doença cística não especificada do rim', 'Q61.9 Doenc cistica NE do rim'),
  ('Q62', 'Anomalias congênitas obstrutivas da pelve renal e malformações congênitas do ureter', 'Q62 Anom cong obstr pelv renal malf cong ureter'),
  ('Q620', 'Hidronefrose congênita', 'Q62.0 Hidronefrose congen'),
  ('Q621', 'Atresia e estenose do ureter', 'Q62.1 Atresia e estenose do ureter'),
  ('Q622', 'Megaureter congênito', 'Q62.2 Megaureter congen'),
  ('Q623', 'Outras anomalias obstrutivas da pelve renal e do ureter', 'Q62.3 Outr anom obstr da pelve renal e do ureter'),
  ('Q624', 'Agenesia do ureter', 'Q62.4 Agenesia do ureter'),
  ('Q625', 'Duplicação do ureter', 'Q62.5 Duplicacao do ureter'),
  ('Q626', 'Má-posição do ureter', 'Q62.6 Ma-posicao do ureter'),
  ('Q627', 'Refluxo vésico-uretero-renal congênito', 'Q62.7 Refluxo vesico-uretero-renal congen'),
  ('Q628', 'Outras malformações congênitas do ureter', 'Q62.8 Outr malformacoes congen do ureter'),
  ('Q63', 'Outras malformações congênitas do rim', 'Q63 Outr malformacoes congen do rim'),
  ('Q630', 'Rim supranumerário', 'Q63.0 Rim supranumerario'),
  ('Q631', 'Rim lobulado, fundido ou em ferradura', 'Q63.1 Rim lobulado fundido ou em ferradura'),
  ('Q632', 'Rim ectópico', 'Q63.2 Rim ectopico'),
  ('Q633', 'Rim hiperplásico e gigante', 'Q63.3 Rim hiperplasico e gigante'),
  ('Q638', 'Outras malformações congênitas especificadas do rim', 'Q63.8 Outr malformacoes congen espec do rim'),
  ('Q639', 'Malformação congênita não especificada do rim', 'Q63.9 Malformacao congen NE do rim'),
  ('Q64', 'Outras malformações congênitas do aparelho urinário', 'Q64 Outr malformacoes congen aparelho urinario'),
  ('Q640', 'Epispádias', 'Q64.0 Epispadias'),
  ('Q641', 'Extrofia vesical', 'Q64.1 Extrofia vesical'),
  ('Q642', 'Válvulas uretrais posteriores congênitas', 'Q64.2 Valvulas uretrais posteriores congen'),
  ('Q643', 'Outras formas de atresia e de estenose de uretra e do colo da bexiga', 'Q64.3 Outr form atresia estenose uretra colo bexig'),
  ('Q644', 'Malformação do úraco', 'Q64.4 Malformacao do uraco'),
  ('Q645', 'Ausência congênita da bexiga e da uretra', 'Q64.5 Ausencia congen da bexiga e da uretra'),
  ('Q646', 'Divertículo congênito da bexiga', 'Q64.6 Diverticulo congen da bexiga'),
  ('Q647', 'Outras malformações congênitas da bexiga e da uretra', 'Q64.7 Outr malformacoes congen da bexiga e uretra'),
  ('Q648', 'Outras malformações congênitas especificadas do aparelho urinário', 'Q64.8 Outr malform congen espec aparelho urinario'),
  ('Q649', 'Malformação congênita não especificada do aparelho urinário', 'Q64.9 Malformacao congen NE do aparelho urinario'),
  ('Q65', 'Malformações congênitas do quadril', 'Q65 Malformacoes congen do quadril'),
  ('Q650', 'Luxação congênita unilateral do quadril', 'Q65.0 Luxacao congen unilateral do quadril'),
  ('Q651', 'Luxação congênita bilateral do quadril', 'Q65.1 Luxacao congen bilateral do quadril'),
  ('Q652', 'Luxação congênita não especificada do quadril', 'Q65.2 Luxacao congen NE do quadril'),
  ('Q653', 'Subluxação congênita unilateral do quadril', 'Q65.3 Subluxacao congen unilateral do quadril'),
  ('Q654', 'Subluxação congênita bilateral do quadril', 'Q65.4 Subluxacao congen bilateral do quadril'),
  ('Q655', 'Subluxação congênita não especificada do quadril', 'Q65.5 Subluxacao congen NE do quadril'),
  ('Q656', 'Quadril instável', 'Q65.6 Quadril instavel'),
  ('Q658', 'Outras deformidades congênitas do quadril', 'Q65.8 Outr deform congen do quadril'),
  ('Q659', 'Deformidade congênita não especificada do quadril', 'Q65.9 Deform congen NE do quadril'),
  ('Q66', 'Deformidades congênitas do pé', 'Q66 Deform congen do pe'),
  ('Q660', 'Pé torto eqüinovaro', 'Q66.0 Pe torto equinovaro'),
  ('Q661', 'Pé torto calcaneovaro', 'Q66.1 Pe torto calcaneovaro'),
  ('Q662', 'Metatarso varo', 'Q66.2 Metatarso varo'),
  ('Q663', 'Outras deformidades congênitas dos pés em varo', 'Q66.3 Outr deform congen dos pes em varo'),
  ('Q664', 'Pé torto calcaneovalgo', 'Q66.4 Pe torto calcaneovalgo'),
  ('Q665', 'Pé chato congênito', 'Q66.5 Pe chato congen'),
  ('Q666', 'Outras deformidades congênitas dos pés em valgo', 'Q66.6 Outr deform congen dos pes em valgo'),
  ('Q667', 'Pé cavo', 'Q66.7 Pe cavo'),
  ('Q668', 'Outras deformidades congênitas do pé', 'Q66.8 Outr deform congen do pe'),
  ('Q669', 'Deformidade congênita não especificada do pé', 'Q66.9 Deform congen NE do pe'),
  ('Q67', 'Deformidades osteomusculares congênitas da cabeça, da face, da coluna e do tórax', 'Q67 Deform osteom cong cabeca face coluna torax'),
  ('Q670', 'Assimetria facial', 'Q67.0 Assimetria facial'),
  ('Q671', 'Deformidade facial por compressão', 'Q67.1 Deform facial p/compressao'),
  ('Q672', 'Dolicocefalia', 'Q67.2 Dolicocefalia'),
  ('Q673', 'Plagiocefalia', 'Q67.3 Plagiocefalia'),
  ('Q674', 'Outras deformidades congênitas do crânio, da face e da mandíbula', 'Q67.4 Outr deform congen cranio face e mandibula'),
  ('Q675', 'Deformidades congênitas da coluna vertebral', 'Q67.5 Deform congen da coluna vertebral'),
  ('Q676', 'Tórax escavado', 'Q67.6 Torax escavado'),
  ('Q677', 'Tórax carinado', 'Q67.7 Torax carinado'),
  ('Q678', 'Outras deformidades congênitas do tórax', 'Q67.8 Outr deform congen do torax'),
  ('Q68', 'Outras deformidades osteomusculares congênitas', 'Q68 Outr deform osteomusculares congen'),
  ('Q680', 'Deformidade congênita do músculo esternocleidomastoideu', 'Q68.0 Deform congen musculo esternocleidomastoideu'),
  ('Q681', 'Deformidade congênita da mão', 'Q68.1 Deform congen da mao'),
  ('Q682', 'Deformidade congênita do joelho', 'Q68.2 Deform congen do joelho'),
  ('Q683', 'Encurvamento congênito do fêmur', 'Q68.3 Encurvamento congen do femur'),
  ('Q684', 'Encurvamento congênito da tíbia e da perônio (fíbula)', 'Q68.4 Encurvamento congen da tibia e da peronio'),
  ('Q685', 'Encurvamento congênito de ossos longos não especificados do membro inferior', 'Q68.5 Encurv congen ossos longos NE membro infer'),
  ('Q688', 'Outras deformidades osteomusculares congênitas', 'Q68.8 Outr deform osteomusculares congen'),
  ('Q69', 'Polidactilia', 'Q69 Polidactilia'),
  ('Q690', 'Dedo(s) da mão supranumerário(s)', 'Q69.0 Dedos da mao supranumerarios'),
  ('Q691', 'Polegar(es) supranumerário(s)', 'Q69.1 Polegares supranumerarios'),
  ('Q692', 'Artelho(s) supranumerário(s)', 'Q69.2 Artelhos supranumerarios'),
  ('Q699', 'Polidactilia não especificada', 'Q69.9 Polidactilia NE'),
  ('Q70', 'Sindactilia', 'Q70 Sindactilia'),
  ('Q700', 'Coalescência dos dedos (dedos da mão fundidos)', 'Q70.0 Coalescencia dos dedos'),
  ('Q701', 'Dedos palmados', 'Q70.1 Dedos palmados'),
  ('Q702', 'Coalescência dos artelhos (artelhos fundidos)', 'Q70.2 Coalescencia dos artelhos'),
  ('Q703', 'Artelhos palmados', 'Q70.3 Artelhos palmados'),
  ('Q704', 'Polissindactilia', 'Q70.4 Polissindactilia'),
  ('Q709', 'Sindactilia não especificada', 'Q70.9 Sindactilia NE'),
  ('Q71', 'Defeitos, por redução, do membro superior', 'Q71 Defeitos p/reducao do membro super'),
  ('Q710', 'Ausência congênita completa do(s) membro(s) superior(es)', 'Q71.0 Ausencia congen completa de membros super'),
  ('Q711', 'Ausência congênita do braço e do antebraço, com mão presente', 'Q71.1 Ausencia congen braco antebraco c/mao pres'),
  ('Q712', 'Ausência congênita do antebraço e da mão', 'Q71.2 Ausencia congen do antebraco e da mao'),
  ('Q713', 'Ausência congênita da mão e de dedo(s)', 'Q71.3 Ausencia congen da mao e de dedos'),
  ('Q714', 'Defeito de redução longitudinal do rádio', 'Q71.4 Defeito de reducao longitudinal do radio'),
  ('Q715', 'Defeito de redução longitudinal do cúbito (ulna)', 'Q71.5 Defeito de reducao longitudinal do cubito'),
  ('Q716', 'Mão em garra de lagosta', 'Q71.6 Mao em garra de lagosta'),
  ('Q718', 'Outros defeitos de redução do membro superior', 'Q71.8 Outr defeitos de reducao do membro super'),
  ('Q719', 'Defeito por redução do membro superior, não especificado', 'Q71.9 Defeito p/reducao do membro super NE'),
  ('Q72', 'Defeitos, por redução, do membro inferior', 'Q72 Defeitos p/reducao do membro infer'),
  ('Q720', 'Ausência congênita completa do(s) membro(s) inferior(es)', 'Q72.0 Ausencia congen completa de membros infer'),
  ('Q721', 'Ausência congênita da coxa e da perna com pé presente', 'Q72.1 Ausencia congen coxa perna c/pe presente'),
  ('Q722', 'Ausência congênita da perna e do pé', 'Q72.2 Ausencia congen da perna e do pe'),
  ('Q723', 'Ausência congênita do pé e de artelho(s)', 'Q72.3 Ausencia congen do pe e de artelhos'),
  ('Q724', 'Defeito por redução longitudinal da tíbia', 'Q72.4 Defeito p/reducao longitudinal da tibia'),
  ('Q725', 'Defeito por redução longitudinal da tíbia', 'Q72.5 Defeito p/reducao longitudinal da tibia'),
  ('Q726', 'Defeito por redução longitudinal do perônio (fíbula)', 'Q72.6 Defeito p/reducao longitudinal do peronio'),
  ('Q727', 'Pé bífido', 'Q72.7 Pe bifido'),
  ('Q728', 'Outros defeitos por redução do(s) membro(s) inferior(es)', 'Q72.8 Outr defeitos p/reducao de membros infer'),
  ('Q729', 'Defeito não especificado por redução do membro inferior', 'Q72.9 Defeito NE p/reducao do membro infer'),
  ('Q73', 'Defeitos por redução de membro não especificado', 'Q73 Defeitos p/reducao de membro NE'),
  ('Q730', 'Ausência congênita de membro(s) não especificado(s)', 'Q73.0 Ausencia congen de membros NE'),
  ('Q731', 'Focomelia, membro(s) não especificado(s)', 'Q73.1 Focomelia membros NE'),
  ('Q738', 'Outros defeitos por redução de membro(s) não especificado(s)', 'Q73.8 Outr defeitos p/reducao de membros NE'),
  ('Q74', 'Outras malformações congênitas dos membros', 'Q74 Outr malformacoes congen dos membros'),
  ('Q740', 'Outras malformações congênitas do(s) membro(s) superiores, inclusive da cintura escapular', 'Q74.0 Out malform cong membr super incl cint escap'),
  ('Q741', 'Malformação congênita do joelho', 'Q74.1 Malformacao congen do joelho'),
  ('Q742', 'Outras malformações congênitas do(s) membro(s) inferiores, inclusive da cintura pélvica', 'Q74.2 Outr malform cong membros inf incl cint pelv'),
  ('Q743', 'Artrogripose congênita múltipla', 'Q74.3 Artrogripose congen mult'),
  ('Q748', 'Outras malformações congênitas especificadas de membro(s)', 'Q74.8 Outr malformacoes congen espec de membros'),
  ('Q749', 'Malformações congênitas não especificadas de membro(s)', 'Q74.9 Malformacoes congen NE de membros'),
  ('Q75', 'Outras malformações congênitas dos ossos do crânio e da face', 'Q75 Outr malformacoes congen ossos cranio e face'),
  ('Q750', 'Craniossinostose', 'Q75.0 Craniossinostose'),
  ('Q751', 'Disostose craniofacial', 'Q75.1 Disostose craniofacial'),
  ('Q752', 'Hipertelorismo', 'Q75.2 Hipertelorismo'),
  ('Q753', 'Macrocefalia', 'Q75.3 Macrocefalia'),
  ('Q754', 'Disostose mandíbulo-facial', 'Q75.4 Disostose mandibulo-facial'),
  ('Q755', 'Disostose óculo-mandibular', 'Q75.5 Disostose oculo-mandibular'),
  ('Q758', 'Outras malformações congênitas especificadas dos ossos do crânio e da face', 'Q75.8 Outr malform congen espec ossos cranio face'),
  ('Q759', 'Malformação congênita não especificada dos ossos do crânio e da face', 'Q75.9 Malform congen NE dos ossos cranio e face'),
  ('Q76', 'Malformações congênitas da coluna vertebral e dos ossos do tórax', 'Q76 Malform congen coluna vertebral ossos torax'),
  ('Q760', 'Espinha bífida oculta', 'Q76.0 Espinha bifida oculta'),
  ('Q761', 'Síndrome de Klippel-Feil', 'Q76.1 Sindr de Klippel-Feil'),
  ('Q762', 'Espondilolistese congênita', 'Q76.2 Espondilolistese congen'),
  ('Q763', 'Escoliose congênita devida à malformação óssea congênita', 'Q76.3 Escoliose congen dev malform ossea congen'),
  ('Q764', 'Outras malformações congênitas da coluna vertebral não-associadas com escoliose', 'Q76.4 Out malf cong coluna vert n-assoc escoliose'),
  ('Q765', 'Costela cervical', 'Q76.5 Costela cervical'),
  ('Q766', 'Outras malformações congênitas das costelas', 'Q76.6 Outr malformacoes congen das costelas'),
  ('Q767', 'Malformação congênita do esterno', 'Q76.7 Malformacao congen do esterno'),
  ('Q768', 'Outras malformações congênitas dos ossos do tórax', 'Q76.8 Outr malformacoes congen dos ossos do torax'),
  ('Q769', 'Malformação congênita não especificada dos ossos do tórax', 'Q76.9 Malformacao congen NE dos ossos do torax'),
  ('Q77', 'Osteocondrodisplasia com anomalias de crescimento dos ossos longos e da coluna vertebral', 'Q77 Osteocondr c/anom cresc ossos long col vert'),
  ('Q770', 'Acondrogenesia', 'Q77.0 Acondrogenesia'),
  ('Q771', 'Nanismo tanatofórico', 'Q77.1 Nanismo tanatoforico'),
  ('Q772', 'Síndrome das costelas curtas', 'Q77.2 Sindr das costelas curtas'),
  ('Q773', 'Condrodisplasia puntacta', 'Q77.3 Condrodisplasia puntacta'),
  ('Q774', 'Acondroplasia', 'Q77.4 Acondroplasia'),
  ('Q775', 'Displasia diastrófica', 'Q77.5 Displasia diastrofica'),
  ('Q776', 'Displasia condroectodérmica', 'Q77.6 Displasia condroectodermica'),
  ('Q777', 'Displasia espondiloepifisária', 'Q77.7 Displasia espondiloepifisaria'),
  ('Q778', 'Outras osteocondrodisplasias com anomalias do crescimento dos ossos longos e da coluna vertebral', 'Q77.8 Out osteocon c/anom cresc osso long col vert'),
  ('Q779', 'Osteocondrodisplasia não especificada com anomalias do crescimento dos ossos longos e da coluna vertebral', 'Q77.9 Osteocond NE c/anom cresc osso long col vert'),
  ('Q78', 'Outras osteocondrodisplasias', 'Q78 Outr osteocondrodisplasias'),
  ('Q780', 'Osteogênese imperfeita', 'Q78.0 Osteogenese imperfeita'),
  ('Q781', 'Displasia poliostótica fibrosa', 'Q78.1 Displasia poliostotica fibrosa'),
  ('Q782', 'Osteopetrose', 'Q78.2 Osteopetrose'),
  ('Q783', 'Displasia diafisária progressiva', 'Q78.3 Displasia diafisaria progressiva'),
  ('Q784', 'Encondromatose', 'Q78.4 Encondromatose'),
  ('Q785', 'Displasia metafisária', 'Q78.5 Displasia metafisaria'),
  ('Q786', 'Exostoses congênitas múltiplas', 'Q78.6 Exostoses congen mult'),
  ('Q788', 'Outras osteocondrodisplasias especificadas', 'Q78.8 Outr osteocondrodisplasias espec'),
  ('Q789', 'Osteocondrodisplasia não especificada', 'Q78.9 Osteocondrodisplasia NE'),
  ('Q79', 'Malformações congênitas do sistema osteomuscular não classificadas em outra parte', 'Q79 Malformacoes congen sist osteomuscular NCOP'),
  ('Q790', 'Hérnia diafragmática congênita', 'Q79.0 Hernia diafragmatica congen'),
  ('Q791', 'Outras malformações congênitas do diafragma', 'Q79.1 Outr malformacoes congen do diafragma'),
  ('Q792', 'Exonfalia', 'Q79.2 Exonfalia'),
  ('Q793', 'Gastrosquise', 'Q79.3 Gastrosquise'),
  ('Q794', 'Síndrome do abdome em ameixa seca (prune belly syndrome)', 'Q79.4 Sindr do abdome em ameixa seca'),
  ('Q795', 'Outras malformações congênitas da parede abdominal', 'Q79.5 Outr malformacoes congen da parede abdominal'),
  ('Q796', 'Síndrome de Ehlers-Danlos', 'Q79.6 Sindr de Ehlers-Danlos'),
  ('Q798', 'Outras malformações congênitas do sistema osteomuscular', 'Q79.8 Outr malformacoes congen sist osteomuscular'),
  ('Q799', 'Malformação congênita não especificada do sistema osteomuscular', 'Q79.9 Malformacao congen NE do sist osteomuscular'),
  ('Q80', 'Ictiose congênita', 'Q80 Ictiose congen'),
  ('Q800', 'Ictiose vulgar', 'Q80.0 Ictiose vulgar'),
  ('Q801', 'Ictiose ligada ao cromossomo X', 'Q80.1 Ictiose ligada ao cromossomo X'),
  ('Q802', 'Ictiose lamelar', 'Q80.2 Ictiose lamelar'),
  ('Q803', 'Eritrodermia ictiosiforme bulhosa congênita', 'Q80.3 Eritrodermia ictiosiforme bulhosa congen'),
  ('Q804', 'Feto arlequim', 'Q80.4 Feto arlequim'),
  ('Q808', 'Outras ictioses congênitas', 'Q80.8 Outr ictioses congen'),
  ('Q809', 'Ictiose congênita não especificada', 'Q80.9 Ictiose congen NE'),
  ('Q81', 'Epidermólise bolhosa', 'Q81 Epidermolise bolhosa'),
  ('Q810', 'Epidermólise bolhosa simples', 'Q81.0 Epidermolise bolhosa simples'),
  ('Q811', 'Epidermólise bolhosa letal', 'Q81.1 Epidermolise bolhosa letal'),
  ('Q812', 'Epidermólise bolhosa distrófica', 'Q81.2 Epidermolise bolhosa distrofica'),
  ('Q818', 'Outras epidermólises bolhosas', 'Q81.8 Outr epidermolises bolhosas'),
  ('Q819', 'Epidermólise bolhosa não especificada', 'Q81.9 Epidermolise bolhosa NE'),
  ('Q82', 'Outras malformações congênitas da pele', 'Q82 Outr malformacoes congen da pele'),
  ('Q820', 'Linfedema hereditário', 'Q82.0 Linfedema hereditario'),
  ('Q821', 'Xeroderma pigmentoso', 'Q82.1 Xeroderma pigmentoso'),
  ('Q822', 'Mastocitose', 'Q82.2 Mastocitose'),
  ('Q823', 'Incontinentia pigmenti', 'Q82.3 Incontinentia pigmenti'),
  ('Q824', 'Displasia ectodérmica (anidrótica)', 'Q82.4 Displasia ectodermica'),
  ('Q825', 'Nevo não-neoplásico congênito', 'Q82.5 Nevo nao-neoplasico congen'),
  ('Q828', 'Outras malformações congênitas especificadas da pele', 'Q82.8 Outr malformacoes congen espec da pele'),
  ('Q829', 'Malformação congênita não especificada da pele', 'Q82.9 Malformacao congen NE da pele'),
  ('Q83', 'Malformações congênitas da mama', 'Q83 Malformacoes congen da mama'),
  ('Q830', 'Ausência congênita da mama com ausência do mamilo', 'Q83.0 Ausencia congen da mama c/ausencia do mamilo'),
  ('Q831', 'Mama supranumerária', 'Q83.1 Mama supranumeraria'),
  ('Q832', 'Ausência de mamilo', 'Q83.2 Ausencia de mamilo'),
  ('Q833', 'Mamilo acessório', 'Q83.3 Mamilo acessorio'),
  ('Q838', 'Outras malformações congênitas da mama', 'Q83.8 Outr malformacoes congen da mama'),
  ('Q839', 'Malformação congênita não especificada da mama', 'Q83.9 Malformacao congen NE da mama'),
  ('Q84', 'Outras malformações congênitas do tegumento', 'Q84 Outr malformacoes congen do tegumento'),
  ('Q840', 'Alopécia congênita', 'Q84.0 Alopecia congen'),
  ('Q841', 'Alterações morfológicas congênitas dos cabelos não classificadas em outra parte', 'Q84.1 Alteracoes morfologicas congen cabelos NCOP'),
  ('Q842', 'Outras malformações congênitas dos cabelos', 'Q84.2 Outr malformacoes congen dos cabelos'),
  ('Q843', 'Anoníquia', 'Q84.3 Anoniquia'),
  ('Q844', 'Leuconíquia congênita', 'Q84.4 Leuconiquia congen'),
  ('Q845', 'Hipertrofia e alargamento das unhas', 'Q84.5 Hipertrofia e alargamento das unhas'),
  ('Q846', 'Outras malformações congênitas das unhas', 'Q84.6 Outr malformacoes congen das unhas'),
  ('Q848', 'Outras malformações congênitas especificadas do tegumento', 'Q84.8 Outr malformacoes congen espec do tegumento'),
  ('Q849', 'Malformação congênita não especificada do tegumento', 'Q84.9 Malformacao congen NE do tegumento'),
  ('Q85', 'Facomatoses não classificadas em outra parte', 'Q85 Facomatoses NCOP'),
  ('Q850', 'Neurofibromatose (não-maligna)', 'Q85.0 Neurofibromatose'),
  ('Q851', 'Esclerose tuberosa', 'Q85.1 Esclerose tuberosa'),
  ('Q858', 'Outras facomatoses não classificadas em outra parte', 'Q85.8 Outr facomatoses NCOP'),
  ('Q859', 'Facomatose não especificada', 'Q85.9 Facomatose NE'),
  ('Q86', 'Síndromes com malformações congênitas devidas a causas exógenas conhecidas, não classificadas em outra parte', 'Q86 Sindr c/malf cong dev causas exog conh NCOP'),
  ('Q860', 'Síndrome fetal alcoólico (dismórfico)', 'Q86.0 Sindr fetal alcoolico'),
  ('Q861', 'Síndrome fetal devida à hidantoína', 'Q86.1 Sindr fetal dev hidantoina'),
  ('Q862', 'Dismorfismo devido ao Warfarin', 'Q86.2 Dismorfismo dev Warfarin'),
  ('Q868', 'Outras síndromes com malformações congênitas devidas a causas exógenas conhecidas', 'Q86.8 Outr sindr c/malf cong dev causas exog conh'),
  ('Q87', 'Outras síndromes com malformações congênitas que acometem múltiplos sistemas', 'Q87 Outr sindr c/malform cong q acomet mult sist'),
  ('Q870', 'Síndromes com malformações congênitas afetando predominantemente o aspecto da face', 'Q87.0 Sindr c/malf cong afet predom aspecto face'),
  ('Q871', 'Síndromes com malformações congênitas associadas predominantemente com nanismo', 'Q87.1 Sindr c/malform congen assoc predom nanismo'),
  ('Q872', 'Síndromes com malformações congênitas afetando predominantemente os membros', 'Q87.2 Sindr c/malform congen afetando predom membr'),
  ('Q873', 'Síndromes com malformações congênitas com hipercrescimento precoce', 'Q87.3 Sindr c/malform congen c/hipercresc precoce'),
  ('Q874', 'Síndrome de Marfan', 'Q87.4 Sindr de Marfan'),
  ('Q875', 'Outras síndromes com malformações congênitas com outras alterações do esqueleto', 'Q87.5 Outr sindr c/malf cong c/outr alt esqueleto'),
  ('Q878', 'Outras síndromes com malformações congênitas especificadas, não classificadas em outra parte', 'Q87.8 Outr sindr c/malformacoes congen espec NCOP'),
  ('Q89', 'Outras malformações congênitas não classificadas em outra parte', 'Q89 Outr malformacoes congen NCOP'),
  ('Q890', 'Malformações congênitas do baço', 'Q89.0 Malformacoes congen do baco'),
  ('Q891', 'Malformações congênitas das supra-renais', 'Q89.1 Malformacoes congen das supra-renais'),
  ('Q892', 'Malformações congênitas de outras glândulas endócrinas', 'Q89.2 Malformacoes congen de outr gland endocrinas'),
  ('Q893', 'Situs inversus', 'Q89.3 Situs inversus'),
  ('Q894', 'Reunião de gêmeos', 'Q89.4 Reuniao de gemeos'),
  ('Q897', 'Malformações congênitas múltiplas, não classificadas em outra parte', 'Q89.7 Malformacoes congen mult NCOP'),
  ('Q898', 'Outras malformações congênitas especificadas', 'Q89.8 Outr malformacoes congen espec'),
  ('Q899', 'Malformações congênitas não especificadas', 'Q89.9 Malformacoes congen NE'),
  ('Q90', 'Síndrome de Down', 'Q90 Sindr de Down'),
  ('Q900', 'Trissomia 21, não-disjunção meiótica', 'Q90.0 Trissomia 21 nao-disjuncao meiotica'),
  ('Q901', 'Trissomia 21, mosaicismo (não-disjunção mitótica)', 'Q90.1 Trissomia 21 mosaicismo'),
  ('Q902', 'Trissomia 21, translocação', 'Q90.2 Trissomia 21 translocacao'),
  ('Q909', 'Síndrome de Down não especificada', 'Q90.9 Sindr de Down NE'),
  ('Q91', 'Síndrome de Edwards e síndrome de Patau', 'Q91 Sindr de Edwards e sindr de Patau'),
  ('Q910', 'Trissomia 18, não-disjunção meiótica', 'Q91.0 Trissomia 18 nao-disjuncao meiotica'),
  ('Q911', 'Trissomia 18, mosaicismo cromossômico (não-disjunção mitótica)', 'Q91.1 Trissomia 18 mosaicismo cromossomico'),
  ('Q912', 'Trissomia 18, translocação', 'Q91.2 Trissomia 18 translocacao'),
  ('Q913', 'Síndrome de Edwards não especificada', 'Q91.3 Sindr de Edwards NE'),
  ('Q914', 'Trissomia 13, não-disjunção meiótica', 'Q91.4 Trissomia 13 nao-disjuncao meiotica'),
  ('Q915', 'Trissomia 13, mosaicismo cromossômico (não-disjunção mitótica)', 'Q91.5 Trissomia 13 mosaicismo cromossomico'),
  ('Q916', 'Trissomia 13, translocação', 'Q91.6 Trissomia 13 translocacao'),
  ('Q917', 'Síndrome de Patau não especificada', 'Q91.7 Sindr de Patau NE'),
  ('Q92', 'Outras trissomias e trissomias parciais dos autossomos, não classificadas em outra parte', 'Q92 Outr trissomias e trissom parc autoss NCOP'),
  ('Q920', 'Trissomia de um cromossomo inteiro, não-disjunção meiótica', 'Q92.0 Trissomia cromoss inteiro n-disjuncao meiot'),
  ('Q921', 'Trissomia de um cromossomo inteiro, mosaicismo cromossômico (não-disjunção mitótica)', 'Q92.1 Trissomia cromoss inteiro mosaicismo cromoss'),
  ('Q922', 'Trissomia parcial major', 'Q92.2 Trissomia parcial major'),
  ('Q923', 'Trissomia parcial minor', 'Q92.3 Trissomia parcial minor'),
  ('Q924', 'Duplicações vistas somente na prometáfase', 'Q92.4 Duplicacoes vistas somente na prometafase'),
  ('Q925', 'Duplicação com outros rearranjos complexos', 'Q92.5 Duplicacao c/outr rearranjos complexos'),
  ('Q926', 'Cromossomos marcadores suplementares', 'Q92.6 Cromossomos marcadores suplementares'),
  ('Q927', 'Triploidia e poliploidia', 'Q92.7 Triploidia e poliploidia'),
  ('Q928', 'Outras trissomias especificadas e trissomias parciais dos autossomos', 'Q92.8 Outr trissomias espec e trissom parc autoss'),
  ('Q929', 'Trissomia e trissomia parcial não especificada dos autossomos', 'Q92.9 Trissomia e trissomia parcial NE autossomos'),
  ('Q93', 'Monossomias e deleções dos autossomos, não classificadas em outra parte', 'Q93 Monossomias e delecoes dos autossomos NCOP'),
  ('Q930', 'Monossomia de cromossomo inteiro, não-disjunção meiótica', 'Q93.0 Monossomia cromoss inteiro n-disjuncao meiot'),
  ('Q931', 'Monossomia de cromossomo inteiro, mosaicismo cromossômico (não-disjunção mitótica)', 'Q93.1 Monossomia cromoss inteiro mosaicism cromoss'),
  ('Q932', 'Cromossomo substituído por anel ou dicêntrico', 'Q93.2 Cromossomo substituido p/anel ou dicentrico'),
  ('Q933', 'Deleção do braço curto do cromossomo 4', 'Q93.3 Delecao do braco curto do cromossomo 4'),
  ('Q934', 'Deleção do braço curto do cromossomo 5', 'Q93.4 Delecao do braco curto do cromossomo 5'),
  ('Q935', 'Outras deleções parciais de cromossomo', 'Q93.5 Outr delecoes parciais de cromossomo'),
  ('Q936', 'Deleções vistas somente na prometáfase', 'Q93.6 Delecoes vistas somente na prometafase'),
  ('Q937', 'Deleções com outros rearranjos complexos', 'Q93.7 Delecoes c/outr rearranjos complexos'),
  ('Q938', 'Outras deleções dos autossomos', 'Q93.8 Outr delecoes dos autossomos'),
  ('Q939', 'Deleções não especificadas dos autossomos', 'Q93.9 Delecoes NE dos autossomos'),
  ('Q95', 'Rearranjos equilibrados e marcadores estruturais, não classificados em outra parte', 'Q95 Rearranjos equilibr e marcadores estrut NCOP'),
  ('Q950', 'Translocação ou inserção equilibrada em sujeito normal', 'Q95.0 Transloc ou insercao equilibr sujeito norm'),
  ('Q951', 'Inversão cromossômica em sujeito normal', 'Q95.1 Inversao cromossomica em sujeito normal'),
  ('Q952', 'Rearranjo autossômico equilibrado em sujeito anormal', 'Q95.2 Rearranjo autossomico equilibr sujeito anorm'),
  ('Q953', 'Rearranjo sexual/autossômico equilibrado em sujeito anormal', 'Q95.3 Rearranjo sexual/autoss equilibr suj anorm'),
  ('Q954', 'Sujeito com marcador de heterocromatina', 'Q95.4 Sujeito c/marcador de heterocromatina'),
  ('Q955', 'Sujeito com sítio autossômico frágil', 'Q95.5 Sujeito c/sitio autossomico fragil'),
  ('Q958', 'Outros rearranjos e marcadores equilibrados', 'Q95.8 Outr rearranjos e marcadores equilibrados'),
  ('Q959', 'Rearranjos e marcadores equilibrados não especificados', 'Q95.9 Rearranjos e marcadores equilibrados NE'),
  ('Q96', 'Síndrome de Turner', 'Q96 Sindr de Turner'),
  ('Q960', 'Cariótipo 45, X', 'Q96.0 Cariotipo 45 X'),
  ('Q961', 'Cariótipo 46, X iso (Xq)', 'Q96.1 Cariotipo 46 X isso'),
  ('Q962', 'Cariótipo 46, X com cromossomo sexual anormal, salvo iso (Xq)', 'Q96.2 Cariotipo 46 X cromoss sex anorm salvo isso'),
  ('Q963', 'Mosaicismo cromossômico, 45, X/46, XX ou XY', 'Q96.3 Mosaicismo cromossomico 45 X/46 XX ou XY'),
  ('Q964', 'Mosaicismo cromossômico, 45, X/outra(s) linhagens celular(es) com cromossomo sexual anormal', 'Q96.4 Mosaic crom 45 X/out linh cel crom sex anorm'),
  ('Q968', 'Outras variantes da síndrome de Turner', 'Q96.8 Outr variantes da sindr de Turner'),
  ('Q969', 'Síndrome de Turner não especificada', 'Q96.9 Sindr de Turner NE'),
  ('Q97', 'Outras anomalias dos cromossomos sexuais, fenótipo feminino, não classificadas em outra parte', 'Q97 Outr anom cromoss sexuais fenotipo fem NCOP'),
  ('Q970', 'Cariótipo 47, XXX', 'Q97.0 Cariotipo 47 XXX'),
  ('Q971', 'Mulher com mais de três cromossomos X', 'Q97.1 Mulher c/mais de tres cromossomos X'),
  ('Q972', 'Mosaicismo cromossômico, linhagens com diversos números de cromossomos X', 'Q97.2 Mosaicismo cromoss linh c/div num cromoss X'),
  ('Q973', 'Mulher com cariótipo 46, XY', 'Q97.3 Mulher c/cariotipo 46 XY'),
  ('Q978', 'Outras anomalias especificadas dos cromossomos sexuais, fenótipo feminino', 'Q97.8 Outr anom espec cromoss sex fenotipo fem'),
  ('Q979', 'Anomalias não especificadas dos cromossomos sexuais, fenótipo feminino', 'Q97.9 Anomalias NE cromoss sexuais fenotipo femin'),
  ('Q98', 'Outras anomalias dos cromossomos sexuais, fenótipo masculino, não classificadas em outra parte', 'Q98 Outr anom cromoss sexuais fenotipo masc NCOP'),
  ('Q980', 'Síndrome de Klinefelter, cariótipo 47, XXY', 'Q98.0 Sindr de Klinefelter cariotipo 47 XXY'),
  ('Q981', 'Síndrome de Klinefelter, homem com mais de dois cromossomos X', 'Q98.1 Sindr Klinefelter hom c/mais dois cromoss X'),
  ('Q982', 'Síndrome de Klinefelter, homem com cariótipo 46, XX', 'Q98.2 Sindr de Klinefelter homem c/cariotipo 46 XX'),
  ('Q983', 'Outro homem com cariótipo 46, XX', 'Q98.3 Outr homem c/cariotipo 46 XX'),
  ('Q984', 'Síndrome de Klinefelter não especificada', 'Q98.4 Sindr de Klinefelter NE'),
  ('Q985', 'Cariótipo 47, XYY', 'Q98.5 Cariotipo 47 XYY'),
  ('Q986', 'Homem com cromossomos sexuais de estrutura anormal', 'Q98.6 Homem c/cromossomos sexuais estrut anormal'),
  ('Q987', 'Homem com mosaicismo dos cromossomos sexuais', 'Q98.7 Homem c/mosaicismo dos cromossomos sexuais'),
  ('Q988', 'Outras anomalias especificadas dos cromossomos sexuais, fenótipo masculino', 'Q98.8 Outr anom espec cromoss sex fenotipo masc'),
  ('Q989', 'Anomalias não especificadas dos cromossomos sexuais, fenótipo masculino', 'Q98.9 Anomalias NE cromoss sexuais fenotipo masc'),
  ('Q99', 'Outras anomalias dos cromossomos, não classificadas em outra parte', 'Q99 Outr anomalias dos cromossomos NCOP'),
  ('Q990', 'Quimera 46, XX/46, XY', 'Q99.0 Quimera 46 XX/46 XY'),
  ('Q991', 'Hermafrodite verdadeiro 46, XX', 'Q99.1 Hermafrodite verdadeiro 46 XX'),
  ('Q992', 'Cromossomo X frágil', 'Q99.2 Cromossomo X fragil'),
  ('Q998', 'Outras anomalias cromossômicas especificadas', 'Q99.8 Outr anomalias cromossomicas espec'),
  ('Q999', 'Anomalia cromossômica não especificada', 'Q99.9 Anomalia cromossomica NE');
