INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('S00', 'Traumatismo superficial da cabeça', 'S00 Traum superf da cabeca'),
  ('S000', 'Traumatismo superficial do couro cabeludo', 'S00.0 Traum superf do couro cabeludo'),
  ('S001', 'Contusão da pálpebra e da região periocular', 'S00.1 Contusao da palpebra e da regiao periocular'),
  ('S002', 'Outros traumatismos superficiais da pálpebra e da região periocular', 'S00.2 Outr traum superf palpebra regiao periocular'),
  ('S003', 'Traumatismo superficial do nariz', 'S00.3 Traum superf do nariz'),
  ('S004', 'Traumatismo superficial do ouvido', 'S00.4 Traum superf do ouvido'),
  ('S005', 'Traumatismo superficial dos lábios e da cavidade oral', 'S00.5 Traum superf dos labios e da cavidade oral'),
  ('S007', 'Traumatismos superficiais múltiplos da cabeça', 'S00.7 Traum superf mult da cabeca'),
  ('S008', 'Traumatismo superficial de outras partes da cabeça', 'S00.8 Traum superf de outr partes da cabeca'),
  ('S009', 'Traumatismo superficial da cabeça, parte não especificada', 'S00.9 Traum superf da cabeca parte NE'),
  ('S01', 'Ferimento da cabeça', 'S01 Ferim da cabeca'),
  ('S010', 'Ferimento do couro cabeludo', 'S01.0 Ferim do couro cabeludo'),
  ('S011', 'Ferimento da pálpebra e da região periocular', 'S01.1 Ferim da palpebra e da regiao periocular'),
  ('S012', 'Ferimento do nariz', 'S01.2 Ferim do nariz'),
  ('S013', 'Ferimento do ouvido', 'S01.3 Ferim do ouvido'),
  ('S014', 'Ferimento da bochecha e região têmporo-mandibular', 'S01.4 Ferim bochecha e regiao temporo-mandibular'),
  ('S015', 'Ferimento do lábio e da cavidade oral', 'S01.5 Ferim do labio e da cavidade oral'),
  ('S017', 'Ferimentos múltiplos da cabeça', 'S01.7 Ferim mult da cabeca'),
  ('S018', 'Ferimento na cabeça, de outras localizações', 'S01.8 Ferim na cabeca de outr localiz'),
  ('S019', 'Ferimento na cabeça, parte não especificada', 'S01.9 Ferim na cabeca parte NE'),
  ('S02', 'Fratura do crânio e dos ossos da face', 'S02 Frat do cranio e dos ossos da face'),
  ('S020', 'Fratura da abóbada do crânio', 'S02.0 Frat da abobada do cranio'),
  ('S021', 'Fratura da base do crânio', 'S02.1 Frat da base do cranio'),
  ('S022', 'Fratura dos ossos nasais', 'S02.2 Frat dos ossos nasais'),
  ('S023', 'Fratura do assoalho orbital', 'S02.3 Frat do assoalho orbital'),
  ('S024', 'Fratura dos ossos malares e maxilares', 'S02.4 Frat dos ossos malares e maxilares'),
  ('S025', 'Fratura de dentes', 'S02.5 Frat de dentes'),
  ('S026', 'Fratura de mandíbula', 'S02.6 Frat de mandibula'),
  ('S027', 'Fraturas múltiplas envolvendo os ossos do crânio e da face', 'S02.7 Frat mult envolv ossos do cranio e face'),
  ('S028', 'Outras fraturas do crânio e dos ossos da face', 'S02.8 Outr frat do cranio e dos ossos da face'),
  ('S029', 'Fratura do crânio ou dos ossos da face, parte não especificada', 'S02.9 Frat do cranio ou dos ossos da face parte NE'),
  ('S03', 'Luxação, entorse ou distensão das articulações e dos ligamentos da cabeça', 'S03 Luxacao entorse distensao artic lig cabeca'),
  ('S030', 'Luxação do maxilar', 'S03.0 Luxacao do maxilar'),
  ('S031', 'Luxação da cartilagem do septo nasal', 'S03.1 Luxacao da cartilagem do septo nasal'),
  ('S032', 'Luxação dentária', 'S03.2 Luxacao dentaria'),
  ('S033', 'Luxação de outras partes da cabeça e das não especificadas', 'S03.3 Luxacao de outr partes da cabeca e das NE'),
  ('S034', 'Entorse e distensão do maxilar', 'S03.4 Entorse e distensao do maxilar'),
  ('S035', 'Entorse e distensão da articulações e dos ligamentos de outras localizações e de localizações não especificadas da cabeça', 'S03.5 Entorse distens artic lig outr loc NE cabeca'),
  ('S04', 'Traumatismo dos nervos cranianos', 'S04 Traum dos nervos cranianos'),
  ('S040', 'Traumatismo do nervo e das vias ópticas', 'S04.0 Traum do nervo e das vias opticas'),
  ('S041', 'Traumatismo do nervo oculomotor', 'S04.1 Traum do nervo oculomotor'),
  ('S042', 'Traumatismo do nervo troclear', 'S04.2 Traum do nervo troclear'),
  ('S043', 'Traumatismo do nervo trigêmeo', 'S04.3 Traum do nervo trigemeo'),
  ('S044', 'Traumatismo do nervo abducente', 'S04.4 Traum do nervo abducente'),
  ('S045', 'Traumatismo do nervo facial', 'S04.5 Traum do nervo facial'),
  ('S046', 'Traumatismo do nervo acústico', 'S04.6 Traum do nervo acustico'),
  ('S047', 'Traumatismo do nervo acessório', 'S04.7 Traum do nervo acessorio'),
  ('S048', 'Traumatismo de outros nervos cranianos', 'S04.8 Traum de outr nervos cranianos'),
  ('S049', 'Traumatismo de nervo craniano não especificado', 'S04.9 Traum de nervo craniano NE'),
  ('S05', 'Traumatismo do olho e da órbita ocular', 'S05 Traum do olho e da orbita ocular'),
  ('S050', 'Traumatismo da conjuntiva e abrasão da córnea sem menção de corpo estranho', 'S05.0 Traum conj abrasao cornea s/menc corp estran'),
  ('S051', 'Contusão do globo ocular e dos tecidos da órbita', 'S05.1 Contusao do globo ocular e dos tec da orbita'),
  ('S052', 'Laceração e ruptura ocular com prolapso ou perda de tecido intra-ocular', 'S05.2 Lacer rupt ocular c/prol perd tec intra-ocul'),
  ('S053', 'Laceração ocular sem prolapso ou perda de tecido intra-ocular', 'S05.3 Lacer ocular s/prolap perda tec intra-ocular'),
  ('S054', 'Ferimento penetrante da órbita com ou sem corpo estranho', 'S05.4 Ferim penetrante orbita c/ s/corpo estranho'),
  ('S055', 'Ferimento penetrante do globo ocular com corpo estranho', 'S05.5 Ferim penetr globo ocular c/corpo estranho'),
  ('S056', 'Ferimento penetrante do globo ocular sem corpo estranho', 'S05.6 Ferim penetr globo ocular s/corpo estranho'),
  ('S057', 'Avulsão do olho', 'S05.7 Avulsao do olho'),
  ('S058', 'Outros traumatismos do olho e da órbita', 'S05.8 Outr traum do olho e da orbita'),
  ('S059', 'Traumatismo do olho e da órbita, não especificado', 'S05.9 Traum do olho e da orbita NE'),
  ('S06', 'Traumatismo intracraniano', 'S06 Traum intracraniano'),
  ('S060', 'Concussão cerebral', 'S06.0 Concussao cerebral'),
  ('S061', 'Edema cerebral traumático', 'S06.1 Edema cerebral traum'),
  ('S062', 'Traumatismo cerebral difuso', 'S06.2 Traum cerebral difuso'),
  ('S063', 'Traumatismo cerebral focal', 'S06.3 Traum cerebral focal'),
  ('S064', 'Hemorragia epidural', 'S06.4 Hemorragia epidural'),
  ('S065', 'Hemorragia subdural devida a traumatismo', 'S06.5 Hemorragia subdural dev traum'),
  ('S066', 'Hemorragia subaracnóide devida a traumatismo', 'S06.6 Hemorragia subaracnoide dev traum'),
  ('S067', 'Traumatismo intracraniano com coma prolongado', 'S06.7 Traum intracraniano c/coma prolongado'),
  ('S068', 'Outros traumatismos intracranianos', 'S06.8 Outr traum intracranianos'),
  ('S069', 'Traumatismo intracraniano, não especificado', 'S06.9 Traum intracraniano NE'),
  ('S07', 'Lesões por esmagamento da cabeça', 'S07 Lesoes p/esmag da cabeca'),
  ('S070', 'Lesão por esmagamento da face', 'S07.0 Lesao p/esmag da face'),
  ('S071', 'Lesão por esmagamento do crânio', 'S07.1 Lesao p/esmag do cranio'),
  ('S078', 'Lesão por esmagamento de outras partes da cabeça', 'S07.8 Lesao p/esmag de outr partes da cabeca'),
  ('S079', 'Lesão por esmagamento da cabeça, parte não especificada', 'S07.9 Lesao p/esmag da cabeca parte NE'),
  ('S08', 'Amputação traumática de parte da cabeça', 'S08 Amput traum de parte da cabeca'),
  ('S080', 'Avulsão do couro cabeludo', 'S08.0 Avulsao do couro cabeludo'),
  ('S081', 'Amputação traumática da orelha', 'S08.1 Amput traum da orelha'),
  ('S088', 'Amputação traumática de outras partes da cabeça', 'S08.8 Amput traum de outr partes da cabeca'),
  ('S089', 'Amputação traumática de parte não especificada da cabeça', 'S08.9 Amput traum de parte NE da cabeca'),
  ('S09', 'Outros traumatismos da cabeça e os não especificados', 'S09 Outr traum da cabeca e os NE'),
  ('S090', 'Traumatismo dos vasos sangüíneos da cabeça não classificados em outra parte', 'S09.0 Traum dos vasos sanguineos da cabeca NCOP'),
  ('S091', 'Traumatismo dos músculos e dos tendões da cabeça', 'S09.1 Traum dos musculos e dos tendoes da cabeca'),
  ('S092', 'Ruptura traumática do tímpano', 'S09.2 Ruptura traum do timpano'),
  ('S097', 'Traumatismos múltiplos da cabeça', 'S09.7 Traum mult da cabeca'),
  ('S098', 'Outros traumatismos especificados da cabeça', 'S09.8 Outr traum espec da cabeca'),
  ('S099', 'Traumatismo não especificado da cabeça', 'S09.9 Traum NE da cabeca'),
  ('S10', 'Traumatismo superficial do pescoço', 'S10 Traum superf do pescoco'),
  ('S100', 'Contusão da garganta', 'S10.0 Contusao da garganta'),
  ('S101', 'Outros traumatismos superficiais da garganta e os não especificados', 'S10.1 Outr traum superf da garganta e os NE'),
  ('S107', 'Traumatismos superficiais múltiplos do pescoço', 'S10.7 Traum superf mult do pescoco'),
  ('S108', 'Traumatismo superficial de outras localizações do pescoço', 'S10.8 Traum superf de outr localiz do pescoco'),
  ('S109', 'Traumatismo superficial do pescoço, parte não especificada', 'S10.9 Traum superf do pescoco parte NE'),
  ('S11', 'Ferimento do pescoço', 'S11 Ferim do pescoco'),
  ('S110', 'Ferimento envolvendo a laringe e a traquéia', 'S11.0 Ferim envolv a laringe e a traqueia'),
  ('S111', 'Ferimento da glândula tireóide', 'S11.1 Ferim da gland tireoide'),
  ('S112', 'Ferimento envolvendo a faringe e o esôfago cervical', 'S11.2 Ferim envolv faringe esofago cervical'),
  ('S117', 'Ferimentos múltiplos do pescoço', 'S11.7 Ferim mult do pescoco'),
  ('S118', 'Ferimentos de outras partes do pescoço', 'S11.8 Ferim de outr partes do pescoco'),
  ('S119', 'Ferimentos do pescoço, parte não especificada', 'S11.9 Ferim do pescoco parte NE'),
  ('S12', 'Fratura do pescoço', 'S12 Frat do pescoco'),
  ('S120', 'Fratura da primeira vértebra cervical', 'S12.0 Frat da primeira vertebra cervical'),
  ('S121', 'Fratura da segunda vértebra cervical', 'S12.1 Frat da segunda vertebra cervical'),
  ('S122', 'Fratura de outras vértebras cervicais especificadas', 'S12.2 Frat de outr vertebras cervicais espec'),
  ('S127', 'Fraturas múltiplas da coluna cervical', 'S12.7 Frat mult da coluna cervical'),
  ('S128', 'Fratura de outras partes do pescoço', 'S12.8 Frat de outr partes do pescoco'),
  ('S129', 'Fratura do pescoço, parte não especificada', 'S12.9 Frat do pescoco parte NE'),
  ('S13', 'Luxação, entorse ou distensão das articulações e dos ligamentos do pescoço', 'S13 Luxacao entorse distensao artic lig pescoco'),
  ('S130', 'Ruptura traumática de disco intervertebral cervical', 'S13.0 Ruptura traum disco intervertebral cervical'),
  ('S131', 'Luxação de vértebra cervical', 'S13.1 Luxacao de vertebra cervical'),
  ('S132', 'Luxação de outras partes do pescoço e das não especificadas', 'S13.2 Luxacao de outr partes do pescoco e das NE'),
  ('S133', 'Luxações múltiplas do pescoço', 'S13.3 Luxacoes mult do pescoco'),
  ('S134', 'Distensão e entorse da coluna cervical', 'S13.4 Distensao e entorse da coluna cervical'),
  ('S135', 'Distensão e entorse da região tireoidiana', 'S13.5 Distensao e entorse da regiao tireoidiana'),
  ('S136', 'Distensão e entorse de articulações e de ligamentos de outras localizações e das não especificadas do pescoço', 'S13.6 Distens entorse artic lig out loc NE pescoco'),
  ('S14', 'Traumatismo de nervos e da medula espinhal ao nível cervical', 'S14 Traum nervos medula espinhal nivel cervical'),
  ('S140', 'Concussão e edema da medula cervical', 'S14.0 Concussao e edema da medula cervical'),
  ('S141', 'Outros traumatismos e os não especificados da medula cervical', 'S14.1 Outr traum e os NE da medula cervical'),
  ('S142', 'Traumatismo da raiz nervosa da coluna cervical', 'S14.2 Traum da raiz nervosa da coluna cervical'),
  ('S143', 'Traumatismo do plexo braquial', 'S14.3 Traum do plexo braquial'),
  ('S144', 'Traumatismo dos nervos periféricos do pescoço', 'S14.4 Traum dos nervos perifericos do pescoco'),
  ('S145', 'Traumatismo dos nervos simpáticos do pescoço', 'S14.5 Traum dos nervos simpaticos do pescoco'),
  ('S146', 'Traumatismo de outros nervos e dos não especificados do pescoço', 'S14.6 Traum de outr nervos e dos NE do pescoco'),
  ('S15', 'Traumatismo dos vasos sangüíneos ao nível do pescoço', 'S15 Traum dos vasos sanguineos nivel do pescoco'),
  ('S150', 'Traumatismo da artéria carótida', 'S15.0 Traum da arteria carotida'),
  ('S151', 'Traumatismo da artéria vertebral', 'S15.1 Traum da arteria vertebral'),
  ('S152', 'Traumatismo da veia jugular externa', 'S15.2 Traum da veia jugular externa'),
  ('S153', 'Traumatismo da veia jugular interna', 'S15.3 Traum da veia jugular interna'),
  ('S157', 'Traumatismo de múltiplos vasos sangüíneos ao nível do pescoço', 'S15.7 Traum de mult vasos sanguineos nivel pescoco'),
  ('S158', 'Traumatismo de outros vasos sangüíneos ao nível do pescoço', 'S15.8 Traum de outr vasos sanguineos nivel pescoco'),
  ('S159', 'Traumatismo de vasos sangüíneos não especificados ao nível do pescoço', 'S15.9 Traum de vasos sanguineos NE nivel pescoco'),
  ('S16', 'Traumatismo de tendões e de músculos do pescoço', 'S16 Traum de tendoes e de musculos do pescoco'),
  ('S16', 'Traumatismo de tendões e de músculos do pescoço', 'S16 Traum de tendoes e de musculos do pescoco'),
  ('S17', 'Lesões por esmagamento do pescoço', 'S17 Lesoes p/esmag do pescoco'),
  ('S170', 'Lesão por esmagamento da laringe e da traquéia', 'S17.0 Lesao p/esmag da laringe e da traqueia'),
  ('S178', 'Lesão por esmagamento de outras partes do pescoço', 'S17.8 Lesao p/esmag de outr partes pescoco'),
  ('S179', 'Lesão por esmagamento do pescoço, parte não especificada', 'S17.9 Lesao p/esmag do pescoco parte NE'),
  ('S18', 'Amputação traumática ao nível do pescoço', 'S18 Amput traum ao nivel do pescoco'),
  ('S18', 'Amputação traumática ao nível do pescoço', 'S18 Amput traum ao nivel do pescoco'),
  ('S19', 'Outros traumatismos do pescoço e os não especificados', 'S19 Outr traum do pescoco e os NE'),
  ('S197', 'Traumatismos múltiplos do pescoço', 'S19.7 Traum mult do pescoco'),
  ('S198', 'Outros traumatismos especificados do pescoço', 'S19.8 Outr traum espec do pescoco'),
  ('S199', 'Traumatismo não especificado do pescoço', 'S19.9 Traum NE do pescoco'),
  ('S20', 'Traumatismo superficial do tórax', 'S20 Traum superf do torax'),
  ('S200', 'Contusão da mama', 'S20.0 Contusao da mama'),
  ('S201', 'Outros traumatismos superficiais da mama e os não especificados', 'S20.1 Outr traum superf da mama e os NE'),
  ('S202', 'Contusão do tórax', 'S20.2 Contusao do torax'),
  ('S203', 'Outros traumatismos superficiais da parede anterior do tórax', 'S20.3 Outr traum superf da parede anterior torax'),
  ('S204', 'Outros traumatismos superficiais da parede posterior do tórax', 'S20.4 Outr traum superf da parede posterior torax'),
  ('S207', 'Traumatismos superficiais múltiplos do tórax', 'S20.7 Traum superf mult do torax'),
  ('S208', 'Traumatismo superficial de outras partes especificadas do tórax e das não especificadas', 'S20.8 Traum superf de outr partes espec torax e NE'),
  ('S21', 'Ferimento do tórax', 'S21 Ferim do torax'),
  ('S210', 'Ferimento da mama', 'S21.0 Ferim da mama'),
  ('S211', 'Ferimento da parede anterior do tórax', 'S21.1 Ferim da parede anterior do torax'),
  ('S212', 'Ferimento da parede posterior do tórax', 'S21.2 Ferim da parede posterior do torax'),
  ('S217', 'Ferimentos múltiplos da parede torácica', 'S21.7 Ferim mult da parede toracica'),
  ('S218', 'Ferimento de outras partes do tórax', 'S21.8 Ferim de outr partes do torax'),
  ('S219', 'Ferimento do tórax parte não especificada', 'S21.9 Ferim do torax parte NE'),
  ('S22', 'Fratura de costela(s), esterno e coluna torácica', 'S22 Frat de costelas esterno e coluna toracica'),
  ('S220', 'Fratura de vértebra torácica', 'S22.0 Frat de vertebra toracica'),
  ('S221', 'Fraturas múltiplas da coluna torácica', 'S22.1 Frat mult da coluna toracica'),
  ('S222', 'Fratura do esterno', 'S22.2 Frat do esterno'),
  ('S223', 'Fratura de costela', 'S22.3 Frat de costela'),
  ('S224', 'Fraturas múltiplas de costelas', 'S22.4 Frat mult de costelas'),
  ('S225', 'Tórax fundido (oscilante)', 'S22.5 Torax fundido'),
  ('S228', 'Fraturas de outras partes dos ossos do tórax', 'S22.8 Frat de outr partes dos ossos do torax'),
  ('S229', 'Fratura dos ossos do tórax, parte não especificada', 'S22.9 Frat dos ossos do torax parte NE'),
  ('S23', 'Luxação, entorse e distensão de articulações e dos ligamentos do tórax', 'S23 Luxacao entorse distensao artic lig do torax'),
  ('S230', 'Ruptura traumática de disco intervertebral torácico', 'S23.0 Ruptura traum disco intervertebral toracico'),
  ('S231', 'Luxação de vértebra torácica', 'S23.1 Luxacao de vertebra toracica'),
  ('S232', 'Luxação de outras partes do tórax e das não especificadas', 'S23.2 Luxacao de outr partes do torax e das NE'),
  ('S233', 'Entorse e distensão da coluna torácica', 'S23.3 Entorse e distensao da coluna toracica'),
  ('S234', 'Entorse e distensão das costelas e do esterno', 'S23.4 Entorse e distensao das costelas e esterno'),
  ('S235', 'Entorse e distensão de outras partes do tórax e de partes não especificadas', 'S23.5 Entorse distensao outr partes torax e NE'),
  ('S24', 'Traumatismos de nervos e da medula espinhal ao nível do tórax', 'S24 Traum nervos e medula espinhal nivel torax'),
  ('S240', 'Concussão e edema da medula espinhal torácica', 'S24.0 Concussao e edema medula espinhal toracica'),
  ('S241', 'Outros traumatismos da medula espinhal torácica e os não especificados', 'S24.1 Outr traum medula espinhal toracica e os NE'),
  ('S242', 'Traumatismo da raiz de nervo da coluna torácica', 'S24.2 Traum da raiz de nervo da coluna toracica'),
  ('S243', 'Traumatismo de nervos periféricos do tórax', 'S24.3 Traum de nervos perifericos do torax'),
  ('S244', 'Traumatismo de nervos simpáticos do tórax', 'S24.4 Traum de nervos simpaticos do torax'),
  ('S245', 'Traumatismo de outros nervos do tórax', 'S24.5 Traum de outr nervos do torax'),
  ('S246', 'Traumatismo de nervo do tórax não especificado', 'S24.6 Traum de nervo do torax NE'),
  ('S25', 'Traumatismo de vasos sangüíneos do tórax', 'S25 Traum de vasos sanguineos do torax'),
  ('S250', 'Traumatismo da aorta torácica', 'S25.0 Traum da aorta toracica'),
  ('S251', 'Traumatismo da artéria subclávia ou inominada (braquiocefálica)', 'S25.1 Traum da arteria subclavia ou inominada'),
  ('S252', 'Traumatismo da veia cava superior', 'S25.2 Traum da veia cava super'),
  ('S253', 'Traumatismo da veia subclávia ou inominada (braquiocefálica)', 'S25.3 Traum da veia subclavia ou inominada'),
  ('S254', 'Traumatismo de vasos sangüíneos pulmonares', 'S25.4 Traum de vasos sanguineos pulmonares'),
  ('S255', 'Traumatismo de vasos sangüíneos intercostais', 'S25.5 Traum de vasos sanguineos intercostais'),
  ('S257', 'Traumatismo de múltiplos vasos sangüíneos do tórax', 'S25.7 Traum de mult vasos sanguineos do torax'),
  ('S258', 'Traumatismo de outros vasos sangüíneos do tórax', 'S25.8 Traum de outr vasos sanguineos do torax'),
  ('S259', 'Traumatismo de vaso sangüíneo não especificado do tórax', 'S25.9 Traum de vaso sanguineo NE do torax'),
  ('S26', 'Traumatismo do coração', 'S26 Traum do coracao'),
  ('S260', 'Traumatismo do coração com hemopericárdio', 'S26.0 Traum do coracao c/hemopericardio'),
  ('S268', 'Outros traumatismos do coração', 'S26.8 Outr traum do coracao'),
  ('S269', 'Traumatismo do coração não especificado', 'S26.9 Traum do coracao NE'),
  ('S27', 'Traumatismo de outros órgãos intratorácicos e dos não especificados', 'S27 Traum de outr orgaos intratoracicos e dos NE'),
  ('S270', 'Pneumotórax traumático', 'S27.0 Pneumotorax traum'),
  ('S271', 'Hemotórax traumático', 'S27.1 Hemotorax traum'),
  ('S272', 'Hemopneumotórax traumático', 'S27.2 Hemopneumotorax traum'),
  ('S273', 'Outros traumatismos do pulmão', 'S27.3 Outr traum do pulmao'),
  ('S274', 'Traumatismo dos brônquios', 'S27.4 Traum dos bronquios'),
  ('S275', 'Traumatismo da traquéia torácica', 'S27.5 Traum da traqueia toracica'),
  ('S276', 'Traumatismo da pleura', 'S27.6 Traum da pleura'),
  ('S277', 'Traumatismos múltiplos de órgãos intratorácicos', 'S27.7 Traum mult de orgaos intratoracicos'),
  ('S278', 'Traumatismo de outros órgãos intratorácicos especificados', 'S27.8 Traum de outr orgaos intratoracicos espec'),
  ('S279', 'Traumatismo de órgão intratorácico não especificado', 'S27.9 Traum de orgao intratoracico NE'),
  ('S28', 'Lesão por esmagamento do tórax e amputação traumática de parte do tórax', 'S28 Lesao p/esmag torax amput traum parte torax'),
  ('S280', 'Esmagamento do tórax', 'S28.0 Esmag do torax'),
  ('S281', 'Amputação traumática de parte do tórax', 'S28.1 Amput traum de parte do torax'),
  ('S29', 'Outros traumatismos do tórax e os não especificados', 'S29 Outr traum do torax e os NE'),
  ('S290', 'Traumatismo de músculo e de tendão ao nível tóracico', 'S29.0 Traum de musculo e de tendao nivel toracico'),
  ('S297', 'Traumatismos múltiplos do tórax', 'S29.7 Traum mult do torax'),
  ('S298', 'Outros traumatismos especificados do tórax', 'S29.8 Outr traum espec do torax'),
  ('S299', 'Traumatismo não especificado do tórax', 'S29.9 Traum NE do torax'),
  ('S30', 'Traumatismo superficial do abdome, do dorso e da pelve', 'S30 Traum superf do abdome do dorso e da pelve'),
  ('S300', 'Contusão do dorso e da pelve', 'S30.0 Contusao do dorso e da pelve'),
  ('S301', 'Contusão da parede abdominal', 'S30.1 Contusao da parede abdominal'),
  ('S302', 'Contusão dos órgãos genitais externos', 'S30.2 Contusao dos orgaos genitais externos'),
  ('S307', 'Traumatismos superficiais múltiplos do abdome, do dorso e da pelve', 'S30.7 Traum superf mult do abdome do dorso e pelve'),
  ('S308', 'Outros traumatismos superficiais do abdome, do dorso e da pelve', 'S30.8 Outr traum superf do abdome do dorso e pelve'),
  ('S309', 'Traumatismo superficial de parte não especificada do abdome, do dorso e da pelve', 'S30.9 Traum superf parte NE abdome dorso e pelve'),
  ('S31', 'Ferimento do abdome, do dorso e da pelve', 'S31 Ferim do abdome do dorso e da pelve'),
  ('S310', 'Ferimento do dorso e da pelve', 'S31.0 Ferim do dorso e da pelve'),
  ('S311', 'Ferimento da parede abdominal', 'S31.1 Ferim da parede abdominal'),
  ('S312', 'Ferimento do pênis', 'S31.2 Ferim do penis'),
  ('S313', 'Ferimento do escroto e do testículo', 'S31.3 Ferim do escroto e do testiculo'),
  ('S314', 'Ferimento da vagina e da vulva', 'S31.4 Ferim da vagina e da vulva'),
  ('S315', 'Ferimento de outros órgãos genitais externos e os não especificados', 'S31.5 Ferim de outr orgaos genitais externos e NE'),
  ('S317', 'Ferimentos múltiplos do abdome, do dorso e da pelve', 'S31.7 Ferim mult do abdome do dorso e da pelve'),
  ('S318', 'Ferimento de outras partes e de partes não especificadas do abdome', 'S31.8 Ferim de outr partes e de partes NE abdome'),
  ('S32', 'Fratura da coluna lombar e da pelve', 'S32 Frat da coluna lombar e da pelve'),
  ('S320', 'Fratura de vértebra lombar', 'S32.0 Frat de vertebra lombar'),
  ('S321', 'Fratura do sacro', 'S32.1 Frat do sacro'),
  ('S322', 'Fratura do cóccix', 'S32.2 Frat do coccix'),
  ('S323', 'Fratura do ílio', 'S32.3 Frat do ilio'),
  ('S324', 'Fratura do acetábulo', 'S32.4 Frat do acetabulo'),
  ('S325', 'Fratura do púbis', 'S32.5 Frat do pubis'),
  ('S327', 'Fraturas múltiplas de coluna lombar e da pelve', 'S32.7 Frat mult de coluna lombar e da pelve'),
  ('S328', 'Fratura de outras partes da coluna lombossacra e da pelve e de partes não especificadas', 'S32.8 Frat outr part coluna lombossacra pelve e NE'),
  ('S33', 'Luxação, entorse ou distensão das articulações e dos ligamentos da coluna lombar e da pelve', 'S33 Luxac entors dist artic lig col lombar pelve'),
  ('S330', 'Ruptura traumática do disco intervertebral lombar', 'S33.0 Ruptura traum do disco intervertebral lombar'),
  ('S331', 'Luxação da vértebra lombar', 'S33.1 Luxacao da vertebra lombar'),
  ('S332', 'Luxação das articulações sacroilíaca e sacrococcígea', 'S33.2 Luxacao artic sacroiliaca sacrococcigea'),
  ('S333', 'Luxação de outras partes e das não especificadas da coluna lombar e da pelve', 'S33.3 Luxacao outr partes e NE coluna lombar pelve'),
  ('S334', 'Ruptura traumática da sínfise púbica', 'S33.4 Ruptura traum da sinfise pubica'),
  ('S335', 'Entorse e distensão da coluna lombar', 'S33.5 Entorse e distensao da coluna lombar'),
  ('S336', 'Entorse e distensão da articulação sacroilíaca', 'S33.6 Entorse e distensao articulacao sacroiliaca'),
  ('S337', 'Entorse e distensão de outras partes e das não especificadas da coluna lombar e da pelve', 'S33.7 Entorse distens out part NE col lombar pelve'),
  ('S34', 'Traumatismo dos nervos e da medula lombar ao nível do abdome, do dorso e da pelve', 'S34 Traum nerv med lombar niv abdome dorso pelve'),
  ('S340', 'Concussão e edema da medula lombar', 'S34.0 Concussao e edema da medula lombar'),
  ('S341', 'Outro traumatismo da medula lombar', 'S34.1 Outr traum da medula lombar'),
  ('S342', 'Traumatismo de raiz nervosa da medula lombar e sacra', 'S34.2 Traum de raiz nervosa da medula lombar sacra'),
  ('S343', 'Traumatismo de cauda eqüina', 'S34.3 Traum de cauda equina'),
  ('S344', 'Traumatismo do plexo lombossacro', 'S34.4 Traum do plexo lombossacro'),
  ('S345', 'Traumatismo de nervos simpáticos lombares, sacros e pélvicos', 'S34.5 Traum nervos simpat lombares sacros pelvicos'),
  ('S346', 'Traumatismo do(s) nervo(s) periférico(s) do abdome, do dorso e da pelve', 'S34.6 Traum nervos perif abdome dorso e pelve'),
  ('S348', 'Traumatismo de outros nervos e dos não especificados ao nível do abdome, do dorso e da pelve', 'S34.8 Traum outr nerv e NE niv abdome dorso pelve'),
  ('S35', 'Traumatismo de vasos sangüíneos ao nível do abdome, do dorso e da pelve', 'S35 Traum vasos sang nivel abdome dorso pelve'),
  ('S350', 'Traumatismo da aorta abdominal', 'S35.0 Traum da aorta abdominal'),
  ('S351', 'Traumatismo da veia cava inferior', 'S35.1 Traum da veia cava infer'),
  ('S352', 'Traumatismo da artéria celíaca ou mesentérica', 'S35.2 Traum da arteria celiaca ou mesenterica'),
  ('S353', 'Traumatismo da veia porta ou esplênica', 'S35.3 Traum da veia porta ou esplenica'),
  ('S354', 'Traumatismo de vaso sangüíneo renal', 'S35.4 Traum de vaso sanguineo renal'),
  ('S355', 'Traumatismo de vaso sangüíneo ilíaco', 'S35.5 Traum de vaso sanguineo iliaco'),
  ('S357', 'Traumatismo de vasos múltiplos ao nível do abdome, do dorso e da pelve', 'S35.7 Traum de vasos mult nivel abdome dorso pelve'),
  ('S358', 'Traumatismo de outros vasos sangüíneos ao nível do abdome, do dorso e da pelve', 'S35.8 Traum outr vasos sang niv abdome dorso pelve'),
  ('S359', 'Traumatismo de vaso sangüíneo não especificado ao nível do abdome, do dorso e da pelve', 'S35.9 Traum vaso sang NE nivel abdome dorso pelve'),
  ('S36', 'Traumatismo de órgãos intra-abdominais', 'S36 Traum de orgaos intra-abdominais'),
  ('S360', 'Traumatismo do baço', 'S36.0 Traum do baco'),
  ('S361', 'Traumatismo do fígado ou da vesícula biliar', 'S36.1 Traum do figado ou da vesicula biliar'),
  ('S362', 'Traumatismo do pâncreas', 'S36.2 Traum do pancreas'),
  ('S363', 'Traumatismo do estômago', 'S36.3 Traum do estomago'),
  ('S364', 'Traumatismo do intestino delgado', 'S36.4 Traum do intestino delgado'),
  ('S365', 'Traumatismo do cólon', 'S36.5 Traum do colon'),
  ('S366', 'Traumatismo do reto', 'S36.6 Traum do reto'),
  ('S367', 'Traumatismo de múltiplos órgãos intra-abdominais', 'S36.7 Traum de mult orgaos intra-abdominais'),
  ('S368', 'Traumatismo de outros órgãos intra-abdominais', 'S36.8 Traum de outr orgaos intra-abdominais'),
  ('S369', 'Traumatismo de órgão intra-abdominal não especificado', 'S36.9 Traum de orgao intra-abdominal NE'),
  ('S37', 'Traumatismo do aparelho urinário e de órgãos pélvicos', 'S37 Traum do aparelho urinario e orgaos pelvicos'),
  ('S370', 'Traumatismo do rim', 'S37.0 Traum do rim'),
  ('S371', 'Traumatismo do ureter', 'S37.1 Traum do ureter'),
  ('S372', 'Traumatismo da bexiga', 'S37.2 Traum da bexiga'),
  ('S373', 'Traumatismo da uretra', 'S37.3 Traum da uretra'),
  ('S374', 'Traumatismo do ovário', 'S37.4 Traum do ovario'),
  ('S375', 'Traumatismo da trompa de Falópio', 'S37.5 Traum da trompa de Falopio'),
  ('S376', 'Traumatismo do útero', 'S37.6 Traum do utero'),
  ('S377', 'Traumatismo de múltiplos órgãos pélvicos', 'S37.7 Traum de mult orgaos pelvicos'),
  ('S378', 'Traumatismo de outros órgãos pélvicos', 'S37.8 Traum de outr orgaos pelvicos'),
  ('S379', 'Traumatismo de órgão pélvico não especificado', 'S37.9 Traum de orgao pelvico NE'),
  ('S38', 'Lesão por esmagamento e amputação traumática de parte do abdome, do dorso e da pelve', 'S38 Lesao p/esmag amput traum part abd dors pelv'),
  ('S380', 'Lesão por esmagamento dos órgãos genitais externos', 'S38.0 Lesao p/esmag dos orgaos genitais externos'),
  ('S381', 'Lesão por esmagamento de outras partes e de partes não especificadas do abdome, do dorso e da pelve', 'S38.1 Lesao p/esmag outr part NE abdome dorso pelv'),
  ('S382', 'Amputação traumática de órgãos genitais externos', 'S38.2 Amput traum de orgaos genitais externos'),
  ('S383', 'Amputação traumática de outras partes e de partes não especificadas do abdome, do dorso e da pelve', 'S38.3 Amput traum outr part NE abdome dorso pelve'),
  ('S39', 'Outros traumatismos e os não especificados do abdome, do dorso e da pelve', 'S39 Outr traum e os NE do abdome dorso e pelve'),
  ('S390', 'Traumatismo de músculo e de tendão do abdome, do dorso e da pelve', 'S39.0 Traum musculo e tendao abdome dorso e pelve'),
  ('S396', 'Traumatismo de órgão(s) intra-abdominal(is) com órgão(s) pélvico(s)', 'S39.6 Traum org intra-abdominais c/orgaos pelvicos'),
  ('S397', 'Outros traumatismos múltiplos do abdome, do dorso e da pelve', 'S39.7 Outr traum mult do abdome do dorso e pelve'),
  ('S398', 'Outros traumatismos especificados do abdome, do dorso e da pelve', 'S39.8 Outr traum espec do abdome do dorso e pelve'),
  ('S399', 'Traumatismo não especificado do abdome, do dorso e da pelve', 'S39.9 Traum NE do abdome do dorso e da pelve'),
  ('S40', 'Traumatismo superficial do ombro e do braço', 'S40 Traum superf do ombro e do braco'),
  ('S400', 'Contusão do ombro e do braço', 'S40.0 Contusao do ombro e do braco'),
  ('S407', 'Traumatismos superficiais múltiplos do ombro e do braço', 'S40.7 Traum superf mult do ombro e do braco'),
  ('S408', 'Outros traumatismos superficiais do ombro e do braço', 'S40.8 Outr traum superf do ombro e do braco'),
  ('S409', 'Traumatismo superficial não especificado do ombro e do braço', 'S40.9 Traum superf NE do ombro e do braco'),
  ('S41', 'Ferimento do ombro e do braço', 'S41 Ferim do ombro e do braco'),
  ('S410', 'Ferimento do ombro', 'S41.0 Ferim do ombro'),
  ('S411', 'Ferimento do braço', 'S41.1 Ferim do braco'),
  ('S417', 'Ferimentos múltiplos do ombro e do braço', 'S41.7 Ferim mult do ombro e do braco'),
  ('S418', 'Ferimento de outras partes e de partes não especificadas da cintura escapular', 'S41.8 Ferim outr partes e NE cintura escapular'),
  ('S42', 'Fratura do ombro e do braço', 'S42 Frat do ombro e do braco'),
  ('S420', 'Fratura da clavícula', 'S42.0 Frat da clavicula'),
  ('S421', 'Fratura da omoplata (escápula)', 'S42.1 Frat da omoplata'),
  ('S422', 'Fratura da extremidade superior do úmero', 'S42.2 Frat da extremidade super do umero'),
  ('S423', 'Fratura da diáfise do úmero', 'S42.3 Frat da diafise do umero'),
  ('S424', 'Fratura da extremidade inferior do úmero', 'S42.4 Frat da extremidade infer do umero'),
  ('S427', 'Fraturas múltiplas da clavícula, da omoplata (escápula) e do úmero', 'S42.7 Frat mult da clavicula da omoplata e umero'),
  ('S428', 'Fratura de outras partes do ombro e do braço', 'S42.8 Frat de outr partes do ombro e do braco'),
  ('S429', 'Fratura da cintura escapular, parte não especificada', 'S42.9 Frat da cintura escapular parte NE'),
  ('S43', 'Luxação, entorse e distensão das articulações e dos ligamentos da cintura escapular', 'S43 Luxacao entorse distens artic lig cint escap'),
  ('S430', 'Luxação da articulação do ombro', 'S43.0 Luxacao da articulacao do ombro'),
  ('S431', 'Luxação da articulação acromioclavicular', 'S43.1 Luxacao da articulacao acromioclavicular'),
  ('S432', 'Luxação da articulação esternoclavicular', 'S43.2 Luxacao da articulacao esternoclavicular'),
  ('S433', 'Luxação de outras partes e das não especificadas da cintura escapular', 'S43.3 Luxacao de outr partes e NE cint escapular'),
  ('S434', 'Entorse e distensão de articulação do ombro', 'S43.4 Entorse e distensao de articulacao do ombro'),
  ('S435', 'Entorse e distensão da articulação acromioclavicular', 'S43.5 Entorse e distensao artic acromioclavicular'),
  ('S436', 'Entorse e distensão da articulação esternoclavicular', 'S43.6 Entorse e distensao artic esternoclavicular'),
  ('S437', 'Entorse e distensão de outras partes e de partes não especificadas da cintura escapular', 'S43.7 Entorse distensao outr partes NE cint escap'),
  ('S44', 'Traumatismo de nervos ao nível do ombro e do braço', 'S44 Traum de nervos ao nivel do ombro e do braco'),
  ('S440', 'Traumatismo do nervo cubital (ulnar) ao nível do braço', 'S44.0 Traum do nervo cubital ao nivel do braco'),
  ('S441', 'Traumatismo do nervo mediano ao nível do braço', 'S44.1 Traum do nervo mediano ao nivel do braco'),
  ('S442', 'Traumatismo do nervo radial ao nível do braço', 'S44.2 Traum do nervo radial ao nivel do braco'),
  ('S443', 'Traumatismo do nervo axilar', 'S44.3 Traum do nervo axilar'),
  ('S444', 'Traumatismo do nervo musculocutâneo', 'S44.4 Traum do nervo musculocutaneo'),
  ('S445', 'Traumatismo do nervo sensitivo cutâneo ao nível do ombro e do braço', 'S44.5 Traum nervo sensit cutaneo nivel ombro braco'),
  ('S447', 'Traumatismo de múltiplos nervos ao nível do ombro e do braço', 'S44.7 Traum de mult nervos ao nivel ombro e braco'),
  ('S448', 'Traumatismo de outros nervos ao nível do ombro e do braço', 'S44.8 Traum de outr nervos ao nivel ombro e braco'),
  ('S449', 'Traumatismo de nervo não especificado ao nível do ombro e do braço', 'S44.9 Traum de nervo NE ao nivel do ombro e braco'),
  ('S45', 'Traumatismo dos vasos sangüíneos ao nível do ombro e do braço', 'S45 Traum dos vasos sanguineos nivel ombro braco'),
  ('S450', 'Traumatismo da artéria axilar', 'S45.0 Traum da arteria axilar'),
  ('S451', 'Traumatismo da artéria braquial', 'S45.1 Traum da arteria braquial'),
  ('S452', 'Traumatismo da veia axilar ou braquial', 'S45.2 Traum da veia axilar ou braquial'),
  ('S453', 'Traumatismo de veia superficial ao nível do ombro e do braço', 'S45.3 Traum de veia superf ao nivel ombro e braco'),
  ('S457', 'Traumatismo de múltiplos vasos sangüíneos ao nível do ombro e do braço', 'S45.7 Traum mult vasos sang nivel ombro braco'),
  ('S458', 'Traumatismo de outros vasos sangüíneos ao nível do ombro e do braço', 'S45.8 Traum de outr vasos sang nivel ombro braco'),
  ('S459', 'Traumatismo de vaso sangüíneo não especificado ao nível do ombro e do braço', 'S45.9 Traum vaso sanguineo NE nivel ombro braco'),
  ('S46', 'Traumatismo de tendão e músculo ao nível do ombro e do braço', 'S46 Traum de tendao e musculo nivel ombro braco'),
  ('S460', 'Traumatismo do tendão do manguito rotador do ombro', 'S46.0 Traum do tendao do manguito rotador do ombro'),
  ('S461', 'Traumatismo do músculo e tendão da cabeça longa do bíceps', 'S46.1 Traum do musculo tendao cabeca longa biceps'),
  ('S462', 'Traumatismo do músculo e tendão de outras partes do bíceps', 'S46.2 Traum do musculo e tendao outr partes biceps'),
  ('S463', 'Traumatismo do músculo e tendão do tríceps', 'S46.3 Traum do musculo e tendao do triceps'),
  ('S467', 'Traumatismo de múltiplos músculos e tendões ao nível do ombro e do braço', 'S46.7 Traum mult musc tendoes nivel ombro braco'),
  ('S468', 'Traumatismo de outros músculos e tendões ao nível do ombro e do braço', 'S46.8 Traum outr musc tendoes nivel ombro braco'),
  ('S469', 'Traumatismo de músculo e tendão não especificado ao nível do ombro e do braço', 'S46.9 Traum musculo tendao NE nivel ombro braco'),
  ('S47', 'Lesão por esmagamento do ombro e do braço', 'S47 Lesao p/esmag do ombro e do braco'),
  ('S47', 'Lesão por esmagamento do ombro e do braço', 'S47 Lesao p/esmag do ombro e do braco'),
  ('S48', 'Amputação traumática do ombro e do braço', 'S48 Amput traum do ombro e do braco'),
  ('S480', 'Amputação traumática da articulação do ombro', 'S48.0 Amput traum da articulacao do ombro'),
  ('S481', 'Amputação traumática de localização entre o ombro e o cotovelo', 'S48.1 Amput traum de localiz entre ombro cotovelo'),
  ('S489', 'Amputação traumática do ombro e do braço, de localização não especificada', 'S48.9 Amput traum do ombro e do braco localiz NE'),
  ('S49', 'Outros traumatismos e os não especificados do ombro e do braço', 'S49 Outr traum e os NE do ombro e do braco'),
  ('S497', 'Traumatismos múltiplos do ombro e do braço', 'S49.7 Traum mult do ombro e do braco'),
  ('S498', 'Outros traumatismos especificados do ombro e do braço', 'S49.8 Outr traum espec do ombro e do braco'),
  ('S499', 'Traumatismo não especificado do ombro e do braço', 'S49.9 Traum NE do ombro e do braco'),
  ('S50', 'Traumatismo superficial do cotovelo e do antebraço', 'S50 Traum superf do cotovelo e do antebraco'),
  ('S500', 'Contusão do cotovelo', 'S50.0 Contusao do cotovelo'),
  ('S501', 'Contusão de outras partes e de partes não especificadas do antebraço', 'S50.1 Contusao outr partes e NE do antebraco'),
  ('S507', 'Traumatismos superficiais múltiplos do antebraço', 'S50.7 Traum superf mult do antebraco'),
  ('S508', 'Outros traumatismos superficiais do antebraço', 'S50.8 Outr traum superf do antebraco'),
  ('S509', 'Traumatismo superficial do antebraço, não especificado', 'S50.9 Traum superf do antebraco NE'),
  ('S51', 'Ferimento do antebraço', 'S51 Ferim do antebraco'),
  ('S510', 'Ferimento do cotovelo', 'S51.0 Ferim do cotovelo'),
  ('S517', 'Ferimentos múltiplos do antebraço', 'S51.7 Ferim mult do antebraco'),
  ('S518', 'Ferimento de outras partes do antebraço', 'S51.8 Ferim de outr partes do antebraco'),
  ('S519', 'Ferimento do antebraço, parte não especificado', 'S51.9 Ferim do antebraco parte NE'),
  ('S52', 'Fratura do antebraço', 'S52 Frat do antebraco'),
  ('S520', 'Fratura da extremidade superior do cúbito (ulna)', 'S52.0 Frat da extremidade super do cubito'),
  ('S521', 'Fratura da extremidade superior do rádio', 'S52.1 Frat da extremidade super do radio'),
  ('S522', 'Fratura da diáfise do cúbito (ulna)', 'S52.2 Frat da diafise do cubito'),
  ('S523', 'Fratura da diáfise do rádio', 'S52.3 Frat da diafise do radio'),
  ('S524', 'Fratura das diáfises do rádio e do cúbito (ulna)', 'S52.4 Frat das diafises do radio e do cubito'),
  ('S525', 'Fratura da extremidade distal do rádio', 'S52.5 Frat da extremidade distal do radio'),
  ('S526', 'Fratura da extremidade distal do rádio e do cúbito (ulna)', 'S52.6 Frat da extremidade distal do radio e cubito'),
  ('S527', 'Fraturas múltiplas do antebraço', 'S52.7 Frat mult do antebraco'),
  ('S528', 'Fratura de outras partes do antebraço', 'S52.8 Frat de outr partes do antebraco'),
  ('S529', 'Fratura do antebraço, parte não especificada', 'S52.9 Frat do antebraco parte NE'),
  ('S53', 'Luxação, entorse e distensão das articulações e dos ligamentos do cotovelo', 'S53 Luxacao entorse distensao artic lig cotovelo'),
  ('S530', 'Luxação da cabeça do rádio', 'S53.0 Luxacao da cabeca do radio'),
  ('S531', 'Luxação do cotovelo, não especificada', 'S53.1 Luxacao do cotovelo NE'),
  ('S532', 'Ruptura traumática do ligamento colateral do rádio', 'S53.2 Ruptura traum do ligamento colateral radio'),
  ('S533', 'Ruptura traumática do ligamento colateral do cúbito (ulna)', 'S53.3 Ruptura traum do ligamento colateral cubito'),
  ('S534', 'Entorse e distensão do cotovelo', 'S53.4 Entorse e distensao do cotovelo'),
  ('S54', 'Traumatismo de nervos ao nível do antebraço', 'S54 Traum de nervos ao nivel do antebraco'),
  ('S540', 'Traumatismo do nervo cubital (ulnar) ao nível do antebraço', 'S54.0 Traum do nervo cubital ao nivel do antebraco'),
  ('S541', 'Traumatismo do nervo mediano ao nível do antebraço', 'S54.1 Traum do nervo mediano ao nivel do antebraco'),
  ('S542', 'Traumatismo do nervo radial ao nível do antebraço', 'S54.2 Traum do nervo radial ao nivel do antebraco'),
  ('S543', 'Traumatismo do nervo cutâneo sensitivo ao nível do antebraço', 'S54.3 Traum nervo cutaneo sensitivo niv antebraco'),
  ('S547', 'Traumatismo de múltiplos nervos ao nível do antebraço', 'S54.7 Traum de mult nervos ao nivel do antebraco'),
  ('S548', 'Traumatismo de outros nervos ao nível do antebraço', 'S54.8 Traum de outr nervos ao nivel do antebraco'),
  ('S549', 'Traumatismo de nervo não especificado ao nível do antebraço', 'S54.9 Traum de nervo NE ao nivel do antebraco'),
  ('S55', 'Traumatismo de vasos sangüíneos ao nível do antebraço', 'S55 Traum de vasos sanguineos ao nivel antebraco'),
  ('S550', 'Traumatismo da artéria cubital (ulnar) ao nível do antebraço', 'S55.0 Traum da arteria cubital ao nivel antebraco'),
  ('S551', 'Traumatismo da artéria radial ao nível do antebraço', 'S55.1 Traum da arteria radial ao nivel antebraco'),
  ('S552', 'Traumatismo de veia ao nível do antebraço', 'S55.2 Traum de veia ao nivel do antebraco'),
  ('S557', 'Traumatismo de múltiplos vasos sangüíneos ao nível do antebraço', 'S55.7 Traum mult vasos sanguineos nivel antebraco'),
  ('S558', 'Traumatismo de outros vasos sangüíneos ao nível do antebraço', 'S55.8 Traum outr vasos sanguineos nivel antebraco'),
  ('S559', 'Traumatismo de vasos sangüíneos não especificados ao nível do antebraço', 'S55.9 Traum de vasos sanguineos NE nivel antebraco'),
  ('S56', 'Traumatismo do músculo e tendão ao nível do antebraço', 'S56 Traum do musculo e tendao ao nivel antebraco'),
  ('S560', 'Traumatismo do músculo flexor e tendão do polegar ao nível do antebraço', 'S56.0 Traum musc flexor tend polegar niv antebraco'),
  ('S561', 'Traumatismo do músculo flexor e tendão de outro(s) dedo(s) ao nível do antebraço', 'S56.1 Traum musc flexor tend out dedos niv antebr'),
  ('S562', 'Traumatismo de outro músculo flexor e tendão ao nível do antebraço', 'S56.2 Traum outr musc flexor tendao niv antebraco'),
  ('S563', 'Traumatismo dos músculos extensor ou abdutor e tendões do polegar ao nível do antebraço', 'S56.3 Traum musc extens abdut tend poleg niv anteb'),
  ('S564', 'Traumatismo do músculo extensor e tendão de outro(s) dedo(s) ao nível do antebraço', 'S56.4 Traum musc extens tend out dedos niv antebr'),
  ('S565', 'Traumatismo de outros músculos extensores e tendões ao nível do antebraço', 'S56.5 Traum outr musc extens tendoes niv antebraco'),
  ('S567', 'Traumatismo de músculos e tendões múltiplos ao nível do antebraço', 'S56.7 Traum musculos tendoes mult nivel antebraco'),
  ('S568', 'Traumatismo de outros músculos e tendões e dos não especificados ao nível do antebraço', 'S56.8 Traum outr musc tendoes e NE nivel antebraco'),
  ('S57', 'Lesão por esmagamento do antebraço', 'S57 Lesao p/esmag do antebraco'),
  ('S570', 'Lesão por esmagamento do cotovelo', 'S57.0 Lesao p/esmag do cotovelo'),
  ('S578', 'Lesão por esmagamento de outras partes do antebraço', 'S57.8 Lesao p/esmag de outr partes do antebraco'),
  ('S579', 'Lesão por esmagamento de parte não especificada do antebraço', 'S57.9 Lesao p/esmag de parte NE do antebraco'),
  ('S58', 'Amputação traumática do cotovelo e do antebraço', 'S58 Amput traum do cotovelo e do antebraco'),
  ('S580', 'Amputação traumática ao nível do cotovelo', 'S58.0 Amput traum ao nivel do cotovelo'),
  ('S581', 'Amputação traumática do antebraço entre o cotovelo e o punho', 'S58.1 Amput traum antebraco entre cotovelo punho'),
  ('S589', 'Amputação traumática do antebraço, nível não especificado', 'S58.9 Amput traum do antebraco nivel NE'),
  ('S59', 'Outros traumatismos do antebraço e os não especificados', 'S59 Outr traum do antebraco e os NE'),
  ('S597', 'Traumatismos múltiplos do cotovelo', 'S59.7 Traum mult do cotovelo'),
  ('S598', 'Outros traumatismos especificados do antebraço', 'S59.8 Outr traum espec do antebraco'),
  ('S599', 'Traumatismo não especificado do antebraço', 'S59.9 Traum NE do antebraco'),
  ('S60', 'Traumatismo superficial do punho e da mão', 'S60 Traum superf do punho e da mao'),
  ('S600', 'Contusão de dedo(s) sem lesão da unha', 'S60.0 Contusao de dedos s/lesao da unha'),
  ('S601', 'Contusão de dedo(s) com lesão da unha', 'S60.1 Contusao de dedos c/lesao da unha'),
  ('S602', 'Contusão de outras partes do punho e da mão', 'S60.2 Contusao de outr partes do punho e da mao'),
  ('S607', 'Traumatismos superficiais múltiplos do punho e da mão', 'S60.7 Traum superf mult do punho e da mao'),
  ('S608', 'Outros traumatismos superficiais do punho e da mão', 'S60.8 Outr traum superf do punho e da mao'),
  ('S609', 'Traumatismo superficial não especificado do punho e da mão', 'S60.9 Traum superf NE do punho e da mao'),
  ('S61', 'Ferimento do punho e da mão', 'S61 Ferim do punho e da mao'),
  ('S610', 'Ferimento de dedo(s) sem lesão da unha', 'S61.0 Ferim de dedos s/lesao da unha'),
  ('S611', 'Ferimento de dedo(s) com lesão da unha', 'S61.1 Ferim de dedos c/lesao da unha'),
  ('S617', 'Ferimentos múltiplos do punho e da mão', 'S61.7 Ferim mult do punho e da mao'),
  ('S618', 'Ferimento de outras partes do punho e da mão', 'S61.8 Ferim de outr partes do punho e da mao'),
  ('S619', 'Ferimento do punho e da mão, parte não especificada', 'S61.9 Ferim do punho e da mao parte NE'),
  ('S62', 'Fratura ao nível do punho e da mão', 'S62 Frat ao nivel do punho e da mao'),
  ('S620', 'Fratura do osso navicular (escafoíde) da mão', 'S62.0 Frat do osso navicular da mao'),
  ('S621', 'Fratura de outro(s) osso(s) do carpo', 'S62.1 Frat de outr ossos do carpo'),
  ('S622', 'Fratura do primeiro metacarpiano', 'S62.2 Frat do primeiro metacarpiano'),
  ('S623', 'Fratura de outros ossos do metacarpo', 'S62.3 Frat de outr ossos do metacarpo'),
  ('S624', 'Fraturas múltiplas de ossos metacarpianos', 'S62.4 Frat mult de ossos metacarpianos'),
  ('S625', 'Fratura do polegar', 'S62.5 Frat do polegar'),
  ('S626', 'Fratura de outros dedos', 'S62.6 Frat de outr dedos'),
  ('S627', 'Fraturas múltiplas de dedo(s)', 'S62.7 Frat mult de dedos'),
  ('S628', 'Fratura de outras partes e de partes não especificadas do punho e da mão', 'S62.8 Frat de outr partes e de partes NE punho mao'),
  ('S63', 'Luxação, entorse e distensão das articulações e dos ligamentos ao nível do punho e da mão', 'S63 Luxac entors distens artic lig niv punho mao'),
  ('S630', 'Luxação do punho', 'S63.0 Luxacao do punho'),
  ('S631', 'Luxação do dedo', 'S63.1 Luxacao do dedo'),
  ('S632', 'Luxações múltiplas dos dedos', 'S63.2 Luxacoes mult dos dedos'),
  ('S633', 'Ruptura traumática de ligamento(s) do punho e do carpo', 'S63.3 Ruptura traum de ligamentos do punho e carpo'),
  ('S634', 'Ruptura traumática do ligamento do dedo nas articulações metacarpofalangianas e interfalangianas', 'S63.4 Rupt traum lig dedo artic metacarp interfal'),
  ('S635', 'Entorse e distensão do punho', 'S63.5 Entorse e distensao do punho'),
  ('S636', 'Entorse e distensão do(s) dedo(s)', 'S63.6 Entorse e distensao de dedos'),
  ('S637', 'Entorse e distensão de outras partes e das não especificadas da mão', 'S63.7 Entorse e distensao de outr partes e NE mao'),
  ('S64', 'Traumatismo de nervos ao nível do punho e da mão', 'S64 Traum de nervos ao nivel do punho e da mao'),
  ('S640', 'Traumatismo do nervo cubital (ulnar) ao nível do punho e da mão', 'S64.0 Traum do nervo cubital ao nivel punho e mao'),
  ('S641', 'Traumatismo do nervo mediano ao nível do punho e da mão', 'S64.1 Traum do nervo mediano ao nivel punho e mao'),
  ('S642', 'Traumatismo do nervo radial ao nível do punho e da mão', 'S64.2 Traum do nervo radial ao nivel punho e mao'),
  ('S643', 'Traumatismo do nervo digital do polegar', 'S64.3 Traum do nervo digital do polegar'),
  ('S644', 'Traumatismo do nervo digital de outro dedo', 'S64.4 Traum do nervo digital de outr dedo'),
  ('S647', 'Traumatismo de múltiplos nervos ao nível de punho e da mão', 'S64.7 Traum de mult nervos ao nivel de punho e mao'),
  ('S648', 'Traumatismo de outros nervos ao nível do punho e da mão', 'S64.8 Traum de outr nervos ao nivel do punho e mao'),
  ('S649', 'Traumatismo de nervo não especificado ao nível do punho e da mão', 'S64.9 Traum de nervo NE ao nivel do punho e da mao'),
  ('S65', 'Traumatismo de vasos sangüíneos ao nível do punho e da mão', 'S65 Traum de vasos sanguineos nivel punho e mao'),
  ('S650', 'Traumatismo da artéria cubital (ulnar) ao nível do punho e da mão', 'S65.0 Traum da arteria cubital nivel punho e mao'),
  ('S651', 'Traumatismo da artéria radial ao nível do punho e da mão', 'S65.1 Traum da arteria radial ao nivel punho e mao'),
  ('S652', 'Traumatismo do arco palmar superficial', 'S65.2 Traum do arco palmar superf'),
  ('S653', 'Traumatismo do arco palmar profundo', 'S65.3 Traum do arco palmar profundo'),
  ('S654', 'Traumatismo de vaso(s) sangüíneo(s) do polegar', 'S65.4 Traum de vasos sanguineos do polegar'),
  ('S655', 'Traumatismo de vaso(s) sangüíneo(s) de outro dedo', 'S65.5 Traum de vasos sanguineos de outr dedo'),
  ('S657', 'Traumatismo de vasos sangüíneos múltiplos ao nível de punho e da mão', 'S65.7 Traum vasos sang mult nivel punho e mao'),
  ('S658', 'Traumatismo de outros vasos sangüíneos ao nível do punho e de mão', 'S65.8 Traum de outr vasos sang nivel punho e mao'),
  ('S659', 'Traumatismo de vaso sangüíneo não especificado ao nível do punho e da mão', 'S65.9 Traum de vaso sanguineo NE nivel punho e mao'),
  ('S66', 'Traumatismo de músculo e tendão ao nível do punho e da mão', 'S66 Traum de musculo e tendao nivel punho e mao'),
  ('S660', 'Traumatismo do músculo flexor longo e tendão do polegar ao nível do punho e da mão', 'S66.0 Traum musc flex long tend poleg niv punh mao'),
  ('S661', 'Traumatismo do músculo flexor e tendão de outro dedo ao nível do punho e da mão', 'S66.1 Traum musc flex tend outr dedo niv punho mao'),
  ('S662', 'Traumatismo do músculo extensor e tendão do polegar ao nível do punho e da mão', 'S66.2 Traum musc extens tend polegar niv punho mao'),
  ('S663', 'Traumatismo do músculo extensor e tendão de outro dedo ao nível do punho e da mão', 'S66.3 Traum musc extens tend out ded niv punho mao'),
  ('S664', 'Traumatismo do músculo intrínseco e tendão do polegar ao nível do punho e da mão', 'S66.4 Traum musc intrins tend poleg niv punho mao'),
  ('S665', 'Traumatismo do músculo intrínseco e tendão de outro dedo ao nível do punho e da mão', 'S66.5 Traum musc intrins tend out ded niv punh mao'),
  ('S666', 'Traumatismo de músculos flexores e tendões múltiplos ao nível do punho e da mão', 'S66.6 Traum musc flexores tend mult niv punho mao'),
  ('S667', 'Traumatismo de músculos extensores e tendões múltiplos ao nível do punho e da mão', 'S66.7 Traum musc extensor tend mult niv punho mao'),
  ('S668', 'Traumatismo de outros músculos e tendões ao nível do punho e da mão', 'S66.8 Traum outr musc tendoes nivel punho e mao'),
  ('S669', 'Traumatismo de músculo e tendão não especificado ao nível do punho e da mão', 'S66.9 Traum musculo e tendao NE nivel punho e mao'),
  ('S67', 'Lesão por esmagamento do punho e da mão', 'S67 Lesao p/esmag do punho e da mao'),
  ('S670', 'Lesão por esmagamento do polegar e de outro(s) dedo(s)', 'S67.0 Lesao p/esmag do polegar e de outr dedos'),
  ('S678', 'Lesão por esmagamento de outras partes e das não especificadas do punho e da mão', 'S67.8 Lesao p/esmag outr partes e NE punho e mao'),
  ('S68', 'Amputação traumática ao nível do punho e da mão', 'S68 Amput traum ao nivel do punho e da mao'),
  ('S680', 'Amputação traumática do polegar (completa) (parcial)', 'S68.0 Amput traum do polegar'),
  ('S681', 'Amputação traumática de um outro dedo apenas (completa) (parcial)', 'S68.1 Amput traum de um outr dedo apenas'),
  ('S682', 'Amputação traumática de dois ou mais dedos somente (completa) (parcial)', 'S68.2 Amput traum de dois ou mais dedos somente'),
  ('S683', 'Amputação traumática combinada de (partes de) dedo(s) associada a outras partes do punho e da mão', 'S68.3 Amput traum comb dedo ass out part punho mao'),
  ('S684', 'Amputação traumática da mão ao nível do punho', 'S68.4 Amput traum da mao ao nivel do punho'),
  ('S688', 'Amputação traumática de outras partes do punho e da mão', 'S68.8 Amput traum de outr partes do punho e da mao'),
  ('S689', 'Amputação traumática do punho e da mão, nível não especificado', 'S68.9 Amput traum do punho e da mao nivel NE'),
  ('S69', 'Outros traumatismos e os não especificados do punho e da mão', 'S69 Outr traum e os NE do punho e da mao'),
  ('S697', 'Traumatismos múltiplos do punho e da mão', 'S69.7 Traum mult do punho e da mao'),
  ('S698', 'Outros traumatismos especificados do punho e da mão', 'S69.8 Outr traum espec do punho e da mao'),
  ('S699', 'Traumatismo não especificados do punho e da mão', 'S69.9 Traum NE do punho e da mao'),
  ('S70', 'Traumatismo superficial do quadril e da coxa', 'S70 Traum superf do quadril e da coxa'),
  ('S700', 'Contusão do quadril', 'S70.0 Contusao do quadril'),
  ('S701', 'Contusão da coxa', 'S70.1 Contusao da coxa'),
  ('S707', 'Traumatismos superficiais múltiplos do quadril e da coxa', 'S70.7 Traum superf mult do quadril e da coxa'),
  ('S708', 'Outros traumatismos superficiais do quadril e da coxa', 'S70.8 Outr traum superf do quadril e da coxa'),
  ('S709', 'Traumatismo superficial não especificado do quadril e da coxa', 'S70.9 Traum superf NE do quadril e da coxa'),
  ('S71', 'Ferimento do quadril e da coxa', 'S71 Ferim do quadril e da coxa'),
  ('S710', 'Ferimento do quadril', 'S71.0 Ferim do quadril'),
  ('S711', 'Ferimento da coxa', 'S71.1 Ferim da coxa'),
  ('S717', 'Ferimentos múltiplos do quadril e da coxa', 'S71.7 Ferim mult do quadril e da coxa'),
  ('S718', 'Ferimentos de outras partes e das não especificadas da cintura pélvica', 'S71.8 Ferim outr partes e das NE cintura pelvica'),
  ('S72', 'Fratura do fêmur', 'S72 Frat do femur'),
  ('S720', 'Fratura do colo do fêmur', 'S72.0 Frat do colo do femur'),
  ('S721', 'Fratura pertrocantérica', 'S72.1 Frat pertrocanterica'),
  ('S722', 'Fratura subtrocantérica', 'S72.2 Frat subtrocanterica'),
  ('S723', 'Fratura da diáfise do fêmur', 'S72.3 Frat da diafise do femur'),
  ('S724', 'Fratura da extremidade distal do fêmur', 'S72.4 Frat da extremidade distal do femur'),
  ('S727', 'Fraturas múltiplas do fêmur', 'S72.7 Frat mult do femur'),
  ('S728', 'Fraturas de outras partes do fêmur', 'S72.8 Frat de outr partes do femur'),
  ('S729', 'Fratura do fêmur, parte não especificada', 'S72.9 Frat do femur parte NE'),
  ('S73', 'Luxação, entorse e distensão da articulação e dos ligamentos do quadril', 'S73 Luxacao entorse distensao artic lig quadril'),
  ('S730', 'Luxação da articulação do quadril', 'S73.0 Luxacao da articulacao do quadril'),
  ('S731', 'Entorse e distensão do quadril', 'S73.1 Entorse e distensao do quadril'),
  ('S74', 'Traumatismo de nervos ao nível do quadril e da coxa', 'S74 Traum de nervos ao nivel do quadril e coxa'),
  ('S740', 'Traumatismo do nervo ciático ao nível do quadril e da coxa', 'S74.0 Traum do nervo ciatico nivel quadril e coxa'),
  ('S741', 'Traumatismo do nervo femural ao nível do quadril e da coxa', 'S74.1 Traum do nervo femural nivel quadril e coxa'),
  ('S742', 'Traumatismo do nervo sensitivo cutâneo ao nível do quadril e da coxa', 'S74.2 Traum nervo sensit cutaneo niv quadril coxa'),
  ('S747', 'Traumatismo de nervos múltiplos ao nível do quadril e da coxa', 'S74.7 Traum de nervos mult ao nivel quadril e coxa'),
  ('S748', 'Traumatismo de outros nervos ao nível do quadril e da coxa', 'S74.8 Traum de outr nervos ao nivel quadril e coxa'),
  ('S749', 'Traumatismo de nervo não especificado ao nível do quadril e da coxa', 'S74.9 Traum de nervo NE ao nivel do quadril e coxa'),
  ('S75', 'Traumatismo de vasos sangüíneos ao nível do quadril e da coxa', 'S75 Traum vasos sanguineos nivel quadril e coxa'),
  ('S750', 'Traumatismo da artéria femural', 'S75.0 Traum da arteria femural'),
  ('S751', 'Traumatismo da veia femural ao nível do quadril e da coxa', 'S75.1 Traum da veia femural nivel quadril e coxa'),
  ('S752', 'Traumatismo da veia grande safena ao nível do quadril e da coxa', 'S75.2 Traum veia grande safena niv quadril e coxa'),
  ('S757', 'Traumatismo de múltiplos vasos sangüíneos ao nível do quadril e da coxa', 'S75.7 Traum mult vasos sang nivel quadril e coxa'),
  ('S758', 'Traumatismo de outros vaso sangüíneos ao nível do quadril e da coxa', 'S75.8 Traum outr vaso sang nivel quadril e coxa'),
  ('S759', 'Traumatismo de vaso sangüíneo não especificado ao nível do quadril e da coxa', 'S75.9 Traum vaso sanguineo NE nivel quadril e coxa'),
  ('S76', 'Traumatismo de músculo e de tendão ao nível do quadril e da coxa', 'S76 Traum musculo e tendao nivel quadril e coxa'),
  ('S760', 'Traumatismo do músculo e do tendão do quadril', 'S76.0 Traum do musculo e do tendao do quadril'),
  ('S761', 'Traumatismo do músculo e do tendão do quadríceps', 'S76.1 Traum do musculo e do tendao do quadriceps'),
  ('S762', 'Traumatismo do músculo e do tendão do adutor da coxa', 'S76.2 Traum do musculo e do tendao do adutor coxa'),
  ('S763', 'Traumatismo do músculo e do tendão dos músculos posteriores ao nível da coxa', 'S76.3 Traum musculo e tendao musc post nivel coxa'),
  ('S764', 'Traumatismo de outros músculos e tendões e os não especificados ao nível da coxa', 'S76.4 Traum outr musculos tendoes e NE nivel coxa'),
  ('S767', 'Traumatismo de múltiplos músculos e tendões ao nível do quadril e da coxa', 'S76.7 Traum mult musc tendoes nivel quadril e coxa'),
  ('S77', 'Lesão por esmagamento do quadril e da coxa', 'S77 Lesao p/esmag do quadril e da coxa'),
  ('S770', 'Lesão por esmagamento do quadril', 'S77.0 Lesao p/esmag do quadril'),
  ('S771', 'Lesão por esmagamento da coxa', 'S77.1 Lesao p/esmag da coxa'),
  ('S772', 'Lesão por esmagamento do quadril e da coxa', 'S77.2 Lesao p/esmag do quadril e da coxa'),
  ('S78', 'Amputação traumática do quadril e da coxa', 'S78 Amput traum do quadril e da coxa'),
  ('S780', 'Amputação traumática na articulação do quadril', 'S78.0 Amput traum na articulacao do quadril'),
  ('S781', 'Amputação traumática localizada entre o joelho e o quadril', 'S78.1 Amput traum localizada entre joelho quadril'),
  ('S789', 'Amputação traumática do quadril e coxa nível não especificado', 'S78.9 Amput traum do quadril e coxa nivel NE'),
  ('S79', 'Outros traumatismos e os não especificados do quadril e da coxa', 'S79 Outr traum e os NE do quadril e da coxa'),
  ('S797', 'Traumatismos múltiplos do quadril e da coxa', 'S79.7 Traum mult do quadril e da coxa'),
  ('S798', 'Outros traumatismos especificados do quadril e da coxa', 'S79.8 Outr traum espec do quadril e da coxa'),
  ('S799', 'Traumatismo não especificado do quadril e da coxa', 'S79.9 Traum NE do quadril e da coxa'),
  ('S80', 'Traumatismo superficial da perna', 'S80 Traum superf da perna'),
  ('S800', 'Contusão do joelho', 'S80.0 Contusao do joelho'),
  ('S801', 'Contusão de outras partes e de partes não especificadas da perna', 'S80.1 Contusao de outr partes e de partes NE perna'),
  ('S807', 'Traumatismos superficiais múltiplos da perna', 'S80.7 Traum superf mult da perna'),
  ('S808', 'Outros traumatismos superficiais da perna', 'S80.8 Outr traum superf da perna'),
  ('S809', 'Traumatismo superficial não especificado da perna', 'S80.9 Traum superf NE da perna'),
  ('S81', 'Ferimento da perna', 'S81 Ferim da perna'),
  ('S810', 'Ferimento do joelho', 'S81.0 Ferim do joelho'),
  ('S817', 'Ferimentos múltiplos da perna', 'S81.7 Ferim mult da perna'),
  ('S818', 'Ferimento de outras partes da perna', 'S81.8 Ferim de outr partes da perna'),
  ('S819', 'Ferimento da perna, parte não especificada', 'S81.9 Ferim da perna parte NE'),
  ('S82', 'Fratura da perna, incluindo tornozelo', 'S82 Frat da perna incl tornozelo'),
  ('S820', 'Fratura da rótula (patela)', 'S82.0 Frat da rotula'),
  ('S821', 'Fratura da extremidade proximal da tíbia', 'S82.1 Frat da extremidade proximal da tibia'),
  ('S822', 'Fratura da diáfise da tíbia', 'S82.2 Frat da diafise da tibia'),
  ('S823', 'Fratura da extremidade distal da tíbia', 'S82.3 Frat da extremidade distal da tibia'),
  ('S824', 'Fratura do perônio (fíbula)', 'S82.4 Frat do peronio'),
  ('S825', 'Fratura do maléolo medial', 'S82.5 Frat do maleolo medial'),
  ('S826', 'Fratura do maléolo lateral', 'S82.6 Frat do maleolo lateral'),
  ('S827', 'Fraturas múltiplas da perna', 'S82.7 Frat mult da perna'),
  ('S828', 'Fratura de outras partes da perna', 'S82.8 Frat de outr partes da perna'),
  ('S829', 'Fratura da perna, parte não especificada', 'S82.9 Frat da perna parte NE'),
  ('S83', 'Luxação, entorse e distensão das articulações e dos ligamentos do joelho', 'S83 Luxacao entorse distensao art lig joelho'),
  ('S830', 'Luxação da rótula (patela)', 'S83.0 Luxacao da rotula'),
  ('S831', 'Luxação do joelho', 'S83.1 Luxacao do joelho'),
  ('S832', 'Ruptura do menisco, atual', 'S83.2 Ruptura do menisco atual'),
  ('S833', 'Ruptura atual da cartilagem da articulação do joelho', 'S83.3 Ruptura atual cartilagem articulacao joelho'),
  ('S834', 'Entorse e distensão envolvendo ligamento colateral (peronial) (tibial) do joelho', 'S83.4 Entorse distensao envolv lig colat joelho'),
  ('S835', 'Entorse e distensão envolvendo ligamento cruzado (anterior) (posterior) do joelho', 'S83.5 Entorse distensao envolv lig cruzado joelho'),
  ('S836', 'Entorse e distensão de outras partes e das não especificadas do joelho', 'S83.6 Entorse distensao outr partes e NE joelho'),
  ('S837', 'Traumatismo de estruturas múltiplas do joelho', 'S83.7 Traum de estruturas mult do joelho'),
  ('S84', 'Traumatismo de nervos periféricos da perna', 'S84 Traum de nervos perifericos da perna'),
  ('S840', 'Traumatismo do nervo tibial ao nível da perna', 'S84.0 Traum do nervo tibial ao nivel da perna'),
  ('S841', 'Traumatismo do nervo peronial ao nível da perna', 'S84.1 Traum do nervo peronial ao nivel da perna'),
  ('S842', 'Traumatismo do nervo cutâneo sensitivo ao nível da perna', 'S84.2 Traum do nervo cutaneo sensitivo nivel perna'),
  ('S847', 'Traumatismo de múltiplos nervos ao nível da perna', 'S84.7 Traum de mult nervos ao nivel da perna'),
  ('S848', 'Traumatismo de outros nervos ao nível da perna', 'S84.8 Traum de outr nervos ao nivel da perna'),
  ('S849', 'Traumatismo de nervo não especificado ao nível da perna', 'S84.9 Traum de nervo NE ao nivel da perna'),
  ('S85', 'Traumatismo de vasos sangüíneos da perna', 'S85 Traum de vasos sanguineos da perna'),
  ('S850', 'Traumatismo da artéria poplítea', 'S85.0 Traum da arteria poplitea'),
  ('S851', 'Traumatismo da artéria tibial (anterior) (posterior)', 'S85.1 Traum da arteria tibial'),
  ('S852', 'Traumatismo da artéria peronial', 'S85.2 Traum da arteria peronial'),
  ('S853', 'Traumatismo da veia grande safena ao nível da perna', 'S85.3 Traum da veia grande safena ao nivel perna'),
  ('S854', 'Traumatismo da veia safena menor ao nível da perna', 'S85.4 Traum da veia safena menor ao nivel da perna'),
  ('S855', 'Traumatismo da veia poplítea', 'S85.5 Traum da veia poplitea'),
  ('S857', 'Traumatismo de múltiplos vasos sangüíneos ao nível da perna', 'S85.7 Traum de mult vasos sanguineos nivel perna'),
  ('S858', 'Traumatismo de outros vasos sangüíneos ao nível da perna', 'S85.8 Traum de outr vasos sanguineos nivel perna'),
  ('S859', 'Traumatismo de vasos sangüíneos não especificados ao nível da perna', 'S85.9 Traum de vasos sanguineos NE ao nivel perna'),
  ('S86', 'Traumatismos de músculo e de tendão ao nível da perna', 'S86 Traum de musculo e de tendao ao nivel perna'),
  ('S860', 'Traumatismo do tendão de Aquiles', 'S86.0 Traum do tendao de Aquiles'),
  ('S861', 'Traumatismo de outro(s) músculo(s) e tendão(ões) do grupo muscular posterior ao nível da perna', 'S86.1 Traum outr musc tend grup musc post niv pern'),
  ('S862', 'Traumatismo do(s) músculo(s) e tendão(ões) do grupo muscular anterior ao nível da perna', 'S86.2 Traum musc tend grupo musc ant nivel perna'),
  ('S863', 'Traumatismo do(s) músculo(s) e tendão(ões) do grupo muscular peronial ao nível da perna', 'S86.3 Traum musc tend grupo musc peron nivel perna'),
  ('S867', 'Traumatismo de múltiplos músculos e tendões ao nível da perna', 'S86.7 Traum de mult musculos e tendoes nivel perna'),
  ('S868', 'Traumatismos de outros músculos e tendões ao nível da perna', 'S86.8 Traum de outr musculos e tendoes nivel perna'),
  ('S869', 'Traumatismo de músculo e de tendão não especificado ao nível da perna', 'S86.9 Traum de musculo e de tendao NE nivel perna'),
  ('S87', 'Traumatismo por esmagamento da perna', 'S87 Traum p/esmag da perna'),
  ('S870', 'Traumatismo por esmagamento do joelho', 'S87.0 Traum p/esmag do joelho'),
  ('S878', 'Traumatismo por esmagamento de outra parte e de partes não especificadas da perna', 'S87.8 Traum p/esmag outr parte e partes NE perna'),
  ('S88', 'Amputação traumática da perna', 'S88 Amput traum da perna'),
  ('S880', 'Amputação traumática ao nível do joelho', 'S88.0 Amput traum ao nivel do joelho'),
  ('S881', 'Amputação traumática entre o joelho e o tornozelo', 'S88.1 Amput traum entre o joelho e o tornozelo'),
  ('S889', 'Amputação traumática da perna ao nível não especificado', 'S88.9 Amput traum da perna ao nivel NE'),
  ('S89', 'Outros traumatismos e os não especificados da perna', 'S89 Outr traum e os NE da perna'),
  ('S890', 'Traumatismos múltiplos da perna', 'S89.0 Traum mult da perna'),
  ('S898', 'Outros traumatismos especificados da perna', 'S89.8 Outr traum espec da perna'),
  ('S899', 'Traumatismo não especificado da perna', 'S89.9 Traum NE da perna'),
  ('S90', 'Traumatismo superficial do tornozelo e do pé', 'S90 Traum superf do tornozelo e do pe'),
  ('S900', 'Contusão do tornozelo', 'S90.0 Contusao do tornozelo'),
  ('S901', 'Contusão de artelho sem lesão da unha', 'S90.1 Contusao de artelho s/lesao da unha'),
  ('S902', 'Contusão de artelho(s) com lesão da unha', 'S90.2 Contusao de artelho c/lesao da unha'),
  ('S903', 'Contusão de outras partes e partes não especificadas do pé', 'S90.3 Contusao de outr partes e partes NE do pe'),
  ('S907', 'Traumatismos superficiais múltiplos do tornozelo e do pé', 'S90.7 Traum superf mult do tornozelo e do pe'),
  ('S908', 'Outros traumatismos superficiais do tornozelo e do pé', 'S90.8 Outr traum superf do tornozelo e do pe'),
  ('S909', 'Traumatismo superficial do tornozelo e do pé, não especificado', 'S90.9 Traum superf do tornozelo e do pe NE'),
  ('S91', 'Ferimentos do tornozelo e do pé', 'S91 Ferim do tornozelo e do pe'),
  ('S910', 'Ferimento do tornozelo', 'S91.0 Ferim do tornozelo'),
  ('S911', 'Ferimento do(s) artelho(s) sem lesão da unha', 'S91.1 Ferim de artelhos s/lesao da unha'),
  ('S912', 'Ferimento do(s) artelho(s) com lesão da unha', 'S91.2 Ferim de artelhos c/lesao da unha'),
  ('S913', 'Ferimento de outras partes do pé', 'S91.3 Ferim de outr partes do pe'),
  ('S917', 'Ferimentos múltiplos do tornozelo e do pé', 'S91.7 Ferim mult do tornozelo e do pe'),
  ('S92', 'Fratura do pé (exceto do tornozelo)', 'S92 Frat do pe'),
  ('S920', 'Fratura do calcâneo', 'S92.0 Frat do calcaneo'),
  ('S921', 'Fratura do astrágalo', 'S92.1 Frat do astragalo'),
  ('S922', 'Fratura de outros ossos do tarso', 'S92.2 Frat de outr ossos do tarso'),
  ('S923', 'Fratura de ossos do metatarso', 'S92.3 Frat de ossos do metatarso'),
  ('S924', 'Fratura do hálux', 'S92.4 Frat do halux'),
  ('S925', 'Fratura de outro artelho', 'S92.5 Frat de outr artelho'),
  ('S927', 'Fraturas múltiplas do pé', 'S92.7 Frat mult do pe'),
  ('S929', 'Fratura do pé não especificada', 'S92.9 Frat do pe NE'),
  ('S93', 'Luxação, entorse e distensão das articulações e dos ligamentos ao nível do tornozelo e do pé', 'S93 Luxac entors distens artic lig niv tornoz pe'),
  ('S930', 'Luxação da articulação do tornozelo', 'S93.0 Luxacao da articulacao do tornozelo'),
  ('S931', 'Luxação do(s) artelho(s)', 'S93.1 Luxacao de artelhos'),
  ('S932', 'Ruptura de ligamentos ao nível do tornozelo e do pé', 'S93.2 Ruptura de ligamentos nivel tornozelo e pe'),
  ('S933', 'Luxação de outras partes e das não especificadas do pé', 'S93.3 Luxacao de outr partes e das NE do pe'),
  ('S934', 'Entorse e distensão do tornozelo', 'S93.4 Entorse e distensao do tornozelo'),
  ('S935', 'Entorse e distensão do(s) artelho(s)', 'S93.5 Entorse e distensao de artelhos'),
  ('S936', 'Entorse e distensão de outras partes e de partes não especificadas do pé', 'S93.6 Entorse distensao outr partes e partes NE pe'),
  ('S94', 'Traumatismo dos nervos ao nível do tornozelo e do pé', 'S94 Traum dos nervos ao nivel do tornozelo e pe'),
  ('S940', 'Traumatismo do nervo plantar externo (lateral)', 'S94.0 Traum do nervo plantar externo'),
  ('S941', 'Traumatismo do nervo plantar interno (medial)', 'S94.1 Traum do nervo plantar interno'),
  ('S942', 'Traumatismo nervo peronial (fibular) profundo ao nível do tornozelo e do pé', 'S94.2 Traum nervo peronial prof niv tornozelo e pe'),
  ('S943', 'Traumatismo do nervo sensitivo cutâneo ao nível do tornozelo e do pé', 'S94.3 Traum nervo sensit cutaneo niv tornozelo pe'),
  ('S947', 'Traumatismo de múltiplos nervos ao nível do tornozelo e do pé', 'S94.7 Traum de mult nervos ao nivel tornozelo e pe'),
  ('S948', 'Traumatismo de outros nervos ao nível do tornozelo e do pé', 'S94.8 Traum de outr nervos ao nivel tornozelo e pe'),
  ('S949', 'Traumatismo de nervo não especificado, ao nível do tornozelo e do pé', 'S94.9 Traum de nervo NE ao nivel do tornozelo e pe'),
  ('S95', 'Traumatismo de vasos sangüíneos ao nível do tornozelo e do pé', 'S95 Traum vasos sanguineos nivel tornozelo e pe'),
  ('S950', 'Traumatismo da artéria dorsal do pé', 'S95.0 Traum da arteria dorsal do pe'),
  ('S951', 'Traumatismo da artéria plantar do pé', 'S95.1 Traum da arteria plantar do pe'),
  ('S952', 'Traumatismo da veia dorsal do pé', 'S95.2 Traum da veia dorsal do pe'),
  ('S957', 'Traumatismo de múltiplos vasos sangüíneos ao nível do tornozelo e do pé', 'S95.7 Traum mult vasos sang nivel tornozelo e pe'),
  ('S958', 'Traumatismo de outros vasos sangüíneos ao nível do tornozelo e do pé', 'S95.8 Traum outr vasos sang nivel tornozelo e pe'),
  ('S959', 'Traumatismo de vaso sangüíneo não especificado ao nível do tornozelo e do pé', 'S95.9 Traum vaso sanguineo NE nivel tornozelo e pe'),
  ('S96', 'Traumatismos do músculo e tendão ao nível do tornozelo e do pé', 'S96 Traum musculo e tendao nivel tornozelo e pe'),
  ('S960', 'Traumatismo do músculo e tendão do músculo flexor longo do(s) artelho(s) ao nível do tornozelo e do pé', 'S96.0 Traum musc tend musc flex long artel torn pe'),
  ('S961', 'Traumatismo do músculo e tendão do extensor longo do(s) artelho(s) ao nível do tornozelo e do pé', 'S96.1 Traum musc tend exten long artel niv torn pe'),
  ('S962', 'Traumatismo de músculo intrínseco e tendão ao nível do tornozelo e do pé', 'S96.2 Traum musc intrinseco tendao nivel tornoz pe'),
  ('S967', 'Traumatismo de múltiplos músculos e tendões ao nível do tornozelo e do pé', 'S96.7 Traum mult musc tendoes nivel tornozelo e pe'),
  ('S968', 'Traumatismo de outros tendões e músculos ao nível do tornozelo e do pé', 'S96.8 Traum outr tendoes e musc niv tornozelo e pe'),
  ('S969', 'Traumatismo de músculo e tendão não especificados do tornozelo e do pé', 'S96.9 Traum de musculo e tendao NE tornozelo e pe'),
  ('S97', 'Lesão por esmagamento do tornozelo e do pé', 'S97 Lesao p/esmag do tornozelo e do pe'),
  ('S970', 'Lesão por esmagamento do tornozelo', 'S97.0 Lesao p/esmag do tornozelo'),
  ('S971', 'Lesão por esmagamento do(s) artelho(s)', 'S97.1 Lesao p/esmag de artelhos'),
  ('S978', 'Lesão por esmagamento de outras partes do tornozelo e do pé', 'S97.8 Lesao p/esmag outr partes do tornozelo e pe'),
  ('S98', 'Amputação traumática do tornozelo e do pé', 'S98 Amput traum do tornozelo e do pe'),
  ('S980', 'Amputação traumática do pé ao nível do tornozelo', 'S98.0 Amput traum do pe ao nivel do tornozelo'),
  ('S981', 'Amputação traumática de apenas um artelho', 'S98.1 Amput traum de apenas um artelho'),
  ('S982', 'Amputação traumática de dois ou mais artelhos', 'S98.2 Amput traum de dois ou mais artelhos'),
  ('S983', 'Amputação traumática de outras partes do pé', 'S98.3 Amput traum de outr partes do pe'),
  ('S984', 'Amputação traumática do pé ao nível não especificado', 'S98.4 Amput traum do pe ao nivel NE'),
  ('S99', 'Outros traumatismos e os não especificados do tornozelo e do pé', 'S99 Outr traum e os NE do tornozelo e do pe'),
  ('S997', 'Traumatismos múltiplos do tornozelo e do pé', 'S99.7 Traum mult do tornozelo e do pe'),
  ('S998', 'Outros traumatismos especificados do tornozelo e do pé', 'S99.8 Outr traum espec do tornozelo e do pe'),
  ('S999', 'Traumatismos não especificados do tornozelo e do pé', 'S99.9 Traum NE do tornozelo e do pe');
