INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('T00', 'Traumatismos superficiais envolvendo múltiplas regiões do corpo', 'T00 Traum superf envolv mult regioes corpo'),
  ('T000', 'Traumatismos superficiais envolvendo a cabeça com o pescoço', 'T00.0 Traum superf envolv a cabeca c/o pescoco'),
  ('T001', 'Traumatismos superficiais envolvendo o tórax com o abdome, parte inferior do dorso e da pelve', 'T00.1 Traum super env torax abd part inf dors pelv'),
  ('T002', 'Traumatismos superficiais envolvendo regiões múltiplas do(s) membro(s) superior(es)', 'T00.2 Traum superf envolv reg mult membros super'),
  ('T003', 'Traumatismos superficiais envolvendo regiões múltiplas do(s) membro(s) inferior(es)', 'T00.3 Traum superf envolv reg mult membros infer'),
  ('T006', 'Traumatismos superficiais envolvendo regiões múltiplas dos membros superiores com membro(s) inferiores', 'T00.6 Traum superf envolv reg mult membr sup infer'),
  ('T008', 'Traumatismos superficiais envolvendo outras combinações de regiões do corpo', 'T00.8 Traum superf envolv outr comb regioes corpo'),
  ('T009', 'Traumatismos superficiais múltiplos não especificados', 'T00.9 Traum superf mult NE'),
  ('T01', 'Ferimentos envolvendo múltiplas regiões do corpo', 'T01 Ferim envolv mult regioes do corpo'),
  ('T010', 'Ferimentos envolvendo a cabeça com o pescoço', 'T01.0 Ferim envolv a cabeca c/o pescoco'),
  ('T011', 'Ferimentos envolvendo o tórax com o abdome, parte inferior do dorso e da pelve', 'T01.1 Ferim envolv torax abd part inf dorso pelve'),
  ('T012', 'Ferimentos envolvendo regiões múltiplas do(s) membro(s) superior(es)', 'T01.2 Ferim envolv regioes mult de membros super'),
  ('T013', 'Ferimentos envolvendo múltiplas regiões do(s) membro(s) inferior(es)', 'T01.3 Ferim envolv mult regioes de membros infer'),
  ('T016', 'Ferimentos envolvendo regiões múltiplas do(s) membro(s) superior(es) com membro(s) inferior(es)', 'T01.6 Ferim envolv regi mult membr super membr inf'),
  ('T018', 'Ferimentos envolvendo outras combinações de regiões do corpo', 'T01.8 Ferim envolv outr combinacoes regioes corpo'),
  ('T019', 'Ferimentos múltiplos não especificados', 'T01.9 Ferim mult NE'),
  ('T02', 'Fraturas envolvendo múltiplas regiões do corpo', 'T02 Frat envolv mult regioes do corpo'),
  ('T020', 'Fraturas envolvendo cabeça com pescoço', 'T02.0 Frat envolv cabeca c/pescoco'),
  ('T021', 'Fraturas envolvendo tórax com parte inferior do dorso e da pelve', 'T02.1 Frat envolv torax c/parte inf dorso e pelve'),
  ('T022', 'Fraturas envolvendo regiões múltiplas de um membro superior', 'T02.2 Frat envolv regioes mult de um membro super'),
  ('T023', 'Fraturas envolvendo regiões múltiplas de um membro inferior', 'T02.3 Frat envolv regioes mult de um membro infer'),
  ('T024', 'Fraturas envolvendo regiões múltiplas de ambos os membros superiores', 'T02.4 Frat envolv regioes mult ambos membros super'),
  ('T025', 'Fraturas envolvendo regiões múltiplas de ambos os membros inferiores', 'T02.5 Frat envolv regioes mult ambos membros infer'),
  ('T026', 'Fraturas envolvendo regiões múltiplas do(s) membro(s) superior(es) com inferior(es)', 'T02.6 Frat envolv regioes mult membros sup c/infer'),
  ('T027', 'Fraturas envolvendo tórax com parte inferior do dorso e pelve com membro(s)', 'T02.7 Frat envolv torax part inf dorso pelve membr'),
  ('T028', 'Fraturas envolvendo outras combinações de regiões do corpo', 'T02.8 Frat envolv outr combinacoes regioes corpo'),
  ('T029', 'Fraturas múltiplas não especificadas', 'T02.9 Frat mult NE'),
  ('T03', 'Luxações, entorses e distensões envolvendo regiões múltiplas do corpo', 'T03 Luxac entors distens envolv reg mult corpo'),
  ('T030', 'Luxações, entorses e distensões envolvendo a cabeça com o pescoço', 'T03.0 Luxac entors distens envolv cabeca pescoco'),
  ('T031', 'Luxações, entorses e distensões envolvendo tórax com parte inferior do dorso e da pelve', 'T03.1 Lux entor dist env torax part inf dors pelv'),
  ('T032', 'Luxações, entorses e distensões envolvendo regiões múltiplas de membro(s) superior(es)', 'T03.2 Luxac entors dist envolv reg mult membr sup'),
  ('T033', 'Luxações, entorses e distensões envolvendo regiões múltiplas do(s) membro(s) inferior(es)', 'T03.3 Luxac entors dist envolv reg mult membr inf'),
  ('T034', 'Luxações, entorses e distensões envolvendo regiões múltiplas dos membros superiores com inferiores', 'T03.4 Luxac entors dist env reg mult membr sup inf'),
  ('T038', 'Luxações, entorses e distensões envolvendo outras combinações de regiões do corpo', 'T03.8 Luxac entors distens env outr comb reg corpo'),
  ('T039', 'Luxações, entorses e distensões múltiplas, não especificadas', 'T03.9 Luxacoes entorses e distensoes mult NE'),
  ('T04', 'Traumatismos por esmagamento envolvendo múltiplas regiões do corpo', 'T04 Traum p/esmag envolv mult regioes do corpo'),
  ('T040', 'Traumatismos por esmagamento envolvendo a cabeça com o pescoço', 'T04.0 Traum p/esmag envolv a cabeca c/o pescoco'),
  ('T041', 'Traumatismos por esmagamento envolvendo tórax com o abdome, parte inferior do dorso e da pelve', 'T04.1 Traum p/esm env torax abd part inf dors pelv'),
  ('T042', 'Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) superior(es)', 'T04.2 Traum p/esmag envolv regioes mult membr sup'),
  ('T043', 'Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) inferior(es)', 'T04.3 Traum p/esmag envolv regioes mult membr inf'),
  ('T044', 'Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) superior(es) com inferior(es)', 'T04.4 Traum p/esmag env regioes mult membr sup inf'),
  ('T047', 'Traumatismo por esmagamento do tórax com abdome, parte inferior do dorso, pelve e membro(s)', 'T04.7 Traum esm torax abd part inf dors pelv membr'),
  ('T048', 'Traumatismos por esmagamento envolvendo outras combinações de regiões do corpo', 'T04.8 Traum p/esmag envolv outr comb regioes corpo'),
  ('T049', 'Traumatismo múltiplos por esmagamento não especificados', 'T04.9 Traum mult p/esmag NE'),
  ('T05', 'Amputações traumáticas envolvendo múltiplas regiões do corpo', 'T05 Amput traum envolv mult regioes do corpo'),
  ('T050', 'Amputação traumática de ambas as mãos', 'T05.0 Amput traum de ambas as maos'),
  ('T051', 'Amputação traumática de uma mão e de um outro braço (qualquer nível, exceto mão)', 'T05.1 Amput traum de uma mao e de um outr braco'),
  ('T052', 'Amputação traumática de ambos os braços (qualquer nível)', 'T05.2 Amput traum de ambos os bracos'),
  ('T053', 'Amputação traumática de ambos os pés', 'T05.3 Amput traum de ambos os pes'),
  ('T054', 'Amputação traumática de um pé e outra perna (qualquer nível, exceto pé)', 'T05.4 Amput traum de um pe e outr perna'),
  ('T055', 'Amputação traumática de ambas as pernas (qualquer nível)', 'T05.5 Amput traum de ambas as pernas'),
  ('T056', 'Amputação traumática de membros superiores e inferiores, qualquer combinação (qualquer nível)', 'T05.6 Amput traum de membros super infer qq comb'),
  ('T058', 'Amputações traumáticas envolvendo outras combinações de regiões do corpo', 'T05.8 Amput traum envolv outr comb regioes corpo'),
  ('T059', 'Amputações traumáticas múltiplas não especificadas', 'T05.9 Amput traum mult NE'),
  ('T06', 'Outros traumatismos envolvendo regiões múltiplas do corpo, não classificados em outra parte', 'T06 Outr traum envolv regioes mult do corpo NCOP'),
  ('T060', 'Traumatismos de cérebro e nervos cranianos com traumatismos de nervos e da medula espinhal ao nível do pescoço', 'T06.0 Traum cer nerv cran nerv med espinh niv pesc'),
  ('T061', 'Traumatismos de nervos e da medula espinhal envolvendo outras regiões múltiplas do corpo', 'T06.1 Traum nerv med espinh env outr reg mult corp'),
  ('T062', 'Traumatismos de nervos envolvendo regiões múltiplas do corpo', 'T06.2 Traum de nervos envolv regioes mult do corpo'),
  ('T063', 'Traumatismos de vasos sangüíneos envolvendo regiões múltiplas do corpo', 'T06.3 Traum vasos sang envolv regioes mult corpo'),
  ('T064', 'Traumatismos de músculos e de tendões envolvendo regiões múltiplas do corpo', 'T06.4 Traum musculos tendoes envolv reg mult corpo'),
  ('T065', 'Traumatismos de órgãos intratorácicos com órgãos intra-abdominais e pélvicos', 'T06.5 Traum org intratorac c/intra-abdom pelvicos'),
  ('T068', 'Outros traumatismos especificados envolvendo regiões múltiplas do corpo', 'T06.8 Outr traum espec envolv regioes mult corpo'),
  ('T07', 'Traumatismos múltiplos não especificados', 'T07 Traum mult NE'),
  ('T07', 'Traumatismos múltiplos não especificados', 'T07 Traum mult NE'),
  ('T08', 'Fratura da coluna, nível não especificado', 'T08 Frat da coluna nivel NE'),
  ('T08', 'Fratura da coluna, nível não especificado', 'T08 Frat da coluna nivel NE'),
  ('T09', 'Outros traumatismos de coluna e tronco, nível não especificado', 'T09 Outr traum de coluna e tronco nivel NE'),
  ('T090', 'Traumatismo superficial do tronco, nível não especificado', 'T09.0 Traum superf do tronco nivel NE'),
  ('T091', 'Ferimento do tronco, nível não especificado', 'T09.1 Ferim do tronco nivel NE'),
  ('T092', 'Luxação, entorse e distensão de articulações e ligamentos não especificados do tronco', 'T09.2 Luxacao entorse distens artic lig NE tronco'),
  ('T093', 'Traumatismo de medula espinhal, nível não especificado', 'T09.3 Traum de medula espinhal nivel NE'),
  ('T094', 'Traumatismo de nervos, de raízes de nervos espinhais e de plexos não especificados do tronco', 'T09.4 Traum nerv raiz nerv espinh plexos NE tronco'),
  ('T095', 'Traumatismo de músculo e tendão não especificados do tronco', 'T09.5 Traum de musculo e tendao NE do tronco'),
  ('T096', 'Amputação traumática do tronco, nível não especificado', 'T09.6 Amput traum do tronco nivel NE'),
  ('T098', 'Outros traumatismos especificados do tronco, nível não especificado', 'T09.8 Outr traum espec do tronco nivel NE'),
  ('T099', 'Traumatismo não especificado do tronco, nível não especificado', 'T09.9 Traum NE do tronco nivel NE'),
  ('T10', 'Fratura do membro superior, nível não especificado', 'T10 Frat do membro super nivel NE'),
  ('T10', 'Fratura do membro superior, nível não especificado', 'T10 Frat do membro super nivel NE'),
  ('T11', 'Outros traumatismos de membro superior, nível não especificado', 'T11 Outr traum de membro super nivel NE'),
  ('T110', 'Traumatismo superficial do membro superior, nível não especificado', 'T11.0 Traum superf do membro super nivel NE'),
  ('T111', 'Ferimento do membro superior, nível não especificado', 'T11.1 Ferim do membro super nivel NE'),
  ('T112', 'Luxação, entorse e distensão de articulação e ligamento não especificados do membro superior, nível não especificado', 'T11.2 Lux entor dist artic lig NE membr sup niv NE'),
  ('T113', 'Traumatismo de nervo não especificado do membro superior, nível não especificado', 'T11.3 Traum de nervo NE do membro super nivel NE'),
  ('T114', 'Traumatismo de vaso sangüíneo não especificado, do membro superior, nível não especificado', 'T11.4 Traum vaso sanguineo NE membro sup nivel NE'),
  ('T115', 'Traumatismo de músculo e tendão não especificado do membro superior, nível não especificado', 'T11.5 Traum musculo e tendao NE membr sup nivel NE'),
  ('T116', 'Amputação traumática do membro superior, nível não especificado', 'T11.6 Amput traum do membro super nivel NE'),
  ('T118', 'Outros traumatismos especificados do membro superior nível não especificado', 'T11.8 Outr traum espec do membro super nivel NE'),
  ('T119', 'Traumatismo não especificado do membro superior nível não especificado', 'T11.9 Traum NE do membro super nivel NE'),
  ('T12', 'Fratura do membro inferior, nível não especificado', 'T12 Frat do membro infer nivel NE'),
  ('T12', 'Fratura do membro inferior, nível não especificado', 'T12 Frat do membro infer nivel NE'),
  ('T13', 'Outros traumatismos de membro inferior, nível não especificado', 'T13 Outr traum de membro infer nivel NE'),
  ('T130', 'Traumatismo superficial de membro inferior, nível não especificado', 'T13.0 Traum superf de membro infer nivel NE'),
  ('T131', 'Ferimento de membro inferior, nível não especificado', 'T13.1 Ferim de membro infer nivel NE'),
  ('T132', 'Luxação, entorse e distensão de articulação e ligamento não especificados de membro inferior, nível não especificado', 'T13.2 Lux entor dist artic lig NE membr inf niv NE'),
  ('T133', 'Traumatismo de nervo não especificado de membro inferior, nível não especificado', 'T13.3 Traum de nervo NE de membro infer nivel NE'),
  ('T134', 'Traumatismo de vaso sangüíneo não especificado de membro inferior, nível não especificado', 'T13.4 Traum vaso sang NE membro infer nivel NE'),
  ('T135', 'Traumatismo de músculo e tendão não especificado de membro inferior, nível não especificado', 'T13.5 Traum musculo tendao NE membro inf nivel NE'),
  ('T136', 'Amputação traumática de membro inferior, nível não especificado', 'T13.6 Amput traum de membro infer nivel NE'),
  ('T138', 'Outros traumatismos especificados de membro inferior, nível não especificado', 'T13.8 Outr traum espec de membro infer nivel NE'),
  ('T139', 'Traumatismo não especificado do membro inferior, nível não especificado', 'T13.9 Traum NE do membro infer nivel NE'),
  ('T14', 'Traumatismo de região não especificada do corpo', 'T14 Traum de regiao NE do corpo'),
  ('T140', 'Traumatismo superficial de região não especificada do corpo', 'T14.0 Traum superf de regiao NE do corpo'),
  ('T141', 'Ferimento de região não especificada do corpo', 'T14.1 Ferim de regiao NE do corpo'),
  ('T142', 'Fratura de região não especificada do corpo', 'T14.2 Frat de regiao NE do corpo'),
  ('T143', 'Luxação, entorse e distensão de região não especificada do corpo', 'T14.3 Luxacao entorse e distensao regiao NE corpo'),
  ('T144', 'Traumatismo de nervo(s) de região não especificada do corpo', 'T14.4 Traum de nervos de regiao NE do corpo'),
  ('T145', 'Traumatismo de vaso(s) sangüíneo(s) de região não especificada do corpo', 'T14.5 Traum de vasos sanguineos de regiao NE corpo'),
  ('T146', 'Traumatismo de músculos e tendões de região não especificada do corpo', 'T14.6 Traum de musculos e tendoes regiao NE corpo'),
  ('T147', 'Traumatismo por esmagamento e amputação traumática de regiões não especificadas do corpo', 'T14.7 Traum p/esmag e amput traum regioes NE corpo'),
  ('T148', 'Outros traumatismos de região não especificada do corpo', 'T14.8 Outr traum de regiao NE do corpo'),
  ('T149', 'Traumatismo não especificado', 'T14.9 Traum NE'),
  ('T15', 'Corpo estranho na parte externa do olho', 'T15 Corpo estranho na parte externa do olho'),
  ('T150', 'Corpo estranho na córnea', 'T15.0 Corpo estranho na cornea'),
  ('T151', 'Corpo estranho no saco conjuntival', 'T15.1 Corpo estranho no saco conjuntival'),
  ('T158', 'Corpo estranho em outros locais e em locais múltiplos da parte externa do olho', 'T15.8 Corpo estranh outr loc mult part ext olho'),
  ('T159', 'Corpo estranho em parte não especificada da região externa do olho', 'T15.9 Corpo estranho parte NE regiao externa olho'),
  ('T16', 'Corpo estranho no ouvido', 'T16 Corpo estranho no ouvido'),
  ('T16', 'Corpo estranho no ouvido', 'T16 Corpo estranho no ouvido'),
  ('T17', 'Corpo estranho no trato respiratório', 'T17 Corpo estranho no trato respirat'),
  ('T170', 'Corpo estranho no seio nasal', 'T17.0 Corpo estranho no seio nasal'),
  ('T171', 'Corpo estranho na narina', 'T17.1 Corpo estranho na narina'),
  ('T172', 'Corpo estranho na faringe', 'T17.2 Corpo estranho na faringe'),
  ('T173', 'Corpo estranho na laringe', 'T17.3 Corpo estranho na laringe'),
  ('T174', 'Corpo estranho na traquéia', 'T17.4 Corpo estranho na traqueia'),
  ('T175', 'Corpo estranho no brônquio', 'T17.5 Corpo estranho no bronquio'),
  ('T178', 'Corpo estranho em outras partes e partes múltiplas do trato respiratório', 'T17.8 Corpo estranho outr partes mult trato resp'),
  ('T179', 'Corpo estranho no trato respiratório, parte não especificada', 'T17.9 Corpo estranho no trato respirat parte NE'),
  ('T18', 'Corpo estranho no aparelho digestivo', 'T18 Corpo estranho no aparelho digestivo'),
  ('T180', 'Corpo estranho na boca', 'T18.0 Corpo estranho na boca'),
  ('T181', 'Corpo estranho no esôfago', 'T18.1 Corpo estranho no esofago'),
  ('T182', 'Corpo estranho no estômago', 'T18.2 Corpo estranho no estomago'),
  ('T183', 'Corpo estranho no intestino delgado', 'T18.3 Corpo estranho no intestino delgado'),
  ('T184', 'Corpo estranho no cólon', 'T18.4 Corpo estranho no colon'),
  ('T185', 'Corpo estranho no ânus e reto', 'T18.5 Corpo estranho no anus e reto'),
  ('T188', 'Corpo estranho em outras partes e partes múltiplas do aparelho digestivo', 'T18.8 Corpo estranho outr partes mult ap digestivo'),
  ('T189', 'Corpo estranho em parte não especificada do aparelho digestivo', 'T18.9 Corpo estranho em parte NE ap digestivo'),
  ('T19', 'Corpo estranho no trato geniturinário', 'T19 Corpo estranho no trato geniturinario'),
  ('T190', 'Corpo estranho na uretra', 'T19.0 Corpo estranho na uretra'),
  ('T191', 'Corpo estranho na bexiga', 'T19.1 Corpo estranho na bexiga'),
  ('T192', 'Corpo estranho na vulva e vagina', 'T19.2 Corpo estranho na vulva e vagina'),
  ('T193', 'Corpo estranho no útero (qualquer parte)', 'T19.3 Corpo estranho no utero'),
  ('T198', 'Corpo estranho em outras partes e partes múltiplas do trato geniturinário', 'T19.8 Corpo estranho out part mult trat geniturin'),
  ('T199', 'Corpo estranho no trato geniturinário, parte não especificada', 'T19.9 Corpo estranho trato geniturinario parte NE'),
  ('T20', 'Queimadura e corrosão da cabeça e pescoço', 'T20 Queim e corrosao da cabeca e pescoco'),
  ('T200', 'Queimadura da cabeça e do pescoço, grau não especificado', 'T20.0 Queim da cabeca e do pescoco grau NE'),
  ('T201', 'Queimadura de primeiro grau da cabeça e do pescoço', 'T20.1 Queim de 1.grau da cabeca e pescoco'),
  ('T202', 'Queimadura de segundo grau da cabeça e do pescoço', 'T20.2 Queim de 2.grau da cabeca e do pescoco'),
  ('T203', 'Queimadura de terceiro grau da cabeça e do pescoço', 'T20.3 Queim de 3.grau da cabeca e pescoco'),
  ('T204', 'Corrosão da cabeça e do pescoço, grau não especificado', 'T20.4 Corrosao da cabeca e do pescoco grau NE'),
  ('T205', 'Corrosão de primeiro grau da cabeça e do pescoço', 'T20.5 Corrosao de 1.grau cabeca e pescoco'),
  ('T206', 'Corrosão de segundo grau da cabeça e do pescoço', 'T20.6 Corrosao de 2.grau cabeca e pescoco'),
  ('T207', 'Corrosão de terceiro grau da cabeça e do pescoço', 'T20.7 Corrosao de 3.grau cabeca e pescoco'),
  ('T21', 'Queimadura e corrosão do tronco', 'T21 Queim e corrosao do tronco'),
  ('T210', 'Queimadura do tronco, grau não especificado', 'T21.0 Queim do tronco grau NE'),
  ('T211', 'Queimadura de primeiro grau do tronco', 'T21.1 Queim de 1.grau do tronco'),
  ('T212', 'Queimadura de segundo grau do tronco', 'T21.2 Queim de 2.grau do tronco'),
  ('T213', 'Queimadura de terceiro grau do tronco', 'T21.3 Queim de 3.grau do tronco'),
  ('T214', 'Corrosão do tronco, grau não especificado', 'T21.4 Corrosao do tronco grau NE'),
  ('T215', 'Corrosão de primeiro grau do tronco', 'T21.5 Corrosao de 1.grau do tronco'),
  ('T216', 'Corrosão de segundo grau do tronco', 'T21.6 Corrosao de 2.grau do tronco'),
  ('T217', 'Corrosão de terceiro grau do tronco', 'T21.7 Corrosao de 3.grau do tronco'),
  ('T22', 'Queimadura e corrosão do ombro e membro superior, exceto punho e mão', 'T22 Queim corrosao ombro membr sup exc punho mao'),
  ('T220', 'Queimadura do ombro e do membro superior, exceto punho e mão, grau não especificado', 'T22.0 Queim ombro membr sup exc punho mao grau NE'),
  ('T221', 'Queimadura de primeiro grau do ombro e do membro superior, exceto punho e mão', 'T22.1 Queim 1.grau ombro membr sup exc punho e mao'),
  ('T222', 'Queimadura de segundo grau do ombro e do membro superior, exceto punho e mão', 'T22.2 Queim 2.grau ombro membr sup exc punho e mao'),
  ('T223', 'Queimadura de terceiro grau do ombro e do membro superior, exceto punho e mão', 'T22.3 Queim 3.grau ombro membr sup exc punho e mao'),
  ('T224', 'Corrosão do ombro e do membro superior, exceto punho e mão, grau não especificado', 'T22.4 Corros ombro membr sup exc punho mao grau NE'),
  ('T225', 'Corrosão de primeiro grau do ombro e do membro superior, exceto punho e mão', 'T22.5 Corrosao 1.grau ombr membr sup exc punho mao'),
  ('T226', 'Corrosão de segundo grau do ombro e do membro superior, exceto punho e mão', 'T22.6 Corrosao 2.grau ombr membr sup exc punho mao'),
  ('T227', 'Corrosão de terceiro grau do ombro e do membro superior, exceto punho e mão', 'T22.7 Corrosao 3.grau ombr membr sup exc punho mao'),
  ('T23', 'Queimadura e corrosão do punho e da mão', 'T23 Queim e corrosao do punho e da mao'),
  ('T230', 'Queimadura do punho e da mão, grau não especificado', 'T23.0 Queim do punho e da mao grau NE'),
  ('T231', 'Queimadura de primeiro grau do punho e da mão', 'T23.1 Queim de 1.grau do punho e da mao'),
  ('T232', 'Queimadura de segundo grau do punho e da mão', 'T23.2 Queim de 2.grau do punho e da mao'),
  ('T233', 'Queimadura de terceiro grau do punho e da mão', 'T23.3 Queim de 3.grau do punho e da mao'),
  ('T234', 'Corrosão do punho e da mão, grau não especificado', 'T23.4 Corrosao do punho e da mao grau NE'),
  ('T235', 'Corrosão de primeiro grau do punho e da mão', 'T23.5 Corrosao de 1.grau do punho e da mao'),
  ('T236', 'Corrosão de segundo grau do punho e da mão', 'T23.6 Corrosao de 2.grau do punho e da mao'),
  ('T237', 'Corrosão de terceiro grau do punho e da mão', 'T23.7 Corrosao de 3.grau do punho e da mao'),
  ('T24', 'Queimadura e corrosão do quadril e membro inferior, exceto tornozelo e do pé', 'T24 Queim corros quadr membro inf exc tornoz pe'),
  ('T240', 'Queimadura do quadril e membro inferior, exceto tornozelo e do pé, grau não especificado', 'T24.0 Queim quadr membr inf exc tornoz pe grau NE'),
  ('T241', 'Queimadura de primeiro grau do quadril e do membro inferior, exceto tornozelo e do pé', 'T24.1 Queim 1.grau quadr membr inf exc tornoz pe'),
  ('T242', 'Queimadura de segundo grau do quadril e do membro inferior, exceto tornozelo e do pé', 'T24.2 Queim 2.grau quadr membr inf exc tornoz pe'),
  ('T243', 'Queimadura de terceiro grau do quadril e do membro inferior, exceto tornozelo e do pé', 'T24.3 Queim 3.grau quadr membr inf exc tornoz pe'),
  ('T244', 'Corrosão do quadril e do membro inferior, exceto tornozelo e do pé, grau não especificado', 'T24.4 Corros quadr membr inf exc tornoz pe grau NE'),
  ('T245', 'Corrosão de primeiro grau do quadril e do membro inferior, exceto tornozelo e do pé', 'T24.5 Corros 1.grau quadr membr inf exc tornoz pe'),
  ('T246', 'Corrosão de segundo grau do quadril e do membro inferior, exceto tornozelo e do pé', 'T24.6 Corros 2.grau quadr membr inf exc tornoz pe'),
  ('T247', 'Corrosão de terceiro grau do quadril e do membro inferior, exceto tornozelo e do pé', 'T24.7 Corros 3.grau quadr membr inf exc tornoz pe'),
  ('T25', 'Queimadura e corrosão do tornozelo e do pé', 'T25 Queim e corrosao do tornozelo e do pe'),
  ('T250', 'Queimadura do tornozelo e do pé, grau não especificado', 'T25.0 Queim do tornozelo e do pe grau NE'),
  ('T251', 'Queimadura de primeiro grau do tornozelo e do pé', 'T25.1 Queim de 1.grau do tornozelo e do pe'),
  ('T252', 'Queimadura de segundo grau do tornozelo e do pé', 'T25.2 Queim de 2.grau do tornozelo e do pe'),
  ('T253', 'Queimadura de terceiro grau do tornozelo e do pé', 'T25.3 Queim de 3.grau do tornozelo e do pe'),
  ('T254', 'Corrosão do tornozelo e do pé, grau não especificado', 'T25.4 Corrosao do tornozelo e do pe grau NE'),
  ('T255', 'Corrosão de primeiro grau do tornozelo e do pé', 'T25.5 Corrosao de 1.grau do tornozelo e do pe'),
  ('T256', 'Corrosão de segundo grau do tornozelo e do pé', 'T25.6 Corrosao de 2.grau do tornozelo e do pe'),
  ('T257', 'Corrosão de terceiro grau do tornozelo e do pé', 'T25.7 Corrosao de 3.grau do tornozelo e do pe'),
  ('T26', 'Queimadura e corrosão limitadas ao olho e seus anexos', 'T26 Queim e corrosao limitadas ao olho e anexos'),
  ('T260', 'Queimadura da pálpebra e da região periocular', 'T26.0 Queim da palpebra e da regiao periocular'),
  ('T261', 'Queimadura da córnea e do saco conjuntival', 'T26.1 Queim da cornea e do saco conjuntival'),
  ('T262', 'Queimadura com resultante ruptura e destruição do globo ocular', 'T26.2 Queim c/result rupt e destruic globo ocular'),
  ('T263', 'Queimadura de outras partes do olho e anexos', 'T26.3 Queim de outr partes do olho e anexos'),
  ('T264', 'Queimadura do olho e anexos, parte não especificada', 'T26.4 Queim do olho e anexos parte NE'),
  ('T265', 'Corrosão da pálpebra e da região periocular', 'T26.5 Corrosao da palpebra e da regiao periocular'),
  ('T266', 'Corrosão da córnea e do saco conjuntival', 'T26.6 Corrosao da cornea e do saco conjuntival'),
  ('T267', 'Corrosão com resultante ruptura e destruição do globo ocular', 'T26.7 Corrosao c/result rupt destruic globo ocular'),
  ('T268', 'Corrosão de outras partes do olho e anexos', 'T26.8 Corrosao de outr partes do olho e anexos'),
  ('T269', 'Corrosão do olho e anexos, parte não especificada', 'T26.9 Corrosao do olho e anexos parte NE'),
  ('T27', 'Queimadura e corrosão do trato respiratório', 'T27 Queim e corrosao do trato respirat'),
  ('T270', 'Queimadura da laringe e traquéia', 'T27.0 Queim da laringe e traqueia'),
  ('T271', 'Queimadura da laringe, traquéia com pulmão', 'T27.1 Queim da laringe traqueia c/pulmao'),
  ('T272', 'Queimadura de outras partes do trato respiratório', 'T27.2 Queim de outr partes do trato respirat'),
  ('T273', 'Queimadura do trato respiratório, parte não especificada', 'T27.3 Queim do trato respirat parte NE'),
  ('T274', 'Corrosão da laringe e traquéia', 'T27.4 Corrosao da laringe e traqueia'),
  ('T275', 'Corrosão da laringe, traquéia com corrosão de pulmão', 'T27.5 Corrosao laringe traqueia c/corrosao pulmao'),
  ('T276', 'Corrosão de outras partes do trato respiratório', 'T27.6 Corrosao de outr partes do trato respirat'),
  ('T277', 'Corrosão do trato respiratório, parte não especificada', 'T27.7 Corrosao do trato respirat parte NE'),
  ('T28', 'Queimadura e corrosão de outros órgãos internos', 'T28 Queim e corrosao de outr orgaos internos'),
  ('T280', 'Queimadura da boca e da faringe', 'T28.0 Queim da boca e da faringe'),
  ('T281', 'Queimadura do esôfago', 'T28.1 Queim do esofago'),
  ('T282', 'Queimadura de outras partes do trato alimentar', 'T28.2 Queim de outr partes do trato alimentar'),
  ('T283', 'Queimadura dos órgãos geniturinários internos', 'T28.3 Queim dos orgaos geniturinarios internos'),
  ('T284', 'Queimadura de outros órgãos internos e dos não especificados', 'T28.4 Queim de outr orgaos internos e dos NE'),
  ('T285', 'Corrosão da boca e faringe', 'T28.5 Corrosao da boca e faringe'),
  ('T286', 'Corrosão do esôfago', 'T28.6 Corrosao do esofago'),
  ('T287', 'Corrosão de outras partes do trato alimentar', 'T28.7 Corrosao de outr partes do trato alimentar'),
  ('T288', 'Corrosão de órgãos geniturinários internos', 'T28.8 Corrosao de orgaos geniturinarios internos'),
  ('T289', 'Corrosão de outros órgãos internos e dos não especificados', 'T28.9 Corrosao de outr orgaos internos e dos NE'),
  ('T29', 'Queimaduras e corrosões de múltiplas regiões do corpo', 'T29 Queim e corrosoes de mult regioes do corpo'),
  ('T290', 'Queimaduras múltiplas, grau não especificado', 'T29.0 Queim mult grau NE'),
  ('T291', 'Queimaduras múltiplas, sem mencionar queimadura(s) ultrapassando o primeiro grau', 'T29.1 Queim mult s/menc queim ultrapass 1.grau'),
  ('T292', 'Queimaduras múltiplas, sem mencionar queimadura(s) ultrapassando o segundo grau', 'T29.2 Queim mult s/menc queim ultrapass 2.grau'),
  ('T293', 'Queimaduras múltiplas, mencionando ao menos uma queimadura de terceiro grau', 'T29.3 Queim mult menc ao menos uma queim de 3.grau'),
  ('T294', 'Corrosões múltiplas, grau não especificado', 'T29.4 Corrosoes mult grau NE'),
  ('T295', 'Corrosões múltiplas, sem mencionar corrosão(ões) ultrapassando o primeiro grau', 'T29.5 Corrosoes mult s/menc corros ultrapas 1.grau'),
  ('T296', 'Corrosões múltiplas, sem mencionar corrosão(ões) ultrapassando o segundo grau', 'T29.6 Corrosoes mult s/menc corros ultrapas 2.grau'),
  ('T297', 'Corrosões múltiplas, mencionado ao menos uma corrosão de terceiro grau', 'T29.7 Corrosoes mult menc ao menos corros 3.grau'),
  ('T30', 'Queimadura e corrosão, parte não especificada do corpo', 'T30 Queim e corrosao parte NE do corpo'),
  ('T300', 'Queimadura, parte do corpo não especificada, grau não especificado', 'T30.0 Queim parte do corpo NE grau NE'),
  ('T301', 'Queimadura de primeiro grau, parte do corpo não especificada', 'T30.1 Queim de 1.grau parte do corpo NE'),
  ('T302', 'Queimadura de segundo grau, parte do corpo não especificada', 'T30.2 Queim de 2.grau parte do corpo NE'),
  ('T303', 'Queimadura de terceiro grau, parte do corpo não especificada', 'T30.3 Queim de 3.grau parte do corpo NE'),
  ('T304', 'Corrosão, parte do corpo não especificada, grau não especificado', 'T30.4 Corrosao parte do corpo NE grau NE'),
  ('T305', 'Corrosão de primeiro grau, parte do corpo não especificada', 'T30.5 Corrosao de 1.grau parte do corpo NE'),
  ('T306', 'Corrosão de segundo grau, parte do corpo não especificada', 'T30.6 Corrosao de 2.grau parte do corpo NE'),
  ('T307', 'Corrosão de terceiro grau, parte do corpo não especificada', 'T30.7 Corrosao de 3.grau parte do corpo NE'),
  ('T31', 'Queimaduras classificadas segundo a extensão da superfície corporal atingida', 'T31 Queim classif seg ext superf corporal ating'),
  ('T310', 'Queimaduras envolvendo menos de 10% da superfície corporal', 'T31.0 Queim envolv menos de 10% da superf corporal'),
  ('T311', 'Queimaduras envolvendo de 10 - 19% da superfície corporal', 'T31.1 Queim envolv de 10-19% da superf corporal'),
  ('T312', 'Queimaduras envolvendo de 20 - 29% da superfície corporal', 'T31.2 Queim envolv de 20-29% da superf corporal'),
  ('T313', 'Queimaduras envolvendo de 30 - 39% da superfície corporal', 'T31.3 Queim envolv de 30-39% da superf corporal'),
  ('T314', 'Queimaduras envolvendo de 40 - 49% da superfície corporal', 'T31.4 Queim envolv de 40-49% da superf corporal'),
  ('T315', 'Queimaduras envolvendo de 50 - 59% da superfície corporal', 'T31.5 Queim envolv de 50-59% da superf corporal'),
  ('T316', 'Queimaduras envolvendo de 60 - 69% da superfície corporal', 'T31.6 Queim envolv de 60-69% da superf corporal'),
  ('T317', 'Queimaduras envolvendo de 70 - 79% da superfície corporal', 'T31.7 Queim envolv de 70-79% da superf corporal'),
  ('T318', 'Queimaduras envolvendo de 80 - 89% da superfície corporal', 'T31.8 Queim envolv de 80-89% da superf corporal'),
  ('T319', 'Queimaduras envolvendo 90% ou mais da superfície corporal', 'T31.9 Queim envolv 90% ou mais da superf corporal'),
  ('T32', 'Corrosões classificadas segundo a extensão da superfície corporal atingida', 'T32 Corrosoes classif seg ext superf corp ating'),
  ('T320', 'Corrosões envolvendo menos de 10% da superfície corporal', 'T32.0 Corrosoes envolv menos de 10% superf corp'),
  ('T321', 'Corrosões envolvendo 10 - 19% da superfície corporal', 'T32.1 Corrosoes envolv 10-19% da superf corporal'),
  ('T322', 'Corrosões envolvendo 20 - 29% da superfície corporal', 'T32.2 Corrosoes envolv 20-29% da superf corporal'),
  ('T323', 'Corrosões envolvendo 30 - 39% da superfície corporal', 'T32.3 Corrosoes envolv 30-39% da superf corporal'),
  ('T324', 'Corrosões envolvendo 40 - 49% da superfície corporal', 'T32.4 Corrosoes envolv 40-49% da superf corporal'),
  ('T325', 'Corrosões envolvendo 50 - 59% da superfície corporal', 'T32.5 Corrosoes envolv 50-59% da superf corporal'),
  ('T326', 'Corrosões envolvendo 60 - 69% da superfície corporal', 'T32.6 Corrosoes envolv 60-69% da superf corporal'),
  ('T327', 'Corrosões envolvendo 70 - 79% da superfície corporal', 'T32.7 Corrosoes envolv 70-79% da superf corporal'),
  ('T328', 'Corrosões envolvendo 80 - 89% da superfície corporal', 'T32.8 Corrosoes envolv 80-89% da superf corporal'),
  ('T329', 'Corrosões envolvendo 90% ou mais da superfície corporal', 'T32.9 Corrosoes envolv 90% ou mais superf corporal'),
  ('T33', 'Geladura superficial', 'T33 Geladura superf'),
  ('T330', 'Geladura superficial da cabeça', 'T33.0 Geladura superf da cabeca'),
  ('T331', 'Geladura superficial do pescoço', 'T33.1 Geladura superf do pescoco'),
  ('T332', 'Geladura superficial do tórax', 'T33.2 Geladura superf do torax'),
  ('T333', 'Geladura superficial da parede abdominal, parte inferior do dorso e da pelve', 'T33.3 Geladura superf pared abd part inf dors pelv'),
  ('T334', 'Geladura superficial do braço', 'T33.4 Geladura superf do braco'),
  ('T335', 'Geladura superficial do punho e da mão', 'T33.5 Geladura superf do punho e da mao'),
  ('T336', 'Geladura superficial do quadril e da coxa', 'T33.6 Geladura superf do quadril e da coxa'),
  ('T337', 'Geladura superficial do joelho e da perna', 'T33.7 Geladura superf do joelho e da perna'),
  ('T338', 'Geladura superficial do tornozelo e do pé', 'T33.8 Geladura superf do tornozelo e do pe'),
  ('T339', 'Geladura superficial de outros locais e de locais não especificados', 'T33.9 Geladura superf de outr locais e locais NE'),
  ('T34', 'Geladura com necrose de tecidos', 'T34 Geladura c/necrose de tec'),
  ('T340', 'Geladura, com necrose de tecidos, da cabeça', 'T34.0 Geladura c/necrose de tec da cabeca'),
  ('T341', 'Geladura, com necrose de tecidos, do pescoço', 'T34.1 Geladura c/necrose de tec do pescoco'),
  ('T342', 'Geladura, com necrose de tecidos, do tórax', 'T34.2 Geladura c/necrose de tec do torax'),
  ('T343', 'Geladura, com necrose de tecidos, da parede abdominal, parte inferior do dorso e da pelve', 'T34.3 Gelad necr tec pared abd part inf dors pelv'),
  ('T344', 'Geladura, com necrose de tecidos, do braço', 'T34.4 Geladura c/necrose de tec do braco'),
  ('T345', 'Geladura, com necrose de tecidos, do punho e da mão', 'T34.5 Geladura c/necrose de tec do punho e da mao'),
  ('T346', 'Geladura, com necrose de tecidos, do quadril e da coxa', 'T34.6 Geladura c/necrose de tec do quadril e coxa'),
  ('T347', 'Geladura, com necrose de tecidos, do joelho e da perna', 'T34.7 Geladura c/necrose de tec do joelho e perna'),
  ('T348', 'Geladura, com necrose de tecidos, do tornozelo e do pé', 'T34.8 Geladura c/necrose de tec do tornozelo e pe'),
  ('T349', 'Geladura, com necrose de tecidos, de localização não especificada', 'T34.9 Geladura c/necrose de tec de localiz NE'),
  ('T35', 'Geladura de múltiplas partes do corpo e das não especificadas', 'T35 Geladura de mult partes do corpo e das NE'),
  ('T350', 'Geladura superficial envolvendo múltiplas partes do corpo', 'T35.0 Geladura superf envolv mult partes do corpo'),
  ('T351', 'Geladura, com necrose de tecidos, de múltiplas partes do corpo', 'T35.1 Geladura c/necrose de tec mult partes corpo'),
  ('T352', 'Geladura, de grau não especificado, da cabeça e do pescoço', 'T35.2 Geladura de grau NE da cabeca e do pescoco'),
  ('T353', 'Geladura, de grau não especificado, do tórax, abdome, parte inferior do dorso e da pelve', 'T35.3 Gelad grau NE torax abd part inf dorso pelve'),
  ('T354', 'Geladura, de grau não especificado, do membro superior', 'T35.4 Geladura de grau NE do membro super'),
  ('T355', 'Geladura, de grau não especificado, do membro inferior', 'T35.5 Geladura de grau NE do membro infer'),
  ('T356', 'Geladura, de grau não especificado, de múltiplas partes do corpo', 'T35.6 Geladura de grau NE de mult partes do corpo'),
  ('T357', 'Geladura, de grau não especificado, de localização não especificada', 'T35.7 Geladura de grau NE de localiz NE'),
  ('T36', 'Intoxicação por antibióticos sistêmicos', 'T36 Intox p/antibioticos sistemicos'),
  ('T360', 'Intoxicação por penicilinas', 'T36.0 Penicilinas'),
  ('T361', 'Intoxicação por cefalosporinas e outras betalactaminas', 'T36.1 Cefalosporinas e outr betalactaminas'),
  ('T362', 'Intoxicação pelo grupo do cloranfenicol', 'T36.2 Grupo do cloranfenicol'),
  ('T363', 'Intoxicação por macrolídios', 'T36.3 Macrolidios'),
  ('T364', 'Intoxicação por tetraciclinas', 'T36.4 Tetraciclinas'),
  ('T365', 'Intoxicação por aminoglicosídeos', 'T36.5 Aminoglicosideos'),
  ('T366', 'Intoxicação por rifamicinas', 'T36.6 Rifamicinas'),
  ('T367', 'Intoxicação por antibióticos antifúngicos administrados por via sistêmica', 'T36.7 Antibioticos antifungicos admin p/via sistem'),
  ('T368', 'Intoxicação por outros antibióticos sistêmicos', 'T36.8 Outr antibioticos sistemicos'),
  ('T369', 'Intoxicação por antibióticos sistêmicos não especificados', 'T36.9 Antibioticos sistemicos NE'),
  ('T37', 'Intoxicação por outras substâncias antiinfecciosas ou antiparasitárias sistêmicas', 'T37 Intox outr subst antiinfecc antiparasit sist'),
  ('T370', 'Intoxicação por sulfonamidas', 'T37.0 Sulfonamidas'),
  ('T371', 'Intoxicação por drogas antimicobacterianas', 'T37.1 Drogas antimicobacterianas'),
  ('T372', 'Intoxicação por antimaláricos e drogas que atuam sobre outros protozoários do sangue', 'T37.2 Antimalaricos drog q atuam s/protoz sangue'),
  ('T373', 'Intoxicação por outros medicamentos antiprotozoários', 'T37.3 Outr medicamentos antiprotozoarios'),
  ('T374', 'Intoxicação por anti-helmínticos', 'T37.4 Anti-helminticos'),
  ('T375', 'Intoxicação por drogas antivirais', 'T37.5 Drogas antivirais'),
  ('T378', 'Intoxicação por outros agentes antiinfecciosos e antiparasitários especificados', 'T37.8 Outr agentes antiinfecc e antiparasit espec'),
  ('T379', 'Intoxicação por agentes antiinfecciosos e antiparasitários sistêmicos não especificados', 'T37.9 Agentes antiinfecc e antiparasit sistem NE'),
  ('T38', 'Intoxicação por hormônios, seus substitutos sintéticos e seus antagonistas não classificados em outra parte', 'T38 Intox p/hormonios seus subst sint antag NCOP'),
  ('T380', 'Intoxicação por glicocorticóides e análogos sintéticos', 'T38.0 Glicocorticoides e analogos sinteticos'),
  ('T381', 'Intoxicação por hormônios tireoidianos e seus derivados', 'T38.1 Hormonios tireoidianos e seus derivados'),
  ('T382', 'Intoxicação por medicamentos antitireoidianos', 'T38.2 Medicamentos antitireoidianos'),
  ('T383', 'Intoxicação por insulina e drogas hipoglicemiantes orais (antidiabéticos)', 'T38.3 Insulina e drogas hipoglicemiantes orais'),
  ('T384', 'Intoxicação por anticoncepcionais orais', 'T38.4 Anticoncepcionais orais'),
  ('T385', 'Intoxicação por outros estrógenos e progestágenos', 'T38.5 Outr estrogenos e progestagenos'),
  ('T386', 'Intoxicação por antigonadotrofinas, antiestrógenos, antiandrógenos não classificados em outra parte', 'T38.6 Antigonadotrofin antiestrog antiandrog NCOP'),
  ('T387', 'Intoxicação por andrógenos e anabolizantes congêneres', 'T38.7 Androgenos e anabolizantes congeneres'),
  ('T388', 'Intoxicação por outros hormônios e substitutos sintéticos, e os não especificados', 'T38.8 Outr hormonios e substitutos sinteticos e NE'),
  ('T389', 'Intoxicação por outros antagonistas hormonais, e os não especificados', 'T38.9 Outr antagonistas hormonais e os NE'),
  ('T39', 'Intoxicação por analgésicos, antipiréticos e anti-reumáticos não-opiáceos', 'T39 Intox analges antipiret anti-reumat n-opiac'),
  ('T390', 'Intoxicação por salicilatos', 'T39.0 Salicilatos'),
  ('T391', 'Intoxicação por derivados do 4-aminofenol', 'T39.1 Derivados do 4-aminofenol'),
  ('T392', 'Intoxicação por derivados pirazolônicos', 'T39.2 Derivados pirazolonicos'),
  ('T393', 'Intoxicação por outros antiinflamatórios não esteróides', 'T39.3 Outr antiinflamatorios nao esteroides'),
  ('T394', 'Intoxicação por anti-reumáticos não classificados em outra parte', 'T39.4 Anti-reumaticos NCOP'),
  ('T398', 'Intoxicação por outros analgésicos não opiáceos e antipiréticos não classificados em outra parte', 'T39.8 Outr analgesicos nao opiac e antipiret NCOP'),
  ('T399', 'Intoxicação por analgésico não-opiáceo, antipirético e anti-reumático, não especificados', 'T39.9 Analges n-opiaceo antipiret e anti-reumat NE'),
  ('T40', 'Intoxicação por narcóticos e psicodislépticos (alucinógenos)', 'T40 Intox p/narcoticos e psicodislepticos'),
  ('T400', 'Intoxicação por ópio', 'T40.0 Opio'),
  ('T401', 'Intoxicação por heroína', 'T40.1 Heroina'),
  ('T402', 'Intoxicação por outros opiáceos', 'T40.2 Outr opiaceos'),
  ('T403', 'Intoxicação por metadona', 'T40.3 Metadona'),
  ('T404', 'Intoxicação por outros narcóticos sintéticos', 'T40.4 Outr narcoticos sinteticos'),
  ('T405', 'Intoxicação por cocaína', 'T40.5 Cocaina'),
  ('T406', 'Intoxicação por outros narcóticos e os não especificados', 'T40.6 Outr narcoticos e os NE'),
  ('T407', 'Intoxicação por cannabis (derivados)', 'T40.7 Cannabis'),
  ('T408', 'Intoxicação por lisergida (LSD)', 'T40.8 Lisergida'),
  ('T409', 'Intoxicação por outros psicodislépticos e os não especificados (alucinógenos)', 'T40.9 Outr psicodislepticos e os NE'),
  ('T41', 'Intoxicação por anestésicos e gases terapêuticos', 'T41 Intox p/anestesicos e gases terapeuticos'),
  ('T410', 'Intoxicação por anestésicos inalatórios', 'T41.0 Anestesicos inalatorios'),
  ('T411', 'Intoxicação por anestésicos intravenosos', 'T41.1 Anestesicos intravenosos'),
  ('T412', 'Intoxicação por outros anestésicos gerais e os não especificados', 'T41.2 Outr anestesicos gerais e os NE'),
  ('T413', 'Intoxicação por anestésicos locais', 'T41.3 Anestesicos locais'),
  ('T414', 'Intoxicação por anestésico não especificado', 'T41.4 Anestesico NE'),
  ('T415', 'Intoxicação por gases terapêuticos', 'T41.5 Gases terapeuticos'),
  ('T42', 'Intoxicação por antiepilépticos, sedativos-hipnóticos e antiparkinsonianos', 'T42 Intox antiepilept sedativ-hipnot antiparkins'),
  ('T420', 'Intoxicação por derivados da hidantoína', 'T42.0 Derivados da hidantoina'),
  ('T421', 'Intoxicação por iminostilbenos', 'T42.1 Iminostilbenos'),
  ('T422', 'Intoxicação por succinimidas e oxazolidinadionas', 'T42.2 Succinimidas e oxazolidinadionas'),
  ('T423', 'Intoxicação por barbitúricos', 'T42.3 Barbituricos'),
  ('T424', 'Intoxicação por benzodiazepinas', 'T42.4 Benzodiazepinas'),
  ('T425', 'Intoxicação por antiepiléticos em associação, não classificados em outra parte', 'T42.5 Antiepileticos em associacao NCOP'),
  ('T426', 'Intoxicação por outras drogas antiepilépticas e sedativos-hipnóticos', 'T42.6 Outr drogas antiepilepticas sedativos-hipnot'),
  ('T427', 'Intoxicação por drogas antiepilépticos, sedativos-hipnóticos, não especificados', 'T42.7 Drogas antiepilepticos sedativos-hipnot NE'),
  ('T428', 'Intoxicação por drogas antiparkinsonianos e outros depressores centrais do tônus muscular', 'T42.8 Drog antipark outr depress centr tonus musc'),
  ('T43', 'Intoxicação por drogas psicotrópicas não classificadas em outra parte', 'T43 Intox p/drogas psicotropicas NCOP'),
  ('T430', 'Intoxicação por antidepressivos tricíclicos e tetracíclicos', 'T43.0 Antidepressivos triciclicos e tetraciclicos'),
  ('T431', 'Intoxicação por antidepressivos inibidores da monoaminooxidase (MAO)', 'T43.1 Antidepressivos inibidores monoaminooxidase'),
  ('T432', 'Intoxicação por outros antidepressivos e os não especificados', 'T43.2 Outr antidepressivos e os NE'),
  ('T433', 'Intoxicação por antipsicóticos e neurolépticos derivados da fenotiazina', 'T43.3 Antipsicoticos neurolept deriv fenotiazina'),
  ('T434', 'Intoxicação por neurolépticos do tipo butirofenona e tioxanteno', 'T43.4 Neurolepticos tipo butirofenona e tioxanteno'),
  ('T435', 'Intoxicação por outros antipsicóticos e neurolépticos e os não especificados', 'T43.5 Outr antipsicoticos e neurolepticos e os NE'),
  ('T436', 'Intoxicação por psicoestimulantes que potencialmente podem provocar dependência', 'T43.6 Psicoestimul que potenc podem prov depend'),
  ('T438', 'Intoxicação por outras drogas psicotrópicas não classificadas em outra parte', 'T43.8 Outr drogas psicotropicas NCOP'),
  ('T439', 'Intoxicação por droga psicotrópica não especificada', 'T43.9 Droga psicotropica NE'),
  ('T44', 'Intoxicação por drogas que afetam principalmente o sistema nervoso autônomo', 'T44 Intox p/drog q afet princ sist nerv autonomo'),
  ('T440', 'Intoxicação por agentes anticolinesterase', 'T44.0 Agentes anticolinesterase'),
  ('T441', 'Intoxicação por outros agentes parassimpaticomiméticos (colinérgicos)', 'T44.1 Outr agentes parassimpaticomimeticos'),
  ('T442', 'Intoxicação por bloqueadores ganglionares não classificados em outra parte', 'T44.2 Bloqueadores ganglionares NCOP'),
  ('T443', 'Intoxicação por outros parassimpaticolíticos (anticolinérgicos e antimuscarínicos) e espasmolíticos não classificados em outra parte', 'T44.3 Outr parassimpaticoliticos espasmolit NCOP'),
  ('T444', 'Intoxicação por agonistas principalmente alfa-adrenorreceptores não classificados em outra parte', 'T44.4 Agonistas princ alfa-adrenorreceptores NCOP'),
  ('T445', 'Intoxicação por agonistas principalmente beta-adrenorreceptores não classificados em outra parte', 'T44.5 Agonistas princ beta-adrenorreceptores NCOP'),
  ('T446', 'Intoxicação por antagonistas alfa-adrenorreceptores não classificados em outra parte', 'T44.6 Antagonistas alfa-adrenorreceptores NCOP'),
  ('T447', 'Intoxicação por antagonistas beta-adrenorreceptores não classificados em outra parte', 'T44.7 Antagonistas beta-adrenorreceptores NCOP'),
  ('T448', 'Intoxicação por bloqueadores neuronais adrenérgicos e de ação central, não classificados em outra parte', 'T44.8 Bloqueador neuron adrenerg acao central NCOP'),
  ('T449', 'Intoxicação por outras drogas que afetam principalmente o sistema nervoso autônomo e as não especificadas', 'T44.9 Outr drog q afet princ sist nerv autonomo NE'),
  ('T45', 'Intoxicação por substâncias de ação essencialmente sistêmica e substâncias hematológicas, não classificadas em outra parte', 'T45 Intox subst acao ess sist subst hematol NCOP'),
  ('T450', 'Intoxicação por drogas antialérgicas e antieméticas', 'T45.0 Drogas antialergicas e antiemeticas'),
  ('T451', 'Intoxicação por drogas antineoplásicas e imunomupressoras', 'T45.1 Drogas antineoplasicas e imunomupressoras'),
  ('T452', 'Intoxicação por vitaminas, não classificadas em outra parte', 'T45.2 Vitaminas NCOP'),
  ('T453', 'Intoxicação por enzimas, não classificadas em outra parte', 'T45.3 Enzimas NCOP'),
  ('T454', 'Intoxicação por ferro e seus compostos', 'T45.4 Ferro e seus compostos'),
  ('T455', 'Intoxicação por anticoagulantes', 'T45.5 Anticoagulantes'),
  ('T456', 'Intoxicação por drogas que afetam a fibrinólise', 'T45.6 Drogas que afetam a fibrinolise'),
  ('T457', 'Intoxicação por antagonistas de anticoagulantes, vitamina K e de outros fatores de coagulação', 'T45.7 Antagonist anticoag vitamina K outr fat coag'),
  ('T458', 'Intoxicação por outras substâncias primariamente sistêmicas e hematológicas', 'T45.8 Outr subst prim sistemicas e hematologicas'),
  ('T459', 'Intoxicação por substância essencialmente sistêmica e hematológica não especificada', 'T45.9 Subst essenc sistemica hematologica NE'),
  ('T46', 'Intoxicação por substâncias que atuam primariamente sobre o aparelho circulatório', 'T46 Intox subst que atuam prim sobre ap circul'),
  ('T460', 'Intoxicação por glicosídeos estimulantes do coração e substâncias de ação semelhante', 'T46.0 Glicosideos estim coracao subst acao semelh'),
  ('T461', 'Intoxicação por bloqueadores dos canais de cálcio', 'T46.1 Bloqueadores dos canais de calcio'),
  ('T462', 'Intoxicação por outras drogas antidisrítmicas não classificadas em outra parte', 'T46.2 Outr drogas antidisritmicas NCOP'),
  ('T463', 'Intoxicação por vasodilatadores coronarianos, não classificados em outra parte', 'T46.3 Vasodilatadores coronarianos NCOP'),
  ('T464', 'Intoxicação por inibidores da enzima de conversão da angiotensina', 'T46.4 Inibidores da enzima conversao angiotensina'),
  ('T465', 'Intoxicação por outras drogas anti-hipertensivas não classificadas em outra parte', 'T46.5 Outr drogas anti-hipertensivas NCOP'),
  ('T466', 'Intoxicação por drogas antihiperlipêmicas e antiarterioscleróticas', 'T46.6 Drog antihiperlipemicas antiarteriosclerotic'),
  ('T467', 'Intoxicação por vasodilatadores periféricos', 'T46.7 Vasodilatadores perifericos'),
  ('T468', 'Intoxicação por drogas antivaricosas, incluindo substâncias esclerosantes', 'T46.8 Drog antivaricosas incl subst esclerosantes'),
  ('T469', 'Intoxicação por outras substâncias e as não especificadas que agem essencialmente sobre o aparelho circulatório', 'T46.9 Outr subst e NE que agem essenc s/ap circ'),
  ('T47', 'Intoxicação por substâncias que atuam primariamente sobre o aparelho gastrointestinal', 'T47 Intox p/subst que atuam prim s/ap gastroint'),
  ('T470', 'Intoxicação por antagonistas dos receptores H2 da histamina', 'T47.0 Antagonistas dos receptores H2 da histamina'),
  ('T471', 'Intoxicação por outros antiácidos e drogas que inibem a secreção gástrica', 'T47.1 Outr antiacidos drog q inibem secr gastrica'),
  ('T472', 'Intoxicação por laxativos estimulantes', 'T47.2 Laxativos estimulantes'),
  ('T473', 'Intoxicação por laxativos salinos e osmóticos', 'T47.3 Laxativos salinos e osmoticos'),
  ('T474', 'Intoxicação por outros laxativos', 'T47.4 Outr laxativos'),
  ('T475', 'Intoxicação por digestivos', 'T47.5 Digestivos'),
  ('T476', 'Intoxicação por drogas antidiarréicas', 'T47.6 Drogas antidiarreicas'),
  ('T477', 'Intoxicação por eméticos', 'T47.7 Emeticos'),
  ('T478', 'Intoxicação por outras substâncias que atuam primariamente sobre o aparelho gastrintestinal', 'T47.8 Outr subst que atuam prim s/ap gastrintest'),
  ('T479', 'Intoxicação por substância não especificada que atua primariamente sobre o aparelho gastrointestinal', 'T47.9 Subst NE que atua prim s/ap gastrointestinal'),
  ('T48', 'Intoxicação por substâncias que atuam primariamente sobre os músculos lisos e esqueléticos e sobre o aparelho respiratório', 'T48 Intox subst q at prim musc lisos esq ap resp'),
  ('T480', 'Intoxicação por drogas ocitócicas', 'T48.0 Drogas ocitocicas'),
  ('T481', 'Intoxicação por relaxantes musculares esqueléticos (bloqueadores neuromusculares)', 'T48.1 Relaxantes musculares esqueleticos'),
  ('T482', 'Intoxicação por outras substâncias e as não especificadas que atuam sobre os músculos', 'T48.2 Outr subst e as NE que atuam sobre musculos'),
  ('T483', 'Intoxicação por antitussígenos', 'T48.3 Antitussigenos'),
  ('T484', 'Intoxicação por expectorantes', 'T48.4 Expectorantes'),
  ('T485', 'Intoxicação por drogas anti-resfriado', 'T48.5 Drogas anti-resfriado'),
  ('T486', 'Intoxicação por antiasmáticos não classificados em outra parte', 'T48.6 Antiasmaticos NCOP'),
  ('T487', 'Intoxicação por outras substâncias e as não especificadas que atuam primariamente sobre o aparelho respiratório', 'T48.7 Outr subst e NE que atuam prim s/ap respirat'),
  ('T49', 'Intoxicação por substâncias de uso tópico que atuam primariamente sobre a pele e as mucosas e por medicamentos utilizados em oftalmologia, otorrinolaringologia e odontologia', 'T49 Int subs uso top pel muc med ut oft otor odo'),
  ('T490', 'Intoxicação por antifúngicos, antiinfecciosos e antiinflamatórios de uso tópico, não classificados em outra parte', 'T49.0 Antifung antiinfec antiinflamat uso top NCOP'),
  ('T491', 'Intoxicação por antipruriginosos', 'T49.1 Antipruriginosos'),
  ('T492', 'Intoxicação por adstringentes e detergentes de uso local', 'T49.2 Adstringentes e detergentes de uso local'),
  ('T493', 'Intoxicação por emolientes, demulcentes e protetores', 'T49.3 Emolientes demulcentes e protetores'),
  ('T494', 'Intoxicação por ceratolíticos, ceratoplásticos e outras drogas e preparados para o tratamento dos cabelos', 'T49.4 Ceratol ceratopl out drog prepar trat cabelo'),
  ('T495', 'Intoxicação por drogas e preparações de uso oftalmológico', 'T49.5 Drogas e preparacoes de uso oftalmologico'),
  ('T496', 'Intoxicação por drogas e preparações de uso otorrinolaringológico', 'T49.6 Drogas preparacoes uso otorrinolaringologico'),
  ('T497', 'Intoxicação por drogas dentárias de uso tópico', 'T49.7 Drogas dentarias de uso topico'),
  ('T498', 'Intoxicação por outras drogas de uso tópico', 'T49.8 Outr drogas de uso topico'),
  ('T499', 'Intoxicação por preparado de uso tópico, não especificado', 'T49.9 Preparado de uso topico NE'),
  ('T50', 'Intoxicação por diuréticos e outras drogas, medicamentos e substâncias biológicas e as não especificadas', 'T50 Intox diuret out drog medic subst biolog NE'),
  ('T500', 'Intoxicação por mineralocorticóides e seus antagonistas', 'T50.0 Mineralocorticoides e seus antagonistas'),
  ('T501', 'Intoxicação por diuréticos de alça', 'T50.1 Diureticos de alca'),
  ('T502', 'Intoxicação por inibidores da anidrase carbônica, benzotiazidas e outros diuréticos', 'T50.2 Inib anidrase carb benzotiazidas outr diuret'),
  ('T503', 'Intoxicação por produtos que agem sobre o equilíbrio eletrolítico, calórico e hídrico', 'T50.3 Prod que agem s/equil eletr caloric hidric'),
  ('T504', 'Intoxicação por drogas que agem sobre o metabolismo do ácido úrico', 'T50.4 Drogas que agem sobre metab acido urico'),
  ('T505', 'Intoxicação por inibidores do apetite', 'T50.5 Inibidores do apetite'),
  ('T506', 'Intoxicação por antídotos e quelantes não classificados em outra parte', 'T50.6 Antidotos e quelantes NCOP'),
  ('T507', 'Intoxicação por analépticos e antagonistas dos receptores de opiáceos', 'T50.7 Analepticos antagonistas receptores opiaceos'),
  ('T508', 'Intoxicação por agentes de diagnóstico', 'T50.8 Agentes de diagn'),
  ('T509', 'Intoxicação por outras drogas, medicamentos e substâncias biológicas e as não especificadas', 'T50.9 Outr drogas medicamentos subst biolog e NE'),
  ('T51', 'Efeito tóxico do álcool', 'T51 Efeito toxico do alcool'),
  ('T510', 'Efeito tóxico do etanol', 'T51.0 Etanol'),
  ('T511', 'Efeito tóxico do metanol', 'T51.1 Metanol'),
  ('T512', 'Efeito tóxico do 2-propanol', 'T51.2 2-propanol'),
  ('T513', 'Efeito tóxico do óleo de fusel', 'T51.3 Oleo de fusel'),
  ('T518', 'Efeito tóxico de outros álcoois', 'T51.8 Outr alcoois'),
  ('T519', 'Efeito tóxico de álcool não especificado', 'T51.9 Alcool NE'),
  ('T52', 'Efeito tóxico de solventes orgânicos', 'T52 Efeito toxico de solventes organicos'),
  ('T520', 'Efeito tóxico de derivados do petróleo', 'T52.0 Derivados do petroleo'),
  ('T521', 'Efeito tóxico do benzeno', 'T52.1 Benzeno'),
  ('T522', 'Efeito tóxico de homólogos do benzeno', 'T52.2 Homologos do benzeno'),
  ('T523', 'Efeito tóxico de glicóis', 'T52.3 Glicois'),
  ('T524', 'Efeito tóxico de cetonas', 'T52.4 Cetonas'),
  ('T528', 'Efeito tóxico de outros solventes orgânicos', 'T52.8 Outr solventes organicos'),
  ('T529', 'Efeito tóxico de solvente orgânico não especificado', 'T52.9 Solvente organico NE'),
  ('T53', 'Efeito tóxico de derivados halogênicos de hidrocarbonetos alifáticos e aromáticos', 'T53 Efeito tox deriv halog hidrocarb alif aromat'),
  ('T530', 'Efeito tóxico do tetracloreto de carbono', 'T53.0 Tetracloreto de carbono'),
  ('T531', 'Efeito tóxico do clorofórmio', 'T53.1 Cloroformio'),
  ('T532', 'Efeito tóxico do tricloroetileno', 'T53.2 Tricloroetileno'),
  ('T533', 'Efeito tóxico do tetracloroetileno', 'T53.3 Tetracloroetileno'),
  ('T534', 'Efeito tóxico do diclorometano', 'T53.4 Diclorometano'),
  ('T535', 'Efeito tóxico do clorofluorcarbono', 'T53.5 Clorofluorcarbono'),
  ('T536', 'Efeito tóxico de outros derivados halogênicos de hidrocarbonetos alifáticos', 'T53.6 Outr deriv halog hidrocarbonetos alifaticos'),
  ('T537', 'Efeito tóxico de derivados halogênicos de hidrocarbonetos aromáticos', 'T53.7 Deriv halogenicos hidrocarbonetos aromaticos'),
  ('T539', 'Efeito tóxico de derivados halogênicos de hidrocarbonetos alifáticos e aromáticos não especificados', 'T53.9 Deriv halog hidrocarbonetos alifat aromat NE'),
  ('T54', 'Efeito tóxico de corrosivos', 'T54 Efeito toxico de corrosivos'),
  ('T540', 'Efeito tóxico do fenol e homólogos do fenol', 'T54.0 Fenol e homologos do fenol'),
  ('T541', 'Efeito tóxico de outros compostos corrosivos orgânicos', 'T54.1 Outr compostos corrosivos organicos'),
  ('T542', 'Efeito tóxico de ácidos corrosivos e substâncias semelhantes', 'T54.2 Acidos corrosivos e subst semelhantes'),
  ('T543', 'Efeito tóxico de bases (álcalis) cáusticas(os) e substâncias semelhantes', 'T54.3 Bases causticas e subst semelhantes'),
  ('T549', 'Efeito tóxico de substância corrosiva não especificada', 'T54.9 Subst corrosiva NE'),
  ('T55', 'Efeito tóxico de sabões e detergentes', 'T55 Efeito toxico de saboes e detergentes'),
  ('T55', 'Efeito tóxico de sabões e detergentes', 'T55 Efeito toxico de saboes e detergentes'),
  ('T56', 'Efeito tóxico de metais', 'T56 Efeito toxico de metais'),
  ('T560', 'Efeito tóxico do chumbo e seus compostos', 'T56.0 Chumbo e seus compostos'),
  ('T561', 'Efeito tóxico do mercúrio e seus compostos', 'T56.1 Mercurio e seus compostos'),
  ('T562', 'Efeito tóxico do cromo e seus compostos', 'T56.2 Cromo e seus compostos'),
  ('T563', 'Efeito tóxico do cádmio e seus compostos', 'T56.3 Cadmio e seus compostos'),
  ('T564', 'Efeito tóxico do cobre e seus compostos', 'T56.4 Cobre e seus compostos'),
  ('T565', 'Efeito tóxico do zinco e seus compostos', 'T56.5 Zinco e seus compostos'),
  ('T566', 'Efeito tóxico do estanho e seus compostos', 'T56.6 Estanho e seus compostos'),
  ('T567', 'Efeito tóxico do berilo e seus compostos', 'T56.7 Berilo e seus compostos'),
  ('T568', 'Efeito tóxico de outros metais', 'T56.8 Outr metais'),
  ('T569', 'Efeito tóxico de metal, não especificado', 'T56.9 Metal NE'),
  ('T57', 'Efeito tóxico de outras substâncias inorgânicas', 'T57 Efeito toxico de outr subst inorganicas'),
  ('T570', 'Efeito tóxico do arsênico e seus compostos', 'T57.0 Arsenico e seus compostos'),
  ('T571', 'Efeito tóxico do fósforo e seus compostos', 'T57.1 Fosforo e seus compostos'),
  ('T572', 'Efeito tóxico do manganês e seus compostos', 'T57.2 Manganes e seus compostos'),
  ('T573', 'Efeito tóxico do cianeto de hidrogênio (ácido cianídrico)', 'T57.3 Cianeto de hidrogenio'),
  ('T578', 'Efeito tóxico de outras substâncias inorgânicas especificadas', 'T57.8 Outr subst inorganicas espec'),
  ('T579', 'Efeito tóxico de substância inorgânica não especificada', 'T57.9 Subst inorganica NE'),
  ('T58', 'Efeito tóxico do monóxido de carbono', 'T58 Efeito toxico de monoxido de carbono'),
  ('T58', 'Efeito tóxico do monóxido de carbono', 'T58 Efeito toxico de monoxido de carbono'),
  ('T59', 'Efeito tóxico de outros gases, fumaças e vapores', 'T59 Efeito toxico de outr gases fumacas vapores'),
  ('T590', 'Efeito tóxico de óxidos de nitrogênio', 'T59.0 Oxidos de nitrogenio'),
  ('T591', 'Efeito tóxico do dióxido de enxofre', 'T59.1 Dioxido de enxofre'),
  ('T592', 'Efeito tóxico de formaldeído', 'T59.2 Formaldeido'),
  ('T593', 'Efeito tóxico do gás lacrimogêneo', 'T59.3 Gas lacrimogenio'),
  ('T594', 'Efeito tóxico do cloro gasoso', 'T59.4 Cloro gasoso'),
  ('T595', 'Efeito tóxico do fluoreto gasoso e ácido fluorídrico', 'T59.5 Fluoreto gasoso e acido fluoridrico'),
  ('T596', 'Efeito tóxico do ácido sulfídrico', 'T59.6 Acido sulfidrico'),
  ('T597', 'Efeito tóxico do dióxido de carbono', 'T59.7 Dioxido de carbono'),
  ('T598', 'Efeito tóxico de outros gases, fumaças e vapores especificados', 'T59.8 Outr gases fumacas e vapores espec'),
  ('T599', 'Efeito tóxico de gases, fumaças e vapores não especificados', 'T59.9 Gases fumacas e vapores NE'),
  ('T60', 'Efeito tóxico de pesticidas', 'T60 Efeito toxico de pesticidas'),
  ('T600', 'Efeito tóxico de inseticidas organofosforados e carbamatos', 'T60.0 Inseticidas organofosforados e carbamatos'),
  ('T601', 'Efeito tóxico de inseticidas halogenados', 'T60.1 Inseticidas halogenados'),
  ('T602', 'Efeito tóxico de outros inseticidas', 'T60.2 Outr inseticidas'),
  ('T603', 'Efeito tóxico de herbicidas e fungicidas', 'T60.3 Herbicidas e fungicidas'),
  ('T604', 'Efeito tóxico de rodenticidas', 'T60.4 Rodenticidas'),
  ('T608', 'Efeito tóxico de outros pesticidas', 'T60.8 Outr pesticidas'),
  ('T609', 'Efeito tóxico de pesticida não especificado', 'T60.9 Pesticida NE'),
  ('T61', 'Efeito tóxico de substâncias nocivas consumidas como fruto do mar', 'T61 Efeito tox subst nocivas cons como fruto mar'),
  ('T610', 'Intoxicação pelo peixe ciguatera', 'T61.0 Intox p/peixe ciguatera'),
  ('T611', 'Intoxicação por peixes escombrídeos', 'T61.1 Intox p/peixes escombrideos'),
  ('T612', 'Outras intoxicações por peixes e mariscos', 'T61.2 Outr intox p/peixes e mariscos'),
  ('T618', 'Efeito tóxico de outros frutos do mar', 'T61.8 Efeito toxico de outr frutos do mar'),
  ('T619', 'Efeito tóxico de frutos do mar não especificados', 'T61.9 Efeito toxico de frutos do mar NE'),
  ('T62', 'Efeito tóxico de outras substâncias nocivas ingeridas como alimento', 'T62 Efeito tox outr subst noc inger como aliment'),
  ('T620', 'Efeito tóxico de ingestão de cogumelos', 'T62.0 Ingestao de cogumelos'),
  ('T621', 'Efeito tóxico de ingestão de frutos', 'T62.1 Ingestao de frutos'),
  ('T622', 'Efeito tóxico de ingestão de outras (partes de) plantas', 'T62.2 Ingestao de outr plantas'),
  ('T628', 'Efeito tóxico de outras substâncias nocivas ingeridas como alimento', 'T62.8 Outr subst nocivas ingeridas como alimento'),
  ('T629', 'Efeito tóxico de substâncias nocivas ingeridas como alimento, não especificadas', 'T62.9 Subst nocivas ingeridas como alimento NE'),
  ('T63', 'Efeito tóxico de contato com animais venenosos', 'T63 Efeito toxico de contato c/animais venenosos'),
  ('T630', 'Efeito tóxico do veneno de serpente', 'T63.0 Veneno de serpente'),
  ('T631', 'Efeito tóxico do veneno de outros répteis', 'T63.1 Veneno de outr repteis'),
  ('T632', 'Efeito tóxico do veneno de escorpião', 'T63.2 Veneno de escorpiao'),
  ('T633', 'Efeito tóxico do veneno de aranha', 'T63.3 Veneno de aranha'),
  ('T634', 'Efeito tóxico do veneno de outros artrópodes', 'T63.4 Veneno de outr artropodes'),
  ('T635', 'Efeito tóxico de contato com peixe', 'T63.5 Contato c/peixe'),
  ('T636', 'Efeito tóxico de contato com outros animais marinhos', 'T63.6 Contato c/outr animais marinhos'),
  ('T638', 'Efeito tóxico de contato com outros animais venenosos', 'T63.8 Contato c/outr animais venenosos'),
  ('T639', 'Efeito tóxico de contato com animal venenoso não especificado', 'T63.9 Contato c/animal venenoso NE'),
  ('T64', 'Efeito tóxico da aflatoxina e de outras micotoxinas contaminantes de alimentos', 'T64 Efeito tox aflatox outr micotox contam alim'),
  ('T64', 'Efeito tóxico da aflatoxina e de outras micotoxinas contaminantes de alimentos', 'T64 Efeito tox aflatox outr micotox contam alim'),
  ('T65', 'Efeito tóxico de outras substâncias e as não especificadas', 'T65 Efeito toxico de outr subst e as NE'),
  ('T650', 'Efeito tóxico de cianetos', 'T65.0 Cianetos'),
  ('T651', 'Efeito tóxico da estricnina e seus sais', 'T65.1 Estricnina e seus sais'),
  ('T652', 'Efeito tóxico do tabaco e da nicotina', 'T65.2 Tabaco e da nicotina'),
  ('T653', 'Efeito tóxico de nitroderivados e aminoderivados do benzeno e seus homólogos', 'T65.3 Nitroderiv aminoderiv benzeno seus homologos'),
  ('T654', 'Efeito tóxico do dissulfeto de carbono', 'T65.4 Dissulfeto de carbono'),
  ('T655', 'Efeito tóxico da nitroglicerina e outros ácidos e ésteres nítricos', 'T65.5 Nitroglicerina outr acidos esteres nitricos'),
  ('T656', 'Efeito tóxico de tinturas e corantes, não classificadas em outra parte', 'T65.6 Tinturas e corantes NCOP'),
  ('T658', 'Efeito tóxico de outras substâncias especificadas', 'T65.8 Outr subst espec'),
  ('T659', 'Efeito tóxico de substância não especificada', 'T65.9 Subst NE'),
  ('T66', 'Efeitos não especificados de radiação', 'T66 Efeitos NE de radiacao'),
  ('T66', 'Efeitos não especificados de radiação', 'T66 Efeitos NE de radiacao'),
  ('T67', 'Efeitos do calor e da luz', 'T67 Efeitos do calor e da luz'),
  ('T670', 'Golpe de calor e insolação', 'T67.0 Golpe de calor e insolacao'),
  ('T671', 'Síncope devida ao calor', 'T67.1 Sincope dev calor'),
  ('T672', 'Cãibras devidas ao calor', 'T67.2 Caibras dev calor'),
  ('T673', 'Exaustão devida ao calor e à perda hídrica', 'T67.3 Exaustao dev calor e a perda hidrica'),
  ('T674', 'Exaustão devida ao calor e à perda de sal', 'T67.4 Exaustao dev calor e a perda de sal'),
  ('T675', 'Exaustão devida ao calor, sem especificação', 'T67.5 Exaustao dev calor s/especificacao'),
  ('T676', 'Fadiga transitória devida ao calor', 'T67.6 Fadiga transitoria dev calor'),
  ('T677', 'Edema devido ao calor', 'T67.7 Edema dev calor'),
  ('T678', 'Outros efeitos do calor e da luz', 'T67.8 Outr efeitos do calor e da luz'),
  ('T679', 'Efeito do calor e da luz não especificado', 'T67.9 Efeito do calor e da luz NE'),
  ('T68', 'Hipotermia', 'T68 Hipotermia'),
  ('T68', 'Hipotermia', 'T68 Hipotermia'),
  ('T69', 'Outros efeitos da temperatura reduzida', 'T69 Outr efeitos da temperatura reduzida'),
  ('T690', 'Mão e pé de imersão', 'T69.0 Mao e pe de imersao'),
  ('T691', 'Congelamento (chilblains)', 'T69.1 Congelamento'),
  ('T698', 'Outros efeitos especificados de temperatura reduzida', 'T69.8 Outr efeitos espec de temperatura reduzida'),
  ('T699', 'Efeito não especificado de temperatura reduzida', 'T69.9 Efeito NE de temperatura reduzida'),
  ('T70', 'Efeitos da pressão atmosférica e da pressão da água', 'T70 Efeitos pressao atmosferica e pressao agua'),
  ('T700', 'Otite barotraumática', 'T70.0 Otite barotraumatica'),
  ('T701', 'Sinusite barotraumática', 'T70.1 Sinusite barotraumatica'),
  ('T702', 'Outros efeitos das grandes altitude e os não especificados', 'T70.2 Outr efeitos das grandes altitude e os NE'),
  ('T703', 'Mal dos caixões (doença de descompressão)', 'T70.3 Mal dos caixoes'),
  ('T704', 'Efeito dos fluidos em alta pressão', 'T70.4 Efeito dos fluidos em alta pressao'),
  ('T708', 'Outros efeitos da pressão atmosférica ou da pressão da água', 'T70.8 Outr efeitos pressao atmosferica press agua'),
  ('T709', 'Efeitos não especificados da pressão atmosférica ou da pressão da água', 'T70.9 Efeitos NE pressao atmosferica pressao agua'),
  ('T71', 'Asfixia', 'T71 Asfixia'),
  ('T71', 'Asfixia', 'T71 Asfixia'),
  ('T73', 'Efeitos de outras privações', 'T73 Efeitos de outr privacoes'),
  ('T730', 'Efeitos da fome', 'T73.0 Efeitos da fome'),
  ('T731', 'Efeitos da sede', 'T73.1 Efeitos da sede'),
  ('T732', 'Exaustão devida às intempéries', 'T73.2 Exaustao dev intemperies'),
  ('T733', 'Exaustão devido a um esforço intenso', 'T73.3 Exaustao dev um esforco intenso'),
  ('T738', 'Outros efeitos de privação', 'T73.8 Outr efeitos de privacao'),
  ('T739', 'Efeito não especificado de privação', 'T73.9 Efeito NE de privacao'),
  ('T74', 'Síndromes de maus tratos', 'T74 Sindr de maus tratos'),
  ('T740', 'Abandono', 'T74.0 Abandono'),
  ('T741', 'Sevícias físicas', 'T74.1 Sevicias fisicas'),
  ('T742', 'Abuso sexual', 'T74.2 Abuso sexual'),
  ('T743', 'Abuso psicológico', 'T74.3 Abuso psicologico'),
  ('T748', 'Outras síndromes especificadas de maus tratos', 'T74.8 Outr sindr espec de maus tratos'),
  ('T749', 'Síndrome não especificada de maus tratos', 'T74.9 Sindr NE de maus tratos'),
  ('T75', 'Efeitos de outras causas externas', 'T75 Efeitos de outr causas externas'),
  ('T750', 'Efeitos do raio', 'T75.0 Efeitos do raio'),
  ('T751', 'Afogamento e submersão não mortal', 'T75.1 Afogamento e submersao nao mortal'),
  ('T752', 'Efeitos da vibração', 'T75.2 Efeitos da vibracao'),
  ('T753', 'Doença causada pelo movimento', 'T75.3 Doenc causada p/movimento'),
  ('T754', 'Efeitos da corrente elétrica', 'T75.4 Efeitos da corrente eletrica'),
  ('T758', 'Outros efeitos especificados de causas externas', 'T75.8 Outr efeitos espec de causas externas'),
  ('T78', 'Efeitos adversos não classificados em outra parte', 'T78 Efeitos adversos NCOP'),
  ('T780', 'Choque anafilático devido à intolerância alimentar', 'T78.0 Choque anafilatico dev intolerancia alim'),
  ('T781', 'Outras reações de intolerância alimentar não classificadas em outra parte', 'T78.1 Outr reacoes de intolerancia alimentar NCOP'),
  ('T782', 'Choque anafilático não especificado', 'T78.2 Choque anafilatico NE'),
  ('T783', 'Edema angioneurótico', 'T78.3 Edema angioneurotico'),
  ('T784', 'Alergia não especificada', 'T78.4 Alergia NE'),
  ('T788', 'Outros efeitos adversos não classificados em outra parte', 'T78.8 Outr efeitos adversos NCOP'),
  ('T789', 'Efeito adverso não especificado', 'T78.9 Efeito adverso NE'),
  ('T79', 'Algumas complicações precoces dos traumatismos não classificadas em outra parte', 'T79 Algumas complic precoces dos traum NCOP'),
  ('T790', 'Embolia gasosa (traumática)', 'T79.0 Embolia gasosa'),
  ('T791', 'Embolia gordurosa (traumática)', 'T79.1 Embolia gordurosa'),
  ('T792', 'Hemorragia traumática secundária e recidivante', 'T79.2 Hemorragia traum secund e recidivante'),
  ('T793', 'Infecção pós-traumática de ferimento não classificada em outra parte', 'T79.3 Infecc pos-traum de ferim NCOP'),
  ('T794', 'Choque traumático', 'T79.4 Choque traum'),
  ('T795', 'Anúria traumática', 'T79.5 Anuria traum'),
  ('T796', 'Isquemia muscular traumática', 'T79.6 Isquemia muscular traum'),
  ('T797', 'Enfisema subcutâneo de origem traumática', 'T79.7 Enfisema subcutaneo orig traum'),
  ('T798', 'Outras complicações precoces de traumatismo', 'T79.8 Outr complic precoces de traum'),
  ('T799', 'Complicação precoce não especificada de traumatismo', 'T79.9 Complic precoce NE de traum'),
  ('T80', 'Complicações conseqüentes à infusão, transfusão ou injeção terapêutica', 'T80 Complic conseq infus transfus injecao terap'),
  ('T800', 'Embolia aérea subseqüentes à infusão, transfusão e injeção terapêutica', 'T80.0 Embolia aerea subs infus transf injec terap'),
  ('T801', 'Complicações vasculares subseqüentes à infusão, transfusão e injeção terapêutica', 'T80.1 Complic vasc subseq infus transf injec terap'),
  ('T802', 'Infecções subseqüentes à infusão, transfusão e injeção terapêutica', 'T80.2 Infecc subseq infusao transfus injecao terap'),
  ('T803', 'Reação de incompatibilidade ABO', 'T80.3 Reacao de incompatibilidade ABO'),
  ('T804', 'Reação de incompatibilidade Rh', 'T80.4 Reacao de incompatibilidade Rh'),
  ('T805', 'Choque anafilático devido a soro', 'T80.5 Choque anafilatico dev soro'),
  ('T806', 'Outras reações ao soro', 'T80.6 Outr reacoes ao soro'),
  ('T808', 'Outras complicações subseqüentes à infusão, transfusão e injeção terapêutica', 'T80.8 Outr complic subseq infus transf injec terap'),
  ('T809', 'Complicação não especificada subseqüente à infusão, transfusão e injeção terapêutica', 'T80.9 Complic NE subseq infus transfus injec terap'),
  ('T81', 'Complicações de procedimentos não classificadas em outra parte', 'T81 Complic de proced NCOP'),
  ('T810', 'Hemorragia e hematoma complicando procedimento não classificado em outra parte', 'T81.0 Hemorragia e hematoma complic proced NCOP'),
  ('T811', 'Choque durante ou resultante de procedimento não classificado em outra parte', 'T81.1 Choque durante ou resultante de proced NCOP'),
  ('T812', 'Perfuração e laceração acidentais durante um procedimento não classificado em outra parte', 'T81.2 Perfuracao lacerac acid durante proced NCOP'),
  ('T813', 'Deiscência de ferida cirúrgica não classificada em outra parte', 'T81.3 Deiscencia de ferida cirurgica NCOP'),
  ('T814', 'Infecção subseqüente a procedimento não classificada em outra parte', 'T81.4 Infecc subsequente a proced NCOP'),
  ('T815', 'Corpo estranho deixado acidentalmente em cavidade corporal ou em ferida operatória subseqüente a procedimento', 'T81.5 Corp estr acid cav corp ferid oper subs proc'),
  ('T816', 'Reação aguda à substância estranha deixada acidentalmente durante um procedimento', 'T81.6 Reacao ag subst estr deix acid durante proc'),
  ('T817', 'Complicações vasculares subseqüentes a um procedimento não classificado em outra parte', 'T81.7 Complic vasc subsequentes a um proced NCOP'),
  ('T818', 'Outras complicações de procedimentos não classificadas em outra parte', 'T81.8 Outr complic de proced NCOP'),
  ('T819', 'Complicação não especificada de procedimento', 'T81.9 Complic NE de proced'),
  ('T82', 'Complicações de dispositivos protéticos, implantes e enxertos cardíacos e vasculares', 'T82 Complic disp prot impl enxert card e vasc'),
  ('T820', 'Complicação mecânica de prótese valvular cardíaca', 'T82.0 Complic mecanica protese valvular cardiaca'),
  ('T821', 'Complicação mecânica de dispositivo eletrônico cardíaco', 'T82.1 Complic mecanica de disp eletronico cardiaco'),
  ('T822', 'Complicação mecânica de enxerto de ponte coronária e implantes de valvas', 'T82.2 Complic mec enxerto ponte coron impl valvas'),
  ('T823', 'Complicações mecânicas de outros enxertos vasculares', 'T82.3 Complic mecanicas outr enxertos vasculares'),
  ('T824', 'Complicação mecânica de cateter vascular de diálise', 'T82.4 Complic mecanica de cateter vascular dialise'),
  ('T825', 'Complicações mecânicas de outros dispositivos e implantes cardiovasculares', 'T82.5 Complic mec outr disp implantes cardiovasc'),
  ('T826', 'Infecção e reação inflamatórias devidas à prótese valvular cardíaca', 'T82.6 Infecc reac inflam dev protese valvular card'),
  ('T827', 'Infecção e reação inflamatórias devidas a outros dispositivos, implantes e enxertos cardíacos e vasculares', 'T82.7 Inf reac inf dev out disp impl enx card vasc'),
  ('T828', 'Outras complicações de dispositivos protéticos, implantes e enxertos cardíacos e vasculares', 'T82.8 Outr complic disp prot impl enx card vasc'),
  ('T829', 'Complicações não especificada de dispositivo protético, implante e enxerto cardíacos e vasculares', 'T82.9 Complic NE disp prot implant enx card vasc'),
  ('T83', 'Complicações de dispositivos protéticos, implantes e enxertos geniturinários internos', 'T83 Complic disp prot impl enx geniturin int'),
  ('T830', 'Complicação mecânica de cateter (de demora) urinário', 'T83.0 Complic mecanica de cateter urinario'),
  ('T831', 'Complicação mecânica de outros dispositivos e implantes urinários', 'T83.1 Complic mec outr disp implantes urinarios'),
  ('T832', 'Complicação mecânica de enxerto de órgão urinário', 'T83.2 Complic mec de enxerto de orgao urinario'),
  ('T833', 'Complicação mecânica de dispositivo intra-uterino (anticoncepcional)', 'T83.3 Complic mecanica de disp intra-uterino'),
  ('T834', 'Complicação mecânica de outros dispositivos protéticos, implantes e enxertos do trato genital', 'T83.4 Complic mec out disp prot impl enx trat gen'),
  ('T835', 'Infecção e reação inflamatória devidas à dispositivo protético, implante e enxerto no aparelho urinário', 'T83.5 Inf reac infl dev disp prot impl enx ap urin'),
  ('T836', 'Infecção e reação inflamatória devidas à dispositivo protético, implante e enxerto no trato genital', 'T83.6 Inf reac inf dev disp prot impl enx trat gen'),
  ('T838', 'Outras complicações de dispositivos protéticos, implantes e enxertos geniturinários', 'T83.8 Outr complic disp prot impl enx genituri'),
  ('T839', 'Complicação não especificada de prótese, implante e enxerto geniturinários', 'T83.9 Complic NE protese impl enx geniturinarios'),
  ('T84', 'Complicações de dispositivos protéticos, implantes e enxertos ortopédicos internos', 'T84 Complic disp prot impl enx ortopedicos int'),
  ('T840', 'Complicação mecânica de prótese articular interna', 'T84.0 Complic mecanica protese articular interna'),
  ('T841', 'Complicação mecânica de dispositivo de fixação interna de ossos dos membros', 'T84.1 Complic mec disp fixacao int ossos membros'),
  ('T842', 'Complicação mecânica de dispositivo de fixação interna de outros ossos', 'T84.2 Complic mec disp fixacao interna outr ossos'),
  ('T843', 'Complicação mecânica de outros dispositivos, implantes e enxertos ósseos', 'T84.3 Complic mec outr disp impl enxertos osseos'),
  ('T844', 'Complicação mecânica de outros dispositivos, implantes e enxertos ortopédicos internos', 'T84.4 Complic mec outr disp impl enx ortoped int'),
  ('T845', 'Infecção e reação inflamatória devidas à prótese articular interna', 'T84.5 Infecc reacao inflam dev protese artic int'),
  ('T846', 'Infecção e reação inflamatória devidas a dispositivo de fixação interna (qualquer local)', 'T84.6 Infecc reacao inflam dev disp fixacao int'),
  ('T847', 'Infecção e reação inflamatória devidas a outros dispositivos protéticos, implantes e enxertos ortopédicos internos', 'T84.7 Inf reac inf out disp prot imp enx ort int'),
  ('T848', 'Outras complicações de dispositivos protéticos, implantes e enxertos ortopédicos internos', 'T84.8 Outr complic disp prot impl enx ortop int'),
  ('T849', 'Complicação não especificada de dispositivo protético, implante e enxerto ortopédicos internos', 'T84.9 Complic NE disp protetico impl enx ortop int'),
  ('T85', 'Complicações de outros dispositivos protéticos, implantes e enxertos internos', 'T85 Complic outr disp proteticos impl enx int'),
  ('T850', 'Complicação mecânica de shunt ventricular (comunicação) intracraniano', 'T85.0 Complic mecanica shunt ventric intracraniano'),
  ('T851', 'Complicação mecânica de estimulador eletrônico implantado no sistema nervoso', 'T85.1 Complic mec estim eletr implant sist nerv'),
  ('T852', 'Complicação mecânica de lente intraocular', 'T85.2 Complic mecanica de lente intraocular'),
  ('T853', 'Complicações mecânicas de outros dispositivos protéticos, implantes e enxertos oculares', 'T85.3 Complic mec outr disp prot impl enx oculares'),
  ('T854', 'Complicação mecânica de prótese e implante mamários', 'T85.4 Complic mecanica protese implante mamarios'),
  ('T855', 'Complicação mecânica de dispositivos protéticos, implante e enxerto gastrointestinais', 'T85.5 Complic mec disp prot impl enx gastrointest'),
  ('T856', 'Complicação mecânica de outros dispositivos protéticos, implantes e enxertos internos especificados', 'T85.6 Complic mec out disp prot impl enx int espec'),
  ('T857', 'Infecção e reação inflamatória devida a outros dispositivos protéticos, implantes e enxertos internos', 'T85.7 Inf reac inf dev outr disp prot impl enx int'),
  ('T858', 'Outras complicações de dispositivos protéticos, implantes e enxertos internos não classificados em outra parte', 'T85.8 Outr complic disp prot impl enx int NCOP'),
  ('T859', 'Complicação não especificada de outros dispositivos protéticos, implantes e enxertos internos', 'T85.9 Complic NE outr disp prot impl enx internos'),
  ('T86', 'Falha e rejeição de órgãos e tecidos transplantados', 'T86 Falha rejeicao orgaos e tec transplantados'),
  ('T860', 'Rejeição a transplante de medula óssea', 'T86.0 Rejeicao a transplante de medula ossea'),
  ('T861', 'Falência ou rejeição de transplante de rim', 'T86.1 Falencia ou rejeicao de transplante de rim'),
  ('T862', 'Falência ou rejeição de transplante de coração', 'T86.2 Falencia ou rejeicao de transplante coracao'),
  ('T863', 'Falência ou rejeição de transplante duplo de coração e pulmão', 'T86.3 Falencia rejeic transpl duplo coracao pulmao'),
  ('T864', 'Falência ou rejeição de transplante de fígado', 'T86.4 Falencia ou rejeicao de transplante figado'),
  ('T868', 'Outra insuficiência ou rejeição de outros órgãos ou tecidos transplantados', 'T86.8 Outr insuf rejeicao outr org tec transplant'),
  ('T869', 'Falência e rejeição a transplante de órgão ou tecido não especificado', 'T86.9 Falencia rejeicao transplante orgao tec NE'),
  ('T87', 'Complicações próprias de reimplante e amputação', 'T87 Complic proprias de reimplante e amput'),
  ('T870', 'Complicações de reimplante (de parte) de extremidade superior', 'T87.0 Complic de reimplante de extremidade super'),
  ('T871', 'Complicações de reimplante (de parte) de extremidade inferior', 'T87.1 Complic de reimplante de extremidade infer'),
  ('T872', 'Complicações de outras partes reimplantadas do corpo', 'T87.2 Complic de outr partes reimplantadas corpo'),
  ('T873', 'Neuroma de coto da amputação', 'T87.3 Neuroma de coto da amput'),
  ('T874', 'Infecção de coto da amputação', 'T87.4 Infecc de coto da amput'),
  ('T875', 'Necrose do coto da amputação', 'T87.5 Necrose do coto da amput'),
  ('T876', 'Outras complicações e as não especificadas do coto de amputação', 'T87.6 Outr complic e as NE do coto de amput'),
  ('T88', 'Outras complicações de cuidados médicos e cirúrgicos não classificadas em outra parte', 'T88 Outr complic cuidados medicos cirurg NCOP'),
  ('T880', 'Infecção subseqüente à imunização', 'T88.0 Infecc subsequente a imunizacao'),
  ('T881', 'Outras complicações subseqüentes à imunização não classificadas em outra parte', 'T88.1 Outr complic subsequentes a imunizacao NCOP'),
  ('T882', 'Choque devido à anestesia', 'T88.2 Choque dev anestesia'),
  ('T883', 'Hipertermia maligna devida à anestesia', 'T88.3 Hipertermia maligna dev anestesia'),
  ('T884', 'Entubação falha ou difícil', 'T88.4 Entubacao falha ou dificil'),
  ('T885', 'Outras complicações de anestesia', 'T88.5 Outr complic de anestesia'),
  ('T886', 'Choque anafilático devido a efeito adverso de droga ou medicamento corretos e administrados de maneira apropriada', 'T88.6 Choq anaf dev ef adv drog med corr adm apr'),
  ('T887', 'Efeito adverso não especificado de droga ou medicamento', 'T88.7 Efeito adverso NE de droga ou medicamento'),
  ('T888', 'Outras complicações de cuidados médicos e cirúrgicos especificados não classificados em outra parte', 'T88.8 Outr complic cuidados med cirurg espec NCOP'),
  ('T889', 'Complicação não especificada de cuidados médicos e cirúrgicos', 'T88.9 Complic NE de cuidados medicos e cirurgicos'),
  ('T90', 'Seqüelas de traumatismo da cabeça', 'T90 Sequelas de traum da cabeca'),
  ('T900', 'Seqüelas de traumatismo superficial da cabeça', 'T90.0 Sequelas de traum superf da cabeca'),
  ('T901', 'Seqüelas de ferimento da cabeça', 'T90.1 Sequelas de ferim da cabeca'),
  ('T902', 'Seqüelas de fratura de crânio e de ossos da face', 'T90.2 Sequelas de frat de cranio e de ossos face'),
  ('T903', 'Seqüelas de traumatismo de nervos cranianos', 'T90.3 Sequelas de traum de nervos cranianos'),
  ('T904', 'Seqüelas de traumatismo do olho e da órbita', 'T90.4 Sequelas de traum do olho e da orbita'),
  ('T905', 'Seqüelas de traumatismo intracraniano', 'T90.5 Sequelas de traum intracraniano'),
  ('T908', 'Seqüelas de outros traumatismos especificados da cabeça', 'T90.8 Sequelas de outr traum espec da cabeca'),
  ('T909', 'Seqüelas de traumatismo não especificado da cabeça', 'T90.9 Sequelas de traum NE da cabeca'),
  ('T91', 'Seqüelas de traumatismos do pescoço e do tronco', 'T91 Sequelas de traum do pescoco e do tronco'),
  ('T910', 'Seqüelas de traumatismo superficial e ferimento do pescoço e do tronco', 'T91.0 Sequelas traum superf e ferim pescoco tronco'),
  ('T911', 'Seqüelas de fratura de coluna vertebral', 'T91.1 Sequelas de frat de coluna vertebral'),
  ('T912', 'Seqüelas de outra fratura do tórax e da pelve', 'T91.2 Sequelas de outr frat do torax e da pelve'),
  ('T913', 'Seqüelas de traumatismo de medula espinhal', 'T91.3 Sequelas de traum de medula espinhal'),
  ('T914', 'Seqüelas de traumatismo de órgãos intratorácicos', 'T91.4 Sequelas de traum de orgaos intratoracicos'),
  ('T915', 'Seqüelas de traumatismo de órgãos intra-abdominais e órgãos pélvicos', 'T91.5 Sequelas traum org intra-abdominais e pelv'),
  ('T918', 'Seqüelas de outros traumatismos especificados do pescoço e do tronco', 'T91.8 Sequelas outr traum espec pescoco e tronco'),
  ('T919', 'Seqüelas de traumatismo não especificado do pescoço e do tronco', 'T91.9 Sequelas de traum NE do pescoco e do tronco'),
  ('T92', 'Seqüelas de traumatismos do membro superior', 'T92 Sequelas de traum do membro super'),
  ('T920', 'Seqüelas de ferimento do membro superior', 'T92.0 Sequelas de ferim do membro super'),
  ('T921', 'Seqüelas de fratura do braço', 'T92.1 Sequelas de frat do braco'),
  ('T922', 'Seqüelas de fratura ao nível do punho e da mão', 'T92.2 Sequelas de frat ao nivel do punho e da mao'),
  ('T923', 'Seqüelas de luxação, entorse e distensão do membro superior', 'T92.3 Sequelas luxacao entorse distensao membr sup'),
  ('T924', 'Seqüelas de traumatismo de nervo de membro superior', 'T92.4 Sequelas de traum de nervo de membro super'),
  ('T925', 'Seqüelas de traumatismo de músculo e tendão do membro superior', 'T92.5 Sequelas traum musculo tendao membro super'),
  ('T926', 'Seqüelas de esmagamento e amputação traumática do membro superior', 'T92.6 Sequelas de esmag e amput traum membro super'),
  ('T928', 'Seqüelas de outros traumatismos especificados do membro superior', 'T92.8 Sequelas de outr traum espec do membro super'),
  ('T929', 'Seqüelas de traumatismo não especificado do membro superior', 'T92.9 Sequelas de traum NE do membro super'),
  ('T93', 'Seqüelas de traumatismos do membro inferior', 'T93 Sequelas de traum do membro infer'),
  ('T930', 'Seqüelas de ferimento do membro inferior', 'T93.0 Sequelas de ferim do membro infer'),
  ('T931', 'Seqüelas de fratura do fêmur', 'T93.1 Sequelas de frat do femur'),
  ('T932', 'Seqüelas de outras fraturas do membro inferior', 'T93.2 Sequelas de outr frat do membro infer'),
  ('T933', 'Seqüelas de luxação, entorse e distensão do membro inferior', 'T93.3 Sequelas luxacao entorse distensao membr inf'),
  ('T934', 'Seqüelas de traumatismo de nervo do membro inferior', 'T93.4 Sequelas de traum de nervo do membro infer'),
  ('T935', 'Seqüelas de traumatismo de músculo e tendão do membro inferior', 'T93.5 Sequelas traum musculo tendao membro infer'),
  ('T936', 'Seqüelas de esmagamento e amputação traumática do membro inferior', 'T93.6 Sequelas de esmag e amput traum membro infer'),
  ('T938', 'Seqüelas de outros traumatismos especificados do membro inferior', 'T93.8 Sequelas de outr traum espec do membro infer'),
  ('T939', 'Seqüelas de traumatismo não especificado do membro inferior', 'T93.9 Sequelas de traum NE do membro infer'),
  ('T94', 'Seqüelas de traumatismos envolvendo múltiplas regiões do corpo e as não especificadas', 'T94 Sequelas traum envolv mult reg corpo e NE'),
  ('T940', 'Seqüelas de traumatismos envolvendo regiões múltiplas do corpo', 'T94.0 Sequelas de traum envolv regioes mult corpo'),
  ('T941', 'Seqüelas de traumatismos não especificados por regiões do corpo', 'T94.1 Sequelas de traum NE p/regioes do corpo'),
  ('T95', 'Seqüelas de queimaduras, corrosões e geladuras', 'T95 Sequelas de queim corrosoes e geladuras'),
  ('T950', 'Seqüelas de queimadura, corrosão e geladura da cabeça e pescoço', 'T95.0 Sequelas queim corrosao gelad cabeca pescoco'),
  ('T951', 'Seqüelas de queimadura, corrosão e geladura do tronco', 'T95.1 Sequelas de queim corrosao e geladura tronco'),
  ('T952', 'Seqüelas de queimadura, corrosão e geladura do membro superior', 'T95.2 Sequelas queim corrosao geladura membro sup'),
  ('T953', 'Seqüelas de queimadura, corrosão e geladura do membro inferior', 'T95.3 Sequelas queim corrosao geladura membro inf'),
  ('T954', 'Seqüelas de queimadura e corrosão classificável só de acordo com a extensão da área corporal envolvida', 'T95.4 Seq queim corros class ext area corp envolv'),
  ('T958', 'Seqüelas de outra queimadura, corrosões e geladuras especificadas', 'T95.8 Sequelas outr queim corrosoes gelad espec'),
  ('T959', 'Seqüelas de queimadura, corrosão e geladura de local não especificado', 'T95.9 Sequelas de queim corrosao geladura local NE'),
  ('T96', 'Seqüelas de intoxicação por drogas, medicamentos e substâncias biológicas', 'T96 Sequelas intox drog medic subst biolog'),
  ('T96', 'Seqüelas de intoxicação por drogas, medicamentos e substâncias biológicas', 'T96 Sequelas intox drog medic subst biolog'),
  ('T97', 'Seqüelas de efeitos tóxicos de substâncias de origem predominantemente não-medicinal', 'T97 Sequelas efeit tox subst orig pred nao-medic'),
  ('T97', 'Seqüelas de efeitos tóxicos de substâncias de origem predominantemente não-medicinal', 'T97 Sequelas efeit tox subst orig pred nao-medic'),
  ('T98', 'Seqüelas de outros efeitos de causas externas e dos não especificados', 'T98 Sequelas outr efeitos causas externas e NE'),
  ('T980', 'Seqüelas dos efeitos da penetração de corpo estranho através de orifício natural', 'T98.0 Sequelas efeit penetr corpo estranh orif nat'),
  ('T981', 'Seqüelas em outros efeitos de causas externas e os não especificados', 'T98.1 Sequelas outr efeitos causas externas e NE'),
  ('T982', 'Seqüelas de algumas complicações precoces de traumatismos', 'T98.2 Sequelas algumas complic precoces de traum'),
  ('T983', 'Seqüelas de complicações dos cuidados médicos e cirúrgicos não classificados em outra parte', 'T98.3 Sequelas de complic cuidados med cirurg NCOP');
