INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('L00', 'Síndrome da pele escaldada estafilocócica do recém-nascido', 'L00 Sindr pele escaldada estafilococ recem-nasc'),
  ('L00', 'Síndrome da pele escaldada estafilocócica do recém-nascido', 'L00 Sindr pele escaldada estafilococ recem-nasc'),
  ('L01', 'Impetigo', 'L01 Impetigo'),
  ('L010', 'Impetigo (qualquer localização) (qualquer microorganismo)', 'L01.0 Impetigo'),
  ('L011', 'Impetiginização de outras dermatoses', 'L01.1 Impetiginizacao de outr dermatoses'),
  ('L02', 'Abscesso cutâneo, furúnculo e antraz', 'L02 Abscesso cutaneo furunculo e antraz'),
  ('L020', 'Abscesso cutâneo, furúnculo e antraz da face', 'L02.0 Abscesso cutaneo furunculo e antraz face'),
  ('L021', 'Abscesso cutâneo, furúnculo e antraz do pescoço', 'L02.1 Abscesso cutaneo furunculo e antraz pescoco'),
  ('L022', 'Abscesso cutâneo, furúnculo e antraz do tronco', 'L02.2 Abscesso cutaneo furunculo e antraz tronco'),
  ('L023', 'Abscesso cutâneo, furúnculo e antraz da nádega', 'L02.3 Abscesso cutaneo furunculo e antraz nadega'),
  ('L024', 'Abscesso cutâneo, furúnculo e antraz do(s) membro(s)', 'L02.4 Abscesso cutaneo furunculo e antraz membros'),
  ('L028', 'Abscesso cutâneo, furúnculo e antraz de outras localizações', 'L02.8 Abscesso cutaneo furunculo e antraz outr loc'),
  ('L029', 'Abscesso cutâneo, furúnculo e antraz de localização não especificada', 'L02.9 Abscesso cutaneo furunculo e antraz loc NE'),
  ('L03', 'Celulite (Flegmão)', 'L03 Celulite'),
  ('L030', 'Celulite de dedos das mãos e dos pés', 'L03.0 Celulite de dedos das maos e dos pes'),
  ('L031', 'Celulite de outras partes do(s) membro(s)', 'L03.1 Celulite de outr partes de membros'),
  ('L032', 'Celulite da face', 'L03.2 Celulite da face'),
  ('L033', 'Celulite do tronco', 'L03.3 Celulite do tronco'),
  ('L038', 'Celulite de outros locais', 'L03.8 Celulite de outr locais'),
  ('L039', 'Celulite não especificada', 'L03.9 Celulite NE'),
  ('L04', 'Linfadenite aguda', 'L04 Linfadenite aguda'),
  ('L040', 'Linfadenite aguda de face, cabeça e pescoço', 'L04.0 Linfadenite aguda de face cabeca e pescoco'),
  ('L041', 'Linfadenite aguda do tronco', 'L04.1 Linfadenite aguda do tronco'),
  ('L042', 'Linfadenite aguda de membro superior', 'L04.2 Linfadenite aguda de membro super'),
  ('L043', 'Linfadenite aguda de membro inferior', 'L04.3 Linfadenite aguda de membro infer'),
  ('L048', 'Linfadenite aguda de outras localizações', 'L04.8 Linfadenite aguda de outr localiz'),
  ('L049', 'Linfadenite aguda de localização não especificada', 'L04.9 Linfadenite aguda de localiz NE'),
  ('L05', 'Cisto pilonidal', 'L05 Cisto pilonidal'),
  ('L050', 'Cisto pilonidal com abscesso', 'L05.0 Cisto pilonidal c/abscesso'),
  ('L059', 'Cisto pilonidal sem abscesso', 'L05.9 Cisto pilonidal s/abscesso'),
  ('L08', 'Outras infecções localizadas da pele e do tecido subcutâneo', 'L08 Outr infecc localiz pele e tec subcutaneo'),
  ('L080', 'Piodermite', 'L08.0 Piodermite'),
  ('L081', 'Eritrasma', 'L08.1 Eritrasma'),
  ('L088', 'Outras infecções localizadas, especificadas, da pele e do tecido subcutâneo', 'L08.8 Outr infecc local espec pele tec subcutaneo'),
  ('L089', 'Infecção localizada da pele e do tecido subcutâneo, não especificada', 'L08.9 Infecc localiz pele e do tec subcutaneo NE'),
  ('L10', 'Pênfigo', 'L10 Penfigo'),
  ('L100', 'Pênfigo vulgar', 'L10.0 Penfigo vulgar'),
  ('L101', 'Pênfigo vegetante', 'L10.1 Penfigo vegetante'),
  ('L102', 'Pênfigo foliáceo', 'L10.2 Penfigo foliaceo'),
  ('L103', 'Pênfigo brasileiro (fogo selvagem)', 'L10.3 Penfigo brasileiro'),
  ('L104', 'Pênfigo eritematoso', 'L10.4 Penfigo eritematoso'),
  ('L105', 'Pênfigo induzido por drogas', 'L10.5 Penfigo induz p/drogas'),
  ('L108', 'Outras formas de pênfigo', 'L10.8 Outr form de penfigo'),
  ('L109', 'Pênfigo, não especificado', 'L10.9 Penfigo NE'),
  ('L11', 'Outras afecções acantolíticas', 'L11 Outr afeccoes acantoliticas'),
  ('L110', 'Ceratose folicular adquirida', 'L11.0 Ceratose folicular adquir'),
  ('L111', 'Dermatose acantolítica transitória (Grover)', 'L11.1 Dermatose acantolitica transitoria'),
  ('L118', 'Outras afecções acantolíticas especificadas', 'L11.8 Outr afeccoes acantoliticas espec'),
  ('L119', 'Afecções acantolíticas não especificadas', 'L11.9 Afeccoes acantoliticas NE'),
  ('L12', 'Penfigóide', 'L12 Penfigoide'),
  ('L120', 'Penfigóide bolhoso', 'L12.0 Penfigoide bolhoso'),
  ('L121', 'Penfigóide cicatricial', 'L12.1 Penfigoide cicatricial'),
  ('L122', 'Doença bolhosa crônica da infância', 'L12.2 Doenc bolhosa cronica da infancia'),
  ('L123', 'Epidermólise bolhosa adquirida', 'L12.3 Epidermolise bolhosa adquir'),
  ('L128', 'Outras formas de penfigóide', 'L12.8 Outr form de penfigoide'),
  ('L129', 'Penfigóide, não especificado', 'L12.9 Penfigoide NE'),
  ('L13', 'Outras afecções bolhosas', 'L13 Outr afeccoes bolhosas'),
  ('L130', 'Dermatite herpetiforme', 'L13.0 Dermatite herpetiforme'),
  ('L131', 'Dermatite pustular subcorneana', 'L13.1 Dermatite pustular subcorneana'),
  ('L138', 'Outras afecções bolhosas especificadas', 'L13.8 Outr afeccoes bolhosas espec'),
  ('L139', 'Doença bolhosa, não especificada', 'L13.9 Doenc bolhosa NE'),
  ('L14', 'Afecções bolhosas em doenças classificadas em outra parte', 'L14 Afeccoes bolhosas em doenc COP'),
  ('L14', 'Afecções bolhosas em doenças classificadas em outra parte', 'L14 Afeccoes bolhosas em doenc COP'),
  ('L20', 'Dermatite atópica', 'L20 Dermatite atopica'),
  ('L200', 'Prurigo de Besnier', 'L20.0 Prurigo de Besnier'),
  ('L208', 'Outras dermatites atópicas', 'L20.8 Outr dermatites atopicas'),
  ('L209', 'Dermatite atópica, não especificada', 'L20.9 Dermatite atopica NE'),
  ('L21', 'Dermatite seborréica', 'L21 Dermatite seborreica'),
  ('L210', 'Seborréia do couro cabeludo', 'L21.0 Seborreia do couro cabeludo'),
  ('L211', 'Dermatite seborréica infantil', 'L21.1 Dermatite seborreica infantil'),
  ('L218', 'Outras dermatites seborréicas', 'L21.8 Outr dermatites seborreicas'),
  ('L219', 'Dermatite seborréica, não especificada', 'L21.9 Dermatite seborreica NE'),
  ('L22', 'Dermatite das fraldas', 'L22 Dermatite das fraldas'),
  ('L22', 'Dermatite das fraldas', 'L22 Dermatite das fraldas'),
  ('L23', 'Dermatites alérgicas de contato', 'L23 Dermatites alergicas de contato'),
  ('L230', 'Dermatite alérgica de contato devida a metais', 'L23.0 Dermatite alergica de contato dev metais'),
  ('L231', 'Dermatite alérgica de contato devida a adesivos', 'L23.1 Dermatite alergica de contato dev adesivos'),
  ('L232', 'Dermatite alérgica de contato devida a cosméticos', 'L23.2 Dermatite alergica de contato dev cosmeticos'),
  ('L233', 'Dermatite alérgica de contato devido a drogas em contato com a pele', 'L23.3 Dermatite alerg contato dev drogas cont pele'),
  ('L234', 'Dermatite alérgica de contato devida a corantes', 'L23.4 Dermatite alergica de contato dev corantes'),
  ('L235', 'Dermatite alérgica de contato devida a outros produtos químicos', 'L23.5 Dermatite alergica contato dev out prod quim'),
  ('L236', 'Dermatite alérgica de contato devida a alimentos em contato com a pele', 'L23.6 Dermatite alergica contat dev alim cont pele'),
  ('L237', 'Dermatite alérgica de contato devido a plantas, exceto alimentos', 'L23.7 Dermatite alerg contato dev plantas exc alim'),
  ('L238', 'Dermatite alérgica de contato devido a outros agentes', 'L23.8 Dermatite alergica contato dev outr agentes'),
  ('L239', 'Dermatite alérgica de contato, de causa não especificada', 'L23.9 Dermatite alergica de contato de causa NE'),
  ('L24', 'Dermatites de contato por irritantes', 'L24 Dermatites de contato p/irritantes'),
  ('L240', 'Dermatite de contato por irritantes devida a detergentes', 'L24.0 Dermatite contato p/irrit dev detergentes'),
  ('L241', 'Dermatite de contato por irritantes devido a óleos e gorduras', 'L24.1 Dermatite contato p/irrit dev oleos gorduras'),
  ('L242', 'Dermatite de contato por irritantes devida a solventes', 'L24.2 Dermatite contato p/irritantes dev solventes'),
  ('L243', 'Dermatite de contato por irritantes devida a cosméticos', 'L24.3 Dermatite contato p/irrit dev cosmeticos'),
  ('L244', 'Dermatite de contato por irritantes devida a drogas em contato com a pele', 'L24.4 Dermatite cont p/irrit dev drogas cont pele'),
  ('L245', 'Dermatite de contato por irritantes devida a outros produtos químicos', 'L24.5 Dermatite contato p/irrit dev outr prod quim'),
  ('L246', 'Dermatite de contato por irritantes devida a alimentos em contato com a pele', 'L24.6 Dermatite contato p/irrit dev alim cont pele'),
  ('L247', 'Dermatite de contato por irritantes devido a plantas, exceto alimentos', 'L24.7 Dermatite cont p/irrit dev plantas exc alim'),
  ('L248', 'Dermatite de contato por irritantes devido a outros agentes', 'L24.8 Dermatite contato p/irrit dev outr agentes'),
  ('L249', 'Dermatite de contato por irritantes, de causa não especificada', 'L24.9 Dermatite contato p/irritantes de causa NE'),
  ('L25', 'Dermatite de contato não especificada', 'L25 Dermatite de contato NE'),
  ('L250', 'Dermatite de contato não especificada devida a cosméticos', 'L25.0 Dermatite de contato NE dev cosmeticos'),
  ('L251', 'Dermatite de contato não especificada devida a drogas em contato com a pele', 'L25.1 Dermatite de contato NE dev drogas cont pele'),
  ('L252', 'Dermatite de contato não especificada devida a corantes', 'L25.2 Dermatite de contato NE dev corantes'),
  ('L253', 'Dermatite de contato não especificada devida a outros produtos químicos', 'L25.3 Dermatite de contato NE dev outr prod quim'),
  ('L254', 'Dermatite de contato não especificada devida a alimentos em contato com a pele', 'L25.4 Dermatite de contato NE dev alim cont pele'),
  ('L255', 'Dermatite de contato não especificada devida a plantas, exceto alimentos', 'L25.5 Dermatite de contato NE dev plantas exc alim'),
  ('L258', 'Dermatite de contato não especificada devida a outros agentes', 'L25.8 Dermatite de contato NE dev outr agentes'),
  ('L259', 'Dermatite de contato não especificada, de causa não especificada', 'L25.9 Dermatite de contato NE de causa NE'),
  ('L26', 'Dermatite esfoliativa', 'L26 Dermatite esfoliativa'),
  ('L26', 'Dermatite esfoliativa', 'L26 Dermatite esfoliativa'),
  ('L27', 'Dermatite devida a substâncias de uso interno', 'L27 Dermatite dev subst de uso interno'),
  ('L270', 'Erupção cutânea generalizada devida a drogas e medicamentos', 'L27.0 Erupcao cutanea generaliz dev drogas medic'),
  ('L271', 'Erupção cutânea localizada devida a drogas e medicamentos', 'L27.1 Erupcao cutanea localizada dev drogas medic'),
  ('L272', 'Dermatite devida à ingestão de alimentos', 'L27.2 Dermatite dev ingestao de alimentos'),
  ('L278', 'Dermatite devida a outras substâncias de uso interno', 'L27.8 Dermatite dev outr subst de uso interno'),
  ('L279', 'Dermatite devida a substância não especificada de uso interno', 'L27.9 Dermatite dev subst NE de uso interno'),
  ('L28', 'Líquen simples crônico e prurigo', 'L28 Liquen simples cronico e prurigo'),
  ('L280', 'Líquen simples crônico', 'L28.0 Liquen simples cronico'),
  ('L281', 'Prurigo nodular', 'L28.1 Prurigo nodular'),
  ('L282', 'Outras formas de prurigo', 'L28.2 Outr form de prurigo'),
  ('L29', 'Prurido', 'L29 Prurido'),
  ('L290', 'Prurido anal', 'L29.0 Prurido anal'),
  ('L291', 'Prurido escrotal', 'L29.1 Prurido escrotal'),
  ('L292', 'Prurido vulvar', 'L29.2 Prurido vulvar'),
  ('L293', 'Prurido anogenital, não especificado', 'L29.3 Prurido anogenital NE'),
  ('L298', 'Outras formas de prurido', 'L29.8 Outr form de prurido'),
  ('L299', 'Prurido não especificado', 'L29.9 Prurido NE'),
  ('L30', 'Outras dermatites', 'L30 Outr dermatites'),
  ('L300', 'Dermatite numular', 'L30.0 Dermatite numular'),
  ('L301', 'Disidrose (pompholyx)', 'L30.1 Disidrose'),
  ('L302', 'Autossensibilização cutânea', 'L30.2 Autossensibilizacao cutanea'),
  ('L303', 'Dermatite infectada', 'L30.3 Dermatite infectada'),
  ('L304', 'Intertrigo eritematoso', 'L30.4 Intertrigo eritematoso'),
  ('L305', 'Pitiríase alba', 'L30.5 Pitiriase alba'),
  ('L308', 'Outras dermatites especificadas', 'L30.8 Outr dermatites espec'),
  ('L309', 'Dermatite não especificada', 'L30.9 Dermatite NE'),
  ('L40', 'Psoríase', 'L40 Psoriase'),
  ('L400', 'Psoríase vulgar', 'L40.0 Psoriase vulgar'),
  ('L401', 'Psoríase pustulosa generalizada', 'L40.1 Psoriase pustulosa generalizada'),
  ('L402', 'Acrodermatite contínua', 'L40.2 Acrodermatite continua'),
  ('L403', 'Pustulose palmar e plantar', 'L40.3 Pustulose palmar e plantar'),
  ('L404', 'Psoríase gutata', 'L40.4 Psoriase gutata'),
  ('L405', 'Artropatia psoriásica', 'L40.5 Artropatia psoriasica'),
  ('L408', 'Outras formas de psoríase', 'L40.8 Outr form de psoriase'),
  ('L409', 'Psoríase não especificada', 'L40.9 Psoriase NE'),
  ('L41', 'Parapsoríase', 'L41 Parapsoriase'),
  ('L410', 'Pitiríase liquenóide e varioliforme aguda', 'L41.0 Pitiriase liquenoide e varioliforme aguda'),
  ('L411', 'Pitiríase liquenóide crônica', 'L41.1 Pitiriase liquenoide cronica'),
  ('L412', 'Papulose linfomatóide', 'L41.2 Papulose linfomatoide'),
  ('L413', 'Parapsoríase de pequenas placas', 'L41.3 Parapsoriase de pequenas placas'),
  ('L414', 'Parapsoríase de grandes placas', 'L41.4 Parapsoriase de grandes placas'),
  ('L415', 'Parapsoríase retiforme', 'L41.5 Parapsoriase retiforme'),
  ('L418', 'Outras parapsoríases', 'L41.8 Outr parapsoriases'),
  ('L419', 'Parapsoríase, não especificada', 'L41.9 Parapsoriase NE'),
  ('L42', 'Pitiríase rósea', 'L42 Pitiriase rosea'),
  ('L42', 'Pitiríase rósea', 'L42 Pitiriase rosea'),
  ('L43', 'Líquen plano', 'L43 Liquen plano'),
  ('L430', 'Líquen plano hipertrófico', 'L43.0 Liquen plano hipertrofico'),
  ('L431', 'Líquen plano bolhoso', 'L43.1 Liquen plano bolhoso'),
  ('L432', 'Reação liquenóide a droga', 'L43.2 Reacao liquenoide a droga'),
  ('L433', 'Líquen plano subagudo (ativo)', 'L43.3 Liquen plano subagudo'),
  ('L438', 'Outras formas de líquen plano', 'L43.8 Outr form de liquen plano'),
  ('L439', 'Líquen plano, não especificado', 'L43.9 Liquen plano NE'),
  ('L44', 'Outras afecções pápulo-descamativas', 'L44 Outr afeccoes papulo-descamativas'),
  ('L440', 'Pitiríase rubra pilar', 'L44.0 Pitiriase rubra pilar'),
  ('L441', 'Líquen nítido', 'L44.1 Liquen nitido'),
  ('L442', 'Líquen estriado', 'L44.2 Liquen estriado'),
  ('L443', 'Líquen rubro moniliforme', 'L44.3 Liquen rubro moniliforme'),
  ('L444', 'Acrodermatite papular infantil (Síndrome de Gianotti-Crosti)', 'L44.4 Acrodermatite papular infantil'),
  ('L448', 'Outras afecções pápulo-descamativas especificadas', 'L44.8 Outr afeccoes papulo-descamativas espec'),
  ('L449', 'Afecções pápulo-descamativas, não especificadas', 'L44.9 Afeccoes papulo-descamativas NE'),
  ('L45', 'Afecções pápulo-descamativas em doenças classificadas em outra parte', 'L45 Afeccoes papulo-descamativas em doenc COP'),
  ('L45', 'Afecções pápulo-descamativas em doenças classificadas em outra parte', 'L45 Afeccoes papulo-descamativas em doenc COP'),
  ('L50', 'Urticária', 'L50 Urticaria'),
  ('L500', 'Urticária alérgica', 'L50.0 Urticaria alergica'),
  ('L501', 'Urticária idiopática', 'L50.1 Urticaria idiopatica'),
  ('L502', 'Urticária devida a frio e a calor', 'L50.2 Urticaria dev frio e a calor'),
  ('L503', 'Urticária dermatográfica', 'L50.3 Urticaria dermatografica'),
  ('L504', 'Urticária vibratória', 'L50.4 Urticaria vibratoria'),
  ('L505', 'Urticária colinérgica', 'L50.5 Urticaria colinergica'),
  ('L506', 'Urticária de contato', 'L50.6 Urticaria de contato'),
  ('L508', 'Outras urticárias', 'L50.8 Outr urticarias'),
  ('L509', 'Urticária não especificada', 'L50.9 Urticaria NE'),
  ('L51', 'Eritema polimorfo (eritema multiforme)', 'L51 Eritema polimorfo'),
  ('L510', 'Eritema multiforme não bolhoso', 'L51.0 Eritema multiforme nao bolhoso'),
  ('L511', 'Eritema multiforme bolhoso', 'L51.1 Eritema multiforme bolhoso'),
  ('L512', 'Necrólise epidérmica tóxica (Síndrome de Lyell)', 'L51.2 Necrolise epidermica toxica'),
  ('L518', 'Outras formas de eritema multiforme', 'L51.8 Outr form de eritema multiforme'),
  ('L519', 'Eritema multiforme, não especificado', 'L51.9 Eritema multiforme NE'),
  ('L52', 'Eritema nodoso', 'L52 Eritema nodoso'),
  ('L52', 'Eritema nodoso', 'L52 Eritema nodoso'),
  ('L53', 'Outras afecções eritematosas', 'L53 Outr afeccoes eritematosas'),
  ('L530', 'Eritema tóxico', 'L53.0 Eritema toxico'),
  ('L531', 'Eritema anular centrífugo', 'L53.1 Eritema anular centrifugo'),
  ('L532', 'Eritema marginado', 'L53.2 Eritema marginado'),
  ('L533', 'Outras formas de eritema figurado crônico', 'L53.3 Outr form de eritema figurado cronico'),
  ('L538', 'Outras afecções eritematosas especificadas', 'L53.8 Outr afeccoes eritematosas espec'),
  ('L539', 'Afecções eritematosas, não especificadas', 'L53.9 Afeccoes eritematosas NE'),
  ('L54', 'Eritema em doenças classificadas em outra parte', 'L54 Eritema em doenc COP'),
  ('L540', 'Eritema marginado na febre reumática aguda', 'L54.0 Eritema marginado na febre reumatica aguda'),
  ('L548', 'Eritema em outras doenças classificadas em outra parte', 'L54.8 Eritema em outr doenc COP'),
  ('L55', 'Queimadura solar', 'L55 Queim solar'),
  ('L550', 'Queimadura solar de primeiro grau', 'L55.0 Queim solar de 1.grau'),
  ('L551', 'Queimadura solar de segundo grau', 'L55.1 Queim solar de 2.grau'),
  ('L552', 'Queimadura solar de terceiro grau', 'L55.2 Queim solar de 3.grau'),
  ('L558', 'Outras queimaduras solares', 'L55.8 Outr queim solares'),
  ('L559', 'Queimadura solar, não especificada', 'L55.9 Queim solar NE'),
  ('L56', 'Outras alterações agudas da pele devidas a radiação ultravioleta', 'L56 Outr alterac agud pele dev rad ultravioleta'),
  ('L560', 'Resposta fototóxica a drogas', 'L56.0 Resposta fototoxica a drogas'),
  ('L561', 'Resposta fotoalérgica a drogas', 'L56.1 Resposta fotoalergica a drogas'),
  ('L562', 'Dermatite por fotocontato (dermatite do berloque)', 'L56.2 Dermatite p/fotocontato'),
  ('L563', 'Urticária solar', 'L56.3 Urticaria solar'),
  ('L564', 'Erupção polimorfa à luz', 'L56.4 Erupcao polimorfa a luz'),
  ('L568', 'Outras alterações agudas especificadas da pele devidas a radiação ultravioleta', 'L56.8 Outr alt agud esp pele dev rad ultravioleta'),
  ('L569', 'Alterações agudas da pele devidas a radiação ultravioleta, não especificadas', 'L56.9 Alteracoes agud pele dev rad ultravioleta NE'),
  ('L57', 'Alterações da pele devidas à exposição crônica à radiação não ionizante', 'L57 Alter pele dev expos cron rad nao ionizante'),
  ('L570', 'Ceratose actínica', 'L57.0 Ceratose actinica'),
  ('L571', 'Reticulóide actínica', 'L57.1 Reticuloide actinica'),
  ('L572', 'Cútis romboidal da nuca', 'L57.2 Cutis romboidal da nuca'),
  ('L573', 'Poiquilodermia de Civatte', 'L57.3 Poiquilodermia de Civatte'),
  ('L574', 'Cútis laxa senil', 'L57.4 Cutis laxa senil'),
  ('L575', 'Granuloma actínico', 'L57.5 Granuloma actinico'),
  ('L578', 'Outras alterações da pele devidas a exposição crônica à radiação não-ionizante', 'L57.8 Outr alt pele dev expos cron rad nao-ioniz'),
  ('L579', 'Alterações da pele devidas a exposição crônica a radiação não-ionizante, não especificadas', 'L57.9 Alter pele dev expos cron rad nao-ioniz NE'),
  ('L58', 'Radiodermatite', 'L58 Radiodermatite'),
  ('L580', 'Radiodermatite aguda', 'L58.0 Radiodermatite aguda'),
  ('L581', 'Radiodermatite crônica', 'L58.1 Radiodermatite cronica'),
  ('L589', 'Radiodermatite, não especificada', 'L58.9 Radiodermatite NE'),
  ('L59', 'Outras afecções da pele e do tecido subcutâneo relacionadas com a radiação', 'L59 Outr afecc pele tec subcutan relac radiacao'),
  ('L590', 'Eritema devido ao calor ou ao fogo (dermatite ab igne)', 'L59.0 Eritema dev calor ou ao fogo'),
  ('L598', 'Outras afecções especificadas da pele e do tecido subcutâneo relacionadas com a radiação', 'L59.8 Outr afecc espec pele tec subcutaneo rel rad'),
  ('L599', 'Afecções da pele e do tecido subcutâneo relacionadas com a radiação, não especificadas', 'L59.9 Afeccoes pele tec subcutaneo relac rad NE'),
  ('L60', 'Afecções das unhas', 'L60 Afeccoes das unhas'),
  ('L600', 'Unha encravada', 'L60.0 Unha encravada'),
  ('L601', 'Onicólise', 'L60.1 Onicolise'),
  ('L602', 'Onicogrifose', 'L60.2 Onicogrifose'),
  ('L603', 'Distrofia ungueal', 'L60.3 Distrofia ungueal'),
  ('L604', 'Linhas de Beau', 'L60.4 Linhas de Beau'),
  ('L605', 'Síndrome das unhas amareladas', 'L60.5 Sindr das unhas amareladas'),
  ('L608', 'Outras afecções das unhas', 'L60.8 Outr afeccoes das unhas'),
  ('L609', 'Afecções das unhas, não especificadas', 'L60.9 Afeccoes das unhas NE'),
  ('L62', 'Afecções das unhas em doenças classificadas em outra parte', 'L62 Afeccoes das unhas em doenc COP'),
  ('L620', 'Paquidermoperiostose com unhas hipocráticas (em vidro de relógio)', 'L62.0 Paquidermoperiostose c/unhas hipocraticas'),
  ('L628', 'Afecções das unhas em outras doenças classificadas em outra parte', 'L62.8 Afeccoes das unhas em outr doenc COP'),
  ('L63', 'Alopécia areata', 'L63 Alopecia areata'),
  ('L630', 'Alopécia total (capitis)', 'L63.0 Alopecia total'),
  ('L631', 'Alopécia universal', 'L63.1 Alopecia universal'),
  ('L632', 'Ofíase', 'L63.2 Ofiase'),
  ('L638', 'Outras formas de alopécia areata', 'L63.8 Outr form de alopecia areata'),
  ('L639', 'Alopécia areata, não especificada', 'L63.9 Alopecia areata NE'),
  ('L64', 'Alopécia androgênica', 'L64 Alopecia androgenica'),
  ('L640', 'Alopécia androgênica induzida por droga', 'L64.0 Alopecia androgenica induz p/droga'),
  ('L648', 'Outras alopécias androgênicas', 'L64.8 Outr alopecias androgenicas'),
  ('L649', 'Alopécia androgênica, não especificada', 'L64.9 Alopecia androgenica NE'),
  ('L65', 'Outras formas não cicatriciais da perda de cabelos ou pêlos', 'L65 Outr form nao cicatric perda cabelos pelos'),
  ('L650', 'Eflúvio telógeno', 'L65.0 Efluvio telogeno'),
  ('L651', 'Eflúvio anágeno', 'L65.1 Efluvio anageno'),
  ('L652', 'Alopécia mucinosa', 'L65.2 Alopecia mucinosa'),
  ('L658', 'Outras formas, especificadas, não cicatriciais, de perda de cabelos ou pêlos', 'L65.8 Outr form espec n cicatric perda cabelo pelo'),
  ('L659', 'Perda de cabelos ou pêlos não cicatriciais, não especificada', 'L65.9 Perda de cabelos ou p/nao cicatriciais NE'),
  ('L66', 'Alopécia cicatricial (perda de cabelos ou pêlos, cicatricial)', 'L66 Alopecia cicatricial'),
  ('L660', 'Pseudopelada', 'L66.0 Pseudopelada'),
  ('L661', 'Líquen planopilar', 'L66.1 Liquen planopilar'),
  ('L662', 'Foliculite descalvante', 'L66.2 Foliculite descalvante'),
  ('L663', 'Perifoliculite abscedante da cabeça', 'L66.3 Perifoliculite abscedante da cabeca'),
  ('L664', 'Foliculite uleritematosa reticulada', 'L66.4 Foliculite uleritematosa reticulada'),
  ('L668', 'Outras formas de alopécia cicatricial', 'L66.8 Outr form de alopecia cicatricial'),
  ('L669', 'Alopécia cicatricial, não especificada', 'L66.9 Alopecia cicatricial NE'),
  ('L67', 'Anormalidades da cor e do pedículo dos cabelos e dos pêlos', 'L67 Anormalidades cor e pediculo cabelos pelos'),
  ('L670', 'Tricorrexe nodosa', 'L67.0 Tricorrexe nodosa'),
  ('L671', 'Variações da cor dos cabelos ou pêlos', 'L67.1 Variacoes da cor dos cabelos ou pelos'),
  ('L678', 'Outras anormalidades da cor e do pedículo dos cabelos ou pêlos', 'L67.8 Outr anorm cor pediculo dos cabelos ou pelos'),
  ('L679', 'Anormalidades da cor e do pedículo dos cabelos e dos pêlos, não especificadas', 'L67.9 Anorma cor pediculo dos cabelos e pelos NE'),
  ('L68', 'Hipertricose', 'L68 Hipertricose'),
  ('L680', 'Hirsutismo', 'L68.0 Hirsutismo'),
  ('L681', 'Hipertricose lanuginosa adquirida', 'L68.1 Hipertricose lanuginosa adquir'),
  ('L682', 'Hipertricose localizada', 'L68.2 Hipertricose localizada'),
  ('L683', 'Politríquia', 'L68.3 Politriquia'),
  ('L688', 'Outras formas de hipertricose', 'L68.8 Outr form de hipertricose'),
  ('L689', 'Hipertricose, não especificada', 'L68.9 Hipertricose NE'),
  ('L70', 'Acne', 'L70 Acne'),
  ('L700', 'Acne vulgar', 'L70.0 Acne vulgar'),
  ('L701', 'Acne conglobata', 'L70.1 Acne conglobata'),
  ('L702', 'Acne varioliforme', 'L70.2 Acne varioliforme'),
  ('L703', 'Acne tropical', 'L70.3 Acne tropical'),
  ('L704', 'Acne infantil', 'L70.4 Acne infantil'),
  ('L705', 'Acne escoriada das mulheres jovens', 'L70.5 Acne escoriada das mulheres jovens'),
  ('L708', 'Outras formas de acne', 'L70.8 Outr form de acne'),
  ('L709', 'Acne, não especificada', 'L70.9 Acne NE'),
  ('L71', 'Rosácea', 'L71 Rosacea'),
  ('L710', 'Dermatite perioral', 'L71.0 Dermatite perioral'),
  ('L711', 'Rinofima', 'L71.1 Rinofima'),
  ('L718', 'Outras formas de rosácea', 'L71.8 Outr form de rosacea'),
  ('L719', 'Rosácea, não especificada', 'L71.9 Rosacea NE'),
  ('L72', 'Cistos foliculares da pele e do tecido subcutâneo', 'L72 Cistos foliculares da pele e tec subcutaneo'),
  ('L720', 'Cisto epidérmico', 'L72.0 Cisto epidermico'),
  ('L721', 'Cisto triquilemal', 'L72.1 Cisto triquilemal'),
  ('L722', 'Esteatocistoma múltiplo', 'L72.2 Esteatocistoma mult'),
  ('L728', 'Outras formas de cistos foliculares da pele e do tecido subcutâneo', 'L72.8 Outr form cistos foliculares pele tec subcut'),
  ('L729', 'Cisto folicular, não especificado da pele e do tecido subcutâneo', 'L72.9 Cisto folicular NE da pele e tec subcutaneo'),
  ('L73', 'Outras afecções foliculares', 'L73 Outr afeccoes foliculares'),
  ('L730', 'Acne quelóide', 'L73.0 Acne queloide'),
  ('L731', 'Pseudofoliculite da barba', 'L73.1 Pseudofoliculite da barba'),
  ('L732', 'Hidradenite supurativa', 'L73.2 Hidradenite supurativa'),
  ('L738', 'Outras afecções foliculares especificadas', 'L73.8 Outr afeccoes foliculares espec'),
  ('L739', 'Afecções foliculares, não especificadas', 'L73.9 Afeccoes foliculares NE'),
  ('L74', 'Afecções das glândulas sudoríparas écrinas', 'L74 Afeccoes das gland sudoriparas ecrinas'),
  ('L740', 'Miliária rubra', 'L74.0 Miliaria rubra'),
  ('L741', 'Miliária cristalina', 'L74.1 Miliaria cristalina'),
  ('L742', 'Miliária profunda', 'L74.2 Miliaria profunda'),
  ('L743', 'Miliária, não especificada', 'L74.3 Miliaria NE'),
  ('L744', 'Anidrose', 'L74.4 Anidrose'),
  ('L748', 'Outras afecções das glândulas sudoríparas écrinas', 'L74.8 Outr afeccoes das gland sudoriparas ecrinas'),
  ('L749', 'Afecções das glândulas sudoríparas écrinas, não especificadas', 'L74.9 Afeccoes das gland sudoriparas ecrinas NE'),
  ('L75', 'Afecções das glândulas sudoríparas apócrinas', 'L75 Afeccoes das gland sudoriparas apocrinas'),
  ('L750', 'Bromidrose', 'L75.0 Bromidrose'),
  ('L751', 'Cromidrose', 'L75.1 Cromidrose'),
  ('L752', 'Miliária apócrina', 'L75.2 Miliaria apocrina'),
  ('L758', 'Outras afecções das glândulas sudoríparas apócrinas', 'L75.8 Outr afeccoes gland sudoriparas apocrinas'),
  ('L759', 'Afecções de glândulas sudoríparas apócrinas, não especificadas', 'L75.9 Afeccoes de gland sudoriparas apocrinas NE'),
  ('L80', 'Vitiligo', 'L80 Vitiligo'),
  ('L80', 'Vitiligo', 'L80 Vitiligo'),
  ('L81', 'Outros transtornos da pigmentação', 'L81 Outr transt da pigmentacao'),
  ('L810', 'Hiperpigmentação pós-inflamatória', 'L81.0 Hiperpigmentacao pos-inflam'),
  ('L811', 'Cloasma', 'L81.1 Cloasma'),
  ('L812', 'Sardas', 'L81.2 Sardas'),
  ('L813', 'Manchas café-com-leite', 'L81.3 Manchas cafe-com-leite'),
  ('L814', 'Outras formas de hiperpigmentação pela melanina', 'L81.4 Outr form de hiperpigmentacao p/melanina'),
  ('L815', 'Leucodermia não classificada em outra parte', 'L81.5 Leucodermia NCOP'),
  ('L816', 'Outros transtornos ligados à diminuição da formação de melanina', 'L81.6 Outr transt lig diminuicao formacao melanina'),
  ('L817', 'Dermatose purpúrica pigmentada', 'L81.7 Dermatose purpurica pigmentada'),
  ('L818', 'Outros transtornos especificados da pigmentação', 'L81.8 Outr transt espec da pigmentacao'),
  ('L819', 'Transtorno da pigmentação, não especificado', 'L81.9 Transt da pigmentacao NE'),
  ('L82', 'Ceratose seborréica', 'L82 Ceratose seborreica'),
  ('L82', 'Ceratose seborréica', 'L82 Ceratose seborreica'),
  ('L83', 'Acantose nigricans', 'L83 Acantose nigricans'),
  ('L83', 'Acantose nigricans', 'L83 Acantose nigricans'),
  ('L84', 'Calos e calosidades', 'L84 Calos e calosidades'),
  ('L84', 'Calos e calosidades', 'L84 Calos e calosidades'),
  ('L85', 'Outras formas de espessamento epidérmico', 'L85 Outr form de espessamento epidermico'),
  ('L850', 'Ictiose adquirida', 'L85.0 Ictiose adquir'),
  ('L851', 'Ceratose adquirida (ceratodermia) palmar e plantar', 'L85.1 Ceratose adquir palmar e plantar'),
  ('L852', 'Ceratose punctata (palmar e plantar)', 'L85.2 Ceratose punctata'),
  ('L853', 'Xerose cutânea', 'L85.3 Xerose cutanea'),
  ('L858', 'Outras formas de espessamento epidérmico', 'L85.8 Outr form de espessamento epidermico'),
  ('L859', 'Espessamento epidérmico, não especificado', 'L85.9 Espessamento epidermico NE'),
  ('L86', 'Ceratodermia em doenças classificadas em outra parte', 'L86 Ceratodermia em doenc COP'),
  ('L86', 'Ceratodermia em doenças classificadas em outra parte', 'L86 Ceratodermia em doenc COP'),
  ('L87', 'Transtornos da eliminação transepidérmica', 'L87 Transt da eliminacao transepidermica'),
  ('L870', 'Ceratose folicular e parafolicular penetrante na pele (Síndrome de Kyrle)', 'L87.0 Ceratose folicular parafolicular penetr pele'),
  ('L871', 'Colagenose perfurante reativa', 'L87.1 Colagenose perfurante reativa'),
  ('L872', 'Elastose perfurante serpiginosa', 'L87.2 Elastose perfurante serpiginosa'),
  ('L878', 'Outros transtornos da eliminação transepidérmica', 'L87.8 Outr transt da eliminacao transepidermica'),
  ('L879', 'Transtorno da eliminação transepidérmica, não especificado', 'L87.9 Transt da eliminacao transepidermica NE'),
  ('L88', 'Piodermite gangrenosa', 'L88 Piodermite gangrenosa'),
  ('L88', 'Piodermite gangrenosa', 'L88 Piodermite gangrenosa'),
  ('L89', 'Úlcera de decúbito', 'L89 Ulcera de decubito'),
  ('L89', 'Úlcera de decúbito', 'L89 Ulcera de decubito'),
  ('L90', 'Afecções atróficas da pele', 'L90 Afeccoes atroficas da pele'),
  ('L900', 'Líquen escleroso e atrófico', 'L90.0 Liquen escleroso e atrofico'),
  ('L901', 'Anetodermia de Schweninger-Buzzi', 'L90.1 Anetodermia de Schweninger-Buzzi'),
  ('L902', 'Anetodermia de Jadassohn-Pellizzari', 'L90.2 Anetodermia de Jadassohn-Pellizzari'),
  ('L903', 'Atrofodermia de Pasini e Pierini', 'L90.3 Atrofodermia de Pasini e Pierini'),
  ('L904', 'Acrodermatite crônica atrófica', 'L90.4 Acrodermatite cronica atrofica'),
  ('L905', 'Cicatrizes e fibrose cutânea', 'L90.5 Cicatrizes e fibrose cutanea'),
  ('L906', 'Estrias atróficas', 'L90.6 Estrias atroficas'),
  ('L908', 'Outras afecções atróficas da pele', 'L90.8 Outr afeccoes atroficas da pele'),
  ('L909', 'Afecções atróficas da pele, não especificadas', 'L90.9 Afeccoes atroficas da pele NE'),
  ('L91', 'Afecções hipertróficas da pele', 'L91 Afeccoes hipertroficas da pele'),
  ('L910', 'Cicatriz quelóide', 'L91.0 Cicatriz queloide'),
  ('L918', 'Outras afecções hipertróficas da pele', 'L91.8 Outr afeccoes hipertroficas da pele'),
  ('L919', 'Afecções hipertróficas da pele, não especificadas', 'L91.9 Afeccoes hipertroficas da pele NE'),
  ('L92', 'Afecções granulomatosas da pele e do tecido subcutâneo', 'L92 Afeccoes granulomatosas pele tec subcutaneo'),
  ('L920', 'Granuloma anular', 'L92.0 Granuloma anular'),
  ('L921', 'Necrobiose lipoídica não classificada em outra parte', 'L92.1 Necrobiose lipoidica NCOP'),
  ('L922', 'Granuloma facial (granuloma eosinófilo da pele)', 'L92.2 Granuloma facial'),
  ('L923', 'Granuloma de corpo estranho da pele e do tecido subcutâneo', 'L92.3 Granuloma corpo estranho pele tec subcutaneo'),
  ('L928', 'Outras afecções granulomatosas da pele e do tecido subcutâneo', 'L92.8 Outr afec granulomatosas pele tec subcutaneo'),
  ('L929', 'Afecções granulomatosas da pele e do tecido subcutâneo, não especificados', 'L92.9 Afecc granulomatosas pele tec subcutaneo NE'),
  ('L93', 'Lúpus eritematoso', 'L93 Lupus eritematoso'),
  ('L930', 'Lúpus eritematoso discóide', 'L93.0 Lupus eritematoso discoide'),
  ('L931', 'Lúpus eritematoso cutâneo subagudo', 'L93.1 Lupus eritematoso cutaneo subagudo'),
  ('L932', 'Outras formas de lúpus eritematoso localizado', 'L93.2 Outr form de lupus eritematoso localizado'),
  ('L94', 'Outras afecções localizadas do tecido conjuntivo', 'L94 Outr afeccoes localizadas do tec conjuntivo'),
  ('L940', 'Esclerodermia localizada (morféia)', 'L94.0 Esclerodermia localizada'),
  ('L941', 'Esclerodermia linear', 'L94.1 Esclerodermia linear'),
  ('L942', 'Calcinose cutânea', 'L94.2 Calcinose cutanea'),
  ('L943', 'Esclerodactilia', 'L94.3 Esclerodactilia'),
  ('L944', 'Pápulas de Gottron', 'L94.4 Papulas de Gottron'),
  ('L945', 'Poiquilodermia vascular atrófica', 'L94.5 Poiquilodermia vascular atrofica'),
  ('L946', 'Ainhum', 'L94.6 Ainhum'),
  ('L948', 'Outras afecções localizadas do tecido conjuntivo, especificadas', 'L94.8 Outr afeccoes localiz tec conjuntivo espec'),
  ('L949', 'Afecções localizadas do tecido conjuntivo, não especificadas', 'L94.9 Afeccoes localizadas do tec conjuntivo NE'),
  ('L95', 'Vasculite limitada a pele não classificadas em outra parte', 'L95 Vasculite limitada a pele NCOP'),
  ('L950', 'Vasculite livedóide', 'L95.0 Vasculite livedoide'),
  ('L951', 'Eritema elevado diutino (duradouro)', 'L95.1 Eritema elevado diutino'),
  ('L958', 'Outras vasculites limitadas a pele', 'L95.8 Outr vasculites limitadas a pele'),
  ('L959', 'Vasculites limitadas a pele, não especificadas', 'L95.9 Vasculites limitadas a pele NE'),
  ('L97', 'Úlcera dos membros inferiores não classificada em outra parte', 'L97 Ulcera dos membros infer NCOP'),
  ('L97', 'Úlcera dos membros inferiores não classificada em outra parte', 'L97 Ulcera dos membros infer NCOP'),
  ('L98', 'Outras afecções da pele e do tecido subcutâneo não classificadas em outra parte', 'L98 Outr afeccoes da pele e tec subcutaneo NCOP'),
  ('L980', 'Granuloma piogênico', 'L98.0 Granuloma piogenico'),
  ('L981', 'Dermatite factícia', 'L98.1 Dermatite facticia'),
  ('L982', 'Dermatose neutrofílica febril (Sweet)', 'L98.2 Dermatose neutrofilica febril'),
  ('L983', 'Celulite eosinofílica (Wells)', 'L98.3 Celulite eosinofilica'),
  ('L984', 'Úlcera crônica da pele, não classificada em outra parte', 'L98.4 Ulcera cronica da pele NCOP'),
  ('L985', 'Mucinose da pele', 'L98.5 Mucinose da pele'),
  ('L986', 'Outras afecções infiltrativas da pele e do tecido subcutâneo', 'L98.6 Outr afecc infiltrativas pele tec subcutaneo'),
  ('L988', 'Outras afecções especificadas da pele e do tecido subcutâneo', 'L98.8 Outr afeccoes espec pele e tec subcutaneo'),
  ('L989', 'Afecções da pele e do tecido subcutâneo, não especificados', 'L98.9 Afeccoes da pele e do tec subcutaneo NE'),
  ('L99', 'Outras afecções da pele e do tecido subcutâneo em doenças classificadas em outra parte', 'L99 Outr afeccoes pele tec subcutaneo doenc COP'),
  ('L990', 'Amiloidose cutânea', 'L99.0 Amiloidose cutanea'),
  ('L998', 'Outras afecções especificadas da pele e do tecido subcutâneo em doenças classificadas em outra parte', 'L99.8 Outr afecc espec pele tec subcut doenc COP');
