INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('Z00', 'Exame geral e investigação de pessoas sem queixas ou diagnóstico relatado', 'Z00 Exame geral invest pess s/queix diagn relat'),
  ('Z000', 'Exame médico geral', 'Z00.0 Exame medico geral'),
  ('Z001', 'Exame de rotina de saúde da criança', 'Z00.1 Exame de rotina de saude da crianca'),
  ('Z002', 'Exame no período de crescimento rápido na infância', 'Z00.2 Exame periodo crescimento rapido na infancia'),
  ('Z003', 'Exame do adolescente durante o crescimento na puberdade', 'Z00.3 Exame adolescente durante cresc puberdade'),
  ('Z004', 'Exame psiquiátrico geral não classificado em outra parte', 'Z00.4 Exame psiquiatrico geral NCOP'),
  ('Z005', 'Exame de doador potencial de órgão e tecido', 'Z00.5 Exame de doador potencial de orgao e tec'),
  ('Z006', 'Exame para comparação ou de controle de normalidade num programa de investigação clínica', 'Z00.6 Exame p/comp controle norm progr invest clin'),
  ('Z008', 'Outros exames gerais', 'Z00.8 Outr exames gerais'),
  ('Z01', 'Outros exames e investigações especiais de pessoas sem queixa ou diagnóstico relatado', 'Z01 Outr exam invest esp pess s/queix diag relat'),
  ('Z010', 'Exame dos olhos e da visão', 'Z01.0 Exame dos olhos e da visao'),
  ('Z011', 'Exame dos ouvidos e da audição', 'Z01.1 Exame dos ouvidos e da audicao'),
  ('Z012', 'Exame dentário', 'Z01.2 Exame dentario'),
  ('Z013', 'Exame da pressão arterial', 'Z01.3 Exame da pressao arterial'),
  ('Z014', 'Exame ginecológico (geral) (de rotina)', 'Z01.4 Exame ginecologico'),
  ('Z015', 'Testes cutâneos de diagnóstico e sensibilização', 'Z01.5 Testes cutaneos de diagn e sensibilizacao'),
  ('Z016', 'Exame radiológico não classificado em outra parte', 'Z01.6 Exame radiologico NCOP'),
  ('Z017', 'Exame de laboratório', 'Z01.7 Exame de laboratorio'),
  ('Z018', 'Outros exames especiais especificados', 'Z01.8 Outr exames especiais espec'),
  ('Z019', 'Exame especial não especificado', 'Z01.9 Exame especial NE'),
  ('Z02', 'Exame médico e consulta com finalidades administrativas', 'Z02 Exame med e consulta c/finalid admin'),
  ('Z020', 'Exame para admissão a instituição educacional', 'Z02.0 Exame p/admissao a instituicao educacional'),
  ('Z021', 'Exame pré-emprego (pré-admissional)', 'Z02.1 Exame pre-emprego'),
  ('Z022', 'Exame para admissão em instituição residencial', 'Z02.2 Exame p/admissao em instituicao residencial'),
  ('Z023', 'Exame para a incorporação nas forças armadas', 'Z02.3 Exame p/a incorporacao nas forcas armadas'),
  ('Z024', 'Exame para licença para a condução de veículos (carteira de motorista)', 'Z02.4 Exame p/licenca p/a conducao de veic'),
  ('Z025', 'Exame para participação em esporte', 'Z02.5 Exame p/participacao em esporte'),
  ('Z026', 'Exame para fins de seguro', 'Z02.6 Exame p/fins de seguro'),
  ('Z027', 'Obtenção de atestado médico', 'Z02.7 Obtencao de atestado medico'),
  ('Z028', 'Outros exames para propósitos administrativos', 'Z02.8 Outr exames p/propositos administrativos'),
  ('Z029', 'Exame não especificado com finalidades administrativas', 'Z02.9 Exame NE c/finalidades administrativas'),
  ('Z03', 'Observação e avaliação médica por doenças e afecções suspeitas', 'Z03 Observ avaliacao med doenc afecc suspeitas'),
  ('Z030', 'Observação por suspeita de tuberculose', 'Z03.0 Observacao p/suspeita de tuberc'),
  ('Z031', 'Observação por suspeita de neoplasia maligna', 'Z03.1 Observacao p/suspeita de neopl malig'),
  ('Z032', 'Observação por suspeita de transtornos mentais e do comportamento', 'Z03.2 Observacao p/susp transt mentais e comport'),
  ('Z033', 'Observação por suspeita de transtorno do sistema nervoso', 'Z03.3 Observacao p/suspeita de transt sist nervoso'),
  ('Z034', 'Observação por suspeita de infarto do miocárdio', 'Z03.4 Observacao p/suspeita de infarto miocardio'),
  ('Z035', 'Observação por suspeita de outras doenças cardiovasculares', 'Z03.5 Observacao p/suspeita outr doenc cardiovasc'),
  ('Z036', 'Observação por suspeita de efeito tóxico de substância ingerida', 'Z03.6 Observ p/susp efeito toxico subst ingerida'),
  ('Z038', 'Observação por suspeita de outras doenças e afecções', 'Z03.8 Observacao p/suspeita de outr doenc afeccoes'),
  ('Z039', 'Observação por suspeita de doença ou afecção não especificada', 'Z03.9 Observacao p/suspeita de doenc ou afeccao NE'),
  ('Z04', 'Exame e observação por outras razões', 'Z04 Exame e observacao p/outr razoes'),
  ('Z040', 'Teste para álcool e para drogas no sangue', 'Z04.0 Teste p/alcool e p/drogas no sangue'),
  ('Z041', 'Exame e observação após acidente de transporte', 'Z04.1 Exame e observacao apos acid transp'),
  ('Z042', 'Exame e observação após acidente de trabalho', 'Z04.2 Exame e observacao apos acid de trabalho'),
  ('Z043', 'Exame e observação após outro acidente', 'Z04.3 Exame e observacao apos outr acid'),
  ('Z044', 'Exame e observação após alegação de estupro e sedução', 'Z04.4 Exame e observ apos alegacao estupro seducao'),
  ('Z045', 'Exame e observação após outros ferimentos infligidos', 'Z04.5 Exame e observ apos outr ferim infligidos'),
  ('Z046', 'Exame psiquiátrico geral, requerido por autoridade', 'Z04.6 Exame psiquiatr geral requerido p/autoridade'),
  ('Z048', 'Exame e observação por outras razões especificadas', 'Z04.8 Exame e observacao p/outr razoes espec'),
  ('Z049', 'Exame e observação por razão não especificada', 'Z04.9 Exame e observacao p/razao NE'),
  ('Z08', 'Exame de seguimento após tratamento por neoplasia maligna', 'Z08 Exame seguim apos tratamento p/neopl malig'),
  ('Z080', 'Exame de seguimento após tratamento cirúrgico de neoplasia maligna', 'Z08.0 Exame seguim apos trat cirurg neopl malig'),
  ('Z081', 'Exame de seguimento após radioterapia por neoplasia maligna', 'Z08.1 Exame seguim apos radioterapia p/neopl malig'),
  ('Z082', 'Exame de seguimento após quimioterapia por neoplasia maligna', 'Z08.2 Exame seguim apos quimioterap p/neopl malig'),
  ('Z087', 'Exame de seguimento após tratamento misto por neoplasia maligna', 'Z08.7 Exame seguim apos trat misto p/neopl malig'),
  ('Z088', 'Exame de seguimento após outro tratamento por neoplasia maligna', 'Z08.8 Exame seguim apos outr trat p/neopl malig'),
  ('Z089', 'Exame de seguimento após tratamento não especificado por neoplasia maligna', 'Z08.9 Exame seguim apos trat NE p/neopl malig'),
  ('Z09', 'Exame de seguimento após tratamento de outras afecções que não neoplasias malignas', 'Z09 Exame seguim apos trat out afec n neop malig'),
  ('Z090', 'Exame de seguimento após cirurgia por outras afecções', 'Z09.0 Exame seguim apos cirurgia p/outr afeccoes'),
  ('Z091', 'Exame de seguimento após radioterapia por outras afecções', 'Z09.1 Exame seguim apos radioterapia p/outr afecc'),
  ('Z092', 'Exame de seguimento após quimioterapia por outras afecções', 'Z09.2 Exame seguim apos quimioterap p/outr afecc'),
  ('Z093', 'Exame de seguimento após psicoterapia', 'Z09.3 Exame seguim apos psicoterapia'),
  ('Z094', 'Exame de seguimento após tratamento de fratura', 'Z09.4 Exame seguim apos tratamento de frat'),
  ('Z097', 'Exame de seguimento após tratamento combinado por outras afecções', 'Z09.7 Exame seguim apos trat combinado outr afecc'),
  ('Z098', 'Exame de seguimento após outro tratamento por outras afecções', 'Z09.8 Exame seguim apos outr trat p/outr afeccoes'),
  ('Z099', 'Exame de seguimento após tratamento não especificado por outras afecções', 'Z09.9 Exame seguim apos trat NE p/outr afeccoes'),
  ('Z10', 'Exame geral de rotina (check up) de uma subpopulação definida', 'Z10 Exame geral de rotina subpopulacao definida'),
  ('Z100', 'Exame de saúde ocupacional', 'Z10.0 Exame de saude ocupacional'),
  ('Z101', 'Exame geral de rotina de residentes de instituições', 'Z10.1 Exame geral de rotina resid de instituicoes'),
  ('Z102', 'Exame geral de rotina de pessoas das forças armadas', 'Z10.2 Exame geral de rotina pessoas forcas armadas'),
  ('Z103', 'Exame geral de rotina de equipe esportiva', 'Z10.3 Exame geral de rotina de equipe esportiva'),
  ('Z108', 'Exame geral de rotina de outra subpopulação definida', 'Z10.8 Exame geral de rotina outr subpop definida'),
  ('Z11', 'Exame especial de rastreamento (screening) de doenças infecciosas e parasitárias', 'Z11 Exame esp rastr doenc infecc parasit'),
  ('Z110', 'Exame especial de rastreamento de doenças infecciosas intestinais', 'Z11.0 Exame especial rastr doenc infecc intest'),
  ('Z111', 'Exame especial de rastreamento de tuberculose pulmonar', 'Z11.1 Exame especial rastr tuberc pulmonar'),
  ('Z112', 'Exame especial de rastreamento de outras doenças bacterianas', 'Z11.2 Exame especial rastr outr doenc bacter'),
  ('Z113', 'Exame especial de rastreamento de infecções de transmissão predominantemente sexual', 'Z11.3 Exame esp rastr infecc transm predom sexual'),
  ('Z114', 'Exame especial de rastreamento de vírus da imunodeficiência humana (HIV)', 'Z11.4 Exame especial rastr de HIV'),
  ('Z115', 'Exame especial de rastreamento de outras doenças virais', 'Z11.5 Exame especial rastr outr doenc virais'),
  ('Z116', 'Exame especial de rastreamento de outras doenças por protozoários e por helmintos', 'Z11.6 Exame esp rastr outr doenc protoz helmintos'),
  ('Z118', 'Exame especial de rastreamento de outras doenças infecciosas e parasitárias', 'Z11.8 Exame esp rastr outr doenc infecc e parasit'),
  ('Z119', 'Exame especial de rastreamento para doença infecciosa e parasitária não especificada', 'Z11.9 Exame esp rastr doenc infecc e parasit NE'),
  ('Z12', 'Exame especial de rastreamento (screening) de neoplasias', 'Z12 Exame especial rastr de neoplasias'),
  ('Z120', 'Exame especial de rastreamento de neoplasia do estômago', 'Z12.0 Exame especial rastr neoplasia do estomago'),
  ('Z121', 'Exame especial de rastreamento de neoplasia do trato intestinal', 'Z12.1 Exame especial rastr neoplasia trato intest'),
  ('Z122', 'Exame especial de rastreamento de neoplasia de órgãos respiratórios', 'Z12.2 Exame especial rastr neoplasia org respirat'),
  ('Z123', 'Exame especial de rastreamento de neoplasia de mama', 'Z12.3 Exame especial rastr de neoplasia de mama'),
  ('Z124', 'Exame especial de rastreamento de neoplasia do colo do útero', 'Z12.4 Exame especial rastr de neoplasia colo utero'),
  ('Z125', 'Exame especial de rastreamento de neoplasia da próstata', 'Z12.5 Exame especial rastr de neoplasia prostata'),
  ('Z126', 'Exame especial de rastreamento de neoplasia da bexiga', 'Z12.6 Exame especial rastr de neoplasia da bexiga'),
  ('Z128', 'Exame especial de rastreamento de neoplasias de outras localizações', 'Z12.8 Exame especial rastr neoplasias outr localiz'),
  ('Z129', 'Exame especial de rastreamento de neoplasia não especificada', 'Z12.9 Exame especial rastr de neoplasia NE'),
  ('Z13', 'Exame especial de rastreamento (screening) de outros transtornos e doenças', 'Z13 Exame especial rastr de outr transt e doenc'),
  ('Z130', 'Exame especial de rastreamento de doenças do sangue e dos órgãos hematopoéticos de alguns transtornos imunitários', 'Z13.0 Exame esp rastr doenc sang org hem tran imun'),
  ('Z131', 'Exame especial de rastreamento de diabetes mellitus', 'Z13.1 Exame especial rastr de diabetes mellitus'),
  ('Z132', 'Exame especial de rastreamento de transtornos nutricionais', 'Z13.2 Exame especial rastr de transt nutricionais'),
  ('Z133', 'Exame especial de rastreamento de transtornos mentais e do comportamento', 'Z13.3 Exame especial rastr transt mentais comport'),
  ('Z134', 'Exame especial de rastreamento de alguns transtornos do desenvolvimento na infância', 'Z13.4 Exame esp rastr alguns transt desenv infanc'),
  ('Z135', 'Exame especial de rastreamento de doenças dos ouvidos e dos olhos', 'Z13.5 Exame especial rastr doenc ouvidos olhos'),
  ('Z136', 'Exame especial de rastreamento de doenças cardiovasculares', 'Z13.6 Exame especial rastr doenc cardiovasculares'),
  ('Z137', 'Exame especial de rastreamento de malformações congênitas, deformidades e anomalias cromossômicas', 'Z13.7 Exame esp rastr malform cong def anom cromos'),
  ('Z138', 'Exame especial de rastreamento de outras doenças e transtornos especificados', 'Z13.8 Exame especial rastr outr doenc transt espec'),
  ('Z139', 'Exame especial de rastreamento não especificado', 'Z13.9 Exame especial rastr NE'),
  ('Z20', 'Contato com e exposição a doenças transmissíveis', 'Z20 Contato exposicao a doenc transmissiveis'),
  ('Z200', 'Contato com e exposição a doenças infecciosas intestinais', 'Z20.0 Contato exposicao a doenc infecc intest'),
  ('Z201', 'Contato com e exposição à tuberculose', 'Z20.1 Contato exposicao a tuberc'),
  ('Z202', 'Contato com e exposição a infecções de transmissão predominantemente sexual', 'Z20.2 Contato exposicao infecc transm pred sexual'),
  ('Z203', 'Contato com e exposição à raiva', 'Z20.3 Contato exposicao a raiva'),
  ('Z204', 'Contato com e exposição à rubéola', 'Z20.4 Contato exposicao a rubeola'),
  ('Z205', 'Contato com e exposição à hepatite viral', 'Z20.5 Contato exposicao a hepatite viral'),
  ('Z206', 'Contato com e exposição ao vírus da imunodeficiência humana (HIV)', 'Z20.6 Contato exposicao ao HIV'),
  ('Z207', 'Contato com e exposição à pediculose, acaríase e outras infestações', 'Z20.7 Contato expos pediculose acariase out infest'),
  ('Z208', 'Contato com e exposição a outras doenças transmissíveis', 'Z20.8 Contato exposicao outr doenc transmissiveis'),
  ('Z209', 'Contato com e exposição a doença transmissível não especificada', 'Z20.9 Contato exposicao a doenc transmissivel NE'),
  ('Z21', 'Estado de infecção assintomática pelo vírus da imunodeficiência humana (HIV)', 'Z21 Estado de infecc assintomatica p/HIV'),
  ('Z21', 'Estado de infecção assintomática pelo vírus da imunodeficiência humana (HIV)', 'Z21 Estado de infecc assintomatica p/HIV'),
  ('Z22', 'Portador de doença infecciosa', 'Z22 Portador de doenc infecc'),
  ('Z220', 'Portador de febre tifóide', 'Z22.0 Portador de febre tifoide'),
  ('Z221', 'Portador de outras doenças infecciosas intestinais', 'Z22.1 Portador de outr doenc infecc intestinais'),
  ('Z222', 'Portador de difteria', 'Z22.2 Portador de difteria'),
  ('Z223', 'Portador de outras doenças bacterianas especificadas', 'Z22.3 Portador de outr doenc bacter espec'),
  ('Z224', 'Portador de infecções com modo de transmissão predominantemente sexual', 'Z22.4 Portador de infecc modo transm predom sexual'),
  ('Z225', 'Portador de hepatite viral', 'Z22.5 Portador de hepatite viral'),
  ('Z226', 'Portador de infecção pelo vírus T-linfotrópico tipo 1 (HTLV-1)', 'Z22.6 Portador infecc virus T-linfotropico tipo 1'),
  ('Z228', 'Portador de outras doenças infecciosas', 'Z22.8 Portador de outr doenc infecc'),
  ('Z229', 'Portador de doença infecciosa não especificada', 'Z22.9 Portador de doenc infecc NE'),
  ('Z23', 'Necessidade de imunização contra uma única doença bacteriana', 'Z23 Necess imuniz contra unica doenc bacter'),
  ('Z230', 'Necessidade de imunização somente contra cólera', 'Z23.0 Necess imunizacao somente colera'),
  ('Z231', 'Necessidade de imunização somente contra febre tifóide e paratifóide (TAB)', 'Z23.1 Necess imuniz somente febre tif paratifoide'),
  ('Z232', 'Necessidade de imunização contra tuberculose (BCG)', 'Z23.2 Necess imunizacao contra tuberc'),
  ('Z233', 'Necessidade de imunização contra a peste', 'Z23.3 Necess imunizacao contra a peste'),
  ('Z234', 'Necessidade de imunização contra a tularemia', 'Z23.4 Necess imunizacao contra a tularemia'),
  ('Z235', 'Necessidade de imunização somente contra o tétano', 'Z23.5 Necess imunizacao somente contra o tetano'),
  ('Z236', 'Necessidade de imunização somente contra a difteria', 'Z23.6 Necess imunizacao somente contra a difteria'),
  ('Z237', 'Necessidade de imunização somente contra a coqueluche', 'Z23.7 Necess imunizacao somente contra coqueluche'),
  ('Z238', 'Vacinação contra outras doenças bacterianas únicas', 'Z23.8 Vacinacao contra outr doenc bacter unicas'),
  ('Z24', 'Necessidade de imunização contra algumas doenças virais únicas', 'Z24 Necess imuniz contra alg doenc virais unicas'),
  ('Z240', 'Necessidade de imunização contra a poliomielite', 'Z24.0 Necess imuniz contra a poliomielite'),
  ('Z241', 'Necessidade de imunização contra a encefalite viral transmitida por artrópodes', 'Z24.1 Necess imuniz contra encef viral trans artr'),
  ('Z242', 'Necessidade de imunização contra a raiva', 'Z24.2 Necess imuniz contra a raiva'),
  ('Z243', 'Necessidade de imunização contra a febre amarela', 'Z24.3 Necess imuniz contra a febre amarela'),
  ('Z244', 'Necessidade de imunização somente contra o sarampo', 'Z24.4 Necess imuniz somente contra o sarampo'),
  ('Z245', 'Necessidade de imunização somente contra a rubéola', 'Z24.5 Necess imuniz somente contra a rubeola'),
  ('Z246', 'Necessidade de imunização somente contra a hepatite viral', 'Z24.6 Necess imuniz somente contra hepatite viral'),
  ('Z25', 'Necessidade de imunização contra outras doenças virais únicas', 'Z25 Necess imuniz contra outr doenc virais unic'),
  ('Z250', 'Necessidade de imunização somente contra a caxumba (parotidite epidêmica)', 'Z25.0 Necess imuniz somente contra a caxumba'),
  ('Z251', 'Necessidade de imunização somente contra a influenza (gripe)', 'Z25.1 Necess imuniz somente contra a influenza'),
  ('Z258', 'Necessidade de imunização contra outras doenças virais únicas especificadas', 'Z25.8 Necess imuniz outr doenc virais unicas espec'),
  ('Z26', 'Necessidade de imunização contra outras doenças infecciosas únicas', 'Z26 Necess imuniz outr doenc infecc unicas'),
  ('Z260', 'Necessidade de imunização contra a leishmaniose', 'Z26.0 Necess imuniz contra a leishmaniose'),
  ('Z268', 'Necessidade de imunização contra outras doenças infecciosas especificadas únicas', 'Z26.8 Necess imuniz outr doenc infecc espec unicas'),
  ('Z269', 'Necessidade de imunização contra doença infecciosa não especificada', 'Z26.9 Necess imuniz contra doenc infecc NE'),
  ('Z27', 'Necessidade de imunização associada contra combinações de doenças infecciosas', 'Z27 Necess imuniz assoc contra comb doenc infecc'),
  ('Z270', 'Necessidade de imunização contra a cólera e as febres tifóide e paratifóides (Cólera + TAB)', 'Z27.0 Necess imuniz contra colera febr tif paratif'),
  ('Z271', 'Necessidade de imunização associada contra a difteria-pertussis-tétano, combinada (DPT)', 'Z27.1 Necess imuniz difteria-pertussis-tetano comb'),
  ('Z272', 'Necessidade de imunização contra a difteria-pertussis-tétano com febres tifóide e paratifóides (DPT + TAB)', 'Z27.2 Necess imuniz dift-pert-tet febr tif paratif'),
  ('Z273', 'Necessidade de imunização contra a difteria-pertussis-tétano com poliomielite (DPT + pólio)', 'Z27.3 Necess imuniz difter-pertussis-tetano polio'),
  ('Z274', 'Necessidade de imunização contra o sarampo-caxumba-rubéola', 'Z27.4 Necess imuniz sarampo-caxumba-rubeola'),
  ('Z278', 'Necessidade de imunização contra outras combinações de doenças infecciosas', 'Z27.8 Necess imuniz combinacoes de doenc infecc'),
  ('Z279', 'Necessidade de imunização contra combinações não especificadas de doenças infecciosas', 'Z27.9 Necess imuniz combinacoes NE de doenc infecc'),
  ('Z28', 'Imunização não realizada', 'Z28 Imuniz nao realizada'),
  ('Z280', 'Imunização não realizada por contra-indicação', 'Z28.0 Imuniz nao realizada p/contra-indicacao'),
  ('Z281', 'Imunização não realizada por decisão do paciente devida à crença ou a grupo de pressão', 'Z28.1 Imuniz nao real decis pac crenc grup pressao'),
  ('Z282', 'Imunização não realizada por decisão do paciente devida a razões outras e às não especificadas', 'Z28.2 Imuniz nao real decis pac razoes outr e NE'),
  ('Z288', 'Imunização não realizada por outras razões', 'Z28.8 Imuniz nao realizada p/outr razoes'),
  ('Z289', 'Imunização não realizada por razões não especificadas', 'Z28.9 Imuniz nao realizada p/razoes NE'),
  ('Z29', 'Necessidade de outras medidas profiláticas', 'Z29 Necessidade de outr medidas profilaticas'),
  ('Z290', 'Isolamento', 'Z29.0 Isolamento'),
  ('Z291', 'Imunoterapia profilática', 'Z29.1 Imunoterapia profilatica'),
  ('Z292', 'Outras quimioterapias profiláticas', 'Z29.2 Outr quimioterapias profilaticas'),
  ('Z298', 'Outras medidas profiláticas especificadas', 'Z29.8 Outr medidas profilaticas espec'),
  ('Z299', 'Medida profilática não especificada', 'Z29.9 Medida profilatica NE'),
  ('Z30', 'Anticoncepção', 'Z30 Anticoncepcao'),
  ('Z300', 'Aconselhamento geral sobre contracepção', 'Z30.0 Aconselhamento geral sobre contracepcao'),
  ('Z301', 'Inserção de dispositivo anticoncepcional (intra-uterino)', 'Z30.1 Insercao de disp anticoncepcional'),
  ('Z302', 'Esterilização', 'Z30.2 Esterilizacao'),
  ('Z303', 'Extração menstrual', 'Z30.3 Extracao menstrual'),
  ('Z304', 'Supervisão do uso de medicamentos anticoncepcionais', 'Z30.4 Supervisao uso medic anticoncepcionais'),
  ('Z305', 'Supervisão de dispositivo anticoncepcional (intra-uterino)', 'Z30.5 Supervisao de disp anticoncepcional'),
  ('Z308', 'Outro procedimento anticoncepcional', 'Z30.8 Outr proced anticoncepcional'),
  ('Z309', 'Procedimento anticoncepcional não especificado', 'Z30.9 Proced anticoncepcional NE'),
  ('Z31', 'Medidas de procriação', 'Z31 Medidas de procriacao'),
  ('Z310', 'Tuboplastia ou vasoplastia após esterilização prévia', 'Z31.0 Tuboplast vasoplast apos esteriliz previa'),
  ('Z311', 'Inseminação artificial', 'Z31.1 Inseminacao artificial'),
  ('Z312', 'Fecundação in vitro', 'Z31.2 Fecundacao in vitro'),
  ('Z313', 'Outros métodos assistidos de fertilização', 'Z31.3 Outr metodos assistidos de fertilizacao'),
  ('Z314', 'Investigação e testes com relação à procriação', 'Z31.4 Invest e testes c/relacao a procriacao'),
  ('Z315', 'Aconselhamento genético', 'Z31.5 Aconselhamento genetico'),
  ('Z316', 'Aconselhamento geral sobre a procriação', 'Z31.6 Aconselhamento geral sobre a procriacao'),
  ('Z318', 'Outra medida especificada de procriação', 'Z31.8 Outr medida espec de procriacao'),
  ('Z319', 'Medida procriativa não especificada', 'Z31.9 Medida procriativa NE'),
  ('Z32', 'Exame ou teste de gravidez', 'Z32 Exame ou teste de gravidez'),
  ('Z320', 'Gravidez (ainda) não confirmada', 'Z32.0 Gravidez nao confirmada'),
  ('Z321', 'Gravidez confirmada', 'Z32.1 Gravidez confirmada'),
  ('Z33', 'Gravidez como achado casual', 'Z33 Gravidez como achado casual'),
  ('Z33', 'Gravidez como achado casual', 'Z33 Gravidez como achado casual'),
  ('Z34', 'Supervisão de gravidez normal', 'Z34 Supervisao de gravidez normal'),
  ('Z340', 'Supervisão de primeira gravidez normal', 'Z34.0 Supervisao de primeira gravidez normal'),
  ('Z348', 'Supervisão de outra gravidez normal', 'Z34.8 Supervisao de outr gravidez normal'),
  ('Z349', 'Supervisão de gravidez normal, não especificada', 'Z34.9 Supervisao de gravidez normal NE'),
  ('Z35', 'Supervisão de gravidez de alto risco', 'Z35 Supervisao de gravidez de alto risco'),
  ('Z350', 'Supervisão de gravidez com história de esterilidade', 'Z35.0 Supervisao gravidez c/historia esterilidade'),
  ('Z351', 'Supervisão de gravidez com história de aborto', 'Z35.1 Supervisao de gravidez c/historia de aborto'),
  ('Z352', 'Supervisão de gravidez com outros antecedentes de procriação problemática', 'Z35.2 Superv grav outr antec procriacao problem'),
  ('Z353', 'Supervisão de gravidez com história de assistência pré-natal insuficiente', 'Z35.3 Superv grav historia assist pre-natal insuf'),
  ('Z354', 'Supervisão de gravidez com grande multiparidade', 'Z35.4 Supervisao gravidez c/grande multiparidade'),
  ('Z355', 'Supervisão de primigesta idosa', 'Z35.5 Supervisao de primigesta idosa'),
  ('Z356', 'Supervisão de primigesta muito jovem', 'Z35.6 Supervisao de primigesta muito jovem'),
  ('Z357', 'Supervisão de gravidez de alto risco devido a problemas sociais', 'Z35.7 Supervisao gravidez alto risco dev probl soc'),
  ('Z358', 'Supervisão de outras gravidezes de alto risco', 'Z35.8 Supervisao de outr gravidezes de alto risco'),
  ('Z359', 'Supervisão não especificada de gravidez de alto risco', 'Z35.9 Supervisao NE de gravidez de alto risco'),
  ('Z36', 'Rastreamento (screening) pré-natal', 'Z36 Rastr pre-natal'),
  ('Z360', 'Rastreamento de anomalias cromossômicas', 'Z36.0 Rastr de anomalias cromossomicas'),
  ('Z361', 'Rastreamento pré-natal de taxa elevada de alfa-fetoproteínas', 'Z36.1 Rastr pre-natal taxa elev alfa-fetoproteinas'),
  ('Z362', 'Outros rastreamentos pré-natais por amniocentese', 'Z36.2 Outr rastr pre-natais p/amniocentese'),
  ('Z363', 'Rastreamento pré-natal de malformações por ultrassom e outros meios físicos', 'Z36.3 Rastr pre-nat malform ultrass outr meios fis'),
  ('Z364', 'Rastreamento pré-natal do retardo de crescimento do feto por ultrassom e outros métodos físicos', 'Z36.4 Rastr pre-nat ret cresc fet ultr out met fis'),
  ('Z365', 'Rastreamento pré-natal de isoimunização', 'Z36.5 Rastr pre-natal de isoimunizacao'),
  ('Z368', 'Outros rastreamentos pré-natais', 'Z36.8 Outr rastr pre-natais'),
  ('Z369', 'Rastreamento pré-natal não especificado', 'Z36.9 Rastr pre-natal NE'),
  ('Z37', 'Resultado do parto', 'Z37 Resultado do parto'),
  ('Z370', 'Nascimento único, nativivo (nado-vivo)', 'Z37.0 Nascimento unico nativivo'),
  ('Z371', 'Nascimento único, natimorto (feto-morto)', 'Z37.1 Nascimento unico natimorto'),
  ('Z372', 'Nascimento gemelar, gêmeos (ambos) nativivos (nado-vivos)', 'Z37.2 Nascimento gemelar gemeos nativivos'),
  ('Z373', 'Nascimento gemelar, um dos gêmeos, nativivo (nado-vivo), o outro, natimorto (feto-morto)', 'Z37.3 Nasc gemelar um nativivo o outr natimorto'),
  ('Z374', 'Nascimento gemelar, gêmeos natimortos (feto-mortos)', 'Z37.4 Nascimento gemelar gemeos natimortos'),
  ('Z375', 'Outros nascimentos múltiplos, todos nativivos (nado-vivos)', 'Z37.5 Outr nascimentos mult todos nativivos'),
  ('Z376', 'Outros nascimentos múltiplos, alguns nativivos (nado-vivos)', 'Z37.6 Outr nascimentos mult alguns nativivos'),
  ('Z377', 'Outros nascimentos múltiplos, todos natimortos (feto-mortos)', 'Z37.7 Outr nascimentos mult todos natimortos'),
  ('Z379', 'Nascimento não especificado', 'Z37.9 Nascimento NE'),
  ('Z38', 'Nascidos vivos (nado-vivos) segundo o local de nascimento', 'Z38 Nascidos vivos segundo o local de nascimento'),
  ('Z380', 'Criança única, nascida em hospital', 'Z38.0 Crianca unica nascida em hospital'),
  ('Z381', 'Criança única, nascida fora do hospital', 'Z38.1 Crianca unica nascida fora do hospital'),
  ('Z382', 'Criança única, não especificado quanto ao local de nascimento', 'Z38.2 Crianca unica NE quanto ao local nascimento'),
  ('Z383', 'Gêmeos (duplos), nascidos em hospital', 'Z38.3 Gemeos nascidos em hospital'),
  ('Z384', 'Gêmeos (duplos), nascidos fora de hospital', 'Z38.4 Gemeos nascidos fora de hospital'),
  ('Z385', 'Gêmeos, não especificados quanto ao local de nascimento', 'Z38.5 Gemeos NE quanto ao local de nascimento'),
  ('Z386', 'Outros nascimentos múltiplos, em hospital', 'Z38.6 Outr nascimentos mult em hospital'),
  ('Z387', 'Outros nascimentos múltiplos, fora de hospital', 'Z38.7 Outr nascimentos mult fora de hospital'),
  ('Z388', 'Outros nascimentos múltiplos, não especificados quanto ao local de nascimento', 'Z38.8 Outr nascimentos mult NE quanto local nasc'),
  ('Z39', 'Assistência e exame pós-natal', 'Z39 Assist e exame pos-natal'),
  ('Z390', 'Assistência e exame imediatamente após o parto', 'Z39.0 Assist e exame imediatamente apos o parto'),
  ('Z391', 'Assistência e exame da mãe nutriz', 'Z39.1 Assist e exame da mae nutriz'),
  ('Z392', 'Seguimento pós-parto de rotina', 'Z39.2 Seguimento pos-parto de rotina'),
  ('Z40', 'Cirurgia profilática', 'Z40 Cirurgia profilatica'),
  ('Z400', 'Cirurgia profilática para fatores de risco relacionados com neoplasias malignas', 'Z40.0 Cirurg profilat fat risco rel neopl malig'),
  ('Z408', 'Outra cirurgia profilática', 'Z40.8 Outr cirurgia profilatica'),
  ('Z409', 'Cirurgia profilática não especificada', 'Z40.9 Cirurgia profilatica NE'),
  ('Z41', 'Procedimentos para outros propósitos exceto cuidados de saúde', 'Z41 Proced p/outr propositos exc cuidados saude'),
  ('Z410', 'Transplante de cabelo', 'Z41.0 Transplante de cabelo'),
  ('Z411', 'Outras intervenções de cirurgia plástica por razões estéticas', 'Z41.1 Outr interv cirurg plast p/razoes esteticas'),
  ('Z412', 'Circuncisão ritual e de rotina', 'Z41.2 Circuncisao ritual e de rotina'),
  ('Z413', 'Perfuração do lobo da orelha', 'Z41.3 Perfuracao do lobo da orelha'),
  ('Z418', 'Outros procedimentos para outros propósitos exceto cuidados de saúde', 'Z41.8 Outr proced outr prop exc cuidados de saude'),
  ('Z419', 'Procedimentos não especificado para outros propósitos exceto cuidados de saúde', 'Z41.9 Proced NE p/outr prop exc cuidados de saude'),
  ('Z42', 'Seguimento envolvendo cirurgia plástica', 'Z42 Seguimento envolv cirurgia plastica'),
  ('Z420', 'Seguimento envolvendo cirurgia plástica da cabeça e do pescoço', 'Z42.0 Seguim envolv cirurg plast cabeca pescoco'),
  ('Z421', 'Seguimento envolvendo cirurgia plástica de mama', 'Z42.1 Seguimento envolv cirurgia plastica de mama'),
  ('Z422', 'Seguimento envolvendo cirurgia plástica de outras partes do tronco', 'Z42.2 Seguim envolv cirurg plast outr part tronco'),
  ('Z423', 'Seguimento envolvendo cirurgia plástica das extremidades superiores', 'Z42.3 Seguim envolv cirurg plast extrem super'),
  ('Z424', 'Seguimento envolvendo cirurgia plástica das extremidades inferiores', 'Z42.4 Seguim envolv cirurg plast extrem infer'),
  ('Z428', 'Seguimento envolvendo cirurgia plástica de outras partes do corpo', 'Z42.8 Seguim envolv cirurg plast outr partes corpo'),
  ('Z429', 'Seguimento envolvendo cirurgia plástica não especificada', 'Z42.9 Seguimento envolv cirurgia plastica NE'),
  ('Z43', 'Atenção a orifícios artificiais', 'Z43 Atencao a orificios artificiais'),
  ('Z430', 'Cuidados à traqueostomia', 'Z43.0 Cuidados a traqueostomia'),
  ('Z431', 'Cuidados à gastrostomia', 'Z43.1 Cuidados a gastrostomia'),
  ('Z432', 'Cuidados à ileostomia', 'Z43.2 Cuidados a ileostomia'),
  ('Z433', 'Cuidados à colostomia', 'Z43.3 Cuidados a colostomia'),
  ('Z434', 'Cuidados a outros orifícios artificiais do tubo digestivo', 'Z43.4 Cuidados outr orif artificiais tubo digest'),
  ('Z435', 'Cuidados à cistostomia', 'Z43.5 Cuidados a cistostomia'),
  ('Z436', 'Cuidados a outros orifícios artificiais das vias urinárias', 'Z43.6 Cuidados outr orif artificais vias urinarias'),
  ('Z437', 'Cuidados à vagina artificial', 'Z43.7 Cuidados a vagina artificial'),
  ('Z438', 'Cuidados a outros orifícios artificiais', 'Z43.8 Cuidados a outr orificios artificiais'),
  ('Z439', 'Cuidados a orifício artificial não especificado', 'Z43.9 Cuidados a orificio artificial NE'),
  ('Z44', 'Colocação e ajustamento de aparelhos de prótese externa', 'Z44 Coloc ajust aparelhos de protese externa'),
  ('Z440', 'Colocação e ajustamento de braço artificial (parcial) (total)', 'Z44.0 Colocacao e ajustamento de braco artificial'),
  ('Z441', 'Colocação e ajustamento de perna artificial (parcial) (total)', 'Z44.1 Colocacao e ajustamento de perna artificial'),
  ('Z442', 'Colocação e ajustamento de olho artificial', 'Z44.2 Colocacao e ajustamento de olho artificial'),
  ('Z443', 'Colocação e ajustamento de prótese externa de mama', 'Z44.3 Colocacao e ajustamento protese externa mama'),
  ('Z448', 'Colocação e ajustamento de outros aparelhos de prótese externa', 'Z44.8 Colocacao e ajustamento outr ap protese ext'),
  ('Z449', 'Colocação e ajustamento de aparelho de prótese externa não especificado', 'Z44.9 Colocacao e ajustamento ap protese ext NE'),
  ('Z45', 'Ajustamento e manuseio de dispositivo implantado', 'Z45 Ajustamento e manuseio de disp implantado'),
  ('Z450', 'Ajustamento e manuseio de marca-passo cardíaco', 'Z45.0 Ajustamento e manuseio marca-passo cardiaco'),
  ('Z451', 'Ajustamento e manuseio de bomba de infusão', 'Z45.1 Ajustamento e manuseio de bomba de infusao'),
  ('Z452', 'Ajustamento e manuseio de dispositivo de acesso vascular', 'Z45.2 Ajustamento e manuseio disp acesso vascular'),
  ('Z453', 'Ajustamento e manuseio de dispositivo implantado de audição', 'Z45.3 Ajustamento e manuseio disp implant audicao'),
  ('Z458', 'Ajustamento e manuseio de outros dispositivos implantados', 'Z45.8 Ajustamento e manuseio outr disp implantados'),
  ('Z459', 'Ajustamento e manuseio de dispositivo implantado não especificado', 'Z45.9 Ajustamento e manuseio de disp implantado NE'),
  ('Z46', 'Colocação e ajustamento de outros aparelhos', 'Z46 Colocacao e ajustamento de outr aparelhos'),
  ('Z460', 'Colocação e ajustamento de óculos e lentes de contato', 'Z46.0 Colocacao ajustamento oculos lentes contato'),
  ('Z461', 'Colocação e ajustamento de aparelho auditivo', 'Z46.1 Colocacao e ajustamento de aparelho auditivo'),
  ('Z462', 'Colocação e ajustamento de outros aparelhos relacionados com o sistema nervoso e órgãos dos sentidos', 'Z46.2 Coloc ajust outr ap rel sist nerv org sentid'),
  ('Z463', 'Colocação e ajustamento de dispositivo de prótese dentária', 'Z46.3 Colocacao ajustamento disp protese dentaria'),
  ('Z464', 'Colocação e ajustamento de aparelho ortodôntico', 'Z46.4 Colocacao e ajustamento aparelho ortodontico'),
  ('Z465', 'Colocação e ajustamento de ileostomia e de outros dispositivos intestinais', 'Z46.5 Coloc ajust ileostomia e outr disp intest'),
  ('Z466', 'Colocação e ajustamento de prótese urinária', 'Z46.6 Colocacao e ajustamento de protese urinaria'),
  ('Z467', 'Colocação e ajustamento de aparelho ortopédico', 'Z46.7 Colocacao e ajustamento aparelho ortopedico'),
  ('Z468', 'Colocação e ajustamento de outros aparelhos especificados', 'Z46.8 Colocacao e ajustamento outr aparelhos espec'),
  ('Z469', 'Colocação e ajustamento de aparelho não especificado', 'Z46.9 Colocacao e ajustamento de aparelho NE'),
  ('Z47', 'Outros cuidados de seguimento ortopédico', 'Z47 Outr cuidados de seguimento ortopedico'),
  ('Z470', 'Seguimento envolvendo remoção de placa de fratura e outros dispositivos de fixação interna', 'Z47.0 Seguim env rem placa frat outr disp fix int'),
  ('Z478', 'Outros seguimentos ortopédicos especificados', 'Z47.8 Outr seguimentos ortopedicos espec'),
  ('Z479', 'Seguimento ortopédico não especificado', 'Z47.9 Seguimento ortopedico NE'),
  ('Z48', 'Outro seguimento cirúrgico', 'Z48 Outr seguimento cirurgico'),
  ('Z480', 'Cuidados a curativos e suturas cirúrgicas', 'Z48.0 Cuidados a curativos e suturas cirurgicas'),
  ('Z488', 'Outro seguimento cirúrgico especificado', 'Z48.8 Outr seguimento cirurgico espec'),
  ('Z489', 'Seguimento cirúrgico não especificado', 'Z48.9 Seguimento cirurgico NE'),
  ('Z49', 'Cuidados envolvendo diálise', 'Z49 Cuidados envolv dialise'),
  ('Z490', 'Cuidado preparatório para diálise', 'Z49.0 Cuidado preparatorio p/dialise'),
  ('Z491', 'Diálise extracorpórea', 'Z49.1 Dialise extracorporea'),
  ('Z492', 'Outras diálises', 'Z49.2 Outr dialises'),
  ('Z50', 'Cuidados envolvendo o uso de procedimentos de reabilitação', 'Z50 Cuidados envolv uso proced de reabilitacao'),
  ('Z500', 'Reabilitação cardíaca', 'Z50.0 Reabilitacao cardiaca'),
  ('Z501', 'Outra fisioterapia', 'Z50.1 Outr fisioterapia'),
  ('Z502', 'Reabilitação de alcoólatra', 'Z50.2 Reabilitacao de alcoolatra'),
  ('Z503', 'Reabilitação de toxicodependentes', 'Z50.3 Reabilitacao de toxicodependentes'),
  ('Z504', 'Psicoterapia, não classificada em outra parte', 'Z50.4 Psicoterapia NCOP'),
  ('Z505', 'Reabilitação da linguagem', 'Z50.5 Reabilitacao da linguagem'),
  ('Z506', 'Treinamento ortóptico', 'Z50.6 Treinamento ortoptico'),
  ('Z507', 'Terapia ocupacional e reabilitação vocacional não classificada em outra parte', 'Z50.7 Terapia ocupacional reabilit vocacional NCOP'),
  ('Z508', 'Cuidados envolvendo uso de outros procedimentos de reabilitação', 'Z50.8 Cuidados envolv uso de outr proced reabilit'),
  ('Z509', 'Cuidados envolvendo uso de procedimento de reabilitação não especificado', 'Z50.9 Cuidados envolv uso de proced reabilit NE'),
  ('Z51', 'Outros cuidados médicos', 'Z51 Outr cuidados medicos'),
  ('Z510', 'Sessão de radioterapia', 'Z51.0 Sessao de radioterapia'),
  ('Z511', 'Sessão de quimioterapia por neoplasia', 'Z51.1 Sessao de quimioterapia p/neoplasia'),
  ('Z512', 'Outra quimioterapia', 'Z51.2 Outr quimioterapia'),
  ('Z513', 'Transfusão de sangue, sem diagnóstico registrado', 'Z51.3 Transfusao de sangue s/diagn registrado'),
  ('Z514', 'Cuidado preparatório para tratamento subsequente não classificado em outra parte', 'Z51.4 Cuidado preparatorio p/trat subsequente NCOP'),
  ('Z515', 'Cuidado paliativo', 'Z51.5 Cuidado paliativo'),
  ('Z516', 'Dessensibilização a alérgenos', 'Z51.6 Dessensibilizacao a alergenos'),
  ('Z518', 'Outro cuidado médico especificado', 'Z51.8 Outr cuidado medico espec'),
  ('Z519', 'Cuidado médico não especificado', 'Z51.9 Cuidado medico NE'),
  ('Z52', 'Doadores de órgãos e tecidos', 'Z52 Doadores de orgaos e tec'),
  ('Z520', 'Doador de sangue', 'Z52.0 Doador de sangue'),
  ('Z521', 'Doador de pele', 'Z52.1 Doador de pele'),
  ('Z522', 'Doador de osso', 'Z52.2 Doador de osso'),
  ('Z523', 'Doador de medula óssea', 'Z52.3 Doador de medula ossea'),
  ('Z524', 'Doador de rim', 'Z52.4 Doador de rim'),
  ('Z525', 'Doador de córnea', 'Z52.5 Doador de cornea'),
  ('Z526', 'Doador de fígado', 'Z52.6 Doador de figado'),
  ('Z527', 'Doador de coração', 'Z52.7 Doador de coracao'),
  ('Z528', 'Doador de outros órgãos ou tecidos', 'Z52.8 Doador de outr orgaos ou tec'),
  ('Z529', 'Doador de órgão ou tecido não especificado', 'Z52.9 Doador de orgao ou tec NE'),
  ('Z53', 'Pessoas em contato com serviços de saúde para procedimentos específicos não realizados', 'Z53 Pessoas cont serv saude proced esp n realiz'),
  ('Z530', 'Procedimento não realizado devido à contra-indicação', 'Z53.0 Proced nao realizado dev contra-indicacao'),
  ('Z531', 'Procedimento não realizado devido à decisão do paciente por razões de crença ou grupo de pressão', 'Z53.1 Proc n real dev dec pac raz crenc grup press'),
  ('Z532', 'Procedimento não realizado devido à decisão do paciente por outras razões e as não especificadas', 'Z53.2 Proced n realiz dev dec pac outr razoes e NE'),
  ('Z538', 'Procedimento não realizado por outras razões', 'Z53.8 Proced nao realizado p/outr razoes'),
  ('Z539', 'Procedimento não realizado por razão não especificada', 'Z53.9 Proced nao realizado p/razao NE'),
  ('Z54', 'Convalescença', 'Z54 Convalescenca'),
  ('Z540', 'Convalescença após cirurgia', 'Z54.0 Convalescenca apos cirurgia'),
  ('Z541', 'Convalescença após radioterapia', 'Z54.1 Convalescenca apos radioterapia'),
  ('Z542', 'Convalescença após quimioterapia', 'Z54.2 Convalescenca apos quimioterapia'),
  ('Z543', 'Convalescença após psicoterapia', 'Z54.3 Convalescenca apos psicoterapia'),
  ('Z544', 'Convalescença após tratamento de fratura', 'Z54.4 Convalescenca apos tratamento de frat'),
  ('Z547', 'Convalescença após tratamento combinado', 'Z54.7 Convalescenca apos tratamento combinado'),
  ('Z548', 'Convalescença após outro tratamento', 'Z54.8 Convalescenca apos outr tratamento'),
  ('Z549', 'Convalescença após tratamento não especificado', 'Z54.9 Convalescenca apos tratamento NE'),
  ('Z55', 'Problemas relacionados com a educação e com a alfabetização', 'Z55 Problemas relac educacao e alfabetizacao'),
  ('Z550', 'Analfabetismo e baixa escolaridade', 'Z55.0 Analfabetismo e baixa escolaridade'),
  ('Z551', 'Escolarização não disponível e impossível', 'Z55.1 Escolarizacao nao disponivel e impossivel'),
  ('Z552', 'Reprovação em exames', 'Z55.2 Reprovacao em exames'),
  ('Z553', 'Maus resultados escolares', 'Z55.3 Maus resultados escolares'),
  ('Z554', 'Má adaptação escolar e dificuldades com professores e colegas', 'Z55.4 Ma adaptacao escolar e dific c/prof colegas'),
  ('Z558', 'Outros problemas relacionados com a educação e com a alfabetização', 'Z55.8 Outr probl relac educacao e alfabetizacao'),
  ('Z559', 'Problemas não especificados relacionados com a educação e com a alfabetização', 'Z55.9 Problemas NE relac educacao e alfabetizacao'),
  ('Z56', 'Problemas relacionados com o emprego e com o desemprego', 'Z56 Problemas relacionados emprego e desemprego'),
  ('Z560', 'Desemprego não especificado', 'Z56.0 Desemprego NE'),
  ('Z561', 'Mudança de emprego', 'Z56.1 Mudanca de emprego'),
  ('Z562', 'Ameaça de perda de emprego', 'Z56.2 Ameaca de perda de emprego'),
  ('Z563', 'Ritmo de trabalho penoso', 'Z56.3 Ritmo de trabalho penoso'),
  ('Z564', 'Desacordo com patrão e colegas de trabalho', 'Z56.4 Desacordo c/patrao e colegas de trabalho'),
  ('Z565', 'Má adaptação ao trabalho', 'Z56.5 Ma adaptacao ao trabalho'),
  ('Z566', 'Outras dificuldades físicas e mentais relacionadas ao trabalho', 'Z56.6 Outr dific fisicas mentais relac ao trabalho'),
  ('Z567', 'Outros problemas e os não especificados relacionados com o emprego', 'Z56.7 Outr problemas e os NE relac emprego'),
  ('Z57', 'Exposição ocupacional a fatores de risco', 'Z57 Exposicao ocupacional a fatores de risco'),
  ('Z570', 'Exposição ocupacional ao ruído', 'Z57.0 Exposicao ocupacional ao ruido'),
  ('Z571', 'Exposição ocupacional à radiação', 'Z57.1 Exposicao ocupacional a radiacao'),
  ('Z572', 'Exposição ocupacional à poeira (pó)', 'Z57.2 Exposicao ocupacional a poeira'),
  ('Z573', 'Exposição ocupacional a outros contaminantes do ar', 'Z57.3 Exposicao ocupacional a outr contam do ar'),
  ('Z574', 'Exposição ocupacional a agentes tóxicos na agricultura', 'Z57.4 Exposicao ocupacional agentes toxicos agric'),
  ('Z575', 'Exposição ocupacional a agentes tóxicos em outras indústrias', 'Z57.5 Exposic ocupac agentes toxicos outr industr'),
  ('Z576', 'Exposição ocupacional a temperaturas extremas', 'Z57.6 Exposicao ocupacional temperaturas extremas'),
  ('Z577', 'Exposição ocupacional à vibração', 'Z57.7 Exposicao ocupacional a vibracao'),
  ('Z578', 'Exposição ocupacional a outros fatores de risco', 'Z57.8 Exposicao ocupacional outr fatores de risco'),
  ('Z579', 'Exposição ocupacional a fator de risco não especificado', 'Z57.9 Exposicao ocupacional a fator de risco NE'),
  ('Z58', 'Problemas relacionados com o ambiente físico', 'Z58 Problemas relacionados c/o ambiente fisico'),
  ('Z580', 'Exposição ao ruído', 'Z58.0 Exposicao ao ruido'),
  ('Z581', 'Exposição à poluição atmosférica', 'Z58.1 Exposicao a poluicao atmosferica'),
  ('Z582', 'Exposição à poluição da água', 'Z58.2 Exposicao a poluicao da agua'),
  ('Z583', 'Exposição à poluição do solo', 'Z58.3 Exposicao a poluicao do solo'),
  ('Z584', 'Exposição à radiação', 'Z58.4 Exposicao a radiacao'),
  ('Z585', 'Exposição a outras poluições', 'Z58.5 Exposicao a outr poluicoes'),
  ('Z586', 'Água potável insuficiente', 'Z58.6 Agua potavel insuficiente'),
  ('Z587', 'Exposição à fumaça de tabaco', 'Z58.7 Exposição à fumaça de tabaco'),
  ('Z588', 'Outros problemas relacionados com o ambiente físico', 'Z58.8 Outr problemas relac ambiente fisico'),
  ('Z589', 'Problema não especificado relacionado com o ambiente físico', 'Z58.9 Problema NE relacionado ambiente fisico'),
  ('Z59', 'Problemas relacionados com a habitação e com as condições econômicas', 'Z59 Probl relac habitacao e  cond economicas'),
  ('Z590', 'Falta de domicílio fixo', 'Z59.0 Falta de domicilio fixo'),
  ('Z591', 'Habitação inadequada', 'Z59.1 Habitacao inadequada'),
  ('Z592', 'Desacordo com vizinhos, locatários e proprietários', 'Z59.2 Desacordo vizinhos locatarios proprietarios'),
  ('Z593', 'Problemas relacionados com a vida em instituição residencial', 'Z59.3 Probl relac vida em instituicao residencial'),
  ('Z594', 'Falta de alimentação adequada', 'Z59.4 Falta de alimentacao adequada'),
  ('Z595', 'Pobreza extrema', 'Z59.5 Pobreza extrema'),
  ('Z596', 'Baixo rendimento', 'Z59.6 Baixo rendimento'),
  ('Z597', 'Seguro social e medidas de bem-estar social insuficientes', 'Z59.7 Seguro social medidas bem-estar social insuf'),
  ('Z598', 'Outros problemas relacionados com a habitação e com as circunstâncias econômicas', 'Z59.8 Outr probl relac habitacao e circunst econom'),
  ('Z599', 'Circunstâncias não especificadas econômicas ou de habitação', 'Z59.9 Circunstancias NE economicas ou de habitacao'),
  ('Z60', 'Problemas relacionados com o meio social', 'Z60 Problemas relacionados c/o meio social'),
  ('Z600', 'Problemas de adaptação às transições do ciclo de vida', 'Z60.0 Probl adaptacao transicoes do ciclo de vida'),
  ('Z601', 'Situação parental atípica', 'Z60.1 Situacao parental atipica'),
  ('Z602', 'Viver só', 'Z60.2 Viver so'),
  ('Z603', 'Dificuldade de aculturação', 'Z60.3 Dificuldade de aculturacao'),
  ('Z604', 'Exclusão e rejeição sociais', 'Z60.4 Exclusao e rejeicao sociais'),
  ('Z605', 'Objeto de discriminação e perseguição percebidas', 'Z60.5 Objeto discriminacao perseguicao percebidas'),
  ('Z608', 'Outros problemas relacionados com o meio social', 'Z60.8 Outr problemas relacionados c/o meio social'),
  ('Z609', 'Problema não especificado relacionado com o meio social', 'Z60.9 Problema NE relacionado c/o meio social'),
  ('Z61', 'Problemas relacionados com eventos negativos de vida na infância', 'Z61 Problemas relac eventos negat vida infancia'),
  ('Z610', 'Perda de relação afetiva na infância', 'Z61.0 Perda de relacao afetiva na infancia'),
  ('Z611', 'Remoção do lar na infância', 'Z61.1 Remocao do lar na infancia'),
  ('Z612', 'Padrão alterado de relações familiares na infância', 'Z61.2 Padrao alterado relacoes familiares infancia'),
  ('Z613', 'Eventos que originam a perda de auto-estima na infância', 'Z61.3 Eventos orig perda auto-estima na infancia'),
  ('Z614', 'Problemas relacionados com abuso sexual alegado de uma criança por uma pessoa de dentro de seu grupo', 'Z61.4 Probl rel abuso sex aleg crianca p/pess grup'),
  ('Z615', 'Problemas relacionados com abuso sexual alegado de uma criança por pessoa de fora de seu grupo', 'Z61.5 Probl rel abus sex crianca p/pess  fora grup'),
  ('Z616', 'Problemas relacionados com abuso físico alegado da criança', 'Z61.6 Probl relac c/abuso fisico alegado crianca'),
  ('Z617', 'Experiência pessoal amedrontadora na infância', 'Z61.7 Experiencia pessoal amedrontadora infancia'),
  ('Z618', 'Outros eventos da vida pessoal negativos na infância', 'Z61.8 Outr eventos vida pessoal negativos infancia'),
  ('Z619', 'Evento pessoal negativo não especificado na infância', 'Z61.9 Evento pessoal negativo NE na infancia'),
  ('Z62', 'Outros problemas relacionados com a educação da criança', 'Z62 Outr probl relac c/a educacao da crianca'),
  ('Z620', 'Supervisão e controle inadequado por parte dos pais', 'Z62.0 Superv contr inadeq p/parte dos pais'),
  ('Z621', 'Superproteção por parte dos pais', 'Z62.1 Superprotecao p/parte dos pais'),
  ('Z622', 'Educação numa instituição', 'Z62.2 Educacao numa instituicao'),
  ('Z623', 'Hostilidade com relação a uma criança, transformada em bode expiatório', 'Z62.3 Hostil c/rel crianca tranf bode expiatorio'),
  ('Z624', 'Negligência emocional da criança', 'Z62.4 Negligencia emocional da crianca'),
  ('Z625', 'Outros problemas relacionados com negligência na educação dos filhos', 'Z62.5 Outr probl relac c/negl educacao dos filhos'),
  ('Z626', 'Pressões não apropriadas por parte dos pais e outras falhas de educação', 'Z62.6 Press nao apropr p/pais e outr falhas educ'),
  ('Z628', 'Outros problemas especificados relacionados com a educação dos filhos', 'Z62.8 Outr probl espec relac educacao dos filhos'),
  ('Z629', 'Problema não especificado relacionado com a educação dos filhos', 'Z62.9 Problema NE relac c/a educacao dos filhos'),
  ('Z63', 'Outros problemas relacionados com o grupo primário de apoio, inclusive com a situação familiar', 'Z63 Outr probl rel grupo prim apoio incl sit fam'),
  ('Z630', 'Problemas nas relações com cônjuge ou parceiro', 'Z63.0 Problemas nas relacoes c/conjuge ou parceiro'),
  ('Z631', 'Problemas nas relações com os pais ou com os sogros', 'Z63.1 Problemas relacoes c/os pais ou c/os sogros'),
  ('Z632', 'Suporte familiar inadequado', 'Z63.2 Suporte familiar inadequado'),
  ('Z633', 'Ausência de um dos membros da família', 'Z63.3 Ausencia de um dos membros da familia'),
  ('Z634', 'Desaparecimento ou falecimento de um membro da família', 'Z63.4 Desaparecimento falecimento membro familia'),
  ('Z635', 'Rompimento da família por separação ou divórcio', 'Z63.5 Rompimento familia p/separacao ou divorcio'),
  ('Z636', 'Parente dependente de cuidados, residente no domicílio', 'Z63.6 Parente dependente cuidados resid domicilio'),
  ('Z637', 'Outros acontecimentos difíceis com incidência na família ou no lar', 'Z63.7 Outr acontec dificeis incid familia lar'),
  ('Z638', 'Outros problemas especificados relacionados com o grupo primário de suporte', 'Z63.8 Outr probl espec relac grupo prim de suporte'),
  ('Z639', 'Problema não especificado relacionado com o grupo primário de suporte', 'Z63.9 Problema NE relac c/o grupo prim de suporte'),
  ('Z64', 'Problemas relacionados com algumas outras circunstâncias psicossociais', 'Z64 Problemas relac algumas outr circ psicossoc'),
  ('Z640', 'Problemas relacionados com uma gravidez não desejada', 'Z64.0 Problemas relac c/uma gravidez nao desejada'),
  ('Z641', 'Problemas relacionados com multiparidade', 'Z64.1 Problemas relacionados c/multiparidade'),
  ('Z642', 'Procura e aceitação de intervenções físicas, nutricionais, ou químicas conhecidas como perigosas ou nocivas', 'Z64.2 Proc aceit interv fis nutr quim perig nociv'),
  ('Z643', 'Procura e aceitação de intervenções comportamentais ou psicológicas conhecidas como perigosas ou nocivas', 'Z64.3 Proc aceit interv comport psic perig nocivas'),
  ('Z644', 'Desacordo com conselheiros', 'Z64.4 Desacordo c/conselheiros'),
  ('Z65', 'Problemas relacionados com outras circunstâncias psicossociais', 'Z65 Probl relac outr circunstancias psicossoc'),
  ('Z650', 'Condenação, sem prisão, por tribunal civil ou criminal', 'Z65.0 Condenacao s/prisao tribunal civil criminal'),
  ('Z651', 'Prisão ou encarceramento', 'Z65.1 Prisao ou encarceramento'),
  ('Z652', 'Problemas ligados à libertação de prisão', 'Z65.2 Problemas ligados a libertacao de prisao'),
  ('Z653', 'Problemas ligados à outras circunstâncias legais', 'Z65.3 Problemas ligados a outr circunst legais'),
  ('Z654', 'Vítima de crime ou de atos terroristas', 'Z65.4 Vitima de crime ou de atos terroristas'),
  ('Z655', 'Exposição a catástrofe, guerra e outras hostilidades', 'Z65.5 Exposicao catastrofe guerra e outr hostilid'),
  ('Z658', 'Outros problemas especificados relacionados com circunstâncias psicossociais', 'Z65.8 Outr probl espec relac circunst psicossoc'),
  ('Z659', 'Problemas relacionados com circunstâncias psicossociais não especificadas', 'Z65.9 Probl relac circunstancias psicossociais NE'),
  ('Z70', 'Aconselhamento relativo às atitudes, comportamento e orientação em matéria de sexualidade', 'Z70 Aconselh relat atit comport orient sexualid'),
  ('Z700', 'Acompanhamento relativo às atitudes em matéria de sexualidade', 'Z70.0 Acompanhament relat atitud materia sexualid'),
  ('Z701', 'Aconselhamento relativo ao comportamento e à orientação sexual do sujeito', 'Z70.1 Aconselh relat comport orient sexual sujeito'),
  ('Z702', 'Aconselhamento relativo ao comportamento e à orientação sexual de um terceiro', 'Z70.2 Aconselh relat comport orient sexual terc'),
  ('Z703', 'Aconselhamento relativo a preocupações associadas relacionadas com as atitudes, o comportamento e orientação em matéria de sexualidade', 'Z70.3 Acons rel preoc ass rel atit comp orient sex'),
  ('Z708', 'Outros aconselhamentos em matéria de sexualidade', 'Z70.8 Outr aconselhamentos em materia sexualidade'),
  ('Z709', 'Aconselhamento não especificado em matéria de sexualidade', 'Z70.9 Aconselhamento NE em materia de sexualidade'),
  ('Z71', 'Pessoas em contato com os serviços de saúde para outros aconselhamentos e conselho médico, não classificados em outra parte', 'Z71 Pess cont serv saud outr acons cons med NCOP'),
  ('Z710', 'Pessoa que consulta no interesse de um terceiro', 'Z71.0 Pessoa que consulta interesse de um terceiro'),
  ('Z711', 'Pessoa com medo de uma queixa para a qual não foi feito diagnóstico', 'Z71.1 Pessoa c/medo queixa nao foi feito diagn'),
  ('Z712', 'Pessoa que consulta para explicação de achados de exame', 'Z71.2 Pessoa que consulta p/explic achados exame'),
  ('Z713', 'Aconselhamento e supervisão dietéticos', 'Z71.3 Aconselhamento e supervisao dieteticos'),
  ('Z714', 'Aconselhamento e supervisão para abuso de álcool', 'Z71.4 Aconselhamento e supervisao p/abuso alcool'),
  ('Z715', 'Aconselhamento e supervisão para abuso de drogas', 'Z71.5 Aconselhamento e supervisao p/abuso drogas'),
  ('Z716', 'Aconselhamento para o abuso de fumo', 'Z71.6 Aconselhamento p/o abuso de fumo'),
  ('Z717', 'Aconselhamento a propósito do vírus da imunodeficiência humana (HIV)', 'Z71.7 Aconselhamento a proposito do HIV'),
  ('Z718', 'Outros aconselhamentos especificados', 'Z71.8 Outr aconselhamentos espec'),
  ('Z719', 'Aconselhamento não especificado', 'Z71.9 Aconselhamento NE'),
  ('Z72', 'Problemas relacionados com o estilo de vida', 'Z72 Problemas relacionados c/o estilo de vida'),
  ('Z720', 'Uso do tabaco', 'Z72.0 Uso do tabaco'),
  ('Z721', 'Uso de álcool', 'Z72.1 Uso de alcool'),
  ('Z722', 'Uso de droga', 'Z72.2 Uso de droga'),
  ('Z723', 'Falta de exercício físico', 'Z72.3 Falta de exercicio fisico'),
  ('Z724', 'Regime e hábitos alimentares inadequados', 'Z72.4 Regime e habitos alimentares inadequados'),
  ('Z725', 'Comportamento sexual de alto risco', 'Z72.5 Comport sexual de alto risco'),
  ('Z726', 'Mania de jogo e apostas', 'Z72.6 Mania de jogo e apostas'),
  ('Z728', 'Outros problemas relacionados com o estilo de vida', 'Z72.8 Outr problemas relacionados c/o estilo vida'),
  ('Z729', 'Problema não especificado relacionado com o estilo de vida', 'Z72.9 Problema NE relacionado c/o estilo de vida'),
  ('Z73', 'Problemas relacionados com a organização de seu modo de vida', 'Z73 Problemas relacionados c/a organiz modo vida'),
  ('Z730', 'Esgotamento', 'Z73.0 Esgotamento'),
  ('Z731', 'Acentuação de traços de personalidade', 'Z73.1 Acentuacao de tracos de personalidade'),
  ('Z732', 'Falta de repouso e de lazer', 'Z73.2 Falta de repouso e de lazer'),
  ('Z733', 'Stress não classificado em outra parte', 'Z73.3 Stress NCOP'),
  ('Z734', 'Habilidades sociais inadequadas não classificadas em outra parte', 'Z73.4 Habilidades sociais inadequadas NCOP'),
  ('Z735', 'Conflito sobre o papel social, não classificado em outra parte', 'Z73.5 Conflito sobre o papel social NCOP'),
  ('Z736', 'Limites impostos às atividades por invalidez', 'Z73.6 Limites impostos as atividades p/invalidez'),
  ('Z738', 'Outros problemas relacionados com a organização do seu modo de vida', 'Z73.8 Outr probl relac organiz modo de vida'),
  ('Z739', 'Problema relacionado com a organização de seu modo de vida não especificado', 'Z73.9 Probl relac organiz modo de vida NE'),
  ('Z74', 'Problemas relacionados com a dependência de uma pessoa que oferece cuidados de saúde', 'Z74 Probl relac depend pess q oferece cuid saude'),
  ('Z740', 'Mobilidade reduzida', 'Z74.0 Mobilidade reduzida'),
  ('Z741', 'Necessidade de assistência com cuidados pessoais', 'Z74.1 Necessidade de assist c/cuidados pessoais'),
  ('Z742', 'Necessidade de assistência a domicílio, sendo que nenhuma pessoa do lar é capaz de assegurar os cuidados', 'Z74.2 Necess assist domic nenh pessoa lar'),
  ('Z743', 'Necessidade de supervisão contínua', 'Z74.3 Necessidade de supervisao continua'),
  ('Z748', 'Outros problemas relacionados com a dependência de pessoa que oferece cuidados de saúde', 'Z74.8 Outr probl relac dep pess q ofer cuid saude'),
  ('Z749', 'Problema não especificado relacionado com a dependência de pessoa que oferece cuidados de saúde', 'Z74.9 Probl NE relac depend pess q ofer cuid saude'),
  ('Z75', 'Problemas relacionados com as facilidades médicas e outros cuidados de saúde', 'Z75 Probl relac facilid medic outr cuid saude'),
  ('Z750', 'Falta de disponibilidade de serviços médicos no domicílio', 'Z75.0 Falta disponib servicos medicos no domicilio'),
  ('Z751', 'Pessoa esperando ser admitida em estabelecimento médico adequado em outra parte', 'Z75.1 Pess esper ser admit estab med adeq out part'),
  ('Z752', 'Outro período de espera para investigação e tratamento', 'Z75.2 Outr periodo de espera p/invest e tratamento'),
  ('Z753', 'Facilidades de saúde não disponíveis ou não acessíveis', 'Z75.3 Facilid saude nao disponiveis ou nao acess'),
  ('Z754', 'Outras organizações de cuidados não disponíveis ou não acessíveis', 'Z75.4 Outr organiz cuidados nao disp ou nao acess'),
  ('Z755', 'Cuidados dispensados para ajudar às famílias durante as férias', 'Z75.5 Cuid dispensados ajudar familias ferias'),
  ('Z758', 'Outras dificuldades especificadas relacionadas com facilidades médicas e com outros cuidados de saúde', 'Z75.8 Outr dific esp relac facil med out cuid saud'),
  ('Z759', 'Problema não especificado relacionado com facilidades médicas e com outros cuidados de saúde', 'Z75.9 Probl NE relac facil med outr cuid saude'),
  ('Z76', 'Pessoas em contato com os serviços de saúde em outras circunstâncias', 'Z76 Pessoas cont serv saude em outr circunst'),
  ('Z760', 'Emissão de prescrição de repetição', 'Z76.0 Emissao de prescricao de repeticao'),
  ('Z761', 'Supervisão e cuidado de saúde de crianças assistidas', 'Z76.1 Superv cuid saude de criancas assistidas'),
  ('Z762', 'Supervisão de cuidado de saúde de outras crianças ou recém-nascidos sadios', 'Z76.2 Superv cuid saud out crianc rec-nasc sadios'),
  ('Z763', 'Pessoa em boa saúde acompanhando pessoa doente', 'Z76.3 Pessoa em boa saude acompanh pessoa doente'),
  ('Z764', 'Outros pensionistas em estabelecimentos de cuidados de saúde', 'Z76.4 Outr pensionistas estab de cuidados de saude'),
  ('Z765', 'Pessoa fingindo ser doente (simulação consciente)', 'Z76.5 Pessoa fingindo ser doente'),
  ('Z768', 'Contatos com serviços de saúde por outras circunstâncias especificadas', 'Z76.8 Cont serv saude p/outr circunstancias espec'),
  ('Z769', 'Pessoa em contato com serviços de saúde em circunstâncias não especificadas', 'Z76.9 Pessoa cont serv saude em circunstancias NE'),
  ('Z80', 'História familiar de neoplasia maligna', 'Z80 Historia familiar de neopl malig'),
  ('Z800', 'História familiar de neoplasia maligna de órgãos digestivos', 'Z80.0 Historia familiar neopl malig org digestivos'),
  ('Z801', 'História familiar de neoplasia maligna de traquéia, brônquio e pulmão', 'Z80.1 Historia famil neopl malig traq bronq pulm'),
  ('Z802', 'História familiar de neoplasia maligna de outros órgãos respiratórios e intratorácicos', 'Z80.2 Hist fam neopl malig outr org resp intrator'),
  ('Z803', 'História familiar de neoplasia de mama', 'Z80.3 Historia familiar de neoplasia de mama'),
  ('Z804', 'História familiar de neoplasia maligna de órgãos genitais', 'Z80.4 Historia familiar neopl malig org genitais'),
  ('Z805', 'História familiar de neoplasia maligna do trato urinário', 'Z80.5 Historia familiar neopl malig trato urinario'),
  ('Z806', 'História familiar de leucemia', 'Z80.6 Historia familiar de leucemia'),
  ('Z807', 'História familiar de outras neoplasias malignas dos tecidos linfático, hematopoético e correlacionados', 'Z80.7 Hist fam out neopl malig tec linf hemat corr'),
  ('Z808', 'História familiar de neoplasia maligna de outros órgãos ou aparelhos', 'Z80.8 Hist familiar neopl malig outr org aparelhos'),
  ('Z809', 'História familiar de neoplasia maligna não especificada', 'Z80.9 Historia familiar de neopl malig NE'),
  ('Z81', 'História familiar de transtornos mentais e comportamentais', 'Z81 Historia familiar transt mentais e comport'),
  ('Z810', 'História familiar de retardo mental', 'Z81.0 Historia familiar de retardo mental'),
  ('Z811', 'História familiar de abuso de álcool', 'Z81.1 Historia familiar de abuso de alcool'),
  ('Z812', 'História familiar de abuso de fumo', 'Z81.2 Historia familiar de abuso de fumo'),
  ('Z813', 'História familiar de abuso de outra substância psicoativa', 'Z81.3 Historia familiar abuso outr subst psicoativ'),
  ('Z814', 'História familiar de abuso de outra substância', 'Z81.4 Historia familiar de abuso de outr subst'),
  ('Z818', 'História familiar de outros transtornos mentais e comportamentais', 'Z81.8 Hist familiar outr transt mentais comport'),
  ('Z82', 'História familiar de algumas incapacidades e doenças crônicas que conduzem a incapacitação', 'Z82 Hist fam alg incap doenc cron incapacitacao'),
  ('Z820', 'História familiar de epilepsia e de outras doenças do sistema nervoso', 'Z82.0 Hist fam epilepsia outr doenc sist nerv'),
  ('Z821', 'História familiar de cegueira e perda de visão', 'Z82.1 Historia familiar cegueira e perda de visao'),
  ('Z822', 'História familiar de surdez e perda de audição', 'Z82.2 Historia familiar surdez e perda de audicao'),
  ('Z823', 'História familiar de acidente vascular cerebral', 'Z82.3 Historia familiar de acid vascular cerebral'),
  ('Z824', 'História familiar de doença isquêmica do coração e outras doenças do aparelho circulatório', 'Z82.4 Hist fam doenc isq coracao out doenc ap circ'),
  ('Z825', 'História familiar de asma e outras doenças respiratórias inferiores crônicas', 'Z82.5 Hist fam asma outr doenc resp infer cronicas'),
  ('Z826', 'História familiar de artrite e outras doenças do sistema osteomuscular e tecido conjuntivo', 'Z82.6 Hist fam artr out doenc sist osteom tec conj'),
  ('Z827', 'História familiar de malformações e deformações congênitas e anomalias cromossômicas', 'Z82.7 Hist fam malform deform congen anom cromos'),
  ('Z828', 'História familiar de outras incapacidades e doenças crônicas que conduzem a incapacitação, não classificadas em outra parte', 'Z82.8 Hist fam outr incap doenc cron incapac NCOP'),
  ('Z83', 'História familiar de outros transtornos específicos', 'Z83 Historia familiar de outr transt especificos'),
  ('Z830', 'História familiar de doença pelo vírus da imunodeficiência humana (HIV)', 'Z83.0 Historia familiar de doenc p/HIV'),
  ('Z831', 'História familiar de outras doenças infecciosas e parasitárias', 'Z83.1 Historia familiar outr doenc infecc parasit'),
  ('Z832', 'História familiar de doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários', 'Z83.2 Hist fam doenc sang org hemat transt imunit'),
  ('Z833', 'História familiar de diabetes mellitus', 'Z83.3 Historia familiar de diabetes mellitus'),
  ('Z834', 'História familiar de outras doenças endócrinas, nutricionais e metabólicas', 'Z83.4 Hist fam outr doenc endocr nutr e metab'),
  ('Z835', 'História familiar de outros transtornos dos olhos e dos ouvidos', 'Z83.5 Hist fam outr transt dos olhos e dos ouvidos'),
  ('Z836', 'História familiar de doenças do aparelho respiratório', 'Z83.6 Historia familiar de doenc aparelho respirat'),
  ('Z837', 'História familiar das doenças do aparelho digestivo', 'Z83.7 Historia familiar doenc aparelho digestivo'),
  ('Z84', 'História familiar de outras afecções', 'Z84 Historia familiar de outr afeccoes'),
  ('Z840', 'História familiar de doenças da pele e do tecido subcutâneo', 'Z84.0 Historia familiar doenc da pele e tec subcut'),
  ('Z841', 'História familiar de transtornos do rim e ureter', 'Z84.1 Historia familiar de transt do rim e ureter'),
  ('Z842', 'História familiar de outras doenças do aparelho geniturinário', 'Z84.2 Historia familiar outr doenc ap geniturinar'),
  ('Z843', 'História familiar de consangüinidade', 'Z84.3 Historia familiar de consanguinidade'),
  ('Z848', 'História familiar de outras afecções especificadas', 'Z84.8 Historia familiar de outr afeccoes espec'),
  ('Z85', 'História pessoal de neoplasia maligna', 'Z85 Historia pessoal de neopl malig'),
  ('Z850', 'História pessoal de neoplasia maligna de órgãos digestivos', 'Z85.0 Historia pessoal neopl malig org digestivos'),
  ('Z851', 'História pessoal de neoplasia maligna de traquéia, brônquio e pulmão', 'Z85.1 Hist pess neopl malig traq bronquio e pulmao'),
  ('Z852', 'História pessoal de neoplasia maligna de outros órgãos respiratórios e intratorácicos', 'Z85.2 Hist pess neopl malig out org resp intrator'),
  ('Z853', 'História pessoal de neoplasia maligna de mama', 'Z85.3 Historia pessoal de neopl malig de mama'),
  ('Z854', 'História pessoal de neoplasia maligna de órgãos genitais', 'Z85.4 Historia pessoal neopl malig orgaos genitais'),
  ('Z855', 'História pessoal de neoplasia maligna de trato urinário', 'Z85.5 Historia pessoal neopl malig trato urinario'),
  ('Z856', 'História pessoal de leucemia', 'Z85.6 Historia pessoal de leucemia'),
  ('Z857', 'História pessoal de outras neoplasias malignas do tecido linfático, hematopoético e tecidos correlatos', 'Z85.7 Hist pess out neop mal tec linf hem tec corr'),
  ('Z858', 'História pessoal de neoplasias malignas de outros órgãos ou aparelhos', 'Z85.8 Hist pess neopl malig outr orgaos aparelhos'),
  ('Z859', 'História pessoal de neoplasia maligna não especificada', 'Z85.9 Historia pessoal de neopl malig NE'),
  ('Z86', 'História pessoal de algumas outras doenças', 'Z86 Historia pessoal de algumas outr doenc'),
  ('Z860', 'História pessoal de outras neoplasias', 'Z86.0 Historia pessoal de outr neoplasias'),
  ('Z861', 'História pessoal de doenças infecciosas e parasitárias', 'Z86.1 Historia pessoal de doenc infecc e parasit'),
  ('Z862', 'História pessoal de doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários', 'Z86.2 Hist pess doenc sang org hemat transt imunit'),
  ('Z863', 'História pessoal de doenças endócrinas, nutricionais e metabólicas', 'Z86.3 Hist pess doenc endocr nutric metabolicas'),
  ('Z864', 'História pessoal de abuso de substâncias psicoativas', 'Z86.4 Historia pessoal de abuso subst psicoativas'),
  ('Z865', 'História pessoal de outros transtornos mentais e comportamentais', 'Z86.5 Historia pessoal outr transt mentais comport'),
  ('Z866', 'História pessoal de doenças do sistema nervoso e dos órgãos dos sentidos', 'Z86.6 Hist pess doenc sist nerv org sentidos'),
  ('Z867', 'História pessoal de doenças do aparelho circulatório', 'Z86.7 Historia pessoal doenc aparelho circulatorio'),
  ('Z87', 'História pessoal de outras doenças e afecções', 'Z87 Historia pessoal de outr doenc e afeccoes'),
  ('Z870', 'História pessoal de doenças do aparelho respiratório', 'Z87.0 Historia pessoal de doenc aparelho respirat'),
  ('Z871', 'História pessoal de doenças do aparelho digestivo', 'Z87.1 Historia pessoal de doenc aparelho digestivo'),
  ('Z872', 'História pessoal de doenças da pele e tecido subcutâneo', 'Z87.2 Historia pessoal doenc pele e tec subcutaneo'),
  ('Z873', 'História pessoal de doenças do sistema osteomuscular e tecido conjuntivo', 'Z87.3 Hist pess doenc sist osteomusc e tec conjunt'),
  ('Z874', 'História pessoal de doenças do aparelho geniturinário', 'Z87.4 Hist pess doenc do aparelho geniturinario'),
  ('Z875', 'História pessoal de complicações da gravidez, parto e puerpério', 'Z87.5 Hist pess complic gravidez parto e puerperio'),
  ('Z876', 'História pessoal de algumas afecções originadas no período perinatal', 'Z87.6 Hist pess afecc orig periodo perinatal'),
  ('Z877', 'História pessoal de malformações e deformidades congênitas e anomalias cromossômicas', 'Z87.7 Hist pess malform deform congen anom cromos'),
  ('Z878', 'História pessoal de outras afecções especificadas', 'Z87.8 Historia pessoal de outr afeccoes espec'),
  ('Z88', 'História pessoal de alergia a drogas, medicamentos e a substâncias biológicas', 'Z88 Hist pess alergia drog medic subst biolog'),
  ('Z880', 'História pessoal de alergia à penicilina', 'Z88.0 Historia pessoal de alergia a penicilina'),
  ('Z881', 'História pessoal de alergia a outro agente antibiótico', 'Z88.1 Hist pessoal alergia outr agente antibiotico'),
  ('Z882', 'História pessoal de alergia às sulfonamidas', 'Z88.2 Historia pessoal de alergia as sulfonamidas'),
  ('Z883', 'História pessoal de alergia a outros agentes antiinfecciosos', 'Z88.3 Hist pess alergia a outr agentes antiinfecc'),
  ('Z884', 'História pessoal de alergia a agente anestésico', 'Z88.4 Hist pess de alergia a agente anestesico'),
  ('Z885', 'História pessoal de alergia a agente narcótico', 'Z88.5 Hist pess de alergia a agente narcotico'),
  ('Z886', 'História pessoal de alergia a agente analgésico', 'Z88.6 Hist pessoal de alergia a agente analgesico'),
  ('Z887', 'História pessoal de alergia a soro e à vacina', 'Z88.7 Hist pessoal de alergia a soro e a vacina'),
  ('Z888', 'História pessoal de alergia a outros drogas, medicamentos e substâncias biológicas', 'Z88.8 Hist pess alerg outr drog medic subst biolog'),
  ('Z889', 'História pessoal de alergia a drogas, medicamentos e substâncias biológicas não especificadas', 'Z88.9 Hist pess alergia drog medic subst biolog NE'),
  ('Z89', 'Ausência adquirida de membros', 'Z89 Ausencia adquir de membros'),
  ('Z890', 'Ausência adquirida de dedo(s) da mão (inclusive polegar) unilateral', 'Z89.0 Ausencia adquir de dedos da mao unilateral'),
  ('Z891', 'Ausência adquirida de mão e punho', 'Z89.1 Ausencia adquir de mao e punho'),
  ('Z892', 'Ausência adquirida de braço acima do punho', 'Z89.2 Ausencia adquir de braco acima do punho'),
  ('Z893', 'Ausência adquirida de ambos membros superiores (qualquer nível)', 'Z89.3 Ausencia adquir de ambos membros super'),
  ('Z894', 'Ausência adquirida de pé e tornozelo', 'Z89.4 Ausencia adquir de pe e tornozelo'),
  ('Z895', 'Ausência adquirida da perna ao nível ou abaixo do joelho', 'Z89.5 Ausencia adquir perna nivel abaixo joelho'),
  ('Z896', 'Ausência adquirida da perna acima do joelho', 'Z89.6 Ausencia adquir da perna acima do joelho'),
  ('Z897', 'Ausência adquirida de ambos membros inferiores (qualquer nível, exceto somente artelhos)', 'Z89.7 Ausencia adquir de ambos membros infer'),
  ('Z898', 'Ausência adquirida dos membros superiores e inferiores (qualquer nível)', 'Z89.8 Ausencia adquir dos membros super e infer'),
  ('Z899', 'Ausência adquirida de membro não especificado', 'Z89.9 Ausencia adquir de membro NE'),
  ('Z90', 'Ausência adquirida de órgãos não classificados em outra parte', 'Z90 Ausencia adquir de orgaos NCOP'),
  ('Z900', 'Ausência adquirida de parte da cabeça e do pescoço', 'Z90.0 Ausencia adquir de parte da cabeca e pescoco'),
  ('Z901', 'Ausência adquirida da(s) mama(s)', 'Z90.1 Ausencia adquir de mamas'),
  ('Z902', 'Ausência adquirida (de parte) do pulmão', 'Z90.2 Ausencia adquir do pulmao'),
  ('Z903', 'Ausência adquirida de parte do estômago', 'Z90.3 Ausencia adquir de parte do estomago'),
  ('Z904', 'Ausência adquirida de outras partes do trato digestivo', 'Z90.4 Ausencia adquir outr partes trato digestivo'),
  ('Z905', 'Ausência adquirida do rim', 'Z90.5 Ausencia adquir do rim'),
  ('Z906', 'Ausência adquirida de outras partes do trato urinário', 'Z90.6 Ausencia adquir outr partes trato urinario'),
  ('Z907', 'Ausência adquirida de órgão(s) genital(is)', 'Z90.7 Ausencia adquir de orgaos genitais'),
  ('Z908', 'Ausência adquirida de outros órgãos', 'Z90.8 Ausencia adquir de outr orgaos'),
  ('Z91', 'História pessoal de fatores de risco, não classificados em outra parte', 'Z91 Historia pessoal de fatores de risco NCOP'),
  ('Z910', 'História pessoal de alergia exceto a drogas e a substâncias biológicas', 'Z91.0 Hist pess alergia exc drogas subst biolog'),
  ('Z911', 'História pessoal de não aderência a tratamento ou regime médico', 'Z91.1 Hist pess nao ader trat ou regime medico'),
  ('Z912', 'História pessoal de má higiene pessoal', 'Z91.2 Historia pessoal de ma higiene pessoal'),
  ('Z913', 'História pessoal de ciclo vigília-sono anormal', 'Z91.3 Historia pessoal ciclo vigilia-sono anormal'),
  ('Z914', 'História pessoal de trauma psicológico não classificado em outra parte', 'Z91.4 Historia pessoal de trauma psicologico NCOP'),
  ('Z915', 'História pessoal de auto agressão', 'Z91.5 Historia pessoal de auto agressao'),
  ('Z916', 'História pessoal de outros traumas físicos', 'Z91.6 Historia pessoal de outr traumas fisicos'),
  ('Z918', 'História pessoal de outros fatores de risco especificados não classificados em outra parte', 'Z91.8 Hist pess outr fatores de risco espec NCOP'),
  ('Z92', 'História pessoal de tratamento médico', 'Z92 Historia pessoal de tratamento medico'),
  ('Z920', 'História pessoal de anticoncepção', 'Z92.0 Historia pessoal de anticoncepcao'),
  ('Z921', 'História pessoal de uso de longo prazo (atual) de anticoagulantes', 'Z92.1 Hist pess uso longo prazo de anticoagulantes'),
  ('Z922', 'História pessoal de uso de longo prazo (atual) de outros medicamentos', 'Z92.2 Hist pess uso longo prazo outr medicamentos'),
  ('Z923', 'História pessoal de irradiação', 'Z92.3 Historia pessoal de irradiacao'),
  ('Z924', 'História pessoal de cirurgia de grande porte não classificada em outra parte', 'Z92.4 Historia pessoal cirurgia grande porte NCOP'),
  ('Z925', 'História pessoal de medidas de reabilitação', 'Z92.5 Historia pessoal de medidas de reabilitacao'),
  ('Z926', 'História pessoal de quimioterapia para doença neoplásica', 'Z92.6 História pess quimioterap p/doenç neoplásica'),
  ('Z928', 'História pessoal de outros tratamentos médicos', 'Z92.8 Historia pessoal de outr tratamentos medicos'),
  ('Z929', 'História pessoal de tratamento médico não especificado', 'Z92.9 Historia pessoal de tratamento medico NE'),
  ('Z93', 'Orifícios artificiais', 'Z93 Orificios artificiais'),
  ('Z930', 'Traqueostomia', 'Z93.0 Traqueostomia'),
  ('Z931', 'Gastrostomia', 'Z93.1 Gastrostomia'),
  ('Z932', 'Ileostomia', 'Z93.2 Ileostomia'),
  ('Z933', 'Colostomia', 'Z93.3 Colostomia'),
  ('Z934', 'Outros orifícios artificiais do trato gastrointestinal', 'Z93.4 Outr orific artificiais trato gastrointest'),
  ('Z935', 'Cistostomia', 'Z93.5 Cistostomia'),
  ('Z936', 'Outros orifícios artificiais do aparelho urinário', 'Z93.6 Outr orificios artificiais aparelho urinario'),
  ('Z938', 'Outros orifícios artificiais', 'Z93.8 Outr orificios artificiais'),
  ('Z939', 'Orifício artificial não especificado', 'Z93.9 Orificio artificial NE'),
  ('Z94', 'Órgãos e tecidos transplantados', 'Z94 Orgaos e tec transplantados'),
  ('Z940', 'Rim transplantado', 'Z94.0 Rim transplantado'),
  ('Z941', 'Coração transplantado', 'Z94.1 Coracao transplantado'),
  ('Z942', 'Pulmão transplantado', 'Z94.2 Pulmao transplantado'),
  ('Z943', 'Coração e pulmões transplantados', 'Z94.3 Coracao e pulmoes transplantados'),
  ('Z944', 'Fígado transplantado', 'Z94.4 Figado transplantado'),
  ('Z945', 'Pele transplantada', 'Z94.5 Pele transplantada'),
  ('Z946', 'Osso transplantado', 'Z94.6 Osso transplantado'),
  ('Z947', 'Córnea transplantada', 'Z94.7 Cornea transplantada'),
  ('Z948', 'Outros órgãos e tecidos transplantados', 'Z94.8 Outr orgaos e tec transplantados'),
  ('Z949', 'Órgão e tecido não especificado transplantado', 'Z94.9 Orgao e tec NE transplantado'),
  ('Z95', 'Presença de implantes e enxertos cardíacos e vasculares', 'Z95 Presenca implantes enxertos cardiacos vasc'),
  ('Z950', 'Presença de marca-passo cardíaco', 'Z95.0 Presenca de marca-passo cardiaco'),
  ('Z951', 'Presença de enxerto de ponte (bypass) aortocoronária', 'Z95.1 Presenca de enxerto de ponte aortocoronaria'),
  ('Z952', 'Presença de prótese de válvula cardíaca', 'Z95.2 Presenca de protese de valvula cardiaca'),
  ('Z953', 'Presença de valva cardíaca xenógena', 'Z95.3 Presenca de valva cardiaca xenogena'),
  ('Z954', 'Presença de outras substituições valvares cardíacas', 'Z95.4 Presenca outr subst valvares cardiacas'),
  ('Z955', 'Presença de implante e enxerto de angioplastia coronária', 'Z95.5 Presenca impl enxerto angioplastia coronaria'),
  ('Z958', 'Presença de outros implantes e enxertos cardíacos e vasculares', 'Z95.8 Presenca outr impl enxertos card vasculares'),
  ('Z959', 'Presença de implante e enxerto cardíaco e vascular não especificado', 'Z95.9 Presenca impl enxerto cardiaco e vascular NE'),
  ('Z96', 'Presença de outros implantes funcionais', 'Z96 Presenca de outr implantes funcionais'),
  ('Z960', 'Presença de implantes urogenitais', 'Z96.0 Presenca de implantes urogenitais'),
  ('Z961', 'Presença de lente intra-ocular', 'Z96.1 Presenca de lente intra-ocular'),
  ('Z962', 'Presença de implante otológicos e audiológicos', 'Z96.2 Presenca de implante otologicos audiologicos'),
  ('Z963', 'Presença de laringe artificial', 'Z96.3 Presenca de laringe artificial'),
  ('Z964', 'Presença de implantes endócrinos', 'Z96.4 Presenca de implantes endocrinos'),
  ('Z965', 'Presença de raiz dentária e implantes mandibulares', 'Z96.5 Presenca raiz dentaria impl mandibulares'),
  ('Z966', 'Presença de implantes articulares ortopédicos', 'Z96.6 Presenca implantes articulares ortopedicos'),
  ('Z967', 'Presença de outros implantes de osso e tendão', 'Z96.7 Presenca de outr implantes de osso e tendao'),
  ('Z968', 'Presença de outros implantes funcionais especificados', 'Z96.8 Presenca de outr implantes funcionais espec'),
  ('Z969', 'Presença de implante funcional não especificado', 'Z96.9 Presenca de implante funcional NE'),
  ('Z97', 'Presença de outros dispositivos protéticos', 'Z97 Presenca de outr disp proteticos'),
  ('Z970', 'Presença de olho artificial', 'Z97.0 Presenca de olho artificial'),
  ('Z971', 'Presença de membro artificial (completo) (parcial)', 'Z97.1 Presenca de membro artificial'),
  ('Z972', 'Presença de dispositivo protético dentário (completo) (parcial)', 'Z97.2 Presenca de disp protetico dentario'),
  ('Z973', 'Presença de óculos e de lentes de contato', 'Z97.3 Presenca de oculos e de lentes de contato'),
  ('Z974', 'Presença de aparelho externo de surdez', 'Z97.4 Presenca de aparelho externo de surdez'),
  ('Z975', 'Presença de dispositivo anticoncepcional intra-uterino (DIU)', 'Z97.5 Presenca disp anticoncepcional intra-uterino'),
  ('Z978', 'Presença de outros dispositivos especificados', 'Z97.8 Presenca de outr disp espec'),
  ('Z98', 'Outros estados pós-cirúrgicos', 'Z98 Outr estados pos-cirurgicos'),
  ('Z980', 'Derivação intestinal ou anastomose intestinal', 'Z98.0 Derivacao intestinal ou anastomose intest'),
  ('Z981', 'Artrodese', 'Z98.1 Artrodese'),
  ('Z982', 'Presença de dispositivo de drenagem do líquor', 'Z98.2 Presenca de disp de drenagem do liquor'),
  ('Z988', 'Outros estados pós-cirúrgicos especificados', 'Z98.8 Outr estados pos-cirurgicos espec'),
  ('Z99', 'Dependência de máquinas e dispositivos capacitantes, não classificados em outra parte', 'Z99 Depend maquinas e disp capacitantes NCOP'),
  ('Z990', 'Dependência de aspirador', 'Z99.0 Dependencia de aspirador'),
  ('Z991', 'Dependência de respirador', 'Z99.1 Dependencia de respirador'),
  ('Z992', 'Dependência de diálise renal', 'Z99.2 Dependencia de dialise renal'),
  ('Z993', 'Dependência de cadeira de rodas', 'Z99.3 Dependencia de cadeira de rodas'),
  ('Z998', 'Dependência de outras máquinas e aparelhos capacitantes', 'Z99.8 Depend outr maq e aparelhos capacitantes'),
  ('Z999', 'Dependência de máquina e aparelho capacitante não especificado', 'Z99.9 Depend maquina e aparelho capacitante NE');
