INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('O00', 'Gravidez ectópica', 'O00 Gravidez ectopica'),
  ('O000', 'Gravidez abdominal', 'O00.0 Gravidez abdominal'),
  ('O001', 'Gravidez tubária', 'O00.1 Gravidez tubaria'),
  ('O002', 'Gravidez ovariana', 'O00.2 Gravidez ovariana'),
  ('O008', 'Outras formas de gravidez ectópica', 'O00.8 Outr form de gravidez ectopica'),
  ('O009', 'Gravidez ectópica, não especificada', 'O00.9 Gravidez ectopica NE'),
  ('O01', 'Mola hidatiforme', 'O01 Mola hidatiforme'),
  ('O010', 'Mola hidatiforme clássica', 'O01.0 Mola hidatiforme classica'),
  ('O011', 'Mola hidatiforme incompleta ou parcial', 'O01.1 Mola hidatiforme incompleta ou parcial'),
  ('O019', 'Mola hidatiforme não especificada', 'O01.9 Mola hidatiforme NE'),
  ('O02', 'Outros produtos anormais da concepção', 'O02 Outr produtos anormais da concepcao'),
  ('O020', 'Ovo claro e mola não-hidatiforme', 'O02.0 Ovo claro e mola nao-hidatiforme'),
  ('O021', 'Aborto retido', 'O02.1 Aborto retido'),
  ('O028', 'Outros produtos anormais da concepção especificados', 'O02.8 Outr produtos anormais da concepcao espec'),
  ('O029', 'Produto anormal da concepção, não especificado', 'O02.9 Produto anormal da concepcao NE'),
  ('O03', 'Aborto espontâneo', 'O03 Aborto espontaneo'),
  ('O030', 'Aborto espontâneo - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos', 'O03.0 Incompl complic inf trato genit org pelvicos'),
  ('O031', 'Aborto espontâneo - incompleto, complicado por hemorragia excessiva ou tardia', 'O03.1 Incompl complic hemorragia excessiva ou tard'),
  ('O032', 'Aborto espontâneo - incompleto, complicado por embolia', 'O03.2 Incompleto complicado p/embolia'),
  ('O033', 'Aborto espontâneo - incompleto, com outras complicações ou com complicações não especificadas', 'O03.3 Incompleto c/outr complic ou c/complic NE'),
  ('O034', 'Aborto espontâneo - incompleto, sem complicações', 'O03.4 Incompleto s/complic'),
  ('O035', 'Aborto espontâneo - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos', 'O03.5 Compl ou NE complic inf trato gen org pelvic'),
  ('O036', 'Aborto espontâneo - completo ou não especificado, complicado por hemorragia excessiva ou tardia', 'O03.6 Compl ou NE complic hemorrag excess ou tard'),
  ('O037', 'Aborto espontâneo - completo ou não especificado, complicado por embolia', 'O03.7 Completo ou NE complicado p/embolia'),
  ('O038', 'Aborto espontâneo - completo ou não especificado, com outras complicações ou com complicações não especificadas', 'O03.8 Compl ou NE c/outr complic ou c/complic NE'),
  ('O039', 'Aborto espontâneo - completo ou não especificado, sem complicações', 'O03.9 Completo ou NE s/complic'),
  ('O04', 'Aborto por razões médicas e legais', 'O04 Aborto p/razoes medicas e legais'),
  ('O040', 'Aborto por razões médicas e legais - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos', 'O04.0 Incompl complic inf trato genit org pelvicos'),
  ('O041', 'Aborto por razões médicas e legais - incompleto, complicado por hemorragia excessiva ou tardia', 'O04.1 Incompl complic hemorragia excessiva ou tard'),
  ('O042', 'Aborto por razões médicas e legais - incompleto, complicado por embolia', 'O04.2 Incompleto complicado p/embolia'),
  ('O043', 'Aborto por razões médicas e legais - incompleto, com outras complicações ou com complicações não especificadas', 'O04.3 Incompleto c/outr complic ou c/complic NE'),
  ('O044', 'Aborto por razões médicas e legais - incompleto, sem complicações', 'O04.4 Incompleto s/complic'),
  ('O045', 'Aborto por razões médicas e legais - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos', 'O04.5 Compl ou NE complic inf trato gen org pelvic'),
  ('O046', 'Aborto por razões médicas e legais - completo ou não especificado, complicado por hemorragia excessiva ou tardia', 'O04.6 Compl ou NE complic hemorrag excess ou tard'),
  ('O047', 'Aborto por razões médicas e legais - completo ou não especificado, complicado por embolia', 'O04.7 Completo ou NE complicado p/embolia'),
  ('O048', 'Aborto por razões médicas e legais - completo ou não especificado, com outras complicações ou com complicações não especificadas', 'O04.8 Compl ou NE c/outr complic ou c/complic NE'),
  ('O049', 'Aborto por razões médicas e legais - completo ou não especificado, sem complicações', 'O04.9 Completo ou NE s/complic'),
  ('O05', 'Outros tipos de aborto', 'O05 Outr tipos de aborto'),
  ('O050', 'Outros tipos de aborto - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos', 'O05.0 Incompl complic inf trato genit org pelvicos'),
  ('O051', 'Outros tipos de aborto - incompleto, complicado por hemorragia excessiva ou tardia', 'O05.1 Incompl complic hemorragia excessiva ou tard'),
  ('O052', 'Outros tipos de aborto - incompleto, complicado por embolia', 'O05.2 Incompleto complicado p/embolia'),
  ('O053', 'Outros tipos de aborto - incompleto, com outras complicações ou com complicações não especificadas', 'O05.3 Incompleto c/outr complic ou c/complic NE'),
  ('O054', 'Outros tipos de aborto - incompleto, sem complicações', 'O05.4 Incompleto s/complic'),
  ('O055', 'Outros tipos de aborto - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos', 'O05.5 Compl ou NE complic inf trato gen org pelvic'),
  ('O056', 'Outros tipos de aborto - completo ou não especificado, complicado por hemorragia excessiva ou tardia', 'O05.6 Compl ou NE complic hemorrag excess ou tard'),
  ('O057', 'Outros tipos de aborto - completo ou não especificado, complicado por embolia', 'O05.7 Completo ou NE complicado p/embolia'),
  ('O058', 'Outros tipos de aborto - completo ou não especificado, com outras complicações ou com complicações não especificadas', 'O05.8 Compl ou NE c/outr complic ou c/complic NE'),
  ('O059', 'Outros tipos de aborto - completo ou não especificado, sem complicações', 'O05.9 Completo ou NE s/complic'),
  ('O06', 'Aborto não especificado', 'O06 Aborto NE'),
  ('O060', 'Aborto não especificado - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos', 'O06.0 Incompl complic inf trato genit org pelvicos'),
  ('O061', 'Aborto não especificado - incompleto, complicado por hemorragia excessiva ou tardia', 'O06.1 Incompl complic hemorragia excessiva ou tard'),
  ('O062', 'Aborto não especificado - incompleto, complicado por embolia', 'O06.2 Incompleto complicado p/embolia'),
  ('O063', 'Aborto não especificado - incompleto, com outras complicações ou com complicações não especificadas', 'O06.3 Incompleto c/outr complic ou c/complic NE'),
  ('O064', 'Aborto não especificado - incompleto, sem complicações', 'O06.4 Incompleto s/complic'),
  ('O065', 'Aborto não especificado - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos', 'O06.5 Compl ou NE complic inf trato gen org pelvic'),
  ('O066', 'Aborto não especificado - completo ou não especificado, complicado por hemorragia excessiva ou tardia', 'O06.6 Compl ou NE complic hemorrag excess ou tard'),
  ('O067', 'Aborto não especificado - completo ou não especificado, complicado por embolia', 'O06.7 Completo ou NE complicado p/embolia'),
  ('O068', 'Aborto não especificado - completo ou não especificado, com outras complicações ou com complicações não especificadas', 'O06.8 Compl ou NE c/outr complic ou c/complic NE'),
  ('O069', 'Aborto não especificado - completo ou não especificado, sem complicações', 'O06.9 Completo ou NE s/complic'),
  ('O07', 'Falha de tentativa de aborto', 'O07 Falha de tentativa de aborto'),
  ('O070', 'Falha de aborto provocado por razões médicas, complicado por infecção do trato genital ou dos órgãos pélvicos', 'O07.0 Falh abort raz med compl inf tr gen org pelv'),
  ('O071', 'Falha de aborto provocado por razões médicas, complicado por hemorragia tardia ou excessiva', 'O07.1 Falh abort prov raz med compl hemor tard exc'),
  ('O072', 'Falha de aborto provocado por razões médicas, complicado por embolia', 'O07.2 Falh abort prov raz med complicado p/embolia'),
  ('O073', 'Falha de aborto provocado por razões médicas, com outras complicações ou com complicações não especificadas', 'O07.3 Falha aborto prov raz medic outr complic NE'),
  ('O074', 'Falha de aborto provocado por razões médicas, sem complicações', 'O07.4 Falha aborto prov raz medic s/complic'),
  ('O075', 'Outras formas, e as não especificadas, de falha na provocação de aborto, complicadas por infecção do trato genital e por infecção dos órgãos pélvicos', 'O07.5 Out for NE fal abor comp inf tr gen org pelv'),
  ('O076', 'Outras formas, e as não especificadas, de falha na provocação de aborto, complicadas por hemorragia tardia ou excessiva', 'O07.6 Out form NE falh abort compl hemor tard exc'),
  ('O077', 'Outras formas, e as não especificadas, de falha na provocação de aborto, complicadas por embolia', 'O07.7 Outr form e NE falh prov abort compl embolia'),
  ('O078', 'Outras formas, e as não especificadas, de falha na provocação de aborto, com outras complicações ou com complicações não especificadas', 'O07.8 Outr form e NE falh prov abort outr compl NE'),
  ('O079', 'Outras formas, e as não especificadas, de falha na provocação de aborto, sem complicação', 'O07.9 Outr form e NE falha prov aborto s/complic'),
  ('O08', 'Complicações conseqüentes a aborto e gravidez ectópica ou molar', 'O08 Complic conseq aborto gravidez ectop molar'),
  ('O080', 'Infecção do trato genital e dos órgãos pélvicos conseqüente a aborto e gravidez ectópica e molar', 'O08.0 Inf tr gen org pel cons abort grav ect molar'),
  ('O081', 'Hemorragia tardia ou excessiva conseqüente a aborto e a gravidez ectópica e molar', 'O08.1 Hemorr tard excess cons abort grav ect molar'),
  ('O082', 'Embolia conseqüente a aborto e a gravidez ectópica e molar', 'O08.2 Embolia conseq aborto grav ectopica molar'),
  ('O083', 'Choque conseqüente a aborto e a gravidez ectópica e molar', 'O08.3 Choque conseq aborto gravidez ectopica molar'),
  ('O084', 'Insuficiência renal conseqüente a aborto e a gravidez ectópica e molar', 'O08.4 Insuf renal conseq aborto grav ectopic molar'),
  ('O085', 'Distúrbios metabólicos conseqüentes a aborto e a gravidez ectópica e molar', 'O08.5 Dist metab conseq aborto grav ectopic molar'),
  ('O086', 'Lesão a órgãos e a tecidos pélvicos conseqüentes a aborto e a gravidez ectópica e molar', 'O08.6 Lesao org tec pelv cons abort grav ect molar'),
  ('O087', 'Outras complicações venosas conseqüentes a aborto e a gravidez ectópica e molar', 'O08.7 Outr compl venosas cons abort grav ect molar'),
  ('O088', 'Outras complicações conseqüentes a aborto e a gravidez ectópica e molar', 'O08.8 Outr complic conseq aborto grav ectop molar'),
  ('O089', 'Complicações conseqüentes a aborto e gravidez ectópica e molar, não especificadas', 'O08.9 Complic conseq aborto grav ectopica molar NE'),
  ('O10', 'Hipertensão pré-existente complicando a gravidez, o parto e o puerpério', 'O10 Hipertens pre-exist complic grav parto puerp'),
  ('O100', 'Hipertensão essencial pré-existente complicando a gravidez, o parto e o puerpério', 'O10.0 Hipertens ess pre-exis comp grav parto puerp'),
  ('O101', 'Doença cardíaca hipertensiva pré-existente complicando a gravidez, o parto e o puerpério', 'O10.1 Doen card hiper pre-ex comp grav parto puerp'),
  ('O102', 'Doença renal hipertensiva pré-existente complicando a gravidez, o parto e o puerpério', 'O10.2 Doen renal hiper pre-ex comp grav part puerp'),
  ('O103', 'Doença cardíaca e renal hipertensiva pré-existente complicando a gravidez, o parto e o puerpério', 'O10.3 Doen card ren hip pre-ex comp grav part puer'),
  ('O104', 'Hipertensão secundária pré-existente complicando a gravidez, o parto e o puerpério', 'O10.4 Hipertens sec pre-exist comp grav parto puer'),
  ('O109', 'Hipertensão pré-existente não especificada, complicando a gravidez, o parto e o puerpério', 'O10.9 Hipertens pre-exist NE compl grav parto puer'),
  ('O11', 'Distúrbio hipertensivo pré-existente com proteinúria superposta', 'O11 Dist hipertens pre-exist proteinuria superp'),
  ('O11', 'Distúrbio hipertensivo pré-existente com proteinúria superposta', 'O11 Dist hipertens pre-exist proteinuria superp'),
  ('O12', 'Edema e proteinúria gestacionais (induzidos pela gravidez), sem hipertensão', 'O12 Edema e proteinuria gestac s/hipertensao'),
  ('O120', 'Edema gestacional', 'O12.0 Edema gestacional'),
  ('O121', 'Proteinúria gestacional', 'O12.1 Proteinuria gestacional'),
  ('O122', 'Edema gestacional com proteinúria', 'O12.2 Edema gestacional c/proteinuria'),
  ('O13', 'Hipertensão gestacional (induzida pela gravidez) sem proteinúria significativa', 'O13 Hipertensao gestacional s/proteinuria signif'),
  ('O13', 'Hipertensão gestacional (induzida pela gravidez) sem proteinúria significativa', 'O13 Hipertensao gestacional s/proteinuria signif'),
  ('O14', 'Hipertensão gestacional (induzida pela gravidez) com proteinúria significativa', 'O14 Hipertensao gestacional c/proteinuria signif'),
  ('O140', 'Pré-eclâmpsia moderada', 'O14.0 Pre-eclampsia moderada'),
  ('O141', 'Pré-eclâmpsia grave', 'O14.1 Pre-eclampsia grave'),
  ('O149', 'Pré-eclâmpsia não especificada', 'O14.9 Pre-eclampsia NE'),
  ('O15', 'Eclâmpsia', 'O15 Eclampsia'),
  ('O150', 'Eclâmpsia na gravidez', 'O15.0 Eclampsia na gravidez'),
  ('O151', 'Eclâmpsia no trabalho de parto', 'O15.1 Eclampsia no trabalho de parto'),
  ('O152', 'Eclâmpsia no puerpério', 'O15.2 Eclampsia no puerperio'),
  ('O159', 'Eclâmpsia não especificada quanto ao período', 'O15.9 Eclampsia NE quanto ao periodo'),
  ('O16', 'Hipertensão materna não especificada', 'O16 Hipertensao materna NE'),
  ('O16', 'Hipertensão materna não especificada', 'O16 Hipertensao materna NE'),
  ('O20', 'Hemorragia do início da gravidez', 'O20 Hemorragia do inicio da gravidez'),
  ('O200', 'Ameaça de aborto', 'O20.0 Ameaca de aborto'),
  ('O208', 'Outras hemorragias do início da gravidez', 'O20.8 Outr hemorragias do inicio da gravidez'),
  ('O209', 'Hemorragia do início da gravidez, não especificada', 'O20.9 Hemorragia do inicio da gravidez NE'),
  ('O21', 'Vômitos excessivos na gravidez', 'O21 Vomitos excessivos na gravidez'),
  ('O210', 'Hiperêmese gravídica leve', 'O21.0 Hiperemese gravidica leve'),
  ('O211', 'Hiperêmese gravídica com distúrbio metabólico', 'O21.1 Hiperemese gravidica c/disturbio metabolico'),
  ('O212', 'Vômitos tardios da gravidez', 'O21.2 Vomitos tard da gravidez'),
  ('O218', 'Outras formas de vômitos complicando a gravidez', 'O21.8 Outr form de vomitos complicando a gravidez'),
  ('O219', 'Vômitos da gravidez, não especificados', 'O21.9 Vomitos da gravidez NE'),
  ('O22', 'Complicações venosas na gravidez', 'O22 Complic venosas na gravidez'),
  ('O220', 'Varizes dos membros inferiores na gravidez', 'O22.0 Varizes dos membros infer na gravidez'),
  ('O221', 'Varizes genitais na gravidez', 'O22.1 Varizes genitais na gravidez'),
  ('O222', 'Tromboflebite superficial na gravidez', 'O22.2 Tromboflebite superf na gravidez'),
  ('O223', 'Flebotrombose profunda na gravidez', 'O22.3 Flebotrombose profunda na gravidez'),
  ('O224', 'Hemorróidas na gravidez', 'O22.4 Hemorroidas na gravidez'),
  ('O225', 'Trombose venosa cerebral na gravidez', 'O22.5 Trombose venosa cerebral na gravidez'),
  ('O228', 'Outras complicações venosas na gravidez', 'O22.8 Outr complic venosas na gravidez'),
  ('O229', 'Complicações venosas na gravidez, não especificadas', 'O22.9 Complic venosas na gravidez NE'),
  ('O23', 'Infecções do trato geniturinário na gravidez', 'O23 Infecc do trato geniturinario na gravidez'),
  ('O230', 'Infecções do rim na gravidez', 'O23.0 Infecc do rim na gravidez'),
  ('O231', 'Infecções da bexiga na gravidez', 'O23.1 Infecc da bexiga na gravidez'),
  ('O232', 'Infecções da uretra na gravidez', 'O23.2 Infecc da uretra na gravidez'),
  ('O233', 'Infecções de outras partes do trato urinário na gravidez', 'O23.3 Infecc outr partes trato urinario gravidez'),
  ('O234', 'Infecção não especificada do trato urinário na gravidez', 'O23.4 Infecc NE do trato urinario na gravidez'),
  ('O235', 'Infecções do trato genital na gravidez', 'O23.5 Infecc do trato genital na gravidez'),
  ('O239', 'Outras infecções e as não especificadas do trato urinário na gravidez', 'O23.9 Outr infecc e NE trato urinario na gravidez'),
  ('O24', 'Diabetes mellitus na gravidez', 'O24 Diabetes mellitus na gravidez'),
  ('O240', 'Diabetes mellitus pré-existente, insulino-dependente', 'O24.0 Diabetes mellitus pre-exist insulino-depend'),
  ('O241', 'Diabetes mellitus pré-existente, não-insulino-dependente', 'O24.1 Diabetes mellitus pre-exist nao-insulino-dep'),
  ('O242', 'Diabetes mellitus pré-existente, relacionado com a desnutrição', 'O24.2 Diabetes mellitus pre-existente rel desnutr'),
  ('O243', 'Diabetes mellitus pré-existente, não especificado', 'O24.3 Diabetes mellitus pre-existente NE'),
  ('O244', 'Diabetes mellitus que surge durante a gravidez', 'O24.4 Diabetes mellitus que surge durante gravidez'),
  ('O249', 'Diabetes mellitus na gravidez, não especificado', 'O24.9 Diabetes mellitus na gravidez NE'),
  ('O25', 'Desnutrição na gravidez', 'O25 Desnutric na gravidez'),
  ('O25', 'Desnutrição na gravidez', 'O25 Desnutric na gravidez'),
  ('O26', 'Assistência materna por outras complicações ligadas predominantemente à gravidez', 'O26 Assist materna outr complic lig predom grav'),
  ('O260', 'Ganho excessivo de peso na gravidez', 'O26.0 Ganho excessivo de peso na gravidez'),
  ('O261', 'Ganho de peso insuficiente na gravidez', 'O26.1 Ganho de peso insuficiente na gravidez'),
  ('O262', 'Assistência à gravidez por motivo de abortamento habitual', 'O26.2 Assist gravidez p/ abortamento habitual'),
  ('O263', 'Retenção de dispositivo intra-uterino contraceptivo (DIU) na gravidez', 'O26.3 Retencao disp intra-uterino contracept grav'),
  ('O264', 'Herpes gestacional', 'O26.4 Herpes gestacional'),
  ('O265', 'Síndrome da hipotensão materna', 'O26.5 Sindr da hipotensao materna'),
  ('O266', 'Transtornos do fígado na gravidez, no parto e no puerpério', 'O26.6 Transt do figado na gravidez parto puerperio'),
  ('O267', 'Subluxação da sínfise (púbica) na gravidez, parto e puerpério', 'O26.7 Subluxacao sinfise gravidez parto puerperio'),
  ('O268', 'Outras afecções especificadas, ligadas a gravidez', 'O26.8 Outr afeccoes espec ligadas a gravidez'),
  ('O269', 'Afecções ligadas a gravidez, não especificadas', 'O26.9 Afeccoes ligadas a gravidez NE'),
  ('O28', 'Achados anormais do rastreamento (screening) antenatal da mãe', 'O28 Achados anorm rastr antenatal mae'),
  ('O280', 'Achados hematológicos anormais do rastreamento (screening) antenatal da mãe', 'O28.0 Achados hematolog anorm rastr antenatal mae'),
  ('O281', 'Achados bioquímicos anormais do rastreamento (screening) antenatal da mãe', 'O28.1 Achados bioquim anorm rastr antenatal mae'),
  ('O282', 'Achados citológicos anormais do rastreamento (screening) antenatal da mãe', 'O28.2 Achados citolog anorm rastr antenatal mae'),
  ('O283', 'Achados ultrassonográficos anormais do rastreamento (screening) antenatal da mãe', 'O28.3 Achados ultrasson anorm rastr antenatal mae'),
  ('O284', 'Achados radiológicos anormais do rastreamento (screening) antenatal da mãe', 'O28.4 Achados radiolog anorm rastr antenatal mae'),
  ('O285', 'Achados cromossômicos e genéticos anormais do rastreamento (screening) antenatal da mãe', 'O28.5 Achados cromos genet anorm rastr antenat mae'),
  ('O288', 'Outros achados anormais do rastreamento (screening) antenatal da mãe', 'O28.8 Outr achados anorm rastr antenatal da mae'),
  ('O289', 'Achados anormais do rastreamento (screening) antenatal da mãe, não especificados', 'O28.9 Achados anorm rastr antenatal da mae NE'),
  ('O29', 'Complicações de anestesia administrada durante a gravidez', 'O29 Complic anestesia admin durante gravidez'),
  ('O290', 'Complicações pulmonares de anestesia administrada durante a gravidez', 'O29.0 Complic pulm anestesia admin durante grav'),
  ('O291', 'Complicações cardíacas de anestesia administrada durante a gravidez', 'O29.1 Complic card anestesia admin durante grav'),
  ('O292', 'Complicações relativas ao sistema nervoso central devidas a anestesia administrada durante a gravidez', 'O29.2 Complic sist nerv centr dev anest admin grav'),
  ('O293', 'Reação tóxica causada por anestesia local administrada durante a gravidez', 'O29.3 Reacao toxica anest local admin durante grav'),
  ('O294', 'Cefaléia causada por anestesia raquidiana ou peridural administradas durante a gravidez', 'O29.4 Cefaleia anest raquid peridur admin dur grav'),
  ('O295', 'Outras complicações de anestesia raquidiana ou peridural administradas durante a gravidez', 'O29.5 Outr compl anest raq peridur admin dur grav'),
  ('O296', 'Falha ou dificuldade na entubação durante a gravidez', 'O29.6 Falha dificuld na entubacao durante gravidez'),
  ('O298', 'Outras complicações de anestesia durante a gravidez', 'O29.8 Outr complic de anestesia durante a gravidez'),
  ('O299', 'Complicações de anestesia durante a gravidez, não especificadas', 'O29.9 Complic de anestesia durante a gravidez NE'),
  ('O30', 'Gestação múltipla', 'O30 Gestacao mult'),
  ('O300', 'Gravidez dupla', 'O30.0 Gravidez dupla'),
  ('O301', 'Gravidez trigemelar', 'O30.1 Gravidez trigemelar'),
  ('O302', 'Gravidez quadrigemelar', 'O30.2 Gravidez quadrigemelar'),
  ('O308', 'Outras gestações múltiplas', 'O30.8 Outr gestacoes mult'),
  ('O309', 'Gestação múltipla, não especificada', 'O30.9 Gestacao mult NE'),
  ('O31', 'Complicações específicas de gestação múltipla', 'O31 Complic especificas de gestacao mult'),
  ('O310', 'Feto papiráceo', 'O31.0 Feto papiraceo'),
  ('O311', 'Continuação da gravidez após aborto de um ou mais fetos', 'O31.1 Continuacao gravidez apos aborto de fetos'),
  ('O312', 'Continuação da gravidez após a morte intra-uterina de um ou mais fetos', 'O31.2 Contin grav apos morte intra-uter de fetos'),
  ('O318', 'Outras complicações específicas de gestação múltipla', 'O31.8 Outr complic especificas de gestacao mult'),
  ('O32', 'Assistência prestada à mãe por motivo de apresentação anormal, conhecida ou suspeitada, do feto', 'O32 Assist prest mae apres anorm conh susp feto'),
  ('O320', 'Assistência prestada à mãe por posição fetal instável', 'O32.0 Assist prest mae p/posicao fetal instavel'),
  ('O321', 'Assistência prestada à mãe por apresentação pélvica', 'O32.1 Assist prestada a mae p/apresentacao pelvica'),
  ('O322', 'Assistência prestada à mãe por posição fetal transversa e oblíqua', 'O32.2 Assist prest mae pos fetal transv e obliqua'),
  ('O323', 'Assistência prestada à mãe por apresentação de face, mento e fronte', 'O32.3 Assist prest mae apres face mento e fronte'),
  ('O324', 'Assistência prestada à mãe por polo cefálico alto em gestação a termo', 'O32.4 Assist prest mae polo cefal alto gest termo'),
  ('O325', 'Assistência prestada à mãe por gestação múltipla com apresentação anormal de um ou mais fetos', 'O32.5 Assist prest mae gest mult apres anorm fetos'),
  ('O326', 'Assistência prestada à mãe por apresentação composta', 'O32.6 Assist prest mae p/apresentacao composta'),
  ('O328', 'Assistência prestada à mãe por outras formas de apresentação anormal do feto', 'O32.8 Assist prest mae outr form apres anorm feto'),
  ('O329', 'Assistência prestada à mãe por apresentação anormal do feto, não especificada', 'O32.9 Assist prest mae apres anormal do feto NE'),
  ('O33', 'Assistência prestada à mãe por uma desproporção conhecida ou suspeita', 'O33 Assist prest mae desprop conhecida suspeita'),
  ('O330', 'Assistência prestada à mãe por uma desproporção devida à deformidade da pelve óssea materna', 'O33.0 Assist prest mae despr deform pelv ossea mat'),
  ('O331', 'Assistência prestada à mãe por uma desproporção devida à contração geral da pelve', 'O33.1 Assist prest mae desprop contrac geral pelve'),
  ('O332', 'Assistência prestada à mãe por uma desproporção devida à contração do estreito superior da pelve', 'O33.2 Assist prest mae despr contr estr sup pelve'),
  ('O333', 'Assistência prestada à mãe por uma desproporção devida à contração do estreito inferior da pelve', 'O33.3 Assist prest mae despr contr estr inf pelve'),
  ('O334', 'Assistência prestada à mãe por uma desproporção de origem mista, materna e fetal', 'O33.4 Assist prest mae desprop orig mista mat fet'),
  ('O335', 'Assistência prestada à mãe por uma desproporção devida a feto excepcionalmente grande', 'O33.5 Assist prest mae desprop feto excepc grande'),
  ('O336', 'Assistência prestada à mãe por uma desproporção devida a feto hidrocefálico', 'O33.6 Assist prest mae desprop feto hidrocefalico'),
  ('O337', 'Assistência prestada à mãe por uma desproporção devida a outras deformidades fetais', 'O33.7 Assist prest mae desprop dev outr deform fet'),
  ('O338', 'Assistência prestada à mãe por uma desproporção de outra origem', 'O33.8 Assist prest mae desproporcao de outr origem'),
  ('O339', 'Assistência prestada à mãe por uma desproporção, não especificada', 'O33.9 Assist prestada a mae p/uma desproporcao NE'),
  ('O34', 'Assistência prestada à mãe por anormalidade, conhecida ou suspeita, dos órgãos pélvicos maternos', 'O34 Assist prest mae anor conh susp org pelv mat'),
  ('O340', 'Assistência à mãe por malformação congênita do útero', 'O34.0 Assist a mae p/malformacao congen do utero'),
  ('O341', 'Assistência prestada à mãe por tumor do corpo do útero', 'O34.1 Assist prestada a mae p/tumor do corpo utero'),
  ('O342', 'Assistência prestada à mãe por cicatriz uterina devida a uma cirurgia anterior', 'O34.2 Assist prest mae cicatriz uterina cirurg ant'),
  ('O343', 'Assistência prestada à mãe por incompetência cervical', 'O34.3 Assist prest mae p/incompetencia cervical'),
  ('O344', 'Assistência prestada à mãe por outras anormalidades do colo do útero', 'O34.4 Assist prest mae outr anorm colo do utero'),
  ('O345', 'Assistência prestada à mãe por outras anormalidades do útero gravídico', 'O34.5 Assist prest mae outr anorm utero gravidico'),
  ('O346', 'Assistência prestada à mãe por anormalidade da vagina', 'O34.6 Assist prest mae p/anormalidade da vagina'),
  ('O347', 'Assistência prestada à mãe por anormalidade da vulva e do períneo', 'O34.7 Assist prest mae p/anorm da vulva e perineo'),
  ('O348', 'Assistência prestada à mãe por outras anormalidades dos órgãos pélvicos', 'O34.8 Assist prest mae p/outr anorm org pelvicos'),
  ('O349', 'Assistência prestada à mãe por anormalidade de órgãos pélvicos, não especificada', 'O34.9 Assist prest mae p/anorm orgaos pelvicos NE'),
  ('O35', 'Assistência prestada à mãe por anormalidade e lesão fetais, conhecidas ou suspeitadas', 'O35 Assist prest mae anorm lesao fet conhec susp'),
  ('O350', 'Assistência prestada à mãe por malformação do sistema nervoso central do feto (suspeitada)', 'O35.0 Assist prest mae malform sist nerv cent feto'),
  ('O351', 'Assistência prestada à mãe por anormalidade cromossômica (suspeitada) do feto', 'O35.1 Assist prest mae anorm cromossomica do feto'),
  ('O352', 'Assistência prestada à mãe por doença hereditária (suspeitada) do feto', 'O35.2 Assist prest mae p/doenc hereditaria do feto'),
  ('O353', 'Assistência prestada à mãe por lesão fetal (suspeitada) causada por doença viral materna', 'O35.3 Assist prest mae lesao fet caus doen vir mat'),
  ('O354', 'Assistência prestada à mãe por lesão (suspeitada) causada ao feto por alcoolismo materno', 'O35.4 Assist prest mae lesao caus feto alcool mat'),
  ('O355', 'Assistência prestada à mãe por lesão fetal (suspeitada) causada por drogas', 'O35.5 Assist prest mae lesao fetal causada drogas'),
  ('O356', 'Assistência prestada à mãe por lesão fetal (suspeitada) causada por radiação', 'O35.6 Assist prest mae lesao fetal causada radiac'),
  ('O357', 'Assistência prestada à mãe por lesão fetal (suspeitada) causada por outros procedimentos médicos', 'O35.7 Assist prest mae lesao fet caus out proc med'),
  ('O358', 'Assistência prestada à mãe por outras anormalidades ou lesões fetais (suspeitadas)', 'O35.8 Assist prest mae outr anorm ou lesoes fetais'),
  ('O359', 'Assistência prestada à mãe por lesão ou anormalidade fetais (suspeitadas), não especificadas', 'O35.9 Assist prest mae lesao ou anorm fetais NE'),
  ('O36', 'Assistência prestada à mãe por outros problemas fetais conhecidos ou suspeitados', 'O36 Assist prest mae outr probl fet conhec susp'),
  ('O360', 'Assistência prestada à mãe por isoimunização Rh', 'O36.0 Assist prestada a mae p/isoimunizacao Rh'),
  ('O361', 'Assistência prestada à mãe por outros tipos de isoimunização', 'O36.1 Assist prest mae p/outr tipos isoimunizacao'),
  ('O362', 'Assistência prestada à mãe por hidropsia fetal', 'O36.2 Assist prestada a mae p/hidropsia fetal'),
  ('O363', 'Assistência prestada à mãe por sinais de hipóxia fetal', 'O36.3 Assist prestada a mae p/sinais hipoxia fetal'),
  ('O364', 'Assistência prestada à mãe por morte intra-uterina', 'O36.4 Assist prestada a mae p/morte intra-uterina'),
  ('O365', 'Assistência prestada à mãe por insuficiência de crescimento fetal', 'O36.5 Assist prestada a mae p/insuf cresc fetal'),
  ('O366', 'Assistência prestada à mãe por crescimento fetal excessivo', 'O36.6 Assist prestada a mae p/cresc fetal excess'),
  ('O367', 'Assistência prestada à mãe por feto viável em gravidez abdominal', 'O36.7 Assist prest mae feto viavel grav abdominal'),
  ('O368', 'Assistência prestada à mãe por outros problemas fetais especificados', 'O36.8 Assist prest mae outr problemas fetais espec'),
  ('O369', 'Assistência prestada à mãe por problema fetal não especificado', 'O36.9 Assist prestada a mae p/problema fetal NE'),
  ('O40', 'Polihidrâmnio', 'O40 Polihidramnio'),
  ('O40', 'Polihidrâmnio', 'O40 Polihidramnio'),
  ('O41', 'Outros transtornos das membranas e do líquido amniótico', 'O41 Outr transt membranas e liquido amniotico'),
  ('O410', 'Oligohidrâmnio', 'O41.0 Oligohidramnio'),
  ('O411', 'Infecção do saco amniótico e das membranas', 'O41.1 Infecc do saco amniotico e das membranas'),
  ('O418', 'Outros transtornos especificados do líquido amniótico e das membranas', 'O41.8 Outr transt espec liq amniotico e membranas'),
  ('O419', 'Transtornos do líquido amniótico e das membranas não especificados', 'O41.9 Transt do liquido amniotico e membranas NE'),
  ('O42', 'Ruptura prematura de membranas', 'O42 Ruptura prematura de membranas'),
  ('O420', 'Ruptura prematura de membranas, com início do trabalho de parto dentro de 24 horas', 'O42.0 Ruptura premat membr c/inic trab parto 24h'),
  ('O421', 'Ruptura prematura de membranas, com início do trabalho de parto depois das primeiras 24 horas', 'O42.1 Ruptura premat membr inic trab parto dep 24h'),
  ('O422', 'Ruptura prematura de membranas, com trabalho de parto retardado por terapêutica', 'O42.2 Ruptura premat membr trab parto retard terap'),
  ('O429', 'Ruptura prematura de membranas, não especificada', 'O42.9 Ruptura prematura de membranas NE'),
  ('O43', 'Transtornos da placenta', 'O43 Transt da placenta'),
  ('O430', 'Síndromes de transfusão placentária', 'O43.0 Sindr de transfusao placentaria'),
  ('O431', 'Malformação da placenta', 'O43.1 Malformacao da placenta'),
  ('O438', 'Outros transtornos da placenta', 'O43.8 Outr transt da placenta'),
  ('O439', 'Transtorno da placenta, não especificado', 'O43.9 Transt da placenta NE'),
  ('O44', 'Placenta prévia', 'O44 Placenta previa'),
  ('O440', 'Placenta prévia especificada como sem hemorragia', 'O44.0 Placenta previa espec como s/hemorragia'),
  ('O441', 'Placenta prévia com hemorragia', 'O44.1 Placenta previa c/hemorragia'),
  ('O45', 'Descolamento prematuro da placenta (abruptio placentae)', 'O45 Descolamento prematuro da placenta'),
  ('O450', 'Descolamento prematuro da placenta com deficiência de coagulação', 'O45.0 Descolamento premat placenta c/defic coagul'),
  ('O458', 'Outro descolamento prematuro da placenta', 'O45.8 Outr descolamento prematuro da placenta'),
  ('O459', 'Descolamento prematuro da placenta, não especificado', 'O45.9 Descolamento prematuro da placenta NE'),
  ('O46', 'Hemorragia anteparto não classificada em outra parte', 'O46 Hemorragia anteparto NCOP'),
  ('O460', 'Hemorragia anteparto com deficiência de coagulação', 'O46.0 Hemorragia anteparto c/defic de coagulacao'),
  ('O468', 'Outra forma de hemorragia anteparto', 'O46.8 Outr form de hemorragia anteparto'),
  ('O469', 'Hemorragia anteparto, não especificada', 'O46.9 Hemorragia anteparto NE'),
  ('O47', 'Falso trabalho de parto', 'O47 Falso trabalho de parto'),
  ('O470', 'Falso trabalho de parto antes de se completarem 37 semanas de gestação', 'O47.0 Falso trab parto antes de 37 sem gestacao'),
  ('O471', 'Falso trabalho de parto na 37ª semana completa ou depois dela', 'O47.1 Falso trab parto 37ª sem completa ou depois'),
  ('O479', 'Falso trabalho de parto, não especificado', 'O47.9 Falso trabalho de parto NE'),
  ('O48', 'Gravidez prolongada', 'O48 Gravidez prolongada'),
  ('O48', 'Gravidez prolongada', 'O48 Gravidez prolongada'),
  ('O60', 'Trabalho de parto pré-termo', 'O60 Trabalho de parto pre-termo'),
  ('O600', 'Trabalho de parto pré-termo sem parto', 'O60.0 Trabalho de parto pré-termo sem parto'),
  ('O601', 'Trabalho de parto pré-termo com parto pré-termo', 'O60.1 Trabalho parto pré-termo c/parto pré-termo'),
  ('O602', 'Trabalho de parto pré-termo com parto a termo', 'O60.2 Trabalho de parto pré-termo c/parto a termo'),
  ('O61', 'Falha na indução do trabalho de parto', 'O61 Falha na inducao do trabalho de parto'),
  ('O610', 'Falha na indução médica do trabalho de parto', 'O61.0 Falha na inducao medica do trabalho de parto'),
  ('O611', 'Falha na indução instrumental do trabalho de parto', 'O61.1 Falha inducao instrumental trabalho de parto'),
  ('O618', 'Outras formas de falha na indução do trabalho de parto', 'O61.8 Outr form falha na inducao trabalho de parto'),
  ('O619', 'Falha na indução do trabalho de parto, não especificada', 'O61.9 Falha na inducao do trabalho de parto NE'),
  ('O62', 'Anormalidades da contração uterina', 'O62 Anormalidades da contracao uterina'),
  ('O620', 'Contrações iniciais inadequadas', 'O62.0 Contracoes iniciais inadequadas'),
  ('O621', 'Inércia uterina secundária', 'O62.1 Inercia uterina secund'),
  ('O622', 'Outras formas de inércia uterina', 'O62.2 Outr form de inercia uterina'),
  ('O623', 'Trabalho de parto precipitado', 'O62.3 Trabalho de parto precipitado'),
  ('O624', 'Contrações uterinas hipertônicas, incoordenadas ou prolongadas', 'O62.4 Contrac uterinas hiperton incoord ou prolong'),
  ('O628', 'Outras anormalidades da contração uterina', 'O62.8 Outr anormalidades da contracao uterina'),
  ('O629', 'Anormalidades da contração uterina, não especificadas', 'O62.9 Anormalidades da contracao uterina NE'),
  ('O63', 'Trabalho de parto prolongado', 'O63 Trabalho de parto prolongado'),
  ('O630', 'Prolongamento do primeiro período (dilatação)', 'O63.0 Prolongamento do primeiro periodo'),
  ('O631', 'Prolongamento do segundo período (expulsão)', 'O63.1 Prolongamento do segundo periodo'),
  ('O632', 'Parto retardado do segundo gêmeo, do terceiro gêmeo etc', 'O63.2 Parto retardado segundo terceiro gemeo etc'),
  ('O639', 'Trabalho de parto prolongado, não especificado', 'O63.9 Trabalho de parto prolongado NE'),
  ('O64', 'Obstrução do trabalho de parto devida à má-posição ou má-apresentação do feto', 'O64 Obstr trab parto dev ma-posic ma-apres feto'),
  ('O640', 'Obstrução do trabalho de parto devida à rotação incompleta do polo cefálico fetal', 'O64.0 Obstr trab part dev rot incomp polo cef fet'),
  ('O641', 'Obstrução do trabalho de parto devida à apresentação pélvica', 'O64.1 Obstr trab parto dev apresentacao pelvica'),
  ('O642', 'Obstrução do trabalho de parto devida à apresentação de face', 'O64.2 Obstr trab parto dev apresentacao de face'),
  ('O643', 'Obstrução do trabalho de parto devida à apresentação de fronte', 'O64.3 Obstr trab parto dev apresentacao de fronte'),
  ('O644', 'Obstrução do trabalho de parto devida à apresentação de ombro', 'O64.4 Obstr trab parto dev apresentacao de ombro'),
  ('O645', 'Obstrução do trabalho de parto devida à apresentação complexa', 'O64.5 Obstr trab parto dev apresentacao complexa'),
  ('O648', 'Obstrução do trabalho de parto devida a outras formas de má-apresentação e má-posição', 'O64.8 Obstr trab part dev out form ma-apres ma-pos'),
  ('O649', 'Obstrução do trabalho de parto devida a má-posição ou má-apresentação, não especificadas', 'O64.9 Obstr trab parto dev ma-posic ou ma-apres NE'),
  ('O65', 'Obstrução do trabalho de parto devida a anormalidade pélvica da mãe', 'O65 Obstr trab parto dev anorm pelvica da mae'),
  ('O650', 'Obstrução do trabalho de parto devida a deformidade pélvica', 'O65.0 Obstr trabalho de parto dev deform pelvica'),
  ('O651', 'Obstrução do trabalho de parto devida à contração geral da pelve', 'O65.1 Obstr trab parto dev contracao geral pelve'),
  ('O652', 'Obstrução do trabalho de parto devida à contração do estreito superior', 'O65.2 Obstr trab parto dev contracao estreito sup'),
  ('O653', 'Obstrução do trabalho de parto devida à contração do estreito inferior ou da cavidade mediana', 'O65.3 Obstr trab parto dev contr estr inf cav med'),
  ('O654', 'Obstrução do trabalho de parto devida a desproporção feto-pélvica, não especificada', 'O65.4 Obstr trab parto dev desprop feto-pelvica NE'),
  ('O655', 'Obstrução do trabalho de parto devida a anormalidade dos órgãos pélvicos maternos', 'O65.5 Obstr trab parto dev anorm org pelvicos mat'),
  ('O658', 'Obstrução do trabalho de parto devida a outras anormalidades pélvicas maternas', 'O65.8 Obstr trab parto dev outr anorm pelvicas mat'),
  ('O659', 'Obstrução do trabalho de parto devida a anormalidades pélvicas maternas não especificadas', 'O65.9 Obstr trab parto dev anorm pelvicas mat NE'),
  ('O66', 'Outras formas de obstrução do trabalho de parto', 'O66 Outr form de obstrucao do trabalho de parto'),
  ('O660', 'Obstrução do trabalho de parto devido a distócia de ombro', 'O66.0 Obstr trab parto dev distocia de ombro'),
  ('O661', 'Obstrução do trabalho de parto por colisão de gêmeos', 'O66.1 Obstr trabalho de parto p/colis de gemeos'),
  ('O662', 'Obstrução do trabalho de parto por feto excepcionalmente grande', 'O66.2 Obstr trab parto p/feto excepc grande'),
  ('O663', 'Obstrução do trabalho de parto devido a outras anormalidades do feto', 'O66.3 Obstr trab parto dev outr anorm do feto'),
  ('O664', 'Falha de tentativa de trabalho de parto, não especificada', 'O66.4 Falha de tentativa de trabalho de parto NE'),
  ('O665', 'Falha de aplicação de fórceps e vácuo-extrator, não especificada', 'O66.5 Falha aplicacao forceps e vacuo-extrator NE'),
  ('O668', 'Outras formas de obstrução do trabalho de parto, especificadas', 'O66.8 Outr form de obstrucao do trab parto espec'),
  ('O669', 'Obstrução do trabalho de parto, não especificado', 'O66.9 Obstrucao do trabalho de parto NE'),
  ('O67', 'Trabalho de parto e parto complicados por hemorragia intraparto não classificados em outra parte', 'O67 Trab parto parto compl hemorr intrapart NCOP'),
  ('O670', 'Hemorragia intraparto com deficiência de coagulação', 'O67.0 Hemorragia intraparto c/defic de coagulacao'),
  ('O678', 'Outras hemorragias intraparto', 'O67.8 Outr hemorragias intraparto'),
  ('O679', 'Hemorragia intraparto não especificada', 'O67.9 Hemorragia intraparto NE'),
  ('O68', 'Trabalho de parto e parto complicados por sofrimento fetal', 'O68 Trab parto e parto complic sofrimento fetal'),
  ('O680', 'Trabalho de parto e parto complicados por anormalidade da freqüência cardíaca fetal', 'O68.0 Trab parto e parto compl anorm freq card fet'),
  ('O681', 'Trabalho de parto e parto complicados por mecônio no líquido amniótico', 'O68.1 Trab parto e parto compl meconio liq amniot'),
  ('O682', 'Trabalho de parto e parto complicados por anormalidade na freqüência cardíaca fetal com mecônio no líquido amniótico', 'O68.2 Trab part part anor frq card fet mec liq amn'),
  ('O683', 'Trabalho de parto e parto complicados por evidências bioquímicas de sofrimento fetal', 'O68.3 Trab parto e parto compl evid bioq sofr fet'),
  ('O688', 'Trabalho de parto e parto complicados por outras evidências de sofrimento fetal', 'O68.8 Trab parto e parto compl outr evid sofr fet'),
  ('O689', 'Trabalho de parto e parto complicados por sofrimento fetal, não especificado', 'O68.9 Trab parto e parto complic sofr fetal NE'),
  ('O69', 'Trabalho de parto e parto complicados por anormalidade do cordão umbilical', 'O69 Trab parto parto compl anorm cordao umbilic'),
  ('O690', 'Trabalho de parto e parto complicados por prolapso do cordão', 'O69.0 Trab parto e parto complic prolapso cordao'),
  ('O691', 'Trabalho de parto e parto complicados por circular de cordão, com compressão', 'O69.1 Trab part part compl circul cordao c/compres'),
  ('O692', 'Trabalho de parto e parto complicados por outros enovelamentos do cordão', 'O69.2 Trab parto e parto compl outr enovel cordao'),
  ('O693', 'Trabalho de parto e parto complicados por cordão curto', 'O69.3 Trab parto e parto complic p/cordao curto'),
  ('O694', 'Trabalho de parto e parto complicados por vasa praevia', 'O69.4 Trab parto e parto complic p/vasa praevia'),
  ('O695', 'Trabalho de parto e parto complicados por lesão vascular do cordão', 'O69.5 Trab parto e parto complic lesao vasc cordao'),
  ('O698', 'Trabalho de parto e parto complicados por outras complicações do cordão', 'O69.8 Trab parto e parto complic outr compl cordao'),
  ('O699', 'Trabalho de parto e parto complicados por complicações do cordão, não especificadas', 'O69.9 Trab parto e parto complic cordao NE'),
  ('O70', 'Laceração do períneo durante o parto', 'O70 Laceracao do perineo durante o parto'),
  ('O700', 'Laceração de períneo de primeiro grau durante o parto', 'O70.0 Laceracao perineo 1. grau durante o parto'),
  ('O701', 'Laceração de períneo de segundo grau durante o parto', 'O70.1 Laceracao perineo 2. grau durante o parto'),
  ('O702', 'Laceração de períneo de terceiro grau durante o parto', 'O70.2 Laceracao perineo 3. grau durante o parto'),
  ('O703', 'Laceração de períneo de quarto grau durante o parto', 'O70.3 Laceracao perineo 4. grau durante o parto'),
  ('O709', 'Laceração de períneo durante o parto, não especificada', 'O70.9 Laceracao de perineo durante o parto NE'),
  ('O71', 'Outros traumatismos obstétricos', 'O71 Outr traum obstetricos'),
  ('O710', 'Ruptura do útero antes do início do trabalho de parto', 'O71.0 Ruptura do utero antes inicio trab parto'),
  ('O711', 'Ruptura do útero durante o trabalho de parto', 'O71.1 Ruptura do utero durante o trabalho de parto'),
  ('O712', 'Inversão do útero pós-parto', 'O71.2 Inversao do utero pos-parto'),
  ('O713', 'Laceração obstétrica do colo do útero', 'O71.3 Laceracao obstetrica do colo do utero'),
  ('O714', 'Laceração vaginal alta isolada, de origem obstétrica', 'O71.4 Laceracao vaginal alta isolada orig obstetr'),
  ('O715', 'Outras lesões obstétricas aos órgãos pélvicos', 'O71.5 Outr lesoes obstetricas aos orgaos pelvicos'),
  ('O716', 'Lesão obstétrica das articulações e dos ligamentos pélvicos', 'O71.6 Lesao obstetr artic e ligamentos pelvicos'),
  ('O717', 'Hematoma obstétrico da pelve', 'O71.7 Hematoma obstetrico da pelve'),
  ('O718', 'Outros traumatismos obstétricos especificados', 'O71.8 Outr traum obstetricos espec'),
  ('O719', 'Traumatismo obstétrico, não especificado', 'O71.9 Traum obstetrico NE'),
  ('O72', 'Hemorragia pós-parto', 'O72 Hemorragia pos-parto'),
  ('O720', 'Hemorragia do terceiro estágio', 'O72.0 Hemorragia do terceiro estagio'),
  ('O721', 'Outras hemorragias do pós-parto imediato', 'O72.1 Outr hemorragias do pos-parto imediato'),
  ('O722', 'Hemorragias pós-parto, tardias e secundárias', 'O72.2 Hemorragias pos-parto tard e secund'),
  ('O723', 'Deficiências de coagulação pós-parto', 'O72.3 Defic de coagulacao pos-parto'),
  ('O73', 'Retenção da placenta e das membranas, sem hemorragias', 'O73 Retencao placenta e membranas s/hemorragias'),
  ('O730', 'Retenção da placenta sem hemorragia', 'O73.0 Retencao da placenta s/hemorragia'),
  ('O731', 'Retenção de partes da placenta ou das membranas, sem hemorragia', 'O73.1 Retencao partes placenta ou membr s/hemorrag'),
  ('O74', 'Complicações de anestesia durante o trabalho de parto e o parto', 'O74 Complic anestesia durante trab parto e parto'),
  ('O740', 'Pneumonite aspirativa devida a anestesia durante o trabalho de parto e o parto', 'O74.0 Pneumonite aspirat dev anest trab parto part'),
  ('O741', 'Outras complicações pulmonares devidas a anestesia durante o trabalho de parto e no parto', 'O74.1 Outr complic pulm dev anest trab parto parto'),
  ('O742', 'Complicações cardíacas devidas a anestesia durante o trabalho de parto e no parto', 'O74.2 Complic card dev anest trab parto e parto'),
  ('O743', 'Complicações do sistema nervoso central devidas a anestesia durante o trabalho de parto e no parto', 'O74.3 Comp sist nerv cent dev anest trab part part'),
  ('O744', 'Reação tóxica a anestesia local durante trabalho de parto e o parto', 'O74.4 Reacao toxica anest local trab parto e parto'),
  ('O745', 'Cefaléia pós-anestesia raquidiana e peridural, durante o trabalho de parto e parto', 'O74.5 Cefal pos-anest raquid perid trab parto part'),
  ('O746', 'Outras complicações de anestesia raquidiana ou peridural, durante o trabalho de parto e parto', 'O74.6 Outr compl anest raquid perid trab part part'),
  ('O747', 'Falha ou dificuldade de entubação durante o trabalho de parto e parto', 'O74.7 Falha ou dific entubacao trab parto e parto'),
  ('O748', 'Outras complicações de anestesia durante o trabalho de parto e parto', 'O74.8 Outr complic anest durante trab parto parto'),
  ('O749', 'Complicações de anestesia durante o trabalho de parto e parto, não especificadas', 'O74.9 Complic anest durante trab parto e parto NE'),
  ('O75', 'Outras complicações do trabalho de parto e do parto não classificadas em outra parte', 'O75 Outr complic do trab parto e do parto NCOP'),
  ('O750', 'Sofrimento materno durante o trabalho de parto e o parto', 'O75.0 Sofrim materno durante trab parto e parto'),
  ('O751', 'Choque durante ou subseqüente ao trabalho de parto e o parto', 'O75.1 Choque durante ou subseq trab parto e parto'),
  ('O752', 'Febre durante o trabalho de parto não classificada em outra parte', 'O75.2 Febre durante o trabalho de parto NCOP'),
  ('O753', 'Outras infecções durante o trabalho de parto', 'O75.3 Outr infecc durante o trabalho de parto'),
  ('O754', 'Outras complicações de procedimentos ou de cirurgia obstétrica', 'O75.4 Outr complic proced ou cirurgia obstetrica'),
  ('O755', 'Demora do parto após ruptura artificial das membranas', 'O75.5 Demora do parto apos ruptura artif membranas'),
  ('O756', 'Demora do parto após ruptura espontânea ou não especificada das membranas', 'O75.6 Demora parto apos ruptura espont ou NE membr'),
  ('O757', 'Parto vaginal subseqüente a cesariana anterior', 'O75.7 Parto vaginal subseq cesariana anterior'),
  ('O758', 'Outras complicações especificadas do trabalho de parto e do parto', 'O75.8 Outr complic espec trab parto e do parto'),
  ('O759', 'Complicações do trabalho de parto e do parto, não especificadas', 'O75.9 Complic do trabalho de parto e do parto NE'),
  ('O80', 'Parto único espontâneo', 'O80 Parto unico espontaneo'),
  ('O800', 'Parto espontâneo cefálico', 'O80.0 Parto espontaneo cefalico'),
  ('O801', 'Parto espontâneo pélvico', 'O80.1 Parto espontaneo pelvico'),
  ('O808', 'Outros tipos de parto único espontâneo', 'O80.8 Outr tipos de parto unico espontaneo'),
  ('O809', 'Parto único espontâneo, não especificado', 'O80.9 Parto unico espontaneo NE'),
  ('O81', 'Parto único por fórceps ou vácuo-extrator', 'O81 Parto unico p/forceps ou vacuo-extrator'),
  ('O810', 'Parto por fórceps baixo', 'O81.0 Parto p/forceps baixo'),
  ('O811', 'Parto por fórceps da cavidade mediana', 'O81.1 Parto p/forceps da cavidade mediana'),
  ('O812', 'Fórceps da cavidade mediana com rotação', 'O81.2 Forceps da cavidade mediana c/rotacao'),
  ('O813', 'Outros tipos de parto por fórceps e os não especificados', 'O81.3 Outr tipos de parto p/forceps e os NE'),
  ('O814', 'Parto por vácuo-extrator', 'O81.4 Parto p/vacuo-extrator'),
  ('O815', 'Parto por combinação de fórceps e vácuo-extrator', 'O81.5 Parto p/combinacao forceps e vacuo-extrator'),
  ('O82', 'Parto único por cesariana', 'O82 Parto unico p/cesariana'),
  ('O820', 'Parto por cesariana eletiva', 'O82.0 Parto p/cesariana eletiva'),
  ('O821', 'Parto por cesariana de emergência', 'O82.1 Parto p/cesariana de emergencia'),
  ('O822', 'Parto por cesariana para histerectomia', 'O82.2 Parto p/cesariana p/histerectomia'),
  ('O828', 'Outros tipos de parto único por cesariana', 'O82.8 Outr tipos de parto unico p/cesariana'),
  ('O829', 'Parto por cesariana, não especificada', 'O82.9 Parto p/cesariana NE'),
  ('O83', 'Outros tipos de parto único assistido', 'O83 Outr tipos de parto unico assistido'),
  ('O830', 'Extração pélvica', 'O83.0 Extracao pelvica'),
  ('O831', 'Outros tipos de parto pélvico assistido', 'O83.1 Outr tipos de parto pelvico assistido'),
  ('O832', 'Outras formas de parto com o auxílio de manipulação', 'O83.2 Outr form de parto c/o auxilio manipulacao'),
  ('O833', 'Parto de gravidez intra-abdominal com feto viável', 'O83.3 Parto de grav intra-abdominal feto viavel'),
  ('O834', 'Cirurgia destrutiva para facilitar o parto', 'O83.4 Cirurgia destrutiva p/facilitar o parto'),
  ('O838', 'Outros tipos especificados de parto único assistido', 'O83.8 Outr tipos espec de parto unico assistido'),
  ('O839', 'Parto único assistido, não especificado', 'O83.9 Parto unico assistido NE'),
  ('O84', 'Parto múltiplo', 'O84 Parto mult'),
  ('O840', 'Parto múltiplo, todos espontâneos', 'O84.0 Parto mult todos espontaneos'),
  ('O841', 'Parto múltiplo, todos por fórceps ou vácuo-extrator', 'O84.1 Parto mult todos p/forceps ou vacuo-extrator'),
  ('O842', 'Parto múltiplo, todos por cesariana', 'O84.2 Parto mult todos p/cesariana'),
  ('O848', 'Outro tipo de parto múltiplo', 'O84.8 Outr tipo de parto mult'),
  ('O849', 'Parto múltiplo, não especificado', 'O84.9 Parto mult NE'),
  ('O85', 'Infecção puerperal', 'O85 Infecc puerperal'),
  ('O85', 'Infecção puerperal', 'O85 Infecc puerperal'),
  ('O86', 'Outras infecções puerperais', 'O86 Outr infecc puerperais'),
  ('O860', 'Infecção da incisão cirúrgica de origem obstétrica', 'O86.0 Infecc da incisao cirurgica orig obstetrica'),
  ('O861', 'Outras infecções dos órgãos genitais subseqüentes ao parto', 'O86.1 Outr infecc dos orgaos genitais subseq parto'),
  ('O862', 'Infecção das vias urinárias subseqüentes ao parto', 'O86.2 Infecc das vias urinarias subsequentes parto'),
  ('O863', 'Outras infecções das vias genitourinárias subseqüentes ao parto', 'O86.3 Outr infecc vias genitourin subseq parto'),
  ('O864', 'Febre de origem desconhecida subseqüente ao parto', 'O86.4 Febre orig desconhecida subsequente ao parto'),
  ('O868', 'Outras infecções puerperais especificadas', 'O86.8 Outr infecc puerperais espec'),
  ('O87', 'Complicações venosas no puerpério', 'O87 Complic venosas no puerperio'),
  ('O870', 'Tromboflebite superficial no puerpério', 'O87.0 Tromboflebite superf no puerperio'),
  ('O871', 'Tromboflebite profunda no puerpério', 'O87.1 Tromboflebite profunda no puerperio'),
  ('O872', 'Hemorróidas no puerpério', 'O87.2 Hemorroidas no puerperio'),
  ('O873', 'Trombose venosa cerebral no puerpério', 'O87.3 Trombose venosa cerebral no puerperio'),
  ('O878', 'Outras complicações venosas no puerpério', 'O87.8 Outr complic venosas no puerperio'),
  ('O879', 'Complicações venosas no puerpério, não especificadas', 'O87.9 Complic venosas no puerperio NE'),
  ('O88', 'Embolia de origem obstétrica', 'O88 Embolia orig obstetrica'),
  ('O880', 'Embolia gasosa de origem obstétrica', 'O88.0 Embolia gasosa orig obstetrica'),
  ('O881', 'Embolia amniótica', 'O88.1 Embolia amniotica'),
  ('O882', 'Embolia obstétrica por coágulo de sangue', 'O88.2 Embolia obstetrica p/coagulo de sangue'),
  ('O883', 'Embolia séptica ou piêmica de origem obstétrica', 'O88.3 Embolia septica ou piemica orig obstetrica'),
  ('O888', 'Outras embolias de origem obstétrica', 'O88.8 Outr embolias orig obstetrica'),
  ('O89', 'Complicações da anestesia administrada durante o puerpério', 'O89 Complic da anestesia admin durante puerperio'),
  ('O890', 'Complicações pulmonares da anestesia durante o puerpério', 'O89.0 Complic pulm anestesia durante puerperio'),
  ('O891', 'Complicações cardíacas devidas a anestesia durante o puerpério', 'O89.1 Complic card dev anestesia durante puerperio'),
  ('O892', 'Complicações relativas ao sistema nervoso central devidas a anestesia durante o puerpério', 'O89.2 Compl rel sist nerv cent dev anest puerperio'),
  ('O893', 'Reação tóxica a uma anestesia local durante o puerpério', 'O89.3 Reacao toxica anest local durante puerperio'),
  ('O894', 'Cefaléia provocada por uma anestesia raquidiana ou peridural, durante o puerpério', 'O89.4 Cefaleia prov anest raquid perid puerperio'),
  ('O895', 'Outras complicações de anestesia raquidiana ou peridural, durante o puerpério', 'O89.5 Outr compl anest raquid perid puerperio'),
  ('O896', 'Falha na ou dificuldade de entubação, durante o puerpério', 'O89.6 Falha dific de entubacao durante puerperio'),
  ('O898', 'Outras complicações da anestesia durante o puerpério', 'O89.8 Outr complic anestesia durante o puerperio'),
  ('O899', 'Complicação devida a anestesia, durante o puerpério, não especificada', 'O89.9 Complic dev anestesia durante o puerperio NE'),
  ('O90', 'Complicações do puerpério não classificadas em outra parte', 'O90 Complic do puerperio NCOP'),
  ('O900', 'Ruptura da incisão de cesariana', 'O90.0 Ruptura da incisao de cesariana'),
  ('O901', 'Ruptura da incisão obstétrica, no períneo', 'O90.1 Ruptura da incisao obstetrica no perineo'),
  ('O902', 'Hematoma da incisão obstétrica', 'O90.2 Hematoma da incisao obstetrica'),
  ('O903', 'Cardiomiopatia no puerpério', 'O90.3 Cardiomiopatia no puerperio'),
  ('O904', 'Insuficiência renal aguda do pós-parto', 'O90.4 Insuf renal aguda do pos-parto'),
  ('O905', 'Tireoidite do pós-parto', 'O90.5 Tireoidite do pos-parto'),
  ('O908', 'Outras complicações do puerpério, não classificadas em outra parte', 'O90.8 Outr complic do puerperio NCOP'),
  ('O909', 'Complicação do puerpério não especificada', 'O90.9 Complic do puerperio NE'),
  ('O91', 'Infecções mamárias associadas ao parto', 'O91 Infecc mamarias assoc ao parto'),
  ('O910', 'Infecção do mamilo associada ao parto', 'O91.0 Infecc do mamilo assoc ao parto'),
  ('O911', 'Abscesso da mama associada ao parto', 'O91.1 Abscesso da mama assoc ao parto'),
  ('O912', 'Mastite não purulenta associada ao parto', 'O91.2 Mastite nao purulenta assoc ao parto'),
  ('O92', 'Outras afecções da mama e da lactação associadas ao parto', 'O92 Outr afeccoes mama e lactacao assoc ao parto'),
  ('O920', 'Mamilo retraído associado ao parto', 'O92.0 Mamilo retraido assoc ao parto'),
  ('O921', 'Fissuras do mamilo associadas ao parto', 'O92.1 Fissuras do mamilo assoc ao parto'),
  ('O922', 'Outras afecções da mama, e as não especificadas, associadas ao parto', 'O92.2 Outr afeccoes da mama e as NE assoc ao parto'),
  ('O923', 'Agalactia', 'O92.3 Agalactia'),
  ('O924', 'Hipogalactia', 'O92.4 Hipogalactia'),
  ('O925', 'Suspensão da lactação', 'O92.5 Suspensao da lactacao'),
  ('O926', 'Galactorréia', 'O92.6 Galactorreia'),
  ('O927', 'Outros distúrbios da lactação e os não especificados', 'O92.7 Outr disturbios da lactacao e os NE'),
  ('O94', 'Seqüelas de complicações da gravidez, parto e puerpério', 'O94 Seqüelas complic gravidez parto e puerpério'),
  ('O94', 'Seqüelas de complicações da gravidez, parto e puerpério', 'O94 Seqüelas complic gravidez parto e puerpério'),
  ('O95', 'Morte obstétrica de causa não especificada', 'O95 Morte obstetrica de causa NE'),
  ('O95', 'Morte obstétrica de causa não especificada', 'O95 Morte obstetrica de causa NE'),
  ('O96', 'Morte, por qualquer causa obstétrica, que ocorre mais de 42 dias, mas menos de 1 ano, após o parto', 'O96 Morte qq caus obst mais 42d menos 1a parto'),
  ('O96', 'Morte, por qualquer causa obstétrica, que ocorre mais de 42 dias, mas menos de 1 ano, após o parto', 'O96 Morte qq caus obst mais 42d menos 1a parto'),
  ('O97', 'Morte por seqüelas de causas obstétricas diretas', 'O97 Morte p/sequelas causas obstetricas diretas'),
  ('O97', 'Morte por seqüelas de causas obstétricas diretas', 'O97 Morte p/sequelas causas obstetricas diretas'),
  ('O98', 'Doenças infecciosas e parasitárias maternas classificáveis em outra parte mas que compliquem a gravidez, o parto e o puerpério', 'O98 Doen inf paras mat COP compl grav part puerp'),
  ('O980', 'Tuberculose complicando a gravidez, o parto e o puerpério', 'O98.0 Tuberc complic gravidez parto e puerperio'),
  ('O981', 'Sífilis complicando a gravidez, o parto e o puerpério', 'O98.1 Sifilis complic gravidez parto e puerperio'),
  ('O982', 'Gonorréia complicando a gravidez, o parto e o puerpério', 'O98.2 Gonorreia complic gravidez parto e puerperio'),
  ('O983', 'Outras infecções em que a via de transmissão é predominantemente sexual, complicando a gravidez, o parto e o puerpério', 'O98.3 Out inf via trans sex compl grav parto puerp'),
  ('O984', 'Hepatite viral complicando a gravidez, o parto e o puerpério', 'O98.4 Hepatite viral complic gravidez parto puerp'),
  ('O985', 'Outras doenças virais complicando a gravidez, o parto e o puerpério', 'O98.5 Outr doenc virais compl gravidez parto puerp'),
  ('O986', 'Doenças causadas por protozoários complicando a gravidez, o parto e o puerpério', 'O98.6 Doenc caus protozoar compl grav parto puerp'),
  ('O988', 'Outras doenças infecciosas e parasitárias maternas complicando a gravidez, o parto e o puerpério', 'O98.8 Out doen inf paras mat comp grav parto puerp'),
  ('O989', 'Doenças infecciosas e parasitárias maternas, não especificadas, complicando a gravidez, o parto e o puerpério', 'O98.9 Doen inf paras mat NE compl grav parto puerp'),
  ('O99', 'Outras doenças da mãe, classificadas em outra parte, mas que complicam a gravidez o parto e o puerpério', 'O99 Outr doenc mat COP compl grav parto puerp'),
  ('O990', 'Anemia complicando a gravidez, o parto e o puerpério', 'O99.0 Anemia complic gravidez parto puerperio'),
  ('O991', 'Outras doenças do sangue e dos órgãos hematopoéticos e alguns transtornos que comprometem o sistema imunológico, complicando a gravidez, o parto e o puerpério', 'O99.1 Out doen sang hemat imun comp grav part puer'),
  ('O992', 'Doenças endócrinas, nutricionais e metabólicas complicando a gravidez, o parto e o puerpério', 'O99.2 Doen endoc nutr metab compl grav parto puerp'),
  ('O993', 'Transtornos mentais e doenças do sistema nervoso complicando a gravidez, o parto e o puerpério', 'O99.3 Trans ment doen sis nerv comp grav part puer'),
  ('O994', 'Doenças do aparelho circulatório complicando a gravidez, o parto e o puerpério', 'O99.4 Doenc ap circulat compl gravidez parto puerp'),
  ('O995', 'Doenças do aparelho respiratório complicando a gravidez, o parto e o puerpério', 'O99.5 Doenc ap respirat compl gravidez parto puerp'),
  ('O996', 'Doenças do aparelho digestivo complicando a gravidez, o parto e o puerpério', 'O99.6 Doenc ap digestiv compl gravidez parto puerp'),
  ('O997', 'Doenças da pele e do tecido subcutâneo complicando a gravidez, o parto e o puerpério', 'O99.7 Doenc pele tec subcut compl grav parto puerp'),
  ('O998', 'Outras doenças e afecções especificadas complicando a gravidez, o parto e o puerpério', 'O99.8 Outr doenc afec espec compl grav parto puerp');
