INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('K00', 'Distúrbios do desenvolvimento e da erupção dos dentes', 'K00 Disturbios desenvolv e da erupcao dos dentes'),
  ('K000', 'Anodontia', 'K00.0 Anodontia'),
  ('K001', 'Dentes supranumerários', 'K00.1 Dentes supranumerarios'),
  ('K002', 'Anomalias do tamanho e da forma dos dentes', 'K00.2 Anomalias do tamanho e da form dos dentes'),
  ('K003', 'Dentes manchados', 'K00.3 Dentes manchados'),
  ('K004', 'Distúrbios na formação dos dentes', 'K00.4 Disturbios na formacao dos dentes'),
  ('K005', 'Anomalias hereditárias da estrutura dentária não classificadas em outra parte', 'K00.5 Anomalias hereditarias estrut dentaria NCOP'),
  ('K006', 'Distúrbios da erupção dentária', 'K00.6 Disturbios da erupcao dentaria'),
  ('K007', 'Síndrome da erupção dentária', 'K00.7 Sindr da erupcao dentaria'),
  ('K008', 'Outros distúrbios do desenvolvimento dos dentes', 'K00.8 Outr disturbios do desenvolv dos dentes'),
  ('K009', 'Distúrbio não especificado do desenvolvimento dentário', 'K00.9 Disturbio NE do desenvolv dentario'),
  ('K01', 'Dentes inclusos e impactados', 'K01 Dentes inclusos e impactados'),
  ('K010', 'Dentes inclusos', 'K01.0 Dentes inclusos'),
  ('K011', 'Dentes impactados', 'K01.1 Dentes impactados'),
  ('K02', 'Cárie dentária', 'K02 Carie dentaria'),
  ('K020', 'Cáries limitadas ao esmalte', 'K02.0 Caries limitadas ao esmalte'),
  ('K021', 'Cáries da dentina', 'K02.1 Caries da dentina'),
  ('K022', 'Cárie do cemento', 'K02.2 Carie do cemento'),
  ('K023', 'Cáries dentárias estáveis', 'K02.3 Caries dentarias estaveis'),
  ('K024', 'Odontoclasia', 'K02.4 Odontoclasia'),
  ('K028', 'Outras cáries dentárias', 'K02.8 Outr caries dentarias'),
  ('K029', 'Cárie dentária, sem outra especificação', 'K02.9 Carie dentaria SOE'),
  ('K03', 'Outras doenças dos tecidos dentários duros', 'K03 Outr doenc dos tec dentarios duros'),
  ('K030', 'Atrito dentário excessivo', 'K03.0 Atrito dentario excessivo'),
  ('K031', 'Abrasão dentária', 'K03.1 Abrasao dentaria'),
  ('K032', 'Erosão dentária', 'K03.2 Erosao dentaria'),
  ('K033', 'Reabsorção patológica dos dentes', 'K03.3 Reabsorcao patologica dos dentes'),
  ('K034', 'Hipercementose', 'K03.4 Hipercementose'),
  ('K035', 'Ancilose dentária', 'K03.5 Ancilose dentaria'),
  ('K036', 'Depósitos nos dentes', 'K03.6 Depositos nos dentes'),
  ('K037', 'Alterações pós-eruptivas da cor dos tecidos duros dos dentes', 'K03.7 Alterac pos-eruptivas cor tec duros dentes'),
  ('K038', 'Outras doenças especificadas dos tecidos duros dos dentes', 'K03.8 Outr doenc espec dos tec duros dos dentes'),
  ('K039', 'Doença dos tecidos duros dos dentes, não especificada', 'K03.9 Doenc dos tec duros dos dentes NE'),
  ('K04', 'Doenças da polpa e dos tecidos periapicais', 'K04 Doenc da polpa e dos tec periapicais'),
  ('K040', 'Pulpite', 'K04.0 Pulpite'),
  ('K041', 'Necrose da polpa', 'K04.1 Necrose da polpa'),
  ('K042', 'Degeneração da polpa', 'K04.2 Degeneracao da polpa'),
  ('K043', 'Formação anormal de tecidos duros na polpa', 'K04.3 Formacao anormal de tec duros na polpa'),
  ('K044', 'Periodontite apical aguda de origem pulpar', 'K04.4 Periodontite apical aguda orig pulpar'),
  ('K045', 'Periodontite apical crônica', 'K04.5 Periodontite apical cronica'),
  ('K046', 'Abscesso periapical com fístula', 'K04.6 Abscesso periapical c/fistula'),
  ('K047', 'Abscesso periapical sem fístula', 'K04.7 Abscesso periapical s/fistula'),
  ('K048', 'Cisto radicular', 'K04.8 Cisto radicular'),
  ('K049', 'Outras doenças da polpa e dos tecidos periapicais e as não especificadas', 'K04.9 Outr doenc da polpa e tec periapicais e NE'),
  ('K05', 'Gengivite e doenças periodontais', 'K05 Gengivite e doenc periodontais'),
  ('K050', 'Gengivite aguda', 'K05.0 Gengivite aguda'),
  ('K051', 'Gengivite crônica', 'K05.1 Gengivite cronica'),
  ('K052', 'Periodontite aguda', 'K05.2 Periodontite aguda'),
  ('K053', 'Periodontite crônica', 'K05.3 Periodontite cronica'),
  ('K054', 'Periodontose', 'K05.4 Periodontose'),
  ('K055', 'Outras doenças periodontais', 'K05.5 Outr doenc periodontais'),
  ('K056', 'Doença periodontal, sem outra especificação', 'K05.6 Doenc periodontal SOE'),
  ('K06', 'Outros transtornos da gengiva e do rebordo alveolar sem dentes', 'K06 Outr transt gengiva rebordo alveolar s/dent'),
  ('K060', 'Retração gengival', 'K06.0 Retracao gengival'),
  ('K061', 'Hiperplasia gengival', 'K06.1 Hiperplasia gengival'),
  ('K062', 'Lesões da gengiva e do rebordo alveolar sem dentes, associadas a traumatismos', 'K06.2 Lesoes geng rebord alveol s/dent assoc traum'),
  ('K068', 'Outros transtornos especificados da gengiva e do rebordo alveolar sem dentes', 'K06.8 Outr transt espec geng rebord alveol s/dent'),
  ('K069', 'Transtorno da gengiva e do rebordo alveolar sem dentes sem outra especificação', 'K06.9 Transt gengiva rebordo alveolar s/dentes SOE'),
  ('K07', 'Anomalias dentofaciais (inclusive a maloclusão)', 'K07 Anomalias dentofaciais'),
  ('K070', 'Anomalias importantes (major) do tamanho da mandíbula', 'K07.0 Anomalias importantes tamanho da mandibula'),
  ('K071', 'Anomalias da relação entre a mandíbula com a base do crânio', 'K07.1 Anomalias relacao entre mandibula base cran'),
  ('K072', 'Anomalias da relação entre as arcadas dentárias', 'K07.2 Anomalias relacao entre as arcadas dentarias'),
  ('K073', 'Anomalias da posição dos dentes', 'K07.3 Anomalias da posicao dos dentes'),
  ('K074', 'Maloclusão, não especificada', 'K07.4 Maloclusao NE'),
  ('K075', 'Anormalidades dentofaciais funcionais', 'K07.5 Anormalidades dentofaciais funcionais'),
  ('K076', 'Transtornos da articulação temporomandibular', 'K07.6 Transt da articulacao temporomandibular'),
  ('K078', 'Outras anomalias dentofaciais', 'K07.8 Outr anomalias dentofaciais'),
  ('K079', 'Anomalia dentofacial, sem outra especificação', 'K07.9 Anomalia dentofacial SOE'),
  ('K08', 'Outros transtornos dos dentes e de suas estruturas de sustentação', 'K08 Outr transt dentes e estrut de sustentacao'),
  ('K080', 'Exfoliação dos dentes devida a causas sistêmicas', 'K08.0 Exfoliacao dos dentes dev causas sistemicas'),
  ('K081', 'Perda de dentes devida a acidente, extração ou a doenças periodontais localizadas', 'K08.1 Perda dent dev acid extr doenc periodont loc'),
  ('K082', 'Atrofia do rebordo alveolar sem dentes', 'K08.2 Atrofia do rebordo alveolar s/dentes'),
  ('K083', 'Raiz dentária retida', 'K08.3 Raiz dentaria retida'),
  ('K088', 'Outros transtornos especificados dos dentes e das estruturas de sustentação', 'K08.8 Outr transt espec dentes estrut sustentacao'),
  ('K089', 'Transtorno dos dentes e de suas estruturas de sustentação, sem outra especificação', 'K08.9 Transt dentes estruturas sustentacao SOE'),
  ('K09', 'Cistos da região bucal não classificados em outra parte', 'K09 Cistos da regiao bucal NCOP'),
  ('K090', 'Cistos odontogênicos de desenvolvimento', 'K09.0 Cistos odontogenicos de desenvolv'),
  ('K091', 'Cistos de desenvolvimento (não-odontogênicos) da região bucal', 'K09.1 Cistos de desenvolv da regiao bucal'),
  ('K092', 'Outros cistos das mandíbulas', 'K09.2 Outr cistos das mandibulas'),
  ('K098', 'Outros cistos da região oral não classificados em outra parte', 'K09.8 Outr cistos da regiao oral NCOP'),
  ('K099', 'Cistos da região oral, sem outras especificações', 'K09.9 Cistos da regiao oral SOE'),
  ('K10', 'Outras doenças dos maxilares', 'K10 Outr doenc dos maxilares'),
  ('K100', 'Transtornos do desenvolvimento dos maxilares', 'K10.0 Transt do desenvolv dos maxilares'),
  ('K101', 'Granuloma central de células gigantes', 'K10.1 Granuloma central de celulas gigantes'),
  ('K102', 'Afecções inflamatórias dos maxilares', 'K10.2 Afeccoes inflam dos maxilares'),
  ('K103', 'Alveolite maxilar', 'K10.3 Alveolite maxilar'),
  ('K108', 'Outras doenças especificadas dos maxilares', 'K10.8 Outr doenc espec dos maxilares'),
  ('K109', 'Doença dos maxilares, sem outra especificação', 'K10.9 Doenc dos maxilares SOE'),
  ('K11', 'Doenças das glândulas salivares', 'K11 Doenc das gland salivares'),
  ('K110', 'Atrofia de glândula salivar', 'K11.0 Atrofia de gland salivar'),
  ('K111', 'Hipertrofia de glândula salivar', 'K11.1 Hipertrofia de gland salivar'),
  ('K112', 'Sialadenite', 'K11.2 Sialadenite'),
  ('K113', 'Abscesso de glândula salivar', 'K11.3 Abscesso de gland salivar'),
  ('K114', 'Fístula de glândula salivar', 'K11.4 Fistula de gland salivar'),
  ('K115', 'Sialolitíase', 'K11.5 Sialolitiase'),
  ('K116', 'Mucocele de glândula salivar', 'K11.6 Mucocele de gland salivar'),
  ('K117', 'Alterações da secreção salivar', 'K11.7 Alteracoes da secrecao salivar'),
  ('K118', 'Outras doenças das glândulas salivares', 'K11.8 Outr doenc das gland salivares'),
  ('K119', 'Doença de glândula salivar, sem outra especificação', 'K11.9 Doenc de gland salivar SOE'),
  ('K12', 'Estomatite e lesões correlatas', 'K12 Estomatite e lesoes correlatas'),
  ('K120', 'Aftas bucais recidivantes', 'K12.0 Aftas bucais recidivantes'),
  ('K121', 'Outras formas de estomatite', 'K12.1 Outr form de estomatite'),
  ('K122', 'Celulite e abscesso da boca', 'K12.2 Celulite e abscesso da boca'),
  ('K13', 'Outras doenças do lábio e da mucosa oral', 'K13 Outr doenc do labio e da mucosa oral'),
  ('K130', 'Doenças dos lábios', 'K13.0 Doenc dos labios'),
  ('K131', 'Mordedura da mucosa das bochechas e dos lábios', 'K13.1 Mordedura da mucosa das bochechas e labios'),
  ('K132', 'Leucoplasia e outras afecções do epitélio oral, inclusive da língua', 'K13.2 Leucoplas outr afecc epitelio oral incl ling'),
  ('K133', 'Leucoplasia pilosa', 'K13.3 Leucoplasia pilosa'),
  ('K134', 'Lesões granulomatosas e granulomatóides da mucosa oral', 'K13.4 Lesoes granulomat granulomatoid mucosa oral'),
  ('K135', 'Fibrose oral submucosa', 'K13.5 Fibrose oral submucosa'),
  ('K136', 'Hiperplasia irritativa da mucosa oral', 'K13.6 Hiperplasia irritativa da mucosa oral'),
  ('K137', 'Outras lesões e as não especificadas da mucosa oral', 'K13.7 Outr lesoes e as NE da mucosa oral'),
  ('K14', 'Doenças da língua', 'K14 Doenc da lingua'),
  ('K140', 'Glossite', 'K14.0 Glossite'),
  ('K141', 'Língua geográfica', 'K14.1 Lingua geografica'),
  ('K142', 'Glossite rombóide mediana', 'K14.2 Glossite romboide mediana'),
  ('K143', 'Hipertrofia das papilas linguais', 'K14.3 Hipertrofia das papilas linguais'),
  ('K144', 'Atrofia das papilas linguais', 'K14.4 Atrofia das papilas linguais'),
  ('K145', 'Língua escrotal', 'K14.5 Lingua escrotal'),
  ('K146', 'Glossodínia', 'K14.6 Glossodinia'),
  ('K148', 'Outras doenças da língua', 'K14.8 Outr doenc da lingua'),
  ('K149', 'Doença da língua, sem outra especificação', 'K14.9 Doenc da lingua SOE'),
  ('K20', 'Esofagite', 'K20 Esofagite'),
  ('K20', 'Esofagite', 'K20 Esofagite'),
  ('K21', 'Doença de refluxo gastroesofágico', 'K21 Doenc de refluxo gastroesofagico'),
  ('K210', 'Doença de refluxo gastroesofágico com esofagite', 'K21.0 Doenc de refluxo gastroesofagico c/esofagite'),
  ('K219', 'Doença de refluxo gastroesofágico sem esofagite', 'K21.9 Doenc de refluxo gastroesofagico s/esofagite'),
  ('K22', 'Outras doenças do esôfago', 'K22 Outr doenc do esofago'),
  ('K220', 'Acalásia do cárdia', 'K22.0 Acalasia do cardia'),
  ('K221', 'Úlcera do esôfago', 'K22.1 Ulcera do esofago'),
  ('K222', 'Obstrução do esôfago', 'K22.2 Obstrucao do esofago'),
  ('K223', 'Perfuração do esôfago', 'K22.3 Perfuracao do esofago'),
  ('K224', 'Discinesia do esôfago', 'K22.4 Discinesia do esofago'),
  ('K225', 'Divertículo do esôfago adquirido', 'K22.5 Diverticulo do esofago adquir'),
  ('K226', 'Síndrome da laceração hemorrágica gastroesofágica', 'K22.6 Sindr laceracao hemorragica gastroesofagica'),
  ('K227', 'Esôfago de Barret', 'K22.7 Esôfago de Barret'),
  ('K228', 'Outras doenças especificadas do esôfago', 'K22.8 Outr doenc espec do esofago'),
  ('K229', 'Doença do esôfago, sem outra especificação', 'K22.9 Doenc do esofago SOE'),
  ('K23', 'Transtornos do esôfago em doenças classificadas em outra parte', 'K23 Transt do esofago em doenc COP'),
  ('K230', 'Esofagite tuberculosa', 'K23.0 Esofagite tuberc'),
  ('K231', 'Megaesôfago na doença de Chagas', 'K23.1 Megaesofago na doenc de Chagas'),
  ('K238', 'Transtornos do esôfago em outras doenças classificadas em outra parte', 'K23.8 Transt do esofago em outr doenc COP'),
  ('K25', 'Úlcera gástrica', 'K25 Ulcera gastrica'),
  ('K250', 'Úlcera gástrica - aguda com hemorragia', 'K25.0 Aguda c/hemorragia'),
  ('K251', 'Úlcera gástrica - aguda com perfuração', 'K25.1 Aguda c/perfuracao'),
  ('K252', 'Úlcera gástrica - aguda com hemorragia e perfuração', 'K25.2 Aguda c/hemorragia e perfuracao'),
  ('K253', 'Úlcera gástrica - aguda sem hemorragia ou perfuração', 'K25.3 Aguda s/hemorragia ou perfuracao'),
  ('K254', 'Úlcera gástrica - crônica ou não especificada com hemorragia', 'K25.4 Cronica ou NE c/hemorragia'),
  ('K255', 'Úlcera gástrica - crônica ou não especificada com perfuração', 'K25.5 Cronica ou NE c/perfuracao'),
  ('K256', 'Úlcera gástrica - crônica ou não especificada com hemorragia e perfuração', 'K25.6 Cronica ou NE c/hemorragia e perfuracao'),
  ('K257', 'Úlcera gástrica - crônica sem hemorragia ou perfuração', 'K25.7 Cronica s/hemorragia ou perfuracao'),
  ('K259', 'Úlcera gástrica - não especificada como aguda ou crônica, sem hemorragia ou perfuração', 'K25.9 NE como aguda cronica s/hemorragia perfur'),
  ('K26', 'Úlcera duodenal', 'K26 Ulcera duodenal'),
  ('K260', 'Úlcera duodenal - aguda com hemorragia', 'K26.0 Aguda c/hemorragia'),
  ('K261', 'Úlcera duodenal - aguda com perfuração', 'K26.1 Aguda c/perfuracao'),
  ('K262', 'Úlcera duodenal - aguda com hemorragia e perfuração', 'K26.2 Aguda c/hemorragia e perfuracao'),
  ('K263', 'Úlcera duodenal - aguda sem hemorragia ou perfuração', 'K26.3 Aguda s/hemorragia ou perfuracao'),
  ('K264', 'Úlcera duodenal - crônica ou não especificada com hemorragia', 'K26.4 Cronica ou NE c/hemorragia'),
  ('K265', 'Úlcera duodenal - crônica ou não especificada com perfuração', 'K26.5 Cronica ou NE c/perfuracao'),
  ('K266', 'Úlcera duodenal - crônica ou não especificada com hemorragia e perfuração', 'K26.6 Cronica ou NE c/hemorragia e perfuracao'),
  ('K267', 'Úlcera duodenal - crônica sem hemorragia ou perfuração', 'K26.7 Cronica s/hemorragia ou perfuracao'),
  ('K269', 'Úlcera duodenal - não especificada como aguda ou crônica, sem hemorragia ou perfuração', 'K26.9 NE como aguda cronica s/hemorragia perfur'),
  ('K27', 'Úlcera péptica de localização não especificada', 'K27 Ulcera peptica de localiz NE'),
  ('K270', 'Úlcera péptica de localização não especificada - aguda com hemorragia', 'K27.0 Aguda c/hemorragia'),
  ('K271', 'Úlcera péptica de localização não especificada - aguda com perfuração', 'K27.1 Aguda c/perfuracao'),
  ('K272', 'Úlcera péptica de localização não especificada - aguda com hemorragia e perfuração', 'K27.2 Aguda c/hemorragia e perfuracao'),
  ('K273', 'Úlcera péptica de localização não especificada - aguda sem hemorragia ou perfuração', 'K27.3 Aguda s/hemorragia ou perfuracao'),
  ('K274', 'Úlcera péptica de localização não especificada - crônica ou não especificada com hemorragia', 'K27.4 Cronica ou NE c/hemorragia'),
  ('K275', 'Úlcera péptica de localização não especificada - crônica ou não especificada com perfuração', 'K27.5 Cronica ou NE c/perfuracao'),
  ('K276', 'Úlcera péptica de localização não especificada - crônica ou não especificada com hemorragia e perfuração', 'K27.6 Cronica ou NE c/hemorragia e perfuracao'),
  ('K277', 'Úlcera péptica de localização não especificada - crônica sem hemorragia ou perfuração', 'K27.7 Cronica s/hemorragia ou perfuracao'),
  ('K279', 'Úlcera péptica de localização não especificada - não especificada como aguda ou crônica, sem hemorragia ou perfuração', 'K27.9 NE como aguda cronica s/hemorragia perfur'),
  ('K28', 'Úlcera gastrojejunal', 'K28 Ulcera gastrojejunal'),
  ('K280', 'Úlcera gastrojejunal - aguda com hemorragia', 'K28.0 Aguda c/hemorragia'),
  ('K281', 'Úlcera gastrojejunal - aguda com perfuração', 'K28.1 Aguda c/perfuracao'),
  ('K282', 'Úlcera gastrojejunal - aguda com hemorragia e perfuração', 'K28.2 Aguda c/hemorragia e perfuracao'),
  ('K283', 'Úlcera gastrojejunal - aguda sem hemorragia ou perfuração', 'K28.3 Aguda s/hemorragia ou perfuracao'),
  ('K284', 'Úlcera gastrojejunal - crônica ou não especificada com hemorragia', 'K28.4 Cronica ou NE c/hemorragia'),
  ('K285', 'Úlcera gastrojejunal - crônica ou não especificada com perfuração', 'K28.5 Cronica ou NE c/perfuracao'),
  ('K286', 'Úlcera gastrojejunal - crônica ou não especificada com hemorragia e perfuração', 'K28.6 Cronica ou NE c/hemorragia e perfuracao'),
  ('K287', 'Úlcera gastrojejunal - crônica sem hemorragia ou perfuração', 'K28.7 Cronica s/hemorragia ou perfuracao'),
  ('K289', 'Úlcera gastrojejunal - não especificada como aguda ou crônica, sem hemorragia ou perfuração', 'K28.9 NE como aguda cronica s/hemorragia perfur'),
  ('K29', 'Gastrite e duodenite', 'K29 Gastrite e duodenite'),
  ('K290', 'Gastrite hemorrágica aguda', 'K29.0 Gastrite hemorragica aguda'),
  ('K291', 'Outras gastrites agudas', 'K29.1 Outr gastrites agudas'),
  ('K292', 'Gastrite alcoólica', 'K29.2 Gastrite alcoolica'),
  ('K293', 'Gastrite superficial crônica', 'K29.3 Gastrite superf cronica'),
  ('K294', 'Gastrite atrófica crônica', 'K29.4 Gastrite atrofica cronica'),
  ('K295', 'Gastrite crônica, sem outra especificação', 'K29.5 Gastrite cronica SOE'),
  ('K296', 'Outras gastrites', 'K29.6 Outr gastrites'),
  ('K297', 'Gastrite não especificada', 'K29.7 Gastrite NE'),
  ('K298', 'Duodenite', 'K29.8 Duodenite'),
  ('K299', 'Gastroduodenite, sem outra especificação', 'K29.9 Gastroduodenite SOE'),
  ('K30', 'Dispepsia', 'K30 Dispepsia'),
  ('K30', 'Dispepsia', 'K30 Dispepsia'),
  ('K31', 'Outras doenças do estômago e do duodeno', 'K31 Outr doenc do estomago e do duodeno'),
  ('K310', 'Dilatação aguda do estômago', 'K31.0 Dilatacao aguda do estomago'),
  ('K311', 'Estenose pilórica hipertrófica do adulto', 'K31.1 Estenose pilorica hipertrofica do adulto'),
  ('K312', 'Estenose e estreitamento em ampulheta do estômago', 'K31.2 Estenose e estreitamento ampulheta estomago'),
  ('K313', 'Espasmo do piloro não classificado em outra parte', 'K31.3 Espasmo do piloro NCOP'),
  ('K314', 'Divertículo gástrico', 'K31.4 Diverticulo gastrico'),
  ('K315', 'Obstrução do duodeno', 'K31.5 Obstrucao do duodeno'),
  ('K316', 'Fístula do estômago e do duodeno', 'K31.6 Fistula do estomago e do duodeno'),
  ('K317', 'Pólipo do estômago e do duodeno', 'K31.7 Polipo do estomago e do duodeno'),
  ('K318', 'Outras doenças especificadas do estômago e do duodeno', 'K31.8 Outr doenc espec do estomago e do duodeno'),
  ('K319', 'Doenças do estômago e do duodeno, sem outra especificação', 'K31.9 Doenc do estomago e do duodeno SOE'),
  ('K35', 'Apendicite aguda', 'K35 Apendicite aguda'),
  ('K350', 'Apendicite aguda com peritonite generalizada', 'K35.0 Apendicite aguda c/peritonite generalizada'),
  ('K351', 'Apendicite aguda com abscesso peritonial', 'K35.1 Apendicite aguda c/abscesso peritonial'),
  ('K359', 'Apendicite aguda sem outra especificação', 'K35.9 Apendicite aguda SOE'),
  ('K36', 'Outras formas de apendicite', 'K36 Outr form de apendicite'),
  ('K36', 'Outras formas de apendicite', 'K36 Outr form de apendicite'),
  ('K37', 'Apendicite, sem outras especificações', 'K37 Apendicite SOE'),
  ('K37', 'Apendicite, sem outras especificações', 'K37 Apendicite SOE'),
  ('K38', 'Outras doenças do apêndice', 'K38 Outr doenc do apendice'),
  ('K380', 'Hiperplasia do apêndice', 'K38.0 Hiperplasia do apendice'),
  ('K381', 'Concreções apendiculares', 'K38.1 Concrecoes apendiculares'),
  ('K382', 'Divertículo do apêndice', 'K38.2 Diverticulo do apendice'),
  ('K383', 'Fístula do apêndice', 'K38.3 Fistula do apendice'),
  ('K388', 'Outras doenças especificadas do apêndice', 'K38.8 Outr doenc espec do apendice'),
  ('K389', 'Doença do apêndice, sem outra especificação', 'K38.9 Doenc do apendice SOE'),
  ('K40', 'Hérnia inguinal', 'K40 Hernia inguinal'),
  ('K400', 'Hérnia inguinal bilateral, com obstrução, sem gangrena', 'K40.0 Hernia inguinal bilateral c/obstr s/gangrena'),
  ('K401', 'Hérnia inguinal bilateral, com gangrena', 'K40.1 Hernia inguinal bilateral c/gangrena'),
  ('K402', 'Hérnia inguinal bilateral, sem obstrução ou gangrena', 'K40.2 Hernia inguinal bilat s/obstr ou gangrena'),
  ('K403', 'Hérnia inguinal unilateral ou não especificada, com obstrução sem gangrena', 'K40.3 Hernia inguinal unilat NE c/obstr s/gangrena'),
  ('K404', 'Hérnia inguinal unilateral ou não especificada, com gangrena', 'K40.4 Hernia inguinal unilateral ou NE c/gangrena'),
  ('K409', 'Hérnia inguinal unilateral ou não especificada, sem obstrução ou gangrena', 'K40.9 Hernia inguinal unilat NE s/obstr gangrena'),
  ('K41', 'Hérnia femoral', 'K41 Hernia femoral'),
  ('K410', 'Hérnia femoral bilateral, com obstrução, sem gangrena', 'K41.0 Hernia femoral bilateral c/obstr s/gangrena'),
  ('K411', 'Hérnia femoral bilateral, com gangrena', 'K41.1 Hernia femoral bilateral c/gangrena'),
  ('K412', 'Hérnia femoral bilateral, sem obstrução ou gangrena', 'K41.2 Hernia femoral bilateral s/obstr ou gangrena'),
  ('K413', 'Hérnia femoral unilateral ou não especificada, com obstrução, sem gangrena', 'K41.3 Hernia femoral unilat NE c/obstr s/gangrena'),
  ('K414', 'Hérnia femoral unilateral ou não especificada, com gangrena', 'K41.4 Hernia femoral unilateral ou NE c/gangrena'),
  ('K419', 'Hérnia femoral unilateral ou não especificada, sem obstrução ou gangrena', 'K41.9 Hernia femoral unilat NE s/obstr ou gangrena'),
  ('K42', 'Hérnia umbilical', 'K42 Hernia umbilical'),
  ('K420', 'Hérnia umbilical com obstrução, sem gangrena', 'K42.0 Hernia umbilical c/obstrucao s/gangrena'),
  ('K421', 'Hérnia umbilical com gangrena', 'K42.1 Hernia umbilical c/gangrena'),
  ('K429', 'Hérnia umbilical sem obstrução ou gangrena', 'K42.9 Hernia umbilical s/obstrucao ou gangrena'),
  ('K43', 'Hérnia ventral', 'K43 Hernia ventral'),
  ('K430', 'Hérnia ventral com obstrução, sem gangrena', 'K43.0 Hernia ventral c/obstrucao s/gangrena'),
  ('K431', 'Hérnia ventral com gangrena', 'K43.1 Hernia ventral c/gangrena'),
  ('K439', 'Hérnia ventral sem obstrução ou gangrena', 'K43.9 Hernia ventral s/obstrucao ou gangrena'),
  ('K44', 'Hérnia diafragmática', 'K44 Hernia diafragmatica'),
  ('K440', 'Hérnia diafragmática com obstrução, sem gangrena', 'K44.0 Hernia diafragmatica c/obstrucao s/gangrena'),
  ('K441', 'Hérnia diafragmática com gangrena', 'K44.1 Hernia diafragmatica c/gangrena'),
  ('K449', 'Hérnia diafragmática sem obstrução ou gangrena', 'K44.9 Hernia diafragmatica s/obstrucao ou gangrena'),
  ('K45', 'Outras hérnias abdominais', 'K45 Outr hernias abdominais'),
  ('K450', 'Outras hérnias abdominais especificadas, com obstrução, sem gangrena', 'K45.0 Outr hernias abdom espec c/obstr s/gangrena'),
  ('K451', 'Outras hérnias abdominais especificadas, com gangrena', 'K45.1 Outr hernias abdominais espec com gangrena'),
  ('K458', 'Outras hérnias abdominais especificadas, sem obstrução ou gangrena', 'K45.8 Outr hernias abdom espec s/obstr ou gangrena'),
  ('K46', 'Hérnia abdominal não especificada', 'K46 Hernia abdominal NE'),
  ('K460', 'Hérnia abdominal não especificada, com obstrução, sem gangrena', 'K46.0 Hernia abdominal NE c/obstrucao s/gangrena'),
  ('K461', 'Hérnia abdominal não especificada com gangrena', 'K46.1 Hernia abdominal NE c/gangrena'),
  ('K469', 'Hérnia abdominal não especificada, sem obstrução ou gangrena', 'K46.9 Hernia abdominal NE s/obstrucao ou gangrena'),
  ('K50', 'Doença de Crohn (enterite regional)', 'K50 Doenc de Crohn'),
  ('K500', 'Doença de Crohn do intestino delgado', 'K50.0 Doenc de Crohn do intestino delgado'),
  ('K501', 'Doença de Crohn do intestino grosso', 'K50.1 Doenc de Crohn do intestino grosso'),
  ('K508', 'Outra forma de doença de Crohn', 'K50.8 Outr form de doenc de Crohn'),
  ('K509', 'Doença de Crohn de localização não especificada', 'K50.9 Doenc de Crohn de localiz NE'),
  ('K51', 'Colite ulcerativa', 'K51 Colite ulcerativa'),
  ('K510', 'Enterocolite ulcerativa (crônica)', 'K51.0 Enterocolite ulcerativa'),
  ('K511', 'Ileocolite ulcerativa (crônica)', 'K51.1 Ileocolite ulcerativa'),
  ('K512', 'Proctite ulcerativa (crônica)', 'K51.2 Proctite ulcerativa'),
  ('K513', 'Retossigmoidite ulcerativa (crônica)', 'K51.3 Retossigmoidite ulcerativa'),
  ('K514', 'Pseudopolipose do cólon', 'K51.4 Pseudopolipose do colon'),
  ('K515', 'Proctocolite mucosa', 'K51.5 Proctocolite mucosa'),
  ('K518', 'Outras colites ulcerativas', 'K51.8 Outr colites ulcerativas'),
  ('K519', 'Colite ulcerativa, sem outra especificação', 'K51.9 Colite ulcerativa SOE'),
  ('K52', 'Outras gastroenterites e colites não-infecciosas', 'K52 Outr gastroenterites e colites nao-infecc'),
  ('K520', 'Gastroenterite e colite devida à radiação', 'K52.0 Gastroenterite e colite dev radiacao'),
  ('K521', 'Gastroenterite e colite tóxicas', 'K52.1 Gastroenterite e colite toxicas'),
  ('K522', 'Gastroenterite e colite alérgicas ou ligadas à dieta', 'K52.2 Gastroenterite colite alerg ligadas a dieta'),
  ('K528', 'Outras gastroenterites e colites especificadas, não-infecciosas', 'K52.8 Outr gastroenterites e colites espec nao-inf'),
  ('K529', 'Gastroenterite e colite não-infecciosas, não especificadas', 'K52.9 Gastroenterite e colite nao-infecc NE'),
  ('K55', 'Transtornos vasculares do intestino', 'K55 Transt vasculares do intestino'),
  ('K550', 'Transtornos vasculares agudos do intestino', 'K55.0 Transt vasculares agudos do intestino'),
  ('K551', 'Transtornos vasculares crônicos do intestino', 'K55.1 Transt vasculares cronicos do intestino'),
  ('K552', 'Angiodisplasia do cólon', 'K55.2 Angiodisplasia do colon'),
  ('K558', 'Outros transtornos vasculares do intestino', 'K55.8 Outr transt vasculares do intestino'),
  ('K559', 'Transtorno vascular do intestino, sem outra especificação', 'K55.9 Transt vascular do intestino SOE'),
  ('K56', 'Íleo paralítico e obstrução intestinal sem hérnia', 'K56 Ileo paralitico e obstr intestinal s/hernia'),
  ('K560', 'Íleo paralítico', 'K56.0 Ileo paralitico'),
  ('K561', 'Intussuscepção', 'K56.1 Intussuscepcao'),
  ('K562', 'Volvo', 'K56.2 Volvo'),
  ('K563', 'Íleo biliar', 'K56.3 Ileo biliar'),
  ('K564', 'Outras obstruções do intestino', 'K56.4 Outr obstrucoes do intestino'),
  ('K565', 'Aderências intestinais (bridas) com obstrução', 'K56.5 Aderencias intestinais c/obstrucao'),
  ('K566', 'Outras formas de obstrução intestinal, e as não especificadas', 'K56.6 Outr form de obstrucao intestinal e as NE'),
  ('K567', 'Íleo, não especificado', 'K56.7 Ileo NE'),
  ('K57', 'Doença diverticular do intestino', 'K57 Doenc diverticular do intestino'),
  ('K570', 'Doença diverticular do intestino delgado com perfuração e abscesso', 'K57.0 Doenc divert intest delgado c/perfur absces'),
  ('K571', 'Doença diverticular do intestino delgado sem perfuração ou abscesso', 'K57.1 Doenc divert intest delgado s/perfur absces'),
  ('K572', 'Doença diverticular do intestino grosso com perfuração e abscesso', 'K57.2 Doenc divert intest grosso c/perfur abscesso'),
  ('K573', 'Doença diverticular do intestino grosso sem perfuração ou abscesso', 'K57.3 Doenc divert intest grosso s/perfur abscesso'),
  ('K574', 'Doença diverticular concomitante dos intestinos delgado e grosso com perfuração e abscesso', 'K57.4 Doenc divert intest delg grosso c/perf absc'),
  ('K575', 'Doença diverticular concomitante dos intestinos delgado e grosso sem perfuração ou abscesso', 'K57.5 Doenc divert intest delg grosso s/perf absc'),
  ('K578', 'Doença diverticular do intestino, de localização não especificada, com perfuração e abscesso', 'K57.8 Doenc divert intest localiz NE c/perf absc'),
  ('K579', 'Doença diverticular do intestino, de localização não especificada, sem perfuração ou abscesso', 'K57.9 Doenc divert intest localiz NE s/perf absc'),
  ('K58', 'Síndrome do cólon irritável', 'K58 Sindr do colon irritavel'),
  ('K580', 'Síndrome do cólon irritável com diarréia', 'K58.0 Sindr do colon irritavel c/diarreia'),
  ('K589', 'Síndrome do cólon irritável sem diarréia', 'K58.9 Sindr do colon irritavel s/diarreia'),
  ('K59', 'Outros transtornos funcionais do intestino', 'K59 Outr transt funcionais do intestino'),
  ('K590', 'Constipação', 'K59.0 Constipacao'),
  ('K591', 'Diarréia funcional', 'K59.1 Diarreia funcional'),
  ('K592', 'Cólon neurogênico não classificado em outra parte', 'K59.2 Colon neurogenico NCOP'),
  ('K593', 'Megacólon não classificado em outra parte', 'K59.3 Megacolon NCOP'),
  ('K594', 'Espasmo anal', 'K59.4 Espasmo anal'),
  ('K598', 'Outros transtornos funcionais especificados do intestino', 'K59.8 Outr transt funcionais espec do intestino'),
  ('K599', 'Transtorno intestinal funcional, não especificado', 'K59.9 Transt intestinal funcional NE'),
  ('K60', 'Fissura e fístula das regiões anal e retal', 'K60 Fissura e fistula das regioes anal e retal'),
  ('K600', 'Fissura anal aguda', 'K60.0 Fissura anal aguda'),
  ('K601', 'Fissura anal crônica', 'K60.1 Fissura anal cronica'),
  ('K602', 'Fissura anal, não especificada', 'K60.2 Fissura anal NE'),
  ('K603', 'Fístula anal', 'K60.3 Fistula anal'),
  ('K604', 'Fístula retal', 'K60.4 Fistula retal'),
  ('K605', 'Fístula anorretal', 'K60.5 Fistula anorretal'),
  ('K61', 'Abscesso das regiões anal e retal', 'K61 Abscesso das regioes anal e retal'),
  ('K610', 'Abscesso anal', 'K61.0 Abscesso anal'),
  ('K611', 'Abscesso retal', 'K61.1 Abscesso retal'),
  ('K612', 'Abscesso anorretal', 'K61.2 Abscesso anorretal'),
  ('K613', 'Abscesso ísquio-retal', 'K61.3 Abscesso isquio-retal'),
  ('K614', 'Abscesso intra-esfincteriano', 'K61.4 Abscesso intra-esfincteriano'),
  ('K62', 'Outras doenças do reto e do ânus', 'K62 Outr doenc do reto e do anus'),
  ('K620', 'Pólipo anal', 'K62.0 Polipo anal'),
  ('K621', 'Pólipo retal', 'K62.1 Polipo retal'),
  ('K622', 'Prolapso anal', 'K62.2 Prolapso anal'),
  ('K623', 'Prolapso retal', 'K62.3 Prolapso retal'),
  ('K624', 'Estenose do ânus e do reto', 'K62.4 Estenose do anus e do reto'),
  ('K625', 'Hemorragia do ânus e do reto', 'K62.5 Hemorragia do anus e do reto'),
  ('K626', 'Úlcera do ânus e do reto', 'K62.6 Ulcera do anus e do reto'),
  ('K627', 'Proctite por radiação', 'K62.7 Proctite p/radiacao'),
  ('K628', 'Outras doenças especificadas do ânus e do reto', 'K62.8 Outr doenc espec do anus e do reto'),
  ('K629', 'Doença do ânus e do reto, sem outra especificação', 'K62.9 Doenc do anus e do reto SOE'),
  ('K63', 'Outras doenças do intestino', 'K63 Outr doenc do intestino'),
  ('K630', 'Abscesso do intestino', 'K63.0 Abscesso do intestino'),
  ('K631', 'Perfuração do intestino (não-traumática)', 'K63.1 Perfuracao do intestino'),
  ('K632', 'Fístula do intestino', 'K63.2 Fistula do intestino'),
  ('K633', 'Úlcera do intestino', 'K63.3 Ulcera do intestino'),
  ('K634', 'Enteroptose', 'K63.4 Enteroptose'),
  ('K635', 'Pólipo do cólon', 'K63.5 Polipo do colon'),
  ('K638', 'Outras doenças especificadas do intestino', 'K63.8 Outr doenc espec do intestino'),
  ('K639', 'Doença do intestino, sem outra especificação', 'K63.9 Doenc do intestino SOE'),
  ('K65', 'Peritonite', 'K65 Peritonite'),
  ('K650', 'Peritonite aguda', 'K65.0 Peritonite aguda'),
  ('K658', 'Outras peritonites', 'K65.8 Outr peritonites'),
  ('K659', 'Peritonite, sem outras especificações', 'K65.9 Peritonite SOE'),
  ('K66', 'Outros transtornos do peritônio', 'K66 Outr transt do peritonio'),
  ('K660', 'Aderências peritoniais', 'K66.0 Aderencias peritoniais'),
  ('K661', 'Hemoperitônio', 'K66.1 Hemoperitonio'),
  ('K668', 'Outras afecções especificadas do peritônio', 'K66.8 Outr afeccoes espec do peritonio'),
  ('K669', 'Afecções do peritônio, sem outra especificação', 'K66.9 Afeccoes do peritonio SOE'),
  ('K67', 'Comprometimento do peritônio, em doenças infecciosas classificadas em outra parte', 'K67 Compr do peritonio em doenc infecc COP'),
  ('K670', 'Peritonite por clamídias', 'K67.0 Peritonite p/clamidias'),
  ('K671', 'Peritonite gonocócica', 'K67.1 Peritonite gonococica'),
  ('K672', 'Peritonite sifilítica', 'K67.2 Peritonite sifilitica'),
  ('K673', 'Peritonite tuberculosa', 'K67.3 Peritonite tuberc'),
  ('K678', 'Outras formas de comprometimento do peritônio em doenças infecciosas classificadas em outra parte', 'K67.8 Outr form compr peritonio doenc infecc COP'),
  ('K70', 'Doença alcoólica do fígado', 'K70 Doenc alcoolica do figado'),
  ('K700', 'Fígado gorduroso alcoólico', 'K70.0 Figado gorduroso alcoolico'),
  ('K701', 'Hepatite alcoólica', 'K70.1 Hepatite alcoolica'),
  ('K702', 'Fibrose e esclerose alcoólicas do fígado', 'K70.2 Fibrose e esclerose alcoolicas do figado'),
  ('K703', 'Cirrose hepática alcoólica', 'K70.3 Cirrose hepatica alcoolica'),
  ('K704', 'Insuficiência hepática alcoólica', 'K70.4 Insuf hepatica alcoolica'),
  ('K709', 'Doença alcoólica do fígado, sem outra especificação', 'K70.9 Doenc alcoolica do figado SOE'),
  ('K71', 'Doença hepática tóxica', 'K71 Doenc hepatica toxica'),
  ('K710', 'Doença hepática tóxica com colestase', 'K71.0 Doenc hepatica toxica c/colestase'),
  ('K711', 'Doença hepática tóxica com necrose hepática', 'K71.1 Doenc hepatica toxica c/necrose hepatica'),
  ('K712', 'Doença hepática tóxica com hepatite aguda', 'K71.2 Doenc hepatica toxica c/hepatite aguda'),
  ('K713', 'Doença hepática tóxica com hepatite crônica persistente', 'K71.3 Doenc hepatica tox c/hepatite cron persist'),
  ('K714', 'Doença hepática tóxica com hepatite crônica lobular', 'K71.4 Doenc hepatica tox c/hepatite cron lobular'),
  ('K715', 'Doença hepática tóxica com hepatite crônica ativa', 'K71.5 Doenc hepatica toxica c/hepatite cron ativa'),
  ('K716', 'Doença hepática tóxica com hepatite não classificada em outra parte', 'K71.6 Doenc hepatica toxica c/hepatite NCOP'),
  ('K717', 'Doença hepática tóxica com fibrose e cirrose hepáticas', 'K71.7 Doenc hepat toxica c/fibrose e cirrose hepat'),
  ('K718', 'Doença hepática tóxica com outros transtornos do fígado', 'K71.8 Doenc hepatica toxica c/outr transt figado'),
  ('K719', 'Doença hepática tóxica, sem outra especificação', 'K71.9 Doenc hepatica toxica SOE'),
  ('K72', 'Insuficiência hepática não classificada em outra parte', 'K72 Insuf hepatica NCOP'),
  ('K720', 'Insuficiência hepática aguda e subaguda', 'K72.0 Insuf hepatica aguda e subaguda'),
  ('K721', 'Insuficiência hepática crônica', 'K72.1 Insuf hepatica cronica'),
  ('K729', 'Insuficiência hepática, sem outras especificações', 'K72.9 Insuf hepatica SOE'),
  ('K73', 'Hepatite crônica não classificada em outra parte', 'K73 Hepatite cronica NCOP'),
  ('K730', 'Hepatite crônica persistente, não classificada em outra parte', 'K73.0 Hepatite cronica persistente NCOP'),
  ('K731', 'Hepatite crônica lobular, não classificada em outra parte', 'K73.1 Hepatite cronica lobular NCOP'),
  ('K732', 'Hepatite crônica ativa, não classificada em outra parte', 'K73.2 Hepatite cronica ativa NCOP'),
  ('K738', 'Outras hepatites crônicas não classificada em outra parte', 'K73.8 Outr hepatites cronicas NCOP'),
  ('K739', 'Hepatite crônica, sem outra especificação', 'K73.9 Hepatite cronica SOE'),
  ('K74', 'Fibrose e cirrose hepáticas', 'K74 Fibrose e cirrose hepaticas'),
  ('K740', 'Fibrose hepática', 'K74.0 Fibrose hepatica'),
  ('K741', 'Esclerose hepática', 'K74.1 Esclerose hepatica'),
  ('K742', 'Fibrose hepática com esclerose hepática', 'K74.2 Fibrose hepatica c/esclerose hepatica'),
  ('K743', 'Cirrose biliar primária', 'K74.3 Cirrose biliar prim'),
  ('K744', 'Cirrose biliar secundária', 'K74.4 Cirrose biliar secund'),
  ('K745', 'Cirrose biliar, sem outra especificação', 'K74.5 Cirrose biliar SOE'),
  ('K746', 'Outras formas de cirrose hepática e as não especificadas', 'K74.6 Outr form de cirrose hepatica e as NE'),
  ('K75', 'Outras doenças inflamatórias do fígado', 'K75 Outr doenc inflam do figado'),
  ('K750', 'Abscesso hepático', 'K75.0 Abscesso hepatico'),
  ('K751', 'Flebite da veia porta', 'K75.1 Flebite da veia porta'),
  ('K752', 'Hepatite reativa não-específica', 'K75.2 Hepatite reativa nao-especifica'),
  ('K753', 'Hepatite granulomatosa não classificada em outra parte', 'K75.3 Hepatite granulomatosa NCOP'),
  ('K754', 'Hepatite autoimune', 'K75.4 Hepatite autoimune'),
  ('K758', 'Outras doenças hepáticas inflamatórias especificadas', 'K75.8 Outr doenc hepaticas inflam espec'),
  ('K759', 'Doença hepática inflamatória, sem outra especificação', 'K75.9 Doenc hepatica inflam SOE'),
  ('K76', 'Outras doenças do fígado', 'K76 Outr doenc do figado'),
  ('K760', 'Degeneração gordurosa do fígado não classificada em outra parte', 'K76.0 Degeneracao gordurosa do figado NCOP'),
  ('K761', 'Congestão passiva crônica do fígado', 'K76.1 Congestao passiva cronica do figado'),
  ('K762', 'Necrose hemorrágica central do fígado', 'K76.2 Necrose hemorragica central do figado'),
  ('K763', 'Infarto do fígado', 'K76.3 Infarto do figado'),
  ('K764', 'Peliose hepática', 'K76.4 Peliose hepatica'),
  ('K765', 'Doença hepática veno-oclusiva', 'K76.5 Doenc hepatica veno-oclusiva'),
  ('K766', 'Hipertensão portal', 'K76.6 Hipertensao portal'),
  ('K767', 'Síndrome hepatorrenal', 'K76.7 Sindr hepatorrenal'),
  ('K768', 'Outras doenças especificadas do fígado', 'K76.8 Outr doenc espec do figado'),
  ('K769', 'Doença hepática, sem outra especificação', 'K76.9 Doenc hepatica SOE'),
  ('K77', 'Transtornos do fígado em doenças classificadas em outra parte', 'K77 Transt do figado em doenc COP'),
  ('K770', 'Transtornos hepáticos em doenças infecciosas e parasitárias classificadas em outra parte', 'K77.0 Transt hepaticos doenc infecc e parasit COP'),
  ('K778', 'Transtornos hepáticos em outras doenças classificadas em outra parte', 'K77.8 Transt hepaticos em outr doenc COP'),
  ('K80', 'Colelitíase', 'K80 Colelitiase'),
  ('K800', 'Calculose da vesícula biliar com colicistite aguda', 'K80.0 Calculose vesicula biliar c/colicistite agud'),
  ('K801', 'Calculose da vesícula biliar com outras formas de colecistite', 'K80.1 Calculose vesic biliar c/outr form colecist'),
  ('K802', 'Calculose da vesícula biliar sem colecistite', 'K80.2 Calculose da vesicula biliar s/colecistite'),
  ('K803', 'Calculose de via biliar com colangite', 'K80.3 Calculose de via biliar c/colangite'),
  ('K804', 'Calculose de via biliar com colecistite', 'K80.4 Calculose de via biliar c/colecistite'),
  ('K805', 'Calculose de via biliar sem colangite ou colecistite', 'K80.5 Calculose via biliar s/colangite colecistite'),
  ('K808', 'Outras colelitíases', 'K80.8 Outr colelitiases'),
  ('K81', 'Colecistite', 'K81 Colecistite'),
  ('K810', 'Colecistite aguda', 'K81.0 Colecistite aguda'),
  ('K811', 'Colecistite crônica', 'K81.1 Colecistite cronica'),
  ('K818', 'Outras colecistites', 'K81.8 Outr colecistites'),
  ('K819', 'Colecistite, sem outra especificação', 'K81.9 Colecistite SOE'),
  ('K82', 'Outras doenças da vesícula biliar', 'K82 Outr doenc da vesicula biliar'),
  ('K820', 'Obstrução da vesícula biliar', 'K82.0 Obstrucao da vesicula biliar'),
  ('K821', 'Hidropsia da vesícula biliar', 'K82.1 Hidropsia da vesicula biliar'),
  ('K822', 'Perfuração da vesícula biliar', 'K82.2 Perfuracao da vesicula biliar'),
  ('K823', 'Fístula da vesícula biliar', 'K82.3 Fistula da vesicula biliar'),
  ('K824', 'Colesterolose da vesícula biliar', 'K82.4 Colesterolose da vesicula biliar'),
  ('K828', 'Outras doenças especificadas da vesícula biliar', 'K82.8 Outr doenc espec da vesicula biliar'),
  ('K829', 'Doença da vesícula biliar, sem outra especificação', 'K82.9 Doenc da vesicula biliar SOE'),
  ('K83', 'Outras doenças das vias biliares', 'K83 Outr doenc das vias biliares'),
  ('K830', 'Colangite', 'K83.0 Colangite'),
  ('K831', 'Obstrução de via biliar', 'K83.1 Obstrucao de via biliar'),
  ('K832', 'Perfuração de via biliar', 'K83.2 Perfuracao de via biliar'),
  ('K833', 'Fístula de via biliar', 'K83.3 Fistula de via biliar'),
  ('K834', 'Espasmo do esfíncter de Oddi', 'K83.4 Espasmo do esfincter de Oddi'),
  ('K835', 'Cisto biliar', 'K83.5 Cisto biliar'),
  ('K838', 'Outras doenças especificadas das vias biliares', 'K83.8 Outr doenc espec das vias biliares'),
  ('K839', 'Doença das vias biliares, sem outra especificação', 'K83.9 Doenc das vias biliares SOE'),
  ('K85', 'Pancreatite aguda', 'K85 Pancreatite aguda'),
  ('K850', 'Pancreatite aguda idiopática', 'K85.0 Pancreatite aguda idiopática'),
  ('K851', 'Pancreatite aguda biliar', 'K85.1 Pancreatite aguda biliar'),
  ('K852', 'Pancreatite aguda induzida por álcool', 'K85.2 Pancreatite aguda induzida por álcool'),
  ('K853', 'Pancreatite aguda induzida por droga', 'K85.3 Pancreatite aguda induzida por droga'),
  ('K858', 'Outras pancreatites agudas', 'K85.8 Outras pancreatites agudas'),
  ('K859', 'Pancreatite aguda, não especificada', 'K85.9 Pancreatite aguda, não especificada'),
  ('K86', 'Outras doenças do pâncreas', 'K86 Outr doenc do pancreas'),
  ('K860', 'Pancreatite crônica induzida por álcool', 'K86.0 Pancreatite cronica induz p/alcool'),
  ('K861', 'Outras pancreatites crônicas', 'K86.1 Outr pancreatites cronicas'),
  ('K862', 'Cisto do pâncreas', 'K86.2 Cisto do pancreas'),
  ('K863', 'Pseudocisto do pâncreas', 'K86.3 Pseudocisto do pancreas'),
  ('K868', 'Outras doenças especificadas do pâncreas', 'K86.8 Outr doenc espec do pancreas'),
  ('K869', 'Doença do pâncreas, sem outra especificação', 'K86.9 Doenc do pancreas SOE'),
  ('K87', 'Transtornos da vesícula biliar, das vias biliares e do pâncreas em doenças classificadas em outra parte', 'K87 Transt ves biliar via biliar pancr doenc COP'),
  ('K870', 'Transtornos da vesícula biliar e das vias biliares em doenças classificadas em outra parte', 'K87.0 Transt vesic biliar vias biliares doenc COP'),
  ('K871', 'Transtornos do pâncreas em doenças classificadas em outra parte', 'K87.1 Transt do pancreas em doenc COP'),
  ('K90', 'Má-absorção intestinal', 'K90 Ma-absorcao intestinal'),
  ('K900', 'Doença celíaca', 'K90.0 Doenc celiaca'),
  ('K901', 'Espru tropical', 'K90.1 Espru tropical'),
  ('K902', 'Síndrome da alça cega não classificada em outra parte', 'K90.2 Sindr da alca cega NCOP'),
  ('K903', 'Esteatorréia pancreática', 'K90.3 Esteatorreia pancreatica'),
  ('K904', 'Má-absorção devida a intolerância não classificada em outra parte', 'K90.4 Ma-absorcao dev intolerancia NCOP'),
  ('K908', 'Outras formas de má-absorção intestinal', 'K90.8 Outr form de ma-absorcao intestinal'),
  ('K909', 'Má-absorção intestinal, sem outra especificação', 'K90.9 Ma-absorcao intestinal SOE'),
  ('K91', 'Transtornos do aparelho digestivo pós-procedimentos, não classificados em outra parte', 'K91 Transt do aparelho digestivo pos-proced NCOP'),
  ('K910', 'Vômitos pós-cirurgia gastrointestinal', 'K91.0 Vomitos pos-cirurgia gastrointestinal'),
  ('K911', 'Síndromes pós-cirurgia gástrica', 'K91.1 Sindr pos-cirurgia gastrica'),
  ('K912', 'Má-absorção pós-cirúrgica não classificada em outra parte', 'K91.2 Ma-absorcao pos-cirurgica NCOP'),
  ('K913', 'Obstrução intestinal pós-operatória', 'K91.3 Obstrucao intestinal pos-operatoria'),
  ('K914', 'Mau funcionamento de colostomia e enterostomia', 'K91.4 Mau funcionamento colostomia e enterostomia'),
  ('K915', 'Síndrome pós-colecistectomia', 'K91.5 Sindr pos-colecistectomia'),
  ('K918', 'Outros transtornos do aparelho digestivo, pós-cirúrgicos, não classificados em outra parte', 'K91.8 Outr transt aparelho digest pos-cirurg NCOP'),
  ('K919', 'Transtorno do aparelho digestivo pós procedimento', 'K91.9 Transt do aparelho digestivo pos proced'),
  ('K92', 'Outras doenças do aparelho digestivo', 'K92 Outr doenc do aparelho digestivo'),
  ('K920', 'Hematêmese', 'K92.0 Hematemese'),
  ('K921', 'Melena', 'K92.1 Melena'),
  ('K922', 'Hemorragia gastrointestinal, sem outra especificação', 'K92.2 Hemorragia gastrointestinal SOE'),
  ('K928', 'Outras doenças especificadas do aparelho digestivo', 'K92.8 Outr doenc espec do aparelho digestivo'),
  ('K929', 'Doença do aparelho digestivo, sem outra especificação', 'K92.9 Doenc do aparelho digestivo SOE'),
  ('K93', 'Transtornos de outros órgãos digestivos em doenças classificadas em outra parte', 'K93 Transt de outr orgaos digestivos doenc COP'),
  ('K930', 'Transtornos devido a tuberculose do intestino, do peritônio e dos gânglios do mesentério', 'K93.0 Transt dev tuberc intest perit gangl mesent'),
  ('K931', 'Megacólon na doença de Chagas', 'K93.1 Megacolon na doenc de Chagas'),
  ('K938', 'Transtornos de outros órgãos digestivos especificados em doenças classificadas em outra parte', 'K93.8 Transt outr org digestivos espec doenc COP');
