INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('D00', 'Carcinoma in situ da cavidade oral, do esôfago e do estômago', 'D00 Carcinoma in situ cav oral esofago estomago'),
  ('D000', 'Carcinoma in situ dos lábios, cavidade oral e faringe', 'D00.0 Labios cavidade oral e faringe'),
  ('D001', 'Carcinoma in situ do esôfago', 'D00.1 Esofago'),
  ('D002', 'Carcinoma in situ do estômago', 'D00.2 Estomago'),
  ('D01', 'Carcinoma in situ de outros órgãos digestivos', 'D01 Carcinoma in situ de outr orgaos digestivos'),
  ('D010', 'Carcinoma in situ do cólon', 'D01.0 Colon'),
  ('D011', 'Carcinoma in situ da junção retossigmóide', 'D01.1 Juncao retossigmoide'),
  ('D012', 'Carcinoma in situ do reto', 'D01.2 Reto'),
  ('D013', 'Carcinoma in situ do ânus e canal anal', 'D01.3 Anus e canal anal'),
  ('D014', 'Carcinoma in situ de outras partes do intestino e as não especificadas', 'D01.4 Outr partes do intestino e as NE'),
  ('D015', 'Carcinoma in situ do fígado, vesícula biliar e vias biliares', 'D01.5 Figado vesicula biliar e vias biliares'),
  ('D017', 'Carcinoma in situ de outros órgãos especificados do aparelho digestivo', 'D01.7 Outr orgaos espec do aparelho digestivo'),
  ('D019', 'Carcinoma in situ de órgãos digestivos, não especificado', 'D01.9 Orgaos digestivos NE'),
  ('D02', 'Carcinoma in situ do ouvido médio e do aparelho respiratório', 'D02 Carcinoma in situ ouvido medio e ap respirat'),
  ('D020', 'Carcinoma in situ da laringe', 'D02.0 Laringe'),
  ('D021', 'Carcinoma in situ da traquéia', 'D02.1 Traqueia'),
  ('D022', 'Carcinoma in situ dos brônquios e pulmões', 'D02.2 Bronquios e pulmoes'),
  ('D023', 'Carcinoma in situ de outras partes do aparelho respiratório', 'D02.3 Outr partes do aparelho respirat'),
  ('D029', 'Carcinoma in situ do aparelho respiratório, não especificado', 'D02.9 Aparelho respirat NE'),
  ('D03', 'Melanoma in situ', 'D03 Melanoma in situ'),
  ('D030', 'Melanoma in situ do lábio', 'D03.0 Melanoma in situ do labio'),
  ('D031', 'Melanoma in situ da pálpebra, incluindo o canto', 'D03.1 Melanoma in situ da palpebra incl o canto'),
  ('D032', 'Melanoma in situ da orelha e do conduto auditivo externo', 'D03.2 Melanoma in situ orelha e conduto audit ext'),
  ('D033', 'Melanoma in situ de outras partes, e de partes não especificadas da face', 'D03.3 Melanoma in situ outr partes e NE da face'),
  ('D034', 'Melanoma in situ do couro cabeludo e do pescoço', 'D03.4 Melanoma in situ couro cabeludo e pescoco'),
  ('D035', 'Melanoma in situ do tronco', 'D03.5 Melanoma in situ do tronco'),
  ('D036', 'Melanoma in situ dos membros superiores, incluindo ombro', 'D03.6 Melanoma in situ membros super incl ombro'),
  ('D037', 'Melanoma in situ dos membros inferiores, incluindo quadril', 'D03.7 Melanoma in situ membros infer incl quadril'),
  ('D038', 'Melanoma in situ de outras localizações', 'D03.8 Melanoma in situ de outr localiz'),
  ('D039', 'Melanoma in situ, não especificado', 'D03.9 Melanoma in situ NE'),
  ('D04', 'Carcinoma in situ da pele', 'D04 Carcinoma in situ da pele'),
  ('D040', 'Carcinoma in situ da pele do lábio', 'D04.0 Pele do labio'),
  ('D041', 'Carcinoma in situ da pele da pálpebra, incluindo o canto', 'D04.1 Pele da palpebra incl o canto'),
  ('D042', 'Carcinoma in situ da pele da orelha e do conduto auditivo externo', 'D04.2 Pele da orelha e do conduto auditivo externo'),
  ('D043', 'Carcinoma in situ da pele de outras partes e de partes não especificadas da face', 'D04.3 Pele de outr partes e de partes NE da face'),
  ('D044', 'Carcinoma in situ da pele do couro cabeludo e do pescoço', 'D04.4 Pele do couro cabeludo e do pescoco'),
  ('D045', 'Carcinoma in situ da pele do tronco', 'D04.5 Pele do tronco'),
  ('D046', 'Carcinoma in situ da pele dos membros superiores, incluindo ombro', 'D04.6 Pele dos membros super incl ombro'),
  ('D047', 'Carcinoma in situ da pele dos membros inferiores, incluindo quadril', 'D04.7 Pele dos membros infer incl quadril'),
  ('D048', 'Carcinoma in situ da pele de outras localizações', 'D04.8 Pele de outr localiz'),
  ('D049', 'Carcinoma in situ da pele, não especificada', 'D04.9 Pele NE'),
  ('D05', 'Carcinoma in situ da mama', 'D05 Carcinoma in situ da mama'),
  ('D050', 'Carcinoma lobular in situ', 'D05.0 Carcinoma lobular in situ'),
  ('D051', 'Carcinoma intraductal in situ', 'D05.1 Carcinoma intraductal in situ'),
  ('D057', 'Outros carcinomas in situ', 'D05.7 Outr carcinomas in situ'),
  ('D059', 'Carcinoma in situ da mama, não especificado', 'D05.9 Carcinoma in situ da mama NE'),
  ('D06', 'Carcinoma in situ do colo do útero (cérvix)', 'D06 Carcinoma in situ do colo do utero'),
  ('D060', 'Carcinoma in situ do endocérvix', 'D06.0 Endocervix'),
  ('D061', 'Carcinoma in situ do exocérvix', 'D06.1 Exocervix'),
  ('D067', 'Carcinoma in situ de outras partes do colo do útero', 'D06.7 Outr partes do colo do utero'),
  ('D069', 'Carcinoma in situ do colo do útero, não especificado', 'D06.9 Colo do utero NE'),
  ('D07', 'Carcinoma in situ de outros órgãos genitais e dos não especificados', 'D07 Carcinoma in situ outr orgaos genitais e NE'),
  ('D070', 'Carcinoma in situ do endométrio', 'D07.0 Endometrio'),
  ('D071', 'Carcinoma in situ da vulva', 'D07.1 Vulva'),
  ('D072', 'Carcinoma in situ da vagina', 'D07.2 Vagina'),
  ('D073', 'Carcinoma in situ de outros órgãos genitais femininos e os não especificados', 'D07.3 Outr orgaos genitais femin e os NE'),
  ('D074', 'Carcinoma in situ do pênis', 'D07.4 Penis'),
  ('D075', 'Carcinoma in situ da próstata', 'D07.5 Prostata'),
  ('D076', 'Carcinoma in situ de outros órgãos genitais masculinos e os não especificados', 'D07.6 Outr orgaos genitais masc e os NE'),
  ('D09', 'Carcinoma in situ de outras localizações e das não especificadas', 'D09 Carcinoma in situ de outr localiz e das NE'),
  ('D090', 'Carcinoma in situ da bexiga', 'D09.0 Bexiga'),
  ('D091', 'Carcinoma in situ de outros órgãos urinários e os não especificados', 'D09.1 Outr orgaos urinarios e os NE'),
  ('D092', 'Carcinoma in situ do olho', 'D09.2 Olho'),
  ('D093', 'Carcinoma in situ da tireóide e de outras glândulas endócrinas', 'D09.3 Tireoide e de outr gland endocrinas'),
  ('D097', 'Carcinoma in situ de outras localizações especificadas', 'D09.7 Carcinoma in situ de outr localiz espec'),
  ('D099', 'Carcinoma in situ, não especificado', 'D09.9 Carcinoma in situ NE'),
  ('D10', 'Neoplasia benigna da boca e da faringe', 'D10 Neopl benig da boca e da faringe'),
  ('D100', 'Neoplasia benigna dos lábios', 'D10.0 Labios'),
  ('D101', 'Neoplasia benigna da língua', 'D10.1 Lingua'),
  ('D102', 'Neoplasia benigna do assoalho da boca', 'D10.2 Assoalho da boca'),
  ('D103', 'Neoplasia benigna de outras partes da boca e as não especificadas', 'D10.3 Outr partes da boca e as NE'),
  ('D104', 'Neoplasia benigna da amígdala', 'D10.4 Amigdala'),
  ('D105', 'Neoplasia benigna de outras partes da orofaringe', 'D10.5 Outr partes da orofaringe'),
  ('D106', 'Neoplasia benigna da nasofaringe', 'D10.6 Nasofaringe'),
  ('D107', 'Neoplasia benigna da hipofaringe', 'D10.7 Hipofaringe'),
  ('D109', 'Neoplasia benigna da faringe, não especificada', 'D10.9 Faringe NE'),
  ('D11', 'Neoplasia benigna de glândulas salivares maiores', 'D11 Neopl benig de gland salivares maiores'),
  ('D110', 'Neoplasia benigna da glândula parótida', 'D11.0 Gland parotida'),
  ('D117', 'Neoplasia benigna de outras glândulas salivares maiores', 'D11.7 Outr gland salivares maiores'),
  ('D119', 'Neoplasia benigna da glândula salivar maior, não especificada', 'D11.9 Gland salivar maior NE'),
  ('D12', 'Neoplasia benigna do cólon, reto, canal anal e ânus', 'D12 Neopl benig do colon reto canal anal e anus'),
  ('D120', 'Neoplasia benigna do ceco', 'D12.0 Ceco'),
  ('D121', 'Neoplasia benigna do apêndice (vermiforme)', 'D12.1 Apendice'),
  ('D122', 'Neoplasia benigna do cólon ascendente', 'D12.2 Colon ascendente'),
  ('D123', 'Neoplasia benigna do cólon transverso', 'D12.3 Colon transverso'),
  ('D124', 'Neoplasia benigna do cólon descendente', 'D12.4 Colon descendente'),
  ('D125', 'Neoplasia benigna do cólon sigmóide', 'D12.5 Colon sigmoide'),
  ('D126', 'Neoplasia benigna do cólon, não especificada', 'D12.6 Colon NE'),
  ('D127', 'Neoplasia benigna da junção retossigmóide', 'D12.7 Juncao retossigmoide'),
  ('D128', 'Neoplasia benigna do reto', 'D12.8 Reto'),
  ('D129', 'Neoplasia benigna do canal anal e ânus', 'D12.9 Canal anal e anus'),
  ('D13', 'Neoplasia benigna de outras partes e de partes mal definidas do aparelho digestivo', 'D13 Neopl benig outr part e mal def ap digestivo'),
  ('D130', 'Neoplasia benigna do esôfago', 'D13.0 Esofago'),
  ('D131', 'Neoplasia benigna do estômago', 'D13.1 Estomago'),
  ('D132', 'Neoplasia benigna do duodeno', 'D13.2 Duodeno'),
  ('D133', 'Neoplasia benigna de outras partes e partes não especificadas do intestino delgado', 'D13.3 Outr partes e partes NE do intestino delgado'),
  ('D134', 'Neoplasia benigna do fígado', 'D13.4 Figado'),
  ('D135', 'Neoplasia benigna das vias biliares extra-hepáticas', 'D13.5 Vias biliares extra-hepaticas'),
  ('D136', 'Neoplasia benigna do pâncreas', 'D13.6 Pancreas'),
  ('D137', 'Neoplasia benigna do pâncreas endócrino', 'D13.7 Pancreas endocrino'),
  ('D139', 'Neoplasia benigna de localizações mal definidas do aparelho digestivo', 'D13.9 Localiz mal definidas do aparelho digestivo'),
  ('D14', 'Neoplasia benigna do ouvido médio e do aparelho respiratório', 'D14 Neopl benig ouvido medio e aparelho respirat'),
  ('D140', 'Neoplasia benigna do ouvido médio, cavidade nasal e seios paranasais', 'D14.0 Ouvido medio cav nasal e seios paranasais'),
  ('D141', 'Neoplasia benigna da laringe', 'D14.1 Laringe'),
  ('D142', 'Neoplasia benigna da traquéia', 'D14.2 Traqueia'),
  ('D143', 'Neoplasia benigna dos brônquios e pulmão', 'D14.3 Bronquios e pulmao'),
  ('D144', 'Neoplasia benigna do aparelho respiratório, não especificado', 'D14.4 Aparelho respirat NE'),
  ('D15', 'Neoplasia benigna de outros órgãos intratorácicos e dos não especificados', 'D15 Neopl benig outr orgaos intratoracicos e NE'),
  ('D150', 'Neoplasia benigna do timo', 'D15.0 Timo'),
  ('D151', 'Neoplasia benigna do coração', 'D15.1 Coracao'),
  ('D152', 'Neoplasia benigna do mediastino', 'D15.2 Mediastino'),
  ('D157', 'Neoplasia benigna de outros órgãos intratorácicos especificados', 'D15.7 Outr orgaos intratoracicos espec'),
  ('D159', 'Neoplasia benigna de órgão intratorácico, não especificado', 'D15.9 Orgao intratoracico NE'),
  ('D16', 'Neoplasia benigna de osso e de cartilagem articular', 'D16 Neopl benig de osso e cartilagem articular'),
  ('D160', 'Neoplasia benigna da omoplata (escápula) e ossos longos dos membros superiores', 'D16.0 Omoplata e ossos longos dos membros super'),
  ('D161', 'Neoplasia benigna dos ossos curtos dos membros superiores', 'D16.1 Ossos curtos dos membros super'),
  ('D162', 'Neoplasia benigna dos ossos longos dos membros inferiores', 'D16.2 Ossos longos dos membros infer'),
  ('D163', 'Neoplasia benigna dos ossos curtos dos membros inferiores', 'D16.3 Ossos curtos dos membros infer'),
  ('D164', 'Neoplasia benigna dos ossos do crânio e da face', 'D16.4 Ossos do cranio e da face'),
  ('D165', 'Neoplasia benigna do osso da mandíbula', 'D16.5 Osso da mandibula'),
  ('D166', 'Neoplasia benigna da coluna vertebral', 'D16.6 Coluna vertebral'),
  ('D167', 'Neoplasia benigna das costelas, do esterno e da clavícula', 'D16.7 Costelas do esterno e da clavicula'),
  ('D168', 'Neoplasia benigna dos ossos pélvicos, sacro e cóccix', 'D16.8 Ossos pelvicos sacro e coccix'),
  ('D169', 'Neoplasia benigna do osso e cartilagem articular, não especificado', 'D16.9 Osso e cartilagem articular NE'),
  ('D17', 'Neoplasia lipomatosa benigna', 'D17 Neopl lipomatosa benig'),
  ('D170', 'Neoplasia lipomatosa benigna da pele e do tecido subcutâneo da cabeça, face e pescoço', 'D17.0 Neop lipom ben pele tec subcut cab face pesc'),
  ('D171', 'Neoplasia lipomatosa benigna da pele e tecido subcutâneo do tronco', 'D17.1 Neopl lipomatosa benig pele tec subcut tronc'),
  ('D172', 'Neoplasia lipomatosa benigna da pele e tecido subcutâneo dos membros', 'D17.2 Neopl lipomatosa benig pele tec subcut membr'),
  ('D173', 'Neoplasia lipomatosa benigna da pele e tecido subcutâneo de outras localizações e de localizações não especificadas', 'D17.3 Neopl lip benig pele tec subc outr loc e NE'),
  ('D174', 'Neoplasia lipomatosa benigna de órgãos intratorácicos', 'D17.4 Neopl lipomatosa benig orgaos intratoracicos'),
  ('D175', 'Neoplasia lipomatosa benigna de órgãos intra-abdominais', 'D17.5 Neopl lipomatosa benig orgaos intra-abdomin'),
  ('D176', 'Neoplasia lipomatosa benigna do cordão espermático', 'D17.6 Neopl lipomatosa benig do cordao espermatico'),
  ('D177', 'Neoplasia lipomatosa benigna de outras localizações', 'D17.7 Neoplasia lipomatosa benigna de outr localiz'),
  ('D179', 'Neoplasia lipomatosa benigna de localização não especificada', 'D17.9 Neoplasia lipomatosa benigna de localiz NE'),
  ('D18', 'Hemangioma e linfangioma de qualquer localização', 'D18 Hemangioma e linfangioma de qualquer localiz'),
  ('D180', 'Hemangioma de qualquer localização', 'D18.0 Hemangioma de qualquer localiz'),
  ('D181', 'Linfangioma de qualquer localização', 'D18.1 Linfangioma de qualquer localiz'),
  ('D19', 'Neoplasia benigna de tecido mesotelial', 'D19 Neopl benig de tec mesotelial'),
  ('D190', 'Neoplasia benigna do tecido mesotelial da pleura', 'D19.0 Tec mesotelial da pleura'),
  ('D191', 'Neoplasia benigna do tecido mesotelial do peritônio', 'D19.1 Tec mesotelial do peritonio'),
  ('D197', 'Neoplasia benigna do tecido mesotelial de outras localizações', 'D19.7 Tec mesotelial de outr localiz'),
  ('D199', 'Neoplasia benigna do tecido mesotelial, não especificado', 'D19.9 Tec mesotelial NE'),
  ('D20', 'Neoplasia benigna de tecido mole do retroperitônio e do peritônio', 'D20 Neopl benig tec mole retro- e peritonio'),
  ('D200', 'Neoplasia benigna do retroperitônio', 'D20.0 Retroperitonio'),
  ('D201', 'Neoplasia benigna do peritônio', 'D20.1 Peritonio'),
  ('D21', 'Outras neoplasias benignas do tecido conjuntivo e de outros tecidos moles', 'D21 Outr neopl benig tec conj e outr tec moles'),
  ('D210', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles da cabeça, face e pescoço', 'D21.0 Tec conj e outr tec moles cabeca face e pesc'),
  ('D211', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles dos membros superiores, incluindo ombro', 'D21.1 Tec conj e out tec moles membr sup incl ombr'),
  ('D212', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles dos membros inferiores, incluindo quadril', 'D21.2 Tec conj e out tec moles membr inf incl quad'),
  ('D213', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles do tórax', 'D21.3 Tec conjuntivo e outr tec moles do torax'),
  ('D214', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles do abdome', 'D21.4 Tec conjuntivo e outr tec moles do abdome'),
  ('D215', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles da pelve', 'D21.5 Tec conjuntivo e outr tec moles da pelve'),
  ('D216', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles do tronco, não especificado', 'D21.6 Tec conjuntivo e outr tec moles do tronco NE'),
  ('D219', 'Neoplasia benigna do tecido conjuntivo e outros tecidos moles, sem outra especificação', 'D21.9 Tec conjuntivo e outr tec moles s/outr espec'),
  ('D22', 'Nevos melanocíticos', 'D22 Nevos melanociticos'),
  ('D220', 'Nevo melanocítico do lábio', 'D22.0 Nevo melanocitico do labio'),
  ('D221', 'Nevo melanocítico da pálpebra, incluindo o canto', 'D22.1 Nevo melanocitico da palpebra incl o canto'),
  ('D222', 'Nevo melanocítico da orelha e do conduto auditivo externo', 'D22.2 Nevo melanocitico orelha e cond auditivo ext'),
  ('D223', 'Nevo melanocítico de outras partes e de partes não especificadas da face', 'D22.3 Nevo melanocitico outr partes e NE da face'),
  ('D224', 'Nevo melanocítico do couro cabeludo e do pescoço', 'D22.4 Nevo melanocitico couro cabeludo e pescoco'),
  ('D225', 'Nevo melanocítico do tronco', 'D22.5 Nevo melanocitico do tronco'),
  ('D226', 'Nevo melanocítico dos membros superiores, incluindo ombro', 'D22.6 Nevo melanocitico membros super incl ombro'),
  ('D227', 'Nevo melanocítico dos membros inferiores, incluindo quadril', 'D22.7 Nevo melanocitico membros infer incl quadril'),
  ('D229', 'Nevo melanocítico, não especificado', 'D22.9 Nevo melanocitico NE'),
  ('D23', 'Outras neoplasias benignas da pele', 'D23 Outr neopl benig da pele'),
  ('D230', 'Neoplasia benigna da pele dos lábios', 'D23.0 Pele dos labios'),
  ('D231', 'Neoplasia benigna da pele da pálpebra, incluindo o canto', 'D23.1 Pele da palpebra incl o canto'),
  ('D232', 'Neoplasia benigna da pele da orelha e do conduto auditivo externo', 'D23.2 Pele da orelha e do conduto auditivo externo'),
  ('D233', 'Neoplasia benigna da pele de outras partes e de partes não especificadas da face', 'D23.3 Pele de outr partes e de partes NE da face'),
  ('D234', 'Neoplasia benigna da pele do couro cabeludo e do pescoço', 'D23.4 Pele do couro cabeludo e do pescoco'),
  ('D235', 'Neoplasia benigna da pele do tronco', 'D23.5 Pele do tronco'),
  ('D236', 'Neoplasia benigna da pele dos membros superiores, incluindo o ombro', 'D23.6 Pele dos membros super incl o ombro'),
  ('D237', 'Neoplasia benigna da pele dos membros inferiores, incluindo o quadril', 'D23.7 Pele dos membros infer incl o quadril'),
  ('D239', 'Neoplasia benigna da pele, não especificada', 'D23.9 Pele NE'),
  ('D24', 'Neoplasia benigna da mama', 'D24 Neopl benig da mama'),
  ('D24', 'Neoplasia benigna da mama', 'D24 Neopl benig da mama'),
  ('D25', 'Leiomioma do útero', 'D25 Leiomioma do utero'),
  ('D250', 'Leiomioma submucoso do útero', 'D25.0 Leiomioma submucoso do utero'),
  ('D251', 'Leiomioma intramural do útero', 'D25.1 Leiomioma intramural do utero'),
  ('D252', 'Leiomioma subseroso do útero', 'D25.2 Leiomioma subseroso do utero'),
  ('D259', 'Leiomioma do útero, não especificado', 'D25.9 Leiomioma do utero NE'),
  ('D26', 'Outras neoplasias benignas do útero', 'D26 Outr neopl benig do utero'),
  ('D260', 'Neoplasia benigna do colo do útero', 'D26.0 Colo do utero'),
  ('D261', 'Neoplasia benigna do corpo do útero', 'D26.1 Corpo do utero'),
  ('D267', 'Neoplasia benigna de outras partes do útero', 'D26.7 Outr partes do utero'),
  ('D269', 'Neoplasia benigna do útero, não especificado', 'D26.9 Utero NE'),
  ('D27', 'Neoplasia benigna do ovário', 'D27 Neopl benig do ovario'),
  ('D27', 'Neoplasia benigna do ovário', 'D27 Neopl benig do ovario'),
  ('D28', 'Neoplasia benigna de outros órgãos genitais femininos e de órgãos não especificados', 'D28 Neopl benig outr org genitais femin e NE'),
  ('D280', 'Neoplasia benigna da vulva', 'D28.0 Vulva'),
  ('D281', 'Neoplasia benigna da vagina', 'D28.1 Vagina'),
  ('D282', 'Neoplasia benigna das trompas e ligamentos uterinos', 'D28.2 Trompas e ligamentos uterinos'),
  ('D287', 'Neoplasia benigna de outros órgãos genitais femininos especificados', 'D28.7 Outr orgaos genitais femin espec'),
  ('D289', 'Neoplasia benigna de órgão genital feminino, não especificado', 'D28.9 Orgao genital femin NE'),
  ('D29', 'Neoplasia benigna dos órgãos genitais masculinos', 'D29 Neopl benig dos orgaos genitais masc'),
  ('D290', 'Neoplasia benigna do pênis', 'D29.0 Penis'),
  ('D291', 'Neoplasia benigna da próstata', 'D29.1 Prostata'),
  ('D292', 'Neoplasia benigna dos testículos', 'D29.2 Testiculos'),
  ('D293', 'Neoplasia benigna do epidídimo', 'D29.3 Epididimo'),
  ('D294', 'Neoplasia benigna do escroto', 'D29.4 Escroto'),
  ('D297', 'Neoplasia benigna de outros órgãos genitais masculinos', 'D29.7 Outr orgaos genitais masc'),
  ('D299', 'Neoplasia benigna de órgão genital masculino, não especificado', 'D29.9 Orgao genital masc NE'),
  ('D30', 'Neoplasia benigna dos órgãos urinários', 'D30 Neopl benig dos orgaos urinarios'),
  ('D300', 'Neoplasia benigna do rim', 'D30.0 Rim'),
  ('D301', 'Neoplasia benigna da pelve renal', 'D30.1 Pelve renal'),
  ('D302', 'Neoplasia benigna do ureter', 'D30.2 Ureter'),
  ('D303', 'Neoplasia benigna da bexiga', 'D30.3 Bexiga'),
  ('D304', 'Neoplasia benigna da uretra', 'D30.4 Uretra'),
  ('D307', 'Neoplasia benigna de outros órgãos urinários', 'D30.7 Outr orgaos urinarios'),
  ('D309', 'Neoplasia benigna de órgão urinário, não especificado', 'D30.9 Orgao urinario NE'),
  ('D31', 'Neoplasia benigna do olho e anexos', 'D31 Neopl benig do olho e anexos'),
  ('D310', 'Neoplasia benigna da conjuntiva', 'D31.0 Conjuntiva'),
  ('D311', 'Neoplasia benigna da córnea', 'D31.1 Cornea'),
  ('D312', 'Neoplasia benigna da retina', 'D31.2 Retina'),
  ('D313', 'Neoplasia benigna da coróide', 'D31.3 Coroide'),
  ('D314', 'Neoplasia benigna do corpo ciliar', 'D31.4 Corpo ciliar'),
  ('D315', 'Neoplasia benigna das glândulas e dos canais lacrimais', 'D31.5 Gland e dos canais lacrimais'),
  ('D316', 'Neoplasia benigna da órbita, não especificada', 'D31.6 Orbita NE'),
  ('D319', 'Neoplasia benigna do olho, não especificado', 'D31.9 Olho NE'),
  ('D32', 'Neoplasia benigna das meninges', 'D32 Neopl benig das meninges'),
  ('D320', 'Neoplasia benigna das meninges cerebrais', 'D32.0 Meninges cerebrais'),
  ('D321', 'Neoplasia benigna das meninges espinhais', 'D32.1 Meninges espinhais'),
  ('D329', 'Neoplasia benigna das meninges, não especificada', 'D32.9 Meninges NE'),
  ('D33', 'Neoplasia benigna do encéfalo e de outras partes do sistema nervoso central', 'D33 Neopl benig encef e out part sist nerv centr'),
  ('D330', 'Neoplasia benigna do encéfalo, supratentorial', 'D33.0 Encefalo supratentorial'),
  ('D331', 'Neoplasia benigna do encéfalo, infratentorial', 'D33.1 Encefalo infratentorial'),
  ('D332', 'Neoplasia benigna do encéfalo, não especificado', 'D33.2 Encefalo NE'),
  ('D333', 'Neoplasia benigna dos nervos cranianos', 'D33.3 Nervos cranianos'),
  ('D334', 'Neoplasia benigna da medula espinhal', 'D33.4 Medula espinhal'),
  ('D337', 'Neoplasia benigna de outras partes especificadas do sistema nervoso central', 'D33.7 Outr partes espec do sist nervoso central'),
  ('D339', 'Neoplasia benigna do sistema nervoso central, não especificado', 'D33.9 Sist nervoso central NE'),
  ('D34', 'Neoplasia benigna da glândula tireóide', 'D34 Neopl benig da gland tireoide'),
  ('D34', 'Neoplasia benigna da glândula tireóide', 'D34 Neopl benig da gland tireoide'),
  ('D35', 'Neoplasia benigna de outras glândulas endócrinas e das não especificadas', 'D35 Neopl benig de outr gland endocrinas e NE'),
  ('D350', 'Neoplasia benigna da glândula supra-renal (adrenal)', 'D35.0 Gland supra-renal'),
  ('D351', 'Neoplasia benigna da glândula paratireóide', 'D35.1 Gland paratireoide'),
  ('D352', 'Neoplasia benigna da glândula hipófise (pituitária)', 'D35.2 Gland hipofise'),
  ('D353', 'Neoplasia benigna do conduto craniofaríngeo', 'D35.3 Conduto craniofaringeo'),
  ('D354', 'Neoplasia benigna da glândula pineal', 'D35.4 Gland pineal'),
  ('D355', 'Neoplasia benigna do corpo carotídeo', 'D35.5 Corpo carotideo'),
  ('D356', 'Neoplasia benigna dos corpos aórticos e outros paragânglios', 'D35.6 Corpos aorticos e outr paraganglios'),
  ('D357', 'Neoplasia benigna de outras glândulas endócrinas especificadas', 'D35.7 Outr gland endocrinas espec'),
  ('D358', 'Neoplasia benigna com comprometimento pluriglandular', 'D35.8 Compr pluriglandular'),
  ('D359', 'Neoplasia benigna de glândula endócrina, não especificada', 'D35.9 Gland endocrina NE'),
  ('D36', 'Neoplasia benigna de outras localizações e de localizações não especificadas', 'D36 Neopl benig de outr localiz e de localiz NE'),
  ('D360', 'Neoplasia benigna dos gânglios linfáticos (linfonodos)', 'D36.0 Ganglios linfaticos'),
  ('D361', 'Neoplasia benigna dos nervos periféricos e sistema nervoso autônomo', 'D36.1 Nervos perifericos e sist nervoso autonomo'),
  ('D367', 'Neoplasia benigna de outras localizações especificadas', 'D36.7 Outr localiz espec'),
  ('D369', 'Neoplasia benigna de localização não especificada', 'D36.9 Neopl benig de localiz NE'),
  ('D37', 'Neoplasia de comportamento incerto ou desconhecido da cavidade oral e dos órgãos digestivos', 'D37 Neopl comp incerto/desc cav oral e org dig'),
  ('D370', 'Neoplasia de comportamento incerto ou desconhecido do lábio, cavidade oral e faringe', 'D37.0 Labio cavidade oral e faringe'),
  ('D371', 'Neoplasia de comportamento incerto ou desconhecido do estômago', 'D37.1 Estomago'),
  ('D372', 'Neoplasia de comportamento incerto ou desconhecido do intestino delgado', 'D37.2 Intestino delgado'),
  ('D373', 'Neoplasia de comportamento incerto ou desconhecido do apêndice', 'D37.3 Apendice'),
  ('D374', 'Neoplasia de comportamento incerto ou desconhecido dos cólons', 'D37.4 Colons'),
  ('D375', 'Neoplasia de comportamento incerto ou desconhecido do reto', 'D37.5 Reto'),
  ('D376', 'Neoplasia de comportamento incerto ou desconhecido do fígado, vesícula biliar e vias biliares', 'D37.6 Figado vesicula biliar e vias biliares'),
  ('D377', 'Neoplasia de comportamento incerto ou desconhecido de outros órgãos digestivos', 'D37.7 Outr orgaos digestivos'),
  ('D379', 'Neoplasia de comportamento incerto ou desconhecido de órgão digestivo, não especificado', 'D37.9 Orgao digestivo NE'),
  ('D38', 'Neoplasia de comportamento incerto ou desconhecido do ouvido médio e dos órgãos respiratórios e intratorácicos', 'D38 Neopl comp inc/desc ouv med org resp intrat'),
  ('D380', 'Neoplasia de comportamento incerto ou desconhecido da laringe', 'D38.0 Laringe'),
  ('D381', 'Neoplasia de comportamento incerto ou desconhecido da traquéia, brônquios e pulmão', 'D38.1 Traqueia bronquios e pulmao'),
  ('D382', 'Neoplasia de comportamento incerto ou desconhecido da pleura', 'D38.2 Pleura'),
  ('D383', 'Neoplasia de comportamento incerto ou desconhecido do mediastino', 'D38.3 Mediastino'),
  ('D384', 'Neoplasia de comportamento incerto ou desconhecido do timo', 'D38.4 Timo'),
  ('D385', 'Neoplasia de comportamento incerto ou desconhecido de outros órgãos respiratórios', 'D38.5 Outr orgaos respirat'),
  ('D386', 'Neoplasia de comportamento incerto ou desconhecido de órgão respiratório, não especificado', 'D38.6 Orgao respirat NE'),
  ('D39', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais femininos', 'D39 Neopl comp incerto/desconh org genitais fem'),
  ('D390', 'Neoplasia de comportamento incerto ou desconhecido do útero', 'D39.0 Utero'),
  ('D391', 'Neoplasia de comportamento incerto ou desconhecido do ovário', 'D39.1 Ovario'),
  ('D392', 'Neoplasia de comportamento incerto ou desconhecido da placenta', 'D39.2 Placenta'),
  ('D397', 'Neoplasia de comportamento incerto ou desconhecido de outros órgãos genitais femininos', 'D39.7 Outr orgaos genitais femin'),
  ('D399', 'Neoplasia de comportamento incerto ou desconhecido de órgão genital feminino, não especificado', 'D39.9 Orgao genital femin NE'),
  ('D40', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais masculinos', 'D40 Neopl comp incerto/desconh org genitais masc'),
  ('D400', 'Neoplasia de comportamento incerto ou desconhecido da próstata', 'D40.0 Prostata'),
  ('D401', 'Neoplasia de comportamento incerto ou desconhecido do testículo', 'D40.1 Testiculo'),
  ('D407', 'Neoplasia de comportamento incerto ou desconhecido de outros órgãos genitais masculinos', 'D40.7 Outr orgaos genitais masc'),
  ('D409', 'Neoplasia de comportamento incerto ou desconhecido de órgão genital masculino, não especificado', 'D40.9 Orgao genital masc NE'),
  ('D41', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos urinários', 'D41 Neopl comp incerto/desconh orgaos urinarios'),
  ('D410', 'Neoplasia de comportamento incerto ou desconhecido do rim', 'D41.0 Rim'),
  ('D411', 'Neoplasia de comportamento incerto ou desconhecido da pelve renal', 'D41.1 Pelve renal'),
  ('D412', 'Neoplasia de comportamento incerto ou desconhecido do ureter', 'D41.2 Ureter'),
  ('D413', 'Neoplasia de comportamento incerto ou desconhecido da uretra', 'D41.3 Uretra'),
  ('D414', 'Neoplasia de comportamento incerto ou desconhecido da bexiga', 'D41.4 Bexiga'),
  ('D417', 'Neoplasia de comportamento incerto ou desconhecido de outros órgãos urinários', 'D41.7 Outr orgaos urinarios'),
  ('D419', 'Neoplasia de comportamento incerto ou desconhecido de órgão urinário, não especificado', 'D41.9 Orgao urinario NE'),
  ('D42', 'Neoplasia de comportamento incerto ou desconhecido das meninges', 'D42 Neopl comp incerto/desconhecido meninges'),
  ('D420', 'Neoplasia de comportamento incerto ou desconhecido das meninges cerebrais', 'D42.0 Meninges cerebrais'),
  ('D421', 'Neoplasia de comportamento incerto ou desconhecido das meninges espinhais', 'D42.1 Meninges espinhais'),
  ('D429', 'Neoplasia de comportamento incerto ou desconhecido de meninges não especificadas', 'D42.9 Meninges NE'),
  ('D43', 'Neoplasia de comportamento incerto ou desconhecido do encéfalo e do sistema nervoso central', 'D43 Neopl comp inc/desc encefalo sist nerv centr'),
  ('D430', 'Neoplasia de comportamento incerto ou desconhecido do encéfalo, supratentorial', 'D43.0 Encefalo supratentorial'),
  ('D431', 'Neoplasia de comportamento incerto ou desconhecido do encéfalo, infratentorial', 'D43.1 Encefalo infratentorial'),
  ('D432', 'Neoplasia de comportamento incerto ou desconhecido do encéfalo, não especificado', 'D43.2 Encefalo NE'),
  ('D433', 'Neoplasia de comportamento incerto ou desconhecido dos nervos cranianos', 'D43.3 Nervos cranianos'),
  ('D434', 'Neoplasia de comportamento incerto ou desconhecido da medula espinhal', 'D43.4 Medula espinhal'),
  ('D437', 'Neoplasia de comportamento incerto ou desconhecido de outras partes do sistema nervoso central', 'D43.7 Outr partes do sist nervoso central'),
  ('D439', 'Neoplasia de comportamento incerto ou desconhecido do sistema nervoso central, não especificado', 'D43.9 Sist nervoso central NE'),
  ('D44', 'Neoplasia de comportamento incerto ou desconhecido das glândulas endócrinas', 'D44 Neopl comp incerto/desconh gland endocrinas'),
  ('D440', 'Neoplasia de comportamento incerto ou desconhecido da glândula tireóide', 'D44.0 Gland tireoide'),
  ('D441', 'Neoplasia de comportamento incerto ou desconhecido da glândula supra-renal (adrenal)', 'D44.1 Gland supra-renal'),
  ('D442', 'Neoplasia de comportamento incerto ou desconhecido da glândula paratireóide', 'D44.2 Gland paratireoide'),
  ('D443', 'Neoplasia de comportamento incerto ou desconhecido da glândula hipófise (pituitária)', 'D44.3 Gland hipofise'),
  ('D444', 'Neoplasia de comportamento incerto ou desconhecido do conduto craniofaríngeo', 'D44.4 Conduto craniofaringeo'),
  ('D445', 'Neoplasia de comportamento incerto ou desconhecido da glândula pineal', 'D44.5 Gland pineal'),
  ('D446', 'Neoplasia de comportamento incerto ou desconhecido do corpo carotídeo', 'D44.6 Corpo carotideo'),
  ('D447', 'Neoplasia de comportamento incerto ou desconhecido dos corpos aórticos e outros paragânglios', 'D44.7 Corpos aorticos e outr paraganglios'),
  ('D448', 'Neoplasia de comportamento incerto ou desconhecido com comprometimento pluriglandular', 'D44.8 Compr pluriglandular'),
  ('D449', 'Neoplasia de comportamento incerto ou desconhecido de glândula endócrina, não especificada', 'D44.9 Gland endocrina NE'),
  ('D45', 'Policitemia vera', 'D45 Policitemia vera'),
  ('D45', 'Policitemia vera', 'D45 Policitemia vera'),
  ('D46', 'Síndromes mielodisplásicas', 'D46 Sindr mielodisplasicas'),
  ('D460', 'Anemia refratária sem sideroblastos', 'D46.0 Anemia refrataria s/sideroblastos'),
  ('D461', 'Anemia refratária com sideroblastos', 'D46.1 Anemia refrataria c/sideroblastos'),
  ('D462', 'Anemia refratária com excesso de blastos', 'D46.2 Anemia refrataria c/excesso de blastos'),
  ('D463', 'Anemia refratária com excesso de blastos com transformação', 'D46.3 Anemia refrataria c/excesso blastos c/transf'),
  ('D464', 'Anemia refratária, não especificada', 'D46.4 Anemia refrataria NE'),
  ('D467', 'Outras síndromes mielodisplásicas', 'D46.7 Outr sindr mielodisplasicas'),
  ('D469', 'Síndrome mielodisplásica, não especificada', 'D46.9 Sindr mielodisplasica NE'),
  ('D47', 'Outras neoplasias de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos correlatos', 'D47 Out neop comp inc/des tec linf hemat tec cor'),
  ('D470', 'Tumores de comportamento incerto ou desconhecido de mastócitos e células histiocíticas', 'D47.0 Tum comp inc/desc mastocit celulas histiocit'),
  ('D471', 'Doença mieloproliferativa crônica', 'D47.1 Doenc mieloproliferativa cronica'),
  ('D472', 'Gamopatia monoclonal', 'D47.2 Gamopatia monoclonal'),
  ('D473', 'Trombocitemia essencial (hemorrágica)', 'D47.3 Trombocitemia essencial'),
  ('D477', 'Outras neoplasias especificadas de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos relacionados', 'D47.7 Out neop esp comp inc/des linf hemat tec rel'),
  ('D479', 'Neoplasia de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos correlatos, não especificada', 'D47.9 Neop comp inc/des tec linf hemat tec corr NE'),
  ('D48', 'Neoplasia de comportamento incerto ou desconhecido de outras localizações e de localizações não especificadas', 'D48 Neopl comp inc/desconh outr localiz e NE'),
  ('D480', 'Neoplasia de comportamento incerto ou desconhecido dos ossos e cartilagens articulares', 'D48.0 Ossos e cartilagens articulares'),
  ('D481', 'Neoplasia de comportamento incerto ou desconhecido do tecido conjuntivo e outros tecidos moles', 'D48.1 Tec conjuntivo e outr tec moles'),
  ('D482', 'Neoplasia de comportamento incerto ou desconhecido dos nervos periféricos e do sistema nervoso periférico', 'D48.2 Nervos perifericos e sist nervoso periferico'),
  ('D483', 'Neoplasia de comportamento incerto ou desconhecido do retroperitônio', 'D48.3 Retroperitonio'),
  ('D484', 'Neoplasia de comportamento incerto ou desconhecido do peritônio', 'D48.4 Peritonio'),
  ('D485', 'Neoplasia de comportamento incerto ou desconhecido da pele', 'D48.5 Pele'),
  ('D486', 'Neoplasia de comportamento incerto ou desconhecido da mama', 'D48.6 Mama'),
  ('D487', 'Neoplasia de comportamento incerto ou desconhecido de outras localizações especificadas', 'D48.7 Outr localiz espec'),
  ('D489', 'Neoplasia de comportamento incerto ou desconhecido sem outra especificação', 'D48.9 Neopl comp incerto/desconhecido s/outr espec'),
  ('D50', 'Anemia por deficiência de ferro', 'D50 Anemia p/defic de ferro'),
  ('D500', 'Anemia por deficiência de ferro secundária à perda de sangue (crônica)', 'D50.0 Anemia p/defic ferro secund perda de sangue'),
  ('D501', 'Disfagia sideropênica', 'D50.1 Disfagia sideropenica'),
  ('D508', 'Outras anemias por deficiência de ferro', 'D50.8 Outr anemias p/defic de ferro'),
  ('D509', 'Anemia por deficiência de ferro não especificada', 'D50.9 Anemia p/defic de ferro NE'),
  ('D51', 'Anemia por deficiência de vitamina B12', 'D51 Anemia p/defic de vitamina B12'),
  ('D510', 'Anemia por deficiência de vitamina B12 devida à deficiência de fator intrínseco', 'D51.0 Anemia p/defic vit B12 dev defic fat intrins'),
  ('D511', 'Anemia por deficiência de vitamina B12 devida à má-absorção seletiva de vitamina B12 com proteinúria', 'D51.1 Anemia def vit B12 ma-abs sel vit B12 c/prot'),
  ('D512', 'Deficiência de transcobalamina II', 'D51.2 Defic de transcobalamina II'),
  ('D513', 'Outras anemias por deficiência de vitamina B12 na dieta', 'D51.3 Outr anemias p/defic vitamina B12 na dieta'),
  ('D518', 'Outras anemias por deficiência de vitamina B12', 'D51.8 Outr anemias p/defic de vitamina B12'),
  ('D519', 'Anemia por deficiência de vitamina B12 não especificada', 'D51.9 Anemia p/defic de vitamina B12 NE'),
  ('D52', 'Anemia por deficiência de folato', 'D52 Anemia p/defic de folato'),
  ('D520', 'Anemia por deficiência de folato na dieta', 'D52.0 Anemia p/defic de folato na dieta'),
  ('D521', 'Anemia por deficiência de folato induzida por drogas', 'D52.1 Anemia p/defic de folato induz p/drogas'),
  ('D528', 'Outras anemias por deficiência de folato', 'D52.8 Outr anemias p/defic de folato'),
  ('D529', 'Anemia por deficiência de folato não especificada', 'D52.9 Anemia p/defic de folato NE'),
  ('D53', 'Outras anemias nutricionais', 'D53 Outr anemias nutricionais'),
  ('D530', 'Anemia por deficiência de proteínas', 'D53.0 Anemia p/defic de proteinas'),
  ('D531', 'Outras anemias megaloblásticas não classificadas em outras partes', 'D53.1 Outr anemias megaloblasticas NCOP'),
  ('D532', 'Anemia escorbútica', 'D53.2 Anemia escorbutica'),
  ('D538', 'Outras anemias nutricionais especificadas', 'D53.8 Outr anemias nutricionais espec'),
  ('D539', 'Anemia nutricional não especificada', 'D53.9 Anemia nutricional NE'),
  ('D55', 'Anemia devida a transtornos enzimáticos', 'D55 Anemia dev transt enzimaticos'),
  ('D550', 'Anemia devida à deficiência de glicose-6-fosfato-desidrogenase (G-6-PD)', 'D55.0 Anemia dev defic glicose-6-fosfato-desidrog'),
  ('D551', 'Anemia devida a outros transtornos do metabolismo do glutation', 'D55.1 Anemia dev outr transt metabolismo glutation'),
  ('D552', 'Anemia devida a transtornos das enzimas glicolíticas', 'D55.2 Anemia dev transt das enzimas glicoliticas'),
  ('D553', 'Anemia devida a transtornos do metabolismo de nucleotídios', 'D55.3 Anemia dev transt metabolismo nucleotidios'),
  ('D558', 'Outras anemias devidas a transtornos enzimáticos', 'D55.8 Outr anemias dev transt enzimaticos'),
  ('D559', 'Anemia devida a transtorno enzimático não especificada', 'D55.9 Anemia dev transt enzimatico NE'),
  ('D56', 'Talassemia', 'D56 Talassemia'),
  ('D560', 'Talassemia alfa', 'D56.0 Talassemia alfa'),
  ('D561', 'Talassemia beta', 'D56.1 Talassemia beta'),
  ('D562', 'Talassemia delta-beta', 'D56.2 Talassemia delta-beta'),
  ('D563', 'Estigma talassêmico', 'D56.3 Estigma talassemico'),
  ('D564', 'Persistência hereditária de hemoglobina fetal', 'D56.4 Persistencia hereditaria hemoglobina fetal'),
  ('D568', 'Outras talassemias', 'D56.8 Outr talassemias'),
  ('D569', 'Talassemia não especificada', 'D56.9 Talassemia NE'),
  ('D57', 'Transtornos falciformes', 'D57 Transt falciformes'),
  ('D570', 'Anemia falciforme com crise', 'D57.0 Anemia falciforme c/crise'),
  ('D571', 'Anemia falciforme sem crise', 'D57.1 Anemia falciforme s/crise'),
  ('D572', 'Transtornos falciformes heterozigóticos duplos', 'D57.2 Transt falciformes heterozigoticos duplos'),
  ('D573', 'Estigma falciforme', 'D57.3 Estigma falciforme'),
  ('D578', 'Outros transtornos falciformes', 'D57.8 Outr transt falciformes'),
  ('D58', 'Outras anemias hemolíticas hereditárias', 'D58 Outr anemias hemoliticas hereditarias'),
  ('D580', 'Esferocitose hereditária', 'D58.0 Esferocitose hereditaria'),
  ('D581', 'Eliptocitose hereditária', 'D58.1 Eliptocitose hereditaria'),
  ('D582', 'Outras hemoglobinopatias', 'D58.2 Outr hemoglobinopatias'),
  ('D588', 'Outras anemias hemolíticas hereditárias especificadas', 'D58.8 Outr anemias hemoliticas hereditarias espec'),
  ('D589', 'Anemia hemolítica hereditária não especificada', 'D58.9 Anemia hemolitica hereditaria NE'),
  ('D59', 'Anemia hemolítica adquirida', 'D59 Anemia hemolitica adquir'),
  ('D590', 'Anemia hemolítica auto-imune induzida por droga', 'D59.0 Anemia hemolitica auto-imune induz p/droga'),
  ('D591', 'Outras anemias hemolíticas auto-imunes', 'D59.1 Outr anemias hemoliticas auto-imunes'),
  ('D592', 'Anemia hemolítica não-auto-imune induzida por drogas', 'D59.2 Anemia hemolitic n-auto-imune induz p/drogas'),
  ('D593', 'Síndrome hemolítico-urêmica', 'D59.3 Sindr hemolitico-uremica'),
  ('D594', 'Outras anemias hemolíticas não-autoimunes', 'D59.4 Outr anemias hemoliticas nao-autoimunes'),
  ('D595', 'Hemoglobinúria paroxística noturna (Marchiafava-Micheli)', 'D59.5 Hemoglobinuria paroxistica noturna'),
  ('D596', 'Hemoglobinúria devida à hemólise por outras causas externas', 'D59.6 Hemoglobinuria dev hemolise p/outr caus ext'),
  ('D598', 'Outras anemias hemolíticas adquiridas', 'D59.8 Outr anemias hemoliticas adquir'),
  ('D599', 'Anemia hemolítica adquirida não especificada', 'D59.9 Anemia hemolitica adquir NE'),
  ('D60', 'Aplasia pura da série vermelha, adquirida (eritroblastopenia)', 'D60 Aplasia pura da serie vermelha adquir'),
  ('D600', 'Aplasia pura adquirida crônica da série vermelha', 'D60.0 Aplasia pura adq cronica serie vermelha'),
  ('D601', 'Aplasia pura adquirida transitória da série vermelha', 'D60.1 Aplasia pura adq transitoria serie vermelha'),
  ('D608', 'Outras aplasias puras adquiridas da série vermelha', 'D60.8 Outr aplasias puras adq serie vermelha'),
  ('D609', 'Aplasia pura adquirida, não especificada, da série vermelha', 'D60.9 Aplasia pura adquir NE da serie vermelha'),
  ('D61', 'Outras anemias aplásticas', 'D61 Outr anemias aplasticas'),
  ('D610', 'Anemia aplástica constitucional', 'D61.0 Anemia aplastica constitucional'),
  ('D611', 'Anemia aplástica induzida por drogas', 'D61.1 Anemia aplastica induz p/drogas'),
  ('D612', 'Anemia aplástica devida a outros agentes externos', 'D61.2 Anemia aplastica dev outr agentes externos'),
  ('D613', 'Anemia aplástica idiopática', 'D61.3 Anemia aplastica idiopatica'),
  ('D618', 'Outras anemias aplásticas especificadas', 'D61.8 Outr anemias aplasticas espec'),
  ('D619', 'Anemia aplástica não especificada', 'D61.9 Anemia aplastica NE'),
  ('D62', 'Anemia aguda pós-hemorrágica', 'D62 Anemia aguda pos-hemorragica'),
  ('D62', 'Anemia aguda pós-hemorrágica', 'D62 Anemia aguda pos-hemorragica'),
  ('D63', 'Anemia em doenças crônicas classificadas em outra parte', 'D63 Anemia em doenc cronicas COP'),
  ('D630', 'Anemia em neoplasias', 'D63.0 Anemia em neoplasias'),
  ('D638', 'Anemia em outras doenças classificadas em outra parte', 'D63.8 Anemia em outr doenc COP'),
  ('D64', 'Outras anemias', 'D64 Outr anemias'),
  ('D640', 'Anemia sideroblástica hereditária', 'D64.0 Anemia sideroblastica hereditaria'),
  ('D641', 'Anemia sideroblástica secundária a doença', 'D64.1 Anemia sideroblastica secund a doenc'),
  ('D642', 'Anemia sideroblástica secundária ao uso de drogas e a toxinas', 'D64.2 Anemia sideroblastic secund uso drogas toxin'),
  ('D643', 'Outras anemias sideroblásticas', 'D64.3 Outr anemias sideroblasticas'),
  ('D644', 'Anemia diseritropoética congênita', 'D64.4 Anemia diseritropoetica congen'),
  ('D648', 'Outras anemias especificadas', 'D64.8 Outr anemias espec'),
  ('D649', 'Anemia não especificada', 'D64.9 Anemia NE'),
  ('D65', 'Coagulação intravascular disseminada (síndrome de desfibrinação)', 'D65 Coagulacao intravascular disseminada'),
  ('D65', 'Coagulação intravascular disseminada (síndrome de desfibrinação)', 'D65 Coagulacao intravascular disseminada'),
  ('D66', 'Deficiência hereditária do fator VIII', 'D66 Defic hereditaria do fator VIII'),
  ('D66', 'Deficiência hereditária do fator VIII', 'D66 Defic hereditaria do fator VIII'),
  ('D67', 'Deficiência hereditária do fator IX', 'D67 Defic hereditaria do fator IX'),
  ('D67', 'Deficiência hereditária do fator IX', 'D67 Defic hereditaria do fator IX'),
  ('D68', 'Outros defeitos da coagulação', 'D68 Outr defeitos da coagulacao'),
  ('D680', 'Doença de Von Willebrand', 'D68.0 Doenc de Von Willebrand'),
  ('D681', 'Deficiência hereditária de fator XI', 'D68.1 Defic hereditaria de fator XI'),
  ('D682', 'Deficiência hereditária de outros fatores de coagulação', 'D68.2 Defic hereditaria outr fatores de coagulacao'),
  ('D683', 'Transtorno hemorrágico devido a anticoagulantes circulantes', 'D68.3 Transt hemorragico dev anticoag circulantes'),
  ('D684', 'Deficiência adquirida de fator de coagulação', 'D68.4 Defic adquir de fator de coagulacao'),
  ('D688', 'Outros defeitos especificados da coagulação', 'D68.8 Outr defeitos espec da coagulacao'),
  ('D689', 'Defeito de coagulação não especificado', 'D68.9 Defeito de coagulacao NE'),
  ('D69', 'Púrpura e outras afecções hemorrágicas', 'D69 Purpura e outr afeccoes hemorragicas'),
  ('D690', 'Púrpura alérgica', 'D69.0 Purpura alergica'),
  ('D691', 'Defeitos qualitativos das plaquetas', 'D69.1 Defeitos qualitativos das plaquetas'),
  ('D692', 'Outras púrpuras não-trombocitopênicas', 'D69.2 Outr purpuras nao-trombocitopenicas'),
  ('D693', 'Púrpura trombocitopênica idiopática', 'D69.3 Purpura trombocitopenica idiopatica'),
  ('D694', 'Outra trombocitopenia primária', 'D69.4 Outr trombocitopenia prim'),
  ('D695', 'Trombocitopenia secundária', 'D69.5 Trombocitopenia secund'),
  ('D696', 'Trombocitopenia não especificada', 'D69.6 Trombocitopenia NE'),
  ('D698', 'Outras afecções hemorrágicas especificadas', 'D69.8 Outr afeccoes hemorragicas espec'),
  ('D699', 'Afecção hemorrágica não especificada', 'D69.9 Afeccao hemorragica NE'),
  ('D70', 'Agranulocitose', 'D70 Agranulocitose'),
  ('D70', 'Agranulocitose', 'D70 Agranulocitose'),
  ('D71', 'Transtornos funcionais dos neutrófilos polimorfonucleares', 'D71 Transt func neutrofilos polimorfonucleares'),
  ('D71', 'Transtornos funcionais dos neutrófilos polimorfonucleares', 'D71 Transt func neutrofilos polimorfonucleares'),
  ('D72', 'Outros transtornos dos glóbulos brancos', 'D72 Outr transt dos globulos brancos'),
  ('D720', 'Anomalias genéticas dos leucócitos', 'D72.0 Anomalias geneticas dos leucocitos'),
  ('D721', 'Eosinofilia', 'D72.1 Eosinofilia'),
  ('D728', 'Outros transtornos especificados dos glóbulos brancos', 'D72.8 Outr transt espec dos globulos brancos'),
  ('D729', 'Transtornos não especificados dos glóbulos brancos', 'D72.9 Transt NE dos globulos brancos'),
  ('D73', 'Doenças do baço', 'D73 Doenc do baco'),
  ('D730', 'Hipoesplenismo', 'D73.0 Hipoesplenismo'),
  ('D731', 'Hiperesplenismo', 'D73.1 Hiperesplenismo'),
  ('D732', 'Esplenomegalia congestiva crônica', 'D73.2 Esplenomegalia congestiva cronica'),
  ('D733', 'Abscesso do baço', 'D73.3 Abscesso do baco'),
  ('D734', 'Cisto do baço', 'D73.4 Cisto do baco'),
  ('D735', 'Infarto do baço', 'D73.5 Infarto do baco'),
  ('D738', 'Outras doenças do baço', 'D73.8 Outr doenc do baco'),
  ('D739', 'Doença não especificada do baço', 'D73.9 Doenc NE do baco'),
  ('D74', 'Metemoglobinemia', 'D74 Metemoglobinemia'),
  ('D740', 'Metemoglobinemia congênita', 'D74.0 Metemoglobinemia congen'),
  ('D748', 'Outras metemoglobinemias', 'D74.8 Outr metemoglobinemias'),
  ('D749', 'Metemoglobinemia não especificada', 'D74.9 Metemoglobinemia NE'),
  ('D75', 'Outras doenças do sangue e dos órgãos hematopoéticos', 'D75 Outr doenc sangue e orgaos hematopoeticos'),
  ('D750', 'Eritrocitose familiar', 'D75.0 Eritrocitose familiar'),
  ('D751', 'Policitemia secundária', 'D75.1 Policitemia secund'),
  ('D752', 'Trombocitose essencial', 'D75.2 Trombocitose essencial'),
  ('D758', 'Outras doenças especificadas do sangue e dos órgãos hematopoéticos', 'D75.8 Outr doenc espec sangue e org hematopoeticos'),
  ('D759', 'Doença não especificada do sangue e dos órgãos hematopoéticos', 'D75.9 Doenc NE do sangue e orgaos hematopoeticos'),
  ('D76', 'Algumas doenças que envolvem o tecido linforreticular e o sistema reticulohistiocítico', 'D76 Alg doenc q env tec linforr e sist reticuloh'),
  ('D760', 'Histiocitose das células de Langerhans não classificadas em outra parte', 'D76.0 Histiocitose das celulas de Langerhans NCOP'),
  ('D761', 'Linfohistiocitose hemofagocítica', 'D76.1 Linfohistiocitose hemofagocitica'),
  ('D762', 'Síndrome hematofagocítica associada à infecção', 'D76.2 Sindr hematofagocitica assoc a infecc'),
  ('D763', 'Outras síndromes histiocíticas', 'D76.3 Outr sindr histiociticas'),
  ('D77', 'Outros transtornos do sangue e dos órgãos hematopoéticos em doenças classificadas em outra parte', 'D77 Outr transt sangue e org hematop doenc COP'),
  ('D77', 'Outros transtornos do sangue e dos órgãos hematopoéticos em doenças classificadas em outra parte', 'D77 Outr transt sangue e org hematop doenc COP'),
  ('D80', 'Imunodeficiência com predominância de defeitos de anticorpos', 'D80 Imunodefic c/predom defeitos anticorpos'),
  ('D800', 'Hipogamaglobulinemia hereditária', 'D80.0 Hipogamaglobulinemia hereditaria'),
  ('D801', 'Hipogamaglobulinemia não familiar', 'D80.1 Hipogamaglobulinemia nao familiar'),
  ('D802', 'Deficiência seletiva de imunoglobulina A (IgA)', 'D80.2 Defic seletiva de imunoglobulina A'),
  ('D803', 'Deficiência seletiva de subclasses de imunoglobulina G (IgG)', 'D80.3 Defic seletiva subclasses imunoglobulina G'),
  ('D804', 'Deficiência seletiva de imunoglobulina M (IgM)', 'D80.4 Defic seletiva de imunoglobulina M'),
  ('D805', 'Imunodeficiência com aumento de imunoglobulina M (IgM)', 'D80.5 Imunodeficiencia c/aumento imunoglobulina M'),
  ('D806', 'Deficiência de anticorpos com imunoglobulinas próximas do normal ou com hiperimunoglobulinemia', 'D80.6 Def anticorp c/imunog prox norm ou c/hiperim'),
  ('D807', 'Hipogamaglobulinemia transitória da infância', 'D80.7 Hipogamaglobulinemia transitoria da infancia'),
  ('D808', 'Outras imunodeficiências com predominância de defeitos de anticorpos', 'D80.8 Outr imunodef c/predom defeitos anticorpos'),
  ('D809', 'Imunodeficiência não especificada com predominância de defeitos de anticorpos', 'D80.9 Imunodef NE c/predom defeitos anticorpos'),
  ('D81', 'Deficiências imunitárias combinadas', 'D81 Defic imunitarias combinadas'),
  ('D810', 'Imunodeficiência combinada grave (SCID) com disgenesia reticular', 'D81.0 Imunodef comb grave c/disgenesia reticular'),
  ('D811', 'Imunodeficiência combinada grave (SCID) com números baixos de células T e B', 'D81.1 Imunodef comb grave c/num baixos celulas T B'),
  ('D812', 'Imunodeficiência combinada grave (SCID) com números baixos ou normais de células B', 'D81.2 Imunodef comb grave c/num baix/norm celul B'),
  ('D813', 'Deficiência de adenosina-deaminase (ADA)', 'D81.3 Defic de adenosina-deaminase'),
  ('D814', 'Síndrome de Nezelof', 'D81.4 Sindr de Nezelof'),
  ('D815', 'Deficiência de purina-nucleosídeo fosforilase (PNP)', 'D81.5 Defic de purina-nucleosideo fosforilase'),
  ('D816', 'Deficiência major classe I do complexo de histocompatibilidade', 'D81.6 Defic major classe I complexo histocompatib'),
  ('D817', 'Deficiência major classe II do complexo de histocompatibilidade', 'D81.7 Defic major classe II complexo histocompatib'),
  ('D818', 'Outras deficiências imunitárias combinadas', 'D81.8 Outr defic imunitarias combinadas'),
  ('D819', 'Deficiências imunitárias combinadas não especificadas', 'D81.9 Defic imunitarias combinadas NE'),
  ('D82', 'Imunodeficiência associada com outros defeitos major', 'D82 Imunodeficiencia assoc c/outr defeitos major'),
  ('D820', 'Síndrome de Wiskott-Aldrich', 'D82.0 Sindr de Wiskott-Aldrich'),
  ('D821', 'Síndrome de Di George', 'D82.1 Sindr de Di George'),
  ('D822', 'Imunodeficiência com encurtamento de membros', 'D82.2 Imunodeficiencia c/encurtamento de membros'),
  ('D823', 'Imunodeficiência que se segue à resposta hereditária defeituosa ao vírus de Epstein-Barr (EB)', 'D82.3 Imunodef q seg resp hered def virus E.-Barr'),
  ('D824', 'Síndrome da hiperimunoglobulina E (IgE)', 'D82.4 Sindr da hiperimunoglobulina E'),
  ('D828', 'Imunodeficiências associadas com outros defeitos major especificados', 'D82.8 Imunodef assoc c/outr defeitos major espec'),
  ('D829', 'Imunodeficiência associada com defeitos major não especificados', 'D82.9 Imunodeficiencia assoc c/defeitos major NE'),
  ('D83', 'Imunodeficiência comum variável', 'D83 Imunodeficiencia comum variavel'),
  ('D830', 'Imunodeficiência comum variável com predominância de anormalidades do número e da função das células B', 'D83.0 Imunodef com var predom anorm num func cel B'),
  ('D831', 'Imunodeficiência comum variável com predominância de transtornos imunorregulatórios de células T', 'D83.1 Imunodef com var pred transt imunorreg cel T'),
  ('D832', 'Imunodeficiência comum variável com auto-anticorpos às células B ou T', 'D83.2 Imunodef comum var c/auto-anticorpos cel B/T'),
  ('D838', 'Outras imunodeficiências comuns variáveis', 'D83.8 Outr imunodeficiencias comuns variaveis'),
  ('D839', 'Imunodeficiência comum variável não especificada', 'D83.9 Imunodeficiencia comum variavel NE'),
  ('D84', 'Outras imunodeficiências', 'D84 Outr imunodeficiencias'),
  ('D840', 'Defeito do antígeno-1 da função de linfócito (LFA-1)', 'D84.0 Defeito do antigeno-1 da funcao de linfocito'),
  ('D841', 'Defeitos no sistema complemento', 'D84.1 Defeitos no sist complemento'),
  ('D848', 'Outras imunodeficiências especificadas', 'D84.8 Outr imunodeficiencias espec'),
  ('D849', 'Imunodeficiência não especificada', 'D84.9 Imunodeficiencia NE'),
  ('D86', 'Sarcoidose', 'D86 Sarcoidose'),
  ('D860', 'Sarcoidose do pulmão', 'D86.0 Sarcoidose do pulmao'),
  ('D861', 'Sarcoidose dos gânglios linfáticos', 'D86.1 Sarcoidose dos ganglios linfaticos'),
  ('D862', 'Sarcoidose do pulmão com sarcoidose dos gânglios linfáticos', 'D86.2 Sarcoidose pulmao c/sarcoidose gangl linfat'),
  ('D863', 'Sarcoidose da pele', 'D86.3 Sarcoidose da pele'),
  ('D868', 'Sarcoidose de outros locais especificados e locais combinados', 'D86.8 Sarcoidose outr locais espec e combinados'),
  ('D869', 'Sarcoidose não especificada', 'D86.9 Sarcoidose NE'),
  ('D89', 'Outros transtornos que comprometem o mecanismo imunitário não classificados em outra parte', 'D89 Outr transt q comprom mecanismo imunit NCOP'),
  ('D890', 'Hipergamaglobulinemia policlonal', 'D89.0 Hipergamaglobulinemia policlonal'),
  ('D891', 'Crioglobulinemia', 'D89.1 Crioglobulinemia'),
  ('D892', 'Hipergamaglobulinemia não especificada', 'D89.2 Hipergamaglobulinemia NE'),
  ('D898', 'Outros transtornos especificados que comprometem o mecanismo imunitário não classificados em outra parte', 'D89.8 Outr transt espec q comprom mec imunit NCOP'),
  ('D899', 'Transtornos não especificados que comprometem o mecanismo imunitário', 'D89.9 Transt NE q comprometem mecanismo imunitario');
