INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('B00', 'Infecções pelo vírus do herpes (herpes simples)', 'B00 Infecc p/virus do herpes'),
  ('B000', 'Eczema herpético', 'B00.0 Eczema herpetico'),
  ('B001', 'Dermatite vesicular devido ao vírus do herpes', 'B00.1 Dermatite vesicular dev virus do herpes'),
  ('B002', 'Gengivoestomatite e faringoamigdalite devida ao vírus do herpes', 'B00.2 Gengivoestom e faringoamig dev virus herpes'),
  ('B003', 'Meningite devida ao vírus do herpes', 'B00.3 Meningite dev virus do herpes'),
  ('B004', 'Encefalite devida ao vírus do herpes', 'B00.4 Encefalite dev virus do herpes'),
  ('B005', 'Afecções oculares devidas ao vírus do herpes', 'B00.5 Afeccoes oculares dev virus do herpes'),
  ('B007', 'Doença disseminada devida ao vírus do herpes', 'B00.7 Doenc disseminada dev virus do herpes'),
  ('B008', 'Outras formas de infecção devida ao vírus do herpes', 'B00.8 Outr form de infecc dev virus do herpes'),
  ('B009', 'Infecção não especificada devida ao vírus do herpes', 'B00.9 Infecc NE dev virus do herpes'),
  ('B01', 'Varicela (Catapora)', 'B01 Varicela'),
  ('B010', 'Meningite por varicela', 'B01.0 Meningite p/varicela'),
  ('B011', 'Encefalite por varicela', 'B01.1 Encefalite p/varicela'),
  ('B012', 'Pneumopatia varicelosa', 'B01.2 Pneumopatia varicelosa'),
  ('B018', 'Varicela com outras complicações', 'B01.8 Varicela c/outr complic'),
  ('B019', 'Varicela sem complicação', 'B01.9 Varicela s/complic'),
  ('B02', 'Herpes zoster (Zona)', 'B02 Herpes zoster'),
  ('B020', 'Encefalite pelo vírus do herpes zoster', 'B02.0 Encefalite p/virus do herpes zoster'),
  ('B021', 'Meningite pelo vírus do herpes zoster', 'B02.1 Meningite p/virus do herpes zoster'),
  ('B022', 'Herpes zoster acompanhado de outras manifestações neurológicas', 'B02.2 Herpes zoster acomp outr manif neurologicas'),
  ('B023', 'Herpes zoster oftálmico', 'B02.3 Herpes zoster oftalmico'),
  ('B027', 'Herpes zoster disseminado', 'B02.7 Herpes zoster disseminado'),
  ('B028', 'Herpes zoster com outras complicações', 'B02.8 Herpes zoster c/outr complic'),
  ('B029', 'Herpes zoster sem complicação', 'B02.9 Herpes zoster s/complic'),
  ('B03', 'Varíola', 'B03 Variola'),
  ('B03', 'Varíola', 'B03 Variola'),
  ('B04', 'Varíola dos macacos (Monkeypox)', 'B04 Variola dos macacos'),
  ('B04', 'Varíola dos macacos (Monkeypox)', 'B04 Variola dos macacos'),
  ('B05', 'Sarampo', 'B05 Sarampo'),
  ('B050', 'Sarampo complicado por encefalite', 'B05.0 Sarampo complicado p/encefalite'),
  ('B051', 'Sarampo complicado por meningite', 'B05.1 Sarampo complicado p/meningite'),
  ('B052', 'Sarampo complicado por pneumonia', 'B05.2 Sarampo complicado p/pneumonia'),
  ('B053', 'Sarampo complicado por otite média', 'B05.3 Sarampo complicado p/otite media'),
  ('B054', 'Sarampo com complicações intestinais', 'B05.4 Sarampo c/complic intestinais'),
  ('B058', 'Sarampo com outras complicações', 'B05.8 Sarampo c/outr complic'),
  ('B059', 'Sarampo sem complicação', 'B05.9 Sarampo s/complic'),
  ('B06', 'Rubéola', 'B06 Rubeola'),
  ('B060', 'Rubéola com complicações neurológicas', 'B06.0 Rubeola c/complic neurologicas'),
  ('B068', 'Rubéola com outras complicações', 'B06.8 Rubeola c/outr complic'),
  ('B069', 'Rubéola sem complicação', 'B06.9 Rubeola s/complic'),
  ('B07', 'Verrugas de origem viral', 'B07 Verrugas orig viral'),
  ('B07', 'Verrugas de origem viral', 'B07 Verrugas orig viral'),
  ('B08', 'Outras infecções virais caracterizadas por lesões da pele e das membranas mucosas, não classificadas em outra parte', 'B08 Outr inf virais lesoes pele membr muc NCOP'),
  ('B080', 'Outras infecções por ortopoxvírus', 'B08.0 Outr infecc p/ortopoxvirus'),
  ('B081', 'Molusco contagioso', 'B08.1 Molusco contagioso'),
  ('B082', 'Exantema súbito (sexta doença)', 'B08.2 Exantema subito'),
  ('B083', 'Eritema infeccioso (quinta doença)', 'B08.3 Eritema infecc'),
  ('B084', 'Estomatite vesicular devida a enterovírus com exantema', 'B08.4 Estomatite vesic dev enterovirus c/exantema'),
  ('B085', 'Faringite vesicular devida a enterovírus', 'B08.5 Faringite vesicular dev enterovirus'),
  ('B088', 'Outras infecções virais especificadas caracterizadas por lesões de pele e das membranas mucosas', 'B08.8 Outr inf virais espec lesoes pele membr muco'),
  ('B09', 'Infecção viral não especificada caracterizada por lesões da pele e membranas mucosas', 'B09 Inf viral NE caract p/lesoes pele membr muco'),
  ('B09', 'Infecção viral não especificada caracterizada por lesões da pele e membranas mucosas', 'B09 Inf viral NE caract p/lesoes pele membr muco'),
  ('B15', 'Hepatite aguda A', 'B15 Hepatite aguda A'),
  ('B150', 'Hepatite A com coma hepático', 'B15.0 Hepatite A c/coma hepatico'),
  ('B159', 'Hepatite A sem coma hepático', 'B15.9 Hepatite A s/coma hepatico'),
  ('B16', 'Hepatite aguda B', 'B16 Hepatite aguda B'),
  ('B160', 'Hepatite aguda B com agente Delta (co-infecção), com coma hepático', 'B16.0 Hepatite aguda B c/agente Delta c/coma hepat'),
  ('B161', 'Hepatite aguda B com agente Delta, (co-infecção), sem coma hepático', 'B16.1 Hepatite aguda B c/agente Delta s/coma hepat'),
  ('B162', 'Hepatite aguda B sem agente Delta, com coma hepático', 'B16.2 Hepatite aguda B s/agente Delta c/coma hepat'),
  ('B169', 'Hepatite aguda B sem agente Delta e sem coma hepático', 'B16.9 Hepatite aguda B s/agente Delta s/coma hepat'),
  ('B17', 'Outras hepatites virais agudas', 'B17 Outr hepatites virais agudas'),
  ('B170', '(Super)infecção Delta aguda de portador de hepatite B', 'B17.0 Infecc Delta aguda de portador de hepatite B'),
  ('B171', 'Hepatite aguda C', 'B17.1 Hepatite aguda C'),
  ('B172', 'Hepatite aguda E', 'B17.2 Hepatite aguda E'),
  ('B178', 'Outras hepatites virais agudas especificadas', 'B17.8 Outr hepatites virais agudas espec'),
  ('B18', 'Hepatite viral crônica', 'B18 Hepatite viral cronica'),
  ('B180', 'Hepatite viral crônica B com agente Delta', 'B18.0 Hepatite viral cronica B c/agente Delta'),
  ('B181', 'Hepatite crônica viral B sem agente Delta', 'B18.1 Hepatite cronica viral B s/agente Delta'),
  ('B182', 'Hepatite viral crônica C', 'B18.2 Hepatite viral cronica C'),
  ('B188', 'Outras hepatites crônicas virais', 'B18.8 Outr hepatites cronicas virais'),
  ('B189', 'Hepatite viral crônica não especificada', 'B18.9 Hepatite viral cronica NE'),
  ('B19', 'Hepatite viral não especificada', 'B19 Hepatite viral NE'),
  ('B190', 'Hepatite viral, não especificada, com coma', 'B19.0 Hepatite viral NE c/coma'),
  ('B199', 'Hepatite viral, não especificada, sem coma', 'B19.9 Hepatite viral NE s/coma'),
  ('B20', 'Doença pelo vírus da imunodeficiência humana (HIV), resultando em doenças infecciosas e parasitárias', 'B20 Doenc p/HIV result doenc infecc e parasit'),
  ('B200', 'Doença pelo HIV resultando em infecções micobacterianas', 'B20.0 Doenc p/HIV result em infecc micobacterianas'),
  ('B201', 'Doença pelo HIV resultando em outras infecções bacterianas', 'B20.1 Doenc p/HIV result outr infecc bacter'),
  ('B202', 'Doença pelo HIV resultando em doença citomegálica', 'B20.2 Doenc p/HIV result em doenc citomegalica'),
  ('B203', 'Doença pelo HIV resultando em outras infecções virais', 'B20.3 Doenc p/HIV result em outr infecc virais'),
  ('B204', 'Doença pelo HIV resultando em candidíase', 'B20.4 Doenc p/HIV result em candidiase'),
  ('B205', 'Doença pelo HIV resultando em outras micoses', 'B20.5 Doenc p/HIV result em outr micoses'),
  ('B206', 'Doença pelo HIV resultando em pneumonia por Pneumocystis jirovecii', 'B20.6 Doenc p/HIV result pneumonia p/P.jirovecii'),
  ('B207', 'Doença pelo HIV resultando em infecções múltiplas', 'B20.7 Doenc p/HIV result em infecc mult'),
  ('B208', 'Doença pelo HIV resultando em outras doenças infecciosas e parasitárias', 'B20.8 Doenc p/HIV result outr doenc infecc parasit'),
  ('B209', 'Doença pelo HIV resultando em doença infecciosa ou parasitária não especificada', 'B20.9 Doenc p/HIV result doenc infecc parasit NE'),
  ('B21', 'Doença pelo vírus da imunodeficiência humana (HIV), resultando em neoplasias malignas', 'B21 Doenc p/HIV result em neopl malig'),
  ('B210', 'Doença pelo HIV resultando em sarcoma de Kaposi', 'B21.0 Doenc p/HIV result em sarcoma de Kaposi'),
  ('B211', 'Doença pelo HIV resultando em linfoma de Burkitt', 'B21.1 Doenc p/HIV result em linfoma de Burkitt'),
  ('B212', 'Doença pelo HIV resultando em outros tipos de linfoma não-Hodgkin', 'B21.2 Doenc p/HIV res outr tip linfoma nao-Hodgkin'),
  ('B213', 'Doença pelo HIV resultando em outras neoplasias malignas dos tecidos linfático, hematopoético e correlatos', 'B21.3 Doenc p/HIV out neop mal tec linf hemat corr'),
  ('B217', 'Doença pelo HIV resultando em múltiplas neoplasias malignas', 'B21.7 Doenc p/HIV result em mult neopl malig'),
  ('B218', 'Doença pelo HIV resultando em outras neoplasias malignas', 'B21.8 Doenc p/HIV result em outr neopl malig'),
  ('B219', 'Doença pelo HIV resultando em neoplasia maligna não especificada', 'B21.9 Doenc p/HIV result em neopl malig NE'),
  ('B22', 'Doença pelo vírus da imunodeficiência humana (HIV) resultando em outras doenças especificadas', 'B22 Doenc p/HIV result em outr doenc espec'),
  ('B220', 'Doença pelo HIV resultando em encefalopatia', 'B22.0 Doenc p/HIV result em encefalopatia'),
  ('B221', 'Doença pelo HIV resultando em pneumonite intersticial linfática', 'B22.1 Doenc p/HIV result pneumonite interst linfat'),
  ('B222', 'Doença pelo HIV resultando em síndrome de emaciação', 'B22.2 Doenc p/HIV result em sindr de emaciacao'),
  ('B227', 'Doença pelo HIV resultando em doenças múltiplas classificadas em outra parte', 'B22.7 Doenc p/HIV result em doenc mult COP'),
  ('B23', 'Doença pelo vírus da imunodeficiência humana (HIV) resultando em outras doenças', 'B23 Doenc p/HIV result em outr doenc'),
  ('B230', 'Síndrome de infecção aguda pelo HIV', 'B23.0 Sindr de infecc aguda p/HIV'),
  ('B231', 'Doença pelo HIV resultando em linfadenopatias generalizadas (persistentes)', 'B23.1 Doenc p/HIV result linfadenopatias generaliz'),
  ('B232', 'Doença pelo HIV resultando em anomalias hematológicas e imunológicas não classificadas em outra parte', 'B23.2 Doenc p/HIV result anom hemat imunolog NCOP'),
  ('B238', 'Doença pelo HIV resultando em outra afecções especificadas', 'B23.8 Doenc p/HIV result em outr afeccoes espec'),
  ('B24', 'Doença pelo vírus da imunodeficiência humana (HIV) não especificada', 'B24 Doenc p/HIV NE'),
  ('B24', 'Doença pelo vírus da imunodeficiência humana (HIV) não especificada', 'B24 Doenc p/HIV NE'),
  ('B25', 'Doença por citomegalovírus', 'B25 Doenc p/citomegalovirus'),
  ('B250', 'Pneumonite por citomegalovírus ', 'B25.0 Pneumonite p/citomegalovirus'),
  ('B251', 'Hepatite por citomegalovírus', 'B25.1 Hepatite p/citomegalovirus'),
  ('B252', 'Pancreatite por citomegalovírus', 'B25.2 Pancreatite p/citomegalovirus'),
  ('B258', 'Outras doenças por citomegalovírus', 'B25.8 Outr doenc p/citomegalovirus'),
  ('B259', 'Doença não especificada por citomegalovírus', 'B25.9 Doenc NE p/citomegalovirus'),
  ('B26', 'Caxumba (Parotidite epidêmica)', 'B26 Caxumba'),
  ('B260', 'Orquite por caxumba (parotidite epidêmica)', 'B26.0 Orquite p/caxumba'),
  ('B261', 'Meningite por caxumba (parotidite epidêmica)', 'B26.1 Meningite p/caxumba'),
  ('B262', 'Encefalite por caxumba (parotidite epidêmica)', 'B26.2 Encefalite p/caxumba'),
  ('B263', 'Pancreatite por caxumba (parotidite epidêmica)', 'B26.3 Pancreatite p/caxumba'),
  ('B268', 'Caxumba (parotidite epidêmica) com outras complicações', 'B26.8 Caxumba c/outr complic'),
  ('B269', 'Caxumba (parotidite epidêmica) sem complicações', 'B26.9 Caxumba s/complic'),
  ('B27', 'Mononucleose infecciosa', 'B27 Mononucleose infecc'),
  ('B270', 'Mononucleose pelo vírus herpes gama', 'B27.0 Mononucleose p/virus herpes gama'),
  ('B271', 'Mononucleose por citomegalovírus', 'B27.1 Mononucleose p/citomegalovirus'),
  ('B278', 'Outras mononucleoses infecciosas', 'B27.8 Outr mononucleoses infecc'),
  ('B279', 'Mononucleose infecciosa não especificada', 'B27.9 Mononucleose infecc NE'),
  ('B30', 'Conjuntivite viral', 'B30 Conjuntivite viral'),
  ('B300', 'Ceratoconjuntivite devida a adenovírus', 'B30.0 Ceratoconjuntivite dev adenovirus'),
  ('B301', 'Conjuntivite devida a adenovírus', 'B30.1 Conjuntivite dev adenovirus'),
  ('B302', 'Faringoconjuntivite viral', 'B30.2 Faringoconjuntivite viral'),
  ('B303', 'Conjuntivite hemorrágica aguda endêmica (por enterovírus)', 'B30.3 Conjuntivite hemorragica aguda endemica'),
  ('B308', 'Outras conjuntivites virais', 'B30.8 Outr conjuntivites virais'),
  ('B309', 'Conjuntivite viral não especificada', 'B30.9 Conjuntivite viral NE'),
  ('B33', 'Outras doenças por vírus não classificada em outra parte', 'B33 Outr doenc p/virus NCOP'),
  ('B330', 'Mialgia epidêmica', 'B33.0 Mialgia epidemica'),
  ('B331', 'Doença de Ross River', 'B33.1 Doenc de Ross River'),
  ('B332', 'Cardite viral', 'B33.2 Cardite viral'),
  ('B333', 'Infecção por retrovírus não classificada em outra parte', 'B33.3 Infecc p/retrovirus NCOP'),
  ('B334', 'Síndrome (cardio-)pulmonar por Hantavírus (SPH) (SCPH)', 'B33.4 Síndrome (cardio-)pulmonar por Hantavírus'),
  ('B338', 'Outras doenças especificadas por vírus', 'B33.8 Outr doenc espec p/virus'),
  ('B34', 'Doenças por vírus, de localização não especificada', 'B34 Doenc p/virus de localiz NE'),
  ('B340', 'Infecção por adenovírus de localização não especificada', 'B34.0 Infecc p/adenovirus local NE'),
  ('B341', 'Infecção por enterovírus de localização não especificada', 'B34.1 Infecc p/enterovirus localiz NE'),
  ('B342', 'Infecção por coronavírus de localização não especificada', 'B34.2 Infecc p/coronavirus localiz NE'),
  ('B343', 'Infecção por parvovírus de localização não especificada', 'B34.3 Infecc p/parvovirus localiz NE'),
  ('B344', 'Infecção por papovavírus de localização não especificada', 'B34.4 Infecc p/papovavirus localiz NE'),
  ('B348', 'Outras infecções por vírus de localização não especificada', 'B34.8 Outr infecc p/virus localiz NE'),
  ('B349', 'Infecção viral não especificada', 'B34.9 Infecc viral NE'),
  ('B35', 'Dermatofitose', 'B35 Dermatofitose'),
  ('B350', 'Tinha da barba e do couro cabeludo', 'B35.0 Tinha da barba e do couro cabeludo'),
  ('B351', 'Tinha das unhas', 'B35.1 Tinha das unhas'),
  ('B352', 'Tinha da mão', 'B35.2 Tinha da mao'),
  ('B353', 'Tinha dos pés', 'B35.3 Tinha dos pes'),
  ('B354', 'Tinha do corpo', 'B35.4 Tinha do corpo'),
  ('B355', 'Tinha imbricada', 'B35.5 Tinha imbricada'),
  ('B356', 'Tinea cruris', 'B35.6 Tinea cruris'),
  ('B358', 'Outras dermatofitoses', 'B35.8 Outr dermatofitoses'),
  ('B359', 'Dermatofitose não especificada', 'B35.9 Dermatofitose NE'),
  ('B36', 'Outras micoses superficiais', 'B36 Outr micoses superf'),
  ('B360', 'Pitiríase versicolor', 'B36.0 Pitiriase versicolor'),
  ('B361', 'Tinha negra', 'B36.1 Tinha negra'),
  ('B362', 'Piedra branca', 'B36.2 Piedra branca'),
  ('B363', 'Piedra negra', 'B36.3 Piedra negra'),
  ('B368', 'Outras micoses superficiais especificadas', 'B36.8 Outr micoses superf espec'),
  ('B369', 'Micose superficial não especificada', 'B36.9 Micose superf NE'),
  ('B37', 'Candidíase', 'B37 Candidiase'),
  ('B370', 'Estomatite por Candida', 'B37.0 Estomatite p/Candida'),
  ('B371', 'Candidíase pulmonar', 'B37.1 Candidiase pulmonar'),
  ('B372', 'Candidíase da pele e das unhas', 'B37.2 Candidiase da pele e das unhas'),
  ('B373', 'Candidíase da vulva e da vagina', 'B37.3 Candidiase da vulva e da vagina'),
  ('B374', 'Candidíase de outras localizações urogenitais', 'B37.4 Candidiase de outr localiz urogenitais'),
  ('B375', 'Meningite por Candida', 'B37.5 Meningite p/Candida'),
  ('B376', 'Endocardite por Candida', 'B37.6 Endocardite p/Candida'),
  ('B377', 'Septicemia por Candida', 'B37.7 Septicemia p/Candida'),
  ('B378', 'Candidíase de outras localizações', 'B37.8 Candidiase de outr localiz'),
  ('B379', 'Candidíase não especificada', 'B37.9 Candidiase NE'),
  ('B38', 'Coccidioidomicose', 'B38 Coccidioidomicose'),
  ('B380', 'Coccidioidomicose pulmonar aguda', 'B38.0 Coccidioidomicose pulmonar aguda'),
  ('B381', 'Coccidioidomicose pulmonar crônica', 'B38.1 Coccidioidomicose pulmonar cronica'),
  ('B382', 'Coccidioidomicose pulmonar não especificada', 'B38.2 Coccidioidomicose pulmonar NE'),
  ('B383', 'Coccidioidomicose cutânea', 'B38.3 Coccidioidomicose cutanea'),
  ('B384', 'Meningite por coccidioidomicose', 'B38.4 Meningite p/coccidioidomicose'),
  ('B387', 'Coccidioidomicose disseminada', 'B38.7 Coccidioidomicose disseminada'),
  ('B388', 'Outras formas de coccidioidomicose', 'B38.8 Outr form de coccidioidomicose'),
  ('B389', 'Coccidioidomicose não especificada', 'B38.9 Coccidioidomicose NE'),
  ('B39', 'Histoplasmose', 'B39 Histoplasmose'),
  ('B390', 'Histoplasmose pulmonar aguda por Histoplasma capsulatum', 'B39.0 Histoplasmose pulmonar aguda p/H.capsulatum'),
  ('B391', 'Histoplasmose pulmonar crônica por Histoplasma capsulatum', 'B39.1 Histoplasmose pulmonar cronic p/H.capsulatum'),
  ('B392', 'Histoplasmose pulmonar não especificada por Histoplasma capsulatum', 'B39.2 Histoplasmose pulmonar NE p/H.capsulatum'),
  ('B393', 'Histoplasmose disseminada por Histoplasma capsulatum', 'B39.3 Histoplasmose disseminada p/H.capsulatum'),
  ('B394', 'Histoplasmose não especificada por Histoplasma capsulatum', 'B39.4 Histoplasmose NE p/Histoplasma capsulatum'),
  ('B395', 'Histoplasmose por Histoplasma duboisii', 'B39.5 Histoplasmose p/Histoplasma duboisii'),
  ('B399', 'Histoplasmose não especificada', 'B39.9 Histoplasmose NE'),
  ('B40', 'Blastomicose', 'B40 Blastomicose'),
  ('B400', 'Blastomicose pulmonar aguda', 'B40.0 Blastomicose pulmonar aguda'),
  ('B401', 'Blastomicose pulmonar crônica', 'B40.1 Blastomicose pulmonar cronica'),
  ('B402', 'Blastomicose pulmonar não especificada', 'B40.2 Blastomicose pulmonar NE'),
  ('B403', 'Blastomicose cutânea', 'B40.3 Blastomicose cutanea'),
  ('B407', 'Blastomicose disseminada', 'B40.7 Blastomicose disseminada'),
  ('B408', 'Outras formas de blastomicose', 'B40.8 Outr form de blastomicose'),
  ('B409', 'Blastomicose não especificada', 'B40.9 Blastomicose NE'),
  ('B41', 'Paracoccidioidomicose', 'B41 Paracoccidioidomicose'),
  ('B410', 'Paracoccidioidomicose pulmonar', 'B41.0 Paracoccidioidomicose pulmonar'),
  ('B417', 'Paracoccidioidomicose disseminada', 'B41.7 Paracoccidioidomicose disseminada'),
  ('B418', 'Outras formas de paracoccidioidomicose', 'B41.8 Outr form de paracoccidioidomicose'),
  ('B419', 'Paracoccidioidomicose não especificada', 'B41.9 Paracoccidioidomicose NE'),
  ('B42', 'Esporotricose', 'B42 Esporotricose'),
  ('B420', 'Esporotricose pulmonar', 'B42.0 Esporotricose pulmonar'),
  ('B421', 'Esporotricose linfocutânea', 'B42.1 Esporotricose linfocutanea'),
  ('B427', 'Esporotricose disseminada', 'B42.7 Esporotricose disseminada'),
  ('B428', 'Outras formas de esporotricose', 'B42.8 Outr form de esporotricose'),
  ('B429', 'Esporotricose não especificada', 'B42.9 Esporotricose NE'),
  ('B43', 'Cromomicose e abscesso feomicótico', 'B43 Cromomicose e abscesso feomicotico'),
  ('B430', 'Cromomicose cutânea', 'B43.0 Cromomicose cutanea'),
  ('B431', 'Abscesso cerebral feomicótico', 'B43.1 Abscesso cerebral feomicotico'),
  ('B432', 'Abscesso e cisto feomicótico subcutâneos', 'B43.2 Abscesso e cisto feomicotico subcutaneos'),
  ('B438', 'Outras formas de cromomicose', 'B43.8 Outr form de cromomicose'),
  ('B439', 'Cromomicose não especificada', 'B43.9 Cromomicose NE'),
  ('B44', 'Aspergilose', 'B44 Aspergilose'),
  ('B440', 'Aspergilose pulmonar invasiva', 'B44.0 Aspergilose pulmonar invasiva'),
  ('B441', 'Outras aspergiloses pulmonares', 'B44.1 Outr aspergiloses pulmonares'),
  ('B442', 'Aspergilose amigdaliana', 'B44.2 Aspergilose amigdaliana'),
  ('B447', 'Aspergilose disseminada', 'B44.7 Aspergilose disseminada'),
  ('B448', 'Outras formas de aspergilose', 'B44.8 Outr form de Aspergilose'),
  ('B449', 'Aspergilose não especificada', 'B44.9 Aspergilose NE'),
  ('B45', 'Criptococose', 'B45 Criptococose'),
  ('B450', 'Criptococose pulmonar', 'B45.0 Criptococose pulmonar'),
  ('B451', 'Criptococose cerebral', 'B45.1 Criptococose cerebral'),
  ('B452', 'Criptococose cutânea', 'B45.2 Criptococose cutanea'),
  ('B453', 'Criptococose óssea', 'B45.3 Criptococose ossea'),
  ('B457', 'Criptococose disseminada', 'B45.7 Criptococose disseminada'),
  ('B458', 'Outras formas de criptococose', 'B45.8 Outr form de criptococose'),
  ('B459', 'Criptococose não especificada', 'B45.9 Criptococose NE'),
  ('B46', 'Zigomicose', 'B46 Zigomicose'),
  ('B460', 'Mucormicose pulmonar', 'B46.0 Mucormicose pulmonar'),
  ('B461', 'Mucormicose rinocerebral', 'B46.1 Mucormicose rinocerebral'),
  ('B462', 'Mucormicose gastrointestinal', 'B46.2 Mucormicose gastrointestinal'),
  ('B463', 'Mucormicose cutânea', 'B46.3 Mucormicose cutanea'),
  ('B464', 'Mucormicose disseminada', 'B46.4 Mucormicose disseminada'),
  ('B465', 'Mucormicose não especificada', 'B46.5 Mucormicose NE'),
  ('B468', 'Outras zigomicoses', 'B46.8 Outr zigomicoses'),
  ('B469', 'Zigomicose não especificada', 'B46.9 Zigomicose NE'),
  ('B47', 'Micetoma', 'B47 Micetoma'),
  ('B470', 'Eumicetoma', 'B47.0 Eumicetoma'),
  ('B471', 'Actinomicetoma', 'B47.1 Actinomicetoma'),
  ('B479', 'Micetoma não especificado', 'B47.9 Micetoma NE'),
  ('B48', 'Outras micoses, não classificadas em outra parte', 'B48 Outr micoses NCOP'),
  ('B480', 'Lobomicose', 'B48.0 Lobomicose'),
  ('B481', 'Rinosporidiose', 'B48.1 Rinosporidiose'),
  ('B482', 'Alesqueriose', 'B48.2 Alesqueriose'),
  ('B483', 'Geotricose', 'B48.3 Geotricose'),
  ('B484', 'Penicilose', 'B48.4 Penicilose'),
  ('B487', 'Micoses oportunistas', 'B48.7 Micoses oportunistas'),
  ('B488', 'Outras micoses especificadas', 'B48.8 Outr micoses espec'),
  ('B49', 'Micose não especificada', 'B49 Micose NE'),
  ('B49', 'Micose não especificada', 'B49 Micose NE'),
  ('B50', 'Malária por Plasmodium falciparum', 'B50 Malaria p/Plasmodium falciparum'),
  ('B500', 'Malária por Plasmodium falciparum com complicações cerebrais', 'B50.0 Malaria p/P.falciparum c/complic cerebrais'),
  ('B508', 'Outras formas graves e complicadas de malária por Plasmodium falciparum', 'B50.8 Outr form grav compl malaria p/P.falciparum'),
  ('B509', 'Malária não especificada por Plasmodium falciparum', 'B50.9 Malaria NE p/Plasmodium falciparum'),
  ('B51', 'Malária por Plasmodium vivax', 'B51 Malaria p/Plasmodium vivax'),
  ('B510', 'Malária por Plasmodium vivax com rotura do baço', 'B51.0 Malaria p/Plasmodium vivax c/rotura do baco'),
  ('B518', 'Malária por Plasmodium vivax com outras complicações', 'B51.8 Malaria p/Plasmodium vivax c/outr complic'),
  ('B519', 'Malária por Plasmodium vivax sem complicações', 'B51.9 Malaria p/Plasmodium vivax s/complic'),
  ('B52', 'Malária por Plasmodium malariae', 'B52 Malaria p/Plasmodium malariae'),
  ('B520', 'Malária por Plasmodium malariae com nefropatia', 'B52.0 Malaria p/Plasmodium malariae c/nefropatia'),
  ('B528', 'Malária por Plasmodium malariae com outras complicações', 'B52.8 Malaria p/Plasmodium malariae c/outr complic'),
  ('B529', 'Malária por Plasmodium malariae sem complicações', 'B52.9 Malaria p/Plasmodium malariae s/complic'),
  ('B53', 'Outras formas de malária confirmadas por exames parasitológicos', 'B53 Outr form malaria conf p/exames parasitolog'),
  ('B530', 'Malária por Plasmodium ovale', 'B53.0 Malaria p/Plasmodium ovale'),
  ('B531', 'Malária por plasmódios de macacos', 'B53.1 Malaria p/plasmodios de macacos'),
  ('B538', 'Outras formas de malárias com confirmação parasitológica, não classificadas em outra parte', 'B53.8 Outr form malarias c/conf parasitolog NCOP'),
  ('B54', 'Malária não especificada', 'B54 Malaria NE'),
  ('B54', 'Malária não especificada', 'B54 Malaria NE'),
  ('B55', 'Leishmaniose', 'B55 Leishmaniose'),
  ('B550', 'Leishmaniose visceral', 'B55.0 Leishmaniose visceral'),
  ('B551', 'Leishmaniose cutânea', 'B55.1 Leishmaniose cutanea'),
  ('B552', 'Leishmaniose cutâneo-mucosa', 'B55.2 Leishmaniose cutaneo-mucosa'),
  ('B559', 'Leishmaniose não especificada', 'B55.9 Leishmaniose NE'),
  ('B56', 'Tripanossomíase africana', 'B56 Tripanossomiase africana'),
  ('B560', 'Tripanossomíase por Trypanosoma gambiense', 'B56.0 Tripanossomiase p/Trypanosoma gambiense'),
  ('B561', 'Tripanossomíase por Trypanosoma rhodesiense', 'B56.1 Tripanossomiase p/Trypanosoma rhodesiense'),
  ('B569', 'Tripanossomíase africana não especificada', 'B56.9 Tripanossomiase africana NE'),
  ('B57', 'Doença de Chagas', 'B57 Doenc de Chagas'),
  ('B570', 'Forma aguda da doença de Chagas, com comprometimento cardíaco', 'B57.0 Form aguda doenc de Chagas c/compr cardiaco'),
  ('B571', 'Forma aguda da doença de Chagas, sem comprometimento cardíaco', 'B57.1 Form aguda doenc de Chagas s/compr cardiaco'),
  ('B572', 'Doença de Chagas (crônica) com comprometimento cardíaco', 'B57.2 Doenc de Chagas c/compr cardiaco'),
  ('B573', 'Doença de Chagas (crônica) com comprometimento do aparelho digestivo', 'B57.3 Doenc de Chagas c/compr aparelho digestivo'),
  ('B574', 'Doença de Chagas (crônica) com comprometimento do sistema nervoso', 'B57.4 Doenc de Chagas c/compr do sist nervoso'),
  ('B575', 'Doença de Chagas (crônica) com comprometimento de outros órgãos', 'B57.5 Doenc de Chagas c/compr de outr orgaos'),
  ('B58', 'Toxoplasmose', 'B58 Toxoplasmose'),
  ('B580', 'Oculopatia por Toxoplasma', 'B58.0 Oculopatia p/Toxoplasma'),
  ('B581', 'Hepatite por Toxoplasma', 'B58.1 Hepatite p/Toxoplasma'),
  ('B582', 'Meningoencefalite por Toxoplasma', 'B58.2 Meningoencefalite p/Toxoplasma'),
  ('B583', 'Toxoplasmose pulmonar', 'B58.3 Toxoplasmose pulmonar'),
  ('B588', 'Toxoplasmose com comprometimento de outros órgãos', 'B58.8 Toxoplasmose c/compr de outr orgaos'),
  ('B589', 'Toxoplasmose não especificada', 'B58.9 Toxoplasmose NE'),
  ('B59', 'Pneumocistose', 'B59 Pneumocistose'),
  ('B59', 'Pneumocistose', 'B59 Pneumocistose'),
  ('B60', 'Outras doenças devidas a protozoários, não classificadas em outra parte', 'B60 Outr doenc dev protozoarios NCOP'),
  ('B600', 'Babesiose', 'B60.0 Babesiose'),
  ('B601', 'Acantamebíase', 'B60.1 Acantamebiase'),
  ('B602', 'Naegleríase', 'B60.2 Naegleriase'),
  ('B608', 'Outras doenças especificadas devidas a protozoários', 'B60.8 Outr doenc espec dev protozoarios'),
  ('B64', 'Doença não especificada devida a protozoários', 'B64 Doenc NE dev protozoarios'),
  ('B64', 'Doença não especificada devida a protozoários', 'B64 Doenc NE dev protozoarios'),
  ('B65', 'Esquistossomose (bilharziose) (Schistosomíase)', 'B65 Esquistossomose'),
  ('B650', 'Esquistossomose devida ao Schistosoma haematobium (esquistossomose urinária)', 'B65.0 Esquistossomose dev Schistosoma haematobium'),
  ('B651', 'Esquistossomose devida ao Schistosoma mansoni (esquistossomose intestinal)', 'B65.1 Esquistossomose dev Schistosoma mansoni'),
  ('B652', 'Esquistossomose devida ao Schistosoma japonicum', 'B65.2 Esquistossomose dev Schistosoma japonicum'),
  ('B653', 'Dermatite por cercárias', 'B65.3 Dermatite p/cercarias'),
  ('B658', 'Outras esquistossomoses', 'B65.8 Outr esquistossomoses'),
  ('B659', 'Esquistossomose não especificada', 'B65.9 Esquistossomose NE'),
  ('B66', 'Outras infestações por trematódeos', 'B66 Outr infestacoes p/trematodeos'),
  ('B660', 'Opistorquíase', 'B66.0 Opistorquiase'),
  ('B661', 'Clonorquíase', 'B66.1 Clonorquiase'),
  ('B662', 'Dicrocelíase', 'B66.2 Dicroceliase'),
  ('B663', 'Fasciolíase', 'B66.3 Fascioliase'),
  ('B664', 'Paragonimíase', 'B66.4 Paragonimiase'),
  ('B665', 'Fasciolopsíase', 'B66.5 Fasciolopsiase'),
  ('B668', 'Outras infestações por trematódeos especificados', 'B66.8 Outr infestacoes p/trematodeos espec'),
  ('B669', 'Infecção não especificada por trematódeo', 'B66.9 Infecc NE p/trematodeo'),
  ('B67', 'Equinococose', 'B67 Equinococose'),
  ('B670', 'Infestação hepática por Echinococcus granulosus', 'B67.0 Infestacao hepatica p/E.granulosus'),
  ('B671', 'Infestação pulmonar por Echinococcus granulosus', 'B67.1 Infestacao pulmonar p/E.granulosus'),
  ('B672', 'Infestação óssea por Echinococcus granulosus', 'B67.2 Infestacao ossea p/Echinococcus granulosus'),
  ('B673', 'Infestações por Echinmococcus granulosus, outras e de localizações múltiplas', 'B67.3 Infestacoes p/E.granulosus outr e local mult'),
  ('B674', 'Infestação não especificada por Echinococcus granulosus', 'B67.4 Infestacao NE p/Echinococcus granulosus'),
  ('B675', 'Infestação hepática por Echinococcus multilocularis', 'B67.5 Infestacao hepatica p/E.multilocularis'),
  ('B676', 'Infecções por Echinococcus multilocularis, outras e de localizações múltiplas', 'B67.6 Infecc p/E.multilocularis outr e local mult'),
  ('B677', 'Infestação não especificada por Echinococcus multilocularis', 'B67.7 Infestacao NE p/Echinococcus multilocularis'),
  ('B678', 'Infestação hepática não especificada, por Echinococcus', 'B67.8 Infestacao hepatica NE p/Echinococcus'),
  ('B679', 'Infestações por Echinococcus, outras e as não especificadas', 'B67.9 Infestacoes p/Echinococcus outr e as NE'),
  ('B68', 'Infestação por Taenia', 'B68 Infestacao p/Taenia'),
  ('B680', 'Infestação por Taenia solium', 'B68.0 Infestacao p/Taenia solium'),
  ('B681', 'Infestação por Taenia saginata', 'B68.1 Infestacao p/Taenia saginata'),
  ('B689', 'Infestação não especificada por Taenia', 'B68.9 Infestacao NE p/Taenia'),
  ('B69', 'Cisticercose', 'B69 Cisticercose'),
  ('B690', 'Cisticercose do sistema nervoso central', 'B69.0 Cisticercose do sist nervoso central'),
  ('B691', 'Cisticercose do olho', 'B69.1 Cisticercose do olho'),
  ('B698', 'Cisticercose de outras localizações', 'B69.8 Cisticercose de outr localiz'),
  ('B699', 'Cisticercose não especificada', 'B69.9 Cisticercose NE'),
  ('B70', 'Difilobotríase e esparganose', 'B70 Difilobotriase e esparganose'),
  ('B700', 'Difilobotríase', 'B70.0 Difilobotriase'),
  ('B701', 'Esparganose', 'B70.1 Esparganose'),
  ('B71', 'Outras infestações por cestóides', 'B71 Outr infestacoes p/cestoides'),
  ('B710', 'Infestação por Hymenolepis', 'B71.0 Infestacao p/Hymenolepis'),
  ('B711', 'Infestação por Dipylidium', 'B71.1 Infestacao p/Dipylidium'),
  ('B718', 'Outras infestações especificadas por cestóides', 'B71.8 Outr infestacoes espec p/cestoides'),
  ('B719', 'Infestação não especificada por cestóides', 'B71.9 Infestacao NE p/cestoides'),
  ('B72', 'Dracontíase', 'B72 Dracontiase'),
  ('B72', 'Dracontíase', 'B72 Dracontiase'),
  ('B73', 'Oncocercose', 'B73 Oncocercose'),
  ('B73', 'Oncocercose', 'B73 Oncocercose'),
  ('B74', 'Filariose', 'B74 Filariose'),
  ('B740', 'Filariose por Wuchereria bancrofti', 'B74.0 Filariose p/Wuchereria bancrofti'),
  ('B741', 'Filariose por Brugia malayi', 'B74.1 Filariose p/Brugia malayi'),
  ('B742', 'Filariose por Brugia timori', 'B74.2 Filariose p/Brugia timori'),
  ('B743', 'Loaíase', 'B74.3 Loaiase'),
  ('B744', 'Mansonelose', 'B74.4 Mansonelose'),
  ('B748', 'Outras filarioses', 'B74.8 Outr filarioses'),
  ('B749', 'Filariose não especificada', 'B74.9 Filariose NE'),
  ('B75', 'Triquinose', 'B75 Triquinose'),
  ('B75', 'Triquinose', 'B75 Triquinose'),
  ('B76', 'Ancilostomíase', 'B76 Ancilostomiase'),
  ('B760', 'Ancilostomose', 'B76.0 Ancilostomose'),
  ('B761', 'Necatoríase', 'B76.1 Necatoriase'),
  ('B768', 'Outras ancilostomíases', 'B76.8 Outr ancilostomiases'),
  ('B769', 'Ancilostomíase não especificada', 'B76.9 Ancilostomiase NE'),
  ('B77', 'Ascaridíase', 'B77 Ascaridiase'),
  ('B770', 'Ascaridíase com complicações intestinais', 'B77.0 Ascaridiase c/complic intestinais'),
  ('B778', 'Ascaridíase com outras complicações', 'B77.8 Ascaridiase c/outr complic'),
  ('B779', 'Ascaridíase não especificada', 'B77.9 Ascaridiase NE'),
  ('B78', 'Estrongiloidíase', 'B78 Estrongiloidiase'),
  ('B780', 'Estrongiloidíase intestinal', 'B78.0 Estrongiloidiase intestinal'),
  ('B781', 'Estrongiloidíase cutânea', 'B78.1 Estrongiloidiase cutanea'),
  ('B787', 'Estrongiloidíase disseminada', 'B78.7 Estrongiloidiase disseminada'),
  ('B789', 'Estrongiloidíase não especificada', 'B78.9 Estrongiloidiase NE'),
  ('B79', 'Tricuríase', 'B79 Tricuriase'),
  ('B79', 'Tricuríase', 'B79 Tricuriase'),
  ('B80', 'Oxiuríase', 'B80 Oxiuriase'),
  ('B80', 'Oxiuríase', 'B80 Oxiuriase'),
  ('B81', 'Outras helmintíases intestinais, não classificadas em outra parte', 'B81 Outr helmintiases intestinais NCOP'),
  ('B810', 'Anisaquíase', 'B81.0 Anisaquiase'),
  ('B811', 'Capilaríase intestinal', 'B81.1 Capilariase intestinal'),
  ('B812', 'Tricostrongilose', 'B81.2 Tricostrongilose'),
  ('B813', 'Angiostrongilíase intestinal', 'B81.3 Angiostrongilíase intestinal'),
  ('B814', 'Helmintíases intestinais mistas', 'B81.4 Helmintiases intestinais mistas'),
  ('B818', 'Outras helmintíases intestinais especificadas', 'B81.8 Outr helmintiases intestinais espec'),
  ('B82', 'Parasitose intestinal não especificada', 'B82 Parasitose intestinal NE'),
  ('B820', 'Helmintíase intestinal não especificada', 'B82.0 Helmintiase intestinal NE'),
  ('B829', 'Parasitose intestinal não especificada', 'B82.9 Parasitose intestinal NE'),
  ('B83', 'Outras helmintíases', 'B83 Outr helmintiases'),
  ('B830', 'Larva migrans visceral', 'B83.0 Larva migrans visceral'),
  ('B831', 'Gnatostomíase', 'B83.1 Gnatostomiase'),
  ('B832', 'Angrostrongilíase devida a Parastrongylus cantonensis', 'B83.2 Angrostrongilíase dev P.cantonensis'),
  ('B833', 'Singamose', 'B83.3 Singamose'),
  ('B834', 'Hirudiníase interna', 'B83.4 Hirudiniase interna'),
  ('B838', 'Outras helmintíases especificadas', 'B83.8 Outr helmintiases espec'),
  ('B839', 'Helmintíase não especificada', 'B83.9 Helmintiase NE'),
  ('B85', 'Pediculose e ftiríase', 'B85 Pediculose e ftiriase'),
  ('B850', 'Pediculose devida a Pediculus humanus capitis', 'B85.0 Pediculose dev Pediculus humanus capitis'),
  ('B851', 'Pediculose devida a Pediculus humanus corporis', 'B85.1 Pediculose dev Pediculus humanus corporis'),
  ('B852', 'Pediculose não especificada', 'B85.2 Pediculose NE'),
  ('B853', 'Ftiríase', 'B85.3 Ftiriase'),
  ('B854', 'Pediculose e ftiríase mista', 'B85.4 Pediculose e ftiriase mista'),
  ('B86', 'Escabiose (sarna)', 'B86 Escabiose'),
  ('B86', 'Escabiose (sarna)', 'B86 Escabiose'),
  ('B87', 'Miíase', 'B87 Miiase'),
  ('B870', 'Miíase cutânea', 'B87.0 Miiase cutanea'),
  ('B871', 'Miíase das feridas', 'B87.1 Miiase das feridas'),
  ('B872', 'Miíase ocular', 'B87.2 Miiase ocular'),
  ('B873', 'Miíase nasofaríngea', 'B87.3 Miiase nasofaringea'),
  ('B874', 'Miíase auricular', 'B87.4 Miiase auricular'),
  ('B878', 'Miíase de outras localizações', 'B87.8 Miiase de outr localiz'),
  ('B879', 'Miíase não especificada', 'B87.9 Miiase NE'),
  ('B88', 'Outras infestações', 'B88 Outr infestacoes'),
  ('B880', 'Outras acaríases', 'B88.0 Outr acariases'),
  ('B881', 'Tungíase (infestação pela pulga da areia)', 'B88.1 Tungiase'),
  ('B882', 'Outras infestações por artrópodos', 'B88.2 Outr infestacoes p/artropodos'),
  ('B883', 'Hirudiníase externa', 'B88.3 Hirudiniase externa'),
  ('B888', 'Outras infestações especificadas', 'B88.8 Outr infestacoes espec'),
  ('B889', 'Infestação não especificada', 'B88.9 Infestacao NE'),
  ('B89', 'Doença parasitária não especificada', 'B89 Doenc parasit NE'),
  ('B89', 'Doença parasitária não especificada', 'B89 Doenc parasit NE'),
  ('B90', 'Seqüelas de tuberculose', 'B90 Sequelas de tuberc'),
  ('B900', 'Seqüelas de tuberculose do sistema nervoso central', 'B90.0 Sequelas de tuberc do sist nervoso central'),
  ('B901', 'Seqüelas de tuberculose geniturinária', 'B90.1 Sequelas de tuberc geniturinaria'),
  ('B902', 'Seqüelas de tuberculose óssea e das articulações', 'B90.2 Sequelas de tuberc ossea e das articulacoes'),
  ('B908', 'Seqüelas de tuberculose de outros órgãos', 'B90.8 Sequelas de tuberc de outr orgaos'),
  ('B909', 'Seqüelas de tuberculose das vias respiratórias e de órgãos não especificados', 'B90.9 Sequelas de tuberc vias respirat e orgaos NE'),
  ('B91', 'Seqüelas de poliomielite', 'B91 Sequelas de poliomielite'),
  ('B91', 'Seqüelas de poliomielite', 'B91 Sequelas de poliomielite'),
  ('B92', 'Seqüelas de hanseníase (lepra)', 'B92 Sequelas de hanseniase'),
  ('B92', 'Seqüelas de hanseníase (lepra)', 'B92 Sequelas de hanseniase'),
  ('B94', 'Seqüelas de outras doenças infecciosas e parasitárias e das não especificadas', 'B94 Sequelas de outr doenc infecc e parasit e NE'),
  ('B940', 'Seqüelas de tracoma', 'B94.0 Sequelas de tracoma'),
  ('B941', 'Seqüelas de encefalite viral', 'B94.1 Sequelas de encefalite viral'),
  ('B942', 'Seqüelas de hepatite viral', 'B94.2 Sequelas de hepatite viral'),
  ('B948', 'Seqüelas de outras doenças infecciosas e parasitárias especificadas', 'B94.8 Sequelas outr doenc infecc e parasit espec'),
  ('B949', 'Seqüelas de doença infecciosa ou parasitária não especificada', 'B94.9 Sequelas de doenc infecc ou parasit NE'),
  ('B95', 'Estreptococos e estafilococos como causa de doenças classificadas em outros capítulos', 'B95 Estr/estafilococo causa doenc class outr cap'),
  ('B950', 'Estreptococo do grupo A, como causa de doenças classificadas em outros capítulos', 'B95.0 Estreptoc grupo A causa doenc class outr cap'),
  ('B951', 'Estreptococo do grupo B, como causa de doenças classificadas em outros capítulos', 'B95.1 Estreptoc grupo B causa doenc class outr cap'),
  ('B952', 'Estreptococo do grupo D, como causa de doenças classificadas em outros capítulos', 'B95.2 Estreptoc grupo D causa doenc class outr cap'),
  ('B953', 'Streptococcus pneumoniae, como causa de doenças classificadas em outros capítulos', 'B95.3 S. pneumoniae causa doenc class outr cap'),
  ('B954', 'Outros estreptococos, como causa de doenças classificadas em outros capítulos', 'B95.4 Outr estreptococo causa doenc class outr cap'),
  ('B955', 'Estreptococo não especificado, como causa de doenças classificadas em outros capítulos', 'B95.5 Estreptococo NE causa doenc class outr cap'),
  ('B956', 'Staphylococcus aureus, como causa de doenças classificadas em outros capítulos', 'B95.6 S.aureus causa doenc class outr cap'),
  ('B957', 'Outros estafilococos como causa de doenças classificadas em outros capítulos', 'B95.7 Outr estafilococo causa doenc class outr cap'),
  ('B958', 'Estafilococo não especificado, como causa de doenças classificadas em outros capítulos', 'B95.8 Estafilococo NE causa doenc class outr cap'),
  ('B96', 'Outros agentes bacterianos, como causa de doenças classificadas em outros capítulos', 'B96 Outr agent bacter causa doenc class outr cap'),
  ('B960', 'Mycoplasma pneumoniae (M. pneumoniae), como causa de doenças classificadas em outros capítulos', 'B96.0 M.pneumoniae causa doenc class outr cap'),
  ('B961', 'Klebsiella pneumoniae (M. pneumoniae), como causa de doenças classificadas em outros capítulos', 'B96.1 K.pneumoniae como doenc class outr cap'),
  ('B962', 'Escherichia coli (E. Coli), como causa de doenças classificadas em outros capítulos', 'B96.2 Escherichia coli como doenc class outr cap'),
  ('B963', 'Haemophilus influenzae (H. influenzae), como causa de doenças classificadas em outros capítulos', 'B96.3 H.influenzae como doenc class outr cap'),
  ('B964', 'Proteus (mirabilis) (morganii), como causa de doenças classificadas em outros capítulos', 'B96.4 Proteus como doenc class outr cap'),
  ('B965', 'Pseudomonas (aeruginosa) (mallei) (pseudomallei), como causa de doenças classificadas em outros capítulos', 'B96.5 Pseudomonas como doenc class outr cap'),
  ('B966', 'Bacillus fragilis (B. fragilis), como causa de doenças classificadas em outros capítulos', 'B96.6 Bacillus fragilis como doenc class outr cap'),
  ('B967', 'Clostridium perfringens (C. perfringens), como causa de doenças classificadas em outros capítulos', 'B96.7 C.perfringens como doenc class outr cap'),
  ('B968', 'Outros agentes bacterianos especificados, como causa de doenças classificadas em outros capítulos', 'B96.8 Outr ag bact espec como doenc class outr cap'),
  ('B97', 'Vírus como causa de doenças classificadas em outros capítulos', 'B97 Virus como doenc class outr cap'),
  ('B970', 'Adenovírus, como causa de doenças classificadas em outros capítulos', 'B97.0 Adenovirus como doenc class outr cap'),
  ('B971', 'Enterovírus, como causa de doenças classificadas em outros capítulos', 'B97.1 Enterovirus como doenc class outr cap'),
  ('B972', 'Coronavírus, como causa de doenças classificadas em outros capítulos', 'B97.2 Coronavirus como doenc class outr cap'),
  ('B973', 'Retrovírus, como causa de doenças classificadas em outros capítulos', 'B97.3 Retrovirus como doenc class outr cap'),
  ('B974', 'Vírus sincicial respiratório, como causa de doenças classificadas em outros capítulos', 'B97.4 Virus sincic resp como doenc class outr cap'),
  ('B975', 'Reovírus, como causa de doenças classificadas em outros capítulos', 'B97.5 Reovirus como doenc class outr cap'),
  ('B976', 'Parvovírus, como causa de doenças classificadas em outros capítulos', 'B97.6 Parvovirus como doenc class outr cap'),
  ('B977', 'Papilomavírus, como causa de doenças classificadas em outros capítulos', 'B97.7 Papilomavirus como doenc class outr cap'),
  ('B978', 'Outros agentes virais, como causa de doenças classificadas em outros capítulos', 'B97.8 Outr agent virais como doenc class outr cap'),
  ('B99', 'Doenças infecciosas, outras e as não especificadas', 'B99 Doenc infecc outr e as NE'),
  ('B99', 'Doenças infecciosas, outras e as não especificadas', 'B99 Doenc infecc outr e as NE');
