INSERT INTO `icd10` (`code`, `description`, `abbr`) VALUES
  ('P00', 'Feto e recém-nascido afetados por afecções maternas, não obrigatoriamente relacionadas com a gravidez atual', 'P00 Fet rec-nasc afet afec mat n obr rel grav at'),
  ('P000', 'Feto e recém-nascido afetados por transtornos maternos hipertensivos', 'P00.0 Fet rec-nasc afet transt mat hipertensivos'),
  ('P001', 'Feto e recém-nascido afetados por doenças maternas renais e das vias urinárias', 'P00.1 Fet rec-nasc afet doenc mat renais vias urin'),
  ('P002', 'Feto e recém-nascido afetados por doenças infecciosas e parasitárias da mãe', 'P00.2 Fet rec-nasc afet doenc infecc parasit mae'),
  ('P003', 'Feto e recém-nascido afetados por outras doenças circulatórias e respiratórias maternas', 'P00.3 Fet rec-nasc afet outr doenc circ resp mat'),
  ('P004', 'Feto e recém-nascido afetados por transtornos nutricionais maternos', 'P00.4 Fet rec-nasc afet transt nutricionais matern'),
  ('P005', 'Feto e recém-nascido afetados por traumatismo materno', 'P00.5 Fet rec-nasc afetados p/traum materno'),
  ('P006', 'Feto e recém-nascido afetados por intervenção cirúrgica na mãe', 'P00.6 Fet rec-nasc afet intervencao cirurgica mae'),
  ('P007', 'Feto e recém-nascido afetados por outros procedimentos médicos na mãe, não classificados em outra parte', 'P00.7 Fet rec-nasc afet outr proced med mae NCOP'),
  ('P008', 'Feto e recém-nascido afetados por outras afecções maternas', 'P00.8 Fet rec-nasc afet outr afeccoes maternas'),
  ('P009', 'Feto e recém-nascido afetados por afecção materna não especificada', 'P00.9 Fet rec-nasc afetados p/afeccao materna NE'),
  ('P01', 'Feto e recém-nascido afetados por complicações maternas da gravidez', 'P01 Fet rec-nasc afet complic maternas gravidez'),
  ('P010', 'Feto e recém-nascido afetados por incompetência do colo uterino', 'P01.0 Fet rec-nasc afet incompetencia colo uterino'),
  ('P011', 'Feto e recém-nascido afetados por ruptura prematura das membranas', 'P01.1 Fet rec-nasc afet ruptura prematura membr'),
  ('P012', 'Feto e recém-nascido afetados por oligohidrâmnio', 'P01.2 Fet rec-nasc afetados p/oligohidramnio'),
  ('P013', 'Feto e recém-nascido afetados por polihidrâmnio', 'P01.3 Fet rec-nasc afetados p/polihidramnio'),
  ('P014', 'Feto e recém-nascido afetados por gravidez ectópica', 'P01.4 Fet rec-nasc afetados p/gravidez ectopica'),
  ('P015', 'Feto e recém-nascido afetados por gravidez múltipla', 'P01.5 Fet rec-nasc afetados p/gravidez mult'),
  ('P016', 'Feto e recém-nascido afetados por morte materna', 'P01.6 Fet rec-nasc afetados p/morte materna'),
  ('P017', 'Feto e recém-nascido afetados por apresentação anormal antes do trabalho de parto', 'P01.7 Fet rec-nasc afet apres anor antes trab part'),
  ('P018', 'Feto e recém-nascido afetados por outras complicações maternas da gravidez', 'P01.8 Fet rec-nasc afet outr complic mat gravidez'),
  ('P019', 'Feto e recém-nascido afetados por afecções maternas da gravidez, não especificadas', 'P01.9 Fet rec-nasc afet afecc maternas gravidez NE'),
  ('P02', 'Feto e recém-nascido afetados por complicações da placenta, do cordão umbilical e das membranas', 'P02 Fet rec-nasc afet compl plac cord umb membr'),
  ('P020', 'Feto e recém-nascido afetados por placenta prévia', 'P02.0 Fet rec-nasc afetados p/placenta previa'),
  ('P021', 'Feto e recém-nascido afetados por outras formas de descolamento da placenta e hemorragia', 'P02.1 Fet rec-nasc afet outr form desc plac hemorr'),
  ('P022', 'Feto e recém-nascido afetados por outras anormalidades morfológicas e funcionais da placenta e as não especificadas', 'P02.2 Fet rec-nasc afet out anor morf func plac NE'),
  ('P023', 'Feto e recém-nascido afetados por síndromes de transfusão placentária', 'P02.3 Fet rec-nasc afet sindr transf placentaria'),
  ('P024', 'Feto e recém-nascido afetados por prolapso de cordão umbilical', 'P02.4 Fet rec-nasc afet prolapso cordao umbilical'),
  ('P025', 'Feto e recém-nascido afetados por outras compressões do cordão umbilical', 'P02.5 Fet rec-nasc afet outr compr cord umbilical'),
  ('P026', 'Feto e recém-nascido afetados por outras afecções do cordão umbilical e as não especificadas', 'P02.6 Fet rec-nasc afet outr afecc cordao umb NE'),
  ('P027', 'Feto e recém-nascido afetados por corioamnionite', 'P02.7 Fet rec-nasc afetados p/corioamnionite'),
  ('P028', 'Feto e recém-nascido afetados por outras anormalidades das membranas', 'P02.8 Fet rec-nasc afet outr anorm membranas'),
  ('P029', 'Feto e recém-nascido afetados por anormalidade não especificada das membranas', 'P02.9 Fet rec-nasc afet anormalidade NE membranas'),
  ('P03', 'Feto e recém-nascido afetados por outras complicações do trabalho de parto e do parto', 'P03 Fet rec-nasc afet out compl trab parto parto'),
  ('P030', 'Feto e recém-nascido afetados por parto e extração pélvicas', 'P03.0 Fet rec-nasc afet parto e extracao pelvicas'),
  ('P031', 'Feto e recém-nascido afetados por outras apresentações anormais, má-posições e desproporções durante o trabalho de parto e o parto', 'P03.1 Fet rec-nasc afet out apres anor ma-pos desp'),
  ('P032', 'Feto e recém-nascido afetados por parto por fórceps', 'P03.2 Fet rec-nasc afetados p/parto p/forceps'),
  ('P033', 'Feto e recém-nascido afetados por parto por vácuo-extrator (ventosa)', 'P03.3 Fet rec-nasc afet parto p/vacuo-extrator'),
  ('P034', 'Feto e recém-nascido afetados por parto por cesariana', 'P03.4 Fet rec-nasc afetados p/parto p/cesariana'),
  ('P035', 'Feto e recém-nascido afetados por parto precipitado', 'P03.5 Fet rec-nasc afetados p/parto precipitado'),
  ('P036', 'Feto e recém-nascido afetados por contrações uterinas anormais', 'P03.6 Fet rec-nasc afet contracoes uterinas anorm'),
  ('P038', 'Feto e recém-nascido afetados por outras complicações especificadas do trabalho de parto e do parto', 'P03.8 Fet rec-nasc afet out comp esp trb part part'),
  ('P039', 'Feto e recém-nascido afetados por complicações não especificadas do trabalho de parto e do parto', 'P03.9 Fet rec-nasc afet compl NE trab parto parto'),
  ('P04', 'Feto e recém-nascido afetados por influências nocivas transmitidas ao feto via placenta ou leite materno', 'P04 Fet rec-nasc infl af noc trans plac leit mat'),
  ('P040', 'Feto e recém-nascido afetados por anestesia e analgesia materna durante a gravidez, trabalho de parto e parto', 'P04.0 Fet rec-nasc afet anest analg mat grav parto'),
  ('P041', 'Feto e recém-nascido afetados por outros medicamentos utilizados pela mãe', 'P04.1 Fet rec-nasc afet outr medic utiliz p/mae'),
  ('P042', 'Feto e recém-nascido afetados pelo uso de fumo pela mãe', 'P04.2 Fet rec-nasc afetados p/uso de fumo p/mae'),
  ('P043', 'Feto e recém-nascido afetados pelo uso de álcool pela mãe', 'P04.3 Fet rec-nasc afetados p/uso de alcool p/mae'),
  ('P044', 'Feto e recém-nascido afetados pelo uso de drogas que causam dependência pela mãe', 'P04.4 Fet rec-nasc afet uso drogaq causam dep mae'),
  ('P045', 'Feto e recém-nascido afetados por uso materno de substâncias químicas dos alimentos', 'P04.5 Fet rec-nasc afet uso mat subst quim aliment'),
  ('P046', 'Feto e recém-nascido afetados pela exposição da mãe a substâncias químicas do meio ambiente', 'P04.6 Fet rec-nasc afet exp mae subs quim meio amb'),
  ('P048', 'Feto e recém-nascido afetados por outras influências nocivas maternas', 'P04.8 Fet rec-nasc afet outr infl nocivas maternas'),
  ('P049', 'Feto e recém-nascido afetados por influências nocivas maternas não especificadas', 'P04.9 Fet rec-nasc afet infl nocivas maternas NE'),
  ('P05', 'Crescimento fetal retardado e desnutrição fetal', 'P05 Crescimento fetal retard e desnutric fetal'),
  ('P050', 'Recém-nascido de baixo peso para a idade gestacional', 'P05.0 Recem-nascido de baixo peso p/a idade gestac'),
  ('P051', 'Pequeno para a idade gestacional', 'P05.1 Pequeno p/a idade gestacional'),
  ('P052', 'Desnutrição fetal sem menção de peso e comprimento baixos para a idade gestacional', 'P05.2 Desnutr fet s/menc peso compr baix idad gest'),
  ('P059', 'Retardo não especificado do crescimento fetal', 'P05.9 Retardo NE do crescimento fetal'),
  ('P07', 'Transtornos relacionados com a gestação de curta duração e peso baixo ao nascer não classificados em outra parte', 'P07 Transt rel gest curt dur peso baix nasc NCOP'),
  ('P070', 'Recém-nascido com peso muito baixo', 'P07.0 Recem-nascido c/peso muito baixo'),
  ('P071', 'Outros recém-nascidos de peso baixo', 'P07.1 Outr recem-nascidos de peso baixo'),
  ('P072', 'Imaturidade extrema', 'P07.2 Imaturidade extrema'),
  ('P073', 'Outros recém-nascidos de pré-termo', 'P07.3 Outr recem-nascidos de pre-termo'),
  ('P08', 'Transtornos relacionados com a gestação prolongada e peso elevado ao nascer', 'P08 Transt relac gest prolong peso elevado nasc'),
  ('P080', 'Recém-nascido de tamanho excessivamente grande', 'P08.0 Recem-nascido tamanho excessivamente grande'),
  ('P081', 'Outros recém-nascidos grandes para a idade gestacional', 'P08.1 Outr recem-nascidos grandes p/a idade gestac'),
  ('P082', 'Recém-nascido pós-termo, não-grande para a idade gestacional', 'P08.2 Recem-nasc pos-termo n-grande idade gest'),
  ('P10', 'Laceração intracraniana e hemorragia devidas a traumatismo de parto', 'P10 Laceracao intracran hemorrag dev traum parto'),
  ('P100', 'Hemorragia subdural devida a traumatismo de parto', 'P10.0 Hemorragia subdural dev traum de parto'),
  ('P101', 'Hemorragia cerebral devida a traumatismo de parto', 'P10.1 Hemorragia cerebral dev traum de parto'),
  ('P102', 'Hemorragia intraventricular devida a traumatismo de parto', 'P10.2 Hemorragia intraventricular dev traum parto'),
  ('P103', 'Hemorragia subaracnoídea devida a traumatismo de parto', 'P10.3 Hemorragia subaracnoidea dev traum de parto'),
  ('P104', 'Ruptura tentorial devida a traumatismo de parto', 'P10.4 Ruptura tentorial dev traum de parto'),
  ('P108', 'Outras lacerações e hemorragias intracranianas devidas a traumatismo de parto', 'P10.8 Outr lacerac hemorr intracr dev traum parto'),
  ('P109', 'Laceração e hemorragia intracranianas não especificadas devidas a traumatismo de parto', 'P10.9 Lacerac hemorr intracran NE dev traum parto'),
  ('P11', 'Outros traumatismos de parto do sistema nervoso central', 'P11 Outr traum de parto do sist nervoso central'),
  ('P110', 'Edema cerebral devido a traumatismo de parto', 'P11.0 Edema cerebral dev traum de parto'),
  ('P111', 'Outras lesões cerebrais especificadas devidas a traumatismo de parto', 'P11.1 Outr lesoes cerebrais espec dev traum parto'),
  ('P112', 'Lesão cerebral não especificada devida a traumatismo de parto', 'P11.2 Lesao cerebral NE dev traum de parto'),
  ('P113', 'Traumatismo de parto do nervo facial', 'P11.3 Traum de parto do nervo facial'),
  ('P114', 'Traumatismo de parto de outros nervos cranianos', 'P11.4 Traum de parto de outr nervos cranianos'),
  ('P115', 'Traumatismo de parto da coluna e da medula espinhal', 'P11.5 Traum de parto da coluna e medula espinhal'),
  ('P119', 'Traumatismo de parto não especificado do sistema nervoso central', 'P11.9 Traum de parto NE do sist nervoso central'),
  ('P12', 'Lesão do couro cabeludo devida a traumatismo de parto', 'P12 Lesao do couro cabeludo dev traum de parto'),
  ('P120', 'Céfalo-hematoma devido a traumatismo de parto', 'P12.0 Cefalo-hematoma dev traum de parto'),
  ('P121', 'Chignon devido a traumatismo de parto', 'P12.1 Chignon dev traum de parto'),
  ('P122', 'Hemorragia subaponeurótica epicraniana devida a traumatismo de parto', 'P12.2 Hemorrag subaponeur epicran dev traum parto'),
  ('P123', 'Esmagamento do couro cabeludo devido a traumatismo de parto', 'P12.3 Esmag couro cabeludo dev traum parto'),
  ('P124', 'Lesão por monitorização do couro cabeludo do recém-nascido', 'P12.4 Lesao p/monitoriz couro cabeludo rec-nasc'),
  ('P128', 'Outras lesões do couro cabeludo devidas a traumatismo de parto', 'P12.8 Outr lesoes couro cabeludo dev traum parto'),
  ('P129', 'Lesão não especificada do couro cabeludo devida a traumatismo de parto', 'P12.9 Lesao NE do couro cabeludo dev traum parto'),
  ('P13', 'Lesões do esqueleto devidas a traumatismo de parto', 'P13 Lesoes do esqueleto dev traum de parto'),
  ('P130', 'Fratura de crânio devida a traumatismo de parto', 'P13.0 Frat de cranio dev traum de parto'),
  ('P131', 'Outras lesões cranianas devidas a traumatismo de parto', 'P13.1 Outr lesoes cranianas dev traum de parto'),
  ('P132', 'Lesão do fêmur devida a traumatismo de parto', 'P13.2 Lesao do femur dev traum de parto'),
  ('P133', 'Lesão de outros ossos longos devida a traumatismo de parto', 'P13.3 Lesao de outr ossos longos dev traum parto'),
  ('P134', 'Fratura da clavícula devida a traumatismo de parto', 'P13.4 Frat da clavicula dev traum de parto'),
  ('P138', 'Lesões de outras partes do esqueleto devidas a traumatismo de parto', 'P13.8 Lesoes outr partes esqueleto dev traum parto'),
  ('P139', 'Lesões não especificadas do esqueleto devidas a traumatismo de parto', 'P13.9 Lesoes NE do esqueleto dev traum de parto'),
  ('P14', 'Lesões ao nascer do sistema nervoso periférico', 'P14 Lesoes ao nascer do sist nervoso periferico'),
  ('P140', 'Paralisia de Erb devida a traumatismo de parto', 'P14.0 Paralisia de Erb dev traum de parto'),
  ('P141', 'Paralisia de Klumpke devida a traumatismo de parto', 'P14.1 Paralisia de Klumpke dev traum de parto'),
  ('P142', 'Paralisia do nervo frênico devida a traumatismo de parto', 'P14.2 Paralisia do nervo frenico dev traum parto'),
  ('P143', 'Outras lesões do plexo braquial devidas a traumatismo de parto', 'P14.3 Outr lesoes plexo braquial dev traum parto'),
  ('P148', 'Outras lesões de outras partes do sistema nervoso periférico devidas a traumatismo de parto', 'P14.8 Out les out part sist nerv perif traum parto'),
  ('P149', 'Lesão não especificada do sistema nervoso periférico devida a traumatismo de parto', 'P14.9 Lesao NE sist nerv perif dev traum de parto'),
  ('P15', 'Outros traumatismos de parto', 'P15 Outr traum de parto'),
  ('P150', 'Lesão do fígado devida a traumatismo de parto', 'P15.0 Lesao do figado dev traum de parto'),
  ('P151', 'Lesão do baço devida a traumatismo de parto', 'P15.1 Lesao do baco dev traum de parto'),
  ('P152', 'Lesão do esternomastóide devida a traumatismo de parto', 'P15.2 Lesao do esternomastoide dev traum de parto'),
  ('P153', 'Lesão dos olhos devida a traumatismo de parto', 'P15.3 Lesao dos olhos dev traum de parto'),
  ('P154', 'Lesão da face ao nascer', 'P15.4 Lesao da face ao nascer'),
  ('P155', 'Lesão dos órgãos genitais externos, devida a traumatismo de parto', 'P15.5 Lesao org genitais externos dev traum parto'),
  ('P156', 'Necrose de gordura subcutânea devida a traumatismo de parto', 'P15.6 Necrose gordura subcutanea dev traum parto'),
  ('P158', 'Outros traumatismos de parto especificados', 'P15.8 Outr traum de parto espec'),
  ('P159', 'Traumatismo de parto não especificado', 'P15.9 Traum de parto NE'),
  ('P20', 'Hipóxia intra-uterina', 'P20 Hipoxia intra-uterina'),
  ('P200', 'Hipóxia intra-uterina diagnosticada antes do início do trabalho de parto', 'P20.0 Hipoxia intra-uter diagn ant inic trab parto'),
  ('P201', 'Hipóxia intra-uterina diagnosticada durante o trabalho de parto e o parto', 'P20.1 Hipoxia intra-uter diagn dur trab parto part'),
  ('P209', 'Hipóxia intra-uterina não especificada', 'P20.9 Hipoxia intra-uterina NE'),
  ('P21', 'Asfixia ao nascer', 'P21 Asfixia ao nascer'),
  ('P210', 'Asfixia grave ao nascer', 'P21.0 Asfixia grave ao nascer'),
  ('P211', 'Asfixia leve ou moderada ao nascer', 'P21.1 Asfixia leve ou moderada ao nascer'),
  ('P219', 'Asfixia ao nascer, não especificada', 'P21.9 Asfixia ao nascer NE'),
  ('P22', 'Desconforto (angústia) respiratório(a) do recém-nascido', 'P22 Desconforto respirat do recem-nascido'),
  ('P220', 'Síndrome da angústia respiratória do recém-nascido', 'P22.0 Sindr da angustia respirat do recem-nascido'),
  ('P221', 'Taquipnéia transitória do recém-nascido', 'P22.1 Taquipneia transitoria do recem-nascido'),
  ('P228', 'Outros desconfortos respiratórios do recém-nascido', 'P22.8 Outr desconfortos respirat do recem-nascido'),
  ('P229', 'Desconforto respiratório não especificado do recém-nascido', 'P22.9 Desconforto respirat NE do recem-nascido'),
  ('P23', 'Pneumonia congênita', 'P23 Pneumonia congen'),
  ('P230', 'Pneumonia congênita devida a agente viral', 'P23.0 Pneumonia congen dev agente viral'),
  ('P231', 'Pneumonia congênita devida a Clamídia', 'P23.1 Pneumonia congen dev Clamidia'),
  ('P232', 'Pneumonia congênita devida a estafilococo', 'P23.2 Pneumonia congen dev estafilococo'),
  ('P233', 'Pneumonia congênita devida a estreptococo do grupo B', 'P23.3 Pneumonia congen dev estreptococo do grupo B'),
  ('P234', 'Pneumonia congênita devida a Escherichia coli', 'P23.4 Pneumonia congen dev Escherichia coli'),
  ('P235', 'Pneumonia congênita devida a Pseudomonas', 'P23.5 Pneumonia congen dev a Pseudomonas'),
  ('P236', 'Pneumonia congênita devida a outros agentes bacterianos', 'P23.6 Pneumonia congen dev outr agentes bacter'),
  ('P238', 'Pneumonia congênita devida a outros organismos', 'P23.8 Pneumonia congen dev outr organismos'),
  ('P239', 'Pneumonia congênita não especificada', 'P23.9 Pneumonia congen NE'),
  ('P24', 'Síndrome de aspiração neonatal', 'P24 Sindr de aspiracao neonatal'),
  ('P240', 'Aspiração neonatal de mecônio', 'P24.0 Aspiracao neonatal de meconio'),
  ('P241', 'Aspiração neonatal de líquido amniótico e muco', 'P24.1 Aspiracao neonatal liquido amniotico e muco'),
  ('P242', 'Aspiração neonatal de sangue', 'P24.2 Aspiracao neonatal de sangue'),
  ('P243', 'Aspiração neonatal de leite e alimento regurgitados', 'P24.3 Aspiracao neonatal leite alimento regurgit'),
  ('P248', 'Outras síndromes de aspiração neonatais', 'P24.8 Outr sindr de aspiracao neonatais'),
  ('P249', 'Síndrome de aspiração neonatal não especificada', 'P24.9 Sindr de aspiracao neonatal NE'),
  ('P25', 'Enfisema intersticial e afecções correlatas originadas no período perinatal', 'P25 Enfisema interst afecc corr orig per perinat'),
  ('P250', 'Enfisema intersticial originado no período perinatal', 'P25.0 Enfisema interst originado periodo perinatal'),
  ('P251', 'Pneumotórax originado no período perinatal', 'P25.1 Pneumotorax originado no periodo perinatal'),
  ('P252', 'Pneumomediastino originado no período perinatal', 'P25.2 Pneumomediastino originado periodo perinatal'),
  ('P253', 'Pneumopericárdio originado no período perinatal', 'P25.3 Pneumopericardio originado periodo perinatal'),
  ('P258', 'Outras afecções relacionadas com o enfisema intersticial originadas no período perinatal', 'P25.8 Out afec rel enfis interst orig per perinat'),
  ('P26', 'Hemorragia pulmonar originada no período perinatal', 'P26 Hemorragia pulmonar orig periodo perinatal'),
  ('P260', 'Hemorragia traqueobrônquica originada no período perinatal', 'P26.0 Hemorragia traqueobronq orig periodo perinat'),
  ('P261', 'Hemorragia pulmonar maciça originada no período perinatal', 'P26.1 Hemorragia pulm macica orig periodo perinat'),
  ('P268', 'Outras hemorragias pulmonares originadas no período perinatal', 'P26.8 Outr hemorragias pulm orig periodo perinat'),
  ('P269', 'Hemorragia pulmonar não especificada originada no período perinatal', 'P26.9 Hemorragia pulmonar NE orig periodo perinat'),
  ('P27', 'Doença respiratória crônica originada no período perinatal', 'P27 Doenc respirat cron orig periodo perinatal'),
  ('P270', 'Síndrome de Wilson-Mikity', 'P27.0 Sindr de Wilson-Mikity'),
  ('P271', 'Displasia broncopulmonar originada no período perinatal', 'P27.1 Displasia broncopulm orig periodo perinatal'),
  ('P278', 'Outras doenças respiratórias crônicas originadas no período perinatal', 'P27.8 Outr doenc respirat cron orig per perinatal'),
  ('P279', 'Doença respiratória crônica não especificada originada no período perinatal', 'P27.9 Doenc respirat cronica NE orig per perinatal'),
  ('P28', 'Outras afecções respiratórias originadas no período perinatal', 'P28 Outr afeccoes respirat orig per perinatal'),
  ('P280', 'Atelectasia primária do recém-nascido', 'P28.0 Atelectasia prim do recem-nascido'),
  ('P281', 'Outras atelectasias do recém-nascido e as não especificadas', 'P28.1 Outr atelectasias do recem-nascido e as NE'),
  ('P282', 'Crises cianóticas do recém-nascido', 'P28.2 Crises cianoticas do recem-nascido'),
  ('P283', 'Apnéia primária do sono do recém-nascido', 'P28.3 Apneia prim do sono do recem-nascido'),
  ('P284', 'Outras apnéias do recém-nascido', 'P28.4 Outr apneias do recem-nascido'),
  ('P285', 'Insuficiência respiratória do recém-nascido', 'P28.5 Insuf respirat do recem-nascido'),
  ('P288', 'Outras afecções respiratórias especificadas do recém-nascido', 'P28.8 Outr afeccoes respirat espec do recem-nasc'),
  ('P289', 'Afecção respiratória do recém-nascido, não especificada', 'P28.9 Afeccao respirat do recem-nascido NE'),
  ('P29', 'Transtornos cardiovasculares originados no período perinatal', 'P29 Transt cardiovasc orig periodo perinatal'),
  ('P290', 'Insuficiência cardíaca neonatal', 'P29.0 Insuf cardiaca neonatal'),
  ('P291', 'Disritmia cardíaca neonatal', 'P29.1 Disritmia cardiaca neonatal'),
  ('P292', 'Hipertensão neonatal', 'P29.2 Hipertensao neonatal'),
  ('P293', 'Persistência da circulação fetal', 'P29.3 Persistencia da circulacao fetal'),
  ('P294', 'Isquemia miocárdica transitória do recém-nascido', 'P29.4 Isquemia miocardica transitoria recem-nasc'),
  ('P298', 'Outros transtornos cardiovasculares originados no período perinatal', 'P29.8 Outr transt cardiovasc orig periodo perinat'),
  ('P299', 'Transtornos cardiovasculares não especificados originados no período perinatal', 'P29.9 Transt cardiovasc NE orig periodo perinatal'),
  ('P35', 'Doenças virais congênitas', 'P35 Doenc virais congen'),
  ('P350', 'Síndrome da rubéola congênita', 'P35.0 Sindr da rubeola congen'),
  ('P351', 'Infecção congênita por citomegalovirus', 'P35.1 Infecc congen p/citomegalovirus'),
  ('P352', 'Infecção congênita por vírus do herpes (simples)', 'P35.2 Infecc congen p/virus do herpes'),
  ('P353', 'Hepatite viral congênita', 'P35.3 Hepatite viral congen'),
  ('P358', 'Outras doenças virais congênitas', 'P35.8 Outr doenc virais congen'),
  ('P359', 'Doença viral congênita não especificada', 'P35.9 Doenc viral congen NE'),
  ('P36', 'Septicemia bacteriana do recém-nascido', 'P36 Septicemia bacter do recem-nascido'),
  ('P360', 'Septicemia do recém-nascido devida a estreptococo do grupo B', 'P36.0 Septicemia rec-nasc dev estreptococo grupo B'),
  ('P361', 'Septicemia do recém-nascido devida a outros estreptococos e aos não especificados', 'P36.1 Septicemia rec-nasc dev outr estreptoc e NE'),
  ('P362', 'Septicemia do recém-nascido devida ao Stafilococcus aureus', 'P36.2 Septicemia rec-nasc dev Stafilococcus aureus'),
  ('P363', 'Septicemia do recém-nascido devida a outros estafilococos e aos não especificados', 'P36.3 Septicemia rec-nasc dev outr estafiloc e NE'),
  ('P364', 'Septicemia do recém-nascido devida a Escherichia coli', 'P36.4 Septicemia recem-nasc dev Escherichia coli'),
  ('P365', 'Septicemia do recém-nascido devida a anaeróbios', 'P36.5 Septicemia do recem-nascido dev anaerobios'),
  ('P368', 'Outras septicemias bacterianas do recém-nascido', 'P36.8 Outr septicemias bacter do recem-nascido'),
  ('P369', 'Septicemia bacteriana não especificada do recém-nascido', 'P36.9 Septicemia bacter NE do recem-nascido'),
  ('P37', 'Outras doenças infecciosas e parasitárias congênitas', 'P37 Outr doenc infecc e parasit congen'),
  ('P370', 'Tuberculose congênita', 'P37.0 Tuberc congen'),
  ('P371', 'Toxoplasmose congênita', 'P37.1 Toxoplasmose congen'),
  ('P372', 'Listeriose neonatal (disseminada)', 'P37.2 Listeriose neonatal'),
  ('P373', 'Malária falciparum congênita', 'P37.3 Malaria falciparum congen'),
  ('P374', 'Outras malárias congênitas', 'P37.4 Outr malarias congen'),
  ('P375', 'Candidíase neonatal', 'P37.5 Candidiase neonatal'),
  ('P378', 'Outras doenças infecciosas e parasitárias congênitas especificadas', 'P37.8 Outr doenc infecc e parasit congen espec'),
  ('P379', 'Doença infecciosa ou parasitária congênita não especificada', 'P37.9 Doenc infecc ou parasit congen NE'),
  ('P38', 'Onfalite do recém-nascido com ou sem hemorragia leve', 'P38 Onfalite recem-nasc c/ou s/hemorragia leve'),
  ('P38', 'Onfalite do recém-nascido com ou sem hemorragia leve', 'P38 Onfalite recem-nasc c/ou s/hemorragia leve'),
  ('P39', 'Outras infecções específicas do período perinatal', 'P39 Outr infecc especificas do periodo perinatal'),
  ('P390', 'Mastite infecciosa neonatal', 'P39.0 Mastite infecc neonatal'),
  ('P391', 'Conjuntivite e dacriocistite neonatais', 'P39.1 Conjuntivite e dacriocistite neonatais'),
  ('P392', 'Infecção intra-amniótica do feto não classificada em outra parte', 'P39.2 Infecc intra-amniotica do feto NCOP'),
  ('P393', 'Infecção neonatal do trato urinário', 'P39.3 Infecc neonatal do trato urinario'),
  ('P394', 'Infecção neonatal da pele', 'P39.4 Infecc neonatal da pele'),
  ('P398', 'Outras infecções especificadas próprias do período perinatal', 'P39.8 Outr infecc espec proprias periodo perinatal'),
  ('P399', 'Infecção própria do período perinatal não especificada', 'P39.9 Infecc propria do periodo perinatal NE'),
  ('P50', 'Perda sangüínea fetal', 'P50 Perda sanguinea fetal'),
  ('P500', 'Perda sangüínea fetal devida a vasa prévia', 'P50.0 Perda sanguinea fetal dev vasa previa'),
  ('P501', 'Perda sangüínea fetal por ruptura do cordão', 'P50.1 Perda sanguinea fetal p/ruptura do cordao'),
  ('P502', 'Perda sangüínea fetal originada da placenta', 'P50.2 Perda sanguinea fetal originada da placenta'),
  ('P503', 'Hemorragia para a circulação do outro gêmeo', 'P50.3 Hemorragia p/a circulacao do outr gemeo'),
  ('P504', 'Hemorragia para a circulação materna', 'P50.4 Hemorragia p/a circulacao materna'),
  ('P505', 'Perda sangüínea devido a secção do cordão umbilical do outro gemelar', 'P50.5 Perda sang dev seccao cord umb outr gemelar'),
  ('P508', 'Outras perdas sangüíneas fetais', 'P50.8 Outr perdas sanguineas fetais'),
  ('P509', 'Perda sangüínea fetal não especificada', 'P50.9 Perda sanguinea fetal NE'),
  ('P51', 'Hemorragia umbilical do recém-nascido', 'P51 Hemorragia umbilical do recem-nascido'),
  ('P510', 'Hemorragia umbilical maciça do recém-nascido', 'P51.0 Hemorragia umbilical macica do recem-nascido'),
  ('P518', 'Outras hemorragias umbilicais do recém-nascido', 'P51.8 Outr hemorragias umbilicais do recem-nascido'),
  ('P519', 'Hemorragia umbilical do recém-nascido, não especificada', 'P51.9 Hemorragia umbilical do recem-nascido NE'),
  ('P52', 'Hemorragia intracraniana não-traumática do feto e do recém-nascido', 'P52 Hemorragia intracran nao-traum feto rec-nasc'),
  ('P520', 'Hemorragia intraventricular (não-traumática) grau 1, do feto e do recém-nascido', 'P52.0 Hemorragia intraventr grau 1 feto rec-nasc'),
  ('P521', 'Hemorragia intraventricular (não-traumática) grau 2, do feto e do recém-nascido', 'P52.1 Hemorragia intraventr grau 2 feto rec-nasc'),
  ('P522', 'Hemorragia intraventricular (não-traumática) grau 3, do feto e do recém-nascido', 'P52.2 Hemorragia intraventr grau 3 feto rec-nasc'),
  ('P523', 'Hemorragia intraventricular (não-traumática) não especificada, do feto ou do recém-nascido', 'P52.3 Hemorragia intraventr NE feto recem-nascido'),
  ('P524', 'Hemorragia intracerebral (não-traumática) do feto e do recém-nascido', 'P52.4 Hemorragia intracerebr feto e recem-nascido'),
  ('P525', 'Hemorragia subaracnoídea (não-traumática) do feto e do recém-nascido', 'P52.5 Hemorragia subaracnoidea feto recem-nascido'),
  ('P526', 'Hemorragia cerebelar (não-traumática) e da fossa posterior do feto ou recém-nascido', 'P52.6 Hemorr cerebel fossa posterior feto rec-nasc'),
  ('P528', 'Outras hemorragias intracranianas (não-traumáticas) do feto e do recém-nascido', 'P52.8 Outr hemorrag intracranianas feto rec-nasc'),
  ('P529', 'Hemorragia intracraniana (não-traumática) do feto e do recém-nascido, não especificada', 'P52.9 Hemorragia intracraniana feto recem-nasc NE'),
  ('P53', 'Doença hemorrágica do feto e do recém-nascido', 'P53 Doenc hemorragica do feto e do recem-nascido'),
  ('P53', 'Doença hemorrágica do feto e do recém-nascido', 'P53 Doenc hemorragica do feto e do recem-nascido'),
  ('P54', 'Outras hemorragias neonatais', 'P54 Outr hemorragias neonatais'),
  ('P540', 'Hematêmese neonatal', 'P54.0 Hematemese neonatal'),
  ('P541', 'Melena neonatal', 'P54.1 Melena neonatal'),
  ('P542', 'Hemorragia retal neonatal', 'P54.2 Hemorragia retal neonatal'),
  ('P543', 'Outras hemorragias gastrointestinais do período neonatal', 'P54.3 Outr hemorrag gastrointest periodo neonatal'),
  ('P544', 'Hemorragia supra-renal neonatal', 'P54.4 Hemorragia supra-renal neonatal'),
  ('P545', 'Hemorragia cutânea neonatal', 'P54.5 Hemorragia cutanea neonatal'),
  ('P546', 'Hemorragia vaginal neonatal', 'P54.6 Hemorragia vaginal neonatal'),
  ('P548', 'Outras hemorragias fetais e neonatais especificadas', 'P54.8 Outr hemorragias fetais e neonatais espec'),
  ('P549', 'Hemorragia fetal e neonatal não especificada', 'P54.9 Hemorragia fetal e neonatal NE'),
  ('P55', 'Doença hemolítica do feto e do recém-nascido', 'P55 Doenc hemolitica do feto e do recem-nascido'),
  ('P550', 'Isoimunização Rh do feto e do recém-nascido', 'P55.0 Isoimunizacao Rh do feto e do recem-nascido'),
  ('P551', 'Isoimunização ABO do feto e do recém-nascido', 'P55.1 Isoimunizacao ABO do feto e do recem-nascido'),
  ('P558', 'Outras doenças hemolíticas do feto e do recém-nascido', 'P55.8 Outr doenc hemoliticas feto e recem-nascido'),
  ('P559', 'Doença hemolítica não especificada do feto e do recém-nascido', 'P55.9 Doenc hemolitica NE do feto e recem-nascido'),
  ('P56', 'Hidropsia fetal devida a doença hemolítica', 'P56 Hidropsia fetal dev doenc hemolitica'),
  ('P560', 'Hidropsia fetal devida à isoimunização', 'P56.0 Hidropsia fetal dev isoimunizacao'),
  ('P569', 'Hidropsia fetal devida a outras doenças hemolíticas e às não especificadas', 'P56.9 Hidropsia fetal dev outr doenc hemolit e NE'),
  ('P57', 'Kernicterus', 'P57 Kernicterus'),
  ('P570', 'Kernicterus devido à isoimunização', 'P57.0 Kernicterus dev isoimunizacao'),
  ('P578', 'Outros kernicterus especificados', 'P57.8 Outr kernicterus espec'),
  ('P579', 'Kernicterus não especificado', 'P57.9 Kernicterus NE'),
  ('P58', 'Icterícia neonatal devida a outras hemólises excessivas', 'P58 Ictericia neonatal dev outr hemolises excess'),
  ('P580', 'Icterícia neonatal devida a contusões', 'P58.0 Ictericia neonatal dev contusoes'),
  ('P581', 'Icterícia neonatal devida a sangramento', 'P58.1 Ictericia neonatal dev sangramento'),
  ('P582', 'Icterícia neonatal devida a infecção', 'P58.2 Ictericia neonatal dev infecc'),
  ('P583', 'Icterícia neonatal devida a policitemia', 'P58.3 Ictericia neonatal dev policitemia'),
  ('P584', 'Icterícia neonatal devida a drogas ou toxinas transmitidas pela mãe ou administradas ao recém-nascido', 'P58.4 Icter neonat drog tox trans mae adm rec-nasc'),
  ('P585', 'Icterícia neonatal devida à deglutação de sangue materno', 'P58.5 Ictericia neonatal dev deglutacao sang mat'),
  ('P588', 'Icterícia neonatal devida a outras hemólises excessivas especificadas', 'P58.8 Icter neonat dev outr hemolises excess espec'),
  ('P589', 'Icterícia neonatal devida a hemólise excessiva não especificada', 'P58.9 Ictericia neonatal dev hemolise excessiva NE'),
  ('P59', 'Icterícia neonatal devida a outras causas e às não especificadas', 'P59 Ictericia neonatal dev outr causas e as NE'),
  ('P590', 'Icterícia neonatal associada ao parto prematuro', 'P59.0 Ictericia neonatal assoc ao parto prematuro'),
  ('P591', 'Síndrome da bile espessa', 'P59.1 Sindr da bile espessa'),
  ('P592', 'Icterícia neonatal de outras lesões hepatocelulares e das não especificadas', 'P59.2 Ictericia neonat outr lesoes hepatocel e NE'),
  ('P593', 'Icterícia neonatal devida a inibidores do leite materno', 'P59.3 Ictericia neonatal dev inibidores leite mat'),
  ('P598', 'Icterícia neonatal devida a outras causas especificadas', 'P59.8 Ictericia neonatal dev outr causas espec'),
  ('P599', 'Icterícia neonatal não especificada', 'P59.9 Ictericia neonatal NE'),
  ('P60', 'Coagulação intravascular disseminada do feto e do recém-nascido', 'P60 Coagulacao intravasc dissem feto rec-nasc'),
  ('P60', 'Coagulação intravascular disseminada do feto e do recém-nascido', 'P60 Coagulacao intravasc dissem feto rec-nasc'),
  ('P61', 'Outros transtornos hematológicos perinatais', 'P61 Outr transt hematologicos perinatais'),
  ('P610', 'Trombocitopenia transitória neonatal', 'P61.0 Trombocitopenia transitoria neonatal'),
  ('P611', 'Policitemia neonatal', 'P61.1 Policitemia neonatal'),
  ('P612', 'Anemia da prematuridade', 'P61.2 Anemia da prematuridade'),
  ('P613', 'Anemia congênita por perda sangüínea fetal', 'P61.3 Anemia congen p/perda sanguinea fetal'),
  ('P614', 'Outras anemias congênitas não classificada em outra parte', 'P61.4 Outr anemias congen NCOP'),
  ('P615', 'Neutropenia transitória neonatal', 'P61.5 Neutropenia transitoria neonatal'),
  ('P616', 'Outros transtornos transitórios de coagulação do período neonatal', 'P61.6 Outr transt transit coag periodo neonatal'),
  ('P618', 'Outros transtornos hematológicos perinatais especificados', 'P61.8 Outr transt hematologicos perinatais espec'),
  ('P619', 'Transtorno hematológico perinatal não especificado', 'P61.9 Transt hematologico perinatal NE'),
  ('P70', 'Transtornos transitórios do metabolismo dos carboidratos específicos do feto e do recém-nascido', 'P70 Trans transit metab carboid esp fet rec-nasc'),
  ('P700', 'Síndrome do filho de mãe com diabetes gestacional', 'P70.0 Sindr do filho de mae c/diabetes gestacional'),
  ('P701', 'Síndrome do filho de mãe diabética', 'P70.1 Sindr do filho de mae diabetica'),
  ('P702', 'Diabetes mellitus neonatal', 'P70.2 Diabetes mellitus neonatal'),
  ('P703', 'Hipoglicemia neonatal iatrogênica', 'P70.3 Hipoglicemia neonatal iatrogenica'),
  ('P704', 'Outras hipoglicemias neonatais', 'P70.4 Outr hipoglicemias neonatais'),
  ('P708', 'Outros transtornos transitórios do metabolismo dos carboidratos do feto e do recém-nascido', 'P70.8 Out trans transit metab carboid fet rec-nasc'),
  ('P709', 'Transtorno transitório não especificado do metabolismo dos carboidratos do feto e do recém-nascido', 'P70.9 Trans transit NE metab carboidr fet rec-nasc'),
  ('P71', 'Transtornos transitórios do metabolismo do cálcio e do magnésio do período neonatal', 'P71 Transt transit metab calcio magn per neonat'),
  ('P710', 'Hipocalcemia do recém-nascido pelo uso de leite de vaca', 'P71.0 Hipocalcemia recem-nascido p/uso leite vaca'),
  ('P711', 'Outras hipocalcemias neonatais', 'P71.1 Outr hipocalcemias neonatais'),
  ('P712', 'Hipomagnesemia neonatal', 'P71.2 Hipomagnesemia neonatal'),
  ('P713', 'Tetania neonatal sem deficiência de cálcio ou magnésio', 'P71.3 Tetania neonatal s/defic de calcio magnesio'),
  ('P714', 'Hipoparatiroidismo neonatal transitório', 'P71.4 Hipoparatiroidismo neonatal transitorio'),
  ('P718', 'Outros transtornos transitórios do metabolismo do cálcio e do magnésio do período neonatal', 'P71.8 Out trans transit metab calc magn per neonat'),
  ('P719', 'Transtornos transitórios não especificados do metabolismo do cálcio e do magnésio do período neonatal', 'P71.9 Transt transit NE metab calc magn per neonat'),
  ('P72', 'Outros transtornos endócrinos transitórios do período neonatal', 'P72 Outr transt endocrinos transit period neonat'),
  ('P720', 'Bócio neonatal, não classificado em outra parte', 'P72.0 Bocio neonatal NCOP'),
  ('P721', 'Hipotireoidismo neonatal transitório', 'P72.1 Hipotireoidismo neonatal transitorio'),
  ('P722', 'Outros transtornos transitórios da função de tireóide não classificados em outra parte', 'P72.2 Outr transt transit funcao de tireoide NCOP'),
  ('P728', 'Outros transtornos endócrinos transitórios e especificados do período neonatal', 'P72.8 Outr transt endocr transit espec per neonat'),
  ('P729', 'Transtorno endócrino neonatal transitório não especificado', 'P72.9 Transt endocrino neonatal transitorio NE'),
  ('P74', 'Outros distúrbios eletrolíticos e metabólicos transitórios do período neonatal', 'P74 Outr dist eletrolit metab transit per neonat'),
  ('P740', 'Acidose metabólica tardia do recém-nascido', 'P74.0 Acidose metabolica tard do recem-nascido'),
  ('P741', 'Desidratação do recém-nascido', 'P74.1 Desidratacao do recem-nascido'),
  ('P742', 'Distúrbios do equilíbrio de sódio do recém-nascido', 'P74.2 Disturbios equilibrio sodio recem-nascido'),
  ('P743', 'Distúrbios do equilíbrio de potássio do recém-nascido', 'P74.3 Disturbios equilibrio potassio recem-nascido'),
  ('P744', 'Outros distúrbios eletrolíticos transitórios do recém-nascido', 'P74.4 Outr dist eletroliticos transit recem-nasc'),
  ('P745', 'Tirosinemia transitória do recém-nascido', 'P74.5 Tirosinemia transitoria do recem-nascido'),
  ('P748', 'Outros distúrbios metabólicos transitórios do recém-nascido', 'P74.8 Outr disturbios metabolicos transit rec-nasc'),
  ('P749', 'Distúrbio metabólico transitório não especificado do recém-nascido', 'P74.9 Disturbio metabolico transitorio NE rec-nasc'),
  ('P75', 'Íleo meconial', 'P75 Ileo meconial'),
  ('P75', 'Íleo meconial', 'P75 Ileo meconial'),
  ('P76', 'Outras obstruções intestinais do recém-nascido', 'P76 Outr obstrucoes intestinais do recem-nascido'),
  ('P760', 'Síndrome da rolha de mecônio', 'P76.0 Sindr da rolha de meconio'),
  ('P761', 'Íleo transitório do recém-nascido', 'P76.1 Ileo transitorio do recem-nascido'),
  ('P762', 'Obstrução intestinal devido a leite espesso', 'P76.2 Obstrucao intestinal dev leite espesso'),
  ('P768', 'Outras obstruções intestinais especificadas do recém-nascido', 'P76.8 Outr obstrucoes intestinais espec rec-nasc'),
  ('P769', 'Obstrução intestinal não especificada do recém-nascido', 'P76.9 Obstrucao intestinal NE do recem-nascido'),
  ('P77', 'Enterocolite necrotizante do feto e do recém-nascido', 'P77 Enterocolite necrotizante do feto e rec-nasc'),
  ('P77', 'Enterocolite necrotizante do feto e do recém-nascido', 'P77 Enterocolite necrotizante do feto e rec-nasc'),
  ('P78', 'Outros transtornos do aparelho digestivo do período perinatal', 'P78 Outr transt ap digestivo periodo perinatal'),
  ('P780', 'Perfuração intestinal no período perinatal', 'P78.0 Perfuracao intestinal no periodo perinatal'),
  ('P781', 'Outras peritonites neonatais', 'P78.1 Outr peritonites neonatais'),
  ('P782', 'Hematemese e melena devidas a deglutição de sangue materno', 'P78.2 Hematemese melena dev degluticao sangue mat'),
  ('P783', 'Diarréia neonatal não-infecciosa', 'P78.3 Diarreia neonatal nao-infecc'),
  ('P788', 'Outros transtornos perinatais especificados do aparelho digestivo', 'P78.8 Outr transt perinatais espec ap digestivo'),
  ('P789', 'Transtorno perinatal não especificado do aparelho digestivo', 'P78.9 Transt perinatal NE do aparelho digestivo'),
  ('P80', 'Hipotermia do recém-nascido', 'P80 Hipotermia do recem-nascido'),
  ('P800', 'Síndrome de lesão pelo frio', 'P80.0 Sindr de lesao p/frio'),
  ('P808', 'Outras hipotermias do recém-nascido', 'P80.8 Outr hipotermias do recem-nascido'),
  ('P809', 'Hipotermia não especificada do recém-nascido', 'P80.9 Hipotermia NE do recem-nascido'),
  ('P81', 'Outros distúrbios da regulação térmica do recém-nascido', 'P81 Outr disturbios regulacao termica rec-nasc'),
  ('P810', 'Hipertermia ambiental do recém-nascido', 'P81.0 Hipertermia ambiental do recem-nascido'),
  ('P818', 'Outros distúrbios especificados da regulação térmica do recém-nascido', 'P81.8 Outr disturb espec regulacao term rec-nasc'),
  ('P819', 'Distúrbio não especificado da regulação térmica do recém-nascido', 'P81.9 Disturbio NE regulacao termica recem-nascido'),
  ('P83', 'Outras afecções comprometendo o tegumento específicas do feto e do recém-nascido', 'P83 Outr afecc compr tegum espec feto rec-nasc'),
  ('P830', 'Esclerema neonatal', 'P83.0 Esclerema neonatal'),
  ('P831', 'Eritema tóxico neonatal', 'P83.1 Eritema toxico neonatal'),
  ('P832', 'Hidropsia fetal não-devida à doença hemolítica', 'P83.2 Hidropsia fetal nao-dev doenc hemolitica'),
  ('P833', 'Outros edemas e os não especificados próprios do feto e do recém-nascido', 'P83.3 Outr edemas e NE proprios feto recem-nascido'),
  ('P834', 'Intumescimento mamário do recém-nascido', 'P83.4 Intumescimento mamario do recem-nascido'),
  ('P835', 'Hidrocele congênita', 'P83.5 Hidrocele congen'),
  ('P836', 'Pólipo umbilical do recém-nascido', 'P83.6 Polipo umbilical do recem-nascido'),
  ('P838', 'Outras afecções especificadas do tegumento próprias do feto e do recém-nascido', 'P83.8 Outr afecc espec tegum propr feto rec-nasc'),
  ('P839', 'Afecção não especificada do tegumento própria do feto e do recém-nascido', 'P83.9 Afeccao NE tegumento propria feto rec-nasc'),
  ('P90', 'Convulsões do recém-nascido', 'P90 Convulsoes do recem-nascido'),
  ('P90', 'Convulsões do recém-nascido', 'P90 Convulsoes do recem-nascido'),
  ('P91', 'Outros distúrbios da função cerebral do recém-nascido', 'P91 Outr disturbios funcao cerebral rec-nasc'),
  ('P910', 'Isquemia cerebral neonatal', 'P91.0 Isquemia cerebral neonatal'),
  ('P911', 'Cistos periventriculares adquiridos do recém-nascido', 'P91.1 Cistos periventriculares adquir rec-nasc'),
  ('P912', 'Leucomalácia cerebral neonatal', 'P91.2 Leucomalacia cerebral neonatal'),
  ('P913', 'Irritabilidade cerebral neonatal', 'P91.3 Irritabilidade cerebral neonatal'),
  ('P914', 'Depressão cerebral neonatal', 'P91.4 Depressao cerebral neonatal'),
  ('P915', 'Coma neonatal', 'P91.5 Coma neonatal'),
  ('P916', 'Encefalopatia hipóxico-isquêmica do recém-nascido', 'P91.6 Encefalopatia hipóxico-isquêmica recém-nasc'),
  ('P918', 'Outros distúrbios especificados da função cerebral do recém-nascido', 'P91.8 Outr disturbios espec funcao cerebr rec-nasc'),
  ('P919', 'Distúrbio não especificado da função cerebral do recém-nascido', 'P91.9 Disturbio NE da funcao cerebral rec-nasc'),
  ('P92', 'Problemas de alimentação do recém-nascido', 'P92 Problemas de alimentacao do recem-nascido'),
  ('P920', 'Vômitos no recém-nascido', 'P92.0 Vomitos no recem-nascido'),
  ('P921', 'Regurgitação e ruminação no recém-nascido', 'P92.1 Regurgitacao e ruminacao no recem-nascido'),
  ('P922', 'Alimentação vagarosa do recém-nascido', 'P92.2 Alimentacao vagarosa do recem-nascido'),
  ('P923', 'Subalimentação do recém-nascido', 'P92.3 Subalimentacao do recem-nascido'),
  ('P924', 'Hiperalimentação do recém-nascido', 'P92.4 Hiperalimentacao do recem-nascido'),
  ('P925', 'Dificuldade neonatal na amamentação no peito', 'P92.5 Dificuldade neonatal na amamentacao no peito'),
  ('P928', 'Outros problemas de alimentação do recém-nascido', 'P92.8 Outr problemas de alimentacao recem-nascido'),
  ('P929', 'Problema não especificado de alimentação do recém-nascido', 'P92.9 Problema NE de alimentacao do recem-nascido'),
  ('P93', 'Reações e intoxicações devidas a drogas administradas ao feto e ao recém-nascido', 'P93 Reacoes e intox dev drog admin feto rec-nasc'),
  ('P93', 'Reações e intoxicações devidas a drogas administradas ao feto e ao recém-nascido', 'P93 Reacoes e intox dev drog admin feto rec-nasc'),
  ('P94', 'Transtornos do tônus muscular do recém-nascido', 'P94 Transt do tonus muscular do recem-nascido'),
  ('P940', 'Miastenia grave neonatal transitória', 'P94.0 Miastenia grave neonatal transitoria'),
  ('P941', 'Hipertonia congênita', 'P94.1 Hipertonia congen'),
  ('P942', 'Hipotonia congênita', 'P94.2 Hipotonia congen'),
  ('P948', 'Outros transtornos do tônus muscular do recém-nascido', 'P94.8 Outr transt do tonus muscular recem-nascido'),
  ('P949', 'Transtorno não especificado do tônus muscular do recém-nascido', 'P94.9 Transt NE do tonus muscular do recem-nascido'),
  ('P95', 'Morte fetal de causa não especificada', 'P95 Morte fetal de causa NE'),
  ('P95', 'Morte fetal de causa não especificada', 'P95 Morte fetal de causa NE'),
  ('P96', 'Outras afecções originadas no período perinatal', 'P96 Outr afeccoes originadas periodo perinatal'),
  ('P960', 'Insuficiência renal congênita', 'P96.0 Insuf renal congen'),
  ('P961', 'Sintomas de abstinência neonatal de drogas utilizadas pela mãe', 'P96.1 Sint abstinencia neonatal drog utiliz p/mae'),
  ('P962', 'Sintomas de abstinência do uso de drogas terapêuticas no recém-nascido', 'P96.2 Sint abstinencia uso drogas terap rec-nasc'),
  ('P963', 'Suturas cranianas amplas no recém-nascido', 'P96.3 Suturas cranianas amplas no recem-nascido'),
  ('P964', 'Interrupção de gravidez, afetando o feto e recém-nascido', 'P96.4 Interrupcao de gravidez afet feto rec-nasc'),
  ('P965', 'Complicações de procedimentos intra-uterinos não classificados em outra parte', 'P96.5 Complic de proced intra-uterinos NCOP'),
  ('P968', 'Outras afecções especificadas originadas no período perinatal', 'P96.8 Outr afeccoes espec orig periodo perinatal'),
  ('P969', 'Afecções originadas no período perinatal não especificadas', 'P96.9 Afeccoes originadas no periodo perinatal NE');
